### ISSUE TITLE
[Feature][Plugin] Add Plugin Flink Sink Elasticsearch

### ISSUE THREAD

**Issue by chaozwn** [apache/seatunnel#1065]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

support seatunnel connector to Elasticsearch Sink.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Elasticsearch changed the license, maybe we should consider not supporting it anymore.

**Comment by baisui1981** [comment]
> Elasticsearch changed the license, maybe we should consider not supporting it anymore.

so regret
