### ISSUE TITLE
[Feature]Support rate limit

### ISSUE THREAD

**Issue by melin** [apache/seatunnel#1082]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Reading and writing the rds database needs to limit traffic to avoid affecting database performance

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Can you describe this requirement in detail?
Sprak or Flink both provide corresponding parameters, is this what you are talking about?

**Comment by melin** [comment]
> Can you describe this requirement in detail? Sprak or Flink both provide corresponding parameters, is this what you are talking about?


For example, when synchronizing data from mysql into hive, I hope to control the speed of reading mysql data, and read up to 100 rows per second to avoid affecting business operations.

The write data speed also needs to be controllable.

ratelimit is an important requirement for data synchronization tools

**Comment by EricJoy2048** [comment]
> > Can you describe this requirement in detail? Sprak or Flink both provide corresponding parameters, is this what you are talking about?
> 
> For example, when synchronizing data from mysql into hive, I hope to control the speed of reading mysql data, and read up to 100 rows per second to avoid affecting business operations.
> 
> The write data speed also needs to be controllable.
> 
> ratelimit is an important requirement for data synchronization tools

Yes, I think we need speed controllable too. Do you have some ideas?

**Comment by hailin0** [comment]
Consider the following implementation ideas

```
env {
    read_limit.rows_per_second = xxx
    read_limit.bytes_per_second = xxx

}

source {
...
}

sink {
...
}
```

Apply this config to execution engine (spark/flink/zeta)

**Comment by PainAshura** [comment]
@hailin0 hey! I am curious if this new feature is being developed or is it being discussed. Or even not going to consider it.
