### ISSUE TITLE
[License Issue] Please update your source codes' license

### ISSUE THREAD

**Issue by wu-sheng** [apache/seatunnel#1100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I accidentally noticed this PR, https://github.com/apache/incubator-seatunnel/pull/912/files#diff-a0275ef336fd0cf14c3d4c026ce3e918301dc0cf7b2663fbf484d9cff5288bd2, which carried the dependency license check script into your source codes. And the same style of `known-dependencies.txt` file, which was created by SkyWalking.

But you should know, this script is coming(copied) from [Apache SkyWalking](https://github.com/apache/skywalking/blob/master/tools/dependencies/check-LICENSE.sh), which was written by one PMC member. And I noticed this script was not submitted by himself(he still owns this file). This file's owner has reviewed this PR, but I think he missed this. Unless he is the one to submit, the License should be taken care of.

So, you should update the source codes' LICENSE to indicate you have copied it from another project. 

FYI @CalvinKirs @zhongjiajie

### SeaTunnel Version

The dev branch

### SeaTunnel Config

```conf
No need.
```

### Running Command

```shell
No need.
```

### Error Exception

```log
No need.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Thanks for the reminder, I'll deal with this asap.
