### ISSUE TITLE
[Feature][Plugin] Add spark ignite connector

### ISSUE THREAD

**Issue by zixi0825** [apache/seatunnel#1127]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add spark ignite connector

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kyle-cx91** [comment]
hi zixi @zixi0825 , will u start to work on this again?  if u don't mind, I'd like to continue basis on u

**Comment by zixi0825** [comment]
> hi zixi @zixi0825 , will u start to work on this again? if u don't mind, I'd like to continue basis on u

I will restart it in this week.

**Comment by kyle-cx91** [comment]
> > hi zixi @zixi0825 , will u start to work on this again? if u don't mind, I'd like to continue basis on u
> 
> I will restart it in this week.

great

**Comment by crystanlan1** [comment]
您好！我想找您合格项目，方便联系吗
