### ISSUE TITLE
[Feature][api] Translate seatunnel-api-spark module's scala code to java

### ISSUE THREAD

**Issue by yx91490** [apache/seatunnel#1142]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Translate seatunnel-api-spark module's scala code to java,  follow the uncomplete job https://github.com/apache/incubator-seatunnel/pull/742

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
@huzk8 do you want to continue this job?

**Comment by TyrantLucifer** [comment]
I want to try it.

**Comment by yx91490** [comment]
> I want to try it.

I don't have permission to assign, you can ask @CalvinKirs @RickyHuo for help.

**Comment by TyrantLucifer** [comment]
According to the problem I met in this requirement, spark-streaming api whether it is necessary do version unification. Currently spark-streaming api is scala version but other base apis are java version. If do version unification is necessary, other spark-streaming connectors also need be rewrited from scala to java. What do you think about it? @yx91490  @CalvinKirs

**Comment by CalvinKirs** [comment]
> According to the problem I met in this requirement, spark-streaming api whether it is necessary do version unification. Currently spark-streaming api is scala version but other base apis are java version. If do version unification is necessary, other spark-streaming connectors also need be rewrited from scala to java. What do you think about it? @yx91490 @CalvinKirs

It is best to use java for this, and for plug-in modules, you can use scala or java

**Comment by TyrantLucifer** [comment]
> > According to the problem I met in this requirement, spark-streaming api whether it is necessary do version unification. Currently spark-streaming api is scala version but other base apis are java version. If do version unification is necessary, other spark-streaming connectors also need be rewrited from scala to java. What do you think about it? @yx91490 @CalvinKirs
> 
> It is best to use java for this, and for plug-in modules, you can use scala or java

Because of the spark-streaming difference between scala and java, for example in scala a spark steam is DStream, but in java a spark stream is JavaDStream, if you want to develop spark-streaming connectors it must do version unification between apis and plugins.

**Comment by yx91490** [comment]
closed by https://github.com/apache/incubator-seatunnel/pull/1188

**Comment by TyrantLucifer** [comment]
Hi @CalvinKirs, for now, only the spark streaming apis are in Scala.  Do we still need to convert the base spark streaming apis? If necessary, we also need to convert all spark streaming connectors from scala to java. If not, this issue can be closed. What's your opinion?😋
