### ISSUE TITLE
[Feature][Spark] Add remote debug for spark job

### ISSUE THREAD

**Issue by legendtkl** [apache/seatunnel#1161]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

For troubleshooting, debug is necessary. 

I want to remotely debug Spark job driver (started by seatunnel) with args like this "spark.driver.extraJavaOptions = "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"". It does not work.

Following the `start-seatunnel-spark.sh` code, I found the driver java options are combined by cli args `--variable`.
```shell
-i|--variable)
      variable=$2
      is_exist ${variable}
      java_property_value="-D${variable}"
      variables_substitution="${java_property_value} ${variables_substitution}"
      shift 2
      ;;
```
But the '-D' prefix make it not work for debug arg `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005`.

So is that possible to support remote debugging with a new cli arg as follows:
```shell
    -p|--debug-port)
      debug_port=$2
      is_exist ${debug_port}
      variables_substitution="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=${debug_port} ${variables_substitution}"
      shift 2
      ;;
```

Thanks.
Kelu.

### Usage Scenario

Remote debug

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
you can specify spark's related configurations in config file's env part (dev branch).

**Comment by legendtkl** [comment]
Hi, @yx91490 , I tried in your way. Unfortunately, it does not work.

The conf:
```text
env {
  # seatunnel defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "seatunnel"
  spark.ui.port = 13000
  spark.driver.extraJavaOptions = "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
}

source {
  socketStream {}
}

transform {
  split {
    fields = ["msg", "name"]
    delimiter = ","
  }
}

sink {
  console {}
}
```

**Comment by yx91490** [comment]
> you can specify spark's related configurations in config file's env part (dev branch).

since https://github.com/apache/incubator-seatunnel/pull/1486 was merged, you can retry this way on latest dev branch.
