### ISSUE TITLE
从hive写入到MySQL，提交任务后一直无法写入到mysql中

### ISSUE THREAD

**Issue by allenchen0314** [apache/seatunnel#1180]
![image](https://user-images.githubusercontent.com/81660436/151362241-03b530d1-71f3-4b6b-abb2-568cc1f2aeb0.png)

**Comment by wuchunfu** [comment]
Please use English description for the title, thanks

**Comment by allenchen0314** [comment]
> Please use English description for the title, thanks
this is my conf file ,and data can not from hive to mysql
![image](https://user-images.githubusercontent.com/81660436/151385329-d67345db-1db7-4623-b9e8-22da655d5189.png)

**Comment by allenchen0314** [comment]
> Please use English description for the title, thanks
data cannot from hive to mysql ,below is  my conf file
![image](https://user-images.githubusercontent.com/81660436/151477606-2740e756-5b23-40fc-8bbe-fe6aae2b7ede.png)

**Comment by CalvinKirs** [comment]
For better communication, please use English. I will close this issue, you can reopen it when you update your Issue Title.
