### ISSUE TITLE
[Feature][flink] flink source, sink supports parallelism parameters 

### ISSUE THREAD

**Issue by bigdataf** [apache/seatunnel#1191]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The flink source sink plugin supports parallel parameters 

### Usage Scenario

The flink source sink plugin supports parallel parameters 

### Related issues

not found yet 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaodayu1209** [comment]
I am interested in implementing this task

**Comment by Hisoka-X** [comment]
Is any update now?

**Comment by bigdataf** [comment]
I think this optimization item is a long-term process, you can see what needs to be improved and you can participate in it, thank you

**Comment by Hisoka-X** [comment]
We can make this come true both spark and flink side. Make it become common parameters.

**Comment by Hisoka-X** [comment]
Can we start  to do this? @CalvinKirs

**Comment by CalvinKirs** [comment]
> Can we start to do this? @CalvinKirs

Since the author claimed this task, but a month has passed and there is still no news, so you can take over this if you are interested.

**Comment by Hisoka-X** [comment]
> > Can we start to do this? @CalvinKirs
> 
> Since the author claimed this task, but a month has passed and there is still no news, so you can take over this if you are interested.

Yes

**Comment by Hisoka-X** [comment]
Already Done.
