### ISSUE TITLE
[Feature][connectors] Will seatunnel support Apache Pulsar as a streaming source

### ISSUE THREAD

**Issue by lnn1988** [apache/seatunnel#1197]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Will seatunnel support Apache Pulsar as a streaming source? or any plan about it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
If you are interested in this, contributions are welcome.

**Comment by TyrantLucifer** [comment]
I want to try it.
