### ISSUE TITLE
[Feature][ci] Increase the building time of ci action

### ISSUE THREAD

**Issue by xleoken** [apache/seatunnel#1202]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We use `30min` as the timeout of the building, it seems not enough for building.

![image](https://user-images.githubusercontent.com/95013770/152898971-34c8b562-534e-463f-8924-3dc61ee55abe.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Under normal circumstances, it should be completed in 30 minutes, and there is no point in waiting for more than 30 minutes.

**Comment by xleoken** [comment]
> Under normal circumstances, it should be completed in 30 minutes, and there is no point in waiting for more than 30 minutes.

@CalvinKirs, seems the network of the github action is unstable.

![image](https://user-images.githubusercontent.com/95013770/152938191-6264fc82-1d27-4210-b46c-29274b203e4b.png)

_Originally posted by @leo65535 in https://github.com/apache/incubator-seatunnel/issues/1205#issuecomment-1032290488_

**Comment by xleoken** [comment]
Closing this issue temporarily, open it when necessary in the future.
