### ISSUE TITLE
[Feature][CI] Automatically generate LICENSE

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1209]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We should support automatic generation of LICENSE file to improve efficiency and accuracy.

## Background

As we all know, the SeaTunnel is a high-performance Data Integration Platform that supports efficient data transformation and transfer between heterogeneous data sources. Therefore, it is inevitable to introduce many third-party dependencies. Therefore, there is also a problem, which is, with more and more third-party components, it will be a very labor-intensive process to manually maintain LICENSE. At the same time, newbies need to learn this LICENSE mechanism, which also increases the entry threshold for newbies. Therefore, this document will introduce a way to automatically generate the LICENSE file.

## Requirement

After preliminary research, some basic requirements have been sorted out:

1. It needs to be implemented in a scripting language to facilitate understanding and maintenance;
2. It can be integrated with the existing Maven build process;
3. It should support Github Action to trigger automatically.

### Version v1.0

The easiest way is to generate a temporary `THIRD-PARTY.txt` through Maven's `license-maven-plugin` plugin. Then through the Python script, the LICENSE file is automatically parsed and created.

![](https://user-images.githubusercontent.com/8108788/153120592-0752c894-7e5e-4ddc-b9c5-1adc36de7dee.png)

### Version v2.0

Further through Maven's exec-maven-plugin plug-in, it supports one-click triggering by using Maven.

![](https://user-images.githubusercontent.com/8108788/153120620-38435a4c-712d-42e1-9250-12c4953ad42b.png)

### Version v3.0

Going a step further, we can integrate with Github Action. When a new PR is created, if the dependency changes, Github Action automatically modifies the LICENSE, and creates a commit to submit it to the new PR. In this way, when contributing new plug-ins, users do not need to understand the LICENSE mechanism, all of which are automatically modified, which greatly reduces the threshold for newbies.

![](https://user-images.githubusercontent.com/8108788/153120647-d038c1d9-63de-4101-a9a9-1e1550f7e642.png)

## Conclusion

Currently I have created the [#1210](https://github.com/apache/incubator-seatunnel/pull/1210) PR, which has completed versions v1.0 and v2.0, we need to discuss whether v3.0 needs to be implemented at this stage. And then we can implement v3.0 in a follow-up PR if necessary. Any comments are welcome, thank you very much.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Good job flow and describe 👍
