### ISSUE TITLE
[Feature][core] rewrite most components of seatunnel start script with java

### ISSUE THREAD

**Issue by yx91490** [apache/seatunnel#1218]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

It's difficult to write shell in right way, in `start-seatunnel-spark.sh` we can seem it is too difficult to extract  'env' conf to concat the final spark-submit command. so I want to rewrite most components of seatunnel start script with java.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
I want to try it. Could you please assign it to me?

**Comment by TyrantLucifer** [comment]
Well, it sounds a great job. I think I can participate in this module.

**Comment by yx91490** [comment]
> Well, it sounds a great job. I think I can participate in this module.

I can finish this task by myself, if I need help I will call you, thanks.
