### ISSUE TITLE
Seatunnel v2.x version is available?

### ISSUE THREAD

**Issue by tmljob** [apache/seatunnel#1224]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Seatunnel v2.x version is available? How to download and deply it?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
see this: https://github.com/apache/incubator-seatunnel/releases/tag/v2.0.4

**Comment by tmljob** [comment]
Thanks
