### ISSUE TITLE
[Feature][ci] Rerun failed step for the backend Github action

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1257]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Sometimes, the `Build and Package` step in the `backend` Github Action may be pending, the reason may be that the Github Action is unstable due to the network. So, we should add a timeout option for the step and rerun the failed step for it to improve the sucess rate. If it is working, we may need generialize this to other Github Action jobs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
closed. discuss on #1258
