### ISSUE TITLE
[Feature][core] Support spark/flink engine internally

### ISSUE THREAD

**Issue by xleoken** [apache/seatunnel#1285]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When deploying seatunnel job, we need install spark/flink environment first. I think we need new mechanism to let spark/flink build in.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
I want to do this, can you asigned to me?

**Comment by xleoken** [comment]
Welcome @yx91490 ~

**Comment by yx91490** [comment]
I have some discussions about the desgin:

1. suppose that most enterprise users have alread deployed their spark or flink, therefor we should integrate spark/flink optionally.
2. if we choose integrate spark/flink, the artifact package will be bigger,  maybe twice than ever, is this acceptable？
3. If we download spark/flink, I don't known is it allowed by asf?

wish your reply, thanks.
