### ISSUE TITLE
[Bug] [ci] seatunnel-dist: Failed to create assembly

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

This problem does not happen all the time, and there is a chance that the following error will be reported. And, after the second try, it was normal again. At the beginning, I encoutered this on my own env, so I though it could caused by env affects. Until now, it happened in the Github Action.

![image](https://user-images.githubusercontent.com/8108788/154696518-94c83213-859a-45c9-9bf9-ef1ab74eb52e.png)

### SeaTunnel Version

The latest (2.0.5-SNAPSHOT)

### SeaTunnel Config

```conf
N/A
```

### Running Command

```shell
N/A
```

### Error Exception

```log
N/A
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by asdf2014** [comment]
FYI, the failed Github Action job: https://github.com/apache/incubator-seatunnel/runs/5248257243?check_suite_focus=true

**Comment by Hisoka-X** [comment]
Use docker to reproduce this bug will be helpful.
