### ISSUE TITLE
[chore] Polish error logging and expose exception stack

### ISSUE THREAD

**Issue by kezhenxu94** [apache/seatunnel#1291]
consider using this so that the exception stack can be exposed

```suggestion
            LOG.error("IotDbInputFormat couldn't be closed", e);
```

_Originally posted by @kezhenxu94 in https://github.com/apache/incubator-seatunnel/pull/1289#discussion_r810031682_

**Comment by hjdokr** [comment]
global replacement?

**Comment by hjdokr** [comment]
Can i try it?

**Comment by CalvinKirs** [comment]
> global replacement?

It's best. looking forward you submit PR.

**Comment by nielifeng** [comment]
> Can i try it?

looking forward you submit PR.

**Comment by asdf2014** [comment]
Hi @hjdokr, so glad you can handle this :+1:

**Comment by dshunter107** [comment]
Hello. Was this ever done?

**Comment by kezhenxu94** [comment]
half a year passed, I don't think there would be any progress, anyone who wants to do this is welcome

**Comment by Zhenye-Na** [comment]
I am working on this small code change, could you assign this issue to me?

Also, I am not able to find `seatunnel-connectors/seatunnel-connector-flink-iotdb/src/main/java/org/apache/seatunnel/flink/source/IotDbInputFormat.java`. Is this file still in the `seatunnel` repo ?

Would you mind pointing me to the new file location ?

Thanks

**Comment by kezhenxu94** [comment]
> I am working on this small code change, could you assign this issue to me?

Please directly send a pull request.

> Also, I am not able to find `seatunnel-connectors/seatunnel-connector-flink-iotdb/src/main/java/org/apache/seatunnel/flink/source/IotDbInputFormat.java`. Is this file still in the `seatunnel` repo ?
> 
> Would you mind pointing me to the new file location ?

If the file is not in the repo, simply ignore it and change the existing ones.

**Comment by Zhenye-Na** [comment]
> > I am working on this small code change, could you assign this issue to me?
> 
> Please directly send a pull request.
> 
> > Also, I am not able to find `seatunnel-connectors/seatunnel-connector-flink-iotdb/src/main/java/org/apache/seatunnel/flink/source/IotDbInputFormat.java`. Is this file still in the `seatunnel` repo ?
> > Would you mind pointing me to the new file location ?
> 
> If the file is not in the repo, simply ignore it and change the existing ones.

Ack, thanks
