### ISSUE TITLE
[Chore][docs] Update codebase connection

### ISSUE THREAD

**Issue by wuchunfu** [apache/seatunnel#1292]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Update codebase connection

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by asdf2014** [comment]
HI @wuchunfu, could you please tell us more about the update of codebase connection, thanks

**Comment by wuchunfu** [comment]
> HI @wuchunfu, could you please tell us more about the update of codebase connection, thanks

The main change is to change `https://interestinglab.github.io` to `https://seatunnel.apache.org` , because the official website is now available
