### ISSUE TITLE
[Feature][Udf] Whether to add UDF/UDAF/UDTF Module

### ISSUE THREAD

**Issue by obobj** [apache/seatunnel#1295]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Spark/Flink SQL supports UDFs, UDAFs and UDTFs, Should we add corresponding features. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
hi @obobj, nice idea!
