### ISSUE TITLE
[Bug] [seatunnel config] Some config classes not found when start example in local env

### ISSUE THREAD

**Issue by DingPengfei** [apache/seatunnel#1305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Lacking some config classes in seatunnel of current dev branch when i start examples at local env

 ` java: cannot find symbol`
 ` symbol:   class ConfigSyntax  `
 ` location: class org.apache.seatunnel.shade.com.typesafe.config.ConfigParseOptions`

### SeaTunnel Version

dev branch

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
hi @DingPengfei, run `mvn clean install` first, then run example.

**Comment by DingPengfei** [comment]
> leo65535

Thanks bro, it works @leo65535

**Comment by DingPengfei** [comment]
> hi @DingPengfei, run `mvn clean install` first, then run example.

Thanks bro, it works

**Comment by somnmos** [comment]
I get the same bug at tag 2.3.2, it always show the above bug when i run mvn clean install command.

**Comment by cobolbaby** [comment]
I ran into the same issue as in 2.3.6 with ./mvnw install -Dmaven.test.skip.
