### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by wangkang2711** [apache/seatunnel#1306]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

我在运行seatunnel时出现该错误：java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
经过上网查资料，发现是版本不匹配，需要升级，我目前使用的spark版本是3.1.2，我在官方是看是只支持3.0以下的spark，想问下什么可以支持3.1.2的spark呀

### Usage Scenario

与AWS上的EMR结合使用

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchunfu** [comment]
Please describe your problem in English, thank you.

**Comment by wangkang2711** [comment]
This error occurs when I run seatunnel: Java lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class

After checking the information on the Internet, it is found that the version does not match and needs to be upgraded. The spark version I currently use is 3.1.2. Officially, I only support spark below 3.0. What can I ask you to support spark of 3.1.2
