### ISSUE TITLE
[Feature][sql] Support variable in sql job conf

### ISSUE THREAD

**Issue by xleoken** [apache/seatunnel#1309]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support variable in sql job conf.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by simon824** [comment]
hi @leo65535 , this feature can assignee to me, thanks.

**Comment by xleoken** [comment]
> hi @leo65535 , this feature can assignee to me, thanks.

Welcome~
