### ISSUE TITLE
[Bug] [Docs] Abnormal display of document in vertical screen

### ISSUE THREAD

**Issue by JesseAtSZ** [apache/seatunnel#1312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

This page will display exceptions in the case of vertical screen：
https://seatunnel.apache.org/zh-CN/docs/introduction

![image](https://user-images.githubusercontent.com/35264598/155099643-89185796-fc86-4139-872e-660751bd7854.png)
Using Chrome browser, you can't drag the page left and right through the scroll bar below, so you can't see the left navigation bar.

### SeaTunnel Version

https://seatunnel.apache.org/zh-CN/docs/introduction

### SeaTunnel Config

```conf
https://seatunnel.apache.org/zh-CN/docs/introduction
```

### Running Command

```shell
https://seatunnel.apache.org/zh-CN/docs/introduction
```

### Error Exception

```log
https://seatunnel.apache.org/zh-CN/docs/introduction
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
![image](https://user-images.githubusercontent.com/16631152/155111302-b43d47ec-ebab-4fac-bb45-23e0b4c05a71.png)
Can you take another picture for me to see?

**Comment by JesseAtSZ** [comment]
The scroll bar below cannot be dragged to the left：

![image](https://user-images.githubusercontent.com/35264598/155116719-20c7f7de-8ddb-466a-a085-fc4561dddd65.png)

**Comment by CalvinKirs** [comment]
got you mean, if you are interested, please submit a PR.

**Comment by JesseAtSZ** [comment]
Today, I found that this problem no longer exists. The Chrome browser version I use is 98.0.4758.102.
