### ISSUE TITLE
[Improve] [doc] Display plugins in the form of a table

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1317]
It would be better that we can display our plugins in the form of a table, which will be more intuitive to users.

![image](https://user-images.githubusercontent.com/8108788/155323856-2f3f9776-8109-4d86-81a3-1baf11f1cc9c.png)

**Comment by asdf2014** [comment]
Any comments are welcome :smile:

**Comment by zhaomin1423** [comment]
I would like to do it.
