### ISSUE TITLE
[Feature][connector-spark] add a jdbc connector base DataSource V2 API

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#1347]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a jdbc connector based on Spark DataSource V2 API. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaomin1423** [comment]
Read data from multiple database and multiple tables.

**Comment by Hisoka-X** [comment]
I don't know what's different between now and new method, can you explain to me when we make this change come true, what will we get? Thanks.
