### ISSUE TITLE
[Bug] [spark-connector-doris] No handling of null values

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#1365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When a column value is NULL, the value in Doris is "null" when the column data type is string.

### SeaTunnel Version

2.0.5-SNAPSHOT

### SeaTunnel Config

```conf
None.
```

### Running Command

```shell
None.
```

### Error Exception

```log
The filed value is "null", it should be NULL.

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaomin1423** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/49054376/156210143-2edb6d07-4ffa-4d2d-801e-77527ea67720.png">
The column of name has incorrect values.

**Comment by zhaomin1423** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/49054376/156210391-40d0e491-1973-46c5-8b1d-bc89ba359bbb.png">
The column of name has correct values.

**Comment by wuchunfu** [comment]
problem solved #1366
