### ISSUE TITLE
[Feature][Connector] HDFS source connector support

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#1371]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Both spark and flink modes require the support of hdfs data sources

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Can you clearly describe the difference from the existing File plugin?

**Comment by Hisoka-X** [comment]
> 

HDFS client configuration and targeted optimization etc. This is a proposal, the details need to be discussed

**Comment by CalvinKirs** [comment]
> > 
> 
> HDFS client configuration and targeted optimization etc. This is a proposal, the details need to be discussed

Can you provide a detailed design? Then the community talks about this together.
