### ISSUE TITLE
[Feature][spark-connector-doris] refactor doris sink

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#1373]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

refactor doris sink.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaomin1423** [comment]
Hi, @CalvinKirs The flink connector doris and spark connector doris have common logical for writing data to doris. Whether we can have a common module responsible for reading and writing, then using it in connectors. What is your opinion？

**Comment by CalvinKirs** [comment]
> Hi, @CalvinKirs The flink connector doris and spark connector doris have common logical for writing data to doris. Whether we can have a common module responsible for reading and writing, then using it in connectors. What is your opinion？

One version is in Scala (Spark) and one version is in Java (Flink). I'm not sure if we can do it, do you have any good ideas?

**Comment by zhaomin1423** [comment]
> > Hi, @CalvinKirs The flink connector doris and spark connector doris have common logical for writing data to doris. Whether we can have a common module responsible for reading and writing, then using it in connectors. What is your opinion？
> 
> One version is in Scala (Spark) and one version is in Java (Flink). I'm not sure if we can do it, do you have any good ideas?

Using java in scala is very natural. In fact, our team does the same.

**Comment by zhaomin1423** [comment]
Also, can we implement the connector alone and use the connector in the code. For example, in spark, using connector by read.format. In this way, our connectors can be used by everyone.

**Comment by CalvinKirs** [comment]
> > > Hi, @CalvinKirs The flink connector doris and spark connector doris have common logical for writing data to doris. Whether we can have a common module responsible for reading and writing, then using it in connectors. What is your opinion？
> > 
> > 
> > One version is in Scala (Spark) and one version is in Java (Flink). I'm not sure if we can do it, do you have any good ideas?
> 
> Using java in scala is very natural. In fact, our team does the same.

I'm not familiar with Scala.... it would be better if this could be done.

**Comment by CalvinKirs** [comment]
> Also, can we implement the connector alone and use the connector in the code. For example, in spark, using connector by read.format. In this way, our connectors can be used by everyone.

@RickyHuo @kid-xiong @wuchunfu hi, WDYT?

**Comment by xtr1993** [comment]
The community advocates the use of Java,In fact, calling java with scala is not standardized，It is better to use java refactoring directly

**Comment by wuchunfu** [comment]
@xtr1993 It looks good, but will this increase the coupling between spark and flink?
