### ISSUE TITLE
[Bug] [doc] quick start's command is wrong when decompress package

### ISSUE THREAD

**Issue by JaydenHu6** [apache/seatunnel#1375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want to use seatunnel on flink, but the first step is wrong, it occurs in quick start 'Step 2: Download seaturnnel'

 decompress `seatunnel-2.0.4.zip` , I got `waterdrop-dist-2.0.4-2.11.8` , it is different from the [document](https://seatunnel.apache.org/docs/flink/quick-start/) `seatunnel-<version>`

<img width="796" alt="image" src="https://user-images.githubusercontent.com/57614820/156366703-3f1b0467-10e3-46e5-9712-027416c00b2c.png">

the same error occurs in [seatunnel on spark](https://seatunnel.apache.org/docs/spark/quick-start) `quick start`

### SeaTunnel Version

  none

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
This is the old version, the new version is renamed SeaTunnel
