### ISSUE TITLE
markdown doc of some connectors are not linked to README.md

### ISSUE THREAD

**Issue by kyle-cx91** [apache/seatunnel#1383]
markdown doc of some connectors are not linked to README.md, such as spark-kafka source connector,leading some users not knowing how to use

![image](https://user-images.githubusercontent.com/10529123/156539176-9a384a86-36a0-4044-babf-68d7d1c65e84.png)

I'd like to check markdown files of all the connectors, and add on the lack ones

**Comment by wuchunfu** [comment]
@ZhangchengHu0923 Looking forward to your contribution

**Comment by simon824** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/18065113/156540905-7747389a-7894-456a-a950-6648909cef51.png">

hi @ZhangchengHu0923, we already have spark-kafka source connector document, it's called `kafkaStream`.

**Comment by kyle-cx91** [comment]
> <img alt="image" width="552" src="https://user-images.githubusercontent.com/18065113/156540905-7747389a-7894-456a-a950-6648909cef51.png">
> 
> hi @ZhangchengHu0923, we already have spark-kafka source connector document, it's called `kafkaStream`.

ok，thx a lot. @simon824 
I have just found we missed the link of  spark-hbase-source
