### ISSUE TITLE
[Bug] [doc] The configuration of truncate is not supported when save mode is update, but it's written on the doc

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#1411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The configuration of truncate is not supported, but it's written on the doc

### SeaTunnel Version

2.0.5-snapshot

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchunfu** [comment]
Fixed #1412
