### ISSUE TITLE
[Feature][Connector] Flink JDBC sink support batch output

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#1423]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Flink jdbc sink need batch output mode, only support streaming mode at now.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
good idea, I also find this constrains between flink connector plugin streaming and batch mode, I'm trying to pull my request for JdbcSink support batch mode which implementing FlinkBatchSource interface.

But more questions I have found, can you help this issue: #1428

**Comment by Hisoka-X** [comment]
This close by #1432
