### ISSUE TITLE
transform data processing

### ISSUE THREAD

**Issue by emmataobao** [apache/seatunnel#1427]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

现在etl任务处理都是使用spark代码进行处理，想进行切换，但是在 transform 中 文档描述只看到使用SQL进行字段处理，但是在使用之中很多字段处理依赖外部的api进行处理，可能是算法api可能是标签库api，有些也可能需要进行join外部表，也有需要发送外部广播，这种etl方式支持吗？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Currently not supported.

**Comment by yx91490** [comment]
you can try udf in sql

**Comment by emmataobao** [comment]
谢谢
