### ISSUE TITLE
[Bug] [flink-jdbc-connector] various jdbc type of dialect compatibility between JdbcSource and JdbcSink

### ISSUE THREAD

**Issue by kalencaya** [apache/seatunnel#1428]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Seatunnel implements data integration through by source -> transforms -> sink principles, and any flink plugin supports `result_table_name` or `source_table_name` option for data transformation between DataStream and DataSet by Table api.

Below is `TableUtil` source code, which connect source, transfrom, sink.
```
public final class TableUtil {

    private TableUtil() {
    }

    public static DataStream<Row> tableToDataStream(StreamTableEnvironment tableEnvironment, Table table, boolean isAppend) {

        TypeInformation<Row> typeInfo = table.getSchema().toRowType();
        if (isAppend) {
            return tableEnvironment.toAppendStream(table, typeInfo);
        }
        return tableEnvironment
                .toRetractStream(table, typeInfo)
                .filter(row -> row.f0)
                .map(row -> row.f1)
                .returns(typeInfo);
    }

    public static DataSet<Row> tableToDataSet(BatchTableEnvironment tableEnvironment, Table table) {
        return tableEnvironment.toDataSet(table, table.getSchema().toRowType());
    }

    public static void dataStreamToTable(StreamTableEnvironment tableEnvironment, String tableName, DataStream<Row> dataStream) {
        tableEnvironment.registerDataStream(tableName, dataStream);
    }

    public static void dataSetToTable(BatchTableEnvironment tableEnvironment, String tableName, DataSet<Row> dataSet) {
        tableEnvironment.registerDataSet(tableName, dataSet);
    }

    public static boolean tableExists(TableEnvironment tableEnvironment, String name) {
        String currentCatalog = tableEnvironment.getCurrentCatalog();
        Catalog catalog = tableEnvironment.getCatalog(currentCatalog).get();
        ObjectPath objectPath = new ObjectPath(tableEnvironment.getCurrentDatabase(), name);
        return catalog.tableExists(objectPath);
    }
}
```
The problem is that when DataStream or DataSet contains some TypeInfomation which Table api not supports, then exception appears.

On flink jdbc plugin case, Flink only supports a few type but different RDBMS has own sql dialect and `JdbcSource#informationMapping` has to provide mapping from jdbc type to TypeInformation. If we add some TypeInformation not supported by `JdbcTypeUtil#TYPE_MAPPING` and `JdbcTypeUtil#SQL_TYPE_NAMES`, then transformation between DataSet or DataStream between Table may failed by exception.
```
public class JdbcTypeUtil {
    private static final Map<TypeInformation<?>, Integer> TYPE_MAPPING;
    private static final Map<Integer, String> SQL_TYPE_NAMES;

    public static int typeInformationToSqlType(TypeInformation<?> type) {
        if (TYPE_MAPPING.containsKey(type)) {
            return (Integer)TYPE_MAPPING.get(type);
        } else if (!(type instanceof ObjectArrayTypeInfo) && !(type instanceof PrimitiveArrayTypeInfo)) {
            throw new IllegalArgumentException("Unsupported type: " + type);
        } else {
            return 2003;
        }
    }

    static {
        HashMap<TypeInformation<?>, Integer> m = new HashMap();
        m.put(BasicTypeInfo.STRING_TYPE_INFO, 12);
        m.put(BasicTypeInfo.BOOLEAN_TYPE_INFO, 16);
        m.put(BasicTypeInfo.BYTE_TYPE_INFO, -6);
        m.put(BasicTypeInfo.SHORT_TYPE_INFO, 5);
        m.put(BasicTypeInfo.INT_TYPE_INFO, 4);
        m.put(BasicTypeInfo.LONG_TYPE_INFO, -5);
        m.put(BasicTypeInfo.FLOAT_TYPE_INFO, 7);
        m.put(BasicTypeInfo.DOUBLE_TYPE_INFO, 8);
        m.put(SqlTimeTypeInfo.DATE, 91);
        m.put(SqlTimeTypeInfo.TIME, 92);
        m.put(SqlTimeTypeInfo.TIMESTAMP, 93);
        m.put(LocalTimeTypeInfo.LOCAL_DATE, 91);
        m.put(LocalTimeTypeInfo.LOCAL_TIME, 92);
        m.put(LocalTimeTypeInfo.LOCAL_DATE_TIME, 93);
        m.put(BasicTypeInfo.BIG_DEC_TYPE_INFO, 3);
        m.put(PrimitiveArrayTypeInfo.BYTE_PRIMITIVE_ARRAY_TYPE_INFO, -2);
        TYPE_MAPPING = Collections.unmodifiableMap(m);
        HashMap<Integer, String> names = new HashMap();
        names.put(12, "VARCHAR");
        names.put(16, "BOOLEAN");
        names.put(-6, "TINYINT");
        names.put(5, "SMALLINT");
        names.put(4, "INTEGER");
        names.put(-5, "BIGINT");
        names.put(6, "FLOAT");
        names.put(8, "DOUBLE");
        names.put(1, "CHAR");
        names.put(91, "DATE");
        names.put(92, "TIME");
        names.put(93, "TIMESTAMP");
        names.put(3, "DECIMAL");
        names.put(-2, "BINARY");
        SQL_TYPE_NAMES = Collections.unmodifiableMap(names);
    }
}
```

### SeaTunnel Version

dev branch

### SeaTunnel Config

```conf
not needed
```

### Running Command

```shell
not needed
```

### Error Exception

```log
not needed
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Can share your config? Let me reproduce it

**Comment by kalencaya** [comment]
flink_jdbc_source_sink.conf
```
env {
  execution.parallelism = 1
}

source {
  JdbcSource {
    driver = com.mysql.cj.jdbc.Driver
    url = "jdbc:mysql://localhost:3306/data_service"
    username = root
    password = 123
    query = "select * from test"
    result_table_name = jdbc
  }
}

transform {
}

sink {
  JdbcSink {
    driver = com.mysql.cj.jdbc.Driver
    url = "jdbc:mysql://localhost:3306/data_service"
    username = root
    password = 123
    query = "insert into test_test(bigint_type,int_type,integer_type,mediumint_type,smallint_type,tinyint_type,bigint_type_2,int_type_2,integer_type_2,mediumint_type_2,smallint_type_2,tinyint_type_2,decimal_type,dec_type,float_type,double_type,time_type,date_type,datetime_type,timestamp_type,varchar_type,char_type) values (?,?,?,?,?, ?,?,?,?,?, ?,?,?,?,?, ?,?,?,?,?, ?,?)"
    source_table_name = jdbc
  }
}
```
mysql ddl:
```
CREATE TABLE `test` (
  `bigint_type` bigint unsigned DEFAULT NULL,
  `int_type` int unsigned DEFAULT NULL,
  `integer_type` int unsigned DEFAULT NULL,
  `mediumint_type` mediumint unsigned DEFAULT NULL,
  `smallint_type` smallint unsigned DEFAULT NULL,
  `tinyint_type` tinyint unsigned DEFAULT NULL,
  `bigint_type_2` bigint DEFAULT NULL,
  `int_type_2` int DEFAULT NULL,
  `integer_type_2` int DEFAULT NULL,
  `mediumint_type_2` mediumint DEFAULT NULL,
  `smallint_type_2` smallint DEFAULT NULL,
  `tinyint_type_2` tinyint DEFAULT NULL,
  `decimal_type` decimal(20,2) DEFAULT NULL,
  `dec_type` decimal(20,2) DEFAULT NULL,
  `float_type` float DEFAULT NULL,
  `double_type` double DEFAULT NULL,
  `time_type` time DEFAULT NULL,
  `date_type` date DEFAULT NULL,
  `datetime_type` datetime DEFAULT NULL,
  `timestamp_type` timestamp NULL DEFAULT NULL,
  `varchar_type` varchar(32) DEFAULT NULL,
  `char_type` char(1) DEFAULT NULL
) ENGINE=InnoDB COMMENT='测试表';

CREATE TABLE `test_test` (
  `bigint_type` bigint unsigned DEFAULT NULL,
  `int_type` int unsigned DEFAULT NULL,
  `integer_type` int unsigned DEFAULT NULL,
  `mediumint_type` mediumint unsigned DEFAULT NULL,
  `smallint_type` smallint unsigned DEFAULT NULL,
  `tinyint_type` tinyint unsigned DEFAULT NULL,
  `bigint_type_2` bigint DEFAULT NULL,
  `int_type_2` int DEFAULT NULL,
  `integer_type_2` int DEFAULT NULL,
  `mediumint_type_2` mediumint DEFAULT NULL,
  `smallint_type_2` smallint DEFAULT NULL,
  `tinyint_type_2` tinyint DEFAULT NULL,
  `decimal_type` decimal(20,2) DEFAULT NULL,
  `dec_type` decimal(20,2) DEFAULT NULL,
  `float_type` float DEFAULT NULL,
  `double_type` double DEFAULT NULL,
  `time_type` time DEFAULT NULL,
  `date_type` date DEFAULT NULL,
  `datetime_type` datetime DEFAULT NULL,
  `timestamp_type` timestamp NULL DEFAULT NULL,
  `varchar_type` varchar(32) DEFAULT NULL,
  `char_type` char(1) DEFAULT NULL
) ENGINE=InnoDB COMMENT='测试表';
```

Because JdbcSource is not a streaming source, but JdbcSink is a streaming sink, this config is invalid for now dev branch and I just pull my request for JdbcSink supporting batch sink waiting for review.

I had edited this comment for update mysql DDL.

**Comment by kalencaya** [comment]
> flink_jdbc_source_sink.conf
> 
> ```
> env {
>   execution.parallelism = 1
> }
> 
> source {
>   JdbcSource {
>     driver = com.mysql.cj.jdbc.Driver
>     url = "jdbc:mysql://localhost:3306/data_service"
>     username = root
>     password = 123
>     query = "select * from test"
>     result_table_name = jdbc
>   }
> }
> 
> transform {
> }
> 
> sink {
>   JdbcSink {
>     driver = com.mysql.cj.jdbc.Driver
>     url = "jdbc:mysql://localhost:3306/data_service"
>     username = root
>     password = 123
>     query = "insert into test_test(bigint_type,int_type,integer_type,mediumint_type,smallint_type,tinyint_type,bigint_type_2,int_type_2,integer_type_2,mediumint_type_2,smallint_type_2,tinyint_type_2,decimal_type,dec_type,float_type,double_type,time_type,date_type,datetime_type,timestamp_type,varchar_type,char_type) values (?,?,?,?,?, ?,?,?,?,?, ?,?,?,?,?, ?,?,?,?,?, ?,?)"
>     source_table_name = jdbc
>   }
> }
> ```
> 
> mysql ddl:
> 
> ```
> CREATE TABLE `test` (
>   `int_type` int unsigned DEFAULT NULL,
>   `integer_type` int unsigned DEFAULT NULL,
>   `mediumint_type` mediumint unsigned DEFAULT NULL,
>   `smallint_type` smallint unsigned DEFAULT NULL,
>   `tinyint_type` tinyint unsigned DEFAULT NULL,
>   `bigint_type_2` bigint DEFAULT NULL,
>   `int_type_2` int DEFAULT NULL,
>   `integer_type_2` int DEFAULT NULL,
>   `mediumint_type_2` mediumint DEFAULT NULL,
>   `smallint_type_2` smallint DEFAULT NULL,
>   `tinyint_type_2` tinyint DEFAULT NULL,
>   `decimal_type` decimal(20,2) DEFAULT NULL,
>   `dec_type` decimal(20,2) DEFAULT NULL,
>   `float_type` float DEFAULT NULL,
>   `double_type` double DEFAULT NULL,
>   `time_type` time DEFAULT NULL,
>   `date_type` date DEFAULT NULL,
>   `datetime_type` datetime DEFAULT NULL,
>   `timestamp_type` timestamp NULL DEFAULT NULL,
>   `varchar_type` varchar(32) DEFAULT NULL,
>   `char_type` char(1) DEFAULT NULL
> ) ENGINE=InnoDB COMMENT='测试表';
> 
> CREATE TABLE `test_test` (
>   `bigint_type` bigint unsigned NOT NULL,
>   `int_type` int unsigned DEFAULT NULL,
>   `integer_type` int unsigned DEFAULT NULL,
>   `mediumint_type` mediumint unsigned DEFAULT NULL,
>   `smallint_type` smallint unsigned DEFAULT NULL,
>   `tinyint_type` tinyint unsigned DEFAULT NULL,
>   `bigint_type_2` bigint DEFAULT NULL,
>   `int_type_2` int DEFAULT NULL,
>   `integer_type_2` int DEFAULT NULL,
>   `mediumint_type_2` mediumint DEFAULT NULL,
>   `smallint_type_2` smallint DEFAULT NULL,
>   `tinyint_type_2` tinyint DEFAULT NULL,
>   `decimal_type` decimal(20,2) DEFAULT NULL,
>   `dec_type` decimal(20,2) DEFAULT NULL,
>   `float_type` float DEFAULT NULL,
>   `double_type` double DEFAULT NULL,
>   `time_type` time DEFAULT NULL,
>   `date_type` date DEFAULT NULL,
>   `datetime_type` datetime DEFAULT NULL,
>   `timestamp_type` timestamp NULL DEFAULT NULL,
>   `varchar_type` varchar(32) DEFAULT NULL,
>   `char_type` char(1) CHARACTER DEFAULT NULL
> ) ENGINE=InnoDB COMMENT='测试表';
> ```

Because JdbcSource is not a streaming source, but JdbcSink is a streaming sink, this config is invalid for now dev branch and I just pull my request for JdbcSink supporting batch sink waiting for review.

**Comment by screampy** [comment]
我也碰到类似这个问题，有两个情况出现了预期外的情况，V2.0.4版本：
1.运行报空指针，原因是因为mysql里面有些字段是tinyint类型，没有匹配上
2.分别测试了mysql和5.6，8.0版本，5.6版本有一些列名大小写相关问题，8.0版本没法获取到columns定义(可能是JDBC驱动问题)，导致io.github.interestinglab.waterdrop.flink.source.JdbcSource.java的getRowTypeInfo方法中names数组元素为空。

还有个问题，目前的正则匹配“select (.+) from (.+).*”  没法匹配带where条件的语句，在一些需要使用预筛选的情况暂时没法实现。

**Comment by screampy** [comment]
我也碰到类似这个问题，有两个情况出现了预期外的情况，V2.0.4版本：
1.运行报空指针，原因是因为mysql里面有些字段是tinyint类型，没有匹配上
2.分别测试了mysql和5.6，8.0版本，5.6版本有一些列名大小写相关问题，8.0版本没法获取到columns定义(可能是JDBC驱动问题)，导致io.github.interestinglab.waterdrop.flink.source.JdbcSource.java的getRowTypeInfo方法中names数组元素为空。

还有个问题，目前的正则匹配“select (.+) from (.+).*”  没法匹配带where条件的语句，在一些需要使用预筛选的情况暂时没法实现。

**Comment by screampy** [comment]
我也碰到类似这个问题，有两个情况出现了预期外的情况，V2.0.4版本：
1.运行报空指针，原因是因为mysql里面有些字段是tinyint类型，没有匹配上
2.分别测试了mysql和5.6，8.0版本，5.6版本有一些列名大小写相关问题，8.0版本没法获取到columns定义(可能是JDBC驱动问题)，导致io.github.interestinglab.waterdrop.flink.source.JdbcSource.java的getRowTypeInfo方法中names数组元素为空。

还有个问题，目前的正则匹配“select (.+) from (.+).*”  没法匹配带where条件的语句，在一些需要使用预筛选的情况暂时没法实现。

**Comment by kalencaya** [comment]
> 我也碰到类似这个问题，有两个情况出现了预期外的情况，V2.0.4版本： 1.运行报空指针，原因是因为mysql里面有些字段是tinyint类型，没有匹配上 2.分别测试了mysql和5.6，8.0版本，5.6版本有一些列名大小写相关问题，8.0版本没法获取到columns定义(可能是JDBC驱动问题)，导致io.github.interestinglab.waterdrop.flink.source.JdbcSource.java的getRowTypeInfo方法中names数组元素为空。
> 
> 还有个问题，目前的正则匹配“select (.+) from (.+).*” 没法匹配带where条件的语句，在一些需要使用预筛选的情况暂时没法实现。

I had also tested PostgreSQL，which differs more with mysql column type and more NPE caused `JdbcSource#getRowTypeInfo` absence of mapping.

Some popular data integration tools based on flink try to split flink-connector-jdbc to concrete RDBMS plugin such as flink-connector-jdbc-mysql for different sql dialect.

Another problem is that Table level api can't support some field type produced by MySQL connector.  
Reproduction process is that you can define a MySQL table with `bigint unsigned` column type, then `ResultSet` implemented by MySQL connector would return `BigInteger` java type for that column, some exception followes.

**Comment by Hisoka-X** [comment]
The problem is: Mysql jdbc will return java type `BigInteger` when get `bigint unsigned` in database, check out [there](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html). But JdbcSource informationMapping Map convert it to `BIG_INT_TYPE_INFO` which flink not support, check out : [Fix reading BIGINT UNSIGNED type field not work in JDBC](https://issues.apache.org/jira/browse/FLINK-17657?jql=project%20%3D%20FLINK%20AND%20text%20~%20%22sql%20biginter%22#). Also `bigint unsigned` is only in Mysql series database.
#### Solve Plan
1. Override JdbcInputFormat so it can hand with `bigint unsigned` as string.
2. Support PostgreSQL's datatype.
3. Separate JdbcSource informationMapping for different databases

**Comment by Hisoka-X** [comment]
@CalvinKirs Please assign me.

**Comment by kalencaya** [comment]
> The problem is: Mysql jdbc will return java type `BigInteger` when get `bigint unsigned` in database, check out [there](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html). But JdbcSource informationMapping Map convert it to `BIG_INT_TYPE_INFO` which flink not support, check out : [Fix reading BIGINT UNSIGNED type field not work in JDBC](https://issues.apache.org/jira/browse/FLINK-17657?jql=project%20%3D%20FLINK%20AND%20text%20~%20%22sql%20biginter%22#). Also `bigint unsigned` is only in Mysql series database.
> 
> #### Solve Plan
> 1. Override JdbcInputFormat so it can hand with `bigint unsigned` as string.
> 2. Support PostgreSQL's datatype.
> 3. Separate JdbcSource informationMapping for different databases

learn a lot.
