### ISSUE TITLE
[Feature][Document] Tasks about document in the features

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1436]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# Content

# Content

* [ ] We should add page about project history and split content from introduction [links](https://seatunnel.apache.org/docs/introduction)
* [x] FAQ should be project level content instead of development level. [link](https://seatunnel.apache.org/docs/developement/FAQ). fix #1460 
* [ ] [Quick start](https://seatunnel.apache.org/docs/flink/quick-start) may better make it eaiser, if we could skip download and install flink and spark installation, using docker-compose or else infra keep it simple would be great.
* [ ] Some version related commands should but `export` version in bash instead of add description in doc. for example in [link](https://seatunnel.apache.org/docs/spark/installation#install-seatunnel) we should use `exprot version=2.0.4` in the bash command

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
> [Quick start](https://seatunnel.apache.org/docs/flink/quick-start) may better make it eaiser, if we could skip download and install flink and spark installation, using docker-compose or else infra keep it simple would be great.

In my view, quick start doesn't need install spark/flink environment, just use local mode. This way like a single node seatunnel task but without task failure recovery. Then next step is cluster mode with flink or spark.

**Comment by hongaer24** [comment]
11
