### ISSUE TITLE
[Feature][doc] Find a way support multi-language in our document

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1437]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

For now, our 2.0.0 document only has an English version, I think we should support multi-language documents. But I do not think translating by human it is a good way, because I make our translate document out-of-date and hard to maintain. I think we better find some way or components offer an easy way to translate hole page content from English to others. I find an example in CWL project. which you could see more detail in DolphinScheduler issue https://github.com/apache/dolphinscheduler/issues/8233

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
We have implemented it some months ago, I will close this issue.
