### ISSUE TITLE
[Feature][website] Add new style tab for two engine instead of separated page

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1456]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Should combine Spark and Flink engine to a single page instead of in different. For example we doris sink in both [Spark](https://seatunnel.apache.org/docs/spark/configuration/sink-plugins/Doris/) and [Fink](https://seatunnel.apache.org/docs/flink/configuration/sink-plugins/Doris/) but the content is most the same. Maybe we should use the same way in [spark](https://spark.apache.org/docs/latest/rdd-programming-guide.html#linking-with-spark) which use the **tab** in content to go to different engine. We could also make it DRY after we done this.

For now, our documents as below, both spark and flink have same title

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/15820530/157578432-5ea9a958-4ec3-4cef-bbad-77ce766c2d85.png">

for eaiser to read, we should combine them to single page, and use tab to switch the engine, like 

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/15820530/157578702-0a91c5a2-a3ef-4aec-80b0-eea450f69959.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I've hear that we have a amazing front-end engineer in SeaTunnel community, could we ask he/she for the help? @CalvinKirs

**Comment by CalvinKirs** [comment]
> I've hear that we have a amazing front-end engineer in SeaTunnel community, could we ask he/she for the help? @CalvinKirs

@wolfboys @wuchunfu hi, are you interested in completing this?

**Comment by wuchunfu** [comment]
> I've hear that we have a amazing front-end engineer in SeaTunnel community, could we ask he/she for the help? @CalvinKirs

@zhongjiajie @CalvinKirs Good idea, if you want to achieve this effect, please refer to: https://docusaurus.io/docs/markdown-features/tabs, this syntax is not `markdown` syntax, will this increase the learning cost of contributors, although it requires a lot of small learning cost

**Comment by zhongjiajie** [comment]
Looking good 👍 

> will this increase the learning cost of contributors

I think it is acceptable, is only a small adding syntax, BTW if we had to choose convenience  between users and contributors, I would choose users instead of contributors. Of course I should avoid this happend

**Comment by zhongjiajie** [comment]
One more things, I found it it a js instead of markdown in https://docusaurus.io/docs/markdown-features/tabs. It possiable to write

```js
<Tabs>
  <TabItem value="apple" label="Apple" default>
    This is an apple 🍎
  </TabItem>
  <TabItem value="orange" label="Orange">
    This is an orange 🍊
  </TabItem>
  <TabItem value="banana" label="Banana">
    This is a banana 🍌
  </TabItem>
</Tabs>
```

in markdown file and them render to the tab style?

**Comment by wuchunfu** [comment]
> One more things, I found it it a js instead of markdown in https://docusaurus.io/docs/markdown-features/tabs. It possiable to write
> 
> ```js
> <Tabs>
>   <TabItem value="apple" label="Apple" default>
>     This is an apple 🍎
>   </TabItem>
>   <TabItem value="orange" label="Orange">
>     This is an orange 🍊
>   </TabItem>
>   <TabItem value="banana" label="Banana">
>     This is a banana 🍌
>   </TabItem>
> </Tabs>
> ```
> 
> in markdown file and them render to the tab style?

It won't render as a tab in `markdown` , this code seems to be `react` syntax

**Comment by wuchunfu** [comment]
If the contributor has finished writing the `markdown` document, he may not be able to view the rendered effect locally. I wonder if other people have other better ways.

**Comment by zhongjiajie** [comment]
> If the contributor has finished writing the `markdown` document, he may not be able to view the rendered effect locally. I wonder if other people have other better ways.

When docs fetch to repository website, can this `react` syntax render to tab style?

**Comment by wuchunfu** [comment]
> > If the contributor has finished writing the `markdown` document, he may not be able to view the rendered effect locally. I wonder if other people have other better ways.
> 
> When docs fetch to repository website, can this `react` syntax render to tab style?

It seems to be possible, this needs to be verified again

**Comment by zhongjiajie** [comment]
Do you have time to verify this feature?

**Comment by wuchunfu** [comment]
> Do you have time to verify this feature?

I will verify later.
