### ISSUE TITLE
[Feature][Refactor] Refactor seatunnel-connector-flink-jdbc to remove embedded literals

### ISSUE THREAD

**Issue by mans2singh** [apache/seatunnel#1465]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The seatunnel-connector-flink-jdbc contains embedded literals for config variables used in sink and source code.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
Can you explain more? your description is not clear for me.

**Comment by mans2singh** [comment]
Hi @kalencaya  - 

Here is an example of the [embedded config literals](https://github.com/apache/incubator-seatunnel/pull/1466/files#diff-a67cdcf0bb65a9239c2b57b3c48874af247305bc59657401fedcb1ef928020d3L81).

Also, I have fixed this issue in PR (https://github.com/apache/incubator-seatunnel/pull/1466).  

Thanks for your time.

**Comment by Hisoka-X** [comment]
Please close this issue because you already done, thanks.

**Comment by CalvinKirs** [comment]
done
