### ISSUE TITLE
[Feature][doc] Add search component for our document

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1470]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I found out we do not have a search component for our documents. I think we should add this component to our document for better search

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msftgitsklsd** [comment]
I want to try this，the search component means searching on the seatunnel's main page(https://seatunnel.apache.org/docs/2.3.0/about) ？
