### ISSUE TITLE
[Feature][Config] Support json format config file

### ISSUE THREAD

**Issue by simon824** [apache/seatunnel#1494]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Json format sometimes is useful for system integration or task migration. Original typesafe config have supported json format config file, but the result parsed by seatunnel-config module is incorrect, we need fix it.

Original json config file
```json
{
  "env" : {
    "spark.app.name" : "SeaTunnel",
    "spark.executor.cores" : 1,
    "spark.executor.instances" : 2,
    "spark.executor.memory" : "1g"
  },
  "sink" : [
    {
      "plugin_name" : "Console"
    }
  ],
  "source" : [
    {
      "plugin_name" : "Fake",
      "result_table_name" : "my_dataset"
    }
  ],
  "transform" : []
}
```

After `ConfigFactory.parseFile`
```json
{
    "env" : {
        "spark.app.name" : "SeaTunnel",
        "spark.executor.cores" : 1,
        "spark.executor.instances" : 2,
        "spark.executor.memory" : "1g"
    },
    "sink" : [
        [
            "Console"
        ]
    ],
    "source" : [
        [
            "Fake",
            "my_dataset"
        ]
    ],
    "transform" : []
}

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchunfu** [comment]
Looking forward to your contribution
