### ISSUE TITLE
mysql to hive 报spark找不到hive数据库和表：Table or view not found: 

### ISSUE THREAD

**Issue by huazheng857** [apache/seatunnel#1497]
seatunnel version
2.1.0
spark version
2.4.3

1、配置文件截图
<img width="560" alt="配置文件" src="https://user-images.githubusercontent.com/101729851/158629304-142ae9f0-b737-46b2-86d8-e1c06c899cc9.png">

2、报错截图
<img width="561" alt="error" src="https://user-images.githubusercontent.com/101729851/158629423-d50e7706-6805-4571-af74-428737782b0d.png">

3、问题描述：
source中用Hive插件可以查到上面的hive库和表并获取到数据，但是在sink中用Hive插件会报错：“Exception StackTrace:org.apache.spark.sql
.AnalysisException:Table or view not found: aquila_tp_sdpms doesn't exist.; line 1 pos 0...”

帮忙看看是哪里有可能出问题，谢谢

**Comment by yx91490** [comment]
reference https://github.com/apache/incubator-seatunnel/issues/1438

**Comment by huazheng857** [comment]
我加上：spark.sql.catalogImplementation = "hive"之后，没有报找不到库和表，数据写入到了hdfs文件中，
但是写入文件的这个hdfs的路径不是我表中指定的hdfs路径，他默认写入了“hdfs://pilotcluster/apps/hive/warehouse/”路径下
而我表数据的hdfs路径为:"/warehouse/galaxy/aquila/"

**Comment by yx91490** [comment]
> 我加上：spark.sql.catalogImplementation = "hive"之后，没有报找不到库和表，数据写入到了hdfs文件中， 但是写入文件的这个hdfs的路径不是我表中指定的hdfs路径，他默认写入了“hdfs://pilotcluster/apps/hive/warehouse/”路径下 而我表数据的hdfs路径为:"/warehouse/galaxy/aquila/"

can you show this table's ddl sql?

**Comment by CalvinKirs** [comment]
For better communication, please use English, I temporarily closed it, you can reopen it after modifying it.
