### ISSUE TITLE
add a plugin for encrypting

### ISSUE THREAD

**Issue by lphcreat** [apache/seatunnel#1511]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

in my work, for data safty, i need encrypting data. so i made a plugin for encrypting, it can encrypt dataset or some columns. but i have a problem i use in wd1.5, so i will fix it. 数据加密插件也可以进行解密算法是des3，但是我用的是1.5，希望可以有个大神帮我~

### Usage Scenario

encrypting data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please share your problem in here, So other guys maybe can help you.
