### ISSUE TITLE
[Bug] [seatunnel-connector-spark-redis] default config as official doc said can't run correctly

### ISSUE THREAD

**Issue by DingPengfei** [apache/seatunnel#1522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Doc from [spark redis sink](https://seatunnel.apache.org/docs/spark/configuration/sink-plugins/Redis) says only "host" and "port" are required in config file. But I got this
`ERROR org.apache.seatunnel.command.BaseTaskExecuteCommand  - Plugin[org.apache.seatunnel.spark.sink.Redis] contains invalid config, error: No configuration setting found for key 'data_type'`
in my local dev env

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
  Fake {
    result_table_name = "my_dataset"
  }
}

transform {
}

sink {
  Console {}
  Redis {
    host = "localhost"
    port = 6379
  }
}
```

### Running Command

```shell
start in my local dev env
```

### Error Exception

```log
ERROR org.apache.seatunnel.command.BaseTaskExecuteCommand  - Plugin[org.apache.seatunnel.spark.sink.Redis] contains invalid config, error: No configuration setting found for key 'data_type'
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yeah, this is a bug, we need to use `hasPath` to check if the configKey is exist.

**Comment by DingPengfei** [comment]
> Yeah, this is a bug, we need to use `hasPath` to check if the configKey is exist.

I had submitted a PR for this. Maybe you can help me to review it.
