### ISSUE TITLE
[Question] [connector-flink] flink-on-yarn config

### ISSUE THREAD

**Issue by xuchangqun** [apache/seatunnel#1537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I'd like to know how to set yarn configs ,for example 

  Options for yarn-cluster mode:
     -d,--detached                        If present, runs the job in detached
                                          mode
     -m,--jobmanager <arg>                Set to yarn-cluster to use YARN
                                          execution mode.
     -yat,--yarnapplicationType <arg>     Set a custom application type for the
                                          application on YARN
     -yD <property=value>                 use value for given property
     -yd,--yarndetached                   If present, runs the job in detached
...

### SeaTunnel Version

seatunnel 2.1.0

### SeaTunnel Config

```conf
demo:

env {
  execution.parallelism = 1
}

source {
  FakeSourceStream {
    result_table_name = "fake"
    field_name = "name,age"
  }
}

transform {
  Split{
    separator = "#"
    fields = ["name","age"]
  }
  sql {
    sql = "select name,age from fake"
  }
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
../bin/start-seatunnel-flink.sh \
	-ynm seatunnel-flink-demo1 \
	-m yarn-cluster \
	--config flink-stream-demo.conf
```

### Error Exception

```log
null
```

### Flink or Spark Version

flink 1.12.2 
on yarn

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@xuchangqun You can add your yarn config after `start-seatunnel-flink.sh `.
e.g. 
```
sh bin/start-seatunnel-flink.sh --config config/application.conf -t yarn-per-job
```
`start-seatunnel-flink.sh` will add your params to submit flink job.

**Comment by xuchangqun** [comment]
> @xuchangqun You can add your yarn config after `start-seatunnel-flink.sh `. e.g.
> 
> ```
> sh bin/start-seatunnel-flink.sh --config config/application.conf -t yarn-per-job
> ```
> 
> `start-seatunnel-flink.sh` will add your params to submit flink job.

@ruanwenjun Thanks , i will try.
