### ISSUE TITLE
[Bug] [spark-connector] can not run on spark 3.1.2 hadoop 3.2.1

### ISSUE THREAD

**Issue by SbloodyS** [apache/seatunnel#1542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

```
22/03/23 16:20:17 ERROR ApplicationMaster: User class threw exception: java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
```

### SeaTunnel Version

2.1.0-release.

### SeaTunnel Config

```conf
es source
hive sink
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh \
--master yarn \
--deploy-mode cluster \
--config config/spark.batch.conf
```

### Error Exception

```log
above.
```

### Flink or Spark Version

spark 3.1.2

### Java or Scala Version

1.8.0_312

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
SeaTunnel support spark version is 2.4.0 at now. You can try it with 2.4.0

**Comment by SbloodyS** [comment]
> SeaTunnel support spark version is 2.4.0 at now. You can try it with 2.4.0

Sad...The version of the production environment cannot be downgraded. There are a lot of errors in compling when i try to upgrade the version of spark to 3.1.2 in ```pom.xml```. It seems like I can not use seatunnel for a while.

**Comment by Hisoka-X** [comment]
> > SeaTunnel support spark version is 2.4.0 at now. You can try it with 2.4.0
> 
> Sad...The version of the production environment cannot be downgraded. There are a lot of errors in compling when i try to upgrade the version of spark to 3.1.2 in `pom.xml`. It seems like I can not use seatunnel for a while.

You can create an issue to ask support spark 3.1.2.

**Comment by SbloodyS** [comment]
> > > SeaTunnel support spark version is 2.4.0 at now. You can try it with 2.4.0
> > 
> > 
> > Sad...The version of the production environment cannot be downgraded. There are a lot of errors in compling when i try to upgrade the version of spark to 3.1.2 in `pom.xml`. It seems like I can not use seatunnel for a while.
> 
> You can create an issue to ask support spark 3.1.2.

Thanks. I've create a feature request link to this issue.
