### ISSUE TITLE
[Feature][Spark] Suggest support spark 3.1.2 in seatunnel

### ISSUE THREAD

**Issue by SbloodyS** [apache/seatunnel#1548]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Suggest support spark 3.1.2 in seatunnel.

### Related issues

#1542

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
let we discuss on #875
