### ISSUE TITLE
[Feature][connectors] Split the connectors module with source and sink

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1568]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, we put the source and sink plugin in a same connector module.

There may hard to find out how many source and sink plugin are already supported from the code. Since may exist some connectors only implements source or sink.

I suggest splitting the connectors module into source module and sink module. This may make the increase the module number, but I think this is needed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@BenJFan @wuchunfu @CalvinKirs @dongzl  What do you think, welcome to discuss.

**Comment by Hisoka-X** [comment]
Maybe we can use some maven plugin to figure out which ones source/sink do we support？

**Comment by ruanwenjun** [comment]
> Maybe we can use some maven plugin to figure out which ones source/sink do we support？

This is a way, but can we just get the plugin types from the module name rather than execute the maven command? Do you have any concern about splitting the source and sink into different module?

**Comment by Hisoka-X** [comment]
> > Maybe we can use some maven plugin to figure out which ones source/sink do we support？
> 
> This is a way, but can we just get the plugin types from the module name rather than execute the maven command? Do you have any concern about splitting the source and sink into different module?

In my opinion, split source and sink only can help developer know how many source and sink we have quickly, doesn't have other advantage. The maven plugin also can do that

**Comment by wuchunfu** [comment]
I don't think it's necessary to do this if it's just to better see what source and sink plugins are available. What I worry about is whether it will affect the build time and increase the package size if you split too many modules.

**Comment by ruanwenjun** [comment]
> I don't think it's necessary to do this if it's just to better see what source and sink plugins are available. What I worry about is whether it will affect the build time and increase the package size if you split too many modules.

Yes, it may increase the build time.

**Comment by ruanwenjun** [comment]
Thanks for join this discussion and give the opinion, right now this change is not necessary indeed. 
I close this issue.
