### ISSUE TITLE
[Feature] Introduce seatunnel-backend module

### ISSUE THREAD

**Issue by simon824** [apache/seatunnel#1573]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

This issue want to discuss do we need a `seatunnel-backend` module  that supports remote submission of tasks , currently we having to execute the submit command on the server side.

And we can discuss what feature we needed in `seatunnel-backend` module.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Good idea to me, I hope we can provide `seatunnel-backend` module or a `seatunnel-cli` client, that can help user to manage the `seatunnel` jobs like submit job/ stop job or some other operation, user don't need to extra use  flink/spark client to do this work.

And furthermore, if the added module can provide the plugin information is better. Such as how many kinds of plugins have been packaged in the seatunnel jar, and what params is needed of the plugin.

**Comment by simon824** [comment]
Thank you for your feedback, I will design the initial version. Also I want to discuss which framework should we choose for providing HTTP services, Jetty or Spring Boot or others, WDYT? @CalvinKirs @wuchunfu @ruanwenjun

**Comment by simon824** [comment]
Jetty +1
IMO, jetty is light and springboot is heavy, backend module is more about forwarding work and state acquisition.

**Comment by ruanwenjun** [comment]
> Thank you for your feedback, I will design the initial version. Also I want to discuss which framework should we choose for providing HTTP services, Jetty or Spring Boot or others, WDYT? @CalvinKirs @wuchunfu @ruanwenjun

If we don't need to integrate with other framework, using Jetty is good to me.
If we still need to do some database operation, I think use SpringBoot is a better choose.
