### ISSUE TITLE
[Feature][sql] Move seatunnel-core-sql to seatunnel-core-flink

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1584]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have `seatunnel-core-flink`, `seatunnel-core-spark`, `seatunnel-core-sql` modules in core module.
This sometimes make confusion, since right now `seatunnel-core-sql` is just support flink engine, and will use flink to run the sql task. It not supports spark.

I suggest moving the code from `seatunnel-core-sql` module to `seatunnel-core-flink`.

We need to add a new `Command` name `FlinkSqlExecuteCommand` and add a new Execution named `FlinkSqlExecution` to execute the command. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Why not rename seatunnel-core-sql to seatunnel-sql-flink？So If we support spark sql, we can use name seatunnel-sql-spark.

**Comment by ruanwenjun** [comment]
> Why not rename seatunnel-core-sql to seatunnel-sql-flink？So If we support spark sql, we can use name seatunnel-sql-spark.

Thanks for your advice, but I think it might be better to remove the current `sql` module? Since `sql` is just a sub-task type like `streaming`, `batch`, `structuredstreaming`.

**Comment by Hisoka-X** [comment]
> > Why not rename seatunnel-core-sql to seatunnel-sql-flink？So If we support spark sql, we can use name seatunnel-sql-spark.
> 
> Thanks for your advice, but I think it might be better to remove the current `sql` module? Since `sql` is just a sub-task type like `streaming`, `batch`, `structuredstreaming`.

It seem like fine
