### ISSUE TITLE
[Bug] [org.apache.seatunnel.config.ConfigBuilder] many wrong 'import' in the source code

### ISSUE THREAD

**Issue by ooeeerrtt** [apache/seatunnel#1601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There are many wrong 'import' in the source code.
For example in 'org.apache.seatunnel.config.ConfigBuilder' 
    import org.apache.seatunnel.shade.com.typesafe.config.Config;
Thr right is 
    import com.typesafe.config.Config;

### SeaTunnel Version

2.1.0-release

### SeaTunnel Config

```conf
nothing
```

### Running Command

```shell
nothing
```

### Error Exception

```log
nothing
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
Run `mvn clean package -DskipTests -Dfast` firstly before imporing seatunnel into IDE.

After success, then you can search more issues about `Config` dependency with interest.
