### ISSUE TITLE
[Feature][doc] Add committers to team page

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1604]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, I find out we do not have committers in our [team page](https://seatunnel.apache.org/team). As an important part of both community and team, I think we should add them to our team page

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchunfu** [comment]
@zhongjiajie I have done this work, https://github.com/apache/incubator-seatunnel-website/pull/100

**Comment by zhongjiajie** [comment]
Thanks @wuchunfu , a little tips here, next time you could use keyword `fix: #1604` or `close: #1604` in repo apache/incubator-seatunnel, and `fix: apache/incubator-seatunnel#1604` or `close: apache/incubator-seatunnel#1604` in repo apache/incubator-seatunnel-website in your PR. After you added it, the related issue will auto close when PR is merged.
It will save some time to maintain the issue
