### ISSUE TITLE
[Feature][docs] Add announcement page in our website to new release and new committer/PMC

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1619]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

hey guys, I think we should add a new page about SeaTunnel's announcement which could announce for new released or new committer and PMC. Or maybe meetup could also include there but I am not sure about that. I think we should have a place put some important matters in our community.

But I find out the top bar is a bit crowded, I don't know whether we should add it or not. https://seatunnel.apache.org/
<img width="896" alt="image" src="https://user-images.githubusercontent.com/15820530/160748886-75cf7ef9-0bd3-42b3-bb79-36e7630c26de.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
ping @CalvinKirs @wuchunfu WDYT?

**Comment by CalvinKirs** [comment]
> ping @CalvinKirs @wuchunfu WDYT?

that's good. But usually, it's up to the new committer to add it, of course, community contributors are welcome to add it.

**Comment by zhongjiajie** [comment]
So we would like to and a new page or not?
