### ISSUE TITLE
[Feature][doc] Add how docker quick start

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1622]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Up to now, our docker quick starts is still `WIP` which you can see in https://seatunnel.apache.org/docs/start/docker. We should better add some content about our docker quick start. If you interested in this you could ref our local quick start https://seatunnel.apache.org/docs/start/local

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jj551** [comment]
assign to  me @zhongjiajie

**Comment by zhongjiajie** [comment]
I assigned it to you, looking  forward your contribution

**Comment by FlechazoW** [comment]
Has this issue been finished yet? If not, I can help.

**Comment by zhongjiajie** [comment]
hi @FlechazoW , I assigned this issue to you, FYI @joshuyaaa

**Comment by FlechazoW** [comment]
> hi @FlechazoW , I assigned this issue to you, FYI @joshuyaaa

Ok, i will finish it asap.

**Comment by zhongjiajie** [comment]
> > hi @FlechazoW , I assigned this issue to you, FYI @joshuyaaa
> 
> Ok, i will finish it asap.

looking forward your contribution

**Comment by FlechazoW** [comment]
> 

I will finish it before Wednesday.

**Comment by FlechazoW** [comment]
Hi, i am sorry that the documents need to be delayed for a few days. These days i was busy with work, and i'm thirty percent done, i think i can finish it in this weekend.

**Comment by zhongjiajie** [comment]
It is there any process there @FlechazoW ?

**Comment by tcodehuber** [comment]
Has this issue been finished yet? I am glad to submit a PR. @zhongjiajie
