### ISSUE TITLE
The doc of spark and flink version is not correct

### ISSUE THREAD

**Issue by chenhu** [apache/seatunnel#1626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Seatunnel 2.10 not support Spark3.x， the doc of [Quick start] about the spark version should not be "Spark version >= 2.x.x" ,  should be Spark version >= 2.x.x and < 3.x or spark3.x is not supported current. 

### SeaTunnel Version

v2.10

### SeaTunnel Config

```conf
nothing
```

### Running Command

```shell
nothing
```

### Error Exception

```log
nothing
```

### Flink or Spark Version

v3.x

### Java or Scala Version

java8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
For now, we need to provide the dependency corresponding version notes.thanks for your contribution:)
