### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by AdkinsHan** [apache/seatunnel#1628]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Until now I still haven't trans data from mysql to hive;
then i tried  mysql to hdfs，Although the process is complex, it is effective；
but i have to refresh table command ;
the  question: when I import using hdfs, do I need to import hive again like sqoop?

### SeaTunnel Version

2.1.0

### SeaTunnel Config

```conf
normal
```

### Running Command

```shell
success
```

### Error Exception

```log
xx
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please provide your config, and execption message

**Comment by ruanwenjun** [comment]
Closed due to no response.
