### ISSUE TITLE
[Feature][connector] Upgrade the version of kudu from 1.7 to 1.12 and add units test for kudu

### ISSUE THREAD

**Issue by Rianico** [apache/seatunnel#1639]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

According to the [email](https://lists.apache.org/thread/gmlqqyw920o8xbvz38q5nton3kfhb278) , I want to upgrade the version of  kudu from 1.7 to 1.12 and add units test for kudu by using kudu-binary which can start a minimize kudu server but has a platform limitation(only support linxu-x86_64 and osx-x86_64).

In order to solve the platform problem about the import problem of kudu-binary jar, maybe we can add profile which can be triggered according to the os environment automically. In this way, we don't have to add `-D` in maven or set `-D` in ide to solve the import problem of kudu-binary jar. But we still need a way to skip the unit test according to to OS version.

Junit5 provides the annotation to skip the test according to the os, and more elegant semantics. But I'm not sure about whether it's worth upgrading the Junit from Junit4 to Junit5?  Anyone give some suggesstions？

### Usage Scenario

Start the minimize kudu server in unit test, so we can test kudu-source, kudu-sink on a kudu cluster.

### Related issues

#1459 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@Rianico As we discussed in mail thread, we can just upgrade the kudu version and use other way to control the UT.
