### ISSUE TITLE
[Bug] [core] Resource leak again..

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/8108788/161389930-15a4a261-7ffe-49ba-a1d0-6c95d842bfcb.png)

### SeaTunnel Version

The latest version (2.1.0)

### SeaTunnel Config

```conf
N/A
```

### Running Command

```shell
N/A
```

### Error Exception

```log
N/A
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, we need to close the `DirectoryStream`.
