### ISSUE TITLE
[Feature][SPARK] Upgrade spark version to 2.4.4

### ISSUE THREAD

**Issue by liujinhui1994** [apache/seatunnel#1660]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The current spark version is using 2.4.0.
For example:：I found some scenes of hudi to be unusable.
After an upgrade, the impact on other components may need to be assessed

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
We have been planning to do multi-version support. I am not sure whether the current version of Spark is compatible with 2.4.4 Can you investigate this?

**Comment by Hisoka-X** [comment]
When use spark2.4.4, I can't run SeaTunnel succeeded. Maybe we should upgrade.
