### ISSUE TITLE
[OnlineMeeting&4.12]SeaTunnel community meeting Topic collection

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#1661]
We will hold an online community meeting on  2022/04/12 20:00-20:30 (GMT+08:00),
Welcome everyone to leave a message in the issue to discuss the content
CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Meeting
Meeting Time: 2022/04/12 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/N3KjzveIauEi

#TencentMeeting：842-260-129

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting

Discussion Issue :

- Review of the content of the previous issue : #1549
-  2.1.1 release
- 1.X bug fix
- #1608 
- #1669

**Comment by chenhu** [comment]
- The APIs of metrics

**Comment by chenhu** [comment]
- Should we add the persist feature for spark transform plugins ?

**Comment by ashulin** [comment]
#1608

**Comment by Hisoka-X** [comment]
#1669

**Comment by CalvinKirs** [comment]
> * The APIs of metrics

Hi, did you look this #1578, Do you have any questions about this design?

**Comment by chenhu** [comment]
> 

I have browsed through the code and have a general understanding. There is no problem. However, I suggest that there be a general document to explain what indicators are available, how to use them, and so on

**Comment by tmljob** [comment]
#1512
1.x version upgrade plan and long-term planning

**Comment by xleoken** [comment]
cc @CalvinKirs plan to add a new feature about SeaTunnel Web Service.

![image](https://user-images.githubusercontent.com/95013770/162934694-753a704c-a447-4849-afc2-0d15d861821e.png)

![image](https://user-images.githubusercontent.com/95013770/162934754-e034780e-443d-4e5f-abc3-1c8447843d91.png)

**Comment by xuchangqun** [comment]
> 

this ui is familiar.

**Comment by xuchangqun** [comment]
hope to support : kafka -> hdfs and kafka -> iceberg (flink sink),
Do you have such a scene.
