### ISSUE TITLE
[Feature][connector] Standardize plugin name

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1694]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, there are some plugins have different name in different engine. e.g. Kafka source connector in Spark is `kafkaStream` and in Flink is `KafkaTableStream`, it's needed to standardize the plugin name. 
And the paramenters are also different in some plugin. e.g. the jdbc sink connector has parameter `user` in Spark engine, and has `username` in Flink engine, but these have the same mean.

For better to maintain and integrate in the future, it's needed to standardize the plugin name and parameters. This will break the compatibility, but it's easy to achieve in the early project.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hililiwei** [comment]
hi @ruanwenjun , i'd like to have a try, may i have the ticket?

**Comment by ruanwenjun** [comment]
> hi @ruanwenjun , i'd like to have a try, may i have the ticket?

Great, I have assigned to you, before your working, please send a proposal email to dev@seatunnel.apache.org about this issue, since this change will break the compatibility.

**Comment by hililiwei** [comment]
Okay, thank you. I will.
