### ISSUE TITLE
[Feature][Core] SeaTunnel Source API

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#1701]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

From the current Source API design of Flink & Spark and other data synchronization product such as Canal, Debezium & Flink CDC.
The following are the required features of Source:

- Support parallel reading, and the framework manages thread resources.（e.g.  Consume a specific multi-partitioned Kafka topic）
- Support dynamic discovery of splits. (e.g. consume a Kafka Topic group with regular expressions)
- Support to coordinate the work of multiple readers. (e.g. Netfilx DBLog CDC lock-free algorithm) 

![SeaTunnel Engine Flow](https://user-images.githubusercontent.com/36807946/163580323-97d81a4d-0a10-420a-b550-1673e11c0d82.png)

### Top level public interfaces

-   **Source**:  Factory class for creating various Source Interfaces;

-   **Boundedness**: Identify whether the source data is bounded;

-   **SourceSplitEnumerator**: Discover the splits and assign them to the SourceReaders;

    -  **SupportCoordinatedEnumerator**: Support coordination;

-   **SourceSplit**：An interface for all the split types.

    -   Split ID `field`: For serialization & support for **ParallelSource**, etc.

    -   **Serializer**
    
-   **SourceEvent**: Interface for event types in the coordination process；
    
-   **SourceReader**：Read the records from the splits；

    -   **SupportCoordinatedReader**: Support coordination;
    
    -    **Collector**：Collect Rows；

         -   **Row**：Row Data
         
             -   Table ID `field`:  It is used for data distribution in the scenario of multiple-table multiplexing connections.

         
    
-   **State**: Used to store source state information. (e.g. kafka offset)
    
    -   **Serializer**
    
-   **StatefulOperator**：For state initialization, restoration, etc.

-   **CheckpointListener**：Notification of checkpoint completion or abort；

#### Translation level public interfaces

-   **RowSerialization**：Converted to engine internal row.

-   **CoordinatedSource**: If the engine don't support source coordination, and source coordination is required, use this source.

-   **ParallelSource**: If the engine don't support source coordination, and source coordination is not required, use this source.

#### Spark version >= 2.3+ Or Flink full version 

the engine don't support source coordination, it is difficult to extend support for this case at the engine level.
We can maintain multi-threaded readers in a single task and support splits and coordination.

![SeaTunnel CoordinatedSource](https://user-images.githubusercontent.com/36807946/163550531-5380497c-89ef-4c9c-8d1a-d7e2d267a51f.png)

-  It needs to manage the thread resources of the source reader;
-  Discover the splits and assign them to the SourceReaders；
-  Support coordination;
-  **There can only be one instance in the engine.**

The above method cannot use the resources of the engine friendly. When the source reader don't need to coordinate, we can support it in the following ways: 
![SeaTunnel ParallelSource](https://user-images.githubusercontent.com/36807946/163550554-0732b861-2ef0-440c-b3ad-ff1e4d814537.png)

- It is necessary to implement a hash algorithm composed of Split ID and SourceReader ID (SubTask ID) to ensure that Split will not be read repeatedly in multiple source readers;

- When dynamic split discovery is required, ensure that SourceSplitEnumerator is running all the time.

#### Engine level public class

- `Flink` **SeaTunnelSource** implements SourceFunction : used to wrap CoordinatedSource or ParallelSource.

- `Spark` **SeaTunnelSource** implements DataReader: used to wrap CoordinatedSource or ParallelSource.

    -  Create a corresponding ReadSupport (Continuous, Microbatch) with **Boundedness** 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hk-lrzy** [comment]
So we can't use this api on spark? And this is same like flink source api, why we need to wrapper it again?

**Comment by ashulin** [comment]
> So we can't use this api on spark? And this is same like flink source api, why we need to wrapper it again?

The source API is indeed similar to Flink, as the Flink source API covers more source features. 
But we can't use the Flink API directly, because SeaTunnel need to be decoupled from the engine so that it can support Flink (lower version) and Spark engine.

**Comment by hk-lrzy** [comment]
> [OnlineMeeting&4.26]SeaTunnel community meeting Topic collect #1721

I agree with you.  but i am not sure whether new source api could use in the other engine or not. 
IMO, the flink source api is too complex for developer.

**Comment by ashulin** [comment]
Completed!
