### ISSUE TITLE
[Feature][doc] Add build CI in main repository

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#1716]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In #1714, we find our doc may crack by some mistake in `mdx` file, to avoid the regression, we should add build CI in the repo and make sure every PR pass the doc build process

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by hezean** [comment]
hi @mangoGoForward what’s the status of this issue? still working on it? or can i take over it

**Comment by mangoGoForward** [comment]
> hi @mangoGoForward what’s the status of this issue? still working on it? or can i take over it

Still open, you can push it if you want to contribute. @HeZean
