### ISSUE TITLE
[Feature][seatunnel-transforms] Add Replace transforms for spark

### ISSUE THREAD

**Issue by wuzhenhua01** [apache/seatunnel#1750]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add replace transforms，supports regular

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
close by #1751
