### ISSUE TITLE
[Feature][jdbc spark] support query param

### ISSUE THREAD

**Issue by lordk911** [apache/seatunnel#1764]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I tried using Spark to read data from a table in mysql and sink it to the console, but it stuck for a long time and ran out of memory.

Is it because Spark reads full data? Whether the query parameter can be added to actively filter some data data.

I also tried adding transform, helpless, that doesn't do the predicate push down, does it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@lordk911 We use English to describe the issue, please translate to English, thanks.

**Comment by lordk911** [comment]
I tried using Spark to read data from a table in mysql and sink it to the console, but it stuck for a long time and ran out of memory. 

Is it because Spark reads full data? Whether the query parameter can be added to actively filter some data data.

I also tried adding transform, helpless, that doesn't do the predicate push down, does it?

**Comment by ashulin** [comment]
Currently source is instantiated directly rather than created by the SQL engine, so predicate pushdown is not supported.

**Comment by chenhu** [comment]
https://seatunnel.apache.org/docs/2.1.1/command/usage

@lordk911 u can use the -i option passing the params to the config file
