### ISSUE TITLE
[Feature][flink-connector-jdbc] add pre sql and post sql 

### ISSUE THREAD

**Issue by dijiekstra** [apache/seatunnel#1789]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

help user do some pre-processing by pre-sql and do some post-processing by post-sql.

By the way, post-sql is not supported in stream job because of the continuity of flow tasks.

Also, in some cases, we can ignore post-SQL exceptions and mark the job as successful.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dijiekstra** [comment]
Hi everybody, I am new to Seatunnel but I can do this so can someone assign this to me?

**Comment by ruanwenjun** [comment]
Closed by #1791
