### ISSUE TITLE
[OnlineMeeting&May 10]SeaTunnel community meeting Topic collect

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#1804]
We will hold an online community meeting on 2022/05/10 20:00-20:30 (GMT+08:00)
CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Meeting
Meeting Time: 2022/05/10 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/bePE0cQIJDKs

#TencentMeeting：873-198-318

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Discussion Issue :

Review of the content of the previous issue : https://github.com/apache/incubator-seatunnel/issues/1721

**Comment by xleoken** [comment]
Topic: Introduce `DynamicTableSourceFactory` and `DynamicTableSinkFactory` to improve the flink api part.

**Comment by tmljob** [comment]
When is the next release version expected to be released, and what release rhythm will be maintained in the future?

**Comment by chenhu** [comment]
Topic : Are we need a webUI to monitor the jobs, and could stop or start the job in web ui

**Comment by felixYyu** [comment]
+1 Should need a webUI
