### ISSUE TITLE
Seatunnel can't load the user defined plugin jars 

### ISSUE THREAD

**Issue by chenhu** [apache/seatunnel#1818]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Jars like oracle、mysql driver jars puted in plugins/[pluginName]/lib ， would not be loaded where seatunnel started

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
nothing
```

### Running Command

```shell
nothing
```

### Error Exception

```log
The exceptions like db driver class not find
```

### Flink or Spark Version

spark2.4

### Java or Scala Version

java8

### Screenshots

<img width="1577" alt="image" src="https://user-images.githubusercontent.com/979010/167247262-fe99780e-d4cc-4953-94ad-8b95e0b7eb13.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/979010/167247282-ab64999a-4d10-4bb4-b608-19b1e10cdf1f.png">
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/979010/167247314-dad824eb-a7f2-41a9-b283-3710280ae1e0.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenhu** [comment]
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/979010/167247688-b6700ab2-715f-4a2a-bd44-816cf2777d07.png">
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/979010/167247712-62dcbe76-7219-497c-bc00-46c70d9b055d.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/979010/167247742-3628df0f-3598-459d-8dc8-840831dbb8bb.png">

**Comment by chenhu** [comment]
Maybe it.getFileName().endsWith("jar") should be it.getFileName().toString().endsWith("jar")

**Comment by ruanwenjun** [comment]
Yes, this is a bug, are you interested to fix this?

**Comment by chenhu** [comment]
yes ,I have submit a PR
https://github.com/apache/incubator-seatunnel/pull/1819
