### ISSUE TITLE
[Feature][Default branch] Should the Default branch is master not dev?

### ISSUE THREAD

**Issue by felixYyu** [apache/seatunnel#1827]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

According to the general specification, the master is used as the default branch management

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
we use `dev` as our default branch
