### ISSUE TITLE
[Bug] [seatunnel-core] Prohibit invoking System.out.println in source code !

### ISSUE THREAD

**Issue by felixYyu** [apache/seatunnel#1833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

System.out.println in source code, slf4j instead System.out.

### SeaTunnel Version

v2.1.1

### SeaTunnel Config

```conf
NaN
```

### Running Command

```shell
NaN
```

### Error Exception

```log
checkstyle rule
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Closed by #1834
