### ISSUE TITLE
[Feature][Seatunnel-core-Flink] upgrade Flink deprecated api 

### ISSUE THREAD

**Issue by legendtkl** [apache/seatunnel#1865]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

upgrade the deprecated flink apis

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
That`s great.

**Comment by legendtkl** [comment]
This story is expected to take some effect. I will submit PRs in two weeks.
