### ISSUE TITLE
[Feature][Connector] spark-connector-excel

### ISSUE THREAD

**Issue by tmljob** [apache/seatunnel#1869]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Provide the excel input source plug-in under the spark engine to obtain excel data.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tmljob** [comment]
I will provide PR to contribute to the project.

**Comment by EricJoy2048** [comment]
SeaTunnel has a source connector named `File`, The file format supported by the File connector are `csv` `json` `parquet` `orc` `text`. I think you can optimization this connector and add `excel` file format support.

**Comment by tmljob** [comment]
> SeaTunnel has a source connector named `File`, The file format supported by the File connector are `csv` `json` `parquet` `orc` `text`. I think you can optimization this connector and add `excel` file format support.

I have submitted a PR for excel alone as a soure plugin. The main reason is that Excel is special compared to other files, and I only implemented it under the spark engine.

**Comment by tmljob** [comment]
#1872
