### ISSUE TITLE
[Feature][plugin] Add seatunnel-plugin-discovery module

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1874]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, we have split the connectors from the launch jar. When our job startup, we will find the connector plugin from disk.
The problem is that we have multiple module need to load plugin, e.g. flink, spark, flink-sql. And after our new API design, we will have more plugins(engine-translation).

Since we didn't add the plugin into our classpath, so we need to use a lookup mechanism to do this.

This issue is hope to add a new module `seatunnel-plugin-discovery` to load plugins. Other module want to use plugin will directly rely on `seatunnel-plugin-discovery`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by legendtkl** [comment]
Good.

With this module, I hope the classloader only load the on-demand jars into classpath to reduce some class conflict.

I would like to participate the work if some subtasks need.

**Comment by ruanwenjun** [comment]
> Good.
> 
> With this module, I hope the classloader only load the on-demand jars into classpath to reduce some class conflict.
> 
> I would like to participate the work if some subtasks need.

Yes, we just need to load the connector jar will be used in config, this has already been implemented.
