### ISSUE TITLE
[Feature][Flink SQL] Add flink sql connector kafka

### ISSUE THREAD

**Issue by legendtkl** [apache/seatunnel#1877]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add kafka connector for flink sql

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #1878
