### ISSUE TITLE
[Feature][seatunnel-connector-flink-fake] Support FakeSourceStream to mock data.

### ISSUE THREAD

**Issue by mosence** [apache/seatunnel#1879]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In old FakeSourceStream, The data is limit and column size is only 2.

Add jar _com.github.jsonzou:jmockdata_  to support config mock data feature.

Like this config:

```
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "id,name,age"
      mock_data_enable = true
      mock_data_bounded = true
      mock_data_schema = [
        {
           name = "id"
           type = "string"
           mock_config = {
             string_regex = "[0-9a-f]{11}"
           }
        }
        {
           name = "name"
           type = "string"
           mock_config = {
             size_range = [10,10]
           }
        }
        {
           name = "age"
           type = "int"
           mock_config = {
             int_range = [1,100]
           }
        }
      ]
    }
```

jmockdata: [https://github.com/jsonzou/jmockdata](https://github.com/jsonzou/jmockdata)

### Usage Scenario

1. In develop test, can mock more type data to do test case.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #1880
