### ISSUE TITLE
[Feature][Core] Plugin-Mapping load ignore case

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#1884]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At dev now, we use `plugin-mapping.properties` to find plugin we should load. The logic is: Parse config, then get source/sink plugin name. use this name to find plugin-mapping key in `plugin-mapping.properties`. The value will be plugin jar prefix name. Finally the jar load success.
The problem is plugin name in config not support ignore case (older version supported). We should support any case plugin name can map to plugin-mapping key. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
@ruanwenjun Hi, I think this is a good first issue.

**Comment by ruanwenjun** [comment]
> @ruanwenjun Hi, I think this is a good first issue.

Do you mean the upper case/lower case mapping to the plugin jar? In fact, I have support this in #1881. But #1881 will not be released in next version. 

I add a help wanted label, we need to finish this issue before our next release.
