### ISSUE TITLE
[Feature] Can it support flink table mode sink and stream mode sink in one job?

### ISSUE THREAD

**Issue by waywtdcc** [apache/seatunnel#1896]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Can it support flink table mode sink and stream mode sink in one job?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
You mean batch and streaming?
