### ISSUE TITLE
[Feature] [spark-clickhouse] ClickhouseFile does not support ReplicatedMergeTree

### ISSUE THREAD

**Issue by Emor-nj** [apache/seatunnel#1910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

ClickhouseFile does not support ReplicatedMergeTree

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Close by #1911
