### ISSUE TITLE
[Feature][Connectors] Add assert plugin

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1912]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, if we want to test a transform/sink plugin we can use a fake source plugin to generate data, and validate the data in the target sink database.

If we want to test a source/transform plugin, we have the below two ways:
1. Use the console sink plugin, and see the data in console. 
2. Start a sink database and validate the data in the database.
These two-way is not convenient at IT, this issue want to import an AssertSink plugin, this plugin is similier with ConsoleSink plugin, but will not print data in console, it will validate the data with some rule, e.g: data rows, data type, data value...

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lhyundeadsoul** [comment]
may i have a try?
@ruanwenjun

**Comment by ruanwenjun** [comment]
> may i have a try? @ruanwenjun

I have assigned to you, if you have any idea, please let me know.

**Comment by lhyundeadsoul** [comment]
@ruanwenjun 
Here is my idea of FakeAssertSink design, please check it out and let me know if there is anything wrong. Thx!
Refer to ConsoleSink, I think the FakeAssertSink plugin should follow the rules following:
1. in  `seatunnel-connector-flink-fake` module and `org.apache.seatunnel.flink.fake.sink` package
2. implements `FlinkBatchSink` and `FlinkStreamSink`,and no need to extend `RichOutputFormat` as there is nothing need to output.
3. config should be like this 
```
FakeAssertSink {
    rules = [
        {
            field_name = 'name'
            field_type = 'string'
            field_value = [
                {
                    rule_type = 'not-null'
                },
                {
                    rule_type = 'minLength'
                    rule_value = 5
                },
                {
                     rule_type = 'maxLength'
                     rule_value = 10
                }
            ]
        },
        {
            field_name = 'age'
            field_type = 'int'
            field_value = [
                {
                    rule_type = 'min'
                    rule_value = 18
                },
                {
                    rule_type = 'max'
                    rule_value = 100
                }
            ]
        }
    ]
 }
```
4. A rule parser and data validator are necessary to resolve the rules config and throw an exception including the wrong data  as long as a data can not pass the rules

**Comment by ruanwenjun** [comment]
> @ruanwenjun Here is my idea of FakeAssertSink design, please check it out and let me know if there is anything wrong. Thx! Refer to ConsoleSink, I think the FakeAssertSink plugin should follow the rules following:
> 
> 1. in  `seatunnel-connector-flink-fake` module and `org.apache.seatunnel.flink.fake.sink` package

I think you can add a new plugin module `seatunnel-connector-flink-assert`.
> 2. implements `FlinkBatchSink` and `FlinkStreamSink`,and no need to extend `RichOutputFormat` as there is nothing need to output.
> 3. config should be like this
> 
> ```
> FakeAssertSink {
>     rules = [
>         {
>             field_name = 'name'
>             field_type = 'string'
>             field_value = [
>                 {
>                     rule_type = 'not-null'
>                 },
>                 {
>                     rule_type = 'minLength'
>                     rule_value = 5
>                 },
>                 {
>                      rule_type = 'maxLength'
>                      rule_value = 10
>                 }
>             ]
>         },
>         {
>             field_name = 'age'
>             field_type = 'int'
>             field_value = [
>                 {
>                     rule_type = 'min'
>                     rule_value = 18
>                 },
>                 {
>                     rule_type = 'max'
>                     rule_value = 100
>                 }
>             ]
>         }
>     ]
>  }
> ```
Yes, you can define some rules.
> 
> 4. A rule parser and data validator are necessary to resolve the rules config and throw an exception including the wrong data  as long as a data can not pass the rules
You mean validate the data in runtime, if validate failed, then throw exception? It's OK to me.

**Comment by lhyundeadsoul** [comment]
> I think you can add a new plugin module seatunnel-connector-flink-assert.

I think so.  That's a better design resolution.

> You mean validate the data in runtime, if validate failed, then throw exception? It's OK to me.

I can add _**a fail-strategy parameter**_ to control whether print or throw ex,  how about that? @ruanwenjun 
```
FakeAssertSink {
    fail-strategy: print (or interrupt)
    rules = [
        {
            field_name = 'name'
            field_type = 'string'
            field_value = []
        }
 }
```

**Comment by lhyundeadsoul** [comment]
I have had a different opinion:
> `Assert` is more likely an alternative function for a `sink` plugin, not just a special sink plugin itself. We should treat assert as an option function of a plugin(e.g. Console Plugin), rather than a new plugin.

I am looking forward to your point of view. Thx! @ruanwenjun

**Comment by ruanwenjun** [comment]
@lhyundeadsoul Different user may have different requirement, in some case they may want to use `assert` in source/transform/sink. This may make it complex, we may add data validate module in the future. Currently, I think we can just add an assent sink plugin, and put it in a single module, this will not make things complex.

**Comment by lhyundeadsoul** [comment]
> @lhyundeadsoul Different user may have different requirement, in some case they may want to use `assert` in source/transform/sink. This may make it complex, we may add data validate module in the future. Currently, I think we can just add an assent sink plugin, and put it in a single module, this will not make things complex.

OK,  So do we need fail-strategy: print (or interrupt) ?

**Comment by ruanwenjun** [comment]
> > @lhyundeadsoul Different user may have different requirement, in some case they may want to use `assert` in source/transform/sink. This may make it complex, we may add data validate module in the future. Currently, I think we can just add an assent sink plugin, and put it in a single module, this will not make things complex.
> 
> OK, So do we need fail-strategy: print (or interrupt) ?

Throw exception is ok.

**Comment by lhyundeadsoul** [comment]
I will add assert sink plugin in api-draft branch
