### ISSUE TITLE
[OnlineMeeting&May 24]SeaTunnel community meeting Topic collect 

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#1915]
We will hold an online community meeting on 2022/05/24 20:00-21:00 (GMT+08:00) China Standard Time - Beijing
CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Meeting Time: 2022/05/24 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/VTTGOkaXRvR5

#TencentMeeting：409-618-953

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting

Review of the content of the previous issue: #1804 

if you have any issue wanna discuss, please leave issue number

**Comment by xleoken** [comment]
Add a topic: [Data Transmission based on SQL](https://lists.apache.org/thread/tc5stn4tf0y67ffqm3y8pr3l5h9p7t8l) [SeaTunnel 规划思考.pptx](https://github.com/apache/incubator-seatunnel/files/8761889/SeaTunnel.pptx)
