### ISSUE TITLE
[Feature][Connector] flink-redis

### ISSUE THREAD

**Issue by kim-up** [apache/seatunnel#1924]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Redis sink & source plugins

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Do you want to submit a PR?

**Comment by kim-up** [comment]
I have the usage scenarios. But I don't find the connector. And https://github.com/apache/flink/tree/master/flink-connectors also don't have the  redis connector. I'm not sure how to develop this connector. Maybe I need to research it, because I'm new to Seatunnel and Flink.

**Comment by kim-up** [comment]
I refer to other connectors, if I  have developed it, I will submit a PR.
