### ISSUE TITLE
[Feature][spark] support cdh spark

### ISSUE THREAD

**Issue by quaker1** [apache/seatunnel#1938]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 it doesn't support cdh spark.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please provide your log which seatunnel run failed.
