### ISSUE TITLE
[Feature][transform] missing etl operation

### ISSUE THREAD

**Issue by wsyhj** [apache/seatunnel#1957]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the case of poor data quality, it is necessary to do default value processing for special values (such as null)

### Usage Scenario

etl

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
If you use sql transform you can do it with sql.
