### ISSUE TITLE
[Discuss] Provide multiple Maven profiles

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#1959]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, SeaTunnel only has a profile for fat jar.
Some users may only have a single engine environment, so other engine related jars are not required.
So I expect to provide multiple maven profiles to support different users.

### Usage Scenario

Reduced build file size of SeaTunnel.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
If do that, we would release different package with single engine, the number of release package will be more, but the size maybe smaller. We should discuss this, what do you think? @CalvinKirs @ruanwenjun

**Comment by Hisoka-X** [comment]
Or use this profile just for some people need repackage.

**Comment by ashulin** [comment]
> Or use this profile just for some people need repackage.

I agree with this suggestion;

**Comment by CalvinKirs** [comment]
> 

+1

**Comment by ashulin** [comment]
closed by #2703
