### ISSUE TITLE
[Bug] [website] flink-fake-connector docs error

### ISSUE THREAD

**Issue by kalencaya** [apache/seatunnel#1989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

fake source and fake source stream

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
not needed
```

### Running Command

```shell
not needed
```

### Error Exception

```log
not needed
```

### Screenshots

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/24804318/172297214-043fe601-83f7-420e-9f90-7e633feec77e.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kalencaya** [comment]
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/24804318/172298669-6075a95e-137b-4737-9f96-114691e0a592.png">

**Comment by wanghuan2054** [comment]
fake source and fake source stream  error has been corrected in dev

**Comment by lhyundeadsoul** [comment]
I have already fixed this bug in [apache:main](https://github.com/apache/incubator-seatunnel-website)   

 https://github.com/apache/incubator-seatunnel-website/pull/127
