### ISSUE TITLE
[OnlineMeeting&June 21]SeaTunnel community meeting Topic collect 

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#2019]
CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Meeting Time: 2022/06/21 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/lIeV69oC5H57

#TencentMeeting：647-445-170

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting

Review of the content of the previous issue: https://github.com/apache/incubator-seatunnel/issues/1986

if you have any issues wanna discuss, please leave issue number

**Comment by CalvinKirs** [comment]
#1947

**Comment by ashulin** [comment]
https://github.com/apache/incubator-seatunnel/issues/2024
