### ISSUE TITLE
[Feature][Doc] Add Flink SQL module to website.

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2021]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At now, we can't see our flink sql module any information. 
We should add link on website about flink sql which already be writeen in /docs/en/connector/flink-sql/. 
And add a guide about how to use flink sql module. 
Checkout the sidebars.js file in docs/, you will know how this can work.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wanghuan2054** [comment]
Please assign this task to me
