### ISSUE TITLE
[Discuss][api-draft] SeaTunnel DataType & Java Class & Engine DataType

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2024]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I found that in the current `api-draft` branch, everyone handles data types differently, which makes the end-to-end test easy to fail, so I expect to be able to determine the data types supported by SeaTunnel, and the corresponding Java Class, Flink data types, Spark data types.

Below is my idea：

The SQL Type of Seatunnel is an enumeration of Data types and may be used as SQL keywords.
Data Type contains specific type information, such as precision.

| SeaTunnel Row Java Class | SeaTunnel SQL Type | SeaTunnel DataType                      | Flink TypeInfo                                        | Spark DataType       |
| ----------------------- | ------------------ | --------------------------------------- | ----------------------------------------------------- | -------------------- |
| java.lang.String        | STRING             | BasicType.STRING                        | BasicTypeInfo.STRING_TYPE_INFO                        | DataTypes.StringType |
| java.lang.Boolean       | BOOLEAN            | BasicType.BOOLEAN                       | BasicTypeInfo.BOOLEAN_TYPE_INFO                       |      DataTypes.BooleanType      |
| java.lang.Byte          | TINYINT            | BasicType.BYTE                          | BasicTypeInfo.BYTE_TYPE_INFO                          | DataTypes.ByteType     |
| java.lang.Short         | SMALLINT           | BasicType.SHORT                         | BasicTypeInfo.SHORT_TYPE_INFO                         |        DataTypes.ShortType        |
| java.lang.Integer       | INT                | BasicType.INT                           | BasicTypeInfo.INT_TYPE_INFO                           |        DataTypes.IntegerType        |
| java.lang.Long          | BIGINT             | BasicType.LONG                          | BasicTypeInfo.LONG_TYPE_INFO                          |        DataTypes.LongType |
| java.lang.Float         | FLOAT              | BasicType.FLOAT                         | BasicTypeInfo.FLOAT_TYPE_INFO                         | DataTypes.FloatType       |
| java.lang.Double        | DOUBLE             | BasicType.DOUBLE                        | BasicTypeInfo.DOUBLE_TYPE_INFO                        |        DataTypes.DoubleType        |
| java.math.BigDecimal    | DECIMAL            | BasicType.BIG_DECIMAL                   | BasicTypeInfo.BIG_DEC_TYPE_INFO                       |     DecimalType       |
| java.time.LocalDate     | DATE               | LocalTimeType.LOCAL_DATE                | LocalTimeTypeInfo.LOCAL_DATE             |         DataTypes.DateType        |
| java.time.LocalTime     | TIME               | LocalTimeType.LOCAL_TIME                | LocalTimeTypeInfo.LOCAL_TIME                |          DataTypes.TimestampType        |
| java.time.LocalDateTime | TIMESTAMP          | LocalTimeType.LOCAL_DATE_TIME           | LocalTimeTypeInfo.LOCAL_DATE_TIME                     |     DataTypes.TimestampType  |
| byte[]                  | BYTES              | PrimitiveArrayType.PRIMITIVE_BYTE_ARRAY | PrimitiveArrayTypeInfo.BYTE_PRIMITIVE_ARRAY_TYPE_INFO | DataTypes.BinaryType |
| T[]                     | ARRAY              | ArrayType<T>                            | BasicArrayTypeInfo<T>                                 |     ArrayType<T>       |
| java.util.Map<K, V>     | MAP                | MapType<K, V>                           | MapTypeInfo<K, V>                                     |       MapType<K,V>       |

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
Do we want to support TIMESTAMP WITH TIMEZONE? Or other?
Currently, the DECIMAL type does not contain information such as precision, is there any need for improvement?

**Comment by EricJoy2048** [comment]
> Do we want to support TIMESTAMP WITH TIMEZONE? Or other?
> Currently, the DECIMAL type does not contain information such as precision, is there any need for improvement?

Yes. Decimal is need precision I think.

**Comment by hk-lrzy** [comment]
> > Do we want to support TIMESTAMP WITH TIMEZONE? Or other?
> > Currently, the DECIMAL type does not contain information such as precision, is there any need for improvement?
> 
> Yes. Decimal is need precision I think.

agree, and i think we need alignment source & sink precison value if there have differents.

**Comment by Hisoka-X** [comment]
Close by #2052
