### ISSUE TITLE
[Bug] [seatunnel-connector-seatunnel-fake] Incorrect use ThreadLocalRandom

### ISSUE THREAD

**Issue by iture123** [apache/seatunnel#2059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 
Error in class org.apache.seatunnel.connectors.seatunnel.fake.source.FakeSourceReader
```
    private final Random random = ThreadLocalRandom.current();

    public void pollNext(Collector<SeaTunnelRow> output) throws InterruptedException {
        // Generate a random number of rows to emit.
        int size = random.nextInt(10);
    }
```
`int size = random.nextInt(10);`
The variable size actually is a fixed value, not a random number,because can not share ThreadLocalRandom  in multi-thread.The correct usage is as follows:
`
int size = ThreadLocalRandom.current().nextInt(10);
`

### SeaTunnel Version

api-draft 2.1.1-SNAPSHOT

### SeaTunnel Config

```conf
FakeSource {
      result_table_name = "fake"
      field_name = "name,age"
    }
```

### Running Command

```shell
run org.apache.seatunnel.example.flink.SeaTunnelApiExample
```

### Error Exception

```log
no
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Close by #2060
