### ISSUE TITLE
[Feature][Connector] Support Rsync to transfer clickhouse data file

### ISSUE THREAD

**Issue by Emor-nj** [apache/seatunnel#2073]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Build rsync shell command to support transfer clickhouse data file with Rsync over ssh.(There is another way to transfer file with Rsync which is rsync-daemon,but rsync-daemon is complex and not flexible.So i choose Rsync with ssh. )
The local client should install sshpass,which to support non interactive password authentication.
And solve the NullPointerException when node_free_password=true.（when i test with clickhousfile, i found that if set node_free_password=true, nodePass will not be init,so nodePass.contains will throw NullPointerException ）

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Emor-nj** [comment]
https://github.com/apache/incubator-seatunnel/issues/1513

**Comment by EricJoy2048** [comment]
good idea. CC @Hisoka-X

**Comment by john8628** [comment]
good job
