### ISSUE TITLE
[Feature][Connector-V2] Email Sink Connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2109]
link https://github.com/apache/incubator-seatunnel/issues/1946

**Comment by 2013650523** [comment]
Do you mean to send the read data content to the mail in the form of Excell table?

**Comment by 2013650523** [comment]
Can you assign me to Email Sink.thx

**Comment by EricJoy2048** [comment]
> Can you assign me to Email Sink.thx

Yes, of course. Welcome.

**Comment by EricJoy2048** [comment]
cc @Hisoka-X

**Comment by YOMO-Lee** [comment]
Can this question be closed now

**Comment by Hisoka-X** [comment]
closed by #2304
