### ISSUE TITLE
[Feature][CI] Add some skip rule for our CI

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#2119]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Since we have frontend part in our codebase, and there are not all of our change should run all CI, we should add some rule to skip some of them. such as only frontend change should not trigger backend test or some thing else. ref #

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Yes, I agree with you. And I will submit a pr to fix it.
