### ISSUE TITLE
Configuration key 'auth' is set to null but expected STRING

### ISSUE THREAD

**Issue by chocolateBlack** [apache/seatunnel#2122]
does redis sink must set auth properties? 

I config  a  hive to redis job,  config file shows blew. I got an error " Application diagnostics message: User class threw exception: org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Null: hive2redis.conf: 74: Configuration key 'auth' is set to null but expected STRING"

`env {
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 1
  spark.executor.cores = 1
  spark.executor.memory = "1g"

  queue = default
  spark.sql.catalogImplementation = "hive"
}

source {
  hive  {
    pre_sql = "SELECT id, name FROM default.result_table_name"
    result_table_name = "result_table_name"
  }
}

transform {
  sql {
    sql = "select CONCAT('a_',id), CONCAT(id, '$', name) from result_table_name"
  }
}

sink {
  redis {
      host = "192.168.111.111"
      port = 7379
      db_num = 11
      data_type = "KV"
      auth = null
  }
}`

I have tried to set auth = null、auth = ““ and not to set auth. All can't install a job。

Version: 2.1.1-SNAPSHOT

**Comment by Hisoka-X** [comment]
`'auth' is set to null but expected STRING"` so you should put your password in this field. check https://seatunnel.apache.org/docs/2.1.2/connector/sink/Redis

**Comment by chocolateBlack** [comment]
> `'auth' is set to null but expected STRING"` so you should put your password in this field. check https://seatunnel.apache.org/docs/2.1.2/connector/sink/Redis

there is no password config to the redis。 I found It was a bug  and fixed in new version。
org.apache.seatunnel.spark.sink.Redis line 41：
from
`auth =  config.getString(AUTH),`
to 
`auth = if (config.getIsNull(AUTH)) null else config.getString(AUTH),`
