### ISSUE TITLE
[Connector-V2] Add orc FileFormat for File Sink Connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2130]
link https://github.com/apache/incubator-seatunnel/issues/1946

Now the FileSink Connector only support `text` file format, `ORC` is a very common file format and it often used in hive. We need support `ORC` file format.

Some help information:
`HdfsTxtTransactionStateFileWriter` and `LocalTxtTransactionStateFileWriter` are the `text` file format implement. They all extends the class `AbstractTransactionStateFileWriter` . `AbstractTransactionStateFileWriter` is a abstract class which define the file writer can support `Transaction` and `State`. If you want implement a `orc` file writer, you should extend `AbstractTransactionStateFileWriter` too.

**Comment by TyrantLucifer** [comment]
I want to try it

**Comment by EricJoy2048** [comment]
> I want to try it

Thank you.

**Comment by TyrantLucifer** [comment]
@CalvinKirs Can you assign it to me? Thank you!

**Comment by TyrantLucifer** [comment]
pr #2369, @CalvinKirs @EricJoy2048 @Hisoka-X please review.
