### ISSUE TITLE
[Connector-V2]Add CSV file format for File Sink Connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2133]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

link https://github.com/apache/incubator-seatunnel/issues/1946

Now the FileSink Connector only support text file format, `CSV` is a very common file format and it often used in hive. We need support `CSV` file format.

Some help information:
`HdfsTxtTransactionStateFileWriter` and `LocalTxtTransactionStateFileWriter` are the text file format implement. They all extends the class `AbstractTransactionStateFileWriter` . `AbstractTransactionStateFileWriter` is a abstract class which define the file writer can support Transaction and State. If you want implement a orc file writer, you should extend `AbstractTransactionStateFileWriter` too.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuxizhi777** [comment]
> ### Search before asking
> * [x]  I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.
> 
> ### Description
> link #1946
> 
> Now the FileSink Connector only support text file format, `CSV` is a very common file format and it often used in hive. We need support `CSV` file format.
> 
> Some help information: `HdfsTxtTransactionStateFileWriter` and `LocalTxtTransactionStateFileWriter` are the text file format implement. They all extends the class `AbstractTransactionStateFileWriter` . `AbstractTransactionStateFileWriter` is a abstract class which define the file writer can support Transaction and State. If you want implement a orc file writer, you should extend `AbstractTransactionStateFileWriter` too.
> 
> ### Usage Scenario
> _No response_
> 
> ### Related issues
> _No response_
> 
> ### Are you willing to submit a PR?
>  * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
I want try it ,assign to me.

**Comment by TyrantLucifer** [comment]
@wuxizhi777 Is there any progress in this work? If not, I can do it.
