### ISSUE TITLE
The simple example of contribution location on the official website has not been updated

### ISSUE THREAD

**Issue by zzzzzzzs** [apache/seatunnel#2138]
Official website address: https://seatunnel.apache.org/zh-CN/docs/2.1.2/contribution/setup

### What happened
The simple example of contribution location on the official website has not been updated. So I have updated the document and submitted a PR.

### SeaTunnel Version

dev

### Screenshots
![image](https://user-images.githubusercontent.com/25766626/177472307-5b897f83-4c61-42ed-8c8f-ccfe88dba54b.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Close by #2139
