### ISSUE TITLE
[Feature][Module Name] Is there any way to monitor data traffic in real time?

### ISSUE THREAD

**Issue by gaozhenfeng1** [apache/seatunnel#2140]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Is there any way to monitor data traffic in real time?

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
You can just use flink/spark metrics plan at now.

**Comment by dik111** [comment]
How Can I get metrics by seatunnel-spark-sink-JDBC ?
