### ISSUE TITLE
Tidb Source and Sink Connector.

### ISSUE THREAD

**Issue by lhyundeadsoul** [apache/seatunnel#2173]
I can work for tidb Source and Sink Connector. thx

_Originally posted by @lhyundeadsoul in https://github.com/apache/incubator-seatunnel/issues/1946#issuecomment-1169865090_

**Comment by lhyundeadsoul** [comment]
@Hisoka-X What feature do we need in Tidb connector while JDBC connector can not support?

**Comment by Hisoka-X** [comment]
> @Hisoka-X What feature do we need in Tidb connector while JDBC connector can not support?

Do what you can! We hope our connector can be best in the future, but it will spend lots of time. Simple but can work are great. Then you can make this connector better in you way.

**Comment by lhyundeadsoul** [comment]
> 

Yes, I think so.
But, it is almost the same as JDBC connector now. There is no new feature detected.

**Comment by Hisoka-X** [comment]
> > 
> 
> Yes, I think so. But, it is almost the same as JDBC connector now. There is no new feature detected.

Both source and sink? Any method to make write/read faster?

**Comment by EricJoy2048** [comment]
I have an idea, Can we add a TiDB sink which write data to TiDB by `load data`. I think this is faster than writing tidb directly through JDBC.

**Comment by lhyundeadsoul** [comment]
> I have an idea, Can we add a TiDB sink which write data to TiDB by `load data`. I think this is faster than writing tidb directly through JDBC.

`load data` in tidb must specify one file in local(not cluster, refer to `目前 TiDB 只支持从客户端进行数据导入，因此在导入数据时 LocalOpt 应设置成 Local` in  https://www.bookstack.cn/read/TiDB-4.0/sql-statements-sql-statement-load-data.md).
Nevertheless, in Seatunnel Context, it should implement by a file source and tidb sink.
so it's hard to combine source and sink operations in one `TiDB Sink`. 

In addition, it can only support batch mode (no streaming) . 

As a result, I think it's not very appropriate to implement a tidb sink using `load data`.

**Comment by lhyundeadsoul** [comment]
According to @ic4y advice, https://github.com/apache/incubator-seatunnel/pull/2219#issuecomment-1191099404 If TiDB connector is almost similar to JDBC connector, that will be tough to maintain. I agree with him.

 There seems no further feature in connector-v1 TiDB connector either.

Do you have any idea about TiDB connector features that are beyond JDBC connector? @Hisoka-X @EricJoy2048 @CalvinKirs @ruanwenjun 
If not, I suggest removing TiDB connector in v2 https://github.com/apache/incubator-seatunnel/issues/1946#issuecomment-1169865090 @Hisoka-X

**Comment by Hisoka-X** [comment]
> According to @ic4y advice, [#2219 (comment)](https://github.com/apache/incubator-seatunnel/pull/2219#issuecomment-1191099404) If TiDB connector is almost similar to JDBC connector, that will be tough to maintain. I agree with him.
> 
> There seems no further feature in connector-v1 TiDB connector either.
> 
> Do you have any idea about TiDB connector features that are beyond JDBC connector? @Hisoka-X @EricJoy2048 @CalvinKirs @ruanwenjun If not, I suggest removing TiDB connector in v2 [#1946 (comment)](https://github.com/apache/incubator-seatunnel/issues/1946#issuecomment-1169865090) @Hisoka-X

I agree with remove it. Thanks for your contribute.
