### ISSUE TITLE
[Feature][Seatunnel-translation] Support Spark3.3.x

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#2189]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support spark3.3.x

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaomin1423** [comment]
Hello, is this going on? I am interested in it. @CalvinKirs

**Comment by zhaomin1423** [comment]
we can change the project structure in seatunnel-translation-spark, because there are some common class using by different spark version. So, firstly, I want to add a seatunnel-translation-spark/seatunnel-translation-spark-common module. what do you think？ @CalvinKirs

**Comment by zhaomin1423** [comment]
I will raise a umbrella issue about support spark-3.x.

**Comment by liugddx** [comment]
#3984
