### ISSUE TITLE
[Bug] [spark-connector-v2-example] No class found

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#2191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Running spark-connector-v2-example in idea develop environment failed, the error as the following image:

![image](https://user-images.githubusercontent.com/51053924/179434729-4c41e84e-6b0e-4eb8-a90f-e18a9a4558a8.png)

I think it maybe the dependencies in pom has some problems, I try to add the 3.0.X  `janino` dependency in pom and fixed it.

In whole project I see it had been added the janino dependency in pom, but the version is `3.1.X`, maybe the `org/codehaus/janino/InternalCompilerException` not be contained in `3.1.X`

In my option, we should add the `janino` 3.0.X dependency in pom.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
Caused by: java.lang.ClassNotFoundException: org.codehaus.janino.InternalCompilerException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 47 more
```

### Screenshots

![image](https://user-images.githubusercontent.com/51053924/179435232-86392bd4-8d01-41bc-8ef0-cf8a05e50c1b.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
@CalvinKirs In hive-v2 connector (#2123 )changed this dependency's version and add to dependencyManagement. I think we should remove this in dependencyManagement. Then hive-v2 define the version in own pom. After this done spark's codehaus version will handle by itself.

**Comment by CalvinKirs** [comment]
> @CalvinKirs In hive-v2 connector (#2123 )changed this dependency's version and add to dependencyManagement. I think we should remove this in dependencyManagement. Then hive-v2 define the version in own pom. After this done spark's codehaus version will handle by itself.

+1.

**Comment by TyrantLucifer** [comment]
Hi, @CalvinKirs @Hisoka-X , I have submitted pr #2192,  please review. Thank you!
