### ISSUE TITLE
[STIP-3] [Server design][st-engine] st new engine server design

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#2210]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As shown below

Use Hazelcast's NodeExtension to extend the implementation of the engine, relying on Hazelcast dynamic scaling, automatic master selection, and distributed memory.
The gray part in the figure is hezalcast, and the blue part is ST-engine.

job submit：
The client submits a job to the ST-Service of the Master node, Job generates a physical execution plan Task in ST-Service and submits it to ST-Service of other nodes in the cluster for execution.
Information such as its job status is maintained in Hazelcast's Imap (distributed storage).

fault tolerance:
The ST-Service instance is stateless (the state is stored in Hazelcast's distributed storage), so when the Master node hangs up. Hazelcast will automatically elect another node as the Master, and the ST-Service on this node will continue to provide services.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/83933160/179723763-7fff536c-8a83-4b1e-869e-bdd8f4675a04.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Could the content of your pictures be modified into English?
