### ISSUE TITLE
[Bug] [Doc] SeaTunnel website have deadLink

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The `concept/Intro to config file` page in seatunnel website have some link to connector. But it's not work at now. We need fix it.
![image](https://user-images.githubusercontent.com/32387433/179972056-f4cb8806-00d2-4156-bd35-55befca1574f.png)
![image](https://user-images.githubusercontent.com/32387433/179972127-73c4d1fd-878f-4b4e-939a-9843682d8fc8.png)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PrajwalBorkar** [comment]
I like to work on this issue. I think these links [source of tunnel](https://seatunnel.apache.org/docs/2.1.2/category/source) & [supported links](https://seatunnel.apache.org/docs/2.1.2/category/sink) should be replaced.

**Comment by Hisoka-X** [comment]
> I like to work on this issue. I think these links [source of tunnel](https://seatunnel.apache.org/docs/2.1.2/category/source) & [supported links](https://seatunnel.apache.org/docs/2.1.2/category/sink) should be replaced.

Great, I assgined to you

**Comment by PrajwalBorkar** [comment]
Are these links are correct so I can replace also for transform what should be replacement?

**Comment by Hisoka-X** [comment]
Maybe you can create a new page about all transform like this: https://seatunnel.apache.org/docs/2.1.2/category/source. Or just use transform common options page.

**Comment by PrajwalBorkar** [comment]
The links are correct in github just it is not pointed to specific file. Instead of that it is pointed to folder and here https://seatunnel.apache.org/docs/2.1.2/category/source  path has category folder instead of connector. But Im not able to change to category in github.

**Comment by Hisoka-X** [comment]
> The links are correct in github just it is not pointed to specific file. Instead of that it is pointed to folder and here https://seatunnel.apache.org/docs/2.1.2/category/source path has category folder instead of connector. But Im not able to change to category in github.

Hi, @CalvinKirs  Can you help for this?

**Comment by CalvinKirs** [comment]
> > The links are correct in github just it is not pointed to specific file. Instead of that it is pointed to folder and here https://seatunnel.apache.org/docs/2.1.2/category/source path has category folder instead of connector. But Im not able to change to category in github.
> 
> Hi, @CalvinKirs Can you help for this?

I'm sorry, but I'm not familiar with it. @zhongjiajie  Do you have any suggestions

**Comment by MRYOG** [comment]
https://seatunnel.incubator.apache.org/docs/2.1.3/category/transform

**Comment by MRYOG** [comment]
现在的链接：https://seatunnel.incubator.apache.org/docs/2.1.3/transform
改成：https://seatunnel.incubator.apache.org/docs/2.1.3/category/transform

**Comment by MRYOG** [comment]
now link ：https://seatunnel.incubator.apache.org/docs/2.1.3/transform
replace ：https://seatunnel.incubator.apache.org/docs/2.1.3/category/transform

**Comment by MRYOG** [comment]
> now link ：https://seatunnel.incubator.apache.org/docs/2.1.3/transform
> replace ：https://seatunnel.incubator.apache.org/docs/2.1.3/category/transform

 Transform of SeaTunnel
