### ISSUE TITLE
[Connector-V2] Add Sentry Sink Connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2244]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

https://sentry.io/welcome/

Sentry is a Application monitoring and Error Tracking software.

Here is some doc can help to add sentry sink connector.
https://docs.sentry.io/platforms/java/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@CalvinKirs  @Hisoka-X  please add it to https://github.com/apache/incubator-seatunnel/issues/1946

**Comment by Saintyang** [comment]
I can work for this issue

**Comment by Hisoka-X** [comment]
> I can work for this issue

Great, I assgined to you.

**Comment by Hisoka-X** [comment]
Closed by #2584
