### ISSUE TITLE
[Feature] [SeaTunnel] Delete .idea directory

### ISSUE THREAD

**Issue by MRYOG** [apache/seatunnel#2258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

.gitignore file found .idea and .idea/* , but project already have .idea directory
If the user clone project for the first time , user can not find package and  must be deleted manually to compile

### SeaTunnel Version

All version

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
None
```

### Error Exception

```log
git clone project can not find packages
```

### Screenshots

![image](https://user-images.githubusercontent.com/10381662/180681882-73c13434-cccc-498f-a20b-765c709ad2ec.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
What you need to deal with is the gitingore file.

**Comment by CalvinKirs** [comment]
https://github.com/apache/incubator-seatunnel/pull/2117/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R16  This PR incorrectly modifies the gitignore file, just restore it.

**Comment by CalvinKirs** [comment]
please modify your PR title.thx

**Comment by Hisoka-X** [comment]
![image](https://user-images.githubusercontent.com/32387433/180707765-0a34510f-3cb5-4171-8c46-cb015d76d898.png)
@CalvinKirs  also should delete `.idea` file

**Comment by CalvinKirs** [comment]
> ![image](https://user-images.githubusercontent.com/32387433/180707765-0a34510f-3cb5-4171-8c46-cb015d76d898.png) @CalvinKirs also should delete `.idea` file

https://github.com/apache/incubator-seatunnel/pull/805 you can refer this.

**Comment by MRYOG** [comment]
I think .idea directory ,it is a local cache directory , if commit need some VCS ,  it should be in the doc/Contribution/Set Up Develop Environment . tell developer need config VCS .
