### ISSUE TITLE
[STIP-4] [ST-Engine][LogicalPlan] Generate LogicalPlan from JobConfig file

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2261]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We define job pipeline by job config file, So the first thing the SeaTunnelClient need to do parse the job config file and generate the action list. `action` is similar to the `operator` in Flink, It is an encapsulation of the `SeaTunnel API`. An action contains an instance of `SeaTunnelSource` or `SeaTunnelTransform` or `SeaTunnelSink`. Every action need to know the upstream of it self.
```
public interface Action extends Serializable {
    @NonNull
    String name();

    void setName(@NonNull String name);

    @NonNull
    List<Action> upstream();

    void addUpstream(@NonNull Action action);
}
```

We support `SourceAction` 、`SinkAction` and `TransformAction` yet.

### We have two profile to parse job config file. 

If there is only one Source and one Sink and at most one Transform, We simply build actions pipeline in the following order.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/32193458/180715841-f3a8c181-ff95-44b4-8b63-89c7a38f4769.png">

If there are multiple sources or multiple transforms or multiple sink, We will rely on `source_table_name` and `result_table_name` to build actions pipeline. So in this case `result_table_name` is necessary for the `Source Connector` and all of `result_table_name` and `source_table_name` are necessary for `Transform Connector`.
By the end, `source_table_name` is necessary for Sink Connector.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/32193458/180717783-cbd581c0-a24c-4a3e-a037-c0766b7305ec.png">

### Parallelism

In SeaTunnel Engine, only `Source` and `PartitionTransform` Connector support set `parallelism`. The action which can not set `parallelism` will extends the upstream action `parallelism`. If an action have more than one upstream action, The `parallelism` of this action is the sum of the parallelism of its upstream action. Because if an action's `parallelism` equals to it's upstream's `parallelism`, the action can be chain into it's upstream action and run in a same subtask.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/32193458/180763230-57b6f14a-cc39-49b4-b4da-c06aafc39350.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2013650523** [comment]
![image](https://user-images.githubusercontent.com/81779971/181260051-cde120da-6195-459a-b250-a2a4f5c2caa1.png)
hi ,please Why does the parallelism of the parallel transformation change from 4 to 2?

**Comment by EricJoy2048** [comment]
> ![image](https://user-images.githubusercontent.com/81779971/181260051-cde120da-6195-459a-b250-a2a4f5c2caa1.png) hi ,please Why does the parallelism of the parallel transformation change from 4 to 2?

In our design, Only `Source` and `PartitionTransform` Connector can set parallelism. The `PartitionTransform` Connector is used to repartition data and `parallelism` is the target partition number.

**Comment by ashulin** [comment]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/36807946/181454461-68803243-9674-4868-801e-9e9afd6ede29.png">

I can't understand what `PartitionTransform` does in the diagram.
If there is a mechanism for `Transform4` to distribute data to `PartitionTransform`, then why don't we distribute to `Sink` directly?
Wouldn't it be simpler to let the user specify the parallelism of the `Sink` in this case?
