### ISSUE TITLE
[ST-Engine][Design] The Design of LogicalPlan to PhysicalPlan

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2269]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

SeaTunnel engine will receive the logical plan sent by the client, and the engine needs to convert it into a physical plan that can be directly executed. Therefore, it is necessary to process the logical execution plan and generate a physical plan through conversion. The specific process is as follows:
1. Logical Plan
![image](https://user-images.githubusercontent.com/32387433/184818874-e35bd746-fe8a-4807-b454-8ef24bbe2dfd.png)
Received the logical plan, we need to remove redundant Actions, and verifying the Schema(Transform2 and Transform 5 should be same)
2. Execution Plan
![image](https://user-images.githubusercontent.com/32387433/184818941-c82a8879-8610-4000-8157-c28f346ee319.png)
While converting to an execution plan: 
- Transforms need to be merged, and the basis for merging is whether the data will be split after the Transform. 
- Convert Shuffle Action to Queue
- Convert to multi pipeline
3. Physical Plan
![image](https://user-images.githubusercontent.com/32387433/184819127-0f69977b-8f5b-4e59-908c-ee5f303ce3d0.png)
We will split the Pipeline into separate executable tasks according to the degree of parallelism, also need add SourceSplitEnumerator and SinkAggregatedCommitter task
After this, can send task to task execution service. Then task can run normally.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2013650523** [comment]
hi, Excuse me,Let me ask you a question, Why is the data queue designed to decouple source and sink?  Is the data cached in the queue when the source fails?

**Comment by Hisoka-X** [comment]
> hi, Excuse me,Let me ask you a question, Why is the data queue designed to decouple source and sink? Is the data cached in the queue when the source fails?

1. The Queue will create when use shuffle transform (at now call partition transform). Used for data shuffle and change parallelism
2. The cache feature you mentioned will be added later
