### ISSUE TITLE
[STIP-6] [ST-Engine][Checkpoint] The design of Checkpoint

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2274]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Backgroud & Motivation

I think the **[[Chandy-Lamport algorithm](https://en.wikipedia.org/wiki/Chandy%E2%80%93Lamport_algorithm)](https://en.wikipedia.org/wiki/Chandy%E2%80%93Lamport_algorithm)** can be used to implement distributed state snapshots (hereinafter referred to as *Checkpoint*);

Based on the current Source & Sink V2 API of SeaTunnel, the required features are:

1. Checkpoint supports both real-time and offline operations;

    - When the job restored, only the Subtask (Vertex of the execution graph) that has not been completed is restored;
2. Jobs can be restored normally when the user changes the parallelism of the connector;

We found that the Checkpoint implemented by Flink and Spark has a large scope of impact: When a job has multiple tables, a table failure will affect the entire job;
So we expect to be able to improve based on this problem:

3.   Minimize the unit of Checkpoint execution and reduce the impact of restore;

### Overall Design

![SeaTunnel Snapshot](https://user-images.githubusercontent.com/36807946/181134432-5faf879a-992f-4569-b703-a488c35c0dbe.png)

1.   Convert the DAG to execution graph, and use [[Topological Sorting](https://en.wikipedia.org/wiki/Topological_sorting)](https://en.wikipedia.org/wiki/Topological_sorting) to identify the execution graph as n (n >= 1) pipelines;
2.   CheckpointCoordinator creates a separate CheckpointTask for each Pipeline;

     - CheckpointTask will manage its own associated pipeline, and the restore unit is pipeline;
3.   Jobs can be restored normally when the user changes the parallelism of the connector;
4.   For the completed subtask, Checkpoint will be performed normally, and the State will be retained (Apache SeaTunel will not have a super large state, such as Join);

     - During the Restore phase, the Completed Subtask will not be deployed;

### The Execution Unit (Pipeline)

Case: Two Kafka tables are written to the corresponding HDFS.

Job DAG:

![SeaTunnel Snapshot-DAG](https://user-images.githubusercontent.com/36807946/181134496-01a4cdeb-0b69-4aaa-b302-2b347e85f8e9.png)

Execution Graph:

![SeaTunnel Snapshot-ExecutionPlan](https://user-images.githubusercontent.com/36807946/181134521-8f22f8df-f805-4037-ab16-88a57b82033c.png)

By topological sorting, we can get

{Enumerator#1, Reader#1#1, Reader#1#2, Writer#1#1, Writer#1#2, AggregatedCommitter#1},

{Enumerator#2, Reader#2#1, Writer#2#1, AggregatedCommitter#2}

two queues, namely two Pipelines;

![SeaTunnel Snapshot-Pipeline](https://user-images.githubusercontent.com/36807946/181134544-cd3f8670-60ca-4682-a4eb-c05359a13fe0.png)

### Support for Completed Subtask

Case: Two MySQL instances are sub-database and sub-table, which are synchronized to other storage after aggregation;

![SeaTunnel Snapshot-Finished1](https://user-images.githubusercontent.com/36807946/181134554-041fe722-6178-4323-8842-7512842c4e9b.png)

We assume that the amount of data of instance Source#2 is smaller, and enter the Completed Status first;

![SeaTunnel Snapshot-Finished2](https://user-images.githubusercontent.com/36807946/181134563-3f91e934-06d5-4f51-a8cf-38b102d86a98.png)

At this time, if the pipeline fails/restarts-manually, the Subtask of Source#2 can not be deployed in the Restore phase to reduce resource usage;

![SeaTunnel Snapshot-Finished3](https://user-images.githubusercontent.com/36807946/181134568-a2839e19-7c4a-4570-b954-b516954c62a9.png)

#### Plan A: Keyed State Redistribute[currently expected]

![Checkpoint Source Plan-B 2](https://user-images.githubusercontent.com/36807946/181144118-e103b4ec-e409-4fd4-8076-646603312ed8.png)

In the checkpoint execution phase, the ID of the subtask is used as the state key and saved to the state backend;

In the checkpoint restore phase, use `subtaskId = key % parallelism` to calculate the restored subtask ID;

##### SinkState

For the state of sink, this satisfies the requirements;

##### SourceState

For the state of the source, the subtask of the source still needs to continue processing;

**The following is the job of SourceTask, which is not managed by Checkpoint;**

We assume that the source is kafka, the task has 1 topic and 6 partitions, and the parallelism is changed from 2 to 3. After restored, the following figure is shown.

![SourceState-1](https://user-images.githubusercontent.com/36807946/181409017-ea49e874-0962-4938-98ee-fbb42c9862ce.png)

We found that splits cannot be assigned to new readers;
In order for the new reader to be assigned to split, we need the ReaderTask to use `SourceSplitEnumerator#addSplitsBack` to return the split to the enumerator;

![SourceState-2](https://user-images.githubusercontent.com/36807946/181409035-9c28c2ad-a52a-4cf3-b274-ddeb03b09ad4.png)

The split is reassigned by the enumerator, and the restore phase is completed;

![SourceState-3](https://user-images.githubusercontent.com/36807946/181409047-c483bf22-aa3f-4f53-84ba-878479aadb00.png)

#### Plan B: Uniform state redistribute

![Checkpoint Source Plan-B 1](https://user-images.githubusercontent.com/36807946/181144045-966d20e4-66ba-4718-88ff-879a580edce8.png)

#### Deprecated Plan

Enumerator and readers of special processing source: 

![Checkpoint Source Plan-A 1](https://user-images.githubusercontent.com/36807946/181140549-8037e70c-27d1-4918-928a-caf7d3fa79e5.png)

In the checkpoint execution phase, the response barrier is the same as that of a normal task,

![Checkpoint Source Plan-A 2](https://user-images.githubusercontent.com/36807946/181140586-6db42ec9-4f67-46fd-9201-6802512d5fa5.png)

During the Restore phase, the state of the reader will be restored to the enumerator;

Use the `SourceSplitEnumerator#addSplitsBack` method to restore the split state, and then the enumerator can assign the split to the reader whose parallelism has been changed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/32193458/181148775-705332e2-d997-4a50-9cd9-aa904be3af3d.png">

Can it be like this?

<img width="881" alt="image" src="https://user-images.githubusercontent.com/32193458/181149570-4180f833-d399-4ac0-88d9-7c6428aed989.png">

**Comment by ashulin** [comment]
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/32193458/181148775-705332e2-d997-4a50-9cd9-aa904be3af3d.png">
> 
> Can it be like this?
> 
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/32193458/181149570-4180f833-d399-4ac0-88d9-7c6428aed989.png">

No, it's different. The above writer has multiple input subtasks, which is to reduce the resource usage on the sink side;

**Comment by EricJoy2048** [comment]
> > <img alt="image" width="835" src="https://user-images.githubusercontent.com/32193458/181148775-705332e2-d997-4a50-9cd9-aa904be3af3d.png">
> > Can it be like this?
> > <img alt="image" width="881" src="https://user-images.githubusercontent.com/32193458/181149570-4180f833-d399-4ac0-88d9-7c6428aed989.png">
> 
> No, it's different. The above writer has multiple input subtasks, which is to reduce the resource usage on the sink side;

From this design https://github.com/apache/incubator-seatunnel/issues/2261 we can know. Now, we only support `Source` and `PartitionTransform` operator to set parallelism, The parallelism of other connectors is equal to the sum of the parallelism of its upstream operators. So, in this case the parallelism of the sink operator is 3(One source have 2 parallelism and another one have 1 parallelism) not 2. Then, we have 3 source subtask and 3 sink subtask, I think it can replace to tow pipeline.

Or, do we have any other more suitable design for parallelism?

**Comment by ashulin** [comment]
@EricJoy2048 Now how do we deal with the union of multiple upstream operators? That's the same thing as the following
<img width="343" alt="image" src="https://user-images.githubusercontent.com/36807946/181452486-e150e98c-7af7-425c-8afd-e53752677c99.png">
Users need `union (all)` post-processing, and we cannot separate them

**Comment by EricJoy2048** [comment]
> @EricJoy2048 Now how do we deal with the union of multiple upstream operators? That's the same thing as the following <img alt="image" width="343" src="https://user-images.githubusercontent.com/36807946/181452486-e150e98c-7af7-425c-8afd-e53752677c99.png"> Users need `union (all)` post-processing, and we cannot separate them

@Hisoka-X

**Comment by Hisoka-X** [comment]
> @EricJoy2048 Now how do we deal with the union of multiple upstream operators? That's the same thing as the following <img alt="image" width="343" src="https://user-images.githubusercontent.com/36807946/181452486-e150e98c-7af7-425c-8afd-e53752677c99.png"> Users need `union (all)` post-processing, and we cannot separate them

We should create a special transform `union`. It can union all upstream data. Then `union` will have parallelism parameter, take this picture as an example, if parallelism = 8 (4+4), just send data to next action, if parallelism != 8, we should use queue( like Partition Transform) to change parallelism.
