### ISSUE TITLE
[Improve][UT] Upgrade junit to 5.+

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2283]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, we still use junit 4.+ in our repo, I hope we can upgrade to [Junit 5.+](https://junit.org/junit5/docs/current/user-guide/#writing-tests), then we can easy to write the UT, JUnit 5 provide some useful feature, e.g. `@ParameterizedTest`, `@EnabledOnOs`,...

Currently we have a small number of test cases and it is easy to upgrade dependencies.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
CC @Hisoka-X @CalvinKirs @ruanwenjun

**Comment by CalvinKirs** [comment]
+1，5 have  many highlights

**Comment by EricJoy2048** [comment]
+1

**Comment by ruanwenjun** [comment]
+1, it would be great if we can upgrade to junit 5+

**Comment by ashulin** [comment]
Because [Testcontainers are tightly coupled with JUnit4](https://github.com/testcontainers/testcontainers-java/issues/970), we can't completely remove junit4, maybe we need a check style rule to banned the import of junit4 class.
