### ISSUE TITLE
[Bug] [connector-file] avro version conflicts

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#2289]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The avro version that contained in flink-avro is 1.10.0, but the avro version that contained in seatunnel main pom is 1.8.2.

![image](https://user-images.githubusercontent.com/51053924/181495842-6cbc13d0-fc85-4fd1-88e6-d0cb2a82a01d.png)

![image](https://user-images.githubusercontent.com/51053924/181496101-45c22a5d-1efc-4b8a-aff6-86fc89a87d22.png)

When we try to use file connector writer parquet file in flink, it will be conflicted between this two different version and throw `NoSuchMethod` exception.

In order to solve this problem, I think we have two plans to unified avro version:

1. Exclude avro in seatunnel-flink-api and include avro 1.8.2 version in it
2. Update parquet-avro version from 1.10.0 to 1.12.0 in main pom, this will include avro 1.10.1 version, but it might be conflicted with spark-core, we also should exclude avro in spark-core

I think the first solution is best, what do you think about? @CalvinKirs  @Hisoka-X 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
NoSuchMethod Exception
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
![image](https://user-images.githubusercontent.com/32387433/181503188-c3618d68-7640-49ee-becb-a552e9ec1799.png)
I checked root pom. The version already are 1.10.0, any thing wrong with me? Or you should update local code.

**Comment by Hisoka-X** [comment]
Sorry, I missed something.
> Exclude avro in seatunnel-flink-api and include avro 1.8.2 version in it

Agree with you, the first one better.

**Comment by TyrantLucifer** [comment]
pr #2294 , @Hisoka-X ,please review
