### ISSUE TITLE
[Feature][Connector-V2-Hive] Add parquet file format support to Hive Sink

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2296]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I found we already supported Parquet File Sink now, For `Hive Sink` we only need add some code in `HiveSinkConfig` and get the target schema from hivemetastore. Then deal with the mapping relationship between the field type in `SeaTunnelRowType ` and the field type in hive table, and modify the field type in `SeaTunnelRowType ` to the type in hive table.

After completing the above modifications, we have completed the support of hive sink connector for parquet table.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaomin1423** [comment]
I am willing to do it.
