### ISSUE TITLE
download backup2 which depneds on backup1 failed

### ISSUE THREAD

**Issue by wzisheng** [apache/seatunnel#2300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

node1:
> clickhouse-backup create --table default.test1 backup1
> clickhouse-backup create --table default.test1 backup2
> clickhouse-backup  upload backuptest1
> clickhouse-backup  upload backuptest2 --diff-from backuptest1

node2:
> clickhouse-backup  download backuptest2
2022/07/29 18:14:57.065003 error one of Download go-routine return error: one of downloadDiffParts go-routine return error:  not found on remote storage

### SeaTunnel Version

1.49

### SeaTunnel Config

```conf
default
```

### Running Command

```shell
see above
```

### Error Exception

```log
2022/07/29 18:14:57.065003 error one of Download go-routine return error: one of downloadDiffParts go-routine return error:  not found on remote storage
```

### Screenshots

![Uploading image.png…]()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Sorry, I don't understand you means, it seems that not seatunnel bug... Are you sure you submitted it correctly?

**Comment by wzisheng** [comment]
sorry， my bad...
