### ISSUE TITLE
[STIP-9] [ST-Engine][Scheduler] Design of TaskGroup Scheduler

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2339]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

From https://github.com/apache/incubator-seatunnel/issues/2269 we know the `JobMaster` will create `PhysicalPlan` for Job. Then the `JobMaster` will deploy the `TaskGroup` use `Scheduler`. 

Here is some design of Scheduler

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/32193458/182339795-7d80f5ae-5dac-4875-b75f-cd1d6f7c8936.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xuzhangtian** [comment]
Hi, in the above example, the tasks within the TaskGroup appear to have an order, but in the code implementation of TaskGroupDefaultImpl, the tasks are stored using a Map, which clearly does not maintain any order. So, how does TaskGroup ensure the execution order of tasks?

**Comment by xuzhangtian** [comment]
> Hi, in the above example, the tasks within the TaskGroup appear to have an order, but in the code implementation of TaskGroupDefaultImpl, the tasks are stored using a Map, which clearly does not maintain any order. So, how does TaskGroup ensure the execution order of tasks?

Sorry I found it in Issues #2279.
