### ISSUE TITLE
mysql 同步hive 支持自动创建hive 表吗？

### ISSUE THREAD

**Issue by melin** [apache/seatunnel#2346]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

mysql 同步hive 支持自动创建hive 表吗？有时候数据库表字段很多，创建表映射字段类型，业务人员难度比较大，创建hive 表难度比较大

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Currently seatunnel is not support auto create table before data synchronization.

**Comment by Hisoka-X** [comment]
This is a feature we can do, if you want, you can contribute this.
