### ISSUE TITLE
[Connector-V2][JDBC-connector] Add more databases that support JDBC

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#2367]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently the JDBC connector supports mysql and Postgres, and we plan to support more.
as follows:
|  NO   | Database | Source/Sink  | Contributer  | Status  |
|  ----  | ----  | ----  | ----  | ----  |
| 1  | Mysql | sink  | @ic4y  | Done | 
| 2 | Mysql | source  | @ic4y  | Done | 
| 3  | Postgres | sink  | @ic4y  | Done | 
| 4  | Postgres | source  | @ic4y  | Done | 
| 3  | SQLServer | sink  |    |  | 
| 4  | SQLServer | source  |    |  | 
| 5  | Orecal | sink  |    |  | 
| 6  | Orecal | source  |    |  | 
| 7  | GaussDB | sink  |    |  | 
| 8  | GaussDB | source  |    |  | 
| 9  | DM达梦 | sink  | @laglangyue   |  | 
| 10  | DM达梦 | source  |  @laglangyue  |  | 
| 11  | DB2 | sink  |  @laglangyue  |  | 
| 12  | DB2 | source  |  @laglangyue  |  | 

Additions and contributions are welcome.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
I want try it for dm first

**Comment by laglangyue** [comment]
Could you assigne the DB2 to me ，and I am willing to do the weekend.
 @Hisoka-X

**Comment by ic4y** [comment]
@lhyundeadsoul 
Are you interested in implementing TiDB under JDBC Connector?

**Comment by lhyundeadsoul** [comment]
> @lhyundeadsoul Are you interested in implementing TiDB under JDBC Connector?

TiDB is as same as MySQL.  
This has been discussed:
https://github.com/apache/incubator-seatunnel/issues/1946#issuecomment-1211797586

**Comment by ic4y** [comment]
> 

You are right, thanks for the reminder. TiDB uses the mysql driver.

**Comment by cyrusmaster** [comment]
@laglangyue   请问达梦连接器现在可用么 ，有没有说明文档
