### ISSUE TITLE
[Feature][seatunnel-connectors-v2][connector-kafka] Kafka supports custom schema

### ISSUE THREAD

**Issue by eyys** [apache/seatunnel#2371]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

English:
The original Kafka connector supports custom schema. The current V2 connector does not support custom schema

中文：
原始的Kafka连接器支持自定义模式。当前的V2连接器不支持自定义schema

### Usage Scenario

Kafka Source user-defined data structures

### Related issues

none

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Yes, this is very import function we should implement. If you can do this will be very helpful

**Comment by hailin0** [comment]
I want to discuss how to define fields schema configuration for connector in seatunnel

I see use case from flink:
`create table x (
field1 bigint,
field2 string,
......
) with (
format: 'xxx'
)`

Connector selectd `xxx` format factory to convert message data format to  `row[fleid1<bigint>,field2<string>]`.


How should it be defined in seatunnel?
e.g:
`
source {
  KafkaSource {
     format = xxx
     format_schema = [{"name": "field1", "data_type": "bigint"}  , {"name": "field2", "data_type": "string"}]
   }
}
`

**Comment by Hisoka-X** [comment]
Yes, it is a important thing that decide how define schema. Please send a discuss mail in dev@seatunnel.apache.org. And attach your idea.

**Comment by Hisoka-X** [comment]
> I want to discuss how to define fields schema configuration for connector in seatunnel
> 
> I see use case from flink: `create table x ( field1 bigint, field2 string, ...... ) with ( format: 'xxx' )`
> 
> Connector selectd `xxx` format factory to convert message data format to `row[fleid1<bigint>,field2<string>]`.
> 
> How should it be defined in seatunnel? e.g: `source { KafkaSource { format = xxx format_schema = [{"name": "field1", "data_type": "bigint"} , {"name": "field2", "data_type": "string"}] } }`

cc @ashulin

**Comment by ashulin** [comment]
https://github.com/apache/incubator-seatunnel/issues/2299

**Comment by EricJoy2048** [comment]
cc @TyrantLucifer

**Comment by ashulin** [comment]
This is a common feature, for example, kafka, HTTP, File, Pulsar, etc;
My opinion is to conform to the habit of SQL;

```conf
# conf file
Source {
    schema {
        field = "STRING"
        field2 = "INT"
        field3 = "DECIMAL(30, 3)"
    }
}
```

**Comment by TyrantLucifer** [comment]
> This is a common feature, for example, kafka, HTTP, File, Pulsar, etc; My opinion is to conform to the habit of SQL;
> 
> ```
> # conf file
> Source {
>     schema {
>         field = "STRING"
>         field2 = "INT"
>         field3 = "DECIMAL(30, 3)"
>     }
> }
> ```

I think it's a good idea that add a common feature in connector to support user-defined schema. In my option, I think we can add a new config option `schema` in all source connector source configs and for each connector they can parse their own schema in `getProducedType` method. The implement function of parsing `schema` we can add it in module `seatunnel-common`. And I agree with your advice @ashulin to conform schema type to the habit of SQL the same as defined in code.

![image](https://user-images.githubusercontent.com/51053924/183329465-58f5c04d-bffc-43ff-81df-ed15837e823d.png)

**Comment by hailin0** [comment]
Another problem is missing metadata of mq connector rowdata.
e.g:  partition、timestamp、key、headers

`
public ProducerRecord(String topic, Integer partition, Long timestamp, K key, V value, Iterable<Header> headers)
`

I see use case from flink: 
https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/DynamicKafkaRecordSerializationSchema.java#L119

**Comment by TyrantLucifer** [comment]
> > This is a common feature, for example, kafka, HTTP, File, Pulsar, etc; My opinion is to conform to the habit of SQL;
> > ```
> > # conf file
> > Source {
> >     schema {
> >         field = "STRING"
> >         field2 = "INT"
> >         field3 = "DECIMAL(30, 3)"
> >     }
> > }
> > ```
> 
> I think it's a good idea that add a common feature in connector to support user-defined schema. In my option, I think we can add a new config option `schema` in all source connector source configs and for each connector they can parse their own schema in `getProducedType` method. The implement function of parsing `schema` we can add it in module `seatunnel-common`. And I agree with your advice @ashulin to conform schema type to the habit of SQL the same as defined in code.
> 
> ![image](https://user-images.githubusercontent.com/51053924/183329465-58f5c04d-bffc-43ff-81df-ed15837e823d.png)

By the way, the row data format information also should defined in source connector. The final source config as the following:

```hcon
Source {
   Kafka {
     schema {
       fields {
          field = "STRING"
          field2 = "INT"
          field3 = "DECIMAL(30, 3)"
       }
        format = "json" // format = "text"
     }
  }
}

```
In most use cases, I think we can support `json` or `text`, if we assign `text`, we also assign `delimiter` in config file.

**Comment by eyys** [comment]
> 
Where should the text type column delimiter be defined here
Is something like that okay?
怎么定义txt类型的列分隔符，这样定义是否可以？
```
Kafka {
  consumer.bootstrap.servers = "127.0.0.1:9092"
  consumer.group.id = "seatunnel5"
  topic = test
  result_table_name = test
  schema {
    fields {
      name = string
      age = int
    }
    format = "json" // format = "text"
    text.delimiter = ","
  }
}
```

**Comment by TyrantLucifer** [comment]
This feature is in development, please waiting pr.

**Comment by TyrantLucifer** [comment]
> This feature is in development, please waiting pr.

@eyys Please refer to #2439 #2436, look forward to your contribution.
