### ISSUE TITLE
[Feature][ReadMe] Mixed use of Chinese and English punctuation

### ISSUE THREAD

**Issue by fuchanghai** [apache/seatunnel#2372]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Mixed use of Chinese and English punctuation. Should we make rules for punctuation in documents?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
According to the specification, we should do this. If you find this kind of problem, you can create a PR to fix it. Any contribution that makes our documentation better is welcome

**Comment by fuchanghai** [comment]
@Hisoka-X Whether the punctuation of Chinese documents is in Chinese or English (,or，)

**Comment by Hisoka-X** [comment]
At this stage, we only care about English documents. Check this https://lists.apache.org/thread/j1vo1yccqp79bv69bzokbqq3n58zytql
