### ISSUE TITLE
[Doc][Connector/Transform] Connector/Transform document have some empty description

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2373]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/32387433/183030275-7387f16e-b900-4655-a076-72f59c43305f.png)
Through the pictures you can find a lot of empty placeholder descriptions, which hopefully can be turned into specific descriptions for each component

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
pr #2375 , @Hisoka-X  please review, thx.
