### ISSUE TITLE
[License Issue] Please update your source codes' license 

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#2397]
`org.apache.seatunnel.connectors.seatunnel.jdbc.internal.split.JdbcNumericBetweenParametersProvider`

I noticed this code, it is exactly the same as Flink(`org.apache.flink.connector.jdbc.split.JdbcNumericBetweenParametersProvider`). I checked that the author is not the same person, but there is no statement. So, you should update the source codes' LICENSE to indicate you have copied it from another project.

I'm not sure if there are other similar codes. I just came across this by accident.

**Comment by EricJoy2048** [comment]
@ic4y  Please have a look.

**Comment by EricJoy2048** [comment]
@CalvinKirs  Can this issue be closed?
