### ISSUE TITLE
[STIP-10] [ST-Engine][JobHistoryStorage] Job History Storage Design

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2398]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now, We only record and maintain the status of jobs and job list in memory. If the server done, everything will lost. So
we need design the `Job History Storage` to save status and job list to disk( Or HDFS).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ic4y** [comment]
Let me do it

**Comment by EricJoy2048** [comment]
> Let me do it

Ok, Thank you

**Comment by ic4y** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/83933160/185138149-517b5d43-5b30-45db-865d-68888764b1a4.png">

**Cluster restart**
    When the cluster restarts, the Job State will be restored from the file system to Imap. At this time, SeatunnelServer only needs to take out the Job that needs to be resumed from Imap to resume execution.

**Master Drift**
When the Master node fails, the cluster will select another node as the Master at this time. At this time, it is necessary to restore the state of the JobMaster to continue processing tasks on the new node. The deployed Task will report the status to the new Master.

**Comment by sheng-jie** [comment]
@ic4y Any Progress  on that?
