### ISSUE TITLE
[Bug] [Connector-V2] java.math.BigDecimal cannot be cast to org.apache.spark.sql.types.Decimal

### ISSUE THREAD

**Issue by laglangyue** [apache/seatunnel#2405]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I was adapting connector-v2 and testing locally, I found some problems with decimal.
I modified the code of the fake of connector-v2 to support the decimal type, and then run 

org.apache.seatunnel.example.spark.v2.seatunnelapiexample, which repeats the error.

![image](https://user-images.githubusercontent.com/35491928/184492922-ecd9f4bb-e433-4416-b910-e450e7a70df6.png)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set spark configuration here
  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  #job.mode = BATCH
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  FakeSource {
    result_table_name = "fake"
    field_name = "name,age,timestamp,decimal"
  }

  # You can also use other input plugins, such as hdfs
  # hdfs {
  #   result_table_name = "accesslog"
  #   path = "hdfs://hadoop-cluster-01/nginx/accesslog"
  #   format = "json"
  # }

  # If you would like to get more information about how to configure seatunnel and see full list of input plugins,
  # please go to https://seatunnel.apache.org/docs/spark/configuration/source-plugins/Fake
}

transform {
  # split data by specific delimiter

  # you can also use other transform plugins, such as sql
  sql {
    sql = "select name,age,timestamp,decimal from fake"
    result_table_name = "sql"
  }

  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,

}

sink {
  Console {}

}
```

### Running Command

```shell
just in idea run the example
org.apache.seatunnel.example.spark.v2.seatunnelapiexample
```

### Error Exception

```log
at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:259)
	at org.apache.seatunnel.core.starter.spark.execution.SinkExecuteProcessor.execute(SinkExecuteProcessor.java:75)
	at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:60)
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:54)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.example.spark.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:43)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ClassCastException: java.math.BigDecimal cannot be cast to org.apache.spark.sql.types.Decimal
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getDecimal(rows.scala:45)
	at org.apache.spark.sql.catalyst.expressions.SpecificInternalRow.getDecimal(SpecificInternalRow.scala:193)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
```

### Java or Scala Version

8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
I'm still a novice in this project. I'm trying to solve it. It would be better if someone could help me

**Comment by laglangyue** [comment]
![image](https://user-images.githubusercontent.com/35491928/184494407-aebc4ad3-d138-4ba5-9f76-d3ffe9e7fa65.png)

**Comment by TyrantLucifer** [comment]
Because the schema of fake source connector is defined in code:

![image](https://user-images.githubusercontent.com/51053924/184496770-9ec4dd90-2b65-4688-a79a-1f758835f387.png)

So the data source should like the following:

```
name age timestamp

xiaoming 23 xxxxxxxxx
```

You try to use sql plugin to tranform data, but your sql has some problems, `decimal` not contained in data source. You can change your sql as the follwing:

```sql
select name,age from fake
```

**Comment by laglangyue** [comment]
> Because the schema of fake source connector is defined in code:
> 
> ![image](https://user-images.githubusercontent.com/51053924/184496770-9ec4dd90-2b65-4688-a79a-1f758835f387.png)
> 
> So the data source should like the following:
> 
> ```
> name age timestamp
> 
> xiaoming 23 xxxxxxxxx
> ```
> 
> You try to use sql plugin to tranform data, but your sql has some problems, `decimal` not contained in data source. You can change your sql as the follwing:
> 
> ```sql
> select name,age from fake
> ```

yes, but I modify this in local.

```java
  @Override
    public SeaTunnelRowType getProducedType() {
        return new SeaTunnelRowType(
            new String[]{"name", "age", "timestamp", "decimal"},
            new SeaTunnelDataType<?>[]{BasicType.STRING_TYPE, BasicType.INT_TYPE, BasicType.LONG_TYPE, new DecimalType(38, 18)});
    }
```

**Comment by TyrantLucifer** [comment]
> > Because the schema of fake source connector is defined in code:
> > ![image](https://user-images.githubusercontent.com/51053924/184496770-9ec4dd90-2b65-4688-a79a-1f758835f387.png)
> > So the data source should like the following:
> > ```
> > name age timestamp
> > 
> > xiaoming 23 xxxxxxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You try to use sql plugin to tranform data, but your sql has some problems, `decimal` not contained in data source. You can change your sql as the follwing:
> > ```sql
> > select name,age from fake
> > ```
> 
> yes, but I modify this in local.
> 
> ```java
>   @Override
>     public SeaTunnelRowType getProducedType() {
>         return new SeaTunnelRowType(
>             new String[]{"name", "age", "timestamp", "decimal"},
>             new SeaTunnelDataType<?>[]{BasicType.STRING_TYPE, BasicType.INT_TYPE, BasicType.LONG_TYPE, new DecimalType(38, 18)});
>     }
> ```

`decimal` is a token in sql language, you can change this key's name and try again. By the way, do you change the code in `FakeSourceReader` ?

![image](https://user-images.githubusercontent.com/51053924/184497588-dd81dcf8-d5d5-4226-afe7-01b3ccb52e02.png)

**Comment by laglangyue** [comment]
> > > Because the schema of fake source connector is defined in code:
> > > ![image](https://user-images.githubusercontent.com/51053924/184496770-9ec4dd90-2b65-4688-a79a-1f758835f387.png)
> > > So the data source should like the following:
> > > ```
> > > name age timestamp
> > > 
> > > xiaoming 23 xxxxxxxxx
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You try to use sql plugin to tranform data, but your sql has some problems, `decimal` not contained in data source. You can change your sql as the follwing:
> > > ```sql
> > > select name,age from fake
> > > ```
> > 
> > 
> > yes, but I modify this in local.
> > ```java
> >   @Override
> >     public SeaTunnelRowType getProducedType() {
> >         return new SeaTunnelRowType(
> >             new String[]{"name", "age", "timestamp", "decimal"},
> >             new SeaTunnelDataType<?>[]{BasicType.STRING_TYPE, BasicType.INT_TYPE, BasicType.LONG_TYPE, new DecimalType(38, 18)});
> >     }
> > ```
> 
> `decimal` is a token in sql language, you can change this key's name and try again. By the way, do you change the code in `FakeSourceReader` ?
> 
> ![image](https://user-images.githubusercontent.com/51053924/184497588-dd81dcf8-d5d5-4226-afe7-01b3ccb52e02.png)

yes I do it , and I submit a PR to optimize the fake connector, This exception is when seatunnel type is converted to sparktype。
In my PR，if the transform sql contained the column  `c_decimal` , the expection happended. if not ,it's ok.
https://github.com/apache/incubator-seatunnel/pull/2406/files

**Comment by TyrantLucifer** [comment]
pr #2408 fixed this problem, you can try again.

**Comment by laglangyue** [comment]
> pr #2408 fixed this problem, you can try again.
thx, very awesome.

**Comment by laglangyue** [comment]
> pr #2408 fixed this problem, you can try again.

it will be null writer to console

**Comment by TyrantLucifer** [comment]
> > pr #2408 fixed this problem, you can try again.
> 
> it will be null writer to console

In my local environment, it seems ok:

![image](https://user-images.githubusercontent.com/51053924/184502760-babb346f-4b5a-4a21-bb3e-8235dbc34242.png)

And this is my code:

![image](https://user-images.githubusercontent.com/51053924/184502782-fb5cd09a-05bc-4340-928b-154cf013f335.png)

![image](https://user-images.githubusercontent.com/51053924/184502798-b205eaaa-af2d-4055-9994-c98a8edf0a16.png)

**Comment by laglangyue** [comment]
> > > pr #2408 fixed this problem, you can try again.
> > 
> > 
> > it will be null writer to console
> 
> In my local environment, it seems ok:
> 
> ![image](https://user-images.githubusercontent.com/51053924/184502760-babb346f-4b5a-4a21-bb3e-8235dbc34242.png)
> 
> And this is my code:
> 
> ![image](https://user-images.githubusercontent.com/51053924/184502782-fb5cd09a-05bc-4340-928b-154cf013f335.png)
> 
> ![image](https://user-images.githubusercontent.com/51053924/184502798-b205eaaa-af2d-4055-9994-c98a8edf0a16.png)

yes, my data is so big that spark can't contain and will be null

**Comment by TyrantLucifer** [comment]
> > > > pr #2408 fixed this problem, you can try again.
> > > 
> > > 
> > > it will be null writer to console
> > 
> > 
> > In my local environment, it seems ok:
> > ![image](https://user-images.githubusercontent.com/51053924/184502760-babb346f-4b5a-4a21-bb3e-8235dbc34242.png)
> > And this is my code:
> > ![image](https://user-images.githubusercontent.com/51053924/184502782-fb5cd09a-05bc-4340-928b-154cf013f335.png)
> > ![image](https://user-images.githubusercontent.com/51053924/184502798-b205eaaa-af2d-4055-9994-c98a8edf0a16.png)
> 
> yes, my data is so big that spark can't contain and will be null

I didn't understand your means, could you please offer an example to me? BTW, if you can offer your origin code it could be better.

**Comment by laglangyue** [comment]
the type is new DecimalType(38, 18) and the data is BigDecimal.valueOf(RandomUtils.nextDouble(Float.MAX_VALUE, Double.MAX_VALUE))

**Comment by laglangyue** [comment]
> > > > > pr #2408 fixed this problem, you can try again.
> > > > 
> > > > 
> > > > it will be null writer to console
> > > 
> > > 
> > > In my local environment, it seems ok:
> > > ![image](https://user-images.githubusercontent.com/51053924/184502760-babb346f-4b5a-4a21-bb3e-8235dbc34242.png)
> > > And this is my code:
> > > ![image](https://user-images.githubusercontent.com/51053924/184502782-fb5cd09a-05bc-4340-928b-154cf013f335.png)
> > > ![image](https://user-images.githubusercontent.com/51053924/184502798-b205eaaa-af2d-4055-9994-c98a8edf0a16.png)
> > 
> > 
> > yes, my data is so big that spark can't contain and will be null
> 
> I didn't understand your means, could you please offer an example to me? BTW, if you can offer your origin code it could be better.
the code is
https://github.com/apache/incubator-seatunnel/pull/2406

**Comment by TyrantLucifer** [comment]
Your random number exceeds the precision of BigDecimal. BigDecimal is used for fractional precision calculations and not for large numbers. I don't think your example is appropriate. Of course this is just my personal opinion. 😁

**Comment by laglangyue** [comment]
> Your random number exceeds the precision of BigDecimal. BigDecimal is used for fractional precision calculations and not for large numbers. I don't think your example is appropriate. Of course this is just my personal opinion. 😁

yes, I get it
