### ISSUE TITLE
[POM] There are some useless dependencies

### ISSUE THREAD

**Issue by laglangyue** [apache/seatunnel#2409]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Some dependencies in root pom(dependencyManagement) but no module reference
such as this, Is this dependency OK?
Of course, there is no problem with packing，but ugly.

```xml

            <dependency>
                <groupId>org.codehaus.jackson</groupId>
                <artifactId>jackson-mapper-</artifactId>
                <version>${codehaus.jackson.version}</version>
            </dependency>

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
There may be no direct references, but there may be indirect references. If no indirect references, you can remove it.

**Comment by laglangyue** [comment]
> ```
> jackson-mapper-
> ```

Thank you for your guide.
I found a strange dependence.

`jackson-mapper-`   may be in root-pom 770 line.

I can't find it in maven central. Can Maven dependency support regular matching

**Comment by Hisoka-X** [comment]
> > ```
> > jackson-mapper-
> > ```
> 
> Thank you for your guide. I found a strange dependence.
> 
> `jackson-mapper-` may be in root-pom 770 line.
> 
> I can't find it in maven central. Can Maven dependency support regular matching

This is a mistake, can you help fix it?

**Comment by laglangyue** [comment]
> > > ```
> > > jackson-mapper-
> > > ```
> > 
> > 
> > Thank you for your guide. I found a strange dependence.
> > `jackson-mapper-` may be in root-pom 770 line.
> > I can't find it in maven central. Can Maven dependency support regular matching
> 
> This is a mistake, can you help fix it?

yes, I'd like to do it this weekend.
