### ISSUE TITLE
[Bug] [seatunnel-connector-flink-clickhouse] ClickhouseBatchSink config:  fields

### ISSUE THREAD

**Issue by lizu18xz** [apache/seatunnel#2411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### fields [array]

The data field that needs to be output to `ClickHouse` , if not configured, it will be automatically adapted according to the data `schema` .

If not config fields, an error will occur: NullpointerException

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
"sink" : [
        {
            "host" : "local:8123",
            "username" : "fdpuser",
            "password" : "fdpuser",
            "database" : "test",
            "table" : "test02",
            "bulk_size" : "15000",
            "plugin_name" : "Clickhouse",
            "_node_type" : "sink",
            "_node_id" : 27,
            "source_table_name" : "table_26"
        }
```

### Running Command

```shell
bin/start-seatunnel-flink.sh --config config/xxxxx.conf
```

### Error Exception

```log
initFieldInjectFunctionMap  method :  NullpointerException
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Can you provide your full config and your clickhouse schema?

**Comment by lizu18xz** [comment]
> "source_table_name" : "table_26"

   "env" : {
        "job.name" : "clickhouse"
    },
    "source" : [
        {
            "url" : "jdbc:mysql://localhost:3306/test?",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "username" : "root",
            "password" : "123456",
            "query" : "select id,name from test",
            "plugin_name" : "JdbcSource",
            "_node_type" : "source",
            "_node_id" : 26,
            "result_table_name" : "table_26"
        }
    ],
    "transform" : [],
    "sink" : [
        {
            "host" : "local:8123",
            "username" : "user",
            "password" : "user",
            "database" : "l_test",
            "table" : "test02",
            "bulk_size" : "15000",
            "plugin_name" : "Clickhouse",
            "_node_type" : "sink",
            "_node_id" : 27,
            "source_table_name" : "table_26"
        }
    ]
}


schema:
CREATE TABLE lizu_test.test02
(
    `id` String,
    `name` String
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/l_test/test02', '{replica}')
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192 

I looked at the code and didn't handle this.  just has field config:

![image](https://user-images.githubusercontent.com/20568293/184887345-c657a882-6fe5-4002-86f5-3722f87581f4.png)

**Comment by LinZhaoguan** [comment]
@Hisoka-X  I would like to fix this problem.
