### ISSUE TITLE
[ST-Engine][Design] Resource Manager design from seatunnel engine

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2426]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Purpose Of Design
1. It can provide the resource address required for the execute of the Job
2. Ability to dynamically scale nodes in third-party resource management services
3. Each Worker can support running multiple tasks of different Jobs to make full use of resources
4. Worker can recover in time if abnormality occurs
#### Unit resources
````java
public class Worker {
    private Slot[] slots;
}
````
````java
public class Slot {
    private Resource resource;
}
````
#### Unit resource definition
The number of resources each unit slot should have
````java
public class Resource {
    private Memory memorySize;
    // only work on kubernetes
    private CPU cpu;
}
````
SeaTunnel supports normal worker memory allocation, and if running on Kubernetes, it can also support allocation for the CPU running the worker.
#### Standalone
1. The Master and Worker are started, the Worker registers the information to the ResourceManager, and the status is monitored by regular heartbeat.
2. JobMaster requests resources from ResourceManager
3. If the resources are sufficient, the corresponding Worker information will be provided to the JobMaster. If not enough, the JobMaster will not have enough resources.
4. After the JobMaster receives the feedback, it determines whether to start scheduling the task or throw an exception
#### Third Party Resource Manager
1. The Master and Worker are started, the Worker registers the information to the ResourceManager, and the status is monitored by regular heartbeat.
2. JobMaster requests resources from ResourceManager
3. If the resources are sufficient, provide the corresponding Worker information to the JobMaster, if not, apply for resources from the third-party resource management and start the Worker.
4. Worker registers with ResourceManager
5. After the JobMaster receives the feedback, it determines whether to start scheduling the task or throw an exception
6. Return resources to ResourceManager after JobMaster execution ends
7. According to the policy, the ResourceManager determines whether the worker needs to be released and then returned to the third-party resource management system or reserved for the next task.
#### The specific process is as follows:
![image](https://user-images.githubusercontent.com/32387433/184812038-45bf6329-f008-45fb-ba99-ab21628f211e.png)

### Worker's slot allocation
Each Worker needs to allocate its resources to different Slots for the Job to run and use. How to split the Worker into different Slots?
There are two allocation strategies:
1. When the Worker starts, the average distribution is completed according to the configuration information
2. Dynamic allocation. When a task applies for resources, the corresponding slot is dynamically created. The size of the slot is determined according to the number of resources required by the task. This can maximize the use of resources and improve the success rate of scheduling large-resource tasks.

### How to communicate between JobMaster and Worker?
The location of each Task is recorded by saving WorkerTaskLocation and TaskLocation, and then JobMaster maintains the Worker node where each WorkerTaskLocation is located.
```java
public class TaskLocation {
    private long taskGroupID;
    private long taskID;
}
```

```java
public class WorkerTaskLocation extends TaskLocation {
    private int slotID;
}
```

### Interface Design
https://github.com/apache/incubator-seatunnel/pull/2472

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
If you have better designs or suggestions, please leave a message

**Comment by Hisoka-X** [comment]
In my view, I perfer call `Slot` as `Grid`

**Comment by EricJoy2048** [comment]
> Dynamic allocation. When a task applies for resources, the corresponding slot is dynamically created. The size of the slot is determined according to the number of resources required by the task. This can maximize the use of resources and improve the success rate of scheduling large-resource tasks.

Yes, I think `Dynamic allocation` is better. Our `TaskExecutionService` can run task in shared thread, So I think the `TaskExecutionService` can run more tasks if every task only have a small dataset.

**Comment by CalvinKirs** [comment]
How do we achieve memory isolation?

**Comment by Hisoka-X** [comment]
> How do we achieve memory isolation?

There is no real isolation, only logical occupation. In fact, other tasks on the same worker can exceed his memory limit. This is for the fact that we only use heap memory at present. If we use out-of-heap memory in the future, we can complete isolation in the true sense.

**Comment by hailin0** [comment]
How do we achieve requested resource are locked,  or release after a task running crash

**Comment by Hisoka-X** [comment]
> How do we achieve requested resource are locked, or release after a task running crash

Locked by Resource Manager, Release by JobMaster and tell Resource Manager

**Comment by EricJoy2048** [comment]
> public class Resource {
>    private Memory memorySize;
>   // only work on kubernetes
>    private CPU cpu;
>}

Does standalone use this `Resource` too? If I want run 500 task in a node(this is possible because of shared threads), How do we define the number of slots supported by a node？And, how many `CPU` and `memorySize` a slot use?

**Comment by Hisoka-X** [comment]
> > public class Resource {
> > private Memory memorySize;
> > // only work on kubernetes
> > private CPU cpu;
> > }
> 
> Does standalone use this `Resource` too? If I want run 500 task in a node(this is possible because of shared threads), How do we define the number of slots supported by a node？And, how many `CPU` and `memorySize` a slot use?

First, standalone yes. The number of our slots is configurable, such as 1024M of memory, 1024 slots can be declared (if you want to). It means that you can run 1024 tasks at the same time, and each slot has 1M memory resources (declarative, not occupied. Later, consider implementing occupied resource application in off-heap memory). By the way, we can share one slot with multi-task in the future.
