### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;

### ISSUE THREAD

**Issue by yqzdy1207** [apache/seatunnel#2452]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
}

source {
        jdbc {
                driver = oracle.jdbc.driver.OracleDriver
                url = "jdbc:oracle:thin:@//192.168.0.xxx:1521/xxx"
                user = DBO
                password = xxx
                table = "xxx"
                result_table_name = "xxx"
        }
}

transform {
}

sink {
  Console {}
  Doris {
}}
```

### Running Command

```shell
seatunnel-2.1.3]$ bin/start-seatunnel-spark.sh --master local[4] --deploy-mode client --config config/spark_jdbc_doris.conf
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
```

### Flink or Spark Version

spark-3.1.3-bin-hadoop3.2

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dik111** [comment]
meet the same issure in flink 1.13.3 and seatunnel 2.1.3
