### ISSUE TITLE
[Question] get external data when transform

### ISSUE THREAD

**Issue by gudandezhu** [apache/seatunnel#2468]
**background**

When I get a piece of data from _source_，i want join external data with _transform_,for example redis or mysql, Seatunnel does not seem to support？i can't find it by Official website
maybe i can try to define a _plugin_

seatunnel version: 2.1.1 - 2.1.3

**Comment by gudandezhu** [comment]
external data May be very large，i wan't use multiple source.  in flink , cache-aside-pattern or  Async I/O can solve this problem well

**Comment by hailin0** [comment]
Sounds like a `lookup` function?

**Comment by gudandezhu** [comment]
For example, the data in Kafka has order ID， I use `kafkaTableStream` as my `source`. I want to obtain the relevant personnel information, but the personnel information is not a `source`. It exists independently in MySQL
