### ISSUE TITLE
[Connector-v2]Extract Connector public fields

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#2469]
The connector has a public field is `fields`, usually the schema that defines the Connector,

But at present our definitions are very confusing, each Connector has its own set, a good example is this,
https://github.com/apache/incubator-seatunnel/pull/2439/files
https://github.com/apache/incubator-seatunnel/pull/2451/files
At the same time, there is also an abstraction of public method extraction, which allows developers to not need to parse the schema again, etc.
But I have questions about the` fields` and `schemas` in it, can we unify a set of standards? The latter use this.
In addition, for some fields (used by some connectors), such as `delimiter`, `format`, etc., whether the standard and format can be unified (I am not sure), we may need a package to do these things,
What do you think?

**Comment by TyrantLucifer** [comment]
In my opinion, `format` in file connectors is a little ambiguous. For some text-based connector `format` is a best option. But your question is very right, we should unify a set of standards for all connectors to support user-defined schema. I think we can defined some common parameters to represent the current schema information.

`fields` represent the fields information of upstream data

`format` represent the format of upstream data, for example: `json` `csv` `orc` `parquet` etc...

`delimiter` represent the delimiter of upstream text data to splite fields.

The function of parsing user-defined schema has implemented in `connector-common`, all that remains is that unified the parameters of connectors

What do you think about?

**Comment by EricJoy2048** [comment]
This discuss is base on Connector-V2 or Connector?

**Comment by CalvinKirs** [comment]
> This discuss is base on Connector-V2 or Connector?

yup, I updated

**Comment by CalvinKirs** [comment]
> In my opinion, `format` in file connectors is a little ambiguous. For some text-based connector `format` is a best option. But your question is very right, we should unify a set of standards for all connectors to support user-defined schema. I think we can defined some common parameters to represent the current schema information.
> 
> `fields` represent the fields information of upstream data
> 
> `format` represent the format of upstream data, for example: `json` `csv` `orc` `parquet` etc...
> 
> `delimiter` represent the delimiter of upstream text data to splite fields.
> 
> The function of parsing user-defined schema has implemented in `connector-common`, all that remains is that unified the parameters of connectors
> 
> What do you think about?

great, but about `fields` and `schema`, do we still need nesting? For now, it doesn't seem necessary.

**Comment by TyrantLucifer** [comment]
> > In my opinion, `format` in file connectors is a little ambiguous. For some text-based connector `format` is a best option. But your question is very right, we should unify a set of standards for all connectors to support user-defined schema. I think we can defined some common parameters to represent the current schema information.
> > 
> > `fields` represent the fields information of upstream data
> > 
> > `format` represent the format of upstream data, for example: `json` `csv` `orc` `parquet` etc...
> > 
> > `delimiter` represent the delimiter of upstream text data to splite fields.
> > 
> > The function of parsing user-defined schema has implemented in `connector-common`, all that remains is that unified the parameters of connectors
> > 
> > What do you think about?
> 
> great, but about `fields` and `schema`, do we still need nesting? For now, it doesn't seem necessary.

The same as you, i think nesting is useless too. So the conclusion is that we will unified the schema options for all connectors as above, right? I can do this work and I will create a issue to track this work.

**Comment by CalvinKirs** [comment]
agree with you. you don't need to create an issue separately, you can do it here

**Comment by TyrantLucifer** [comment]
The sub tasks about this issue as the following shown:

- [ ] local file source connector
- [ ] hdfs file source connector
- [ ] oss file source connector
- [ ] http source connector
- [ ] kafka source connector

**Comment by ashulin** [comment]
I don't think `format` should be a child of `schema`, `format` should be a connector-level option with `schema`.
`schema` is used to represent the meta information of the table such as field information(`fields`), primary key, etc.

**Comment by ashulin** [comment]
`format` is useless in some connectors, such as mysql, oracle.
