### ISSUE TITLE
New seatunnel-connectors-v2（dev） moudel compilation issue

### ISSUE THREAD

**Issue by guanboo** [apache/seatunnel#2471]
I created a module based on seatunnel-connectors-v2（dev） with a compilation error：
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:doc-jar (attach-javadocs) on project connector-druid: MavenReportException: Error while creating archive: wrap: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

But there is no problem with running the Example:
![image](https://user-images.githubusercontent.com/110977641/185544703-6f4584ad-ff46-4f0b-9326-1a385a0aa7fb.png)

**Comment by hailin0** [comment]
need more infos or screenshots

e.g.
new-connector example
compile command

**Comment by guanboo** [comment]
Branch：api-draft is no problem
