### ISSUE TITLE
[ST-Engine][Client] Make the client can output the job's log

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2476]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In `org.apache.seatunnel.engine.client.job.JobProxy#waitForJobComplete()` we use `jobFuture` to monitor the Job run state and called `jobFuture.get()` to wait the job complete. I think we need output the job's log when we are waiting for the job to complete.

The job run logs is created in JobMaster, The JobMaster is run is the master node of the cluster. In JobMaster we use the `ILogger` to create logs, `ILogger` is the `Hazelcast` component. And from the `Hazelcast` document I found that , we may could use https://docs.hazelcast.com/hazelcast/5.1/maintain-cluster/logging#listening-to-logging-events to output the JobMaster logs in Client.
 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
Is it possible to output logs at the granularity of jobs or pipelines? This is difficult to debug if multiple jobs output the same log.

**Comment by EricJoy2048** [comment]
> Is it possible to output logs at the granularity of jobs or pipelines? This is difficult to debug if multiple jobs output the same log.

Yes, I think we can filter the job logs use the jobid.  And we must add some format when the logs create in JobMaster

**Comment by EricJoy2048** [comment]
@hailin0  Are you interested in completing this feature?

**Comment by hailin0** [comment]
> @hailin0 Are you interested in completing this feature?

@EricJoy2048 
please assign to me

**Comment by jianneng-fit2cloud** [comment]
@hailin0 Hello，May I ask if it is currently supported？
