### ISSUE TITLE
[Feature][seatunnel-connector-flink] support for multiple format

### ISSUE THREAD

**Issue by cswangzheng** [apache/seatunnel#2509]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, there is no flink format module in seatunnel. 
For example, if we want to use avro in file plugin, we need to add the  flink-avro jar to classpath and change the file connector code to implement it, for kafka, we need do this again.
So my thoughts is there should be format folder, if user specific format in the config, the related format should be auto loaded, and each connector which use format has supply the interface that user can write the implememt.
Any thoughts for this?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This feature add by #2014 to connector-v2. Can you support it on connector-v2? Like add more format.

**Comment by cswangzheng** [comment]
> This feature add by #2014 to connector-v2. Can you support it on connector-v2? Like add more format.

v2 connector will be long time supported, and v1 connector will be deperacted?

**Comment by Hisoka-X** [comment]
> > This feature add by #2014 to connector-v2. Can you support it on connector-v2? Like add more format.
> 
> v2 connector will be long time supported, and v1 connector will be deperacted?

From the current point of view, both versions will be supported, but I hope that more new features will support v2 first. This will be much better to maintain, and at the same time you support v2, which means that multiple engines are supported at the same time.
