### ISSUE TITLE
[Bug] [Connector-Http] Can't set request param

### ISSUE THREAD

**Issue by yiminyangguang520** [apache/seatunnel#2511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

It can not set request param

### SeaTunnel Version

dev branch

### SeaTunnel Config

```conf
there is no error exception
```

### Running Command

```shell
there is no error exception
```

### Error Exception

```log
there is no error exception
```

### Screenshots

<img width="1551" alt="截屏2022-08-23 23 25 55" src="https://user-images.githubusercontent.com/7455230/186198607-3128ce2f-7104-42b8-a253-c64844e23663.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Good catch, waiting your PR.

**Comment by TyrantLucifer** [comment]
Waiting for your hotfix.
