### ISSUE TITLE
[Feature][Doc] The contribute document need be update

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2541]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The contribute document in `seatunnel/docs/en/contribution/contribute-plugin.md` are out of date. We should add connector-v2 contribute guide in it. And fix `plugin-mapping.properties` path in doc. And add any information which can help new developer start.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mr-LiuXu** [comment]
I want to give it a try,can you assign it to me?

**Comment by Hisoka-X** [comment]
> I want to give it a try,can you assign it to me?

Great! I already assigned to you

**Comment by Mr-LiuXu** [comment]
Updating document

**Comment by Mr-LiuXu** [comment]
I have improved some details and debugging steps on the contribution guide of seatunnel-connectors-v2 and added some common basic modules, formats, etc. Can you take a look?

**Comment by Hisoka-X** [comment]
> I have improved some details and debugging steps on the contribution guide of seatunnel-connectors-v2 and added some common basic modules, formats, etc. Can you take a look?

Great! I will take a look.

**Comment by Sanskruti-3** [comment]
Can you assign this to me?

**Comment by Hisoka-X** [comment]
> Can you assign this to me?

@Sanskruti-3 Sorry, this issue already assign to @Mr-LiuXu , can you pick another issue to contribute seatunnel? Thanks!
