### ISSUE TITLE
how to add driver-jar to lib

### ISSUE THREAD

**Issue by laglangyue** [apache/seatunnel#2551]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Indeed, we should not provide drivers directly. Because different data source drivers may be different, do we need to provide a loading directory for the user to put the driver-jar in. Where or how?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
Every jars for Spark-Task  is fat-jar, I can't find the lib to put the Driver-jar for jdbc, It's stupid to put it to spark lib

**Comment by Hisoka-X** [comment]
Check this ：https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel

**Comment by laglangyue** [comment]
thx，I get it.



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 29, 2022 10:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/incubator-seatunnel] how to add driver-jar to lib (Issue#2551)




 
Check this ：https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel

**Comment by winnlight** [comment]
> 检查这个：[https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded - 通过海道](https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel)

实际上我就
是按照这样放置jar的，为啥还是不行啊。
![image](https://user-images.githubusercontent.com/72123320/187178840-acc9d6da-a5ff-49ce-991e-0c8a69c3c4c8.png)

**Comment by winnlight** [comment]
> > 检查这个：[https://seatun.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded - 通过海道](https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel)
> 
> 我其实 就是按照这样的罐子的，为不行啊。 ![图片](https://user-images.githubusercontent.com/72123320/187178840-acc9d6da-a5ff-49ce-991e-0c8a69c3c4c8.png)

![image](https://user-images.githubusercontent.com/72123320/187179133-ab52f0f3-5548-4dcc-9947-e1864c6619e8.png)

**Comment by laglangyue** [comment]
> > > 检查这个：[https://seatun.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded - 通过海道](https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel)
> > 
> > 
> > 我其实 就是按照这样的罐子的，为不行啊。 ![图片](https://user-images.githubusercontent.com/72123320/187178840-acc9d6da-a5ff-49ce-991e-0c8a69c3c4c8.png)
> 
> ![image](https://user-images.githubusercontent.com/72123320/187179133-ab52f0f3-5548-4dcc-9947-e1864c6619e8.png)

your lib is error, `plugins/my_plugins/lib`

**Comment by laglangyue** [comment]
> > > 检查这个：[https://seatun.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded - 通过海道](https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel)
> > 
> > 
> > 我其实 就是按照这样的罐子的，为不行啊。 ![图片](https://user-images.githubusercontent.com/72123320/187178840-acc9d6da-a5ff-49ce-991e-0c8a69c3c4c8.png)
> 
> ![image](https://user-images.githubusercontent.com/72123320/187179133-ab52f0f3-5548-4dcc-9947-e1864c6619e8.png)

it maybe a bug, I will check it tomorrow evening

**Comment by laglangyue** [comment]
> > > 检查这个：[https://seatun.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded - 通过海道](https://seatunnel.apache.org/docs/2.1.3/faq#where-can-the-self-written-plugins-or-third-party-jdbcjar-be-placed-to-be-loaded-by-seatunnel)
> > 
> > 
> > 我其实 就是按照这样的罐子的，为不行啊。 ![图片](https://user-images.githubusercontent.com/72123320/187178840-acc9d6da-a5ff-49ce-991e-0c8a69c3c4c8.png)
> 
> ![image](https://user-images.githubusercontent.com/72123320/187179133-ab52f0f3-5548-4dcc-9947-e1864c6619e8.png)

org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery#findPluginJarPath
please see this code, the plugin should has some rule

**Comment by laglangyue** [comment]
may be we can use the plugins/sql/lib/

**Comment by Hisoka-X** [comment]
I checked the code, this method only work with spark. We should add jar in `plugins` to flink environment use `org.apache.seatunnel.flink.FlinkEnvironment.registerPlugin(List<URL> pluginPaths)`
