### ISSUE TITLE
[Feature][ST-Engine] Storage Running Job and it's status to hazelcast IMap

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2577]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

A sub task of https://github.com/apache/incubator-seatunnel/issues/2501

`Update runningJob, Job Status(JobStatus, PipelineState, ExecutionState, stateTimestamps) to hazelcast IMap`

### RunningJobInfo

The `runningJobInfo` will contain `initializationTimestamp ` and `jobImmutableInformationData`. `initializationTimestamp` is the job init timestamp.

The IMap name is `runningJobInfo`, the key is jobId and the value is `RunningJobInfo`

```
IMap<Long, RunningJobInfo> runningJobInfoIMap = nodeEngine.getHazelcastInstance().getMap("runningJobInfo");
```

### PhysicalPlan.jobStatus

Now `jobStatus` type is `AtomicReference<JobStatus>`, I will change it to `IMap<Long, JobStatus>`. The key is JobId and the value is the current JobStatus.

the key of IMap is the job id and the value of the IMap is `JobStatus`

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("runningJobState");
```

In the `updateJobState(@NonNull JobStatus current, @NonNull JobStatus targetState)` we use `compareAndSet` to update Job state. I will change it to `synchronized updateJobState(@NonNull JobStatus current, @NonNull JobStatus targetState)` to ensure the state turn right.

### PhysicalPlan.stateTimestamps

I will update the `stateTimestamps` type to IMap too. 

The key is job id and value is stateTimestamps.

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("stateTimestamps");
```

### SubPlan.pipelineState

The pipeline state use the IMap `runningJobState` too. I want to create as few IMap as possible, because each IMap will create a `WAL` file.

Add a class `PipelineId`

```
public class PipelineId {
        private final long jobId,

        private final long pipelineId,
}
```

The key of IMap is `PipelineId` and value is `PipelineState`

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("runningJobState");
```

### SubPlan.stateTimestamps

The key is `PipelineId` and value is stateTimestamps.

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("stateTimestamps");
```

### PhysicalVertex.executionState

The key is `TaskGroupLocation` and value is `ExecutionState`.

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("runningJobState");
```

### PhysicalVertex.stateTimestamps

The key is `TaskGroupLocation` and value is stateTimestamps.

```
IMap<Object, Object> runningJobStateIMap = nodeEngine.getHazelcastInstance().getMap("stateTimestamps");
```

I will modify the `JobMaster.initFuture` method to check the current state of PhysicalVertex/SubPlan/PhysicalPlan while init the future. If the state is a `End` state, the future will be `complete`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@hailin0  @Hisoka-X  @CalvinKirs  @ashulin  @ic4y  @laglangyue  @TyrantLucifer  @2013650523  

Do you have any suggestions?

**Comment by CalvinKirs** [comment]
> The pipeline state use the IMap runningJobState too. I want to create as few IMap as possible, because each IMap will create a WAL file.

The WAL file count is not determined by this. So you can rest assured on this one.

**Comment by TyrantLucifer** [comment]
> > The pipeline state use the IMap runningJobState too. I want to create as few IMap as possible, because each IMap will create a WAL file.
> 
> The WAL file count is not determined by this. So you can rest assured on this one.

I share his opinion too, you can boldly use.

**Comment by EricJoy2048** [comment]
> > The pipeline state use the IMap runningJobState too. I want to create as few IMap as possible, because each IMap will create a WAL file.
> 
> The WAL file count is not determined by this. So you can rest assured on this one.

Ok, thank you

**Comment by EricJoy2048** [comment]
Now the  type of JobStatus, PipelineState, ExecutionState  are `AtomicReference`, we use `compareAndSet` to ensure the atomicity of state updates. To use IMap to storage state and ensure the `stateTimestamps ` and states update together, I will use an Object Lock in method `updateTaskState` and `turnToEndState`.

**Comment by EricJoy2048** [comment]
> The runningJobInfo will contain initializationTimestamp and jobImmutableInformationData. initializationTimestamp is the > job init timestamp.
>
> The IMap name is runningJobInfo, the key is jobId and the value is RunningJobInfo

How about using  `Tuple2<Data, Long>` instead of `RunningJobInfo`? I think and a class `RunningJobInfo` is no need.

**Comment by Hisoka-X** [comment]
Closed by https://github.com/apache/incubator-seatunnel/pull/2699
