### ISSUE TITLE
[Feature][Metrics] Seatunnel-Metrics

### ISSUE THREAD

**Issue by lvlv-feifei** [apache/seatunnel#2592]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

To build a seatunnel metrics system, the idea is to obtain task metrics through spark sink on&&flink reporter, and seatunnel processes the metrics in a unified manner, defines the interface in seatunnel to specify the seatunnel reporter rules, and the external system obtains the seatunnel parameters by implementing the interface.The following figure shows the process introduction:
<img width="1066" alt="seatunnel-metrics" src="https://user-images.githubusercontent.com/40759793/187873969-5d5d7da9-bafa-4a17-a7a4-fdb3ea84dc81.png">
Try to integrate the flink spark indicator style uniformly.
The main method of the interface `void open() void stop() void report()`
Working with configuration files   mission end command  metrics output method

### Usage Scenario

When you need to view the running status of the seatunnel task and analyze the running efficiency, etc.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Great! Looking forward your contribute!
