### ISSUE TITLE
[Bug] [Spark-Streamming] offset

### ISSUE THREAD

**Issue by sudufly** [apache/seatunnel#2594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

spark-streaming 偏移量提交异常，任务未处理完，但是偏移量已经提交
![image](https://user-images.githubusercontent.com/46857527/187945003-62b58c5e-19b2-4d67-9e50-775c0c528069.png)
上述提交偏移量部分可简化为下图

![image](https://user-images.githubusercontent.com/46857527/187945236-677a9120-c98d-431e-9f8d-0735599a3d16.png)
任务还未完成，但是offsetRanges 会一直被更新为最新的偏移量，不知道是不是我理解不深刻0.0

### SeaTunnel Version

apache-seatunnel-incubating-2.1.0

### SeaTunnel Config

```conf
source {

	kafkaStream {
		topics = "seatunnel_input"
		consumer.bootstrap.servers = "cat-1-200:9092"
		consumer.group.id = "seatunnel_group"
		result_table_name = "msg"
	}
        kafkaStream {
                topics = "accessdata-test"
                consumer.bootstrap.servers = "cat-1-200:9092"
                consumer.group.id = "seatunnel_group"
                result_table_name = "msg-1"
        }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh  --master local[4] --deploy-mode client -c json
```

### Error Exception

```log
xxx
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I have the opposite opinion with you, of course, this may also be my opinion. I think your first source should be submitted normally, but for the second source, the offset should never be submitted. Can you synchronize more information @sudufly
