### ISSUE TITLE
[Improve][build]  root's pom.xml don't need to manage all dependencies

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2606]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the future, we will support multiple versions of the flink/spark engine, and version management will become an important issue.

seatunnel manages all dependencies in root's pom.xml, while many connectors require different versions of dependencies;
I expect to only manage basic core dependencies such as log4j, commons in root's pom.xml;
The dependencies of connectors and engines are managed by their modules;

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
e2e test need jdbc driver,Is it a direct dependency now? or add bom model?

**Comment by Hisoka-X** [comment]
@liugddx We will support add driver into e2e, track this: https://github.com/apache/incubator-seatunnel/pull/2640
