### ISSUE TITLE
[Improve][e2e] connectors e2e use separate module

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2607]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently there may be dependency conflicts when executing e2e tests in an e2e module;
The relocation of maven-shade-plugin can only solve some conflicts, for Class.forName(), relocation will cause new problems; 
so the e2e test of the connector can only be divided into different modules;

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
please assign to me
