### ISSUE TITLE
[Discuss][Doc] Unify some contents in source and sink connector documents

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2612]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The connector has some very important features, such as `batch` and `stream` and `exact-once` of the source connector. `exact-once` of sink connector. But there is no uniform fixed format description for these  in the connector-v2 document.

I suggest that we provide a fixed document template to standardize the description of these features.

Such as:
template for Source connector:

- [x] batch
- [ ] stream
- [x] exactly-once

template for Sink connector:
- [x] exactly-once

Do you have any suggestions for this?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@2013650523  @laglangyue  @TyrantLucifer  @iture123  @hailin0  @legendtkl  @531651225 @zhuangchong

**Comment by ashulin** [comment]
exact-once --> exactly-once

**Comment by EricJoy2048** [comment]
> exact-once --> exactly-once

Ok, Thank you.

**Comment by hailin0** [comment]
template for Source connector:

- [ ] parallelism
- [ ] format(csv、json、parquet、avro、orc)

**Comment by hailin0** [comment]
template for Source & Sink connector:

- [ ] schema projection

**Comment by EricJoy2048** [comment]
> template for Source connector:
> 
> * [ ]  parallelism
> * [ ]  format(csv、json、parquet、avro、orc)

I think `format(csv、json、parquet、avro、orc)` is not a universal feature for Source connector. It is only used for connectors that can directly read or write data files.

**Comment by EricJoy2048** [comment]
> template for Source & Sink connector:
> 
> * [ ]  schema projection

You are right.

**Comment by hailin0** [comment]
> > template for Source connector:
> > 
> > * [ ]   parallelism
> > * [ ]   format(csv、json、parquet、avro、orc)
> 
> I think `format(csv、json、parquet、avro、orc)` is not a universal feature for Source connector. It is only used for connectors that can directly read or and write data files.

agree

**Comment by zhuangchong** [comment]
+1

**Comment by TyrantLucifer** [comment]
> > template for Source connector:
> > 
> > * [ ]   parallelism
> > * [ ]   format(csv、json、parquet、avro、orc)
> 
> I think `format(csv、json、parquet、avro、orc)` is not a universal feature for Source connector. It is only used for connectors that can directly read or write data files.

For some unstructured data connectors, `format` is also important. Beacuse connectors use this parameter as a basis for identifying the upstream data format

**Comment by EricJoy2048** [comment]
> For some unstructured data connectors, `format` is also important. Beacuse connectors use this parameter as a basis for identifying the upstream data format

I will add `format` in the connector that needs it.

**Comment by EricJoy2048** [comment]
I am not found `Hive Source` Connector in the document. @TyrantLucifer  @CalvinKirs 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/32193458/188258712-3142fef4-44d2-428f-a1e0-fd56d437b332.png">

**Comment by TyrantLucifer** [comment]
> I am not found `Hive Source` Connector in the document. @TyrantLucifer @CalvinKirs
> 
> <img alt="image" width="356" src="https://user-images.githubusercontent.com/32193458/188258712-3142fef4-44d2-428f-a1e0-fd56d437b332.png">

Because the file sink connector refactoring hive sink connector also needs to be refactored, and so I will submit this part of the code with the documentation.

**Comment by EricJoy2048** [comment]
I suggest we add a doc file named `key-features.md` to explain the technical terms. And then every connector document link to this file

**Comment by TyrantLucifer** [comment]
> I suggest we add a doc file named `key-features.md` to explain the technical terms. And then every connector document link to this file

+1

**Comment by 2013650523** [comment]
> template for Source & Sink connector:
> 
> * [ ]  schema projection

What does this mean in general?

**Comment by ashulin** [comment]
> > template for Source & Sink connector:
> > 
> > * [ ]   schema projection
> 
> What does this mean in general?

+1, `user-defined schema` is perhaps better; `projection pushdown` is SQL optimization terminology.
