### ISSUE TITLE
[Bug] [connector-v2] Elasticsearch sink need optimization

### ISSUE THREAD

**Issue by iture123** [apache/seatunnel#2621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1.in ElasticsearchSinkWriter.java,if bulk es error,need to throw Exception.
```
   BulkResponse bulkResponse = esRestClient.bulk(requestBody);
    if (!bulkResponse.isErrors()) {
        break;
    }
```

2.in IndexTypeSerializerFactory.java,if es version is 6.x,neet to give a default index type.
 ```
   public static IndexTypeSerializer getIndexTypeSerializer(ElasticsearchVersion elasticsearchVersion, String type) {
        if (elasticsearchVersion == ES2 || elasticsearchVersion == ES5) {
            if (type == null || "".equals(type)) {
                type = DEFAULT_TYPE;
            }
            return new RequiredIndexTypeSerializer(type);
        }
        if (elasticsearchVersion == ES6) {
            if (type != null && !"".equals(type)) {
                return new RequiredIndexTypeSerializer(type);
            }
        }
        return new NotIndexTypeSerializer();
    }
```

### SeaTunnel Version

2.1.3-SNAPSHOT

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
no
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Good job, waiting for your contribution.

**Comment by EricJoy2048** [comment]
@iture123  Is there any new progress in this issue?
