### ISSUE TITLE
[Bug] [connector-v2] #!/bin/sh need modify to #!/bin/bash

### ISSUE THREAD

**Issue by iture123** [apache/seatunnel#2631]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Such as in file start-seatunnel-flink-new-connector.sh
#!/bin/sh need modify to #!/bin/bash
Because in some Linux  Distributions,sh linked to dash.

### SeaTunnel Version

2.1.3-SNAPSHOT

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
Run FakeSourceToConsoleIT.java
```

### Error Exception

```log
22/09/03 18:28:04 ERROR FlinkContainer: /tmp/flink/seatunnel/bin/start-seatunnel-flink-new-connector.sh: 46: [: 2: unexpected operator
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
pls change Line Spearator to LF

**Comment by iture123** [comment]
> pls change Line Spearator to LF

I see.

**Comment by laglangyue** [comment]
see PR #2633
you should fix it local
