### ISSUE TITLE
[Discuss][e2e] How to load connector extra jar dependencies in container?

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#2642]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

According to some connectors like jdbc that need extra jar dependencies, if we want to test these connectors in e2e it needs load extra jar denpendencies in docker containers. The actual use of the connector requires the user to place these dependencies in the specified location, but not in end-to-end testing.

We can't put these extra dependencies in the whole end-to-end testing module, I think the best way is to make corresponding docker images for different connectors, this will achieve the purpose of decoupling and no extra dependencies will be added in.

What your guys think about it? Do you have any other good suggestions?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hk-lrzy** [comment]
Should we add it into connector modules, it should related with connector.
