### ISSUE TITLE
[Feature][Connector-v2] Support iceberg sink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2645]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support iceberg sink #1946

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@2013650523

**Comment by 2013650523** [comment]
hi,I am working on the Sink Iceberg.

**Comment by hailin0** [comment]
link #2495

**Comment by s7monk** [comment]
i can work for it

**Comment by EricJoy2048** [comment]
> i can work for it

You are welcome.

**Comment by hailin0** [comment]
file compression reference：
https://iceberg.apache.org/docs/latest/flink/#rewrite-files-action
https://github.com/apache/iceberg/blob/master/flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java#L168

**Comment by cswangzheng** [comment]
@s7monk is this pr in progress?

**Comment by bing-h** [comment]
I have worked on it in recent one week, and in testing progress

**Comment by zengqinchris** [comment]
> hi,I am working on the Sink Iceberg.

hi，is Sink Iceberg feature is finish？

**Comment by molsionmo** [comment]
@liugddx plz assign it to me. thx

**Comment by jonsey888** [comment]
hi，is Sink Iceberg feature is finish？When can it be used normally

**Comment by hailin0** [comment]
Is there any progress?  @molsionmo

**Comment by jonsey888** [comment]
@hailin0 hi, do you have the V2 connectors Development Guide? I want to develop my own connector based on seatunnel

**Comment by bing-h** [comment]
I have finished two connector, sqs source connector and iceberg sink connector

**Comment by shuitao** [comment]
when can we  see this feature?

**Comment by liugddx** [comment]
> when do we can see this feature?

@molsionmo Any progress yet?

**Comment by vcommon** [comment]
is it ok?

**Comment by vcommon** [comment]
> 

how can find the iceberg sink connector v2?

**Comment by DeeeFOX** [comment]
support yet?

**Comment by zengqinchris** [comment]
自动seatunnel的引擎的 sink iceberg的功能啥时候可以发布测试？

**Comment by auguszero** [comment]
> I have finished two connector, sqs source connector and iceberg sink connector

@bing-h  upload your code ?

**Comment by bing-h** [comment]
> > I have finished two connector, sqs source connector and iceberg sink connector
> 
> @bing-h upload your code ?

I'm going to submit my codes, and find someone else have completed the iceberg and sqs connectors in dev branch. You can checkout it.
