### ISSUE TITLE
[Feature][ST-Web] Job execution design

### ISSUE THREAD

**Issue by lhboss** [apache/seatunnel#2666]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/36065215/188776328-659c9a0c-b36e-4df0-86ea-dd0506d4ee5a.png)

1. The job instance displays the name of the execution container ： The services are run by the springboot framework, and when the scheduled task is executed to save the job instance, you can read the application name of the current service configuration and save it as the specific execution container name

2. The next execution time of the executor updates the job and submits the job task to the time wheel to ensure atomicity：The previous process was that the task was submitted to the time wheel and then updated the execution time of the next task, but there is a possibility of reporting an error before updating the next task execution time, resulting in the update operation not performing normally and causing other problems，Now it is a try catch operation by querying the task list and submitting the job task to the time wheel by guaranteeing update of the next task execution time by finally, these two operations do not guarantee atomicity but guarantee that the next task execution time this operation will be performed for a period of time without affecting the next schedule

### Related issues

#1947 

sub task of #1969 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
I reopen this issue because we plan to do it.

**Comment by EricJoy2048** [comment]
Hi, @lhboss , Thanks for you contribution. In #3360  the Executor is only a client to get job information and submit it and request the SeaTunnel Web API to update job status. So I think `Query this task list` is not what we need. `Query this task list` is more like the work that a scheduler needs to do.
