### ISSUE TITLE
[Feature][API] SeaTunnel Transform API

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2678]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We already have `SeaTunnel Source API` and `SeaTunnel Sink API`, but we don't have `SeaTunnel Transform API` now.
We need `SeaTunnel Transform API` and it must have some key features:

- Like source and sink, it is decoupled from the engine and can run on different engines.
- In order to ensure seatunnel's positioning as a data integration platform and not introduce work beyond the plan, the SeaTunnel Transform API will only support UDF level data conversion.
- In theory, UDF level transform does not require checkpoint and state storage.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@TyrantLucifer  @laglangyue  @legendtkl  @zhuangchong  @hailin0 @ashulin  @Hisoka-X  @CalvinKirs  @ic4y  @lhyundeadsoul  @wolfboys  @2013650523  @531651225  

I try @ everyone I know.

**Comment by ashulin** [comment]
+1, I expect to reduce row conversions in the engine translation.

**Comment by 2013650523** [comment]
+1

**Comment by TyrantLucifer** [comment]
It's great to hear about this exciting decision from the community and I want to be a part of it. It's necessary to develop our own transform API.

**Comment by laglangyue** [comment]
+1

**Comment by lhyundeadsoul** [comment]
+1
Looking forward to more details.

**Comment by EricJoy2048** [comment]
> [DISCUSS] SeaTunnel RoadMap #2169

YYDS

**Comment by EricJoy2048** [comment]
> It's great to hear about this exciting decision from the community and I want to be a part of it. It's necessary to develop our own transform API.

YYDS

**Comment by hailin0** [comment]
> In order to ensure seatunnel's positioning as a data integration platform and not introduce work beyond the plan

+1

**Comment by ic4y** [comment]
+1

**Comment by 531651225** [comment]
+1

**Comment by Hisoka-X** [comment]
+1

**Comment by EricJoy2048** [comment]
Is anyone interested in this feature and can create a pr for it?

**Comment by TyrantLucifer** [comment]
> 

As of now, the api for this part is not designed yet, right?

**Comment by TyrantLucifer** [comment]
> Is anyone interested in this feature and can create a pr for it?


As of now, the api for this part is not designed yet, right?

**Comment by EricJoy2048** [comment]
> > Is anyone interested in this feature and can create a pr for it?
> 
> As of now, the api for this part is not designed yet, right?

Yes. We need to design it from scratch.

**Comment by hailin0** [comment]
@EricJoy2048  please assign to me
