### ISSUE TITLE
[Bug] [e2e] e2e can't running in WIN10

### ISSUE THREAD

**Issue by laglangyue** [apache/seatunnel#2712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

e2e can't running in WIN10

![image](https://user-images.githubusercontent.com/35491928/189483383-63cd867a-6f08-4b5c-889a-d1c1e9e82d0a.png)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
fake e2e
```

### Running Command

```shell
idea run
```

### Error Exception

```log
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
I know this exception, I will fix it

**Comment by laglangyue** [comment]
![image](https://user-images.githubusercontent.com/35491928/189487064-91641f62-bc09-40ac-88fa-212538e5b30f.png)

**Comment by TyrantLucifer** [comment]
It's ok in my computer. Please check your configuration. Change the line feed of shell from `CRLF` to `LF`.

**Comment by laglangyue** [comment]
> It's ok in my computer. Please check your configuration.

Are your test in win10?

**Comment by laglangyue** [comment]
My computer is win10, and docker is  in  virtual box centos7

**Comment by TyrantLucifer** [comment]
> > It's ok in my computer. Please check your configuration.
> 
> Are your test in win10?

yep.

**Comment by laglangyue** [comment]
> > > It's ok in my computer. Please check your configuration.
> > 
> > 
> > Are your test in win10?
> 
> yep.

fine , I'll take a look at it again, I don't change anything.It work before e2e module changed.
