### ISSUE TITLE
[Feature][seatunnel-connector-spark-jdbc-sink] add options, prefix is 'jdbc.'

### ISSUE THREAD

**Issue by isMrH** [apache/seatunnel#2727]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Adding a configuration item prefixed with `jdbc.` to `Sink-jdbc` did not take effect.
No matter how I configure it, the batch size is 1000.
The number of processes connecting to tidb is also uncontrollable.
I don't see the prefix `jdbc.` configuration instructions in the documentation in sink.
I don't know if this is because the configuration is wrong and it doesn't work.
```
env {
  spark.app.name = "st_export_test"
  spark.executor.instances = 20
  spark.executor.cores = 4
  spark.executor.memory = "8g"
  spark.sql.catalogImplementation = "hive"
}

source {
  hive {
    pre_sql = """
    select * from table
    """
    result_table_name = "table"
  }
}

transform {
}

sink {
  jdbc {
    driver = "com.mysql.cj.jdbc.Driver"
    saveMode = "update"
    url = "jdbc:mysql://10.32.xx.xx:4000/test?&useConfigs=maxPerformance&useServerPrepStmts=true&prepStmtCacheSqlLimit=2048&prepStmtCacheSize=256&rewriteBatchedStatements=true&allowMultiQueries=true"
    user = "tidb"
    password = "tidb"
    dbTable = "table"
    isolationLevel = "NONE"
    jdbc.partitionColumn = "id"
    jdbc.lowerBound = 1
    jdbc.upperBound = 1000
    jdbc.numPartitions = 10
    jdbc.batchsize = 100
    source_table_name = "table"
  }
}
```

### Usage Scenario

I want to control the number of processes that sink JDBC writes to tidb and the batch size.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
which version? TIDB is really compatible with MySQL, you can try this conf [connector-v2-sink-jdbc](https://seatunnel.apache.org/docs/connector-v2/sink/Jdbc) in dev branch

**Comment by laglangyue** [comment]
The human conf file can infer the configuration relationship through the parent attribute, so the prefix is not required in Connector-v2

**Comment by isMrH** [comment]
@laglangyue 
Spark version 2.4.0-cdh6.2.1
SeaTunnel Version 2.1.2
I don't see these configurations in the code.
`batch_size` I've also tried this configuration without effect.

**Comment by laglangyue** [comment]
> @laglangyue Spark version 2.4.0-cdh6.2.1 SeaTunnel Version 2.1.2 I don't see these configurations in the code. `batch_size` I've also tried this configuration without effect.

In previous versions, it may be connector-v1, which I am not very familiar with.
@TyrantLucifer Do you know how to write the conf.
