### ISSUE TITLE
[Improve][e2e] Improve end-to-end testing of connector-v2 in a multi-engine environment

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2733]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now developers need to write a lot of repetitive code to test different engines, which is a very boring thing.
If we support more versions of the engine, this will generate more duplicate test code.

### Usage Scenario

Connector-v2 e2e

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
@hailin0 @CalvinKirs @Hisoka-X @EricJoy2048 @TyrantLucifer @laglangyue @liugddx @ic4y

**Comment by TyrantLucifer** [comment]
Looking forward this exciting feature.

**Comment by EricJoy2048** [comment]
link https://github.com/apache/incubator-seatunnel/issues/2691

**Comment by laglangyue** [comment]
![image](https://user-images.githubusercontent.com/35491928/190550001-a5c72dc1-0faf-4cc7-a454-6eddade1b536.png)

How can data be constructed uniformly

**Comment by laglangyue** [comment]
What do you think about the design about E2E improve,more of work is hot to construct the Docker-Container

**Comment by ashulin** [comment]
@laglangyue I am going to use the `TestTemplate` to solve the problem of multiple engines. The container of the connector needs to be implemented by the developer. The e2e test may also require the developer to verify the correctness of the result, which cannot be automatically generated;

**Comment by laglangyue** [comment]
> @laglangyue I am going to use the `TestTemplate` to solve the problem of multiple engines. The container of the connector needs to be implemented by the developer. The e2e test may also require the developer to verify the correctness of the result, which cannot be automatically generated;

Ok

**Comment by hailin0** [comment]
this is my suggestion
https://github.com/apache/incubator-seatunnel/issues/2691#issuecomment-1246746281
