### ISSUE TITLE
[Improve][Connector-V2] Enhance  FakeSource connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2752]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Thoughts on enhance FakeSource:

- [x] SeaTunnelSchema support parse row type from config file #2765 
- [x] Support define row type
- [x] Supports define the total number of rows of data
- [x] Supports direct definition of data values(row)
- [x] Support value's range to avoid exceed in some connectors.
- [x] Support random generate null value for validating connector's stability.
- [x] Support more than splits and parallelism #2961 

Anyone willing to help?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Now `SeaTunnelSchema` can not parse row type from config file, so we should upgrade it first. I can do this work.

**Comment by laglangyue** [comment]
Please assign it to me, I am interested in FakeDatasource and console

**Comment by EricJoy2048** [comment]
I think fake source need support define the key fields and generate unique value for key fields. It's very useful to test `exactly-once` sink which implement `exactly-once` by Idempotent write data.

**Comment by hk-lrzy** [comment]
- Support value's range to avoid exceed  in some connectors.
- Support random generate `null` value for validating connector's stability.

**Comment by laglangyue** [comment]
> 我认为假源需要支持定义关键字段并为关键字段生成唯一值。测试通过幂等写入数据`exactly-once`实现的接收器非常有用。`exactly-once`

good idea, I will do it

**Comment by laglangyue** [comment]
> * Support value's range to avoid exceed  in some connectors.
> * Support random generate `null` value for validating connector's stability.

I will do it but lately

**Comment by EricJoy2048** [comment]
I suggest FakeSource support parallel, I want to use FakeSource and LocalFileSink test the data consistency while some engine node shutdown(For SeaTunnel Engine integration testing). The FakeSource task will run in more than one cluster node only if it support parallel.

**Comment by liugddx** [comment]
> * [ ]  Support more than splits and parallelism.
please assign this task to me. I am working for customize parallelism.
