### ISSUE TITLE
[Core][Translation] Support Primitive Array convert to References Array

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2788]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At now, If we set value use Primitive Array like `double[]`,  will happen convert exception, because we only support `Double[]`, all primitive type have same problem. 
![image](https://user-images.githubusercontent.com/32387433/190941941-0a389fcc-0ace-4a16-afd4-dce4db53f1c7.png)
So we should convert Primitive Array to References Array when we convert `SeaTunnelRow` to EngineRow(Spark/Flink).
The detail in `org.apache.seatunnel.translation.serialization.RowConverter`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?

**Comment by Hisoka-X** [comment]
> For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?

Yes, we should ensure consistent data types instead of including Primitive Array and References Array during data transfer. Confused to downstream components that use data, since we only support References Array, we need to convert Primitive Array to References Array when Source produces `SeaTunnelRow`. The reason for not entrusting this task to the Source Connector is to reduce the burden on the Source implementer.

**Comment by TyrantLucifer** [comment]
> > For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?
> 
> Yes, we should ensure consistent data types instead of including Primitive Array and References Array during data transfer. Confused to downstream components that use data, since we only support References Array, we need to convert Primitive Array to References Array when Source produces `SeaTunnelRow`. The reason for not entrusting this task to the Source Connector is to reduce the burden on the Source implementer.

Please assign it to me. Thx.

**Comment by EricJoy2048** [comment]
> > > For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?
> > 
> > 
> > Yes, we should ensure consistent data types instead of including Primitive Array and References Array during data transfer. Confused to downstream components that use data, since we only support References Array, we need to convert Primitive Array to References Array when Source produces `SeaTunnelRow`. The reason for not entrusting this task to the Source Connector is to reduce the burden on the Source implementer.
> 
> Please assign it to me. Thx.

Hi, @TyrantLucifer  What is the status of this issue?

**Comment by TyrantLucifer** [comment]
> > > > For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?
> > > 
> > > 
> > > Yes, we should ensure consistent data types instead of including Primitive Array and References Array during data transfer. Confused to downstream components that use data, since we only support References Array, we need to convert Primitive Array to References Array when Source produces `SeaTunnelRow`. The reason for not entrusting this task to the Source Connector is to reduce the burden on the Source implementer.
> > 
> > 
> > Please assign it to me. Thx.
> 
> Hi, @TyrantLucifer What is the status of this issue?

Can be closed.

**Comment by EricJoy2048** [comment]
> > > > > For array type convert I had fixed in pr #2479, I see `Primitive Array` only one type of byte is implemented. Do you mean that array convert is also has some problems in flink engine?
> > > > 
> > > > 
> > > > Yes, we should ensure consistent data types instead of including Primitive Array and References Array during data transfer. Confused to downstream components that use data, since we only support References Array, we need to convert Primitive Array to References Array when Source produces `SeaTunnelRow`. The reason for not entrusting this task to the Source Connector is to reduce the burden on the Source implementer.
> > > 
> > > 
> > > Please assign it to me. Thx.
> > 
> > 
> > Hi, @TyrantLucifer What is the status of this issue?
> 
> Can be closed.

Thanks.
