### ISSUE TITLE
[Improve] [Connector-V2-Clickhouse] Improve Clickhouse Connector

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2789]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

Imporve clickhouse connector features & bugs

### Clickhouse Source
- [x] #2806 @wuxizhi777 
- [ ] #2808 @wuxizhi777 
- [x] #3014
- [x] #3057 @FWLamb
- [x] #2949 @FWLamb 
### Clickhouse Sink
- [x] #3101 @FWLamb 
- [x] #2949 @FWLamb 
- [ ] Clickhouse Sink Support BitMap

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

> please assign to me support Int128,Int256

**Comment by hailin0** [comment]
Add sub task:  Add e2e testcase

**Comment by wuxizhi777** [comment]
please assign to me .  
 1. Random use host when config multi-host.
2.  Support multi-split read.

**Comment by FWLamb** [comment]
please assign to me add e2e testcase

**Comment by Hisoka-X** [comment]
> please assign to me add e2e testcase

@FWLamb  Great! I assgined to you. Please track it on #2949

**Comment by FWLamb** [comment]
please assign to me support Int128,Int256

**Comment by Hisoka-X** [comment]
> please assign to me support Int128,Int256

@FWLamb Please track it on #3057

**Comment by wenwei8268** [comment]
please assign to me support Clickhouse Sink geo type ;

**Comment by FWLamb** [comment]
please assign to me support write Geo type.

**Comment by Hisoka-X** [comment]
Hi @wuxizhi777 Any new progress? If you need some help, please let us know. Thanks!
