### ISSUE TITLE
[Doc][Connector-V2] Console Sink Connector have no document

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2794]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Console Sink Connector have no document

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
please assigned to me,thanks.
