### ISSUE TITLE
[Feature][Connector-v2] Enhance Assert sink connector 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2796]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Thoughts on enhance Assert sink connector:
- [ ] Support check the number of rows
    - check rows not empty
    - check minimum number of rows
    - check maximum number of rows
- [ ] Support direct define of data values(row)
- [ ] Support setting parallelism as 1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
Anyone willing to help?

@TyrantLucifer 

Please help to add `help wanted` label

**Comment by liugddx** [comment]
please assigned to me.thanks @TyrantLucifer

**Comment by liugddx** [comment]
please expain the second  and third point,thanks.

`Support setting parallelism as 1` means force setting  parallelism as 1 like `
if (seaTunnelSink.getPluginName().equals("Assert")){
                stream.getExecutionEnvironment().setParallelism(1);
            }
`
![image](https://user-images.githubusercontent.com/48236177/191938487-4f2af61b-c61e-4a89-b9a2-ef2e72174344.png)

I was going to use Metric to Amount of calculated data,but Metric does not work.

@hailin0

**Comment by liugddx** [comment]
i will resolve the second point in another pr.
