### ISSUE TITLE
[Feature][Connector-V2-Clickhouse] Clickhouse Source random use host when config multi-host

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2806]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

subtask of #2789 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
@wuxizhi777 Please track in here.

**Comment by wenwei8268** [comment]
https://github.com/apache/incubator-seatunnel/pull/3108
