### ISSUE TITLE
[Feature][Core][Connector-V2] Unified The way of setting JobName

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2809]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In connector-v2, flink can set job name use `job.name` in `env` in config. But spark can't set job name(application name) at now.
Our goal:
Both flink and spark:
1. User can use same way to set job name in command.
2. User can use same way to set job name in `env` in config.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I want to give it a try
