### ISSUE TITLE
[Feature][ElasticSearch] Add Connector-V2 ElasticSearch sink e2e Test

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2819]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add Connector-V2 ElasticSearch sink e2e Test

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msftgitsklsd** [comment]
please let me try this

**Comment by Hisoka-X** [comment]
> please let me try this

Great! I already assigned to you

**Comment by msftgitsklsd** [comment]
Is there some special configuration in idea? In dev branch I run FakeSourceToConsoleIT and get error . Just run "mvn clean package -pl seatunnel-dist -am -Dmaven.test.skip=true"  work fine 

`/Users/maruko/opensource/incubator-seatunnel/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/spark/AbstractTestSparkContainer.java:55:13
java: 无法访问com.github.dockerjava.api.command.CreateContainerCmd
  找不到com.github.dockerjava.api.command.CreateContainerCmd的类文件`

**Comment by Hisoka-X** [comment]
> Is there some special configuration in idea? In dev branch I run FakeSourceToConsoleIT and get error . Just run "mvn clean package -pl seatunnel-dist -am -Dmaven.test.skip=true" work fine
> 
> `/Users/maruko/opensource/incubator-seatunnel/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/spark/AbstractTestSparkContainer.java:55:13 java: 无法访问com.github.dockerjava.api.command.CreateContainerCmd 找不到com.github.dockerjava.api.command.CreateContainerCmd的类文件`

Did you start your docker env in local?

**Comment by msftgitsklsd** [comment]
> > Is there some special configuration in idea? In dev branch I run FakeSourceToConsoleIT and get error . Just run "mvn clean package -pl seatunnel-dist -am -Dmaven.test.skip=true" work fine
> > `/Users/maruko/opensource/incubator-seatunnel/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/container/spark/AbstractTestSparkContainer.java:55:13 java: 无法访问com.github.dockerjava.api.command.CreateContainerCmd 找不到com.github.dockerjava.api.command.CreateContainerCmd的类文件`
> 
> Did you start your docker env in local?

already sloved, the local maven plugins not download completely

**Comment by msftgitsklsd** [comment]
I'm back
