### ISSUE TITLE
[Improve][connector-v2] SourceReader Base implementation of One reader multiple splits 

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#2824]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Most readers fall into one of the following categories:

 1. One reader single splits. (Some dead simple blocking readers)

 2. One reader multiple splits.
    1. Sequential Single Split (File, database query, most bounded splits)
    2. Multi-split multiplexed (Kafka, Pulsar, Pravega, ...)
    3. Multi-split multi-threaded (Kinesis, ...)

For case 1, we already have the base implementation.

For case 2, we don't have a uniform implementation. For example, for kafka and pulsar source, their implementations are different, which makes code quality and code review difficult

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lhyundeadsoul** [comment]
I am curious why there is always `one reader` rather than `multi-reader & multi-split` .

**Comment by ashulin** [comment]
@lhyundeadsoul Because each degree of parallelism corresponds to one reader, and readers are isolated from each other, we only discuss based on one reader;

**Comment by ashulin** [comment]
@hailin0 The multi-split multiplexed feature of the CDC reader can be tracked using this issue.

**Comment by hailin0** [comment]
@ashulin  please assign to me
