### ISSUE TITLE
[API&Connectors]Optimize connector-source split

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#2836]
At present, all our source sharding logic is handed over to the connector for implementation. 

Most sharding strategies are hash modulo, but the implementation details are different. Contributors spend too much effort on understanding the sharding logic. 

Therefore, I suggest that we abstract and encapsulate the sharding strategy into the API layer. Contributors only need to provide the number of shards, how to allocate and start will be implemented at the API layer, and the connector can choose an appropriate sharding strategy. A connector chooses different sharding strategies in different scenarios.

**Comment by ashulin** [comment]
#2824
