### ISSUE TITLE
[Feature][Docs] Need connector-V2  source and sink kafka docs

### ISSUE THREAD

**Issue by TaoZex** [apache/seatunnel#2840]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently ,we need connector-V2  sink kafka docs,this part is missing.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Can you add source doc too? Thanks!

**Comment by TaoZex** [comment]
> Can you add source doc too? Thanks!

Yes, I will add the source doc too.

**Comment by TaoZex** [comment]
done.
