### ISSUE TITLE
[Feature][Connector-V2] Imporve http connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2857]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Features:

Sink:
- [ ] Support extract `HEADERS`、`PARAMS` from SeaTunnelRow fields
- [ ] Support batch send data row
- [ ] Support more format

Source:
- [x] #3415

example
```curl

First http request get page 1
------------------------
GET /xxx/page
response headers:
next_offset: xxx1


Second request get next page
--------------------------------
GET /xxx/page?start_offset=xxx1

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
Anyone willing to help?

**Comment by hailin0** [comment]
Please help to add `help wanted` label

@TyrantLucifer

**Comment by TyrantLucifer** [comment]
I can do this work, pls assign to me. Thx.

**Comment by EricJoy2048** [comment]
> I can do this work, pls assign to me. Thx.

Hi, @TyrantLucifer , does this work complete?

**Comment by TyrantLucifer** [comment]
> > I can do this work, pls assign to me. Thx.
> 
> Hi, @TyrantLucifer , does this work complete?

Not completed. Please reopen.

**Comment by EricJoy2048** [comment]
> > > I can do this work, pls assign to me. Thx.
> > 
> > 
> > Hi, @TyrantLucifer , does this work complete?
> 
> Not completed. Please reopen.

Ok, I will add it to `projects: SeaTunnel RoadMap`

**Comment by jobmission** [comment]
你好，http connector分页支持了么？

**Comment by jobmission** [comment]
@TyrantLucifer does this work complete?
