### ISSUE TITLE
[Bug] [Connector-V2] Hive Source Connector don't add the partition fields and values in to data

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Hive Source Connector don't add the partition fields and values in to data

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
ALL
```

### Running Command

```shell
ALL
```

### Error Exception

```log
ALL
```

### Flink or Spark Version

ALL

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mr-LiuXu** [comment]
I want to give it a try,can you assign it to me?

**Comment by EricJoy2048** [comment]
> I want to give it a try,can you assign it to me?

Yes, of course.

**Comment by EricJoy2048** [comment]
@TyrantLucifer  You are the maintainer of Hive connector, If you have some idea, please comment and reply here.
