### ISSUE TITLE
[Feature][Community] Add Bot to guide newcomers

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#2902]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hi, I know that some communities will introduce bots to guide newcomers to the community, such as echarts or dolophinscheduler. Proper use of bots can reduce the energy of community members and better help new contributors or new users to familiarize themselves with the community:

We may have some of the following features,
1; Close the issue that has not been responded to for a long time, when the community needs further feedback from the user but the user has not responded for a long time. The period can be 7 days.
2: When the user asks a question in Chinese, the user is automatically reminded to use English.
3: For new contributors, give proper encouragement when PRs are merged, and tell them how to find their next contribution at ease. We'll have good first issues and some long-term, medium-difficulty tasks.
4: For new contributors, properly tell them how to view CI error messages, how to update code, etc., and associate upstream. Documentation links for tools like codestyle.

If you have anything else to add, please leave a message below

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
+1 
> 1; Close the issue that has not been responded to for a long time, when the community needs further feedback from the user but the user has not responded for a long time. The period can be 7 days.

May be 14 days is better, 7 days is too short.

**Comment by EricJoy2048** [comment]
Does the bot can add a `need review again` label when the pr update.

**Comment by CalvinKirs** [comment]
> Does the bot can add a `need review again` label when the pr update.

yup, We can automatically mark labels, such as waiting for user feedback, waiting for community responses, waiting for review, etc.

**Comment by CalvinKirs** [comment]
> +1
> 
> > 1; Close the issue that has not been responded to for a long time, when the community needs further feedback from the user but the user has not responded for a long time. The period can be 7 days.
> 
> May be 14 days is better, 7 days is too short.

Ok

**Comment by liugddx** [comment]
Maybe the pr need be reviewed by previous contributors

**Comment by hailin0** [comment]
+1

**Comment by liugddx** [comment]
Could you add a method to automatically run CI? like flink bot.
