### ISSUE TITLE
[Bug] [ST-Engine] seatunnel.sh -e local can not exit while job complete.

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

sh seatunnel.sh -e local need exit after job complete, but now.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  job.mode = "BATCH"
  execution.checkpoint.interval = 5000
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
    FakeSource {
      result_table_name = "fake"
      field_name = "name,age",
      parallelism = 3
    }
}

transform {
}

sink {
  LocalFile {
    path="/tmp/hive/warehouse/test2"
    field_delimiter="\t"
    row_delimiter="\n"
    partition_by=["age"]
    partition_dir_expression="${k0}=${v0}"
    is_partition_field_write_in_file=true
    file_name_expression="${transactionId}_${now}"
    file_format="text"
    sink_columns=["name","age"]
    filename_time_format="yyyy.MM.dd"
    is_enable_transaction=true
    save_mode="error"

  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config config/batch_to_console.conf -e local
```

### Error Exception

```log
NO
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hk-lrzy** [comment]
plz assign it to me , i can work on it.
