### ISSUE TITLE
[Feature][Discuss] Uniform parameters are available for multiple engines

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#2912]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, seatunnel has a variety of engines. Each engine has its own unique parameters. Some parameters can be adapted to all engines, such as parallelism. We can find more such parameters

### Usage Scenario

Connector-V2

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Very helpful issue.

**Comment by hailin0** [comment]
good idea

**Comment by hailin0** [comment]
flink example:
```
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
  execution.checkpoint.interval = 10000
  execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}
```

spark example:
```
env {
job.mode = "BATCH"
  job.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}
```

**Comment by Carl-Zhou-CN** [comment]
At present, there are some differences between the startup methods of Flink and Spark in seatunnel. Spark pays more attention to the env parameter in config when it starts. Flink depends more on the command line parameters. The parameters that cannot be recognized by the command line are used as the startup parameters of Flink. Does this need to be unified?

**Comment by Hisoka-X** [comment]
> At present, there are some differences between the startup methods of Flink and Spark in seatunnel. Spark pays more attention to the env parameter in config when it starts. Flink depends more on the command line parameters. The parameters that cannot be recognized by the command line are used as the startup parameters of Flink. Does this need to be unified?

In my view, we should focus on env parameter at now. Provide a unified user experience to users. The different about how to handle these parameter, if can be unified would be better.

**Comment by hailin0** [comment]
> > At present, there are some differences between the startup methods of Flink and Spark in seatunnel. Spark pays more attention to the env parameter in config when it starts. Flink depends more on the command line parameters. The parameters that cannot be recognized by the command line are used as the startup parameters of Flink. Does this need to be unified?
> 
> In my view, we should focus on env parameter at now. Provide a unified user experience to users. The different about how to handle these parameter, if can be unified would be better.

agree

**Comment by Carl-Zhou-CN** [comment]
> > At present, there are some differences between the startup methods of Flink and Spark in seatunnel. Spark pays more attention to the env parameter in config when it starts. Flink depends more on the command line parameters. The parameters that cannot be recognized by the command line are used as the startup parameters of Flink. Does this need to be unified?
> 
> In my view, we should focus on env parameter at now. Provide a unified user experience to users. The different about how to handle these parameter, if can be unified would be better.



> > > At present, there are some differences between the startup methods of Flink and Spark in seatunnel. Spark pays more attention to the env parameter in config when it starts. Flink depends more on the command line parameters. The parameters that cannot be recognized by the command line are used as the startup parameters of Flink. Does this need to be unified?
> > 
> > 
> > In my view, we should focus on env parameter at now. Provide a unified user experience to users. The different about how to handle these parameter, if can be unified would be better.
> 
> agree

OK

**Comment by hailin0** [comment]
command line parameters reference

https://seatunnel.apache.org/docs/command/usage/

**Comment by Carl-Zhou-CN** [comment]
underway
