### ISSUE TITLE
[Feature][seatunnel-e2e] Add a container module to simplify spark-e2e and flink-e2e

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#2914]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Containers are using in spark-e2e and flink-e2e. Now, there are some duplicate codes. We can manage containers in project, then using them in e2e.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
Duplicated with #2733
