### ISSUE TITLE
The relational library supports upsert mode writing

### ISSUE THREAD

**Issue by yuangjiang** [apache/seatunnel#2919]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The relational library supports upsert mode writing, for example, when mysql->oracle is used, data is quickly imported into the main table through distributed distribution. When encountering an update failure, log the error to a file and the entire task does not stop. Record data of failed task synchronization after the task is completed. It turned out that we used the temporary table method to solve this problem. I don't know if seatunnel has a relatively complete and fast data import solution.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
@ic4y Hi, do you have any idea?

**Comment by liugddx** [comment]
i have an idea,when data synchronization fails,we can write drity data to a three-way store,need a dirtyManager module to do this job.And this module is pluggable,we can configure it in the env.
