### ISSUE TITLE
[Feature][DISCUSS] operator support customize some feature configurations,like parallel

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#2925]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Sometimes transform need more parallel, so i think operator support customize some feature configurations.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
+1 
Yes, It a good idea.

**Comment by liugddx** [comment]
Do we set each operator individually or set the  parallelism uniformly?  @ashulin

**Comment by ashulin** [comment]
@liugddx My opinion is the same as the [spark scenario] #2965, the user can set the parallelism of a single source and sink, and can also set the global parallelism. When the parallelism of the plugin does not exist, the global parallelism is used.

**Comment by liugddx** [comment]
> @liugddx My opinion is the same as the [spark scenario] #2965, the user can set the parallelism of a single source and sink, and can also set the global parallelism. When the parallelism of the plugin does not exist, the global parallelism is used.

I found that some operators are specified in parallelism itself.like `jdbcSource` and `jdbcSink`.Should we have uniform Settings? like this pr.

**Comment by ashulin** [comment]
@liugddx I would like to have uniform the parallelism option Settings
