### ISSUE TITLE
Seatunnel-2.1.3 How to specify a spark file?

### ISSUE THREAD

**Issue by 2416210017** [apache/seatunnel#2926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Seatunnel-2.1.3 How to specify a spark file? Spark2.4 is used. The hive table cannot be found. The hive site is specified Xml is normal.
![image](https://user-images.githubusercontent.com/52597892/192677983-623b2ca5-baf3-40e4-ab2d-b5af84dd3991.png)

![image](https://user-images.githubusercontent.com/52597892/192678810-ef351cb9-b0d9-408f-a066-7825451baa9a.png)
![Uploading image.png…]()

### SeaTunnel Version

Seatunnel-2.1.3

### SeaTunnel Config

```conf
cat /tmp/mysql_tt3.sh

env {
   spark.app.name = "ads_product_sale_d"
   spark.executor.instances = 1
   spark.dynamicAllocation.maxExecutors = 20
   spark.executor.cores = 1
   spark.executor.memory = "8g"
   spark.sql.catalogImplementation = "hive"
   spark.sql.hive.verifyPartitionPath = "true"
  }
  
source  {

       hive {
        pre_sql = "select * from mid.player"
        result_table_name = "player_hive"
       }
	   
  }
  
transform {
}

  sink {
      Doris {
	       fenodes = "172.17.209.4:8030"
          database = "example_db"
          table = "player_starrocks"
          user = "root"
          password = "123456"
          batch_size=10000
          doris.column_separator="\t"
          doris.columns="id,name,age"
      }
          
  }
```

### Running Command

```shell
su hive -s /bin/bash -c "/app/seatunnel-2.1.3/bin/start-seatunnel-spark.sh --master yarn --deploy-mode cluster --config /tmp/mysql_tt3.sh"
```

### Error Exception

```log
Caused by: org.apache.spark.sql.AnalysisException: Table or view not found: `mid`.`player_parquet`; line 1 pos 14;
```

### Flink or Spark Version

spark-2.4

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Do you want some other people help you fix it?

**Comment by 2416210017** [comment]
Yes, can I help you? thank you

> Do you want some other people help you fix it?
