### ISSUE TITLE
[Improve][Exception Management] Unified exception management in whole project

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#2930]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

So far, the exceptions thrown in the code have not been managed uniformly, the connector and other modules still use RunException, unified exception management can make the code more clear and easy to read, and quickly prompt the user where the exception occurred.

The subtasks to be done are as follows:

- [x] #3043
- [x] #3330
- [x] #3332
- [x] #3434
- [x] #3445
- [x] #3507 
- [x] #3508
- [x] #3509
- [x] #3512
- [x] #3515
- [x] #3516
- [x] #3518
- [x] #3519
- [x] #3521
- [x] #3523
- [x] #3529
- [x] #3530 
- [x] #3531 
- [x] #3532 
- [x] #3535
- [x] #3536
- [x] #3542
- [x] #3543 
- [x] #3544 
- [x] #3551 
- [x] #3548 
- [x] #3547 
- [x] #3568
- [x] #3549
- [x] #3556
- [x] #3554
- [x] #3562
- [x] #3550
- [x] #3546
- [x] #3545

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
I want to work for kafka,Google Sheets,http,feishu,lemlist,myhours,klaviyo,onesignal,starrocks,tablestore,redis and mongodb connector to unified exception.

**Comment by TyrantLucifer** [comment]
Please take one task at a time. Assign kafka to you.

**Comment by TyrantLucifer** [comment]
> I want to work for kafka,Google Sheets,http,feishu,lemlist,myhours,klaviyo,onesignal,starrocks,tablestore,redis and mongodb connector to unified exception.


Please take one task at a time. Assign kafka to you. The owner of connectors do this work is better.

**Comment by TaoZex** [comment]
> > I want to work for kafka,Google Sheets,http,feishu,lemlist,myhours,klaviyo,onesignal,starrocks,tablestore,redis and mongodb connector to unified exception.
> 
> Please take one task at a time. Assign kafka to you. The owner of connectors do this work is better.

Thanks.I will finish the connectors that I am familiar with.

**Comment by john8628** [comment]
please assign StarRocks and  pulsar to me; thx

**Comment by FWLamb** [comment]
please assign Clickhouse and Neo4j to me, thx.

**Comment by lianghuan-xatu** [comment]
please assign Kudu to me! Thx

**Comment by 1ceWine** [comment]
Please assign OneSignal connector to me.Thanks.

**Comment by Carl-Zhou-CN** [comment]
Please assign jdbc connector to me.Thank

**Comment by MonsterChenzhuo** [comment]
Please assign wechat connector to me.Thank

**Comment by TyrantLucifer** [comment]
> Please assign wechat connector to me.Thank

https://github.com/apache/incubator-seatunnel/issues/3562

**Comment by FWLamb** [comment]
please assign ElasticSearch source & sink connector to me, thx.

**Comment by Zzihh** [comment]
Are there any remaining tasks assigned to me?

**Comment by TaoZex** [comment]
I have unified the exception of formats module, please link the issue：https://github.com/apache/incubator-seatunnel/issues/3571

**Comment by cason0126** [comment]
I am doing expose configurable options in Hudi 。
Please assign Hudi connector to me.Thanks

**Comment by TyrantLucifer** [comment]
The task was successfully accomplished! Thank you for all contributors.
