### ISSUE TITLE
[Bug] [Connector-V2-Spark] 'source.parallelism' parameter does not work in spark engine

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#2931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Now the parameter of setting parallelism for source connector does not work in spark engine.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
This is a bug, we can use the same parameter "parallelism" in unity with flink without the API prefix

**Comment by TyrantLucifer** [comment]
> This is a bug, we can use the same parameter "parallelism" in unity with flink without the API prefix

Yes, you are right, I will change the value either.
