### ISSUE TITLE
[Feature][Clickhouse-Connector-V2] Add Clickhouse e2e testcase

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#2949]
Subtask of #2789

**Comment by Hisoka-X** [comment]
@FWLamb

**Comment by FWLamb** [comment]
[https://github.com/apache/incubator-seatunnel/pull/2954](url)

**Comment by FWLamb** [comment]
#2954

**Comment by FWLamb** [comment]
[Feature][Clickhouse-Connector-V2] Add Clickhouse e2e testcase#2954

**Comment by FWLamb** [comment]
[Feature][Clickhouse-Connector-V2] Add Clickhouse e2e testcase #2954

**Comment by FWLamb** [comment]
[Feature][Clickhouse-Connector-V2] Add Clickhouse e2e testcase #2954
