### ISSUE TITLE
[Improve][Connector-V2-kafka] Support for dynamic discover topic & partition in streaming mode

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#2958]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

subtask of #2755 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Will you submit a pr for this?

**Comment by Carl-Zhou-CN** [comment]
yes,I will try

**Comment by IeohMingChan** [comment]
Can multiple topics be filtered out for consumption through regular expressions or other ways?

**Comment by ashulin** [comment]
@IeohMingChan Yes, it is supported by regular expressions

**Comment by ashulin** [comment]
@Carl-Zhou-CN Hello, is there any difficulty? If you have any questions, you can give feedback to the community

**Comment by Carl-Zhou-CN** [comment]
@IeohMingChan @ashulin Sorry, there is some delay in time, I will work hard for this direction, encounter difficulties I will contact the community in time

**Comment by IeohMingChan** [comment]
> @Carl-Zhou-CN Hello, is there any difficulty? If you have any questions, you can give feedback to the community

Thank you. I want to use regular expressions for log execution, I will give feedback to the community if I have any questions.

**Comment by IeohMingChan** [comment]
> @IeohMingChan @ashulin Sorry, there is some delay in time, I will work hard for this direction, encounter difficulties I will contact the community in time

Thank you for your enthusiasm!
