### ISSUE TITLE
[Improve][Connector-V2-kafka] Support setting read starting offset or time at startup config

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#2959]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

subtask of #2755 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/32193458/193242525-2e108287-44b9-4575-a95c-6285e6306765.png">

Will you submit a pr for this?

**Comment by Carl-Zhou-CN** [comment]
yes,I will try
