### ISSUE TITLE
[Improve][Connector-V2-kafka] Support read message metadata(key、timestamp、headers)

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#2960]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

subtask of #2755 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
There is currently no particularly good way to support metadata columns. If metadata columns are required, you may only add one option for each metadata column;

solution proposal for metadata columns: #2490

**Comment by Carl-Zhou-CN** [comment]
underway

**Comment by Carl-Zhou-CN** [comment]
@ashulin @EricJoy2048 
![7983ff29b69a13127260c30ae5f446d](https://user-images.githubusercontent.com/67902676/201276704-5b9249ee-a9cf-406f-a2ea-716bbb801f28.png)
This is the schema that we currently support for kafka. I would like to add metadata columns to it. I want to get some support
