### ISSUE TITLE
[Bug] [sqlserver] timestamp convert exception

### ISSUE THREAD

**Issue by laglangyue** [apache/seatunnel#2963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There is a bug here. The timestamp of sqlserver is a version number, which is synonymous with rowversion. It is stored as a binary number and can be converted to bigint by function, not timestamp type.

![image](https://user-images.githubusercontent.com/35491928/193376328-e358f1e2-d822-4155-ad1f-19c5e073b9f3.png)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
not need
```

### Running Command

```shell
not need
```

### Error Exception

```log
not need
```

### Flink or Spark Version

not need

### Java or Scala Version

not need

### Screenshots

not need

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
Please don't assign it to others. I have a friend from Amway to deal with it

**Comment by jinkachy** [comment]
> Please don't assign it to others. I have a friend from Amway to deal with it

yes, I can try it @laglangyue

**Comment by FWLamb** [comment]
you can use Timestamp.valueOf() to  convert it

**Comment by FWLamb** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.
> 
> ### What happened
> There is a bug here. The timestamp of sqlserver is a version number, which is synonymous with rowversion. It is stored as a binary number and can be converted to bigint by function, not timestamp type.
> 
> ![image](https://user-images.githubusercontent.com/35491928/193376328-e358f1e2-d822-4155-ad1f-19c5e073b9f3.png)
> 
> ### SeaTunnel Version
> dev
> 
> ### SeaTunnel Config
> ```
> not need
> ```
> 
> ### Running Command
> ```shell
> not need
> ```
> 
> ### Error Exception
> ```
> not need
> ```
> 
> ### Flink or Spark Version
> not need
> 
> ### Java or Scala Version
> not need
> 
> ### Screenshots
> not need
> 
> ### Are you willing to submit PR?
> * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

you can use Timestamp.valueOf() to convert it

**Comment by FWLamb** [comment]
you can use Timestamp.valueOf() to convert it

**Comment by jinkachy** [comment]
> you can use Timestamp.valueOf() to convert it

The sqlserver timestamp type(rowversion) is not a timestamp, but a binary stored version number.  It cant be convert to timestamp
