### ISSUE TITLE
[Feature][seatunnel-api]seatunnel support json and tuple data types

### ISSUE THREAD

**Issue by FWLamb** [apache/seatunnel#2966]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Does the seatunnel plan support json and tuple data types

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
Currently String and json formats are supported, I don't think it is necessary to support json datatype.  And tuple can also use struct type or split transform

**Comment by TyrantLucifer** [comment]
> Currently String and json formats are supported, I don't think it is necessary to support json datatype. And tuple can also use struct type or split transform

Aggre with you. I think this proposal is useless.
