### ISSUE TITLE
[Feature][Server init] Add init ddl script for server

### ISSUE THREAD

**Issue by luketalent** [apache/seatunnel#2977]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add init ddl script for server. for example, the table of user , role.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
[Closed by #7](https://github.com/apache/incubator-seatunnel-web/pull/7)
