### ISSUE TITLE
[Doc][web site] doc error

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2991]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

https://seatunnel.apache.org/docs/2.2.0-beta/start-v2/local

document format error.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/32193458/194005001-b9d0cd8f-a26b-400b-8139-03e0af17e7fe.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
Please assign to me.
