### ISSUE TITLE
[Doc][Connector-V2] IoTDB source connector doc error

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2992]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

eg is null.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/32193458/194005422-b516b3b8-d715-4e8b-bec5-b736d109a824.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
Please assign to me.

**Comment by ashulin** [comment]
@TaoZex Assigned to you, please submit PR to [seatunnel-website](https://github.com/apache/incubator-seatunnel-website)

**Comment by ashulin** [comment]
link #2993
