### ISSUE TITLE
[Feature][seatunnel-connector-flink-clickhouse] How to use clickhouse local

### ISSUE THREAD

**Issue by lizu18xz** [apache/seatunnel#3010]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

How to use clickhouse local ?   --path  , The parameters in the code are not seen on the official website https://clickhouse.com/docs/zh/operations/utilities/clickhouse-local/

Is there a more detailed introduction？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
@Hisoka-X CC

**Comment by Hisoka-X** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/32387433/194357552-efde108d-a64a-4f34-8a25-df677cdd90d1.png">
Please use help command to get all config with clickhouse-local.

**Comment by lizu18xz** [comment]
![image](https://user-images.githubusercontent.com/20568293/194360386-4219b237-64c7-4243-894c-6a7cb0f88d46.png)

Which version is used?

**Comment by Hisoka-X** [comment]
> ![image](https://user-images.githubusercontent.com/20568293/194360386-4219b237-64c7-4243-894c-6a7cb0f88d46.png)
> 
> Which version is used?

22.3.1.1, how about yours?

**Comment by lizu18xz** [comment]
> 

21.7.5.29  ,  I'll try upgrading

**Comment by lizu18xz** [comment]
21.7.5.29 ,I used it wrong before ,needs to be specified like this

 -- --path /clickhouse/ch9-data/local-data

https://cloud.tencent.com/developer/article/1828819  

```
% echo -e "1\n2\n3"|clickhouse-local -S "id Int64" -N "tmp_table" -q "CREATE TABLE test_batch (id Int64,EventTime Date) ENGINE = MergeTree() PARTITION BY toYYYYMM(EventTime) ORDER BY id;INSERT INTO TABLE test_batch SELECT id,'2021-05-05' FROM tmp_table;" -- --path /clickhouse/ch9-data/local-data
```

**Comment by Hisoka-X** [comment]
Yep
