### ISSUE TITLE
[Improve] [Connector-V2-Clickhouse] Support nest type and array

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3014]
Subtask of #2789

**Comment by Hisoka-X** [comment]
@FWLamb

**Comment by FWLamb** [comment]
It seems that currently SeaTunnelDataType does not have an implementation class related to the nest type, right?

**Comment by Hisoka-X** [comment]
> It seems that currently SeaTunnelDataType does not have an implementation class related to the nest type, right?

Use SeatunnelRow to complete it.

**Comment by Hisoka-X** [comment]
Please check `FakeDataGenerator`
