### ISSUE TITLE
[Disscuss][e2e] Print out the error log

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3032]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Current e2e runs are reporting errors that do not print out detailed errors,it's not convenient to troubleshoot the problem.I recommend printing an error log if the results are incorrect.
like `Assertions.assertEquals(0, execResult.getExitCode(),"the error log");` etc.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Can E2E's codeView contain this?

**Comment by TyrantLucifer** [comment]
`execResult.getExitCode()` is only contains the exit code of this test case, the more detail error message where we can get it?

**Comment by Hisoka-X** [comment]
How to define `"the error log"`? If just like some `this e2e run failed`, what's different before changed?

**Comment by Hisoka-X** [comment]
The main problem is you can't get error message when e2e use shell command to submit job.

**Comment by liugddx** [comment]
> Exceptions to task execution can be obtained using `execResult.getStderr()`.

**Comment by Hisoka-X** [comment]
> Exceptions to task execution can be obtained using `execResult.getStderr()`.

OK for me.

**Comment by hailin0** [comment]
Is this helpful?

https://github.com/apache/incubator-seatunnel/pull/3028#discussion_r990657385

**Comment by liugddx** [comment]
> Is this helpful?
> 
> [#3028 (comment)](https://github.com/apache/incubator-seatunnel/pull/3028#discussion_r990657385)

LGTM.
