### ISSUE TITLE
[Disscuss][api] Add New Data Type : BigInteger 

### ISSUE THREAD

**Issue by FWLamb** [apache/seatunnel#3071]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Clickhouse needs to support Int128 and Int256. How to implement it? At present, adding BigInteger data type is a solution.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FWLamb** [comment]
If the Long data type is used, the _clickhouse client_ may overflow when the data exceeds the maximum value of Long The _clickhouse client_ uses BigInteger internally to process Int128 and Int256, or how we should distinguish them so that the _clickhouse client_ can use the correct data type.

**Comment by Hisoka-X** [comment]
@ashulin PTAL.

**Comment by ashulin** [comment]
I recommend using `decimal(38,0)`. 
There is currently a BIGINT type, of course it only represents 8-byte data;
This is also the current solution such as Impala, spark, and flink;

**Comment by FWLamb** [comment]
Good idea. I'll try it.

**Comment by FWLamb** [comment]
Problem solved.
