### ISSUE TITLE
[Bug] [sub module] Cannot be built separately.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Building submodules alone fails.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
#1980

**Comment by TyrantLucifer** [comment]
`mvn clean package -pl seatunnel-connectors-v2/connector-redis -am -DskipTests`

![image](https://user-images.githubusercontent.com/51053924/195525389-3d8dff3a-a827-49ce-b7a3-9c09b58ad080.png)
