### ISSUE TITLE
[Feature][doc] “env” lists all optional parameters

### ISSUE THREAD

**Issue by xiaomaiyun** [apache/seatunnel#3090]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

“env
Used to add some engine optional parameters, no matter which engine (Spark or Flink), the corresponding optional parameters should be filled in here.
”
But, I don't know what parameters are supported by the engine I'm using, I would like to be able to list all currently supported parameter names and meanings in the evn module.
for example：
flink configuration：
  execution.parallelism = 1
  job.mode = "STREAMING"
  execution.checkpoint.interval = 10000
  execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"

Spark configuration：
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
This is a Spark or Flink parameter, which we can find explicitly at https://spark.apache.org/docs/latest/configuration.html, and the parameters inside Connector have their own documentation. So there is no need to list them redundantly.

**Comment by xiaomaiyun** [comment]
> This is a Spark or Flink parameter, which we can find explicitly at https://spark.apache.org/docs/latest/configuration.html, and the parameters inside Connector have their own documentation. So there is no need to list them redundantly.

For flink parameters, I can't seem to find all the parameters [here](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/) . https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/, such as:
execution.parallelism = 1
job.mode = "STREAMING"
execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"

**Comment by xiaomaiyun** [comment]
> For flink parameters, I can't seem to find all the parameters [here](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/) . https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/, such as:
> execution.parallelism = 1
> job.mode = "STREAMING"
> execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"

For flink parameters, I can't seem to find all the parameters [here](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/) . https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/, such as:
execution.parallelism = 1
job.mode = "STREAMING"
execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"

**Comment by xiaomaiyun** [comment]
> This is a Spark or Flink parameter, which we can find explicitly at https://spark.apache.org/docs/latest/configuration.html, and the parameters inside Connector have their own documentation. So there is no need to list them redundantly.

For flink parameters, I can't seem to find all the parameters [here](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/) . https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/config/, such as:
execution.parallelism = 1
job.mode = "STREAMING"
execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
