### ISSUE TITLE
[Improve][Example] The local test connector is not available

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3091]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I want to test the connector in a local spark environment,but I need to do a few extra steps.The reason is that the spark engine needs to get dependency packages and local tests have problems getting dependency packages.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Could you describe your problem and your expectations in detail?

**Comment by liugddx** [comment]
> Could you describe your problem and your expectations in detail?

When I test the connector in the spark environment, I not only need to rely on the connector, but also need to add some extra work, like the following
![1665750723167](https://user-images.githubusercontent.com/48236177/195847677-7c4336a7-c72b-438f-a7b4-d93225f7bce8.jpg)
