### ISSUE TITLE
[Feature] When can Spark 3. x be supported？

### ISSUE THREAD

**Issue by wangzhen-wudangshan** [apache/seatunnel#3103]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When can Spark 3. x be supported？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
You can follow this https://github.com/apache/incubator-seatunnel/pull/2574, we will be releasing it soon and if you are able to participate in the testing together, the process will be fast.

**Comment by wangzhen-wudangshan** [comment]
Can you give a solution directly? Because it is urgent to integrate more than 3.0 versions of Spark.
There is too much in the #2574 connection，and time is limited.

**Comment by PainAshura** [comment]
Hey. Is Spark3.x supported now?
