### ISSUE TITLE
[Docs]Connector Plugin Development Guide

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#3107]
For most users, when the existing Connector does not meet the needs of custom development, he needs a simple guide, he don't need to download the entire project, they could create a separate project, just need to introduce the relevant API dependencies can be quickly developed, and then packaged to use. But we are currently missing this part of the documentation, could someone add it for this purpose?

**Comment by CalvinKirs** [comment]
We need to include documentation for Connector V1 as well as V2.
For APi related dependency jar packages, we can use the official release jar as an example

**Comment by IOTdailinwei** [comment]
I want to do this.
