### ISSUE TITLE
[Improve][Core] Change SeaTunnel Logo Print Method

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3153]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At now, we print seatunnel logo use method `AsciiArtUtils::printAsciiArt` when deploy on  flink or spark.
![image](https://user-images.githubusercontent.com/32387433/197105717-0023e3c9-298d-4044-b056-2381f2afeb4f.png)
It will throw exception when use some jdk. 
![image](https://user-images.githubusercontent.com/32387433/197105645-b845176e-798a-425c-a738-934526c41438.png)
We should replace it to static seatunnel string like our engine `NodeExtensionCommon.ST_LOGO` and `NodeExtensionCommon.COPYRIGHT_LINE`.
![image](https://user-images.githubusercontent.com/32387433/197105672-af47ebb7-3d14-4d0f-a349-26112d008460.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
Please assign it to me.Thx;
