### ISSUE TITLE
v2 kafka json analysis

### ISSUE THREAD

**Issue by 365323507** [apache/seatunnel#3177]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

source {
	Kafka {
        topic = "Log"
        bootstrap.servers = "hdp01:9092"
		schema = {
			fields {
				a1= "string"
				b1=
			}
		}
		result_table_name = test
    }
}

How to configure schema

{
    "a1": "cs",
    "b1": {
        "proxy": 100
    }
}

### Usage Scenario

v2 kafka json

How to configure schema

{
    "a1": "cs",
    "b1": {
        "proxy": 100
    }
}

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
```hocon
schema {
  a1 = string
  b1 = {
    proxy = int
  }
}
```
