### ISSUE TITLE
[clickhouse][Connector-V2] How to use connection ssl

### ISSUE THREAD

**Issue by 365323507** [apache/seatunnel#3190]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

sink {
	Clickhouse {
		host = "192.168.0.245:8123"
		database = "table"
		table = "t1"
		username = "default"
		password = "1234561"
		clickhouse.ssl = "true"
		clickhouse.ssl_mode = "none"
		clickhouse.ssl_root_certificate = "/home/bigdata/module/seatunnel/kong/server.crt"
		schema = {
			fields {
				uri = string
			}
		}
		bulk_size = 1
	}
}

Connection error

### Usage Scenario

[clickhouse][Connector-V2] Clickhouse SSL used sink Connection error

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This is a good feature. Looking forward your PR!
