### ISSUE TITLE
[Feature][CORE] Not supported inner variale substitution

### ISSUE THREAD

**Issue by CriysHot** [apache/seatunnel#3227]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I can't cite my object in my config,it's ok that the developers cite their object by using substitution,for ex
![image](https://user-images.githubusercontent.com/42238827/198822682-8f7af41f-7b9a-47db-b917-2d88762c18e3.png)
Here is a piece of code about this .
![image](https://user-images.githubusercontent.com/42238827/198822864-c0388c83-19a5-4a82-a0ff-8c808ed89fc5.png)

### Usage Scenario

i wanna implement dynamically exec my task,such as sql.
please look the following picture：
![image](https://user-images.githubusercontent.com/42238827/198823039-2118ece1-2755-42da-8d21-34c3b7a1d4ac.png)
i can optionally exec my sql by getting external var rather than getting a  external sql directly

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CriysHot** [comment]
there is a piece of related code 
![image](https://user-images.githubusercontent.com/42238827/198823347-6ce9277e-2de8-4470-b8b8-041a81d1b4b0.png)
package org.apache.seatunnel.core.base.config;

**Comment by liugddx** [comment]
@Hisoka-X assgin to me .

**Comment by liugddx** [comment]
you can config like this `transform {
  sql {
    sql = ${?x.sql1}
  }
}`,and -i x.sql1=select * from a

**Comment by liugddx** [comment]
![image](https://user-images.githubusercontent.com/48236177/199745956-596b6337-f7d0-433f-8c04-bb3f42a38bcf.png)
![image](https://user-images.githubusercontent.com/48236177/199746022-ba9c585f-852a-4c7e-9623-601fbc28d6c6.png)
![image](https://user-images.githubusercontent.com/48236177/199746062-6ec2815a-5e86-43ea-934a-a1dc9bc5ae01.png)
