### ISSUE TITLE
scala.util.matching.Regex.<init>(Ljava/lang/String;Lscala/collection/Seq;)V

### ISSUE THREAD

**Issue by nashlibby** [apache/seatunnel#3248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

import hive data to clickhouse

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
env {
  spark.app.name = "dmp"
  spark.executor.instances = 5
  spark.executor.cores = 2
  spark.executor.memory = "4g"
  spark.sql.catalogImplementation = "hive"
}

source {
  Hive {
    pre_sql = "select * from dmp_release.t1"
    result_table_name = "t1"
  }
}

transform {
}

sink {
   clickhouse {
        host = "localhost:8123"
        database = "dmp_release"
        table = "t1"
        fields = ["id", "name"]
        username = "default"
        password = ""
   }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh --config config/spark.batch.conf -e client -m 'local[*]'
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: scala.util.matching.Regex.<init>(Ljava/lang/String;Lscala/collection/Seq;)V
```

### Flink or Spark Version

spark version: 3.3.0

### Java or Scala Version

jdk version: 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Spark3 is not supported for now, but I don't know if this has anything to do with this, I'm not familiar with scala.

**Comment by nashlibby** [comment]
only spark2?
