### ISSUE TITLE
[Bug] [seatunel-transform-flink-udf] udf prepare method  properties analysis error

### ISSUE THREAD

**Issue by lucifer1024** [apache/seatunnel#3250]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

`
  public void prepare(FlinkEnvironment prepareEnv) {
       
        final Properties properties = new Properties();
        PropertiesUtil.setProperties(config, properties, UDF_CONFIG_PREFIX, false);
        
        classNames = new ArrayList<>(properties.size());
        functionNames = new ArrayList<>(properties.size());
        
        properties.forEach((k, v) -> {
            classNames.add(String.valueOf(k));
            functionNames.add(String.valueOf(k));
        });
    }
`

`
udf {
    function.test_1 = "com.example.udf.flink.TestUDF"
    function.test_2 = "com.example.udf.flink.TestUDTF"
  }
`

`classNames.add(String.valueOf(k)) ` error,  is not  **k** , 
  
it should be   **v**   , `classNames.add(String.valueOf(v))`

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
empty
```

### Running Command

```shell
empty
```

### Error Exception

```log
empty
```

### Flink or Spark Version

empty

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This is an obvious mistake. Looking forward your PR!

**Comment by Hisoka-X** [comment]
What‘s happend ? If this is a bug, I will reopen it.

**Comment by Hisoka-X** [comment]
If you don't have enough time to fix it, maybe others can help to do it.

**Comment by shengdoupi** [comment]
Hi, assign me please.

> If you don't have enough time to fix it, maybe others can help to do it.

**Comment by lucifer1024** [comment]
> What‘s happend ? If this is a bug, I will reopen it.

Sorry ,  I thought it was fixed  in #3171

**Comment by lucifer1024** [comment]
I to fix it
