### ISSUE TITLE
[Bug] [docs] File name of 'install-plugin.sh' is different from the doc

### ISSUE THREAD

**Issue by hufengkai** [apache/seatunnel#3251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I followed the quick start guide to run ‘sh bin/install_plugin.sh’ to install plugins, but found the actual file name is install-plugin.sh

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
sh bin/install_plugin.sh
```

### Error Exception

```log
sh: bin/install_plugin.sh: No such file or directory
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Welcome to submit PR.

**Comment by hufengkai** [comment]
https://github.com/apache/incubator-seatunnel/pull/3260
