### ISSUE TITLE
[Feature][starter][spark] Support transform-v2 for spark

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3268]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

subtask of #3178

reference
#3145
https://github.com/apache/incubator-seatunnel/blob/2.3.0-beta-release/seatunnel-core/seatunnel-spark-starter/src/main/java/org/apache/seatunnel/core/starter/spark/execution/SparkExecution.java#L55

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@TyrantLucifer  Please help add `help wanted` label

**Comment by FWLamb** [comment]
please assign to me, I want to try it; thx.

**Comment by hailin0** [comment]
> please assign to me, I want to try it; thx.

@FWLamb 
If you have any questions, welcome to discuss, I have communicated with @john8628 about #3267

**Comment by FWLamb** [comment]
> > please assign to me, I want to try it; thx.
> 
> @FWLamb If you have any questions, welcome to discuss, I have communicated with @john8628 about #3267

Thank you. I will communicate with you later.
