### ISSUE TITLE
[Bug] [Kafka Sink] 指定topic使用'topic'报错

### ISSUE THREAD

**Issue by jinhshi** [apache/seatunnel#3289]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用kafka sink 指定topic时按照官方示例报错
sink {

  kafka {
      **topic** = "seatunnel"
      bootstrap.servers = "localhost:9092"
      partition = 3
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
  }
}

Previous exception in task: No configuration setting found for key 'topics'

应使用 '**tpoics**'

### SeaTunnel Version

2.2.0-beta

### SeaTunnel Config

```conf
sink {
  kafka {
      topic = "seatunnel"
      bootstrap.servers = "localhost:9092"
      partition = 3
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh --master local[4] --deploy-mode client --config ./config/
```

### Error Exception

```log
Previous exception in task: No configuration setting found for key 'topics'
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bravekong** [comment]
The document has errors，you can use topics . like : topics = "seatunnel"

**Comment by wuchunfu** [comment]
@jinhshi Please use English, thanks

**Comment by Carl-Zhou-CN** [comment]
hi,@jinhshi There are some differences between v1 and v2 parameters
v1 source：topics
v1 sink：topic
v2 source&sink：topic

**Comment by jinhshi** [comment]
> 

I use v2 : bin/start-seatunnel-spark-connector-v2.sh, ‘topic’ won't work, but ’topics‘ will @Carl-Zhou-CN

**Comment by Carl-Zhou-CN** [comment]
Can you upgrade the latest version to try? 2.2.0-beta v2 doesn't seem to open kafka
