### ISSUE TITLE
[Feature][Http Sink] save response body to somewhere else

### ISSUE THREAD

**Issue by jinhshi** [apache/seatunnel#3302]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

  when I use http sink , i wish save the response boby to somewhere else, eg. kafka or separate log files which only include the repsonse body. 

  Like this feature of NIFI：
<img width="682" alt="NIFI" src="https://user-images.githubusercontent.com/45941667/199907509-5c19d9bb-7a11-458b-80d4-e9c3c16e90b6.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Maybe you can use HTTP source to do that.
