### ISSUE TITLE
[Improve][Connector-V2][HTTP] Improve HTTP responce parse format

### ISSUE THREAD

**Issue by TaoZex** [apache/seatunnel#3339]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

![2a06ca5d4aa17ea9519d3eb271ab73a](https://user-images.githubusercontent.com/45089228/200731661-dc18b162-176a-4106-898f-b7403bda2582.png)

In SaaS services,the response returns in such a format that the individual fields can be defined by the field name.

![b838ff61af4e1e4c442b3bcc7b92bd4](https://user-images.githubusercontent.com/45089228/200734484-f9060654-e148-4d37-972b-7f0c5eb831a7.png)

But this complex format cannot be customized through the field name.I'm thinking about how to deal with this kind of data.

If you have a good suggestion, please comment on it！

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
```hocon
schema {
  obejct = string
  id = string
  name = string
  avatar_url = string
  type = string
  bot {
    owner {
      type = string
      user {
        object = string
        id = string
        name = string
        avatar_url = string
        type = string
        person {
          email = string
        }
      }
    }
  }
}
```
