### ISSUE TITLE
[Bug] [Transform-sql-Use UDAF] The demo on the official website has incorrect configuration parameters

### ISSUE THREAD

**Issue by monawang6** [apache/seatunnel#3355]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://seatunnel.apache.org/docs/2.1.3/transform/sql

The configuration parameters of the sql module demo in transform on the official website are incorrect.

### SeaTunnel Version

seatunnel 2.1.3

### SeaTunnel Config

```conf
xx
```

### Running Command

```shell
xx
```

### Error Exception

```log
xx
```

### Screenshots

![image](https://user-images.githubusercontent.com/117819716/200804876-5b8ad941-7131-4417-a5b9-031d7a64aa9c.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi,I want to try
