### ISSUE TITLE
[Feature][Connector V2] Add support for mongodb source complex types

### ISSUE THREAD

**Issue by davidewhw** [apache/seatunnel#3376]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

exapmle ARRAY<ROW<`address` STRING, `city` STRING, `country` STRING, `postalCode` STRING, `province` STRING>>

### Usage Scenario

When reading mongodb data sources, support for complex types is required

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
So far, SeaTunnel `ArrayType` not support complex type now. This functionality needs to wait until the underlying API changes.
