### ISSUE TITLE
[Feature][SeaTunnel Engine] Add test to test stream job recover when all cluster node done and restart

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3430]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a test to do this:

1. 3 node cluster start and then submit a stream job (Fake Source -> LocalFile Sink, and Fake Source will write 6000 rows. You can reference https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/ClusterFaultToleranceIT.java)
2. Stop all nodes when there are some rows write into the local files.
3. Start all nodes.
4. Check the job status will recover to `Running`.
5. Wait and check the local files will have all the row write from Fake Source and the number of the rows are `6000`.
6. Cannel the job and wait the job's status turn to `CANCELED`.
7. Stop the cluster client.
8. Stop all cluster nodes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
I want to try this task, it will help me understand engine better. Please assign it to me,thanks.
