### ISSUE TITLE
[Transform][udf]  a example  for udf

### ISSUE THREAD

**Issue by zhangweiweikol** [apache/seatunnel#3457]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I can't found any example  about udf's  jar code,  in  all the document.  I never write about that, and can't search that.
Could you  provide a example?  

Thanks alot.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangweiweikol** [comment]
extends ScalarFunction

**Comment by Zhang88665** [comment]
import org.apache.flink.table.functions.ScalarFunction;

public class UDFexample extends ScalarFunction {
    public String eval(String msg) {
        try {
            //your udf
        } catch (Exception e) {
            e.printStackTrace();
        }
        return msg;
    }
}
