### ISSUE TITLE
[Feature][Kubernetes] Run seatunnel in K8s with flink application mode and spark cluster mode

### ISSUE THREAD

**Issue by cswangzheng** [apache/seatunnel#3479]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have already use k8s for flink and spark.  For flink we use application mod. For spark, we use cluster mode, which means the job manager deployment is created by flink client, and driver pod created by spark client. For example, we can use this command to start a seatunnel flink cluster:
`./bin/flink run-application \
    --target kubernetes-application \
    -Dkubernetes.cluster-id=seatunnel-cluster \
    -Dkubernetes.container.image=seatunnel-image-name \
    local:///opt/flink/seatunnel.jar`

The first thing is in the document part, told user we can support this kind of deployment.  

The second thing, usually we build a unique image for flink or spark without config file in it, so use config as a file in pod is not a choose, if the content of config file can be passed by param should be better. So we want to add new param like config-content, which is base64 encode value of the content of config file.

Any thoughts for this?

### Usage Scenario

Enhance seatunnel to support more kind of deployment mode.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by legendtkl** [comment]
+1
Good proposal.

**Comment by Grypse** [comment]
We can add job configmap to kubernetes deployment to support custom param, then mount configmap to some path to start the job.
