### ISSUE TITLE
[Feature][TCP/UDP connector] seatunnel support a tcp/udp-connector such as syslog etc?

### ISSUE THREAD

**Issue by bitian** [apache/seatunnel#3482]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I saw that someone asked if there is a syslog or dns connector, data collection through the tcp/udp protocol. Does Seatunnul currently have plugin support , or is there any plan to add this function for the future?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Does `Socket` Connector can do it?

**Comment by liugddx** [comment]
> May need a dedicated connector,Need to support the udp protocol

**Comment by bitian** [comment]
> > May need a dedicated connector,Need to support the udp protocol

Is it possible to use Seatunnel to develop a server-side connector to monitor and receive data？
