### ISSUE TITLE
[Bug] [Core] Read config file but without check it exist.

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/32387433/202990202-363cd7b1-92ad-46f3-b00f-c1cfc3fca4e4.png">

- When we parse the config file, we always think it exists, which may throw `No configuration setting found for key 'env'` when the file does not exist. Users may be confused, we need to check whether it exists before parsing the config file, and if it does not exist, we need to throw an error and provide the correct prompt.
- Both Flink/Spark/ST Engine should do this check.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
I want to try this issue.Please assign to me,

**Comment by TaoZex** [comment]
Is this the way to check config？https://github.com/apache/incubator-seatunnel/pull/3493
