### ISSUE TITLE
[Feature][Core] Override env parameters via command line arguments

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3487]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Override env parameters via command line arguments

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Do we now use command line parameters to directly replace the parameters in config or use placeholder replacement in config?

1. direct replacement
start-seatunnel-flink-connector-v2.sh -c config.conf -i job.name=test
```
env {
job.name = seatunnel
}
```

2. placeholder replacement

start-seatunnel-flink-connector-v2.sh -c config.conf -i jobName=test
```
env {
job.name = ${jobName}
}

**Comment by liugddx** [comment]
> Do we now use command line parameters to directly replace the parameters in config or use placeholder replacement in config?
> 
> 1. direct replacement
>    start-seatunnel-flink-connector-v2.sh -c config.conf -i job.name=test
> 
> ```
> env {
> job.name = seatunnel
> }
> ```
> 
> 2. placeholder replacement
> 
> start-seatunnel-flink-connector-v2.sh -c config.conf -i jobName=test
> 
> ```
> env {
> job.name = ${jobName}
> }
> ```

The second method is now supported, but sometimes the placeholder will not be configured

**Comment by liugddx** [comment]
> > Do we now use command line parameters to directly replace the parameters in config or use placeholder replacement in config?
> > 
> > 1. direct replacement
> >    start-seatunnel-flink-connector-v2.sh -c config.conf -i job.name=test
> > 
> > ```
> > env {
> > job.name = seatunnel
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. placeholder replacement
> > 
> > start-seatunnel-flink-connector-v2.sh -c config.conf -i jobName=test
> > ```
> > env {
> > job.name = ${jobName}
> > }
> > ```
> 
> The second method is now supported, but sometimes the placeholder will not be configured

@Hisoka-X @EricJoy2048 @TyrantLucifer  Any suggestions?

**Comment by Hisoka-X** [comment]
I think method 1 can only support replace parameter in env. But not use `-i`, use `-p` or other. Method 2 is good for replace the placeholder.
