### ISSUE TITLE
[Improve][Connector-V2][JDBC] Unified exception for JDBC source & sink connector

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3556]
sub-task of #2930

**Comment by TyrantLucifer** [comment]
@Carl-Zhou-CN Please comment here.

**Comment by Carl-Zhou-CN** [comment]
ok

**Comment by MonsterChenzhuo** [comment]
@TyrantLucifer Please assign to me.Thx.

**Comment by TyrantLucifer** [comment]
> @TyrantLucifer Please assign to me.Thx.

Sorry, this task has been assigned to @Carl-Zhou-CN , could you please do another task such elsticsearch?
