### ISSUE TITLE
[Improve][Connector-V2][WeChat] Unified exception for WeChat sink connector

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3562]
sub-task of #2930

**Comment by MonsterChenzhuo** [comment]
please assign WeChat connector to me; thx

**Comment by TyrantLucifer** [comment]
> please assign WeChat connector to me; thx

Good job! Looking forward your contribution.

**Comment by TyrantLucifer** [comment]
closed because of no exception to handle.
