### ISSUE TITLE
[Feature][Connector V2] Add conditions for mongodb source incremental pull

### ISSUE THREAD

**Issue by wangsvip** [apache/seatunnel#3567]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I will regularly pull the incremental data of mongodb into hive every day. At present, the extraction method of mongodb is to pull the full amount, and then filter the incremental data in the transform. This method is not friendly. If this table has 1 billion data, it will increase every day. The amount of 5,000 records requires the source side to pull in 1 billion data, and then filter out 5,000 records on the transform side. DBA disagrees with this approach, saying that it consumes a lot of resources, and it needs to be done once a day. If there are too many, the CPU on the direct line will explode. Therefore, I hope to add a place where the filter conditions can be written on the source side, so that I can directly check the 5000 incremental data and export it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx
