### ISSUE TITLE
[Bug] [seatunnel-connector-flink-kafka] KafkaTableStream transform the schemaInfo to ArrayNode, but when using SchemaUtil's setSchema function, it should be ObjectNode. 

### ISSUE THREAD

**Issue by BenjaminWenqiYu** [apache/seatunnel#3597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

KafkaTableStream transform the schemaInfo to ArrayNode, but when using SchemaUtil's setSchema function, it should be ObjectNode. 

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
} 

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**

  KafkaTableStream {
    consumer.bootstrap.servers = "localhost:9092"
    consumer.group.id = "seatunnel"
    topics = transactions
    result_table_name = transactions
    format.type = json
    schema = "{\"account_id\":\"long\",\"amount\":\"long\",\"transaction_time\":\"datetime\"}"
    format.allow-comments = "true"
    format.ignore-parse-errors = "true"
    consumer.auto.offset.reset = latest
  }
}

transform {
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
./bin/start-seatunnel-flink.sh -m yarn-cluster -ynm seatunnel -c config/flink.kafka.console
```

### Error Exception

```log
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader org.apache.flink.util.ChildFirstClassLoader @2d72f75e)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
Are you willing to fix it? If not，I think I will check it  and try to fix it this weekend，please wait a time.

**Comment by crazyxFeng** [comment]
the bug had fixed？ who can tell me
