### ISSUE TITLE
[Feature][common] Support read message metadata

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#3599]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The metadata for the connector should also be parsed in the schema because it is a type of data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
link #2960  #3570

**Comment by Carl-Zhou-CN** [comment]
schema = {
      fields {
        name = "string"
        age = "int"
      }
      meta.fields {
       topicAlias = topic
       partitionAlias = partition
      }
}

**Comment by Carl-Zhou-CN** [comment]
> schema = { fields { name = "string" age = "int" } meta.fields { topicAlias = topic partitionAlias = partition } }

@Hisoka-X  @TyrantLucifer @ashulin @hailin0 @TaoZex 
This is the metadata field I extended in Kafka before. Now I want to extend it to all connectors. I'm not sure whether this form is available. Can you give me some advice.
Can we define relevant interfaces for metadata in the schema and implement each connector accordingly, because the metadata of each connector is different and incompatible

**Comment by Carl-Zhou-CN** [comment]
![image](https://user-images.githubusercontent.com/67902676/204693440-ae7121f6-e8cf-4eab-85a3-20b27ded2024.png)

**Comment by Hisoka-X** [comment]
> Can we define relevant interfaces for metadata in the schema and implement each connector accordingly

Yes, we can. I think the main thing is parse schema meta config in `SeaTunnelSchema`, then return to (or get by) connector.
Next, connector can know what meta info I should save or not. Finally save into Row.

**Comment by TyrantLucifer** [comment]
IMO, we didn't need this interface, metadata is a part of data, we should process it in connectors. The core point of this feature is that how to define the schema of metadata? Or it's a good idea not to define a schema, because connectors know their own metadata, the only thing we do is merge it in SeaTunnel Row.

**Comment by Hisoka-X** [comment]
> IMO, we didn't need this interface, metadata is a part of data, we should process it in connectors. The core point of this feature is that how to define the schema of metadata? Or it's a good idea not to define a schema, because connectors know their own metadata, the only thing we do is merge it in SeaTunnel Row.

But we need a option to open collect metadata or not. I think it should define in schema

**Comment by Carl-Zhou-CN** [comment]
> IMO, we didn't need this interface, metadata is a part of data, we should process it in connectors. The core point of this feature is that how to define the schema of metadata? Or it's a good idea not to define a schema, because connectors know their own metadata, the only thing we do is merge it in SeaTunnel Row.
I think that if the schema is not defined, the user may not need all the metadata of the connector, but only some metadata or a special definition of the name

**Comment by Carl-Zhou-CN** [comment]
> IMO, we didn't need this interface, metadata is a part of data, we should process it in connectors. The core point of this feature is that how to define the schema of metadata? Or it's a good idea not to define a schema, because connectors know their own metadata, the only thing we do is merge it in SeaTunnel Row.

I think that if the schema is not defined, the user may not need all the metadata of the connector, but only some metadata or a special definition of the name

**Comment by TyrantLucifer** [comment]
> > IMO, we didn't need this interface, metadata is a part of data, we should process it in connectors. The core point of this feature is that how to define the schema of metadata? Or it's a good idea not to define a schema, because connectors know their own metadata, the only thing we do is merge it in SeaTunnel Row.
> 
> I think that if the schema is not defined, the user may not need all the metadata of the connector, but only some metadata or a special definition of the name

So this is not a general requirement, the metadata if not a part of upstream data, and the defination name should not be contained in scheam config. Set different configuration items for different connectors to map.

**Comment by Carl-Zhou-CN** [comment]
> So this is not a general requirement, the metadata if not a part of upstream data, and the defination name should not be contained in scheam config. Set different configuration items for different connectors to map.

However, all connectors have metadata, and users should be able to select the metadata they need under the current connector. I think it may be universal in this perspective
