### ISSUE TITLE
[Improve][Connector-V2][E2E] Refactor e2e test cases

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3601]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As so far, we had completed the work of refactoring e2e code structure. So the next work is that to rewrite e2e test cases using new e2e code framework. BTW, in your pull request you need delete old e2e test cases.

The subtasks to be done are as follows:

- [x] #3602
- [x] #3605
- [x] #3606
- [x] #3671
- [x] #3616
- [x] #3922
- [x] #3607

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
Please assgin to me this issue： [Improve][Connector-V2][DataHub] Refactor DataHub connector e2e test cases
link issue ：https://github.com/apache/incubator-seatunnel/issues/3605

**Comment by Carl-Zhou-CN** [comment]
I want to try ElasticSearch

**Comment by MonsterChenzhuo** [comment]
please assign `[Improve][Connector-V2][MongoDB] Refactor MongoDB connector e2e test cases` to me; thx

**Comment by Carl-Zhou-CN** [comment]
I also want to try IotDB

**Comment by Carl-Zhou-CN** [comment]
I also want to try IceBerg

**Comment by FlechazoW** [comment]
Please assign the JDBC connector to me, thx.

**Comment by TyrantLucifer** [comment]
reopened

**Comment by TyrantLucifer** [comment]
All task has been done, thank you for your all contribution!
