### ISSUE TITLE
 [Feature][Connector V2] expose configurable options in cassandra

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3614]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add OptionRule for connector `cassandra` . You can reference other connectors to implement `TableSourceFactory` or `TableSinkFactory`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1ceWine** [comment]
Please assign to me.Thanks.

**Comment by EricJoy2048** [comment]
> Please assign to me.Thanks.

Ok, Look forward to your pr.

**Comment by TaoZex** [comment]
https://github.com/apache/incubator-seatunnel/pull/3681
