### ISSUE TITLE
[Bug] [seatunnel-connectors-v2] [connector-http] Http connector json parse error

### ISSUE THREAD

**Issue by hx23840** [apache/seatunnel#3623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

json data not parse

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
  execution.checkpoint.interval = 5000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  Http {
    url = "http://192.168.50.58:8099/api/test"
    method = "POST"
    format = "json"
    body = ""
    schema {
      fields {
        code = int
        data = string
        success = boolean
      }
    }
  }
}

transform {
}

sink {
  console {

  }
}

```

### Running Command

```shell
./bin/seatunnel.sh \
--config ./config/seatunnel.streaming.conf.template -e local
```

### Error Exception

```log
no exception
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
@liugddx
