### ISSUE TITLE
[Bug] [connect-file-hadoop] hdfsfile sink Cannot output files to the specified directory

### ISSUE THREAD

**Issue by matesoul** [apache/seatunnel#3638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

hdfsfile sink Cannot output files to the specified directory，The temporary directory `/tmp/seatunnel/seatunnel/`  has files。
If I make `transform` is empty, it works。

### SeaTunnel Version

2.3.1-beta

### SeaTunnel Config

```conf
env {
	parallelism.default = 1
	execution.checkpointing.interval = 2000
	state.checkpoints.dir = "hdfs://bigdata-3:8020/seatunnel-task/checkpoint"
	execution.checkpointing.timeout = 1000
}

source {
	Jdbc {
		driver = "com.mysql.cj.jdbc.Driver"
		url = "jdbc:mysql://192.168.30.48:3306/datahh_test"
		user = "root"
		password = "Root@123"
		query = "select id,code,name,description,dimension,grain,type,del_flag,create_by,create_time,update_by,update_time from bd_dq_rule"
		result_table_name = "bd_dq_rule"

	}
}
transform {
}
sink {
	HdfsFile {
		fs.defaultFS = "hdfs://bigdata-3:8020"
		path = "/tmp/test/warehouse/test6"
		file_name_expression = "${transactionId}_dev"
		file_format = "text"
		filename_time_format = "yyyy.MM.dd"
		field_delimiter = "\\001"
		row_delimiter = "\n"
		partition_by = ["grain"]
		is_partition_field_write_in_file = "false"
		sink_columns = ["id","code","name","description","dimension","grain","type","del_flag","create_by","create_time","update_by","update_time"]
		is_enable_transaction = "true"
	}
}
```

### Running Command

```shell
/opt/seatunnel-2.3.0/bin/start-seatunnel-flink-connector-v2.sh --target yarn-per-job --detached -Dparallelism.default=1 --config /opt/seatunnel-config/dev-mysql-hdfs_1670070802195.conf -Djobmanager.memory.process.size=1024mb -Dtaskmanager.memory.process.size=1024mb -Dyarn.application.name=dev-mysql-hdfs -Dexecution.runtime-mode=BATCH
```

### Error Exception

```log
no error
```

### Flink or Spark Version

1.13.6

### Java or Scala Version

scala 1.11
java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by matesoul** [comment]
CREATE TABLE `bd_dq_rule` (
  `id` bigint unsigned NOT NULL COMMENT '主键ID',
  `code` varchar(100) DEFAULT NULL COMMENT '规则编号',
  `name` varchar(100) DEFAULT NULL COMMENT '规则名称',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `dimension` tinyint unsigned DEFAULT NULL COMMENT '质量维度（1：完整性，2：有效性，3：准确性，4：唯一性，5：一致性，6：合理性）',
  `grain` tinyint unsigned DEFAULT NULL COMMENT '检核粒度（1：表级，2：字段级）',
  `type` tinyint unsigned DEFAULT NULL COMMENT '类型（0：数值型，1：波动率型）',
  `del_flag` tinyint unsigned DEFAULT '0' COMMENT '删除状态（0：正常，1：已删除）',
  `create_by` varchar(64) NOT NULL COMMENT '创建人',
  `create_time` bigint unsigned NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL COMMENT '修改人',
  `update_time` bigint unsigned NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_code` (`code`) USING BTREE COMMENT '编号',
  KEY `idx_name` (`name`) USING BTREE COMMENT '名称',
  KEY `idx_flag` (`del_flag`) USING BTREE COMMENT '删除状态',
  KEY `idx_create_time` (`create_time`) USING BTREE COMMENT '创建时间',
  KEY `idx_grain` (`grain`) USING BTREE COMMENT '检核粒度'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='度量规则信息表';


INSERT INTO bd_dq_rule (id,code,name,description,dimension,grain,`type`,del_flag,create_by,create_time,update_by,update_time) VALUES
	 (5,'T5','表行数，1天波动率。','基准值为昨天的样本（表行数），比较当天采集的表行数，对比波动率。',6,1,1,0,'admin',1651137665807,'admin',1651137665807);

**Comment by wangsvip** [comment]
我也是，tidb导到hive 为空, 这个版本问题很多，官方文档写的还很乱，根本没法看，示例给的参数跟源码里给的都不一样，要想真正用起来你得看源码才行

**Comment by EricJoy2048** [comment]
`If I make transform is empty, it works` Does it means it is right when transform is empty?
Can you show the config file which is not work?

**Comment by TyrantLucifer** [comment]
This problem has solved. Because the checkpoint parameters configuration error caused not trigger the commit operation.
