### ISSUE TITLE
[Feature][Connector V2] expose configurable options in cassandra

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3663]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Reference other connector to implement `TableSourceFactory` and `TableSinkFactory`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@cason0126

**Comment by Sad-Man-Shang** [comment]
I also want to try this.

**Comment by cason0126** [comment]
@EricJoy2048  OK，please assign to me

**Comment by EricJoy2048** [comment]
> I also want to try this.

Sorry, @cason0126  apply for this work first. 

![Uploading image.png…]()

You can get other `good first issue` from here https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
