### ISSUE TITLE
[Feature][ST-Engine] Output job summary metrics at the end of the job

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#3664]

**Comment by FWLamb** [comment]
assign to me .

**Comment by ic4y** [comment]
Is there any progress? At present, st-engine can print the metric at the end of the task, but it is very rough and needs to optimize the output

**Comment by ic4y** [comment]
@FWLamb 
Is there any progress? At present, st-engine can print the metric at the end of the task, but it is very rough and needs to optimize the output

**Comment by FWLamb** [comment]
> @FWLamb Is there any progress? At present, st-engine can print the metric at the end of the task, but it is very rough and needs to optimize the output

Sorry, I'm busy these days and haven't looked carefully. If someone wants to participate in this, they can be assigned; I take time to do this on weekends. Do you have any suggestions for the output content? I don't have a good idea about which metrics to output.

**Comment by ic4y** [comment]
Move to #4013
