### ISSUE TITLE
[Feature][Engine Starter] update SeaTunnel Starter and change -e to -m

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3674]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In starter `-e` is to specify driver run mode and only spark use, it have two select options `client`,`cluster`. And `-m` is to specify the engine deploy mode.  

SeaTunnel Engine now use `-e` to specify the engine deploy mode, we need update it and use `-m` to specify the engine deploy mode.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FWLamb** [comment]
assign to me .
