### ISSUE TITLE
[Feature][Engine] Add support close engine instance shell.

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3680]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add shell command `stop-seatunnel-cluster.sh`
The command can close seatunnel cluster instance in currect host.
If one host have multi seatunnel cluster instance, should use `-cn` or `--cluster` to choose which cluster should be closed.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/32387433/206368822-790e76b0-5bb6-4441-a431-641adbea2945.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FWLamb** [comment]
assign to me.
