### ISSUE TITLE
[Feature][SeaTunnel Engine] Add a jvm.properties file to define the SeaTunnel Engine JVM Options

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3710]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a jvm.properties file to define the SeaTunnel Engine JVM Options

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx。
