### ISSUE TITLE
[Bug] [e2e] org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Starting the resource manager.*'

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/seatunnel#3715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1399" alt="图片" src="https://user-images.githubusercontent.com/60029759/207278110-8595a4f5-8d26-4dbd-8c0c-1a2643e7485e.png">
<img width="1396" alt="图片" src="https://user-images.githubusercontent.com/60029759/207278708-76f43067-565e-4c69-bb15-da70e02eda83.png">

<img width="1187" alt="图片" src="https://user-images.githubusercontent.com/60029759/207278173-54c45fed-d86c-457f-ac42-7936b5e80185.png">
Recently, while working on e2e development, I found that executing e2e tasks kept reporting the above exception.

<img width="1417" alt="图片" src="https://user-images.githubusercontent.com/60029759/207286887-c19cb0fb-010f-44f5-8436-3a8ed0774f74.png">
<img width="1438" alt="图片" src="https://user-images.githubusercontent.com/60029759/207287175-ebeed899-14ff-40ed-adf4-3fa7915f8429.png">

The other problem is that he gets stuck here, and I don't know what causes it.
### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Grypse** [comment]
How do you fix this errors?

**Comment by linyu003** [comment]
Sorry to bother you, but how do you solve the problem?  @Grypse @MonsterChenzhuo

**Comment by linyu003** [comment]
I worked around the problem.

The cause is Mac's m1 chip. The docker images e2e depended on are based on AMD64arch. Althoungh it can be run on mac's m1 chip, which is arm64 arch, the performance is really limited and many unexpected blockings and errors will fail the running.

So I just go to use another PC with ubuntu 22 and an AMD64 cpu.  Everything goes well now.
