### ISSUE TITLE
[Improve][connector-jdbc] Support exactly-once for jdbc connector source 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3725]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support exactly-once for jdbc connector source 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
Please assign to me.
