### ISSUE TITLE
[Feature][connector][doris] Support write cdc changelog event in doris sink 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3726]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support write cdc changelog event in doris sink

reference
https://github.com/apache/incubator-seatunnel/pull/3653
https://github.com/apache/incubator-seatunnel/pull/3673
https://github.com/apache/incubator-seatunnel/pull/3444

https://github.com/apache/incubator-seatunnel/pull/3631

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
I will try it , please assign to me,thanks

**Comment by hailin0** [comment]
> I will try it , please assign to me,thanks

reference
https://doris.apache.org/docs/dev/ecosystem/flink-doris-connector

**Comment by john8628** [comment]
> > I will try it , please assign to me,thanks
> 
> reference https://doris.apache.org/docs/dev/ecosystem/flink-doris-connector

OK， thanks

**Comment by hailin0** [comment]
reference  https://doris.apache.org/docs/dev/data-operate/import/import-way/stream-load-manual

**Comment by hailin0** [comment]
@john8628 

hi, do you need help?

**Comment by john8628** [comment]
oh , i am sorry , I have been ill recently;

**Comment by hailin0** [comment]
https://doris.apache.org/docs/dev/data-operate/update-delete/batch-delete-manual
https://doris.apache.org/zh-CN/docs/dev/data-operate/update-delete/sequence-column-manual/
https://github.com/apache/doris-flink-connector/blob/master/flink-doris-connector/src/main/java/org/apache/doris/flink/sink/writer/RowDataSerializer.java#L104
