### ISSUE TITLE
[Improve][Connector-V2][Console] Improve console connector sink output format

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3737]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="630" alt="image" src="https://user-images.githubusercontent.com/14371345/208033590-a31aba7b-f5ec-4820-ad5a-e1d6eba0eddd.png">

**Improve**
- [ ] output content to slf4j log(Currently is STDOUT)
- [ ] output contains all fields of SeaTunnelRow（e.g. table-id、rowkind、...）

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Grypse** [comment]
Please assign this to me!

**Comment by hailin0** [comment]
> Please assign this to me!

Assigned
