### ISSUE TITLE
[Improve][Connector][Doris] Improve doris connector sink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3741]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

reference https://doris.apache.org/docs/dev/data-operate/import/import-way/stream-load-manual

feature

- [x] #3752
- [x] #3753

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 531651225** [comment]
please assign  to me

**Comment by hailin0** [comment]
> please assign to me

@531651225 
https://github.com/apache/incubator-seatunnel/issues/3752
