### ISSUE TITLE
[Feature][connector][kafka] Support read `canal` format message from kafka

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#3746]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support read [`canal`](https://github.com/alibaba/canal/wiki) format message from kafka

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx。

**Comment by hailin0** [comment]
It is suggest to add new implment to here

https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json

**Comment by ashulin** [comment]
@MonsterChenzhuo @hailin0 IMO, The `canal` format is added to the `json-format` module to be more general.

**Comment by hailin0** [comment]
> It is suggest to add new implment to here
> 
> https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-formats/seatunnel-format-json/src/main/java/org/apache/seatunnel/format/json

@ashulin I mean it too

**Comment by MonsterChenzhuo** [comment]
ok

**Comment by hailin0** [comment]
hi, do you need help?

**Comment by MonsterChenzhuo** [comment]
@hailin0 Thanks, no need for now
