### ISSUE TITLE
[Feature][Seatunnel-engine] print engine configuration when start.

### ISSUE THREAD

**Issue by Grypse** [apache/seatunnel#3767]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

There does not have detailed engine configuration when engine starting.
Need to add configuration detail for user check.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Good feature, waiting your PR!
