### ISSUE TITLE
[Bug] [connector-file-ftp] connectors-v2 ftp输出，文件只被输出到了tmp目录中

### ISSUE THREAD

**Issue by chenyekun** [apache/seatunnel#3777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

flink connector V2中的ftp输出，文件只被输出到了tmp目录中，没有输出到path目录

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
transform {
}

sink {
FtpFile {
    host = "192.168.10.25"
    port = 21
    user = "anonymous"
    password = "anonymous"
    path = "/pub/csv/fff"
    field_delimiter = ","
    row_delimiter = "\n"
    file_format = "text"
    source_table_name = "t1"
    file_name_expression = "${transactionId}_${now}"
    filename_time_format = "yyyy.MM.dd"
    is_enable_transaction = true
    tmp_path = /pub/tmp
    parallelism = 1
}
}

source {
jdbc {
  password = "123456"
  driver = "com.mysql.cj.jdbc.Driver"
  query = "SELECT ArmyNo as admin,DeployCount as age FROM test"
  parallelism = 1
  result_table_name = "t1"
  user = "root"
  url = "jdbc:mysql://192.168.10.104:3306/y_vue"
}

}

env {
  execution.parallelism = 1
}
```

### Running Command

```shell
./start-seatunnel-flink-connector-v2.sh -c ../config/mysql_ftp.conf
```

### Error Exception

```log
无报错信息
```

### Flink or Spark Version

Flink1.13.6

### Java or Scala Version

2.12

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Please setting parameters about flink checkpoint in `env` block.

**Comment by chenyekun** [comment]
> Please setting parameters about flink checkpoint in `env` block.

增加如下配置：
  execution.checkpoint.mode = exactly-once
  execution.checkpoint.data-uri = "hdfs://192.168.10.21:9820/checkpoint"
  execution.checkpoint.interval = 20000
可以看到checkpoint产生，但是还是相同的问题，不输出到path目录下。
