### ISSUE TITLE
[Improve][Connector-V2] Update Clickhouse Connector JDBC Driver Version

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3806]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Some bug in clickhouse-jdbc driver already fixed by clickhouse team. We should update dependency version to get fix. Please make some test to make sure connector running normal before commit PR.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by goldwater2019** [comment]
Please assign this to me!Thx!

**Comment by Hisoka-X** [comment]
> Please assign this to me!Thx!

Great! I already assigned to you. Looking forward your PR.
