### ISSUE TITLE
[Feature][connector-clickhouse] ScpFileTransfer & RsyncFileTransfer want to set remote port.

### ISSUE THREAD

**Issue by tedshim** [apache/seatunnel#3814]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Feature][connector-clickhouse] ScpFileTransfer & RsyncFileTransfer want to set remote port.

### Usage Scenario

I don't use 22 for SSH remote port, I use 5222 port.

org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.file.ScpFileTransfer

private static final int SCP_PORT = 22; 
==>
private static final int SCP_PORT = 5222; 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Thanks for your report. We will finished it in next version.

**Comment by tedshim** [comment]
I'll check it out in the next version.
