### ISSUE TITLE
[Bug] [FileSinkConnector] Text And Json WriteStrategy lost the sinkColumnsIndexInRow

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

We use `sinkColumnsIndexInRow` to get the field to write to file in Orc and Parquet WriteStrategy, But `sinkColumnsIndexInRow` lost in Text And Json WriteStrategy.

In OrcWriteStrategy:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/32193458/209772489-12296b55-fa3e-4a00-83e4-1599417c98f3.png">

But in TextWriteStategy:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/32193458/209772528-da0ac1a8-6606-47d6-9ff4-b33050cc6021.png">

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
closed because of #3863
