### ISSUE TITLE
[Improve][SourceConnector] Unified schema parameter, update InfluxDB Source fields to schema

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3821]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We need  unified schema parameter, All Source Connector which used schema need use the same option name `schema`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 531651225** [comment]
please assign to me,thanks

**Comment by wfrong** [comment]
please assign to me,very thanks

**Comment by wfrong** [comment]
please assign to me,thanks
