### ISSUE TITLE
[Improve][SourceConnector] Unified schema parameter, update Iceberg source fields to schema

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3822]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Unified schema parameter, update Iceberg source option `fields` to `schema`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by amaan0o7** [comment]
Hi, @EricJoy2048  I'm new to open source. could you assign me this issue I would like to give it a try on this.
