### ISSUE TITLE
[Improve][SourceConnector] Unified schema parameter, update IoTDB source fields to schema

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3823]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve][SourceConnector] Unified schema parameter, update IoTDB source `fields` to `schema`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wfrong** [comment]
please assign to me,thanks

**Comment by zhilinli123** [comment]
I want to mention this pr, but I don't know exactly what content should be changed. Can you introduce it if it is convenient? Thank you very much

**Comment by wfrong** [comment]
> I want to mention this pr, but I don't know exactly what content should be changed. Can you introduce it if it is convenient? Thank you very much

already has a PR relate to this issue: https://github.com/apache/incubator-seatunnel/pull/3896, please try other issue.
