### ISSUE TITLE
[Improve] [SourceConnector] config supports only specific fields

### ISSUE THREAD

**Issue by xiaofan2022** [apache/seatunnel#3825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

config should be able to set all type fields for the corresponding component

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
    spark.executor.instances = 2
    spark.executor.cores = 1
    spark.executor.memory = "1g"
    spark.master = local
}

source {
 hive {
     pre_sql = "SELECT user_id, fans_count FROM temp.xhs_user_portrait_count  limit 10"
     result_table_name = "t_table"
   }
}
transform {
}

sink {
    jdbc {
        saveMode = "Overwrite",
        truncate="true",
        driver = "com.mysql.cj.jdbc.Driver",
        url = "jdbc:mysql:///test?rewriteBatchedStatements=true",
        isolationLevel="NONE",
        user = "",
        password = "",
        dbTable = "t_test",
        customUpdateStmt = "INSERT INTO t_test (user_id,fans_count) values(?,?)"
        jdbc.connect_timeout = 10000
        jdbc.socket_timeout = 10000
      }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh --master yarn --deploy-mode client --config ./test.conf
```

### Error Exception

```log
The jdbc sink component does not support truncate, causing the drop table
```

### Flink or Spark Version

truncate is not supported and the setting causes drop table

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fourSheep8X** [comment]
老哥，后来有解决没，现在想每次同步非分区表之前truncate下，结果没找到合适的方式 @xiaofan2022
