### ISSUE TITLE
[Discuss][Seatunnel-Engine]change queue to disruptor.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3849]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now the queue we use is BlockingQueue. I want to replace it with Disruptor and test its performance under massive data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
I want to try it, so I'm ready to test it. Is this a meaningful issue for Seatunnel ?
 @CalvinKirs @hailin0 @Hisoka-X @EricJoy2048 @TyrantLucifer @ashulin @ic4y

**Comment by Hisoka-X** [comment]
> I want to try it, so I'm ready to test it. Is this a meaningful issue for Seatunnel ? @CalvinKirs @hailin0 @Hisoka-X @EricJoy2048 @TyrantLucifer @ashulin @ic4y

Great! This is a feature I'm very curious about the result.

**Comment by TyrantLucifer** [comment]
We can disscuss this in meeting tonight. Prepare the design plan and the necessity of the proposal before the discussion is better.

**Comment by ic4y** [comment]
> I want to try it, so I'm ready to test it. Is this a meaningful issue for Seatunnel ? @CalvinKirs @hailin0 @Hisoka-X @EricJoy2048 @TyrantLucifer @ashulin @ic4y


This is a good idea, and care about resource usage when testing.
