### ISSUE TITLE
[Improve][Shade][Hadoop] Improve hadoop shade

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#3855]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As we know, some dependencies such as guava, jackson... maybe conflicts with other components  So we need process these components' class name using maven-shade plugin.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wendongdi** [comment]
im wudidi and would like to do this

**Comment by TyrantLucifer** [comment]
closed because of #3858
