### ISSUE TITLE
[Feature][CDC][Postgres] Support PostgreSQL CDC

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#3868]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add PostgreSQL CDC

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2000liux** [comment]
Excuse me, is there any code development for this problem。

**Comment by sunxiaojian** [comment]
Reopen this issue ？

**Comment by ctaity-treinta** [comment]
Hi, Do we have news about this? :(👍

**Comment by jobmission** [comment]
Hi, Do we have news about this? :(👍
