### ISSUE TITLE
[Discuss][CheckPoint Storage & IMap Storage] Support use JDBC to storage the checkpoint state data and IMap data

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3870]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now, If you want to use SeaTunnel Zeta Cluster, you must storage checkpoint state data and IMap data to distributed file system(For example, HDFS, OSS, S3). But for some enterprises, they do not have their own big data systems, HDFS, and cloud storage. Should SeaTunnel support  use JDBC to storage the checkpoint state data and IMap data? I think  in the case of small cluster size, use MySQL to storage checkpoint state data and IMap data can work fine.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
> I think in the case of small cluster size, use MySQL to storage checkpoint state data and IMap data can work fine.

+1

**Comment by CalvinKirs** [comment]
+1 db is a good choice when the amount of data is small.

**Comment by liugddx** [comment]
#3792

**Comment by liugddx** [comment]
Maybe there are multiple options available, such as mongodb.

**Comment by 2000liux** [comment]
This is a good proposal。
- For example, use rocksdb, an embedded file database. Lightweight and easy to use.
- The experience of rocksdb can be learned from flink

- if useing  database 、We need to consider the high availability of the database
