### ISSUE TITLE
[Discuss][Core]Support Cache between source and sink

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3871]
Caching is a very important capability in a data integration platform. But in general, it can be realized with the help of third-party storage.  I think this is a very meaningful issue, so we should discuss possible solutions here.

Three-party storage platform：
- Hdfs/Oss/S3
- Kafka/Pulsar
- ...

**Comment by 2000liux** [comment]
@liugddx Caching needs to consider the cache duration. It seems that hdfs, S3, and Oss are not good choices.
