### ISSUE TITLE
Could not find any jdbc dialect factories that implement 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath

### ISSUE THREAD

**Issue by cxy-java** [apache/seatunnel#3879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

an error occurred when I used the seatunnel engine
![image](https://user-images.githubusercontent.com/17775046/210926592-b8ea5a57-6672-494e-ba58-1aae123687b1.png)

### SeaTunnel Version

3.2.0

### SeaTunnel Config

```conf
Jdbc {
        url = "jdbc:mysql://localhost/test?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "123456"
        query = "select * from user"
    }
```

### Running Command

```shell
bin/seatunnel.sh --config config/jdbc_to_console.conf -e local
```

### Error Exception

```log
Exception StackTrace:org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factories that implement 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ElandGREEN** [comment]
what version of jdk is used ?
I have encountered this problem in jdk versions earlier than 1.8.
Plz provide complete logs to confirm which classloader is used.

**Comment by KunWangV** [comment]
same problem

**Comment by fengjian428** [comment]
how to fix this? I also met this

**Comment by Francis-Tmac** [comment]
I also met this

**Comment by YuriyGavrilov** [comment]
same but with Trino driver 
https://trino.io/docs/current/client/jdbc.html
