### ISSUE TITLE
[Improve] [Doc] Improve OSSFile Connector title

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

update `OssFile ` to `OssFile[Jindo] ` is better.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/32193458/210947010-76f59da1-b717-42e1-bd0b-498558273af1.png">

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx。
