### ISSUE TITLE
[Feature][Zeta] Add Zeta Client ShutdownHook To Cancel Job

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3924]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At now, if we submit job to cluster use engine client, then we kill client or use Ctrl+C to shutdown. The job will continue execute in the cluster. We should add ShutdownHook in client side, to cancel job when client shutdown. 
1. Support Cancel Job use ShutdownHook When client shutdown
2. Support use shell command to determine if client shutdown should cancel job or not when submit job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Assign to me thanks.
