### ISSUE TITLE
[Feature][Zeta] add the dataType of partition_column for JDBC, for example DateTime

### ISSUE THREAD

**Issue by zengxiaosong** [apache/seatunnel#3931]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

many table don't have the dataType of  int or decimal  in hospital

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Duplicate with #3973, so I will close it, if you have any problems please reopen this and send a disscuss e-mail to `dev@seatunnel.apache.org`, thank you!
