### ISSUE TITLE
[Discuss][Zeta-Client] Get task information.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3948]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now if we want to get task execution information, we need to get it through the seatunnel.sh script then print in the console.
Since the commands are blocked, it is necessary to wait for a command to be executed before executing the next one.

Can we change the command to execute asynchronously, and then print the execution result to the client log file?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Maybe make the client console an interactive mode of communication.

**Comment by TyrantLucifer** [comment]
Now zeta support print job support for timing output statistics. You can see the details about this pr #3913

**Comment by liugddx** [comment]
> Now zeta support print job support for timing output statistics. You can see the details about this pr #3913

I am not referring to the indicator data, I think the client can be made interactive, so that there is no need for a task and a link.

**Comment by TyrantLucifer** [comment]
> > Now zeta support print job support for timing output statistics. You can see the details about this pr #3913
> 
> I am not referring to the indicator data, I think the client can be made interactive, so that there is no need for a task and a link.

OK, got it.
