### ISSUE TITLE
[Bug] [Jdbc source] Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Jdbc'} not found.

### ISSUE THREAD

**Issue by javaite** [apache/seatunnel#3949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I wrote an test for source of jdbc, and an error has occurred
![image](https://user-images.githubusercontent.com/293920/212471336-f97e4880-cf7f-4eae-a08a-4c7ab946d830.png)

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
template file:
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  Jdbc {
    url = "jdbc:mysql://l27.0.0.1:3306/source"
    driver = "com.mysql.jdbc.Driver"
    user = "root"
    password = "******"
    query = "select * from demo"
  }
}

sink {
  Console {}
}
```

### Running Command

```shell
bin/seatunnel.sh --config ~/v2.batch.config.template -e local
```

### Error Exception

```log
Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Jdbc'} not found
```

### Flink or Spark Version

engineType='seatunnel'

### Java or Scala Version

java 11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
See https://github.com/apache/incubator-seatunnel/blob/dev/plugins/README.md https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/faq.md

**Comment by TyrantLucifer** [comment]
Please do the prepare work, you can refer to https://seatunnel.apache.org/docs/2.3.0/start-v2/locally/deployment get more details.

**Comment by WilliaJing** [comment]
@javaite Excuse me, have you solved this problem?
