### ISSUE TITLE
[Feature][Statistics] Connector pr not yet merged

### ISSUE THREAD

**Issue by Zephyrcf** [apache/seatunnel#3960]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

连接器名称 | pr
-- | --
DingTalk | https://github.com/apache/incubator-seatunnel/pull/2757
Kylin | https://github.com/apache/incubator-seatunnel/pull/3116
TIKV | https://github.com/apache/incubator-seatunnel/pull/3173
Excel File | https://github.com/apache/incubator-seatunnel/pull/2585
GoogleSheets  | https://github.com/apache/incubator-seatunnel/pull/3411 https://github.com/apache/incubator-seatunnel/pull/3848
presto | https://github.com/apache/incubator-seatunnel/pull/3774
StarRocks | https://github.com/apache/incubator-seatunnel/pull/3679
Druid | https://github.com/apache/incubator-seatunnel/pull/2937
SelectDB cloud | https://github.com/apache/incubator-seatunnel/pull/3958

</html>

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sanjaychitransh** [comment]
presto | #3774 when this PR will merged
