### ISSUE TITLE
[Feature][connector-cdc] Configuration-related optimization suggestions

### ISSUE THREAD

**Issue by 2000liux** [apache/seatunnel#3971]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

#### Question 1
- When constructing MySql, SqlServer, and SourceConfig, some repeated string keys appear directly in the code 
- Is it possible to extract these same operations involved in building Properties into public methods, each class only needs to handle different content separately?
- Make other JdbcSourceConfigFactory subclass factory code simpler and more elegant.

- Below is the existing code
  - mysql
![image](https://user-images.githubusercontent.com/42398474/212905406-f54a47bd-ae9e-4480-842c-3b8e250cafaa.png)
  - sqlServer
![image](https://user-images.githubusercontent.com/42398474/212905464-fbb6a6d6-b38f-445d-804b-334c8ed133e6.png)

#### Question 2
- The JdbcSourceOptions class in the connector-cdc-base module is a public options class, and the PORT field attribute defaults to 3306. This port is only used by mysql, and other databases may have some hidden dangers when using this key.

![image](https://user-images.githubusercontent.com/42398474/212906209-ef988063-c7da-417e-bf23-62caae352028.png)

#### Question 3
- I found that there may be inelegant writing in the code of some options
   - For example
![image](https://user-images.githubusercontent.com/42398474/212907030-c9d320de-95d9-45ce-b780-5a42b0e2a408.png)
![image](https://user-images.githubusercontent.com/42398474/212907131-858de6db-fa62-4b97-9640-0f27fd81d189.png)
![image](https://user-images.githubusercontent.com/42398474/212907768-4a72fa60-e356-4312-8b4a-52d81def7dd9.png)

---
#### Remarks
- I have carefully read the source code of flink, and some excellent codes related to options and configuration of flink can simplify integration into the seatunnel project.
- Hope to join this project and submit an issue for the first time. Hope my suggestion can make the seatunnel part code more elegant.
- If my suggestion is effective, please assign me this task。
- Can you leave valuable suggestions on this issue, which will enable me to integrate into the seatunel project more quickly。Tasnks  [How to join this project](https://github.com/apache/incubator-seatunnel/discussions/3970)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2000liux** [comment]
Is my issue tag correct ？
- 我的这个 issue 标签是否正确？

**Comment by TyrantLucifer** [comment]
Looking forward your contirbution!

**Comment by 2000liux** [comment]
@TyrantLucifer 
Is there a development group. I may encounter some problems in the development process and hope to solve them。

- For example, properties in the base class are inaccessible. Its access right is protected
- ![image](https://user-images.githubusercontent.com/42398474/213073409-5ae2d7e5-106f-47cb-977a-801addc16115.png)

- for example:
  - Can I build a map or pojo at the end of the fromReadonlyConfig method and provide the map public get method so that these properties can be accessed in the provided construction Properties public class, or have better suggestions.

**Comment by TyrantLucifer** [comment]
> @TyrantLucifer Is there a development group. I may encounter some problems in the development process and hope to solve them。
> 
> * For example, properties in the base class are inaccessible. Its access right is protected
> * ![image](https://user-images.githubusercontent.com/42398474/213073409-5ae2d7e5-106f-47cb-977a-801addc16115.png)
> * for example:
>   
>   * Can I build a map or pojo at the end of the fromReadonlyConfig method and provide the map public get method so that these properties can be accessed in the provided construction Properties public class, or have better suggestions.

You can add my wechat: tyrantlucifer
