### ISSUE TITLE
[Feature][Connector-V2] JDBC Source Connector `partition_key` support Date/String type.

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#3973]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

JDBC Source Connector only support number as `partition_key` type. We should support Date and String as `partition_key` type.
1. Support Date(Or Date Type String, like: `2022-12-11`) and String as `partition_key` type
2. String type support `prefix`, so if users string always start with `seatunnel`, we can config prefix `seatunnel` to split all data start with `seatunnel`, like `seatunnel-1`, `seatunnel-2`, `seatunnel-3`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
assign to me

**Comment by 2000liux** [comment]
I will also follow up on this issue

**Comment by liugddx** [comment]
> I will also follow up on this issue

You can do the second point.  cc : @Hisoka-X
