### ISSUE TITLE
[Feature][Connectors] Support delta lake read and write function

### ISSUE THREAD

**Issue by 2000liux** [apache/seatunnel#3983]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

- I did not find delta read and sink task items in [[Umbrella][Connector] New SeaTunnel API Connectors interface](https://github.com/apache/incubator-seatunnel/issues/1946)

- I think this feature should be supported

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ikstewa** [comment]
@2000liux I see you marked this as completed. Do you have any details on the Delta Lake support?
