### ISSUE TITLE
[Bug] [seatunnel-spark-connector-v2-example] pluginName not found Error running Spark Connector V2 example using idea

### ISSUE THREAD

**Issue by msftgitsklsd** [apache/seatunnel#3992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want to test maxcompute source on local machine 
1.In project seatunnel-spark-connector-v2-example add file  in dir resource/examples/max.conf
2. seatunnel-spark-connector-v2-example pom.xml add 
  <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>connector-maxcompute</artifactId>
            <version>${project.version}</version>
        </dependency>
3.change org.apache.seatunnel.example.engine.SeaTunnelEngineExample args to '/examples/max.conf'
4.run org.apache.seatunnel.example.engine.SeaTunnelEngineExample then get error   pluginName not found

### SeaTunnel Version

commit d7280abbe9e72262640836182a7f090a5706988a (HEAD, tag: 2.3.0)

### SeaTunnel Config

```conf
env {
  spark.app.name = "seatunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = "local[2]"
  // 这个配置必需填写
   #spark.sql.catalogImplementation = "hive"
}
source {
  Maxcompute {
    accessId="accessId"
    accesskey="accesskey"
    endpoint="http://service.cn-beijing.maxcompute.aliyun.com/api"
    project="dw_data_dev"
    table_name="test3"
    #split_row = 10000
  }
}


sink {
  Console {}
}
```

### Running Command

```shell
org.apache.seatunnel.example.engine.SeaTunnelEngineExample.main
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Maxcompute'} not found.
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:58)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.spark.v2.ExampleUtils.builder(ExampleUtils.java:43)
	at org.apache.seatunnel.example.spark.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:29)
```

### Java or Scala Version

java version "1.8.0_231"

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msftgitsklsd** [comment]
After reload all dependencies proberm sloved，the ide can not load the plugin

**Comment by PG-Young** [comment]
23/02/20 14:53:57 ERROR yarn.Client: Application diagnostics message: User class threw exception: org.apache.seatunnel.core.starter.exception.CommandExecuteException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='KafkaStream'} not found


./start-seatunnel-spark-connector-v2.sh  --master yarn  --deploy-mode cluster --config ../config/example04.conf

这个是什么问题呢   该怎么解决？
