### ISSUE TITLE
[Improve][Connector-fake] Optimizing Data Generation Strategies

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4002]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, the fake first completes the data generation, and then transmits it to the sink, if you test a large amount of data, it will cause memory overflow.  Optimization point：The generated data is directly transmitted to the sink, and it is not necessary to generate all of them.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
I hope you can assign this pr to me. I am a little white man and I am very interested in this

**Comment by liugddx** [comment]
> I hope you can assign this pr to me. I am a little white man and I am very interested in this

Has been assigned to you, feel free to contact me if you have any questions.

**Comment by liugddx** [comment]
> > I hope you can assign this pr to me. I am a little white man and I am very interested in this
> 
> Has been assigned to you, feel free to contact me if you have any questions.
