### ISSUE TITLE
[Improve][Zeta] Optimize the output of zeta client command execution

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#4013]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Optimize the output of the following related commands. Cancel meaningless printing and optimize the actual output of the command
```
-l, --list         list job status
-j, --job-id       Get job status by JobId
--metrics          Get job metrics by JobI
```

For example seatunnel.sh -j jobID

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/83933160/215653807-b6a3b1ea-bfb3-4070-81ea-2f63da794e7e.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ic4y** [comment]
@FWLamb still interested in this issues?

**Comment by MonsterChenzhuo** [comment]
" optimize the actual output " Do you have any reference standards, or examples?

**Comment by ic4y** [comment]
> " optimize the actual output " Do you have any reference standards, or examples?

There is no better example. It looks clear and easy to understand.

**Comment by ic4y** [comment]
For example this style. etc..
<img width="815" alt="image" src="https://user-images.githubusercontent.com/83933160/215674855-d8cea241-6b5a-4251-adc9-a4fb40bb8f79.png">

**Comment by FWLamb** [comment]
> @FWLamb still interested in this issues?

You can assign it to people who are interested in it, thank you.

**Comment by sunnyzhuzhu** [comment]
assign it to me please! I will try my best to do it.@ic4y

**Comment by ic4y** [comment]
> assign it to me please! I will try my best to do it.@ic4y

Of course, thanks for your contribution.

**Comment by ic4y** [comment]
@sunnyzhuzhu Any progress or questions?

**Comment by sunnyzhuzhu** [comment]
> @sunnyzhuzhu Any progress or questions?

Thanks for your help! I have contacted you with wechat. Question is that Can all commands in seatunnel.sh's output irrelevant to result be removed from console, not only -l/-j/--metircs?   As they are configred through log4j2_client.properties at the same time.

**Comment by ic4y** [comment]
> > @sunnyzhuzhu Any progress or questions?
> 
> Thanks for your help! I have contacted you with wechat. Question is that Can all commands in seatunnel.sh's output irrelevant to result be removed from console, not only -l/-j/--metircs? As they are configred through log4j2_client.properties at the same time.

Output with other logs is acceptable, but key information needs to be formatted and eye-catchin.
