### ISSUE TITLE
[Improve][Zeta][Imap store] support S3,OSS 

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4014]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, Imap has supported the hdfs persistence method, and now it needs to support OSS/S3.

You can refer to
https://github.com/apache/incubator-seatunnel/blob/6a4a850b4c92a3b01beba5e1686024a51fdd507e/seatunnel-engine/seatunnel-engine-storage/checkpoint-storage-plugins/checkpoint-storage-hdfs/src/main/java/org/apache/seatunnel/engine/checkpoint/storage/hdfs/HdfsStorage.java#L63

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunnyzhuzhu** [comment]
can you assign it to me please? thanks very much!

**Comment by liugddx** [comment]
> can you assign it to me please? thanks very much!

Already assigned to you, please enjoy!

**Comment by tc-gaoxiong** [comment]
about support oss/s3，is hdfs on oss/s3? or write to oss/s3 directly.

**Comment by liugddx** [comment]
> about support oss/s3，is hdfs on oss/s3? or write to oss/s3 directly.

Does it make any difference?

**Comment by tc-gaoxiong** [comment]
> > about support oss/s3，is hdfs on oss/s3? or write to oss/s3 directly.
> 
> Does it make any difference?

imap -> oss; or imap -> hdfs, but hdfs data storage in oss

**Comment by tc-gaoxiong** [comment]
https://github.com/apache/seatunnel/pull/4683, maybe this issue has fixed.
