### ISSUE TITLE
[Feature][API] Add Key Features enum for Source and Sink connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4021]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, the key features supported by source and sink are only described through documents, and I think there are often errors in the documents. Is it better for us to enumerate the Key Features of Source and Sink, and then add an interface in the factory of the connector so that the connector can return the features it supports?

We now support run with savepoint, but the program does not know whether a job can be retransmitted at a breakpoint. If our Source and Sink can tell the framework layer whether they support exactly-once, then the framework layer can know whether the job can be continued at break points (if both source and Sink support exactly-once, we think the job supports continued at break points).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
example

Add interface
```java
public interface SupportExctlyOnce {

}
```

Source or Sink implement interface
```java
public class MySource implements SeaTunnelSource, SupportExctlyOnce {
}
```

**Comment by EricJoy2048** [comment]
> example
> 
> Add interface
> 
> ```java
> public interface SupportExctlyOnce {
> 
> }
> ```
> 
> Source or Sink implement interface
> 
> ```java
> public class MySource implements SeaTunnelSource, SupportExctlyOnce {
> }
> ```

I suggest we add key feature enum 

```
public enum SourceKeyFeature {
       Exactly-once,
       xxxx, 
       xxxx
}

public enum SinkKeyFeature {
       xxx,
       xxx
}
```

And add method `List<SourceKeyFeature> getSupportedKeyFeatures()` to `Factory`.

**Comment by ashulin** [comment]
I agree with @hailin0 .

**Comment by laglangyue** [comment]
If it's just an empty interface tag, I think the annotation is better

**Comment by EricJoy2048** [comment]
> I agree with @hailin0 .

Ok, I think so too.

**Comment by EricJoy2048** [comment]
> If it's just an empty interface tag, I think the annotation is better

In fact, these interfaces may add methods in the future.
