### ISSUE TITLE
[Disscuss][Feature][Zeta] Add rest api module.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4044]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, the Zeta cluster lacks monitoring information and lacks a way to obtain this information, which makes jobs running a black box for users. So I suggest adding a rest method to get the cluster running status.

like :

http://localhost:8080/hazelcast/rest/getAllJobsInfo  --Get all job details.

http://localhost:8080/hazelcast/rest/getClusterInfo --Get cluster information

--

We can do it based on https://docs.hazelcast.com/hazelcast/5.2/maintain-cluster/rest-api#hide-nav.

We can customize the restapi interface, like `org.apache.seatunnel.engine.server.log.Log4j2HttpGetCommandProcessor`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
good idea

**Comment by EricJoy2048** [comment]
+1

**Comment by EricJoy2048** [comment]
I suggest add it in `seatunnel-engine-client` too.

**Comment by liugddx** [comment]
> I suggest add it in `seatunnel-engine-client` too.

Agree with you.

**Comment by liugddx** [comment]
> 
We also need the ability of server to provide restful api, just like flink .
