### ISSUE TITLE
[Feature][Zeta] Get job metrics asynchronously

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4046]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, the client will obtain the result of a task execution at the end of the task, which is not friendly to users who want to obtain the execution status of the task, so I suggest changing synchronous acquisition to asynchronous acquisition.

https://github.com/apache/incubator-seatunnel/blob/3f1dcfc9157647b98946171a034a01a60dc8fd0e/seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java#L152

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msftgitsklsd** [comment]
please let me try this
