### ISSUE TITLE
[Improve][Catalog] Make Catalog support table change operations

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#4052]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

This is a subtask of https://github.com/apache/incubator-seatunnel/issues/4050 to track completion.

Make `org.apache.seatunnel.api.table.catalog.Catalog` support various change operations of the `CatalogTable`.

And improve the MySQL Catalog.

#### Related pseudo-code

```java
// create, get, update catalog
public interface Catalog {
    // query
    List<String> listDatabases() throws CatalogException;
    List<String> listTables(String databaseName) throws CatalogException, DatabaseNotExistException;
    // get catalog table
    CatalogTable getTable(TablePath tablePath) throws CatalogException, TableNotExistException;
    // update catalog table
    void createTable(TablePath tablePath, CatalogTable table, boolean ignoreIfExists) throws TableAlreadyExistException, DatabaseNotExistException, CatalogException;
    void dropTable(TablePath tablePath, boolean ignoreIfNotExists)
            throws TableNotExistException, CatalogException;
}
```

### Usage Scenario

- Validate the table structure
- Automatic table creation
- Drop table
- Clear table data

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
@ashulin  I'm not sure how to implement this issue for now, but I'm interested in cdc and would like to find an opportunity to participate in it and take part of the work.Do you have any good suggestions?

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx。

**Comment by ruanwenjun** [comment]
> please assign to me; thx。

I am working on this issue :).
