### ISSUE TITLE
[Feature][Zeta] Make SeaTunnel Zeta support multi-table

### ISSUE THREAD

**Issue by ashulin** [apache/seatunnel#4054]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

This is a subtask of https://github.com/apache/incubator-seatunnel/issues/4050 to track completion.

Make the Zeta engine support multi-table data distribution to the corresponding data channel.

#### Related pseudo-code

```java
// For Source deserialization and Row distribution
public class MultipleRowType implements SeaTunnelDataType<SeaTunnelRow> {
    private final String[] tableNames;
    private final SeaTunnelRowType[] rowTypes;
}
```

```java
// pseudo-code
public class DistributionTransform extends SeaTunnelTransform<Record<?>> {
    // Use MultipleRowType to distribute records to corresponding data channels
    private MultipleRowType multiRowType;
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
Prepare to use [hazelcast#queue](https://docs.hazelcast.com/hazelcast/5.1/data-structures/queue) as shuffle pipeline
