### ISSUE TITLE
[Feature][CDC][Pulsar] Support read canal format message

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4066]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Reference

https://github.com/apache/incubator-seatunnel/pull/3950
https://pulsar.apache.org/docs/2.3.0/io-cdc-canal/

Feature
- [ ] update https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-connectors-v2/connector-pulsar
- [ ] add e2e testcase
- [ ] update docs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
How difficult is it，Is there a reference? I have no experience in CDC. I have parsed the schema of canal data in the offline transmission of kafka-spark-connector. I have some interest in it

**Comment by hailin0** [comment]
@laglangyue easy task,   support config `canal-json` format into pulsar source and add e2e

Reference
https://github.com/apache/incubator-seatunnel/pull/3950

**Comment by laglangyue** [comment]
ok,I would like to try it



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 7, 2023 12:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/incubator-seatunnel] [Feature][Connector][Pulsar] Supportread canal format message (Issue #4066)




 
easy task
 
Reference
 #3950
