### ISSUE TITLE
[Bug] [Connector-ClickHouse] The date type cannot maintain the original type

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#4090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I read date data from CK Source is IST type, but the data written to Sink is UTC type
I want it to be consistent and not break old types

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Assigned to me  thanks.

**Comment by zhilinli123** [comment]
@CalvinKirs Big guy help take a look at this problem
