### ISSUE TITLE
[Improve][build] Give the maven module a human readable name

### ISSUE THREAD

**Issue by taoran92** [apache/seatunnel#4100]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When building SeaTunnel the output both on the command line and in IDEs like IntelliJ always show the artifact name as the module name.

By simply setting a more human readable module name in all of the pom.xml files the build output becomes much easier to read for developers. Just like Apache Beam or Apache Flink etc.

Also, changing the names do not change anything for users because dependencies are referred to by group/artifactId.

Hi guys, Do you agree?  If so I'll clean up my experiment (see below) and put up a formal pull request.

before:
[INFO] Reactor Summary for SeaTunnel 2.3.1-SNAPSHOT:
[INFO] 
[INFO] SeaTunnel .......................................... SUCCESS [  5.748 s]
[INFO] seatunnel-shade .................................... SUCCESS [  0.508 s]
[INFO] seatunnel-jackson .................................. SUCCESS [  3.574 s]
[INFO] seatunnel-common ................................... SUCCESS [  6.299 s]
[INFO] seatunnel-api ...................................... SUCCESS [  6.732 s]
[INFO] seatunnel-plugin-discovery ......................... SUCCESS [  2.462 s]
[INFO] seatunnel-core ..................................... SUCCESS [  0.365 s]
[INFO] seatunnel-core-starter ............................. SUCCESS [  2.209 s]
[INFO] seatunnel-translation .............................. SUCCESS [  0.354 s]
[INFO] seatunnel-translation-base ......................... SUCCESS [  1.225 s]
[INFO] seatunnel-translation-flink ........................ SUCCESS [  0.318 s]
[INFO] seatunnel-translation-flink-13 ..................... SUCCESS [  2.296 s]
[INFO] seatunnel-flink-starter ............................ SUCCESS [  2.113 s]

after:

[INFO] SeaTunnel : .............................................. SUCCESS [ 3.132 s]
[INFO] SeaTunnel : Common ................................. SUCCESS [  6.332 s]
[INFO] SeaTunnel : Api .................................... SUCCESS [  6.729 s]
[INFO] SeaTunnel : Plugin Discovery ....................... SUCCESS [  2.491 s]
[INFO] SeaTunnel : Core : ................................. SUCCESS [  0.384 s]
[INFO] SeaTunnel : Core : Starter ......................... SUCCESS [  2.280 s]
[INFO] SeaTunnel : Translation : .......................... SUCCESS [  0.347 s]
[INFO] SeaTunnel : Translation : Base ..................... SUCCESS [  1.264 s]
[INFO] SeaTunnel : Translation : Flink : .................. SUCCESS [  0.314 s]
[INFO] SeaTunnel : Translation : Flink : 1.3 .............. SUCCESS [  2.127 s]
[INFO] SeaTunnel : Core : Flink Starter ................... SUCCESS [  1.963 s]
[INFO] SeaTunnel : Core : Flink Starter : 1.3 ............. SUCCESS [  3.615 s]
[INFO] SeaTunnel : Translation : Flink : 1.5 .............. SUCCESS [  2.576 s]
[INFO] SeaTunnel : Core : Flink Starter : 1.5 ............. SUCCESS [  2.726 s]
[INFO] SeaTunnel : Translation : Spark : .................. SUCCESS [  0.327 s]
[INFO] SeaTunnel : Translation : Spark : 2.4 .............. SUCCESS [  4.505 s]
[INFO] SeaTunnel : Core : Spark Starter : ................. SUCCESS [  1.573 s]
[INFO] SeaTunnel : Core : Spark Starter : 2.4 ............. SUCCESS [  3.245 s]
[INFO] SeaTunnel : Translation : Spark : 3.3 .............. SUCCESS [  3.536 s]

### Usage Scenario

maven build log or IDEs GUI(e.g. idea), make more human-readable.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by taoran92** [comment]
@TyrantLucifer hi, what do u think?

**Comment by TyrantLucifer** [comment]
Emmm, IMO, it's not make sense. Usually user will download the bin package from apache website and will not package it by themselves. cc @CalvinKirs @Hisoka-X @EricJoy2048

**Comment by Hisoka-X** [comment]
I like this change, It's really human readable. This change for developer, not user.

**Comment by taoran92** [comment]
Yes, it has no effect on user jar packages. Can we support this? i will start a pr later. thanks. @Hisoka-X

**Comment by TyrantLucifer** [comment]
> I like this change, It's really human readable. This change for developer, not user.

OK, thank you for your advice. @chucheng92 Looking forwark your contribution.

**Comment by TyrantLucifer** [comment]
Because of #4114 , this issue will be closed
