### ISSUE TITLE
The password of the configuration file needs ciphertext storage

### ISSUE THREAD

**Issue by linghuliz** [apache/seatunnel#4124]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Encrypt the password in the configuration file to avoid storing the plaintext password in the file of the production environment. This is an effective security scheme, with necessary functions.

### Usage Scenario

Production release
https://github.com/apache/incubator-seatunnel/issues/3591

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
link #4134
