### ISSUE TITLE
[Bug] [Sinker] The sink connection not closed when throw Exception in SinkWriter

### ISSUE THREAD

**Issue by rewerma** [apache/seatunnel#4132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When SinkWriter throw Exceptions, the resource (for example: JDBC connection) dose not release. Because the code: `SinkWriter.close()`  dose not be called when has Exception.

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
None
```

### Error Exception

```log
None
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MurderWind** [comment]
you should reopen this issues, it's really exists it. it should be  right what's free the connection
