### ISSUE TITLE
[Feature][Zeta][REST-API] Get all completed jobs information.

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#4145]

**Comment by Zzihh** [comment]
maybe i want to try.

**Comment by liugddx** [comment]
> maybe i want to try.

Assigned to you, thank you for supporting Seatunnel.

**Comment by liugddx** [comment]
> maybe i want to try.

What's the progress? Let me know if you need anything.

**Comment by MonsterChenzhuo** [comment]
@Zzih Will this pr go ahead? If not, I would like to take over and finish it

**Comment by liugddx** [comment]
#5949
