### ISSUE TITLE
[Feature][format] Add avro format for Seatunnel

### ISSUE THREAD

**Issue by TaoZex** [apache/seatunnel#4163]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add avro format for Seatunnel.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
You can assign it to me

**Comment by TyrantLucifer** [comment]
This requirement has been discussed in https://github.com/apache/incubator-seatunnel/issues/3120, please send an e-mail to dev@seatunnel.apache.org and discuss with community. This issue I will close it, if the result of community it is useful, you can reopen it.
