### ISSUE TITLE
[Feature][Connect jdbc] Support Array/Json/Jsonb/Timestamptz DataType in Connect jdbc PostgreSQL

### ISSUE THREAD

**Issue by ediconss** [apache/seatunnel#4213]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support Array/Json/Jsonb/Timestamptz DataType in Connect jdbc PostgreSQL

### Usage Scenario

Use Connect jdbc read PostgreSQL database

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
please assign to me; thx。

**Comment by ediconss** [comment]
Can assign it to me ?  I have finished part of the work
