### ISSUE TITLE
[Bug] seatunnel spark to doris not report error when be reponse job failed

### ISSUE THREAD

**Issue by msmoving** [apache/seatunnel#4251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i use seatunnel sync data from hive to doris, the spark task log "Batch Messages Response" Status is Fail, but seatunnel still show job success. what happened about it? 

### SeaTunnel Version

2.1.0   

### SeaTunnel Config

```conf
Doris {
             fenodes="xxx:8030"
             database="xxx"
             table="xxx"
             user="xxx"
             password="xxx"
             batch_size=1000
             doris.column_separator="\\t"
             doris.columns="id, name, sex"
  }
```

### Running Command

```shell
start-seatunnel-spark --master yarn --deploy-mode client --config ./myjob.conf
```

### Error Exception

```log
not report exception
```

### Flink or Spark Version

spark version is 2.4.0-cdh6.2.1

### Java or Scala Version

2.11

### Screenshots

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/16308094/222689384-9e33d43f-79a8-4c5b-a338-91c6062fc41a.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
can you show more message ， is there any exception?

**Comment by msmoving** [comment]
> 

tks for your reply~ there is no any exception found. 
and i found the reason for it. because sink.DorisUtil.streamLoad is not catch the fail status in doris respose.
like the below picture, i will attemp to parse the reponse in our version.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/16308094/222897268-41717525-97cb-48e1-83b2-8b5b05ead7d9.png">

**Comment by msmoving** [comment]
> can you show more message ， is there any exception?

**Comment by msmoving** [comment]
> can you show more message ， is there any exception?

**Comment by laglangyue** [comment]
> > 
> 
> tks for your reply~ there is no any exception found. and i found the reason for it. because sink.DorisUtil.streamLoad is not catch the fail status in doris respose. like the below picture, i will attemp to parse the reponse in our version.
> 
> <img alt="image" width="574" src="https://user-images.githubusercontent.com/16308094/222897268-41717525-97cb-48e1-83b2-8b5b05ead7d9.png">

if possile，can you also fix it for seatunnal?

**Comment by msmoving** [comment]
> > > 
> > 
> > 
> > tks for your reply~ there is no any exception found. and i found the reason for it. because sink.DorisUtil.streamLoad is not catch the fail status in doris respose. like the below picture, i will attemp to parse the reponse in our version.
> > <img alt="image" width="574" src="https://user-images.githubusercontent.com/16308094/222897268-41717525-97cb-48e1-83b2-8b5b05ead7d9.png">
> 
> if possile，can you also fix it for seatunnal?

the latest version has changed the sync ways, and already parse the reponse , i will update my version to v2.3.0 for it
