### ISSUE TITLE
[Feature][Translation] Add Translation For Flink To Run MySQL-CDC

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#4266]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

MySQL-CDC have some feature we should implement in flink translation layer. Like 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/32387433/222903648-148ca907-9c52-437b-a865-315d10593c80.png">
But we don't implement it at now.
We should add code for some todo part in flink translation layer. To make sure MySQL-CDC run normally on flink engine.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
CC @ashulin

**Comment by ashulin** [comment]
`CoordinatedEnumeratorContext` & `CoordinatedReaderContext` have been implemented.
