### ISSUE TITLE
[OnlineMeeting&Mar.7]SeaTunnel community meeting Topic collect 

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4285]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

EricJoy2048 invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Time: 2023/03/7 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/g9HE5qfUimVF

#TencentMeeting：722-1466-3426

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
https://github.com/apache/incubator-seatunnel/pull/4286
