### ISSUE TITLE
[Feature][plugin install] auto download hadoop-uber jar when install

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4323]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now seatunel needs to rely on its own hadoop uber jar `seatunnel-shade/seatunnel-hadoop3-3.1.4-uber` package to run, but like connector, because of the license problem, we did not put this package into the binary package of the release, so we need to add the ability to automatically download the Hadoop uber package in the install script.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodingGPT** [comment]
please assigned to me tks

**Comment by TyrantLucifer** [comment]
It has supported since 2.3.0
