### ISSUE TITLE
[Bug] [connector-v2] [Eleasticsearch] document description error 

### ISSUE THREAD

**Issue by iture123** [apache/seatunnel#4370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The Description 'support version >= 2.x and < 8.x.’ is error,the correct  is 'support version >= 2.x and <= 8.x.’,Yet, st support ES 8.x.Relevant documents are as follows:
https://seatunnel.apache.org/docs/2.3.0/connector-v2/source/Elasticsearch
https://seatunnel.apache.org/docs/2.3.0/connector-v2/sink/Elasticsearch

### SeaTunnel Version

2.3

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
no
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
If it is convenient, you can assign it to me! thank you
@iture123

**Comment by zhilinli123** [comment]
You can shut it down now, @TyrantLucifer  @iture123
