### ISSUE TITLE
[Feature][Doc] Add Release Manager Document To WebSite

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4378]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

This is a release guide document https://tyrantlucifer.com/apache-release-manager.html, Please transform it to English and add to [seatunnel web site](https://github.com/apache/incubator-seatunnel-website)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lianghuan-xatu** [comment]
please assign it to me, Thx!

**Comment by EricJoy2048** [comment]
Hi, @lianghuan-xatu  What is the progress of this issue now?

**Comment by lianghuan-xatu** [comment]
Translation work is done. There is one last step left to change the link to the image. I will finish as soon as possible.
