### ISSUE TITLE
[Feature][Transform] SQLTransform Support CatalogTable

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4425]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

sub task of https://github.com/apache/incubator-seatunnel/issues/4402, So you can reference other transform's code.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tobehardest** [comment]
Hi, I want to try and get this done, can you assign it to me?
