### ISSUE TITLE
[Discuss][Sink-Hive] can sink support dymatic table

### ISSUE THREAD

**Issue by chenchurong** [apache/seatunnel#4432]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

can sink config set dymatic table ? for example, i submit a streaming task with seatunnel-2.3.1, my source is kafka, message detail is
{
  "tableName": "default.ods_table1",
  "data": "datadetail"
}

can i save data to dymatic table use key  "tableName" in kafka message

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
update your issue title

**Comment by chenchurong** [comment]
> update your issue title

updated

**Comment by kim-up** [comment]
It doesn't feel like a good design.
There will be a lot of redundant configuration information in the message. 
And sink and suorce can not achieve a clear boundary.
