### ISSUE TITLE
[DOC][Quick Start] Add Transform to Quick Start v2

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#4433]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, our official Quick Start v2 does not include Transform configuration in the example Config, which causes many new users to not know how to use Transform. It is recommended to add Transform to Quick Start v2.

The current sample configuration file is as follows:
![image](https://user-images.githubusercontent.com/83933160/228186783-daf160a6-d41b-4c13-bd90-fbf50fac5248.png)

It is recommended to modify it as follows:
![image](https://user-images.githubusercontent.com/83933160/228186957-64607a3a-abe9-4ea3-878a-e2b5a8f1f921.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kim-up** [comment]
Please assign it to me, Thx!

**Comment by ic4y** [comment]
> Please assign it to me, Thx!

Go ahead. But remember to run validation on the modified .cong file after making the changes.
