### ISSUE TITLE
[Bug] [transform-v2] cdc delete operate will change to insert

### ISSUE THREAD

**Issue by lordk911** [apache/seatunnel#4464]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want use mysqlcdc write to doris, Just for test, add a Sql transform, then When I delete a row from mysql , I can see from log  : the deleted row goes into transformer and become a insert operate send to sink

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
source is MySQL-CDC 
add a SQL transform
sink is Console and Doris
```

### Running Command

```shell
./bin/seatunnel.sh --config ./jobs/mycdc2doris.conf -e local
```

### Error Exception

```log
no error, delete operate changed to insert
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@rewerma  PTAL.
