### ISSUE TITLE
[Doc] [Sqlserver CDC] hostname is required, but the can not found in the document.

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4473]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="766" alt="image" src="https://user-images.githubusercontent.com/32193458/229273204-633001c7-7cfc-41d7-a816-cc238540ce56.png">

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodingGPT** [comment]
pls assigned to me thanks
