### ISSUE TITLE
支持国产数据库吗，如人大金仓Kingbase

### ISSUE THREAD

**Issue by chengyuan1029** [apache/seatunnel#4512]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

请问，支持国产数据库了吗？支持粒度咋样，如人大金仓Kingbase

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
it not supported now, do you has any document for us , maybe I would like to do it, because the database support is in Roadmap for me

**Comment by davidzollo** [comment]
Please describe the title and description in English, thank you

**Comment by NickYoungPeng** [comment]
#4803

**Comment by gitfortian** [comment]
> it not supported now, do you has any document for us , maybe I would like to do it, because the database support is in Roadmap for me

can seatunnel support cdc connector not only jdbc connector，realtime data integration now not supported
