### ISSUE TITLE
[Discuss][Transform-v2] The Flink engine supports Flink SQL and UDF components.

### ISSUE THREAD

**Issue by YMBSKLK** [apache/seatunnel#4547]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Flink SQL and UDF in Flink engine can solve many complex data transformation scenarios, so it is necessary for us to integrate Flink SQL and UDF transformation components.
this pull request #4543 supports Flink SQL and UDF components.@TyrantLucifer @hailin0 @EricJoy2048

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
I don't know if I understand correctly, Seatunnel is a data integration project, not a data development project. So the intermediate process should be simple. If adding these features will cause binding to the engine and increase the workload?

**Comment by hailin0** [comment]
This is a removed feature
