### ISSUE TITLE
[Bug] [Sink] [LocalFile] Produces txt file no matter what file_format is set

### ISSUE THREAD

**Issue by archibald-nice** [apache/seatunnel#4553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Local Job always produced txt file no matter what kind 'file_format' is set.

> BTW! there is no problem when I use version 2.3.0.(I switch to 2.3.1 because I want to compress file)

### SeaTunnel Version

2.3.1-release

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
    job.mode = "BATCH"
}

source {
    Jdbc {
        url = "jdbc:oracle:thin:@xx.xx.xx.xx:1521:wft?serverTimezone=Asia/Shanghai"
        driver = "oracle.jdbc.driver.OracleDriver"
        connection_check_timeout_sec = 100
        user = "test"
        password = "test"
        query = "SELECT * FROM TEST"
    }
}


sink {
    LocalFile {
        path = "/tmp/test_data/"
        custom_filename = true
        file_name_expression = "${transactionId}_${now}"
        filename_time_format = "yyyy-MM-dd"
        file_format = parquet\orc\json\csv
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/batch-demo.conf -e local
```

### Error Exception

```log
No Error logging. Just unable to get expected file type.
```

### Flink or Spark Version

No.

### Java or Scala Version

jdk-1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
`file_format` has update to `file_format_type`

**Comment by archibald-nice** [comment]
@TyrantLucifer 
Ok, everything went well. Thank you so much for your help. However, I noticed that the [Official-Doc](https://seatunnel.apache.org/docs/2.3.1/connector-v2/sink/LocalFile#file_format-string) may need to be updated
