### ISSUE TITLE
how to sync mongodb to hdfs

### ISSUE THREAD

**Issue by pekrockstar** [apache/seatunnel#4562]
都是国人，中文描述了，抱歉：

请问，mongodb同步时的schema，如果有个字段是map类型的，schema怎么写？如下：

```json
{
    "a": "abc",
    "b": 123,
    "c": {
        "c1": "abc",
        "c2": {
            "c21": "abc"
        }
    }
}
```

```json
{
    "a": "abc",
    "b": 123,
    "c": {
        "c2": {
            "c21": "abc",
            "c22": "def",
            "c23": {
                "d31": "abc"
            }
        }
    }
}
```

seatunnel里的mongodb source 大概是这么写：

```config
schema {
     fields {
      a=string
      b=int
      c=HOWTO
     }
}
```
这里的c请问填什么，这个我记得v2.1可以直接string，怎么到了2.3怎么就倒退了啊，怎么填都不行

**Comment by pekrockstar** [comment]
用的spark-v2

**Comment by zhilinli123** [comment]
Refer to job config：
https://github.com/apache/incubator-seatunnel/issues

`# Set the basic configuration of the task to be performed
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

# Create a source to connect to Mongodb
source {
  MongodbV2 {
    connection = "mongodb://user:password@127.0.0.1:27017"
    database = "test_db"
    collection = "source_table"
    schema = {
      fields {
        c_map = "map<string, string>"
        c_array = "array<int>"
        c_string = string
        c_boolean = boolean
        c_tinyint = tinyint
        c_smallint = smallint
        c_int = int
        c_bigint = bigint
        c_float = float
        c_double = double
        c_bytes = bytes
        c_date = date
        c_decimal = "decimal(38, 18)"
        c_timestamp = timestamp
        c_row = {
          c_map = "map<string, string>"
          c_array = "array<int>"
          c_string = string
          c_boolean = boolean
          c_tinyint = tinyint
          c_smallint = smallint
          c_int = int
          c_bigint = bigint
          c_float = float
          c_double = double
          c_bytes = bytes
          c_date = date
          c_decimal = "decimal(38, 18)"
          c_timestamp = timestamp
        }
      }
    }
  }
}

# Console printing of the read Mongodb data
sink {
  Console {
  }
}

`

**Comment by pekrockstar** [comment]
> Refer to job config： 参考作业配置： https://github.com/apache/incubator-seatunnel/issues

I was unable to find anything about this issue, in my opinion, seatunnel can't even do the most basic functions well. 
I am perplexed as to how it managed to be included in Apache. the project's quality really sucks.

Sorry, but the fact is indeed like this.

**Comment by zhilinli123** [comment]
https://github.com/apache/incubator-seatunnel/issues/4565
@rockagen 
I'm sorry I just slipped up
 Here are some configurations for MongoDb 
If you are confused, I can bring you to the user group to discuss with you
Currently we are discussing to complete the integration of the document will have a unified and clear document for everyone's reference

**Comment by pekrockstar** [comment]
> #4565 @rockagen I'm sorry I just slipped up Here are some configurations for MongoDb If you are confused, I can bring you to the user group to discuss with you Currently we are discussing to complete the integration of the document will have a unified and clear document for everyone's reference

First of all, thank you for your reply.

What I mean is, if one of the fields is dynamic, you know, the node fields under this field are not fixed. My idea is to use this field as a string directly, but the current schema does not recognize string.

If set `c=string` will throw exception like this:
```java
org.apache.seatunnel.api.table.type.BasicType cannot be cast to org.apache.seatunnel.api.table.type.SeaTunnelRowType
```

**Comment by zhilinli123** [comment]
> 
@MonsterChenzhuo Zhuoyu, can you help to look at this problem
