### ISSUE TITLE
[Improve][Doc] Zeta Local mode need make auto-increment to true in hazelcast.yaml file

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4579]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The default hazelcast.yaml is used for Zeta Cluster mode, In local mode, the `auto-increment` need update to `true` in the `$SEATUNNEL_HOME/config/hazelcast.yaml `.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodingGPT** [comment]
pls assigned to me tks

**Comment by EricJoy2048** [comment]
> pls assigned to me tks

Ok
