### ISSUE TITLE
[Connector-V2] [OSS] File-oss config check bug and file-oss-jindo factoryIdentifier shuold be `OSS-JINDO` 

### ISSUE THREAD

**Issue by kim-up** [apache/seatunnel#4580]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/9264192/232045625-fa98877c-78a4-4cf5-83a4-66e1502b355a.png)

The same problem occurs with  `OssFileSink`

And another problem: 
![image](https://user-images.githubusercontent.com/9264192/232046628-1a04d61a-33f3-43c5-b481-f3539109d08d.png)

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
because of #4581 merged, so I will open this issue.
