### ISSUE TITLE
[Bug] [Connector-V2] Hive `access_key、access_secret、endpoint` can not find to create the FileSystem 

### ISSUE THREAD

**Issue by kim-up** [apache/seatunnel#4582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/9264192/232183479-b3e80bef-f457-4254-9295-911692680a60.png)

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
Using Connector-Hive with OSS or S3 etc FileSystem.
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kim-up** [comment]
There ara two solutions:

1. Add `extraOptions` which includes `FileSystem` conf items in `Connector` configuration. `Oss` example: 
```
Hive {
    table_name = "default.seatunnel_orc"
    metastore_uri = "thrift://namenode001:9083"
    extra_options {
         fs.oss.accessKeyId = "xxxxxxxxx"
         fs.oss.accessKeySecret = 'xxxxxxx"
         ...
    }
  }
```
2. Or add `FileSystem` conf items in `Connector` configuration directly.
```
Hive {
    table_name = "default.seatunnel_orc"
    metastore_uri = "thrift://namenode001:9083"
    access_key = "xxxxxxxxx"
    access_secret= 'xxxxxxx"
    ...
  }
```
By the way, the keys of `FileSystem` conf items can be consistent with  `Connector-File-xxx`.
 
Which one is better, or is there a better way？

**Comment by TyrantLucifer** [comment]
`hdfs_site_path` will solve this problem:

![image](https://user-images.githubusercontent.com/51053924/232326098-42d05c6d-b9bc-4ae2-af3a-4a07326f5c9f.png)

![image](https://user-images.githubusercontent.com/51053924/232326121-7768ba80-385e-4dfa-8478-247b480b963e.png)

So I will close this issue, if you have any other problems, please start a discussion with community.
