### ISSUE TITLE
[Feature][TDengine] Using http rest connection instead of jdbc driver

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4602]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[TDengine] Using http rest connection instead of jdbc driver

reason
https://github.com/apache/incubator-seatunnel/pull/4598

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Alibaba-HZY** [comment]
I have interest to work for this issue. Please assign this issue to me.
