### ISSUE TITLE
[Feature][E2E] Add mysql-cdc e2e testcase

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4603]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add e2e testcase like `SqlServerCDCIT.java`

https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mysql-e2e
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/MySQL-CDC.md

reference
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e/src/test/java/org/apache/seatunnel/e2e/connector/cdc/sqlserver/SqlServerCDCIT.java
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/SqlServer-CDC.md

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Assigned to me I want to try thanks

**Comment by hailin0** [comment]
@zhilinli123 
looking forward to you
