### ISSUE TITLE
[Feature][CDC] Support flink running cdc job

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4605]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support flink running cdc job

### validate

Remove `@ DisabledOnContainer ` from  `SqlServerCDCIT `
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e/src/test/java/org/apache/seatunnel/e2e/connector/cdc/sqlserver/SqlServerCDCIT.java#L63

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by s7monk** [comment]
I am willing to try this ticket, counld you assign it to me,thx. @hailin0

**Comment by hailin0** [comment]
Is anyone interested?

**Comment by hailin0** [comment]
@rewerma Hello～ ，are you interested?

**Comment by zhilinli123** [comment]
Do you have a brief overview of what Flink needs to do to run CDC? I am more interested in this
@hailin0
