### ISSUE TITLE
[Feature][Zeta] Improve local mode startup request ports 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4607]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Local mode automatically sets the hazelcast startup port to `auto-increment`

local mode startup example
```shell
bin/seatunnel.sh -m local -config job.file
```

reference
https://github.com/apache/incubator-seatunnel/blob/dev/config/hazelcast.yaml#L34

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
looks same with this [issue](https://github.com/apache/incubator-seatunnel/issues/4579), if still not resolved, i want take this task, thanks.

**Comment by hailin0** [comment]
> looks same with this [issue](https://github.com/apache/incubator-seatunnel/issues/4579), if still not resolved, i want take this task, thanks.

This looks like just the documentation

**Comment by liunaijie** [comment]
@hailin0 
here is my understanding, proposal:

local mode will create a Hazelcast server in local, but it will use the default config(hazelcast.yaml). this config set the `auto-increment` to fasle. i need set it to true in local mode.

Proposal:
change this config before [createServeInLocal](https://github.com/apache/incubator-seatunnel/blob/d2094bf2e19de2bb8c6a7eb06b438982d5cb8e38/seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java#L87) 
change the `auto-increment` to true
```
seaTunnelConfig.getHazelcastConfig().getNetworkConfig().setPortAutoIncrement(true);
```

**Comment by hailin0** [comment]
> 

good，looking forward to you  @liunaijie 

> @hailin0 here is my understanding, proposal:
> 
> local mode will create a Hazelcast server in local, but it will use the default config(hazelcast.yaml). this config set the `auto-increment` to fasle. i need set it to true in local mode.
> 
> Proposal: change this config before [createServeInLocal](https://github.com/apache/incubator-seatunnel/blob/d2094bf2e19de2bb8c6a7eb06b438982d5cb8e38/seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java#L87) change the `auto-increment` to true
> 
> ```
> seaTunnelConfig.getHazelcastConfig().getNetworkConfig().setPortAutoIncrement(true);
> ```
