### ISSUE TITLE
[Feature][SeaTunnel Engine] Add OSS  to  cluster-mode  type

### ISSUE THREAD

**Issue by SeanZhang2021** [apache/seatunnel#4621]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now SeaTunnel only support hdfs in cluster-mode，could add oss to cluster-mode  type? for example: "fs.defaultFS: oss://xxx"

### Usage Scenario

using in the condition when a system didn't have hdfs but use oss.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
You can assign it to me

**Comment by TyrantLucifer** [comment]
> You can assign it to me

Assigned to you, looking forward your contribution!
