### ISSUE TITLE
[Bug] [spark] only support one sinkPlugin

### ISSUE THREAD

**Issue by sudufly** [apache/seatunnel#4648]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I set up two sink plugins, only the first one works., spark  only support one Action Operator
![image](https://user-images.githubusercontent.com/46857527/233824577-478c1b97-2832-4f1f-8733-5f8ad18cb992.png)

### SeaTunnel Version

2.31

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  spark.master = local
}

source {
    Kafka {
          topic = "telematics-base"
          format = json
          bootstrap.servers = "172.18.1.200:9092"
          consumer.group = "seatunnel_group"
    result_table_name = "xxx"

    }

}





sink {
Console {
source_table_name="xxx"
  }

Kafka {
          topic = "test"
          format = json
          bootstrap.servers = "172.18.1.200:9092"
          consumer.group = "seatunnel_group"
    source_table_name = "xxx" }

}
```

### Running Command

```shell
idea local
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sudufly** [comment]
read 自定义SeaTunnelSource，自定义kafkareader里面控制了当模式为stream的时候，永远不结束读取数据，因为read模式是批处理模式，readStream才是流处理，所以第一个sinkPlugin 永远不会结束，我试过发送signalNoMoreElement 的时候多个sinkPlugins就可以正常执行，这个是否需要修复一下呢
![image](https://user-images.githubusercontent.com/46857527/233831257-e03b4949-6741-4d17-a803-cdea88e94c88.png)

![image](https://user-images.githubusercontent.com/46857527/233831217-175b527c-2d28-4679-8f23-457e85e1c5fc.png)

**Comment by CheneyYin** [comment]
> read 自定义SeaTunnelSource，自定义kafkareader里面控制了当模式为stream的时候，永远不结束读取数据，因为read模式是批处理模式，readStream才是流处理，所以第一个sinkPlugin 永远不会结束，我试过发送signalNoMoreElement 的时候多个sinkPlugins就可以正常执行，这个是否需要修复一下呢
> ![image](https://user-images.githubusercontent.com/46857527/233831257-e03b4949-6741-4d17-a803-cdea88e94c88.png)
> 
> ![image](https://user-images.githubusercontent.com/46857527/233831217-175b527c-2d28-4679-8f23-457e85e1c5fc.png)
> 

Similar to #4640

**Comment by laglangyue** [comment]
there are some bug for spark structured streaming, can you fix it

**Comment by laglangyue** [comment]
thx for your email, and I receiver it.
