### ISSUE TITLE
[Feature][Connector][Http] Support multi-line text splits 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4649]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### support for splitting response text by line

```java
//pseudocode
boolean enableMultiLines = true;
if (enableMultiLines) {
    StringReader stringReader = new StringReader(content);
    BufferedReader bufferedReader = new BufferedReader(stringReader);
    String lineStr;
    while ((lineStr = bufferedReader.readLine()) != null) {

    }
}
```

### change location
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-connectors-v2/connector-http/connector-http-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/http/source/HttpSourceReader.java#L101

### verify
- add e2e testcase
- update docs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodingGPT** [comment]
pls assigned to me, tks

**Comment by HsbcJone** [comment]
its a good case. I have done this task. after tested i will submit pr. @hailin0 @CodingGPT

**Comment by HsbcJone** [comment]
@hailin0 The code has been submitted and local testing has passed. I hope you can review it

**Comment by HsbcJone** [comment]
pls assigned to me, tks
