### ISSUE TITLE
[Feature][Clickhouse] Update clickhouse docs

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4657]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

clickhouse unsupported  jdbc connect

Remove tip

https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Clickhouse.md
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Clickhouse.md

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kim-up** [comment]
Please assign it to me
