### ISSUE TITLE
There are design flaws in the HTTP streaming mode

### ISSUE THREAD

**Issue by wenyongning1** [apache/seatunnel#4667]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

http source  job.mode ="STREAMING"
Linkage between the poll_interval_ms parameter integer and the time parameter in the get request URL to achieve consistent extraction of data sources

### Usage Scenario

Need to use streaming mode to read HTTP data in real-time

### Related issues

You can only read HTTP data in batch mode, and you need to frequently start scheduled tasks

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Can you seed an email to dev@seatunnel.apache.org to discuss this issue?
