### ISSUE TITLE
There is an issue with the data format supported by seatunnel's HTTP source

### ISSUE THREAD

**Issue by wenyongning1** [apache/seatunnel#4669]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Document Introduction，format [String], the format of upstream data, now only support json text, default json.
But in fact, it only supports json and json array, and does not support text format
for example:
[{},{},{}]
or
{}

### Usage Scenario

When the data volume is large and there are many fields, it is necessary to save traffic and cannot follow the JSON format. The k value will occupy a large amount of traffic, and we hope to support the return value of file types.
For example, file content:
1#xiao1#25
1#xiao2#26
1#xiao2#27

### Related issues

Yes, currently there is a portion of the data going through HTTP and there are many fields.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 666fishsun** [comment]
@wenyongning1 can you give us more detailed description of your file format?
