### ISSUE TITLE
[Feature][spark engine] support native  spark sql function  when use spark engine

### ISSUE THREAD

**Issue by zhengshubin** [apache/seatunnel#4674]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In seatunnel 2.3.1, it can not use spark sql function when use spark engine, like date_format etc, spark sql function is  Conveniently  、 high fault-tolerance  than    seatunnel   function. I hope  that  seatunel can   provide  a  parameter  which
support use native  spark  sql function instad of   seatunnel   function.

### Usage Scenario

spark engine   transform

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CheneyYin** [comment]
[This](https://github.com/apache/incubator-seatunnel/pull/4543#issuecomment-1510329190) might help you.
