### ISSUE TITLE
[Feature][transform] 2.3.1中transform sql取消了多source关联join，仅允许简单sql,后续还能恢复吗

### ISSUE THREAD

**Issue by xjiahai** [apache/seatunnel#4675]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

transform 2.3.0中可以在sql使用复杂sql，如多源join，2.3.1中transform V2中sql query仅支持简单sql，后续是否考虑恢复复杂sql

### Usage Scenario

1

### Related issues

1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
thanks for your feedback.
As a global project, please update the issue title and description in English, thx

**Comment by TyrantLucifer** [comment]
I will not support join operation in the future.

**Comment by cs3163077** [comment]
why
