### ISSUE TITLE
[Feature][Zeta] hdfs checkpoint support HA configuration

### ISSUE THREAD

**Issue by VincentSleepless** [apache/seatunnel#4676]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Zeta hdfs checkpoint only support fs.defaultFS with specific namenode ip，when hdfs cluster mode is HA or Feberation, it will not works.

### Usage Scenario

org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsConfiguration 
add hdfs ha configuration , in order to increase the robustness of checkpoint read & write

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pandas886** [comment]
what is progess now ?

i found the hdfs checkpoint is not support HA mode  in org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsConfiguration.
![图片](https://github.com/apache/incubator-seatunnel/assets/123344357/c7d57862-34c4-4a70-9fa0-4a76c3389f14)
