### ISSUE TITLE
[Bug] [connector-elasticsearch] nested string fields were not serialized properly

### ISSUE THREAD

**Issue by wuguangkuo** [apache/seatunnel#4679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When read doc from elasticsearch，the nested string fields were serialized with redundant double quotation marks.
For example: I have a nested doc like this `"{\"outer\":{\"inner\":{\"id\":\"123\", \"name\":\"test\"}}}"`, when read "inner.id", I got "\"123\"". I think the correct result should be "123".

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
   Elasticsearch {
       hosts = ["ip:port"]
       index = "f_mid_refund_task"
       username = ""
       password = ""
       schema = {
           fields {
               cf.sub_order_id = string
               cf.payment_time = timestamp
       }
       result_table_name = "mytable"
   }
}

sink {

  jdbc {
      source_table_name= "mytable"
      saveMode = "update"
      url = "jdbc:mysql://ip:port/database?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true"
      driver = "com.mysql.cj.jdbc.Driver"
      user = ""
      password = ""
      query = """
      INSERT INTO order_refund_from_es (`子订单id`, `订单付款时间`)
      values(?, ?)
      """
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-2-connector-v2.sh \
--master local[4] \
--deploy-mode client \
--config ./my.conf
```

### Error Exception

```log
none
```

### Flink or Spark Version

spark 2.4.8

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpretty** [comment]
This bug maybe fixed in #4233
