### ISSUE TITLE
[Feature][connectors-elasticsearch] support query parameters and parallelism parameters.

### ISSUE THREAD

**Issue by LYL41011** [apache/seatunnel#4681]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, the lack of support for query statements and concurrency is causing many difficulties for us. It is highly inefficient when dealing with large amounts of data, and since our company mainly deals with incremental synchronization, we require a query condition limitation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpretty** [comment]
The current version of es source supports query. you can click 
https://seatunnel.apache.org/docs/2.3.1/connector-v2/source/Elasticsearch/#query-json
