### ISSUE TITLE
使用使用遇到的坑

### ISSUE THREAD

**Issue by xinxinghe** [apache/seatunnel#4691]
初次使用时，切记要按照官方文档中的步骤进行操作，一定要执行install-plugin.sh 脚本，不然会报 NoClassDefFoundError 错误

**Comment by davidzollo** [comment]
thanks for your kind reminder to new users!
Please update the title and description in English.

**Comment by lucklilili** [comment]
It would be better to describe in English

**Comment by lucklilili** [comment]
It would be better to describe in English

**Comment by lucklilili** [comment]
test

**Comment by lucklilili** [comment]
test

**Comment by lucklilili** [comment]
Can you provide a detailed description, using English to describe community response more efficiently
