### ISSUE TITLE
[Feature][Connector] Track currently unsupported data types

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#4695]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, there are many unsupported data types in the connectors and in the engine. We are now maintaining these data types through this issues.

connectors：
| connector | dataType | pr |
| --- | --------- | --- |
| Mysql CDC | Bit(N) | https://github.com/apache/incubator-seatunnel/pull/4671 |
| JDBC mysql | Bit(N)| https://github.com/apache/incubator-seatunnel/pull/4671 |
| JDBC mysql | YEAR| https://github.com/apache/incubator-seatunnel/pull/4639  |
| JDBC Postgres | GEOMETRY | https://github.com/apache/incubator-seatunnel/pull/4673|
| JDBC Postgres | GEOGRAPHY | https://github.com/apache/incubator-seatunnel/pull/4673 |

Data types that need to be supported internally by Zeta：
 | dataType | issue | pr |
| --------- | ------ |--- |
| time types with time zones | https://github.com/apache/incubator-seatunnel/issues/4682 |Wait for implementation |

welcome everyone to test and add unsupported data types, or to implement these unsupported data types.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
JDBC mysql | YEAR Assigned to me Thanks

**Comment by zhilinli123** [comment]
Mysql CDC TINYINT(n) This is also not implemented

**Comment by wuxizhi777** [comment]
bitmap不支持，clickhouse 里面有bitmap 数据类型的

**Comment by ic4y** [comment]
> bitmap不支持，clickhouse 里面有bitmap 数据类型的

@wuxizhi777 source or sink?

**Comment by ic4y** [comment]
> Mysql CDC TINYINT(n) This is also not implemented

TINYINT(n) should be read as the Bit(n) data type when accessed through JDBC, so if Bit(n) is supported, TINYINT(n) should be supported as well. 
Alternatively, wait for https://github.com/apache/incubator-seatunnel/pull/4671 to be merged, then test whether TINYINT(n) is supported

**Comment by zhilinli123** [comment]
> > Mysql CDC TINYINT(n) This is also not implemented
> 
> TINYINT(n) should be read as the Bit(n) data type when accessed through JDBC, so if Bit(n) is supported, TINYINT(n) should be supported as well. Alternatively, wait for #4671 to be merged, then test whether TINYINT(n) is supported

jdbc TINYINT(1) is also supported by Flink

**Comment by ic4y** [comment]
> > > Mysql CDC TINYINT(n) This is also not implemented
> > 
> > 
> > TINYINT(n) should be read as the Bit(n) data type when accessed through JDBC, so if Bit(n) is supported, TINYINT(n) should be supported as well. Alternatively, wait for #4671 to be merged, then test whether TINYINT(n) is supported
> 
> jdbc TINYINT(1) is also supported by Flink


In #4671, TINYINT(1) is already supported. You can add corresponding tests in #4639.

**Comment by zhilinli123** [comment]
JDBC mysql YEAR : https://github.com/apache/incubator-seatunnel/pull/4639
