### ISSUE TITLE
[Feature][connector] 支持任意格式文件(音、视、图的等非结构化数据)的同步(ftp/hdfs/s3)

### ISSUE THREAD

**Issue by BestBurning** [apache/seatunnel#4714]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

支持任意格式文件(音、视、图的等非结构化数据)的同步(ftp/hdfs/s3)

### Usage Scenario

非结构化数据的数据文件同步

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
thanks for your willing to contribute a PR 
As a global project, please update the issue title and description in English, thx
