### ISSUE TITLE
[Bug] [Hive Source Connector] During Hive source processing, data from multiple columns (Textfile type) is combined into one column.

### ISSUE THREAD

**Issue by seeker-jie** [apache/seatunnel#4731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When processing the Hive source, multiple columns of data (with data type as Textfile) will be read into a single column.
create table sql:

```sql
create table test
(
    name    string,
    age     int,
    detail  string,
    address string
)
    row format serde 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
    stored as
        inputformat 'org.apache.hadoop.mapred.TextInputFormat'
        outputformat 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
    location 'hdfs://***/test'
    tblproperties ('spark.sql.create.version' = '2.4.8', 'spark.sql.sources.schema.numParts' = '1',
        'spark.sql.sources.schema.part.0' =
                '{\"type\":\"struct\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"age\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}},{\"name\":\"detail\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"address\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}]}');
```

test data:

| name   | age | detail | address        |
|--------|-----|--------|----------------|
| test_2 | 2   | sdasd  | asds           |
| test_3 | 3   | sdfsd  | sad            |
| test_4 | 4   | asqwer | gsdfg          |
| test_5 | 5   | tet    | sadf           |
| test_6 | 6   | asdfas | asdfasdf       |
| test_7 | 7   | sdfasd | fasdsd         |
| test_8 | 8   | ghrty  | uiyuy          |
| test_9 | 9   | rwerwe | uiyui          |
| test_10| 10  | rtet   | rtytyuty       |
| test   | 1   | shaskaslajs | jsdflsjfljdfld |

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  spark.streaming.batchDuration = 5
  spark.app.name = "seatunnel"
  spark.ui.port = 13000
  spark.sql.catalogImplementation = "hive"
}

source {
  Hive {
    table_name = "default.test_st"
    metastore_uri = "thrift://myhost:9083"
  }
}
transform {
}

sink{
  console{
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh --master local --deploy-mode client --config ./config/hive-source.conf
```

### Error Exception

```log
No Exception.
```

### Flink or Spark Version

Spark version: 2.4.8

### Java or Scala Version

Openjdk version: 1.8.0_322

### Screenshots

![image](https://github.com/apache/incubator-seatunnel/assets/46879926/057c9572-86b9-454b-96fb-2ef5c81ab9ea)

<img width="419" alt="image" src="https://github.com/apache/incubator-seatunnel/assets/46879926/0c09b4e4-5a0a-49f3-a0b3-1ca97d11dc90">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@TyrantLucifer  PTAL

**Comment by TyrantLucifer** [comment]
> @TyrantLucifer PTAL

Use 2.3.1 and re test

**Comment by shysnow** [comment]
I also encountered the same problem.

**Comment by shysnow** [comment]
我看源码发现字段分隔符是通过delimiter设置的,只要设置这个delimiter=","就可以了,我的配置文件内容如下

env {
  spark.sql.catalogImplementation = "hive"
  spark.app.name = "SeaTunnel-spark3"
  spark.executor.instances = 4
  spark.executor.cores = 2
  spark.executor.memory = "5g"
  spark.yarn.queue = "aiops"
  spark.ui.enabled = true
}

source {
Hive {
  table_name = "default.hive_id_int"
  metastore_uri = "thrift://cdh129130:9083"
  kerberos_principal = "hive/cdh129144@MYCDH"
  kerberos_keytab_path = "/home/aiops/keytab/hive.keytab"
  hdfs_site_path = "/etc/hadoop/conf/hdfs-site.xml"
  parallelism = 1
  read_columns = ["nid","date_id","mm","latn_id","email","ctime","address"],
  fetch_size = 10000
  delimiter=","
  
}
}

transform {
}

sink {
Console{

}
}
