### ISSUE TITLE
[Bug] [Connector-kafka] consummer work abnormally when some partition dosen't has data

### ISSUE THREAD

**Issue by sudufly** [apache/seatunnel#4735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1. function pollNext waits for all partitions task to be done
but when some partitions dosen't has data, the CompletableFuture will blocked by the empty partition (poll(10000))
2. Is it necessary to do assign and seek everytime？
![image](https://github.com/apache/incubator-seatunnel/assets/46857527/4e6de172-9252-4bb6-9b9e-db6ce88078b8)

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
xx
```

### Running Command

```shell
xx
```

### Error Exception

```log
xx
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Do you mean the partition just quits without data? This is a streaming job, right?

**Comment by sudufly** [comment]
> Do you mean the partition just quits without data? This is a streaming job, right?

pollNext  是在一个while 里面执行的，这个方法会等待所有分区poll完成，但是在某种情况下，整个while会被阻塞（POLL_TIMEOUT 10s）
当某个分区没有数据（测试情况，或者某个分区先被消费完但是新数据还没上来），下一个while循环都会等待一个timeout的时间

**Comment by liugddx** [comment]
> > Do you mean the partition just quits without data? This is a streaming job, right?
> 
> pollNext 是在一个while 里面执行的，这个方法会等待所有分区poll完成，但是在某种情况下，整个while会被阻塞（POLL_TIMEOUT 10s） 当某个分区没有数据（测试情况，或者某个分区先被消费完但是新数据还没上来），下一个while循环都会等待一个timeout的时间

I think this wait is necessary,What do you recommend?

**Comment by sudufly** [comment]
就是在流模式下工作得不像一个流，像sparkStream ，或者自己写的kafka consumer,
就算只有一个分区有数据也能立马消费到数据，但是seatunnel 的 kafka source 在这种情况下 因为这个默认超时时间的缘故，表现就是每10s消费一次数据，如果所有分区都有数据的话就不会出现这个现象

> > > Do you mean the partition just quits without data? This is a streaming job, right?
> > 
> > 
> > pollNext 是在一个while 里面执行的，这个方法会等待所有分区poll完成，但是在某种情况下，整个while会被阻塞（POLL_TIMEOUT 10s） 当某个分区没有数据（测试情况，或者某个分区先被消费完但是新数据还没上来），下一个while循环都会等待一个timeout的时间
> 
> I think this wait is necessary,What do you recommend?

就是在流模式下工作得不像一个流，像sparkStream ，或者自己写的kafka consumer,
就算只有一个分区有数据也能立马消费到数据，但是seatunnel 的 kafka source 在这种情况下 因为这个默认超时时间的缘故，表现就是每10s才能消费一次数据，如果所有分区都有数据的话就不会出现这个现象
