### ISSUE TITLE
[Bug] [Connector-V2] Remove scheduler in JDBC sink

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#4736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

At now, we add scheduler in jdbc sink #2009 , this is not an acceptable solution, we need to remove the corresponding code, because sometimes the thread pool created in the sink cannot be recycled normally.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
cc @ic4y

**Comment by zhilinli123** [comment]
Assign it to me and I want to finish it thanks

**Comment by liugddx** [comment]
1. release the thread pool in case of exception .
2. trigger flush on checkpoint.

**Comment by liugddx** [comment]
> 1. release the thread pool in case of exception .
> 2. trigger flush on checkpoint.

@zhilinli123 
cc: @ic4y @Hisoka-X

**Comment by ic4y** [comment]
> > 1. release the thread pool in case of exception .
> > 2. trigger flush on checkpoint.
> 
> @zhilinli123 cc: @ic4y @Hisoka-X

Yes. Try to fix it rather than delete it.

**Comment by liugddx** [comment]
> > > 1. release the thread pool in case of exception .
> > > 2. trigger flush on checkpoint.
> > 
> > 
> > @zhilinli123 cc: @ic4y @Hisoka-X
> 
> Yes. Try to fix it rather than delete it.

I think checkpoint and scheduler have the same effect, so I think checkpoint can be used to replace scheduler.This keeps the code simple and reduces complexity @Hisoka-X @ic4y

**Comment by Hisoka-X** [comment]
> I think checkpoint and scheduler have the same effect, so I think checkpoint can be used to replace scheduler.This keeps the code simple and reduces complexity @Hisoka-X @ic4y

Yep
