### ISSUE TITLE
[Improve] [seatunnel-engine-storage] Extract a base/common module from module : checkpoint-storage-hdfs

### ISSUE THREAD

**Issue by GOODBOY008** [apache/seatunnel#4740]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Module `checkpoint-storage-hdfs` maybe chaos and should extract a base/common module.
<img width="482" alt="企业微信截图_16838864392702" src="https://github.com/apache/incubator-seatunnel/assets/13617900/740c4651-e23c-4712-bd6e-15b84a8f5465">

### SeaTunnel Version

latest

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Thanks for you contribution.
