### ISSUE TITLE
[Bug] Error: Could not find or load main class

### ISSUE THREAD

**Issue by zengqinchris** [apache/seatunnel#4741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

This error is reported when the latest dev code is packaged and executed to start the cluster
![image](https://github.com/apache/incubator-seatunnel/assets/44901627/707405fa-3e3a-48ee-ac68-53dfa30e9a82)

After modifying the seatunnel-cluster.sh script, it can be executed

![image](https://github.com/apache/incubator-seatunnel/assets/44901627/45ea73f4-8cad-4a71-88bf-e33ab188701a)

If the startup script is not annotated, execute it，
```
# while read line
# do
#    if [[ ! $line == \#* ]] && [ -n "$line" ]; then
#        JAVA_OPTS="$JAVA_OPTS $line"
#    fi
# done < ${APP_DIR}/config/jvm_options
```
启动脚本注释上面的shell命令就可以启动集群，但是加上就不能执行启动集群
Error reported
Error: Could not find or load main class

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
sh seatunnel-cluster.sh
```

### Error Exception

```log
Error: Could not find or load main class
```

### Flink or Spark Version

no use

### Java or Scala Version

jdk8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zengqinchris** [comment]
打包环境是  win 10，然后执行了编码处理

**Comment by zengqinchris** [comment]
dos2unix ./seatunnel-cluster.sh
dos2unix ./stop-seatunnel-cluster.sh
dos2unix ./seatunnel.sh
dos2unix ../config/seatunnel-env.sh

> 打包环境是 win 10，然后执行了编码处理

**Comment by liugddx** [comment]
Can you provide the complete JAVA_OPTS?

**Comment by zengqinchris** [comment]
目前的原因就是 在win打包字符编码问题导致的，必须在linux下打包编译才可以

**Comment by zengqinchris** [comment]
> Can you provide the complete JAVA_OPTS?

![image](https://github.com/apache/incubator-seatunnel/assets/44901627/4e6bb16d-95a6-4e7d-8c5b-e92aefd63d0b)

`JAVA_OPTS:  -Dseatunnel.config=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/seatunnel.yaml -Dhazelcast.config=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/hazelcast.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.configurationFile=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/log4j2.properties -Dseatunnel.logs.path=/home/hadoop/apache- -XX:+HeapDumpOnOutOfMemoryErrorrcent=30 -Dseatunnel.logs.file_name=seatunnel-engine-server

这个是shell打印的执行命令，如果单独拷贝出来执行，正常启动集群，如果在seatunnel-cluster.sh脚本里执行，就报错
java  -Dseatunnel.config=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/seatunnel.yaml -Dhazelcast.config=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/hazelcast.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.configurationFile=/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/config/log4j2.properties -Dseatunnel.logs.path=/home/hadoop/apache-seatun -cp /home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/lib/*:/home/hadoop/apache-seatunnel-incubating-2.3.2-SNAPSHOT/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer


Error: Could not find or load main class
`
