### ISSUE TITLE
[Bug] [Seatunnel-Config] The config module easily get ConfigIncluder Class Error.

### ISSUE THREAD

**Issue by mosence** [apache/seatunnel#4750]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When individuals repackage, it is easy to trigger errors caused by the shadow of the config module.

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
com.typesafe.config.ConfigIncluder无法转 换org.apache.seatunnel.shade.co.typesafe.config.ConfigInclude
```

### Flink or Spark Version

none

### Java or Scala Version

none

### Screenshots

![c9fb644f3ab2f89a3165b727cce1d6f](https://github.com/apache/incubator-seatunnel/assets/2803645/59eb37e6-86a7-4b54-82e8-6e2db12e1757)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
this problem can be resovled using the following solution:

1. git clone source project.
2. execute `mvn clean install -DskipTests`

**Comment by woshishen9002** [comment]
当我想要在idea中编译运行代码的时候，我同样遇到了这个问题。命令 : mvn clean install -DskipTests 
解决方法：
1》.执行mvn clean install -DskipTests    
2》.将已经编译的 seatunnel-config-base-2.3.4-SNAPSHOT.jar 手动安装到本地maven仓库 ，命令：mvn install:install-file -DgroupId=org.apache.seatunnel  -DartifactId=seatunnel-config-base -Dversion=2.3.4-SNAPSHOT "-Dfile=C:\workspace\idea\box_src\seatunnel-2.3.3\seatunnel-config\seatunnel-config-base\target\seatunnel-config-base-2.3.4-SNAPSHOT.jar"  "-Dpackaging=jar" 
3》.执行命令 ：  mvn package ，打包整个项目
4》.重新加载idea中的maven依赖（即点击idea右侧栏 maven窗口，点击Reload All Maven Projects图标）
5》.如果代码中有引入包异常的情况，重新打开idea试试

**Comment by yaoquanxin** [comment]
god love you,you are a good men. i sovle it ,thanks.my sister.
