### ISSUE TITLE
[Bug] [MYSQL-CDC] [Doris-sink] doris-sink task can not be restored from checkpoint 

### ISSUE THREAD

**Issue by JackyChenPeng** [apache/seatunnel#4756]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

if a doris-task's config file with the same sink.label-prefix, it can not be excuted twice and it always can not be restored from checkpoint.
but if I modified the sink.label-prefix ,it also can not be restored from checkpoint cuz the config file was changed.

[duplicate-label-error.txt](https://github.com/apache/incubator-seatunnel/files/11476436/duplicate-label-error.txt)
[error.txt](https://github.com/apache/incubator-seatunnel/files/11476397/error.txt)

### SeaTunnel Version

seatunnel-2.3.1

### SeaTunnel Config

```conf
env {
  job.name = "jacky.test"
  job.mode = "STREAMING"
  parallelism = 2
}

source {
  MySQL-CDC {
    result_table_name = "t_loan_apply_temp"
    catalog = {
    factory = "MySQL"
    }
    parallelism = 2
    server-id = 1001
    username = "biz-ro"
    password = "xx"
    table-names = ["mexico_one.t_loan_apply"]
    base-url = "jdbc:mysql://biz-rds-ro.norotech.lo:3306/mexico_one"
  }

}

transform {
}

sink {
    Doris {
        fenodes = "xxxx"
        username = "jacky_chen"
        password = "xx"
        source_table_name = "t_loan_apply_temp"
        table.identifier = "mexico_one.t_loan_apply"
        sink.enable-2pc = "true"
        sink.label-prefix = "biz_20230515_031906"
        doris.config = {
            format="json"
            read_json_by_line="true"
        }
    }
}
```

### Running Command

```shell
starndalone cluster
step 1. run a task manually: sh bin/seatunnel.sh  -c noroDwhConfig/mexico_one.t_loan_apply.conf 通过log找到job id
step 2. excuteing:  sh bin/seatunnel.sh -s {job id} 存savepoint
step 3. restore task  from checkpoint:    sh bin/seatunnel.sh -c noroDwhConfig/mexico_one.t_loan_apply.conf -r {job id}
```

### Error Exception

```log
please see attachment.
```

### Java or Scala Version

jdk-1.8.0-371

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi, as for your first question, the same label-prefix cannot perform the same task twice. For the time being, it may be because the two tasks finally produce the same label, which may need to be improved. As for your second question, I am not quite clear
