### ISSUE TITLE
请问下，Seatunnel和Seatunnel-Web是如何关联起来的？这部分有说明吗？

### ISSUE THREAD

**Issue by bggmjxh** [apache/seatunnel#4765]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description
我看了Seatunnel的介绍，很惊艳。大大降低了大数据治理的学习成本。但是我看了官网以及搜索之后，发现学习曲线刚开始比较陡峭。让我难以入手。
我是一名新手，目前通过文档已经可以把Seatunnel从MySQL一张表转到MySQL的另一张表。但是这种是无状态。
我看了官方的文档之后，还有如下问题，请问下，我该怎么去应用，或者说您这边有案例之类的吗?我通过google搜索之后，大多数还是宣传为主，很少有沉下来做开发使用指南的。这让我难以进一步学习使用。

1、我用了Seatunnel是不是可以不用Flink了？用Seatunnel自带的引擎，能做到流批一体吗？
2、Seatunnel的CDC这一部分是怎么使用的？我没看到文档上有这方面的介绍。
3、Seatunnel和Seatunnel-Web是如何关联起来的？正式版的Web应用在什么时候发布？
4、Seatunnel强依赖于海豚调度，但是我启动之后，没有发现两者除了租户和token校验，还有哪些关联？
5、Seatunnel的ETL功能是无状态的？怎么做到有状态，我通过官方的示例，试了下某一个配置，就像是一个job跑完就停了。不能是一个服务一样，是有状态的，我通过接口或者什么去传入配置，然后执行？
以上是我一个新手的一些疑问，希望能得到解答。

### Usage Scenario

新手使用

### Related issues

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
1. Yes, yes 
2.Seatunnel CDC currently supports only the Zeta engine 
3. The next version is expected to be around the end of May
4.PTAL@EricJoy2048 
5.PTAL@EricJoy2048

**Comment by zhilinli123** [comment]
myql document reference：
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md

**Comment by bggmjxh** [comment]
> myql文档参考： [https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md ](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md) [https://github.com/apache/incubator-seatunnel/blob /dev/docs/en/connector-v2/source/Mysql.md](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md)

我看了下，MySQL和JDBC方式还不支持流式处理是吧，就是目前只能是一个job启动停止一次？
这个什么时候会支持？比如说我写一个视图，定义一个字段为锚点，然后流式的增量同步或者更新。

**Comment by zhilinli123** [comment]
> 是一个job启动停止一次？

jdbc source does not support streams
jdbc sink supports stream writing
Stream reading I understand only source tables are supported and you need to use CDC to do that

**Comment by terry-xu-2021** [comment]
我也有同样的疑惑， seatunnel-web从它的文档没有看到和seatunnel的关系，只在pom里看到依赖了seatunnel-common， 是包含了所有seatunnel功能吗？web对dolphinscheduler版本是否有要求

**Comment by davidzollo** [comment]
Thanks for your attention to the new generation of super high-performance tool - Apache SeaTunnel!  As a global project, please describe your question in English. Welcome to join our local channel

---

非常感谢您关注新一代超高性能数据集成工具 - Apache SeaTunnel。作为一个全球化的开源项目，请使用英语！欢迎联系我微信:davidzollo 加入本地微信群

**Comment by will0815** [comment]
Seatunnel urgently needs an easy-to-use management platform. For an ordinary data  worker, pure configuration files are too difficult to dev or operate.........
