### ISSUE TITLE
[Bug] [seatunnel-connectors] [seatunnel-connector-spark-clickhouse]  Data cannot be imported to all nodes by configuring split_mode and sharding_key

### ISSUE THREAD

**Issue by Dylan-zj** [apache/seatunnel#4770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Cluster configuration: 

- 20 machine nodes(clickhouse-01 ~ clickhouse-20) 
- 10 shards 
- every shard has 2 replicas
- the weight of every shard is 1

Configure split_mode=true, specify  sharding_key, and the sharding_key is String type 

After importing the data, it is found that only 8 nodes(clickhouse-01 ~ clickhouse-08) have data.

Root cause: 
`(hashInstance.hash(ByteBuffer.wrap(row.getString(fieldIndex).getBytes), 0) & Long.MaxValue % shardWeightCount).toInt (Clickhouse.scala 440)`
When the hash function is used to determine which shard to import data, '%' has a higher priority than '&', and the shardWeightCount is 20 in my case, then `Long.MaxValue % shardWeightCount` is 7, so the result of this line is one of 0 to 7.
 Finally, the data only can be imported to clickhouse-01 ~  clickhouse-08

### SeaTunnel Version

v 2.1.3

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
None
```

### Error Exception

```log
None
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuxizhi777** [comment]
assign to me!!

**Comment by liugddx** [comment]
> assign to me!!!

Already assigned to you.

**Comment by wuxizhi777** [comment]
val hashInstance = XXHashFactory.fastestInstance().hash64()

    val s =  "hah,what,you,am,who,am,i,123,de,df,fd,CR5,QA6,T7H,E8G,B11I,123,ZW2,SN1,34,23"

    var apps = s.split(",")

    for ( app <- apps){
      var offset = ( ( hashInstance.hash(ByteBuffer.wrap(app.getBytes), 0) & Long.MaxValue )  % 20).toInt
      println(app)
      println(offset)
    }
 this is ture write type
