### ISSUE TITLE
How to develop a new Connector？

### ISSUE THREAD

**Issue by NickCodeJourney** [apache/seatunnel#4775]
### Discussed in https://github.com/apache/incubator-seatunnel/discussions/4723

<div type='discussions-op-text'>

<sup>Originally posted by **YuanjunXu** May  9, 2023</sup>
I want to develop a new Connector.
What should I do or what interfaces should I implement？</div>

**Comment by EricJoy2048** [comment]
You can see https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-connectors-v2/README.zh.md

**Comment by NickCodeJourney** [comment]
> You can see https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-connectors-v2/README.zh.md

thx
