### ISSUE TITLE
[Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by dreamer1027** [apache/seatunnel#4779]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

jdbc sink connect为啥必须指定query，否则会报sql must not be null的错误，query只能写成Insert into table(XXX, XXX) values(?, ?)格式吗

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
We support automatic generation of write sql based on library name table name
please refer to： 
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md

**Comment by dreamer1027** [comment]
i have not found the same page in this document：
https://seatunnel.apache.org/docs/2.3.1/connector-v2/sink/Jdbc
it has to be updated?

**Comment by zhilinli123** [comment]
> i have not found the same page in this document： https://seatunnel.apache.org/docs/2.3.1/connector-v2/sink/Jdbc it has to be updated?

Our official website is being reconstructed and has not been released for the time being

**Comment by dreamer1027** [comment]
oh i know, thank you very much！
