### ISSUE TITLE
[Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by dreamer1027** [apache/seatunnel#4783]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Is there an option to automatically create a table on the hive sink?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
See #4767
