### ISSUE TITLE
[Bug] [seatunnel-transforms-v2] When using the SQL transform plugin changes SeaTunnelRow RowKind to the default RowKind.INSERT

### ISSUE THREAD

**Issue by qianxkun** [apache/seatunnel#4784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I use MySQL CDC to sync data to Elasticsearch

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Can you provide more detailed log information or configuration file information? So we can test it? thx
@qianxkun

**Comment by qianxkun** [comment]
I guess because org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLEngine#transformBySQL the return of the new SeaTunnelRow(outputFields) will discard incoming arguments and use the default values.

**Comment by qianxkun** [comment]
I guess because org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLEngine#transformBySQL the return of the new SeaTunnelRow(outputFields) will discard incoming arguments and use the default values. @zhilinli123

**Comment by zhilinli123** [comment]
I saw the same problem just now. I'll go back and try to fix it thanks for your feedback

**Comment by qianxkun** [comment]
I submitted pr for this problem

**Comment by zhilinli123** [comment]
> I submitted pr for this problem

Great! Looking forward to the merger

**Comment by zhilinli123** [comment]
pr:https://github.com/apache/seatunnel/pull/4786
