### ISSUE TITLE
[Feature][Project] Change repository name from incubator-seatunnel to seatunnel

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/seatunnel#4796]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Since 2023.05.18, SeaTunnel has graduated and becomes the top level projcet. So the repository name removed the `incubator` prefix, so we should update the repository name in whole project files.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DalongZhenZ** [comment]
let me realize it

**Comment by hailin0** [comment]
<img width="1333" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/4a9ab89d-1ba9-4c86-bfe2-e3ea93814c13">

**Comment by Ajil5467** [comment]
Hello! I would like to take up this issue.

**Comment by liugddx** [comment]
Has this issue been completed? @alibabaMapengfei

**Comment by DalongZhenZ** [comment]
> Has this issue been completed? @alibabaMapengfei

yeah,i have been completed

**Comment by liugddx** [comment]
> > Has this issue been completed? @alibabaMapengfei
> 
> yeah,i have been completed

OK I will close this issue.
