### ISSUE TITLE
[Feature][Connector]We need avro format for data when using rocketmq or kafka

### ISSUE THREAD

**Issue by sunnyleixu** [apache/seatunnel#4821]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We need avro format for data when using rocketmq or kafka,have any plan of avro?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
i want take this task
