### ISSUE TITLE
[Feature][Format] support csv format

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/seatunnel#4825]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

It is necessary to rewrite the support of csv in the file system to the format module as a general format to support kafka's needs for parsing csv.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/tree/dev/seatunnel-formats/seatunnel-format-text
