### ISSUE TITLE
[Bug] [connector-v2][mongodb] NULL data type bug

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/seatunnel#4840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
When mongo's source connector reads the NULL data type, it will report a null pointer exception
![图片](https://github.com/apache/seatunnel/assets/60029759/c70fe57e-3f3a-4c64-9a0b-3d22689f859a)

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by exxiang** [comment]
Would it be convenient to share your test data and configuration files

**Comment by exxiang** [comment]
What is your mongodb version
