### ISSUE TITLE
[Bug] [Source] Temporary files are not ignored

### ISSUE THREAD

**Issue by xiaofan2022** [apache/seatunnel#4873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

ignored Temporary files

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  # You can set spark configuration here
  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  #job.mode = BATCH
  job.name = "SeaTunnel"
  spark.executor.instances = 1
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}
source {
  Hive {
    table_name = "test.test_count"
    metastore_uri = "thrift://master1:9083"
    hdfs_site_path = "/data/conf/cdh/hadoop/hdfs-site.xml"
    read_partitions = ["dt=2023-01-01"]
    result_table_name = "hive_table"
  }
}
transform {
  #Sql {
  #  source_table_name = "hive_table"
   # result_table_name = "trans_table"
   # query = "select * from hive_table"
  #}
}

sink {
  console{
  }
}
```

### Running Command

```shell
seatunnel.sh --config test.conf --deploy-mode local
```

### Error Exception

```log
.hive-staging_hive*  Contains data, will dirty read。
```

### Screenshots

> 
![Snipaste_2023-06-02_10-30-36](https://github.com/apache/seatunnel/assets/41982310/6b71ce94-0cca-43b9-9568-61c40f237665)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Check whether there is a problem PTAL: @EricJoy2048  ,I'll fix it if I can
