### ISSUE TITLE
When will the next release be released

### ISSUE THREAD

**Issue by wu-a-ge** [apache/seatunnel#4874]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When using realease 2.3.1, I found various problems such as high cpu resource load and long task running time of zeta, which need to be fixed in the next version. Therefore, when will the next version be released so that zeta engine can be more stable

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
PATAL: @EricJoy2048

**Comment by EricJoy2048** [comment]
The release of version 2.3.2 will be completed in these two days

**Comment by davidzollo** [comment]
2.3.2 has been released
