### ISSUE TITLE
[Bug] [Sink Clickhouse] The xxhash64 sharding function does not work

### ISSUE THREAD

**Issue by 1309637127** [apache/seatunnel#4890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

We use the seatunnel to copy a table from hive to clickhouse with 6 shards we enabled the seatunnel splitmode and set the sharding_key.
When the task is finished, we found that there is only 4 shards have data, the other 2 shard does not have data.

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
split_mode = true
sharding_key = CUST_NO
```

### Running Command

```shell
no command
```

### Error Exception

```log
no exception
```

### Flink or Spark Version

Spark 2.3.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
About this problem, you can provide you with test data, conf configuration file information, and corresponding version information

**Comment by zhilinli123** [comment]
Fix pr: https://github.com/apache/seatunnel/pull/4772

**Comment by 1309637127** [comment]
@zhilinli123 
This cause 2 problems:
1、Seatunnel push data to only part of the nodes 
     We have 6 nodes in the product environment and only 4 nodes have data, the other have no data.
2、We expect the xxHash have the same xxHash result as Clickhouse
      We have further ETL job in Clickhouse, we use cust_no as the sharding key, we expect all the data concerning with the same cust_no stay in the same node, but we've test the xxHash result with Clickhouse result they are not equal.

Below is the java xxHash and Clickhouse xxHash result "00000186620663":
java xxHash: -1055457840867779448
java xxHash & Long.MAX result: 8167914195986996360
Clickhouse xxHash: 17391286232841772168

And with the xxHash result seatunnel push the customer to shard0 and in clickhouse put the customer is in shard 5
