### ISSUE TITLE
[Bug] [seatunnel-translation-flink-15] failed compile

### ISSUE THREAD

**Issue by hanhanzhang** [apache/seatunnel#4896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

failed to compile the new release 2.3.2

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
{ }
```

### Running Command

```shell
mvn clean package -DskipTests -P release
```

### Error Exception

```log
[ERROR] Failed to execute goal on project seatunnel-flink-15-starter: Could not resolve dependencies for project org.apache.seatunnel:seatunnel-flink-15-starter:jar:2.3.2: org.apache.seatunnel:seatunnel-flink-starter-common:jar:2.3.2-SNAPSHOT was not found in https://repository.apache.org/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
```

### Java or Scala Version

java8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
use `mvn clean package -DskipTests -P ci`

**Comment by Aalron** [comment]
i use `mvn clean package -DskipTests -P ci` also throw exception，How did you succeed?

**Comment by TyrantLucifer** [comment]
Use dev branch and try again

**Comment by yuxh** [comment]
Meeting the same problem when I try to compile 2.3.2 using ./mvnw install -Dmaven.test.skip

**Comment by iskunaaa** [comment]
You can try modifying seatunnel: version: 2.3.3-SNAPSHOT to 2.3.2-SNAPSHOT in all pom.xml files . for example：sed -i 's/2.3.3-SNAPSHOT/2.3.2-SNAPSHOT/g' `find ./* -name pom.xml`

**Comment by FrogJiangYY** [comment]
I have same problem in 2.3.3 release.I check flink starter 13 and 15 :
![image](https://github.com/apache/seatunnel/assets/44504578/5a41dd83-d7ed-4a67-a54a-313415e67c97)
flink 15 starter only have shell,so I annotated seatunnel-flink-starter module pom.xml about flink 15 starter，like this：
![image](https://github.com/apache/seatunnel/assets/44504578/29fd6b03-6778-4526-b936-637bca487380)
then, it success to seatunnel-flink-starter module,but fail to connecter module:
![image](https://github.com/apache/seatunnel/assets/44504578/562750ec-2d17-4f3f-a074-dfa0bfd9e93f)
![image](https://github.com/apache/seatunnel/assets/44504578/d9cc3468-a9c8-485b-8cef-7178fff458a1)
I check seatunnel-connector-v2-e2e,seatunnel-transforms-v2-e2e and root module pom.xml and annotated it,:
![image](https://github.com/apache/seatunnel/assets/44504578/7ed40d6e-c532-4285-bcab-6bef3896fd92)
at last maven build success:
![image](https://github.com/apache/seatunnel/assets/44504578/06e8b693-4981-43a2-ba86-3f0bb3ddbd74)

**Comment by novanchen** [comment]
in 2.3.3 release source code, just update ${revision} to ${project.version} like the picture below.

![image](https://github.com/apache/seatunnel/assets/4452553/945e345a-37bc-4608-ba57-85f351ec8cd7)
