### ISSUE TITLE
kafka-source 接入的数据格式是xml类型，应该如何配置能解析成表做处理

### ISSUE THREAD

**Issue by 1498658503** [apache/seatunnel#4913]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

我有一个需求，连接kafka，接到xml的数据，可以解析出字段并做后续处理吗？ 

### Usage Scenario

接收xml输入，存入数据库

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JamesBaiyong** [comment]
<img width="710" alt="image" src="https://github.com/apache/seatunnel/assets/23315594/6c45074a-aa9b-4fdd-bde1-16955571e162">
看源码，kafka source 得format参数只能枚举这些类型，xml估计不行，感觉只能把上游的输出kafka之前转换类型
