### ISSUE TITLE
[Feature][Connector] Hubspot connector support

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4931]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

HubSpot is a leading developer and marketer of software products for inbound marketing, sales, and customer service. Its primary software platform is designed to help businesses attract visitors, convert leads, and close customers.

You can reference the connectors under https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-http to implement  HubSpot Connector.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Boss Gao, assign this to me I want to try to finish it

**Comment by liugddx** [comment]
> Boss Gao, assign this to me I want to try to finish it

Already assigned to you.
