### ISSUE TITLE
[Bug] [Zeta] No response is received when the Savepoint command is executed for the second time

### ISSUE THREAD

**Issue by wu-a-ge** [apache/seatunnel#4932]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I execute seatunnel.sh -s jobid for the first time when executing Mysql CDC, my Job can exit normally and resume normally (but the periodic checkpoint will not be executed again, I think there are bugs here). When I execute seatunnel.sh -s jobid the second time, the client hangs and the server does not quit!!

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
seatunnel:
  engine:
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      max-concurrent: 1
      tolerable-failure: 2
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /data/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
```

### Running Command

```shell
seatunnel.sh -s 721621860327882753
```

### Error Exception

```log
no exception
```

### Java or Scala Version

1.8

#### server 
![image](https://github.com/apache/seatunnel/assets/2646059/3658186c-746e-4002-a2a3-7b2f9536a2da)
#### client
![image](https://github.com/apache/seatunnel/assets/2646059/09dd6af4-1d5e-4643-80ed-0b10dabbf7fa)
#### server
![image](https://github.com/apache/seatunnel/assets/2646059/cf887315-dfc9-47e0-bf98-607435bbcd96)

#### client
![image](https://github.com/apache/seatunnel/assets/2646059/f52d8ac4-55d2-4ba1-9761-4cb1162fe223)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Can you provide more detailed log information?

**Comment by Fu-Nick** [comment]
It is the info log provided above my picture, which does not produce any exception. Do you mean that I print out the DEBUG log?

**Comment by wu-a-ge** [comment]
@liugddx

**Comment by wu-a-ge** [comment]
[error.txt](https://github.com/apache/seatunnel/files/11768356/error.txt)
@liugddx

**Comment by liugddx** [comment]
> [error.txt](https://github.com/apache/seatunnel/files/11768356/error.txt) @liugddx

You can increase the checkpoint time.
https://github.com/apache/seatunnel/blob/8d5d10966d407175781da98dffa8333ad0c2749d/config/seatunnel.yaml#L28

**Comment by wu-a-ge** [comment]
That doesn't make sense, I was able to execute the savepoint in 1 second the first time, but not in 1 minute the second time, so it's definitely not a timeout issue

**Comment by dingyan2394** [comment]
i alse have this problem 2.3.2

**Comment by wu-a-ge** [comment]
> i alse have this problem 2.3.2

refer #5051
