### ISSUE TITLE
[Feature][Connector] Databricks Lakehouse Sink Support

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#4934]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Databricks Lakehouse is a very user-friendly data warehouse with a large number of users, and a Sink connector for Databricks Lakehouse is very necessary.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
assign to me, please

**Comment by nycjay** [comment]
Is this PR looking to add support for Databricks, or rather for the Delta Table format? 

Also, sink and source would both be interesting. We use Databricks to process our data and produce some resulting Delta tables. We then want to load from there into another database like SQL Server for downstream usage.
