### ISSUE TITLE
[Bug] [zeta] clickhouse to Doris，8 hours difference in datetime type

### ISSUE THREAD

**Issue by gaopeng666** [apache/seatunnel#4935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

clickhouse to Doris，8 hours difference in datetime type

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
You want to provide more detailed information for troubleshooting.

**Comment by gaopeng666** [comment]
Fixed, add server_time_zone parameter
