### ISSUE TITLE
[Feature][connector-kafka] kafka source无法解析复杂字段  (connector-kafka  does not seem to support parsing complex fields)

### ISSUE THREAD

**Issue by JamesBaiyong** [apache/seatunnel#4939]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

zh: 2.3.1版本的Kafka-source，似乎在解析复杂字段上不支持，比如如下的数据，没有办法解析到正确的字段。
en: The Seatunnel  of version 2.3.1  kafka source  connnector  does not seem to support parsing complex fields, for example, it cannot parse the following data into the correct fields.

```json
{
    "data": {
        "id": "data id",
        "create_time": "2023-06-06 20:00:12"
    }
}
```

### Usage Scenario

conf
```shell
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
}

source {
    kafka {
    result_table_name = "t1"
    consumer.group = "seatunnel_group"
    schema = {
      fields {
       data = {
          id = string
          create_time = string
       }
    }
    }
    format = json
    field_delimiter = ","
    topic = "topic_name"
    bootstrap.servers = "xxxxxxx"
    start_mode=timestamp
    start_mode.timestamp=1686587892000
  }
}


sink {
 Console {
  source_table_name="t1"
 }
}
``` 
out log
<img width="1423" alt="image" src="https://github.com/apache/seatunnel/assets/23315594/c78e4b8f-86c2-4ef2-b917-2cf990cf99c4">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
use row datatype. for example:
row = {
          id = string
          create_time = string
       }
try it.

**Comment by JamesBaiyong** [comment]
@lightzhao not work
```shell
  schema = {
      fields {
       data = {
          id = string
          create_time = string
       }
      row = {
        id = string
        create_time = string
        }
    }
    }
```

**Comment by Zhouwen-CN** [comment]
data {
    id = "string"
    create_time = "string"
 }
我试过了,可以的,这个时候data应该就是一个row类型
但是我不明白应该怎么把id和create_time提取出来,我用sql拿不到他们

**Comment by JamesBaiyong** [comment]
@chen0623-bak 如何做到的？是2.3.1版本吗？能否帖一下完整的配置

**Comment by Zhouwen-CN** [comment]
2.3.2版本

env {
  execution.parallelism = 1
  job.mode = "STREAMING"

}

source {
    kafka {
    result_table_name = "t1"
      schema = {
        fields {
         data = {
            id = "string"
            create_time = "string"
         }
      }
    }
    topic = "topic_name"
    bootstrap.servers = "hadoop110:9092"
  }
}

transform {
  Sql {
    source_table_name = "t1"
    result_table_name = "t2"
    query = "select data from t1"
  }
}

sink {
  Console {
    source_table_name = "t2"
  }
}

我尝试过  data.id
也尝试过将data换成map结构  data['id']
都无法获取到, 可能还没完善吧

**Comment by Zhouwen-CN** [comment]
我刚刚看了下源码, fieldNames, 只会存储顶层的field
data.id, data['id'] 是没有这个功能的
找不到会报错

**Comment by JamesBaiyong** [comment]
@chen0623-bak 所以是2.3.1和目前最新的2.3.2的connector都是不支持的是吧。不过我看2.3.2支持自定义udf，也许可以通过这个方式，走transform，用udf来解析。

**Comment by Zhifu-Liu** [comment]
> 我刚刚看了下源码, fieldNames, 只会存储顶层的field data.id, data['id'] 是没有这个功能的 找不到会报错

确实，field只能存储顶层字段，我也尝试了不同的配置方法进行复杂字段的部分字段提取，但是都读取不出来。
研究了一下2.3.1的源码，果然没有相关实现，目前只能全部读取出来。

**Comment by Zhouwen-CN** [comment]
@JamesBaiyong 可以试试, 传入key或者索引, 获取item

**Comment by Zhouwen-CN** [comment]
返回类型应该也是问题, 可能得写一组
getRow
getArray
getMap
getScalar

**Comment by ocean-zhc** [comment]
Im ok ! 通过transform各种转换解析可达到目的，稍微复杂点！

**Comment by CodeJess** [comment]
> Im ok ! 通过transform各种转换解析可达到目的，稍微复杂点！

您好，想请问您是如何做到的，可以分享一下吗

**Comment by ocean-zhc** [comment]
> > Im ok ! 通过transform各种转换解析可达到目的，稍微复杂点！
> 
> 您好，想请问您是如何做到的，可以分享一下吗

https://www.yuque.com/ocean-bn1qm/at42cv/ls6mh259xxbnf4cb?singleDoc# 《SeaTunnel实现Kafka Souce解析复杂Json案例（对外）》 密码：ksu0

**Comment by ocean-zhc** [comment]
> > Im ok ! 通过transform各种转换解析可达到目的，稍微复杂点！
> 
> 您好，想请问您是如何做到的，可以分享一下吗

https://www.yuque.com/ocean-bn1qm/at42cv/ls6mh259xxbnf4cb?singleDoc# 《SeaTunnel实现Kafka Souce解析复杂Json案例（对外）》 密码：ksu0

**Comment by JamesBaiyong** [comment]
> ksu0

感谢，写的很清晰，帮助很大～

**Comment by Zhifu-Liu** [comment]
> > ksu0
> 
> 感谢，写的很清晰，帮助很大～

请问你按照贴子里的udf方法跑通了吗？

**Comment by Zhouwen-CN** [comment]
@ocean-zhc 我的想法是这样的
这是我的配置, 我已经测试过了 
```
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
    FakeSource {
      result_table_name="t1"
      schema = {
        fields {
          c_int = "int"
          c_string = "string"
          c_array = "array<string>"
          c_map = "map<string,string>"
          c_row {
            c_int = "int"
            c_string = "string"
          }
        }
      }
      rows = [
        {
          kind = INSERT
          fields = [1, "zs", ["can","tiao","rap"],{"name":"zs","age":"18"},[1,"shanghai"]]
        },
        {
          kind = INSERT
          fields = [2, "ls", ["can","tiao","rap"],{"name":"ls","age":"19"},[2,"beijing"]]
        },
        {
          kind = INSERT
          fields = [3, "ww", ["can","tiao","rap"],{"name":"ww","age":"20"},[1,"shenzheng"]]
        },
      ]
    }
}
transform {
  Sql {
    source_table_name = "t1"
    result_table_name = "t2"
    -- query = "select get_time(c_row,1) from t1"
    -- query = "select get_time(c_map,'name') from t1"
    -- query = "select get_time(c_array,0) from t1"
  }
}
sink {
  Console {
    source_table_name = "t2"
  }
}
```


这是我自定义的udf

```java
@AutoService(ZetaUDF.class)
public class GetItemUDF implements ZetaUDF {

    @Override
    public String functionName() {
        return "GET_ITEM";
    }

    /**
     * 先调用 evaluate 然后才会调用 resultType
     * 所以在处理 evaluate 时,拿不到类型
     * 不然row类型应该也能根据key获取value的
     * 现在只能根据下标拿value
     * @param argsType
     * @return
     */
    @Override
    public SeaTunnelDataType<?> resultType(List<SeaTunnelDataType<?>> argsType) {
        return BasicType.STRING_TYPE;
    }

    @SneakyThrows(RuntimeException.class)
    @Override
    public Object evaluate(List<Object> args) {
        Object data = args.get(0);
        Object param = args.get(1);

        if (data instanceof Map) {
            return ((Map<?, ?>) data).get(param).toString();
        }else if(data instanceof Object[]){
            int index = Integer.parseInt(param.toString());
            return ((Object[]) data)[index].toString();
        }else if (data instanceof SeaTunnelRow){
            int index = Integer.parseInt(param.toString());
            return ((SeaTunnelRow) data).getField(index).toString();
        }
        throw new RuntimeException("this get_item function only supports [array,row,map] types ...");
    }
}
```

**Comment by Zhouwen-CN** [comment]
我改了一版, 能获取嵌套map,根据key获取row的字段, 在我发布的新的问题里面
[https://github.com/apache/seatunnel/issues/5040](url)

**Comment by yidan3166** [comment]
麻烦请教下大家，如果是数组能解析成多行处理吗？现在array<Map<string,string>>类型不支持。
比如
```
{
	"teacher_id": 12,
	"name": "liu",
	"students": [{
			"stu_id": 1,
			"name": "小明"
		}, {
			"stu_id": 2,
			"name": "小亮"
		}
	]
}
```
需要解析成 teacher_table(teacher_id,name), students(stu_id,name,teacher_id)两张表，或者udf、transform的方式也可以，感谢大家。

**Comment by Zhouwen-CN** [comment]
炸裂应该是不可以的, 上层接口规定一行输入 一行输出
