### ISSUE TITLE
[Feature][SQL Transform] Support 'select *' clause

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4941]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the sql transform support 'select *'

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@rewerma Are you interested?

**Comment by john8628** [comment]
could you assign it to me ?  i wii try it

**Comment by rewerma** [comment]
[#4991](https://github.com/apache/seatunnel/pull/4991)

**Comment by hailin0** [comment]
> could you assign it to me ? i wii try it

sorry i'm late
