### ISSUE TITLE
[Feature][connectors-v2] 希望在connector-doris中能够添加自定义be地址及端口

### ISSUE THREAD

**Issue by jianneng-fit2cloud** [apache/seatunnel#4988]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

sink配置doris时，如果目标doris是部署在docker环境中，那么seatunnel无法连接到doris be,因为RestService.getBackendsV2方法获取到的是docker ip。

![image](https://github.com/apache/seatunnel/assets/48425184/fecb2530-842e-4090-be22-cfc055e698d0)

希望能够通过配置，自定义doris be地址及端口，如果配置了be，那么使用be,否则按照原来的获取方式？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hupay** [comment]
我也遇到这个问题了。
