### ISSUE TITLE
mysql cdc mode=initial  全量阶段和增量阶段timestamp解析不一致

### ISSUE THREAD

**Issue by yinshaohua77** [apache/seatunnel#5016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

env {
  # You can set flink configuration here
  execution.parallelism = 4
  job.mode = "STREAMING"
  #checkpoint.interval = 20000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "file:///opt/soft/seatunnel/defaultfs"
}
source {
  MySQL-CDC {

    parallelism = 1
    server-id = 5656-5670
    username = "xxxxx"
    password = "xxxxx"
    table-names = ["xxxxx.xxxxx]
    base-url = "jdbc:mysql://xxxxxx:3306/xxxxxx"
    startup.mode = "initial"
    #server-time-zone = "UTC+8"
  }
}

sink {
    jdbc {

        url = "jdbc:oracle:thin:@xxxxx:1521/dbcenter"
        driver = "oracle.jdbc.OracleDriver"
        user = "xxxx"
        password = "xxxx"

        connection_check_timeout_sec = 90
        max_retries = 10
		
        table = jxxxxx
        database = xxxxx
        generate_sink_sql = true
		primary_keys = ["account","group_id"]

    }

}

对于mysql cdc timestamp 字段，无论是加不加server-time-zone = "UTC+8"，或者jdbc串里面加不加serverTimezone 的情况，都会出现全量阶段和增量阶段timestamp字段类型同步问题，相差时区的时间

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 4
  job.mode = "STREAMING"
  #checkpoint.interval = 20000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "file:///opt/soft/seatunnel/defaultfs"
}
source {
  MySQL-CDC {

    parallelism = 1
    server-id = 5656-5670
    username = "xxxxx"
    password = "xxxxx"
    table-names = ["xxxxx.xxxxx]
    base-url = "jdbc:mysql://xxxxxx:3306/xxxxxx"
    startup.mode = "initial"
    #server-time-zone = "UTC+8"
  }
}

sink {
    jdbc {

        url = "jdbc:oracle:thin:@xxxxx:1521/dbcenter"
        driver = "oracle.jdbc.OracleDriver"
        user = "xxxx"
        password = "xxxx"

        connection_check_timeout_sec = 90
        max_retries = 10
		
        table = jxxxxx
        database = xxxxx
        generate_sink_sql = true
		primary_keys = ["account","group_id"]

    }

}
```

### Running Command

```shell
zeta engine
```

### Error Exception

```log
none
```

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I want to try.

**Comment by Carl-Zhou-CN** [comment]
@yinshaohua77 hi，please modify to try below
source {
  MySQL-CDC {

    parallelism = 1
    server-id = 5656-5670
    username = "xxxxx"
    password = "xxxxx"
    table-names = ["xxxxx.xxxxx]
    base-url = "jdbc:mysql://xxxxxx:3306/xxxxxx"
    startup.mode = "initial"
   server-time-zone = "Asia/Shanghai"
  }
}

**Comment by Carl-Zhou-CN** [comment]
![image](https://github.com/apache/seatunnel/assets/67902676/b94a7f15-0483-4710-a14b-c60feb73d92d)
