### ISSUE TITLE
Fetching latest records in Batch mode - Apache Seatunnel

### ISSUE THREAD

**Issue by arjun-guptha** [apache/seatunnel#5019]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I have successfully deployed Seatunnel in my system. I'm currently working on synchronizing data between the source and sink in MySQL. I'm running Seatunnel in batch mode, but it's currently retrieving all records from the source and dumping them into the sink table. I need to run this job every 30 minutes, but it should only fetch the latest records from the source, not all the records.

Is there a way to configure Seatunnel to only retrieve the latest records from the source and dump them into the sink table in batch mode?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Pass the incremental value into sql every time it is scheduled. This can be solved by custom parameters

**Comment by arjun-guptha** [comment]
Hi @liugddx Thanks for your response.
I'm curious to know if the current released versions of this seatunnel supports incremental offline batch synchronization ?

**Comment by liugddx** [comment]
> Hi @liugddx Thanks for your response. I'm curious to know if the current released versions of this seatunnel supports incremental offline batch synchronization ?

This scenario requires the use of scheduling capabilities, DolphinScheduler might be a good choice

**Comment by baobao2016** [comment]
这个是很常用的功能，希望能添加这方面的支持

**Comment by baobao2016** [comment]
DolphinScheduler 好像也不支持动态传递sql的where条件的参数

**Comment by liugddx** [comment]
> DolphinScheduler 好像也不支持动态传递sql的where条件的参数

SeaTunnel has custom parameters.
