### ISSUE TITLE
[Doc] [StarRocks Sink] Lost base-url option in the document

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5027]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

From the code we know StarRocks Sink need a required option named `base-url`, but I am not found it in the document https://seatunnel.apache.org/docs/2.3.2/connector-v2/sink/StarRocks

#### Advanced
Since [#4572](https://github.com/apache/seatunnel/issues/4572) We have a new document format specification. Can you update StarRocks Sink document reference https://github.com/apache/seatunnel/issues/4544 and https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/sink/Mysql.md?plain=1 ?

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
pls assign to me

**Comment by liugddx** [comment]
> pls assign to me

Already assigned to you.

**Comment by liunaijie** [comment]
@EricJoy2048  i find the document already has the `base-url` option.

![image](https://github.com/apache/seatunnel/assets/28497357/5ede8b4b-30bc-4354-8605-52eb76f50065)



https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/sink/StarRocks.md?plain=1#L20

**Comment by EricJoy2048** [comment]
> https://seatunnel.apache.org/docs/2.3.2/connector-v2/sink/StarRocks

Ok, Thanks. Do you want to help seatunnel improve the document of other connector? You can comment this issue https://github.com/apache/seatunnel/issues/4572 and let we know.
