### ISSUE TITLE
[Feature][Connector] Add gbase 8a sink connector

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#5039]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

-

### Usage Scenario

-

### Related issues

-

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DalongZhenZ** [comment]
gbase have three database ,such as gabs8a  ,gbase8s  ,gbase8c,  this need three connector?

**Comment by liugddx** [comment]
> gbase have three database ,such as gabs8a ,gbase8s ,gbase8c, this need three connector?

gbase 8a

**Comment by alibabaMapengfei** [comment]
let me complate it
