### ISSUE TITLE
[STIP-16] [Design][Zeta] Add Zeta Http Client

### ISSUE THREAD

**Issue by zhibinF** [apache/seatunnel#5047]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

From https://github.com/apache/seatunnel/issues/4955 ,  we design Seatunnel Http Client instead of Seatnnel CLI.
At present, seatunnel has been implemented to query status and statistics of running jobs, as well as recent completed jobs through rest command. Now we try to design Zeta job submission via rest api.

**Job Parameter Passing**
Pass parameters as a POST request
All the parameters in the config file are passed in json format in the body of the broken post.
Other CLI job parameters are passed in parameter: clusterName, masterType, jobName, restoreJobId, async

**URL entry**
"/hazelcast/rest/maps/submit-job"

**Implementation ideas**
1. Under the rest folder to create RestHttpPostCommandProcessor. Java
2. In NodeExtension. Register RestHttpPostCommandProcessor in Java
3. Registered in RestConstant * SUBMIT_JOB_URL * for "/ hazelcast/rest/maps/submit-job",
4. Registered in the handle RestHttpPostCommandProcessor handleSubmitJob function is used to submit the task
5. Implement the submit task in the handleSubmitJob function

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
#2272 #2333

**Comment by liugddx** [comment]
Since the request is sent directly to the master node, We can directly call `CoordinatorService.submitJob` to complete the task submission.
