### ISSUE TITLE
[Bug] [Zeta] A field type is Float64 and Nullable in Clickhouse, if the data value is NULL that seatunnel reads it as 0

### ISSUE THREAD

**Issue by Henry75m39** [apache/seatunnel#5055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

My clickhouse version is 22.2.3.1, Seatunnle is  2.3.1/2.3.2

A field type Float64 and Nullable we have declared in Clickhouse. When the data value is NULL, we found seatunnel read and sink it as '0'  into a destination field of MySQL  .  

We monitor the console and see that all source values are 0 instead of NULL original values.

### SeaTunnel Version

Seatunnle is  2.3.1/2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  Clickhouse {
    host = "xxxxx:xxxx"
    database = "ods"
    sql = """
SELECT id,
           b.STRBAKCODE as code,
           a.ifundid,
           a.STRSCODE as strscode ,
           std_date,
           net_value,
           adj_net_value,
           cum_net_value,
           adj_cum_net_value,
           ten_thousand_income,
           seven_day_annualized_return          
    from
      (select
           INOFUNDSHARE  as   id,
           STRSCODE     ,
           IFUNDID         as ifundid,
           substring(SDTPERIOD,1,10)  as std_date,
           DDANWEIFENE     as net_value,
           DTIAOZHENGDWFE  as adj_net_value,
           DLEIJIFENE      as cum_net_value,
           DWFERATE_LJ  as adj_cum_net_value ,
           DWANFENSHOUYI   as ten_thousand_income,
           DNIANHUASHOUYI  as seven_day_annualized_return
      from ods.ods_jn_tbfundshareportion where toDate(SDTPERIOD) >= '2023-07-07') a
    left join(
             select distinct STRBAKCODE,STRSCODE
             from ods.ods_jn_tbcode
    ) b on upper(a.STRSCODE)=upper(b.STRSCODE) where code is not NULL
"""	
    username = "xxxxx"
    password = "xxxx"
    result_table_name = "test"
  }
}

sink {
Console {}}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/work/nav.conf -e local
```

### Error Exception

```log
No error message comes and exception occurred. program runs succeed.
```

### Flink or Spark Version

No Flink, or Spark

### Screenshots

![image](https://github.com/apache/seatunnel/assets/42402567/98020d01-cf42-4b49-993b-cc25a8e5f2a0)
![image](https://github.com/apache/seatunnel/assets/42402567/0d6859c3-b5df-4e08-b099-22d0bd9e121e)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Henry75m39** [comment]
is  there anybody look at this issue?  it is blocker of our deployment in PRD env

**Comment by jackyyyyyssss** [comment]
you can see pr [Fix][Connector-V2][Clickhouse] fix clickhouse source connector read Nullable() type is not null,exam…
