### ISSUE TITLE
恢复transform sql支持多source

### ISSUE THREAD

**Issue by cs3163077** [apache/seatunnel#5056]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

恢复transform sql支持多source。如果transform sql只支持单个的source，完全可以在source中处理，transform sql就没有意义。

### Usage Scenario

1：增量同步
2：不同数据源join

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackfirst86** [comment]
多数据源的join可以使用类似维表lookup的方式实现，zeta引擎有计划支持，我们也在试着修改并支持none、full、lru等缓存模式。
另外，tansform是否可以支持 一个输入table、多个输出table的，这个特性很重要。大家有没有实现思路？
Hope tansform can support one input table and multiple output tables. This feature is very important.
Does anyone have any implementation ideas?

**Comment by zwbachilles** [comment]
> 多数据源的join可以使用类似维表lookup的方式实现，zeta引擎有计划支持，我们也在试着修改并支持none、full、lru等缓存模式。 另外，tansform是否可以支持 一个输入table、多个输出table的，这个特性很重要。大家有没有实现思路？ Hope tansform can support one input table and multiple output tables. This feature is very important. Does anyone have any implementation ideas?

我也遇到同样问题，哥们你最后咋弄的呢？

**Comment by iventong** [comment]
多source join 的问题现在如何解决呢
