### ISSUE TITLE
[Bug] [Module Name] Cannot run in Centos6.6's env

### ISSUE THREAD

**Issue by Tangsonghuai** [apache/seatunnel#5069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use command 
tar -zxvf apache-seatunnel-xx-2.3.2.tar.gz in Centos6.6,I run a sample example,it goes wrong
the error image : NoclassDeffoundError: com/sun/jersey/client/impl/copyOnWriteHashMap

![464vheb6x210zpkcbtz7eijo1_0](https://github.com/apache/seatunnel/assets/34538205/21c89634-b9a1-434c-947d-a2e3414812e3)

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
the origion config
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
the error image : NoclassDeffoundError: com/sun/jersey/client/impl/copyOnWriteHashMap
```

### Flink or Spark Version

None

### Java or Scala Version

1.8.0_171-b11

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tangsonghuai** [comment]
please help

**Comment by jackyyyyyssss** [comment]
add 
![image](https://github.com/apache/seatunnel/assets/127465317/48ea4c15-53fe-4687-b913-89a72e0ec7ce)
lib  can resolve 
![image](https://github.com/apache/seatunnel/assets/127465317/f31aa497-a0ef-4993-9b4f-93bac13f8fa6)
maven is   <dependency>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
        <version>${project.version}</version>
        <classifier>optional</classifier>
        <scope>provided</scope>
      </dependency>

**Comment by Tangsonghuai** [comment]
> add ![image](https://user-images.githubusercontent.com/127465317/253147905-48ea4c15-53fe-4687-b913-89a72e0ec7ce.png) lib can resolve ![image](https://user-images.githubusercontent.com/127465317/253148163-f31aa497-a0ef-4993-9b4f-93bac13f8fa6.png) maven is org.apache.seatunnel
> 
> * ```
>                       <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
>                       <version>${project.version}</version>
>   ```

请问，我直接把这个包放入解压后的seatunnel的lib下面可以吗

**Comment by jackyyyyyssss** [comment]
可以的

**Comment by jackyyyyyssss** [comment]
> > add ![image](https://user-images.githubusercontent.com/127465317/253147905-48ea4c15-53fe-4687-b913-89a72e0ec7ce.png) lib can resolve ![image](https://user-images.githubusercontent.com/127465317/253148163-f31aa497-a0ef-4993-9b4f-93bac13f8fa6.png) maven is org.apache.seatunnel
> > 
> > * ```
> >                       <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
> >                       <version>${project.version}</version>
> >   ```
> 
> 请问，我直接把这个包放入解压后的seatunnel的lib下面可以吗

可以的

**Comment by Tangsonghuai** [comment]
> seatunnel-hadoop3-3.1.4-uber

非常感谢，祝你天天艳遇不断，天天发大财

**Comment by Tangsonghuai** [comment]
problem solved！

**Comment by fabianlv** [comment]
how get seatunnel-hadoop3-3.1.4-uber-2.3.2-SNAPSHOT-2.11.12.jar file?
