### ISSUE TITLE
[Feature][Connector-V2-RabbitMQ] support plain text payload

### ISSUE THREAD

**Issue by jobmission** [apache/seatunnel#5075]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Rabbitmq source connector should support non-json schema payload, like plain text or xml  , and so on.

### Usage Scenario

the rabbitmq message is plain text, not json ,no shcema.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jobmission** [comment]
still need this feature.

**Comment by 736473283** [comment]
still need this feature, too.
