### ISSUE TITLE
[Bug] [mysql cdc] where binlog create table  tinyint(1) default false  then error 

### ISSUE THREAD

**Issue by yinshaohua77** [apache/seatunnel#5095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when binlog contain "create table xxx (  xxx   tinyint(1) default false )" 
then  the process exit and report error  cannot parse false to int 

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
XXXX
```

### Running Command

```shell
XXXX
```

### Error Exception

```log
error processing binlog event
java.lang.NumberFormatException :for input string "false"
java.lang.Integer.parseInt(Integer.java:580)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I will try to add this conversion
