### ISSUE TITLE
[Feature][connector-v2] Support file path with wildcard for source connectors like SFTP/FTP  

### ISSUE THREAD

**Issue by voyagertanyao** [apache/seatunnel#5098]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Seatunnel source connector sftp/ftp ,file path do not support wildcard format , e.g /dir1/dir2/*.csv.      /dir1/prifix_*.txt

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Can you provide more detail?

**Comment by voyagertanyao** [comment]
> Can you provide more detail?

like this:
NOW, for sftp/ftp source, the config parameter "path" can only be a single file or a directory, e.g.
A:      path = "/tmp/user/2023-07-21/"
B:      path = "/tmp/user/upload/00000_0.csv"
scene A, we can get all files under path "/tmp/user/2023-07-21/",
scene B, we can get this csv file only under path "/tmp/user/upload/00000_0.csv"

BUT, when I want to get files with format csv(whatever) under a  directory, e.g.
<img width="774" alt="image" src="https://github.com/apache/seatunnel/assets/20474171/014c9807-6343-44ae-9ce4-f8a025594932">
 I can not config the path parameter like : path = "/tmp/user/2023-07-21/*.csv"
 this will lead to error , no such file found xxxxxx

THIS Idea comes from this scene: I just want to get part of files under a certain directory, not all

**Comment by FlechazoW** [comment]
I got it. I'll follow this issue. Please assign to me.

**Comment by chenhaonan313** [comment]
I'm also looking for a way to do this scene

**Comment by FlechazoW** [comment]
PR merged.

**Comment by voyagertanyao** [comment]
> PR merged.

Thanks So much
