### ISSUE TITLE
[Bug] [LocalFile] the localFile sink always write 'txt' when file_format is not 'txt'

### ISSUE THREAD

**Issue by codering** [apache/seatunnel#5116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want to write data to local  parquet file. but file suffix is always '.txt' , not '.parquet'  when I set file_format to 'parquet'
.

<img width="740" alt="image" src="https://github.com/apache/seatunnel/assets/2271825/a25fcdc2-38d8-4bda-9f95-10010d27809e">

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
sink {
  LocalFile {
    path = "/tmp/seatunnel"
    file_format = "parquet"
    field_delimiter = ","
    sink_columns = ["name","age"]
  }
}

```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
filename suffix is wrong .
```

### Java or Scala Version

java 1.8

### Screenshots

<img width="712" alt="image" src="https://github.com/apache/seatunnel/assets/2271825/72321fa5-3be4-4918-83cf-f8133b5ed5b9">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
Use the key of file_format_type, the document is wrong.
