### ISSUE TITLE
[OnlineMeeting&July.25] SeaTunnel community meeting Topic collection

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5142]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

EricJoy2048 invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Time: 2023/07/25 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/yisLUSgpYoEl

#TencentMeeting: 432-577-685

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

**Comment by kim-up** [comment]
https://github.com/apache/seatunnel/pull/5112
