### ISSUE TITLE
[Feature][CDC] Support for preferring numeric fields as split keys

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5156]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

select order:

TINYINT
SMALLINT
INT
BIGINT
DECIMAL
STRING

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
reference
https://github.com/apache/seatunnel/pull/5147/

**Comment by Carl-Zhou-CN** [comment]
Please assign it to me @hailin0
