### ISSUE TITLE
关于MySQL CDC到starrocks的同步延迟

### ISSUE THREAD

**Issue by YOMO-Lee** [apache/seatunnel#5165]
在使用seatunnel同步MySQL CDC到starrocks的时候，发现starrocks同步不及时。
首先明确一点，CDC的数据应该是实时的，问题应该是出在sink到starrocks的时候。
一开始发现是由 env 的 checkpoint.interval 参数控制的，但是不希望降低该参数，后来发现可以通过调整sink端starrocks的 batch_interval_ms 参数来控制
此问题已解决，记录一下

**Comment by Sdreamery** [comment]
请问您看看您的配置参数是怎么写的吗，我这边也是这样，同步后面没反应

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
