### ISSUE TITLE
[Bug] [MongoDB-CDC] Incremental data kind error in snapshot phase

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5169]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Incremental data kind error in snapshot phase

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
none
```

### Screenshots

cdc-base logic
<img width="1061" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/5dff1059-af60-4fb3-9189-265b4daf9f68">
<img width="853" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/76185708-c059-42aa-bda3-82a5df22e9d9">

MongoDB cdc logic
<img width="1102" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/0c8ef60d-ae7b-40d5-91f3-0f2a8b451f41">

trigger error location
<img width="877" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/76c9eea5-b032-49a6-9ac4-cfe2fbe314a8">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
MongoDB's sourceRecord can't get the operation under Envelope.operationFor, right?

**Comment by Carl-Zhou-CN** [comment]
Please assign it to me @hailin0
