### ISSUE TITLE
[SOURCE][HTTP] poll_interval_ms is disabled ，source端http里的poll_interval_ms

### ISSUE THREAD

**Issue by homjay666** [apache/seatunnel#5172]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[SOURCE][HTTP] poll_interval_ms is disabled
![image](https://github.com/apache/seatunnel/assets/64208216/3226d78d-83f4-475c-8f99-de88ecd1ae14)

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"

  # #execution.checkpoint.interval = 10000
  # #execution.checkpoint.data-uri = "hdfs://bigdata101:8020/tmp/seatunnel/checkpoint"
}


source {
Http {
  url = "http://XXX:12347/bigdata/data?id=2"
  method = "GET"
  result_table_name = "http_table"
  format = "json"
  content_field = "$.data.*"
  schema = {
    fields {
      courtName = string
      courtAreaCode = string
      courtBuildDate = string
      courtId = int
    }
  }
  # https://seatunnel.apache.org/docs/2.3.2/connector-v2/source/Http
  # TODO 轮询间隔毫秒 失效,Github提交issue
  poll_interval_ms = 50000
 }
}


transform {
  FieldMapper {
    source_table_name = "http_table"
    result_table_name = "kafka_table"
    field_mapper = {
      courtName = courtName
      courtAreaCode = courtAreaCode
      courtBuildDate = courtBuildDate
      courtId = courtId
    }
  }
}

sink {
   kafka {
       source_table_name = "kafka_table"
       topic = "zhj_flow_seatunnel"
       bootstrap.servers = "bigdata101:9092,bigdata102:9092,bigdata103:9092"
   }
}
```

### Running Command

```shell
NO
```

### Error Exception

```log
NO
```

### Zeta or Flink or Spark Version

NO

### Java or Scala Version

NO

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by homjay666** [comment]
help

**Comment by FlechazoW** [comment]
Can you provide more detail?

**Comment by homjay666** [comment]
env {
  execution.parallelism = 1
  job.mode = "STREAMING"

  # #execution.checkpoint.interval = 10000
  # #execution.checkpoint.data-uri = "hdfs://bigdata101:8020/tmp/seatunnel/checkpoint"
}


source {
Http {
  url = "http://????:12347/bigdata/data?id=2"
  method = "GET"
  result_table_name = "http_table"
  format = "json"
  content_field = "$.data.*"
  schema = {
    fields {
      courtName = string
      courtAreaCode = string
      courtBuildDate = string
      courtId = int
    }
  }
  poll_interval_ms = "测试"
  poll_interval_ms = 100000000000000000000000000
  poll_interval_ms = 50000
 }
}


transform {
  FieldMapper {
    source_table_name = "http_table"
    result_table_name = "kafka_table"
    field_mapper = {
      courtName = courtName
      courtAreaCode = courtAreaCode
      courtBuildDate = courtBuildDate
      courtId = courtId
    }
  }
}

sink {
   kafka {
       source_table_name = "kafka_table"
       topic = "zhj_flow_seatunnel"
       bootstrap.servers = "bigdata101:9092,bigdata102:9092,bigdata103:9092"
   }
}

**Comment by homjay666** [comment]
poll_interval_ms  
1、字符串
2、长整数
3、整数
执行都不会报错，此参数与运行不相关

**Comment by hanyouyou13** [comment]
poll_interval_millis  int

**Comment by homjay666** [comment]
poll_interval_millis int 不行，请求api，没有发生停顿

**Comment by homjay666** [comment]
参数名   poll_interval_ms  =>   poll_interval_millis

**Comment by homjay666** [comment]
Parameter name poll_interval_millis

**Comment by moonzhm** [comment]
@homjay666 请问您那边http流式实现了吗？我测试seatunnel的时候只能在任务启动的时候读http source一次，但可以保持流式任务运行，post新数据上去后，不论配不配置poll_interval_millis，都读不到http数据增加
