### ISSUE TITLE
[Bug] [JDBC] Oracle source The current field is DecimalType containing decimals: 18 Unable to support

### ISSUE THREAD

**Issue by junmingliu** [apache/seatunnel#5204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Oracle version: 11.2

1.数据库设置number，报错The current field is DecimalType containing decimals: 18 Unable to support。debug如下所示：
<img width="923" alt="企业微信截图_6ed2a3df-30e4-4e9b-a515-2d50ca1337e7" src="https://github.com/apache/seatunnel/assets/15081645/1b25857a-68a3-43ab-b8fe-1928dae4cf63">
2.数据库设置number(*,0)，报错The current field is DecimalType containing decimals: 18 Unable to support。debug如下所示：
<img width="756" alt="image" src="https://github.com/apache/seatunnel/assets/15081645/bcbc6090-f9e3-4340-840e-db8f83a8abdc">
3.数据库设置number(18)，成功执行。

### SeaTunnel Version

DEV branch

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  job.mode = "BATCH"
}
source{
    Jdbc {
url = "jdbc:oracle:thin:@XXXX/XXXX"
driver = "oracle.jdbc.OracleDriver"
connection_check_timeout_sec = 100
user = "XXX"
password = "XXX"
        partition_column = "ID"
partition_num = 20
fetch_size = 5000
query = "select * from indicator_bigdata"
parallelism = 5
    }
}

sink {
    jdbc {
url = "jdbc:postgresql://XXX:5432/XXX"
driver = "org.postgresql.Driver"
user = "XXX"
password = "XXX"
batch_size = 5000
batch_inteval_ms = 0
database = public
table = indicator_bigdata
generate_sink_sql = true
}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config oracle2pg.template -e local
```

### Error Exception

```log
The current field is DecimalType containing decimals: 18 Unable to support
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Your partition key cannot be a decimal place, we want it to be a positive integer

**Comment by junmingliu** [comment]
> 

I understand that it's a positive integer，when scale is zero，there are two judgments。
when basicType is long，the range of long value is between -9223372036854775808 and 9223372036854775807，it's length is 19，as to unsigned， the length is 20。
I am curious that the judgment of precision less than or equal to 18。when it's length is 19 or 20，partitionColumn is invalid，Because it would be set DecimalType(38,18)。
Besides，as a user，maybe i would use Number（there are no precision and scale） to define a positive integer，it can save positive integer。Whether we should be compatible with this situation。

**Comment by zhilinli123** [comment]
I will try to fix what seems, to be a type judgment issue

**Comment by junmingliu** [comment]
> I will try to fix what seems, to be a type judgment issue

ok，thanks。

**Comment by zhilinli123** [comment]
@ic4y @liugddx  close current issues thks
CC @junmingliu  fix issues

**Comment by liugddx** [comment]
> @ic4y @liugddx close current issues thks CC @junmingliu fix issues

OK

**Comment by liugddx** [comment]
> [junmingliu](/junmingliu)

**Comment by ic4y** [comment]
> @ic4y @liugddx close current issues thks CC @junmingliu fix issues

Thanks for the bug fix, @zhilinli123 ! Your contribution is greatly appreciated. 👍

**Comment by ic4y** [comment]
And a special shoutout to @junmingliu for reporting this bug.
