### ISSUE TITLE
[Bug] [Source Http]  params is invalid

### ISSUE THREAD

**Issue by ocean-zhc** [apache/seatunnel#5210]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Http Source  params is invalid!

### SeaTunnel Version

dev分支（2.3.2-SNAPSHOT）

### SeaTunnel Config

```conf
env {
    execution.parallelism = 5
    job.mode = "BATCH"
    job.name = "http2mysql"
}
 
source {
    Http {
        url = "http://127.0.0.1:8080/api/demo2"
        method = "POST"
        format = "json"
        params =  {
            id = 1
            }
        json_field = {
            id = "$.value[*].id"
            lrrq = "$.value[*].lrrq"
        }
        schema = {
            fields {
                id = int
                lrrq = string
            }
        }
    }

}
transform {
    
}
sink {
    console {
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh -c config/http2mysql.conf -e local
```

### Error Exception

```log
no error
```

### Zeta or Flink or Spark Version

2.3.2-SNAPSHOT

### Screenshots

<img width="1212" alt="image" src="https://github.com/apache/seatunnel/assets/46189785/42a43bef-f459-46cd-94d0-b06d76be0ea8">
<img width="482" alt="image" src="https://github.com/apache/seatunnel/assets/46189785/49bdb1a5-438d-465b-8b17-d4aa24d6c727">

The interface returns the following：
<img width="828" alt="image" src="https://github.com/apache/seatunnel/assets/46189785/66b65120-e4cd-4f4a-b63f-e3963feb980d">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ocean-zhc** [comment]
Find similar issues below:
#4497

**Comment by Hisoka-X** [comment]
cc @zhuangchong @TaoZex

**Comment by jackyyyyyssss** [comment]
@Hisoka-X  http params is form header  body is json i want to improve doc please assigned me  
![image](https://github.com/apache/seatunnel/assets/127465317/9dbd2ea2-7769-4cd6-ab50-b00bf61b0cab)

**Comment by Hisoka-X** [comment]
Thank you  @jackyyyyyssss . But I have a question, does you metioned code are reason of this issue?

**Comment by jackyyyyyssss** [comment]
> Thank you @jackyyyyyssss . But I have a question, does you metioned code are reason of this issue?

param is use httpheader application/x-www-form-urlencoded  he want to application/json httpheader  use  config like this can resolve
![image](https://github.com/apache/seatunnel/assets/127465317/e408bdde-75c4-473a-b34c-e3c235320710)
l

**Comment by Hisoka-X** [comment]
@jackyyyyyssss But I think params used for http request params like `http://localhost:8080/test?id=1`. Not used for header. The OptionRule prove that. 
![image](https://github.com/apache/seatunnel/assets/32387433/45bfc73c-dfcb-4001-9979-0807106e6745)

Maybe we should check the reason why params not worked.

**Comment by Hisoka-X** [comment]
@jackyyyyyssss I got it, thanks for your explain! It's wrong use case for use params.
