### ISSUE TITLE
[Feature][Module Name] Transform V2 SQL无法支持select * from source_table 的写法

### ISSUE THREAD

**Issue by Toroidals** [apache/seatunnel#5225]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

env {
  execution.parallelism = 1
  job.mode = "BATCH"
  spark.sql.catalogImplementation = "hive"
  spark.app.name = "seatunnel-hive-to-ck_"
  # spark.yarn.queue = "root.hive"
  spark.executor.instances = 2
  spark.executor.cores = 4
  spark.driver.memory = "3g"
  spark.executor.memory = "4g"
  spark.hadoop.hive.exec.dynamic.partition = "true"
  spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
  spark.sql.sources.partitionOverwriteMode = "dynamic"
  spark.executor.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.driver.extraJavaOptions = "-Dfile.encoding=UTF-8"
}

source {
  Hive {
    metastore_uri = "thrift://xxx:9083"
    table_name = "dm.xxx"
    read_partitions = ["day_id=20230804"]
    result_table_name = "soure_table"
  }

}

transform {
Sql {
    source_table_name = "soure_table"
    result_table_name = "sink_table"
    # 可正常执行： query = "select id,id1,id2,name,date01,timestamp01,decimal01,double01,'2023080401' as hour_id from soure_table"
    query = "select *,'2023080401' as hour_id from soure_table"  
}
}

sink {
Clickhouse {
    host = "xxx:8123"
    source_table_name = "sink_table"
    database = dm
    table = xxx
    username = "xxx"
    password = "xxx"
    clickhouse.confg = {
      max_rows_to_read = "100"
      read_overflow_mode = "throw"
          bulk_size = 100000
      retry = 3
    }
  }
}

想通过以上配置在transform 时使用sql添加字段hour_id ，但是目前 transform 不支持select *的写法

### Usage Scenario

想通过以上配置在transform 时使用sql添加字段hour_id ，但是目前 transform 不支持select *的写法，将其改为：query = "select id,id1,id2,name,date01,timestamp01,decimal01,double01,'2023080401' as hour_id from soure_table"可正常执行，但是我需要配置的表很多，相通过select * 简化配置，达到配置文件可以共用的目的，希望后续版本能支持  transform sql中：select *的写法

### Related issues

无

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2416210017** [comment]
I also found this issue. In previous versions of seatunel, it was possible to write this way, but now it seems that many of the previous features are not usable, and I think this is bad.

**Comment by Toroidals** [comment]
修改 seatunnel-transforms-v2 的 org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.init方法：
第65行：this.sql = sql 改为：this.sql = sql.replace("*", String.join(",", inputRowType.getFieldNames()));
修改后如下：

    @Override
    public void init(String inputTableName, SeaTunnelRowType inputRowType, String sql) {
        this.inputTableName = inputTableName;
        this.inputRowType = inputRowType;
        this.sql = sql.replace("*", String.join(",", inputRowType.getFieldNames()));

        List<ZetaUDF> udfList = new ArrayList<>();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        ServiceLoader.load(ZetaUDF.class, classLoader).forEach(udfList::add);

        this.zetaSQLType = new ZetaSQLType(inputRowType, udfList);
        this.zetaSQLFunction = new ZetaSQLFunction(inputRowType, zetaSQLType, udfList);
        this.zetaSQLFilter = new ZetaSQLFilter(zetaSQLFunction);

        parseSQL();
    }

**Comment by Zhouwen-CN** [comment]
seatunnel sql transform Grammar analysis dependency on **jsqlParser**
The specific error reported is here **ZetaSQLEngine class validateSQL method**
```java
            for (SelectItem selectItem : selectBody.getSelectItems()) {
                if (selectItem instanceof AllColumns) {
                    throw new IllegalArgumentException("Unsupported all columns select syntax");
                }
            }
```
When select *
selectItem instanceof AllColumns = true
