### ISSUE TITLE
[Bug] [Zeta] imap-storage-file module e2e error

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

imap-storage-file module e2e error

### SeaTunnel Version

dev
https://pipelines.actions.githubusercontent.com/serviceHosts/5f1d2e93-1249-42e2-b16d-ed31c598c5d5/_apis/pipelines/1/runs/61768/signedlogcontent/80?urlExpires=2023-08-07T08%3A06%3A07.4388650Z&urlSigningMethod=HMACV1&urlSignature=sN%2FmU3jzGF0B9ZTamYyzoJwiQGtlREiVjySaq6VhR8w%3D

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Zeta or Flink or Spark Version

dev

### Screenshots

<img width="1475" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/02bb7b05-2a85-4a29-97e3-e63fba0096de">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
@hailin0 Please assign to me
