### ISSUE TITLE
[Bug] [rest-api] rest-api 返回的jobId不对

### ISSUE THREAD

**Issue by wangwwwork** [apache/seatunnel#5241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

通过rest-api返回jobId的信息；返回的jobId最后几位进行了四舍五入；741112929666990081-》741112929666990100
![f3b0fd6b5b8a9958e5fe2d3cfd96525](https://github.com/apache/seatunnel/assets/18329914/a861d902-9b45-4a8c-95fa-c927a4fab728)
![abb9caeba37ddd8177d68fcbb97146f](https://github.com/apache/seatunnel/assets/18329914/9362abfe-7976-4089-bbcd-3bf26a9cd118)

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
集群执行
```

### Error Exception

```log
无
```

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Hi, Would you like to fix this?

**Comment by jackyyyyyssss** [comment]
i  will try  to fix  it

**Comment by chenliejun** [comment]
你好，请问你的这个问题解决了吗？我在2.3.5版本中调用/hazelcast/rest/maps/submit-job这个rest api 依然存此问题：返回的json结果中jsonId与实际控制台seatunnel.sh -l 命令查询到的jobId不一致，最后几位好像是被000和谐了（貌似不是四舍五入，而是相差一定数字，感觉是这个分布式jobId生成器存在类似自增错位的问题）
