### ISSUE TITLE
[Bug] [Zeta] Synchronize data from MySQL to Hive Chinese field garbled code

### ISSUE THREAD

**Issue by chuansenwang** [apache/seatunnel#5244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I deployed a seatunnel cluster using a container and attempted to synchronize data from the MySQL database to the Hive warehouse. However, I found that the Hive Chinese fields were garbled during the query

MySQL database query display
123	张三	10
124	李四	10

Hive database query display
123,??,10
124,??,10

The data I insert through commands on the console will not be garbled
INSERT INTO student VALUES (1234,"哈哈2",12);

Hive database query display
123,??,10
124,??,10
1234,"哈哈2",12

### SeaTunnel Version

seatunnel 2.3.2
mysql 5.7
hive 3.1.3
hadoop 3.3.5
jdk 1.8

### SeaTunnel Config

```conf
env {
  job.name = "test_mysql_source_to_hive"
  execution.parallelism = 1
  job.mode = "BATCH"
}
source{
    jdbc {
        url = "jdbc:mysql://mysql-master:3306/test?serverTimezone=GMT%2b8&characterEncoding=utf-8"
        #driver = "com.mysql.cj.jdbc.Driver"
        driver = "com.mysql.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "123456"
        query = "select id,name,age from student"
    }
}

transform {
    # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
    # please go to https://seatunnel.apache.org/docs/transform/sql
}

sink {
    Hive {
        table_name = "default.student"
        metastore_uri = "thrift://hive-metastore:9083"
  }
}
```

### Running Command

```shell
$SEATUNNEL_HOME/bin/seatunnel.sh --config $SEATUNNEL_HOME/config/MySQL2Hive.conf
```

### Error Exception

```log
无
```

### Java or Scala Version

jdk 1.8

### Screenshots

创建Hive语句
CREATE TABLE  IF NOT EXISTS student(
  id INT COMMENT 'ID',
  name STRING COMMENT '名字',
  age INT COMMENT '年龄'
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

MySQL 数据库语句：
CREATE TABLE `Student` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `age` int(2) DEFAULT NULL,
  `sex` tinyint(1) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Do you get garbled characters when you insert into xx in hive?

**Comment by chuansenwang** [comment]
> Do you get garbled characters when you insert into xx in hive?

thank you for your reply. when I insert into xxx in Hive, it won't garble.
and when I use Spark3 Engine  to execute the same task, it won't garble 
![image](https://github.com/apache/seatunnel/assets/125018730/d8bd7d03-1457-4413-8e96-75d2db8af7cd)

**Comment by zhilinli123** [comment]
I will try to fix it!

**Comment by zhilinli123** [comment]
Can you provide your hive ddl  @chuansenwang
