### ISSUE TITLE
[Feature][Doc] Add global search functionality to the official website documentation.

### ISSUE THREAD

**Issue by ic4y** [apache/seatunnel#5246]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Related links:

[SkyWalking Official Website](https://skywalking.apache.org/)
[Algolia for Developers](https://www.algolia.com/developers/?utm_medium=referral&utm_content=powered_by&utm_source=skywalking.apache.org&utm_campaign=docsearch)

![image](https://github.com/apache/seatunnel/assets/83933160/1d7b3930-650f-472b-b9a9-e53e028c5cb2)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ic4y** [comment]
@javalover123

**Comment by javalover123** [comment]
@ic4y

**Comment by javalover123** [comment]
@ic4y Update, <https://github.com/apache/seatunnel-website/pull/265>
