### ISSUE TITLE
[Feature][Connector Amazondynamodb] Add split to Amazondynamodb Connectors

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#5250]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support https://seatunnel.apache.org/docs/concept/connector-v2-features#parallelism
Refer to https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
@liugddx can you assign it to me , i will try it ;

**Comment by liugddx** [comment]
> @liugddx can you assign it to me , i will try it ;

Already assigned to you.
