### ISSUE TITLE
[Feature][Bin] Seatunnel bin file support windows.

### ISSUE THREAD

**Issue by FlechazoW** [apache/seatunnel#5258]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Our current script cannot be used on the Windows platform, and a .bat script needs to be provided.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyLoveFreedom** [comment]
mark

**Comment by susanbushisan** [comment]
I download seatunnel for my window pc , but I can't run SeaTunnel Application with git bash. It seems like start up script not support on windows. Is there a way to fix this?

**Comment by FlechazoW** [comment]
> 

How did you run? And what's the command you execute?

**Comment by FlechazoW** [comment]
> I download seatunnel for my window pc , but I can't run SeaTunnel Application with git bash. It seems like start up script not support on windows. Is there a way to fix this?

How did you run? And what's the command you execute?

**Comment by susanbushisan** [comment]
> > I download seatunnel for my window pc , but I can't run SeaTunnel Application with git bash. It seems like start up script not support on windows. Is there a way to fix this?
> 
> How did you run? And what's the command you execute?

first execute` ./bin/install-plugin.sh with git bash` ---- success
then execute` ./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local` ---- fail 

_错误: 找不到或无法加载主类 org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
原因: java.lang.ClassNotFoundException: org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient_
guess the diff java command 

then execute `java  -Dhazelcast.client.config=/d/soft/apache-seatunnel-2.3.3/config/hazelcast-client.yaml -Dseatunnel.config=/d/soft/apache-seatunnel-2.3.3/config/seatunnel.yaml -Dhazelcast.config=/d/soft/apache-seatunnel-2.3.3/config/hazelcast.yaml -Dlog4j2.configurationFile=/d/soft/apache-seatunnel-2.3.3/config/log4j2_client.properties -Dseatunnel.logs.path=/d/soft/apache-seatunnel-2.3.3/logs -Dseatunnel.logs.file_name=seatunnel-starter-client-1692955317755 -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -cp /d/soft/apache-seatunnel-2.3.3/lib/*;/d/soft/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient --config ./config/v2.batch.config.template -e local` ---- fail

_错误: 找不到或无法加载主类 D:.soft.apache-seatunnel-2.3.3.lib.seatunnel-transforms-v2.jar
原因: java.lang.ClassNotFoundException: D:.soft.apache-seatunnel-2.3.3.lib.seatunnel-transforms-v2.jar
bash: /d/soft/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar: cannot execute binary file: Exec format error_

can't run st

**Comment by FlechazoW** [comment]
> > > I download seatunnel for my window pc , but I can't run SeaTunnel Application with git bash. It seems like start up script not support on windows. Is there a way to fix this?
> > 
> > 
> > How did you run? And what's the command you execute?
> 
> first execute` ./bin/install-plugin.sh with git bash` ---- success then execute` ./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local` ---- fail
> 
> _错误: 找不到或无法加载主类 org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient 原因: java.lang.ClassNotFoundException: org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient_ guess the diff java command
> 
> then execute `java -Dhazelcast.client.config=/d/soft/apache-seatunnel-2.3.3/config/hazelcast-client.yaml -Dseatunnel.config=/d/soft/apache-seatunnel-2.3.3/config/seatunnel.yaml -Dhazelcast.config=/d/soft/apache-seatunnel-2.3.3/config/hazelcast.yaml -Dlog4j2.configurationFile=/d/soft/apache-seatunnel-2.3.3/config/log4j2_client.properties -Dseatunnel.logs.path=/d/soft/apache-seatunnel-2.3.3/logs -Dseatunnel.logs.file_name=seatunnel-starter-client-1692955317755 -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -cp /d/soft/apache-seatunnel-2.3.3/lib/*;/d/soft/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient --config ./config/v2.batch.config.template -e local` ---- fail
> 
> _错误: 找不到或无法加载主类 D:.soft.apache-seatunnel-2.3.3.lib.seatunnel-transforms-v2.jar 原因: java.lang.ClassNotFoundException: D:.soft.apache-seatunnel-2.3.3.lib.seatunnel-transforms-v2.jar bash: /d/soft/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar: cannot execute binary file: Exec format error_
> 
> can't run st

Ok, I got it. I'll replicate it locally.

**Comment by FlechazoW** [comment]
PR #5445  merged.
