### ISSUE TITLE
[Feature][Connector-V2] Influxdb support token auth

### ISSUE THREAD

**Issue by scorpig** [apache/seatunnel#5305]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Authenticate with the Token scheme](https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/#authenticate-with-the-token-scheme)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
@hailin0 hailin , could you assign it to me ? I will take it ;
