### ISSUE TITLE
[Bug] [plugins] Executing the install-plugin.sh script reports an error

### ISSUE THREAD

**Issue by xuqinghuang** [apache/seatunnel#5320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When executing the install-plugin.sh script, an exception was thrown and the exception kept printing.
Later I found out that this script must be run under seatunnel_home.
I think this script lacks the previous directory check, and this script should be executable in any directory, but now it can only be executed in the installation directory, which is not stated in the document.

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
apache-seatunnel-2.3.2/bin/install-plugin.sh
```

### Error Exception

```log
Install hadoop shade jar, usage version is 2.3.2
/srv/software/apache-seatunnel-2.3.2/mvnw: 223: cannot open /srv/software/.mvn/wrapper/maven-wrapper.properties: No such file
/srv/software/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Install SeaTunnel connectors plugins, usage version is 2.3.2
install connector :  connector-amazondynamodb
/srv/software/apache-seatunnel-2.3.2/mvnw: 223: cannot open /srv/software/.mvn/wrapper/maven-wrapper.properties: No such file
/srv/software/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
install connector :  connector-assert
/srv/software/apache-seatunnel-2.3.2/mvnw: 223: cannot open /srv/software/.mvn/wrapper/maven-wrapper.properties: No such file
/srv/software/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
install connector :  connector-cassandra
/srv/software/apache-seatunnel-2.3.2/mvnw: 223: cannot open /srv/software/.mvn/wrapper/maven-wrapper.properties: No such file
/srv/software/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
install connector :  connector-cdc-mysql
/srv/software/apache-seatunnel-2.3.2/mvnw: 223: cannot open /srv/software/.mvn/wrapper/maven-wrapper.properties: No such file
/srv/software/.mvn/wrapper/maven-wrapper.jar: No such file or directory
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/41868545/2d089674-7d23-443b-b4d2-3e25f1fa90b6)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by stillcoolme** [comment]
the log show that not found .mvn/wrapper/maven-wrapper.jar ，rather than dir problem，do you fix this problem？

**Comment by stillcoolme** [comment]
@xuqinghuang

**Comment by Wky15163053670** [comment]
这应该是maven的问题，可以参考一下这个 https://blog.csdn.net/blueheart20/article/details/51601441

**Comment by Wky15163053670** [comment]
这应该是maven的问题，可以参考一下这个 https://blog.csdn.net/blueheart20/article/details/51601441

**Comment by xuqinghuang** [comment]
抱歉，问题很早就找到原因了，但是忘记关闭了。
产生上面这个错误的原因是因为我在执行命令时并不是在 seatunnel_home 目录下执行 `install-plugin.sh` 导致的。
在 `install-plugin.sh` 脚本中会往上一层目录找到 `mvnw` 脚本，而 `mvnw` 脚本中会用 `pwd` 命令获取路径，然后在该路径下查找 `.mvn/wrapper/maven-wrapper.jar` 这个文件，此时就出现了上面的问题。
猜测这个`mvnw`应该是直接拷贝过来使用的，当时可能没考虑到这一点。理论上修改 `mvnw` 脚本中使用 `pwd` 获取目录的方式就可以解决这个问题，或者在入门文档中写清楚 `install-plugin.sh` 需要再 seatunnel_home 下执行也可以避免这个问题。
