### ISSUE TITLE
Seatunnel web submit a job to Seatunnel failed

### ISSUE THREAD

**Issue by redteaxixi** [apache/seatunnel#5327]
Hi,

Encountered a problem and hope to get help from here.

Installed both 2.3.3-SNAPSHOT seatunnel and seatunnel-web.

Test execute job to seatunnel server, it works fine.
However, submit a job from seatunnel-web, it failed with error on server log as following:
![seatunnel_issue](https://github.com/apache/seatunnel/assets/31273023/1ce49546-be99-4fb8-86b4-3cbe920fda42)

Also attached log file here.
[seatunnel-engine-server.log](https://github.com/apache/seatunnel/files/12366967/seatunnel-engine-server.log)

Thanks!

**Comment by coding-now** [comment]
concurrent.CompletionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource; local class incompatible: stream classdesc serialVersionUID = 2858267005650363299, local class serialVersionUID = -2572245715217596179

**Comment by coding-now** [comment]
test seatunnel-web submit job, got error:

 [qtp227080339-97] [AbstractLogger.info():69] - Start submit job, job id: 773814675245629441, with plugin jar [file:/app/apache-seatunnel-2.3.3/connectors/seatunnel/**_connector-cdc-mysql-2.3.3.jar_**]
11-06 15:43:15.972 ERROR [tr:,sp:] [qtp227080339-97] [GlobalExceptionHandler.logError():83] - com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource; local class incompatible: stream classdesc serialVersionUID = 2858267005650363299, local class serialVersionUID = -2572245715217596179

.....
![企业微信截图_1699257697737](https://github.com/apache/seatunnel/assets/26567069/39ced69f-7487-4fdf-a5e0-dc7fa490893e)


**Add serialVersionUID in class IncrementalSource and its child class?**
