### ISSUE TITLE
[Bug] [Mysql] Failed to synchronize tiny type of data

### ISSUE THREAD

**Issue by junmingliu** [apache/seatunnel#5330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Mysql2Pg，Failed to synchronize tiny type of data，tiny type would be transformed to boolean。
![image](https://github.com/apache/seatunnel/assets/15081645/e81651ad-beca-4054-91f9-134e6f390d8a)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
mysql2pg
```

### Running Command

```shell
engine模式
```

### Error Exception

```log
Caused by: org.postgresql.util.PSQLException: ERROR: column "status" is of type smallint but expression is of type boolean
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by junmingliu** [comment]
It can be assigned to me and I can try to fix it。

**Comment by CheneyYin** [comment]
https://github.com/apache/seatunnel/blob/c109385bb5138c20d78664fbc63ff86c8404b895/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/catalog/mysql/MysqlDataTypeConvertor.java#L107-L117
Reuse or keep consistent

**Comment by CheneyYin** [comment]
> It can be assigned to me and I can try to fix it。

Have you resolved this issue?
The MySQL Tiny Int cast is noisy and inappropriate, but I don't think it's causing the problem.  According [debezium mysql connector datatype mapping](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-basic-types), MySQL Tiny Int will be mapped to INT16 (2 bytes). So `column.length() == 2` and MySQL Tiny Int will be converted to `BasicTypes.INT_TYPE`.
