### ISSUE TITLE
[Bug] [Module Name] Bug title No suitable dialect factory found

### ISSUE THREAD

**Issue by luckyfruit96** [apache/seatunnel#5345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I've seen a similar issue, but switching from version 2.3.1 to 2.3.2 resolved it. However, I'm already using version 2.3.2. The JDBC connection is to China Star's Inceptor database.

### SeaTunnel Version

seatunnel-2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}
source{
    Jdbc {
        url="jdbc:hive2://128.6.1.55:10000/test;guardianToken=KlplPYY9aRo4QT6oCbPo-DSJXCCS"
        driver="io.transwarp.jdbc.InceptorDriver"
        connection_check_timeout_sec=100
        user="sjzt"
        password="sjzt"
        query="select * from adp_dwd_test.t_comm_scr_var_corr_test"
    }
}
sink {
  Console {
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config workjson/testinceptor.josn -e local
```

### Error Exception

```log
org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:hive2://128.6.1.55:10000/test;guardianToken=KlplPYY9aRo4QT6oCbPo-DSJXCCS' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.
```

### Screenshots

![1692602778406](https://github.com/apache/seatunnel/assets/132887586/b9a6afe8-1b5e-4b70-b77b-04de81536261)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Have you put the driver in the specified directory?

**Comment by luckyfruit96** [comment]
> Have you put the driver in the specified directory?

Hello, I have placed the driver package in the 'lib' directory. I have used the driver in the program and it can establish a connection.

**Comment by liunaijie** [comment]
which is the similar issue? i check the code, looks now we don't support  `China Star's Inceptor` database. 
at least `jdbc:hive2` this url pattern is not supported.

**Comment by luckyfruit96** [comment]
> which is the similar issue? i check the code, looks now we don't support `China Star's Inceptor` database. at least `jdbc:hive2` this url pattern is not supported.

inceptor is a commercial database that is based on Hive. Does that mean it doesn't support Hive2 JDBC connections?

**Comment by liunaijie** [comment]
> > which is the similar issue? i check the code, looks now we don't support `China Star's Inceptor` database. at least `jdbc:hive2` this url pattern is not supported.
> 
> inceptor is a commercial database that is based on Hive. Does that mean it doesn't support Hive2 JDBC connections?

yes
