### ISSUE TITLE
[Feature][CDC] Improve snapshot read performance

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5349]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When closing ExactlyOnce, the memory buffer can be canceled and read data should be sent to the sink immediately.

reference
https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-cdc/connector-cdc-base/src/main/java/org/apache/seatunnel/connectors/cdc/base/source/reader/external/IncrementalSourceScanFetcher.java#L123

https://github.com/apache/seatunnel/blob/dev/seatunnel-connectors-v2/connector-cdc/connector-cdc-mysql/src/main/java/org/apache/seatunnel/connectors/seatunnel/cdc/mysql/source/reader/fetch/scan/MySqlSnapshotSplitReadTask.java#L235

<img width="1446" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/6ab46110-1f82-4a01-b4ad-8ad10be06f7f">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
If there have been no new developments, I can try to complete it.
