### ISSUE TITLE
[Bug] [SqlServer-CDC 2 MYSQL JDBC CDC] SqlServer-CDC 2 MYSQL JDBC CDC not worked

### ISSUE THREAD

**Issue by 2gamayibuxulong** [apache/seatunnel#5377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use SQL SERVER CDC to sync SQL SERVER records to mysql,but not worked

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
}

source {
  SqlServer-CDC {
    username = "**"
    password = "***"
    database-names = ["a"]
    table-names = ["a.dbo.b"]
    base-url="jdbc:sqlserver://127.0.0.1:1443;DatabaseName=a"
  }
}

transform {
  FieldMapper {
    field_mapper = {
        id = id
        lastname = lastname
    }
  }
}


sink {
    jdbc {
        url = "jdbc:mysql://localhost:3306/demo"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "root"
        generate_sink_sql = true
        # You need to configure both database and table
        database = demo
        table = di_test
        primary_keys = ["id"]
    }
}
```

### Running Command

```shell
I use org.apache.seatunnel.example.engine.SeaTunnelEngineExample main method to run my conf。
```

### Error Exception

```log
i changed my data in sqlserver,but mysql data not changed
```

### Java or Scala Version

java version jdk-11.0.15

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
you can using `console` as sink test sqlserver cdc reading records

```
sink {
    console {}
}
```

**Comment by hailin0** [comment]
and confirm whether you enable sqlserver-cdc

reference
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e/src/test/resources/ddl/column_type_test.sql#L24
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e/src/test/resources/ddl/column_type_test.sql#L71
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e/src/test/resources/sqlservercdc_to_console.conf

**Comment by 2gamayibuxulong** [comment]
Thanks Reply,I referred to the reference document you provided，My focus is my sink compent is mysql cdc write,your reference is sqlserver-cdc to sqlserver jdbc write。In addition, since the first full synchronization was successful after startup, after the corresponding table record in the SqlServer database was modified, the corresponding record in the mysql database was not modified. This is my main confusion。

**Comment by 2gamayibuxulong** [comment]
I debug the org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter#write method，and no more SeaTunnelRow element consume from the Context since I changed my record in sqlserver.

**Comment by 2gamayibuxulong** [comment]
I also test the  the reference document you provided, The same situation。No CDC effect

**Comment by 2gamayibuxulong** [comment]
I also use check my table is is_tracked_by_cdc = 1

```code
SELECT s.name AS Schema_Name, tb.name AS Table_Name
, tb.object_id, tb.type, tb.type_desc, tb.is_tracked_by_cdc
FROM sys.tables tb
INNER JOIN sys.schemas s on s.schema_id = tb.schema_id
WHERE tb.is_tracked_by_cdc = 1
```

**Comment by 2gamayibuxulong** [comment]
sorry,I originally thought my SQL server Agent was running, but the true is not running,so CDC not work out。Thanks Reply again。
