### ISSUE TITLE
[Bug] [install-plugin.sh] Install connectors plugin failed

### ISSUE THREAD

**Issue by kgpty** [apache/seatunnel#5380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When i Install the connectors plugins (on Windows wsl, ubuntu2004), the 'install-plugin.sh' report this:
`Install SeaTunnel connectors plugins, usage version is 2.3.3
./bin/install-plugin.sh: 54: Bad substitution`

I have checked the './connectors/seatunnel', No connector-jdbc intalled. What shoul i do ?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
`--connectors-v2--
connector-fake
connector-console
connector-jdbc
--end--`
```

### Running Command

```shell
sh ./bin/install-plugin.sh 2.3.3
```

### Error Exception

```log
Install hadoop shade jar, usage version is 2.3.3
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:get (default-cli) @ standalone-pom ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] Resolving org.apache.seatunnel:seatunnel-hadoop3-3.1.4-uber:jar:optional:2.3.3 with transitive dependencies
[WARNING] destination/dest parameter is deprecated: it will disappear in future version.
[INFO] Copying /home/pty/.m2/repository/org/apache/seatunnel/seatunnel-hadoop3-3.1.4-uber/2.3.3/seatunnel-hadoop3-3.1.4-uber-2.3.3-optional.jar to /home/pty/libs/apache-seatunnel-2.3.3/lib
[WARNING] Notice transitive dependencies won't be copied.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.866 s
[INFO] Finished at: 2023-08-25T16:47:50+08:00
[INFO] ------------------------------------------------------------------------
Install SeaTunnel connectors plugins, usage version is 2.3.3
./bin/install-plugin.sh: 54: Bad substitution
```

### Java or Scala Version

Open JDK 11

### Screenshots

![image](https://github.com/apache/seatunnel/assets/140572206/707c014b-8f7c-4b65-a418-a75dbe52c706)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
FYR
https://stackoverflow.com/questions/20615217/bash-bad-substitution
