### ISSUE TITLE
[Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by BoomLee1024** [apache/seatunnel#5381]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

数据同步 hive 的时候，需要指定hdfs-site.xml 文件，这样可以获得 namenode 高可用的地址。这块可不可以直接写入到配置文件中呢，这样集群的hdfs-site.xml 如果发生变化，我就可以不用关心。我只需要在代码中生成配置文件里指定就可以了，这样增加了灵活性。

### Usage Scenario

1.例如配置文件添加以下配置
"hadoopConfig": {
							"dfs.ha.namenodes.nameservice1": "namenode50,namenode138",
							"dfs.namenode.rpc-address.nameservice1.namenode138": "IP1:8020",
							"dfs.namenode.rpc-address.nameservice1.namenode50": "IP2:8020",
							"dfs.nameservices": "nameservice1",
							"dfs.client.failover.proxy.provider.nameservice1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
						}

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Please maintain the title of the issue well.
Regarding the problem, we generally maintain access information in `hdfs-site.xml`, which is very cumbersome to maintain in the job config.

**Comment by hailin0** [comment]
> Please maintain the title of the issue well. Regarding the problem, we generally maintain access information in `hdfs-site.xml`, which is very cumbersome to maintain in the job config.

+1

**Comment by hailin0** [comment]
Please maintain the title of the issue well.
