### ISSUE TITLE
[Bug] [Connector-v2] missing OssJindoFile connector release in 2.3.3

### ISSUE THREAD

**Issue by foggiest** [apache/seatunnel#5383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Could not download  org.apache.seatunnel:connector-file-oss-jindo:jar:2.3.3 during plugin install .
Could not find corresponding version artifact on maven ,the latest release is 2.3.2

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
all default
```

### Running Command

```shell
./bin/install-plugin.sh
```

### Error Exception

```log
ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Missing:
[ERROR] ----------
[ERROR] 1) org.apache.seatunnel:connector-file-oss-jindo:jar:2.3.3
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=org.apache.seatunnel -DartifactId=connector-file-oss-jindo -Dversion=2.3.3 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=org.apache.seatunnel -DartifactId=connector-file-oss-jindo -Dversion=2.3.3 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]         1) org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
[ERROR]         2) org.apache.seatunnel:connector-file-oss-jindo:jar:2.3.3
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   aliyun (https://maven.aliyun.com/repository/public, releases=true, snapshots=false)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/35755923/c315b419-8a95-4206-a8e1-7141a7cdfd8b)

![image](https://github.com/apache/seatunnel/assets/35755923/3a044817-0c88-4be8-b6b5-6436e332753c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
after 2.3.3. pls change the connector name from 'connector-file-oss-jindo' to 'connector-file-jindo-oss'

**Comment by foggiest** [comment]
@liunaijie Where to change this connector name ? connectors/plugin-mapping.properties or config/plugin_config or other config file ?

**Comment by liunaijie** [comment]
@foggiest change in `config/plugin_config`. change the connector name to `connector-file-jindo-oss`

**Comment by foggiest** [comment]
@liunaijie many thanks~, successfully installed all plugin after changing~
