### ISSUE TITLE
[Feature][Hive JDBC Source] Support Hive JDBC Source Connector

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5389]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have `Hive` Source Connector now, but it can not support `where` condition.
Therefore, in order to support reading based on `where` conditions, it is necessary to support the `Hive JDBC connector`, which uses the hive jdbc driver to connect to the `hiveserver2` service through jdbc to read data.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NickCodeJourney** [comment]
Please assign it to me
