### ISSUE TITLE
I want to enter the channel to understand the problem, how to join?

### ISSUE THREAD

**Issue by itc7** [apache/seatunnel#5391]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I'm having trouble deploying with quick-start-seatunnel-engine,

2023-08-28 20:51:40,213 WARN  com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask - [localhost]:5801 [seatunnel-410521] [5.1] Received auth from Connection[id=1990, /127.0.0.1:5801->/127.0.0.1:54331, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid dee352c4-d8e0-4fc8-bfeb-4206ee08e216 and clientName hz.client_1, authentication failed

I don't know how to do it, I want to ask for help

### Usage Scenario

MYSQL-CDC -> S3-REDSHIFT

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by itc7** [comment]
apache-seatunnel-2.3.3

**Comment by itc7** [comment]
```
env {
  execution.parallelism = 5
  job.mode = "STREAMING"
}

source {
  MySQL-CDC {
    result_table_name = "*****r_info"
    username = "admin"
    password = "******"
    table-names = ["c*****y.*****r_info"]
    base-url = "jdbc:mysql://b**************rcq.sa-east-1.rds.amazonaws.com:3306/ca*****?useUnicode=true&characterEncoding=utf8&useSSL=false"
    server-time-zone = "America/Araguaina"
  }
}

sink {
  S3Redshift {
    jdbc_url = "redshift-cluster-2.cgwg*******mp.sa-east-1.redshift.amazonaws.com:5439/ca*****2"
    jdbc_user = "awsuser"
    jdbc_password = ""******""
    execute_sql="COPY *****r_info FROM 's3://test${path}' IAM_ROLE 'arn:aws:iam::73*******82:role/RedshiftAllCommandsFullAccessRule' REGION 'sa-east-1' removequotes emptyasnull blanksasnull maxerror 100 delimiter '|' ;"
    access_key = ""
    secret_key = ""
    bucket = "s3a://seatunnel-ca*****"
    tmp_path = "/tmp/seatunnel"
    path="/seatunnel/text"
    row_delimiter="\n"
    partition_dir_expression="${k0}=${v0}"
    is_partition_field_write_in_file=true
    file_name_expression="${transactionId}_${now}"
    file_format_type = "text"
    filename_time_format="yyyy.MM.dd"
    is_enable_transaction=true
    fs.s3a.endpoint="s3.sa-east-1.amazonaws.com"
    fs.s3a.aws.credentials.provider = "arn:aws:iam::73*******82:role/RedshiftAllCommandsFullAccessRule"
  }
}
```

Here is my config file

`./bin/seatunnel.sh --config ./config/ca*****_order.template -e local`


Here is my start command

**Comment by liunaijie** [comment]
pls share your wechat id, i can invite you to the wechat user group.
and can you share you deploy step then i can repeat your issue

**Comment by itc7** [comment]
> pls share your wechat id, i can invite you to the wechat user group. and can you share you deploy step then i can repeat your issue

my wechat id is: fpj2580

I follow this tutorial to deploy, the steps are relatively simple.
https://seatunnel.apache.org/zh-CN/docs/2.3.0/start-v2/locally/deployment

**Comment by itc7** [comment]
I have received an invitation and can close

**Comment by yangyiforward** [comment]
> I have received an invitation and can close

how did you resolve the problem ? i get the same error @itc7 thx
