### ISSUE TITLE
[OnlineMeeting&Aug.29] SeaTunnel community meeting Topic collect

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#5393]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Jia Fan invites you to join a Tencent Meeting.
Meeting Topic: SeaTunnel Community Meeting
Meeting Time: 2023/08/29 20:00-22:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join, or add to the meeting list:
https://meeting.tencent.com/dm/LzTBEgpPoMaI

#Tencent Meeting: 728-287-533

Copy this information and open the Tencent Meeting app on your phone to participate.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chl-wxp** [comment]
[STIP2-The Sink terminal implements SaveMode functions (including SchemaSaveMode and DataSaveMode)](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=263427916)

**Comment by zhilinli123** [comment]
### Connector doc  sync
 **Complete Connector document:**

- [x]  S3File
- [x]  MyHours
- [x]  StarRocks
- [x]  SelectDB-Cloud
- [x]  HdfsFile
- [x]  Feishu
- [x]  IoTDB
- [x]  Oracle
- [x]  Iceberg
- [x]  Http
- [x]  Slack

 **Open Connector document:**

- [ ]  RocketMq:https://github.com/apache/seatunnel/pull/5361
- [ ]  Socket:https://github.com/apache/seatunnel/pull/5287
- [ ]  Console:https://github.com/apache/seatunnel/pull/5230
- [ ]  SftpFile:https://github.com/apache/seatunnel/pull/5386

**Thanks to all contributors for their contributions to the Connector documentation**

**Comment by gitfortian** [comment]
1、任务因为下游数据库的问题失败了  然后我直接 -r不能恢复吗  现在是只支持-s触发savepoint之后才能-r启动吗 
2、rest api 能否获取历史的所有任务（没被清理掉的）
3、rest api cancel任务

**Comment by Hisoka-X** [comment]
https://github.com/apache/seatunnel/issues/5395

**Comment by HaoXuAI** [comment]
https://github.com/apache/seatunnel/pull/5367
