### ISSUE TITLE
[Bug] [Module Name] docs/en/connector-v2/sink/FtpFile.md EERRORERRORRROR

### ISSUE THREAD

**Issue by AdkinsHan** [apache/seatunnel#5397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

username [string]
The target ftp username is required

password [string]

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
FtpFile {
    host = "dxxx"
    port = 21
    user = "xxx"
    password = "xxxx"
    path = "/devlop/csv"
    file_format_type = "csv"
}
```

### Running Command

```shell
sh ./bin/start-seatunnel-spark-3-connector-v2.sh --master local[3] --deplot-mode client -i ghy_host=datalake16.ghy.com.cn --config ./config/08-hive2csv.config
```

### Error Exception

```log
user cant be empty document says username but config use user
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/102467301/3659f099-b7a9-4910-b3db-ab509dd313db)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
I do not really understand what you mean?

**Comment by AdkinsHan** [comment]
Just the markdown document error the sample is not same with the code
