### ISSUE TITLE
[Bug] [Docs] IoTDB Source example error

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source example error

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
source example error
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/14371345/3f6279bb-daae-47e6-83d0-c0dca1eb9da6)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
i will fix this issue
