### ISSUE TITLE
[scheduled task][scheduled task] Added the scheduled task scheduling function

### ISSUE THREAD

**Issue by zck573693104** [apache/seatunnel#5406]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The offline task scheduling function is added

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Can you describe the requirements in detail?

**Comment by zck573693104** [comment]
> Can you describe the requirements in detail?
------English-------
Because it is offline synchronization, it is scheduled at a certain time, but some tasks have dependencies when scheduling, such as job1 ok and continue to perform job2 and so on, and hope that ST provides a function that supports the configuration of task dependencies and timing scheduling. Or can we come out with a timing scheduling function first? For example, the cron configuration allows tasks to be pulled up automatically
----Chinese------
因为是离线同步，都是某个时间进行调度的，但是调度时候有的任务还有依赖性，比如job1 ok 又继续执行job2等等，希望ST出一个支持配置任务依赖关系以及定时调度的功能。或者可以先出一个定时调度功能嘛？比如通过cron配置让任务自动拉起

**Comment by liugddx** [comment]
> 

ST web seems to have scheduling capabilities.You can try it after the web is released.

**Comment by zck573693104** [comment]
use  ST web
