### ISSUE TITLE
[Bug] [seatunnel-web] Tasks -> Source Name Null

### ISSUE THREAD

**Issue by zhangheng3** [apache/seatunnel#5423]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

On seatunnel-web UI , Datasource is  configured hive-metastore and mysql jdbc , but Source Name Option is Null at Tasks, Dropdown menu is empty
![image](https://github.com/apache/seatunnel/assets/25759822/d92b4c29-5e45-44c0-a2d5-b017a5f18b2d)
![image](https://github.com/apache/seatunnel/assets/25759822/c5a2a93d-863c-4d02-8f81-42f22963fe85)

### SeaTunnel Version

apache-seatunnel-web-1.0.0-SNAPSHOT

### SeaTunnel Config

```conf
server:
  port: 8801

spring:
  application:
    name: seatunnel
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seatunnel?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: xxxxxxxx
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  expireTime: 86400
  secretKey: https://github.com/apache/seatunnel
  algorithm: HS256

---
spring:
  config:
    activate:
      on-profile: h2
  sql:
    init:
      schema-locations: classpath*:script/seatunnel_server_h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:seatunnel;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
```

### Running Command

```shell
sh bin/seatunnel-backend-daemon.sh start
```

### Error Exception

```log
2023-09-04 19:49:47.399 seatunnel sgal-comm-data WARN [qtp1415812333-57] [SeatunnelPermissionServiceImpl.funcPermissionCheck():38] - func permission check in seatunnel
2023-09-04 19:49:47.400 seatunnel sgal-comm-data WARN [qtp1415812333-57] [SeatunnelPermissionServiceImpl.availableResourceRange():57] - query available resource range in seatunnel
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zatomsmasher** [comment]
I encountered the same problem yesterday,and there are two things worth noting:
1. Set $SEATUNNEL_HOME to environment variable. By default, the web server will load connector plugins from the $SEATUNNEL_HOME/connectors/seatunnel path when it starts.
2. Check conf/connector-datasource-mapper.yaml. The display of your datasources is constrained by the configuration in this file.

**Comment by zhangheng3** [comment]
> I encountered the same problem yesterday,and there are two things worth noting:
> 
> 1. Set $SEATUNNEL_HOME to environment variable. By default, the web server will load connector plugins from the $SEATUNNEL_HOME/connectors/seatunnel path when it starts.
> 2. Check conf/connector-datasource-mapper.yaml. The display of your datasources is constrained by the configuration in this file.

Thanks for your reply, But I have already set SEATUNNEL_HOME An error occurred: 

Caused by: java.lang.NoSuchMethodError: org.apache.seatunnel.api.configuration.Options$SingleChoiceOptionBuilder.defaultValue(Ljava/lang/Object;)Lorg/apache/seatunnel/api/configuration/Option;
	at org.apache.seatunnel.connectors.seatunnel.file.config.BaseSinkConfig.<clinit>(BaseSinkConfig.java:54)
	at org.apache.seatunnel.connectors.seatunnel.file.oss.sink.OssFileSinkFactory.optionRule(OssFileSinkFactory.java:44)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.sinkFullOptionRule(FactoryUtil.java:282)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.lambda$getAllPlugin$5(AbstractPluginDiscovery.java:273)

**Comment by zhangheng3** [comment]
> I encountered the same problem yesterday,and there are two things worth noting:
> 
> 1. Set $SEATUNNEL_HOME to environment variable. By default, the web server will load connector plugins from the $SEATUNNEL_HOME/connectors/seatunnel path when it starts.
> 2. Check conf/connector-datasource-mapper.yaml. The display of your datasources is constrained by the configuration in this file.

Thank's for your reply,It seems that there are still some issues with this platform ,  I'll use dolphinscheduler to schedule  seatunnel first.

**Comment by LiRed7** [comment]
Is it finally resolved? What is the solution? Please tell me.

**Comment by czxin788** [comment]
![image](https://github.com/apache/seatunnel/assets/13861904/43af74ae-f7ad-4119-ab72-7d3d9f6d3766)

I have the same issue.

deploy seatunnel web  is very difficulty

**Comment by channingwen** [comment]
deploy seatunnel web is so difficulty，how to solve this problem？

env and jar lib
export SEATUNNEL_HOME=/home/apache-seatunnel-2.3.5
export SeaTunnel_HOME=$SEATUNNEL_HOME
export SEATUNNEL_WEB_HOME=/home/apache-seatunnel-web-1.0.0-bin
export ST_WEB_BASEDIR_PATH=/home/apache-seatunnel-web-1.0.0-bin
export PATH=$PATH:$SEATUNNEL_HOME/bin:$SEATUNNEL_WEB_HOME/bin

![image](https://github.com/apache/seatunnel/assets/27676001/059113d3-56a8-47c1-af79-2ed999b543f3)

warn log：
[SeatunnelPermissionServiceImpl.funcPermissionCheck():38] - func permission check in seatunnel

**Comment by emmanuelsosa** [comment]
Same issue.. No datasources listed

**Comment by WZH-hub** [comment]
Same issue.. No datasources listed
