### ISSUE TITLE
[Feature][File Connector] Supports writing column names when the output type is file (CSV)

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5443]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We do not support adding column names to the first line when using File type Sink to generate files. If this feature is supported, the generated CSV file will be easier to read.

Here are some references:

In  `TextWriteStrategy.getOrCreateOutputStream` method the write will create a new file when can not get outputstream from `beingWrittenOutputStream`. I think it is more appropriate to obtain column names from `SeaTunnelRowType` and write them after creating a new file output stream.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zck573693104** [comment]
PLT

**Comment by zhengchar** [comment]
How can I follow this issue？

**Comment by EricJoy2048** [comment]
> PLT

Has been assigned to you

**Comment by EricJoy2048** [comment]
> 

If you are interested in a certain issue, you can reply below the issue to express your desire to claim the task. 
Some examples: `Please assign it to me.`, `I want to do it.`
