### ISSUE TITLE
[Feature][FileConnector] Unify some option in file source/sink connector

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#5461]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have some option that is different in the file family connector.

For example, in the FtpFile connector sink, we support compress_codec, but we don't set compress_codec in the source, this might be strange.

And further more, in localfile/ftpfile/hdfsfile, there also exist some option that is different, e.g. some support row_delimiter, some don't support.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
#5083 this pr will support compress_codec in the FileReader

**Comment by EricJoy2048** [comment]
Thanks for your contribution. 
Can you fix `And further more, in localfile/ftpfile/hdfsfile, there also exist some option that is different, e.g. some support row_delimiter, some don't support.` ?

**Comment by liunaijie** [comment]
> Thanks for your contribution. Can you fix `And further more, in localfile/ftpfile/hdfsfile, there also exist some option that is different, e.g. some support row_delimiter, some don't support.` ?

ok, i will do this.

**Comment by liunaijie** [comment]
make it active
