### ISSUE TITLE
[Feature][CDC] Support MongoDB  CDC running on flink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5465]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Adapt to MongoDB running on flink

reference
https://github.com/apache/seatunnel/pull/4918

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
Please assign it to me. Thank you
