### ISSUE TITLE
[Bug] [S3File Connector] Sync excel file data from S3File to Mysql got wrong data

### ISSUE THREAD

**Issue by redteaxixi** [apache/seatunnel#5470]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Case: Sync excel file data from S3File to Mysql
Issue: Incorrect sink data: excel file contains 8 lines of different data, but once the data sync into Mysql, all 8 lines of data are the last line of the file.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
}

source {
  S3File {
    path = "/xlsx/20230907/test_seatunnel.xlsx"
    bucket = "s3a://xxx"
    fs.s3a.endpoint="xxxx"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    file_format_type = "excel"
    access_key = "xxx"
    secret_key = "xxxxx"
    schema {
        fields {
            KCode = string
            Title = string
            Author = string
            Version = string
            SecurityLevel = string
        }
    }
  }
}

sink {
  Jdbc {
    url = "jdbc:mysql://xxx:3306/mei_etl?rewriteBatchedStatements=true&serverTimezone=GMT%2B8"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "xxx"
    password = "xxx"
    database = "xxx"
    table = "test_excel"
    generate_sink_sql=true
  }
}
~
```

### Running Command

```shell
sh bin/seatunnel.sh -c s3excel.conf
```

### Error Exception

```log
No error exception.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
Because I don't have an S3 data source, I can't replicate it. I need some help from you.
(1) The version of seatunnel
(2) Does the CSV file of s3 have this issue
(3) Download this file, write it to MySQL through localfile, and compare it.

**Comment by redteaxixi** [comment]
@laglangyue ,
1) version of seatunnel is 2.3.3
2) CSV works well, but excel has the issue
3) Just give it a try and local excel encountered the same problem.

**Comment by redteaxixi** [comment]
@laglangyue , if you need, I will upload the excel file here.

**Comment by laglangyue** [comment]
> ```shell
> sh bin/seatunnel.sh -c s3excel.conf
> ```

From your description, it seems that it is not a problem with S3, but with Excel. Therefore, the local file should also be able to reproduce this problem. If it can be replicated, please provide it to me. It cannot be reproduced and it is useless to provide it to me because I do not have an S3 data source

**Comment by redteaxixi** [comment]
@laglangyue 

Please take a look at the conf and let me know if anything should be changed, thanks.

env {
  job.mode = "BATCH"
}

source {
  LocalFile {
    path = "/mei/seatunnel/seatunnel-2.3.3/apache-seatunnel-2.3.3/test_seatunnel.xlsx"
    file_format_type = "excel"
    schema {
        fields {
            KCode = string
            Title = string
            Author = string
            Version = string
            SecurityLevel = string
        }
    }
  }
}

sink {
  Jdbc {
    url = "jdbc:mysql://172.70.10.231:3306/mei_etl?rewriteBatchedStatements=true&serverTimezone=GMT%2B8"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "xxx"
    password = "xxxx"
    database = "testdb"
    table = "test_excel"
    generate_sink_sql=true
  }
}

**Comment by redteaxixi** [comment]
[test_seatunnel.xlsx](https://github.com/apache/seatunnel/files/12592755/test_seatunnel.xlsx)

**Comment by redteaxixi** [comment]
This is the data in mysql.
![image](https://github.com/apache/seatunnel/assets/31273023/3efc99b6-622f-4c96-8882-8c23f8d1b2f8)

**Comment by laglangyue** [comment]
I tested the Spark engine locally and did not find any such issues

**Comment by redteaxixi** [comment]
@laglangyue ,hi, I found the problem with Zeta engine, can you please test it with Zeta?
