### ISSUE TITLE
[Discuss] Dockerfile

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#5475]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now we don't have the docker image, And seatunnel has a lots of connectors, most time user don't need all connector.

So I think we can have a base docker image (or only have fake and console connector). and give an example Dockerfile to download the needed connector.

### Usage Scenario

# Basic image Dockerfile
```
FROM eclipse-temurin:8-jre

RUN apt update ; \
    apt install -y wget ;

ARG version=2.3.2
ARG SEATUNNEL_HOME=/opt/seatunnel

# there I download from maven repo. It can be changed to copy from locally if we want build when release

RUN wget "https://archive.apache.org/dist/seatunnel/${version}/apache-seatunnel-${version}-bin.tar.gz" -P $SEATUNNEL_HOME && \
    cd $SEATUNNEL_HOME && \
    tar -zxvf apache-seatunnel-${version}-bin.tar.gz



```

# Example Re-Build Dockefile
```
FROM seatunnel-base-image

COPY bin/docker_install_plugin.sh /opt/seatunnel/install_plugin.sh
RUN chmod 777 /opt/seatunnel/install_plugin.sh && \
    ./opt/seatunnel/install_plugin.sh
```

### The connector install script:
```
#!/bin/bash

plugins=("connector-fake" "connector-console")
for item in "${plugins[@]}"; do
    wget https://repo1.maven.org/maven2/org/apache/seatunnel/${item}/${version}/${item}-${version}.jar -P /opt/seatunnel/connectors/seatunel
done

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Sounds good, The basic image of Zeta will only contain the Zeta engine, and we can run the install script when building images.

But why we don't directly provide an image containing the whole connectors? since the image will be very big?

**Comment by liunaijie** [comment]
> Sounds good, The basic image of Zeta will only contain the Zeta engine, and we can run the install script when building images.
> 
> But why we don't directly provide an image containing the whole connectors? since the image will be very big?

Yeah, if we include all connectors the image will be very big, and I think in most cases people don't need the whole connectors.

**Comment by ruanwenjun** [comment]
> > Sounds good, The basic image of Zeta will only contain the Zeta engine, and we can run the install script when building images.
> > But why we don't directly provide an image containing the whole connectors? since the image will be very big?
> 
> Yeah, if we include all connectors the image will be very big, and I think in most cases people don't need the whole connectors.

Got it.
