### ISSUE TITLE
[Discuss][Http] http supports page increase？

### ISSUE THREAD

**Issue by xiaofan2022** [apache/seatunnel#5477]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Some interfaces need to turn the page to see if the data needs to be supported, for example, the user provides page number fields, and validation criteria. Can realize the loop query until the query is complete

### Usage Scenario

Some interfaces need to turn pages to query data

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This feature looks good to me. This might be useful if some endpoint can only support page queries.

Are you interested in submitting PR to support this?

**Comment by xiaofan2022** [comment]
I plan to do this so that the user can specify the page field name and stop condition (jsonpath validation), and then increment the page field in turn until the stop condition is met. I don't know if there's a better idea

**Comment by ruanwenjun** [comment]
> I plan to do this so that the user can specify the page field name and stop condition (jsonpath validation), and then increment the page field in turn until the stop condition is met. I don't know if there's a better idea

Yes, we can add step for each fetch, this might make the HTTP config complex, could you provide a detail design for this.

**Comment by xiaofan2022** [comment]
Okay, this is a very interesting thing, so let me look at the code

**Comment by hailin0** [comment]
@xiaofan2022 

Reference materials

https://github.com/apache/seatunnel/issues/3415
https://github.com/apache/seatunnel/pull/4372

**Comment by xiaofan2022** [comment]
Whether it is necessary to add new components, I think currently, such as gitlab and github connector are based on http-base to add retry configuration, if I change this retry logic to http-base, then other component code will be redundant. Moreover, if the page search is early, it may also be designed to encrypt the request parameters
