### ISSUE TITLE
[Bug] [Config] jvm_options config file format is dos

### ISSUE THREAD

**Issue by Zhouwen-CN** [apache/seatunnel#5481]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I'm not sure if this is a bug
![image](https://github.com/apache/seatunnel/assets/77488507/77204e98-0a21-44a5-8ac7-a35e2c290249)

When starting a local job , it will read the jvm_client_options file splicing jvm parameters
Starting the seatunnel cluster, will be read jvm_options file
![image](https://github.com/apache/seatunnel/assets/77488507/47ec2611-f29b-47f0-ad18-5e028ec8cf63)

jvm_options file fileformat is DOS, which will cause the judgment of empty lines to fail
![image](https://github.com/apache/seatunnel/assets/77488507/a4773351-d709-4464-a443-ce7f77abc822)

When I debugged the script, I discovered this
![image](https://github.com/apache/seatunnel/assets/77488507/441c6f45-6220-4c9a-8eaa-c41cc9493e51)

**When I put the jvm_options config file format is modified to unix, it can run**
![image](https://github.com/apache/seatunnel/assets/77488507/913a6859-0a07-4f56-9368-92db70956a4e)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
{}
```

### Running Command

```shell
./bin/seatunnel.sh
```

### Error Exception

```log
No exception
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
When I open this file on my mac, I  cannot find the '\r', this might be added by your system.

**Comment by Zhouwen-CN** [comment]
ok,  thanks, It may be a problem with `Windows`
