### ISSUE TITLE
debezium upgrade 

### ISSUE THREAD

**Issue by liutaobigdata** [apache/seatunnel#5491]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When does the community plan to upgrade the debezium version?

### Usage Scenario

The debezium in flink-cdc has been upgraded to 1.9.7. The flink cdc community describes this version as a performance improvement. Seatunnel can imitate flink cdc to upgrade the debezium version.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Yes, upgrade debezium is needed, we need to dive into , and do some test.
