### ISSUE TITLE
UT failed due to download `jindo-core` dependency

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#5496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I found recently most ci failed due to below problem, is there any good idea to solve this? If this is only caused by network problem can we change the repo.

<img width="1521" alt="image" src="https://github.com/apache/seatunnel/assets/22415594/f04f5f8a-b0c1-4340-85f6-ac8fdd9e3283">

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YaoFly** [comment]
run seatunnel\bin\install-plugin.cmd or install-plugin.sh please

**Comment by YaoFly** [comment]
If your maven setting file uses a mirror warehouse, please exclude repository jindodata,cloudera in the mirrorOf tag
eg:
`<mirrorOf>*,!jindodata,!cloudera</mirrorOf>`

**Comment by ruanwenjun** [comment]
Closed by #5511

**Comment by ruanwenjun** [comment]
> If your maven setting file uses a mirror warehouse, please exclude repository jindodata,cloudera in the mirrorOf tag
> eg:
> `<mirrorOf>*,!jindodata,!cloudera</mirrorOf>`

Thanks for your suggestion,  #5511  change this dependency to provided, this might solve this issue.
