### ISSUE TITLE
[Feature][Spark] Reading speed limit of source connector

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5504]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Reading speed limit of source connector

references
https://github.com/apache/seatunnel/pull/5502

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
You can assign it to me. Thank you
