### ISSUE TITLE
[Bug] [Config] ReadOnlyConfig can not transform to Config

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5536]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If an option with type Map, after `Config` transform to `ReadOnlyConfig`, It will can not be transform to Config again, If we do it , the map option will have wrong `key`.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
It should be fixed in #5612
