### ISSUE TITLE
[Feature][File Connector] Remove the orc and parquet file in test/resources dir & use code to create them in test case

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5545]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Dear community contributors, I have noticed that we have added some testing files to the resources directory of some connectors e2e [1]. Due to the fact that binary files are not allowed in the source code package of the Apache project release, we need to remove these test files. An alternative solution is to generate these test data files using code display instead of directly adding these files to the resources directory.

https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-file/connector-file-base/src/test/resources

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
I try it, assigned to me. @EricJoy2048
