### ISSUE TITLE
[Hotfix] [Seatunnel-Web][seatunnel-server] Null Pointer Exception when try to create new user

### ISSUE THREAD

**Issue by 112khanhamza** [apache/seatunnel#5549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I try to create a new user on the seatunnel-web UI it throws null pointer exception

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
NullPointerException
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhibinF** [comment]
This appears to be because user was not inserted in the table when the sql was created.

**Comment by 112khanhamza** [comment]
@zhibinF Thanks for commenting, it's because in the role table records are not inserted for normal user and admin user, I have updated the sql for the same and created a pull request. It also got merged today.
