### ISSUE TITLE
[Bug] [connector-jdbc] Nullable Column source have null data could be unexpected results.

### ISSUE THREAD

**Issue by mosence** [apache/seatunnel#5559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

create table s_a
(
    c_int       int        null,
    c_long      mediumtext null,
    c_short     smallint   null,
    c_byte      tinyint    null,
    c_decimal   decimal    null,
    c_float     float      null,
    c_double    double     null,
    c_boolean   tinyint(1) null,
    c_date      date       null,
    c_time      time       null,
    c_datetime  datetime   null,
    c_timestamp timestamp  null
);

create table t_a
(
    c_int       int        null,
    c_long      mediumtext null,
    c_short     smallint   null,
    c_byte      tinyint    null,
    c_decimal   decimal    null,
    c_float     float      null,
    c_double    double     null,
    c_boolean   tinyint(1) null,
    c_date      date       null,
    c_time      time       null,
    c_datetime  datetime   null,
    c_timestamp timestamp  null
);

s_a 's data like this: 

![image](https://github.com/apache/seatunnel/assets/2803645/c4d78fe9-95ac-46ad-91b6-4e3042c5da54)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  checkpoint.interval = 300000
  parallelism = 1
  job.mode = "BATCH"
}
source {
  jdbc {
    url = "jdbc:mysql://localhost:3306/db?useSsl=false"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "app"
    password = "password"
    query = "select c_int,c_long,c_short,c_byte,c_decimal,c_float,c_double,c_boolean,c_date,c_time,c_datetime,c_timestamp from s_a"
    result_table_name = "sourceTable"
  }
}
sink {
  jdbc {
    source_table_name = "sourceTable"
    url = "jdbc:mysql://localhost:3306/db?useSsl=false"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "user"
    password = "password"
    query = "insert into t_a(c_int,c_long,c_short,c_byte,c_decimal,c_float,c_double,c_boolean,c_date,c_time,c_datetime,c_timestamp) values (?,?,?,?,?,?,?,?,?,?,?,?);"
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh -c config.conf -e local
```

### Error Exception

```log
No exception. But data unexpected results. See Screenshots.
```

### Zeta or Flink or Spark Version

Zeta 

### Java or Scala Version

Java 1.8

### Screenshots

![1695713776582](https://github.com/apache/seatunnel/assets/2803645/1c9c868b-e57d-4c3a-bcfa-b9da96d04692)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Fixed by #5560
