### ISSUE TITLE
[Feature][File Connector] optionrule support ENABLE_HEADER_WRITE(FILE_FORMAT_TYPE is text/csv )

### ISSUE THREAD

**Issue by zck573693104** [apache/seatunnel#5566]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

optionrule FILE_FORMAT_TYPE is text/csv ,add parameter BaseSinkConfig.ENABLE_HEADER_WRITE

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Resolved by #5567
