### ISSUE TITLE
[Bug] [FileConnector] Optimize the File connector OptionRule

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#5571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I found in some file connectors the OptionRule is not the same as the code in the connector.
We need to optimize this.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qizhiliu0639** [comment]
Hi, I'd like to fix this bug. It seems like that the file connector OptionRule in Doc and the OptionRule in code are not the same right?
