### ISSUE TITLE
[Improve][E2E][Log] Set Logger level to INFO

### ISSUE THREAD

**Issue by CheneyYin** [apache/seatunnel#5587]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 I found that some necessary logs of `seatunnel-e2e` were not output. These logs are useful for debugging and feature verification. I suggest set logger level to *INFO* in `seatunnel-e2e/seatunnel-e2e-common/src/test/resources/log4j2.properties`.

Before change level
![level_warn](https://github.com/apache/seatunnel/assets/29588249/8a9e5b89-261f-46cd-8782-b266987cf180)

After change level
![level_info](https://github.com/apache/seatunnel/assets/29588249/6ca2afc2-1c65-4e45-bc92-9c1539bf6533)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
There is no need to set it as info level in e2e. The log will be very large. We can tell the developer to change the log level to info in the document.

**Comment by CheneyYin** [comment]
> There is no need to set it as info level in e2e. The log will be very large. We can tell the developer to change the log level to info in the document.

I agree with you

- #5589
