### ISSUE TITLE
Does version 2.3.3 support the configuration of multiple tables in the same database?

### ISSUE THREAD

**Issue by Python-IBM** [apache/seatunnel#5592]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The source and sink configuration in the official document connector V2 of version 2.3.3 only supports single tables and does not support multiple tables.

### Usage Scenario

source {
  MySQL-CDC {
    result_table_name = "fake"
    parallelism = 1
    server-id = 5656
    username = "mysqluser"
    password = "mysqlpw"
    database-name = mysql_test
    table-names = ["table_a","table_b","table_c"]
    base-url = "jdbc:mysql://localhost:56725/inventory_vwyw0n"
  }
}

sink {
    Doris {
        fenodes = "e2e_dorisdb:8030"
        username = root
        password = ""
        #table.identifier = "test.e2e_table_sink"
        database-name = doris_test
        table-names = ["table_a","table_b","table_c"]
        sink.enable-2pc = "true"
        sink.label-prefix = "test_csv"
        doris.config = {
          format = "csv"
          column_separator = ","
        }
    }
}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
This feature is not currently supported. But the community is already developing.

**Comment by Python-IBM** [comment]
> This feature is not currently supported. But the community is already developing.

May I ask which version will support multi table configuration for source and sink?
