### ISSUE TITLE
can not find file with idea

### ISSUE THREAD

**Issue by ImprovementSugar** [apache/seatunnel#5629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

can not find file

![image](https://github.com/apache/seatunnel/assets/47029292/fb247eb2-0acf-4dc0-85cf-b09b28d0b270)

### SeaTunnel Version

dev 

### SeaTunnel Config

```conf
default
```

### Running Command

```shell
default
```

### Error Exception

```log
can not find file
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FuYouJ** [comment]
I also encountered some similar problems, and this is how I solved them.

- ./mvnw install -Dmaven.test.skip
-  mvn clean package -pl seatunnel-connectors-v2/connector-redis -am -DskipTests -T 1C
- open subModule.pom file,

![image](https://github.com/apache/seatunnel/assets/51348093/83c7ec2e-1815-4f6c-bca6-68ccf1873a56)

**Comment by Hisoka-X** [comment]
Please execute `mvn clean install -DskipTests`. Then refresh cache on maven in idea.
![image](https://github.com/apache/seatunnel/assets/32387433/04df4497-80a0-482c-a3e5-d16c9171fcbe)

**Comment by ImprovementSugar** [comment]
thanks its usesful
