### ISSUE TITLE
[Bug] [Zeta Engine] Savepoint cannot be stored as split

### ISSUE THREAD

**Issue by lihjChina** [apache/seatunnel#5636]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

My source has 1 million data and the target has 0. When I start the synchronization task, I write the data to the target and then execute The command ./seatunnel.sh -s 766195915831640065 was used to store the savepoint, but it was not found until the task was fully transferred and the target reached 1 million. Then the savepoint was written to HDFS.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
    "job.mode"="BATCH"
    "job.name"="DEMO"
    "execution.parallelism"=2
}
source {
    Jdbc {
        url="jdbc:mysql://xxx/seatunnel_source?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true"
        driver="com.mysql.cj.jdbc.Driver"
        user="root"
        password="xxx"
        query="select * from emp_quality_millions_100w"
        "partition_column"="emp_id"
        "partition_num"=40
        "parallelism"=2
    }
}
transform {
}
sink {
    Jdbc {
        url="jdbc:mysql://xxx/seatunnel_sink?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true"
        driver="com.mysql.cj.jdbc.Driver"
        user="root"
        password="xxx"
        database="seatunnel_sink"
        table="emp_104"
        "batch_size"="1000"
        "generate_sink_sql"="true"
	    "enable_upsert" = true
     	"generate_sink_sql" = true
        "query" = ""

    }
}



seatunnel.yaml is
seatunnel:
    engine:
        backup-count: 1
        queue-type: blockingqueue
        print-execution-info-interval: 60
        slot-service:
            dynamic-slot: true
        checkpoint:
            interval: 10000
            timeout: 300000
            storage:
                type: hdfs
                max-retained: 3
                plugin-config:
                    namespace: /tmp/seatunnel/checkpoint_snapshot/
                    storage.type: hdfs
                    fs.defaultFS: hdfs://xxx:8020
```

### Running Command

```shell
./bin/seatunnel.sh -s 766195915831640065
```

### Error Exception

```log
no exception
```

### Java or Scala Version

java version "1.8.0_291"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lihjChina** [comment]
This is all the logs
[https://github.com/lihjChina/log/blob/master/seatunnel-engine-server.log](url)

**Comment by Carl-Zhou-CN** [comment]
@lihjChina link #5695 The problem may have been improved, can you help verify it on the dev branch

**Comment by lihjChina** [comment]
I have verified it in dev and it has been resolved. Thank you

**Comment by lihjChina** [comment]
I have verified it in dev and it has been resolved. Thank you
