### ISSUE TITLE
[OnlineMeeting& Oct.17]SeaTunnel community meeting Topic collect

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5639]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

EricJoy2048 invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Time: 2023/10/17 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/02rEXoAn4FHR

#TencentMeeting: 473-393-591

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
#5395 and #5483

**Comment by ic4y** [comment]
transform supports multiple tables
add catalogTableMeta transform

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/issues/5482

**Comment by zhilinli123** [comment]
### Connector doc sync
#### Complete Connector document:
- [x]  RocketMq:https://github.com/apache/seatunnel/pull/5361
- [x]  Console:https://github.com/apache/seatunnel/pull/5230

#### Pending review: 
- [ ]  SftpFile&Socket:https://github.com/apache/seatunnel/pull/5386
- [ ]  SqlServer:https://github.com/apache/seatunnel/pull/5498
- [ ]  Common connector:https://github.com/apache/seatunnel/pull/5453
- [ ]  FakeSource:https://github.com/apache/seatunnel/pull/5255
#### Connector deployment
- [ ]  Docker:https://github.com/apache/seatunnel/pull/5580
- [ ] K8s:https://github.com/apache/seatunnel/pull/5594

**Comment by lianghuan-xatu** [comment]
https://github.com/apache/seatunnel/issues/5012

**Comment by chl-wxp** [comment]
https://github.com/apache/seatunnel/pull/5535

**Comment by ruanwenjun** [comment]
[Support config column/primaryKey/constraintKey in schema](https://github.com/apache/seatunnel/pull/5564)
