### ISSUE TITLE
[Bug][doc] connector-v2/sink/HdfsFile  Example parameter error

### ISSUE THREAD

**Issue by samael0119** [apache/seatunnel#5649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In the task example, the `file_format` parameter for `Simple` and `For orc file format simple config` should be `file_format_type` instead of `file_format`.

https://seatunnel.apache.org/docs/2.3.3/connector-v2/sink/HdfsFile#task-example

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
Yes, it was a bug
