### ISSUE TITLE
[Feature][Connector][JDBC] Add config option, Partition datatype

### ISSUE THREAD

**Issue by naxels** [apache/seatunnel#5656]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hi team,

Love SeaTunnel and have been seriously considering it for our future data integration needs at work.

The one problem I stumble into with Oracle, one of our bigger databases is the NUMBER type.
Looking through the issues & pull requests etc, I see that many other people are facing this issue.

We as well cannot use the parallel feature to optimally move thousands of records unfortunately.

I ran the OracleCatalog.java SELECT_COLUMNS_SQL_TEMPLATE SQL script
and this was returned:

<img width="1050" alt="image" src="https://github.com/apache/seatunnel/assets/3195443/ad3e216b-6ff4-4ecb-86f8-16e5207ad52f">

clearly with the defaults throwing me into Decimal territory.

Given that this is a hard problem to solve with Oracle and the code is already complex to try to turn it into a number.

I started thinking, what if there is an additional config option for JDBC, called something like
partition_type
partition_datatype
partition_overwrite_type

and setting this to integer or true (depending on your future thoughts regarding parallel support)
would force SeaTunnel to act as if the column is indeed an Integer (or future supported type) and not a Decimal.

Thank you for considering and keep up the good work!

### Usage Scenario

For Oracle connector parallel execution, speeding up data transfers

### Related issues

https://github.com/apache/seatunnel/pull/4439

https://github.com/apache/seatunnel/pull/5209

https://github.com/apache/seatunnel/issues/5204

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yjkim0083** [comment]
@naxels 
I found a solution.
add java_opt "-Doracle.jdbc.J2EE13Compliant=true"
