### ISSUE TITLE
[Feature][Mongodb-CDC] Add multi-table e2e testcase

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5679]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Feature][Mongodb-CDC] Add multi-table e2e testcase

add testcae into
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mongodb-e2e

reference
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mysql-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/mysql/MysqlCDCIT.java#L177

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ghost** [comment]
Hey @hailin0 ,

I've created a pull request, but there are errors in the Github Actions. I'll fix them and let you know.

**Comment by ghost** [comment]
Dear @hailin0,

After careful consideration and multiple attempts to address the issue, I have come to the realization that it is beyond my current expertise and skill set. 
I deeply apologize for any inconvenience this may cause to the team and the progress of the project. It was not my intention to hinder the development process, and I regret that I am unable to fulfill the requirements of this particular task.

Thank you for your understanding and support during this time.
