### ISSUE TITLE
org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:8081[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by wachoo** [apache/seatunnel#5689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:8081

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
1. config/hazelcast.yaml
hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - localhost
    port:
      auto-increment: false
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50


2. config/seatunnel.yaml
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission#      

3. config/v2.streaming.conf.template
```

### Running Command

```shell
bash ./bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/v2.streaming.conf.template
```

### Error Exception

```log
org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:8081
```

### Zeta or Flink or Spark Version

Flink 1.15.1

### Java or Scala Version

openjdk version "1.8.0_372"

### Screenshots

![image](https://github.com/apache/seatunnel/assets/13916787/880be5b6-e568-415b-bdf8-12daf807ffcf)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
you don't have start the flink cluster, you need start flink cluster before submit job.
pls refer https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

**Comment by wachoo** [comment]
> you don't have start the flink cluster, you need start flink cluster before submit job. pls refer https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

![image](https://github.com/apache/seatunnel/assets/13916787/7e2d39dc-cb64-49f5-ba23-156586156a99)

yeah, I have got the server started , just like 'org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer -d'
./bin/seatunnel-cluster.sh -d

but, it also doesn't work

**Comment by liunaijie** [comment]
if you need run with flink engine, you need 
1. start seatunnel cluster ( the `./bin/seatunnel-cluster.sh -d` command you run )
2. start the flink cluster ( cd flink home, run `./bin/start-cluster.sh` )
3. submit job 

https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/deployment/resource-providers/standalone/overview/

**Comment by wachoo** [comment]
> if you need run with flink engine, you need
> 
> 1. start seatunnel cluster ( the `./bin/seatunnel-cluster.sh -d` command you run )
> 2. start the flink cluster ( cd flink home, run `./bin/start-cluster.sh` )
> 3. submit job
> 
> https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/deployment/resource-providers/standalone/overview/

Thank you very much，it works !

**Comment by wachoo** [comment]
We should start the flink cluster firstly.
