### ISSUE TITLE
 [Bug] [seatunnel engine] rest-api post task always fail

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5691]
I deploy seatunnel by the method of [quick-start-seatunnel-engin](https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-seatunnel-engine).
and  The following code runs successfully
`
cd "apache-seatunnel-${version}"
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local

`
but with [rest-api](https://seatunnel.apache.org/docs/2.3.3/seatunnel-engine/rest-api)
post task always fail.(Whether it is fake data or use mysql)
![image](https://github.com/apache/seatunnel/assets/28780269/71ee437f-55d8-4488-bab0-55f9320cecd5)
![image](https://github.com/apache/seatunnel/assets/28780269/9b275716-9d29-4786-9c9b-276fa7f97ac3)
`json

{
    "env": {
        "job.mode": "batch"
    },
    "source": [
        {
            "plugin_name": "FakeSource",
            "result_table_name": "fake",
            "row.num": 100,
            "schema": {
                "fields": {
                    "name": "string",
                    "age": "int",
                    "card": "int"
                }
            }
        }
    ],
    "transform": [
    ],
    "sink": [
        {
            "plugin_name": "Console",
            "source_table_name": ["fake"]
        }
    ]
}
`

_Originally posted by @QiuZiXian in https://github.com/apache/seatunnel/issues/5686#issuecomment-1776409318_

**Comment by liunaijie** [comment]
what's your question? and is this duplicate with https://github.com/apache/seatunnel/issues/5686 ?

**Comment by QiuZiXian** [comment]
> what's your question? and is this duplicate with #5686 ?
I have closed #5686，It's only quote.my question is ： Running Command directly by linux shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
can success.
but 
use [rest-api](https://seatunnel.apache.org/docs/2.3.3/seatunnel-engine/rest-api) to post task always fail.
![image](https://github.com/apache/seatunnel/assets/28780269/80fbeadc-55c4-4b61-8e87-4c0cd3ff0bdf)
post request body:
`json
{
    "env": {
        "job.mode": "batch"
    },
    "source": [
         {
            "plugin_name": "connector-fake",
            "result_table_name": "fake",
            "row.num": 100,
            "schema": {
                "fields": {
                    "name": "string",
                    "age": "int",
                    "card": "int"
                }
            }
        }
    ],
    "transform": [
    ],
    "sink": [
        {
            "plugin_name": "Console",
            "source_table_name": ["fake"]
        }
    ]
}
`

**Comment by QiuZiXian** [comment]
> what's your question? and is this duplicate with #5686 ?

**Comment by liunaijie** [comment]
I check the code, it's a bug, we will fix it.

**Comment by Hisoka-X** [comment]
Fixed by https://github.com/apache/seatunnel/pull/5702
