### ISSUE TITLE
[Bug] [Rest-API] submit job api has some issue

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#5699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when use rest api to submit job, failed.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
https://seatunnel.apache.org/docs/2.3.3/seatunnel-engine/rest-api/
```

### Running Command

```shell
use postman call api `locahost:5801/hazelcast/rest/maps/submit-job`
```

### Error Exception

```log
{
    "status": "fail",
    "message": "null"
}
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by QiuZiXian** [comment]
see #5691

**Comment by QiuZiXian** [comment]
#5691 
has been fixed？

**Comment by Hisoka-X** [comment]
> #5691 has been fixed？

@QiuZiXian It should be fixed by #5702

**Comment by QiuZiXian** [comment]
thk.
Do I need to compile from source code or re-download 2.3.3? @Hisoka-X

**Comment by Hisoka-X** [comment]
you should compile from source of dev branch.

**Comment by QiuZiXian** [comment]
ok.
excuse me，how to deploy by flink or spark engine? #5737

**Comment by Hisoka-X** [comment]
https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

**Comment by QiuZiXian** [comment]
> https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

this only once. not a serve on 5801.
how to deploy  background process.
like a jar, nohup

**Comment by Hisoka-X** [comment]
5801 on for zeta. If you mean flink/spark master/jobmanager server, I think you should refer flink/spark doc on their website.

**Comment by QiuZiXian** [comment]
5801 for zeta.
but seatunnel engine support for zeta、flink、spark？doesn't it？
seatunnel with zeta on 5801，
then seatunnel with flink ，how to like ‘seatunnel with zeta on 5801’， deploy to background process.

I has deployed flink .and do successful as https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink.
What I want to know is how to run it in the background instead of the command line every time
