### ISSUE TITLE
[Bug] [Maxcompute] mvn install failure

### ISSUE THREAD

**Issue by aaaaaabiao** [apache/seatunnel#5709]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I followed the document and performed the operation, the following error occurred。
DOC:
<img width="864" alt="image" src="https://github.com/apache/seatunnel/assets/17848880/99483c6d-9c04-40ae-a236-5905d34e0f25">
ERROR
![image](https://github.com/apache/seatunnel/assets/17848880/b523fb30-a810-4a70-99a2-b733b877709c)
![image](https://github.com/apache/seatunnel/assets/17848880/c0af5612-1f4c-48d3-852d-b0b6c49ac2b0)

### SeaTunnel Version

latest

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
git clone git@github.com:apache/seatunnel.git
./mvnw install -Dmaven.test.skip
```

### Error Exception

```log
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project connector-maxcompute: Compilation failure: Compilation failure:
[ERROR] /coding/open-source/seatunnel/seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/source/MaxcomputeSourceFactory.java:[27] 错误: 找不到符号
[ERROR]   符号:   静态 SCHEMA
[ERROR]   位置: 类
[ERROR] /coding/open-source/seatunnel/seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/catalog/MaxComputeCatalogFactory.java:[28] 错误: 找不到符号
[ERROR]   符号:   静态 SCHEMA
[ERROR]   位置: 类
[ERROR] /coding/open-source/seatunnel/seatunnel-connectors-v2/connector-maxcompute/src/main/java/org/apache/seatunnel/connectors/seatunnel/maxcompute/source/MaxcomputeSource.java:[36] 错误: 找不到符号
[ERROR]   符号:   静态 SCHEMA
[ERROR]   位置: 类
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This is a mistake on dev. Already be fixed by https://github.com/apache/seatunnel/pull/5708. Thanks @aaaaaabiao for report this.
