### ISSUE TITLE
[Feature][Hive] support rcfile

### ISSUE THREAD

**Issue by melin** [apache/seatunnel#5711]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

There are some enterprises that use rcfile, for example： 招商局

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laglangyue** [comment]
orc file?

**Comment by melin** [comment]
> orc file?

No, RCFILE: https://cwiki.apache.org/confluence/display/Hive/RCFile
