### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by Best1055** [apache/seatunnel#5713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

读取mysql的bit类型字段报错，怎么样可以读取mysql的bit类型字段呢？

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
无
```

### Error Exception

```log
oro, apache, seatunnel core, starter, seatunnel SeaTunnelclient,main(SeaTunnelClient.ava' 34aused by: org.apache.seatunnel.transform.exception .TransformException:rted CAST AS tvpe: CHARat org.apache.seatunnel.transform. sglengine.zeta.Zetas0LType.getCastType(Zetas0LType, java:178)at org,apache. seatunnel.transform,salengine,zeta.Zetas0LType. getExpressionlype(Zetas0lType.iava:105)
ErrorCode:[COMMON-05]，ErrorDescription:[Unsupported operation]
Unsupp
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
can you provide the config.

**Comment by Best1055** [comment]
source {
  MySQL-CDC {
    result_table_name = ""
    debezium {
        snapshot.mode = "never"
        decimal.handling.mode = "double"
    }
    username = ""
    password = ""
    table-names = [""]
    base-url = ""
    #默认initial，同步历史数据 + 增量
    startup.mode = INITIAL
	format = DEFAULT
  }
}
sink {

  StarRocks {
    source_table_name = ""
    nodeUrls = [""]
	base-url = ""
    username = 
    password = ""
    database = ""
    table = ""
    batch_max_rows = 5000
    starrocks.config = {
      format = "JSON"
      strip_outer_array = "true"
    }
  }
}

**Comment by Best1055** [comment]
> 你能提供配置吗？

已经提供

**Comment by Best1055** [comment]
> can you provide the config.

ok
