### ISSUE TITLE
[Bug] [Connector-mongodb] The mongodb connector causes a consistent number of connections in the business system not to be released. Task run completed

### ISSUE THREAD

**Issue by Slashoper** [apache/seatunnel#5715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

below is my seatunnel job config:
env {
    execution.parallelism = 1
}

source {
  mongodb {
   uri = "mongodb://xxxxxx:xxx@xxxx:27017"
   database = "order_center"
   collection = "vehicleOrderOperation"
   flat.sync-string=true
   schema {
     fields {
           _id = string
     }
   }
   match.query="{ createTime : { $gte : ISODate(\"${pardate}T00:00:00Z\"), $lte : ISODate(\"${nowdate}T23:59:59Z\") } }"
}
}
transform {
    #sql {
    #    sql = "select name,age from fake"
    #}
}

sink {
    #Console {}
    
  S3File {
    bucket = "s3a://mhero-bdp-prod"
    tmp_path = "/tmp/seatunnel/mongo/vehicleOrderOperation"
    path="/xxxxxx_tmp/t_ods_vehicle_order_operation"
    fs.s3a.endpoint="http://xxxx:xxx"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "xxx"
    secret_key = "xxx"
    #file_format_type = "orc"
  }

}

The following figure shows the number of connections
![image](https://github.com/apache/seatunnel/assets/19834014/34041083-48d4-40fc-aeee-bf29fcd54aa6)

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
}

source {
  mongodb {
   uri = "mongodb://xxxxxx:xxx@xxxx:27017"
   database = "order_center"
   collection = "vehicleOrderOperation"
   flat.sync-string=true
   schema {
     fields {
           _id = string
     }
   }
   match.query="{ createTime : { $gte : ISODate(\"${pardate}T00:00:00Z\"), $lte : ISODate(\"${nowdate}T23:59:59Z\") } }"
}
}
transform {
    #sql {
    #    sql = "select name,age from fake"
    #}
}

sink {
    #Console {}
    
  S3File {
    bucket = "s3a://mhero-bdp-prod"
    tmp_path = "/tmp/seatunnel/mongo/vehicleOrderOperation"
    path="/xxxxxx_tmp/t_ods_vehicle_order_operation"
    fs.s3a.endpoint="http://xxxx:xxx"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "xxx"
    secret_key = "xxx"
    #file_format_type = "orc"
  }

}
```

### Running Command

```shell
seatunnel.sh --config ./config/mongodb.config
```

### Error Exception

```log
no
```

### Zeta or Flink or Spark Version

seatunnel engine 2.3.3

### Java or Scala Version

java

### Screenshots

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by W-dragan** [comment]
I have also discovered this issue and it has been resolved by modifying the local code
![image](https://github.com/user-attachments/assets/38677378-82b3-4776-8b65-ff09a70f4b29)
