### ISSUE TITLE
[Feature][Doris] Support multi-table source read

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5731]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Doris] Support multi-table source read

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@CodingGPT Please comment this issue

**Comment by CodingGPT** [comment]
please assign to me tks

**Comment by hailin0** [comment]
Hi, [CodingGPT](https://github.com/CodingGPT) , Is there any progress on this task?

**Comment by EricJoy2048** [comment]
Hi, [CodingGPT](https://github.com/CodingGPT) , Is there any progress on this task?

**Comment by EricJoy2048** [comment]
@CodingGPT

**Comment by hailin0** [comment]
Anyone willing to fix it?

**Comment by happyboy1024** [comment]
can assign it to me
