### ISSUE TITLE
[help][deploy] how to deploy to flink or spark engine

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5737]
how to deploy by flink or spark engine?

do like
https://seatunnel.apache.org/docs/2.3.3/seatunnel-engine/deployment
only for zeta.
so how to deploy by flink or spark engine?

**Comment by Hisoka-X** [comment]
https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

**Comment by QiuZiXian** [comment]
https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink

this only once. not a serve on 5801.
how to deploy background process.
like a jar, nohup

**Comment by QiuZiXian** [comment]
5801 for zeta.
but seatunnel engine support for zeta、flink、spark？doesn't it？
seatunnel with zeta on 5801，
then seatunnel with flink ，how to like ‘seatunnel with zeta on 5801’， deploy to background process.

I has deployed flink .and do successful as https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink.
What I want to know is how to run it in the background instead of the command line every time
