### ISSUE TITLE
[help][deploy] how to deploy to flink or spark engine

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5740]
#5737

**Comment by liunaijie** [comment]
first of all, change `config/seatunnel-env.sh` to config spark/flink home.

- Spark
run command to submit job

spark 3.x.x
```
cd "apache-seatunnel-${version}"
./bin/start-seatunnel-spark-3-connector-v2.sh \
--master local[4] \
--deploy-mode client \
--config ./config/seatunnel.streaming.conf.template
```

- Flink
1. start flink cluster fist

2. submit job 

```
cd "apache-seatunnel-${version}"
./bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/v2.streaming.conf.template
```

I think that's all clear in the document.

https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-flink
https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/quick-start-spark

**Comment by QiuZiXian** [comment]
yes，But it has nothing to do with my problem.
What I want to know is how to run it in the background instead of the command line every time.
What I need is a command that runs in the background, not a one-off

**Comment by liunaijie** [comment]
what do you mean run it in the background? submit job or start the cluster?

**Comment by QiuZiXian** [comment]
./bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/v2.streaming.conf.template

this method mean ：Run this command every time you execute a task.
but I hope it(flink engine) like zeta (5801) : need to run a task, only post rest-api
