### ISSUE TITLE
[Bug] [dev] some question of package 2.3.4 

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

package from win local dev env，
deploy linux env.
An error occurs when running at the beginning：
错误: 找不到或无法加载主类 
I tried to fix it. Using the config of 2.3.3, I could run it. but throw new error：
2023-10-30 10:34:06,678 WARN  org.apache.seatunnel.engine.server.log.Log4j2HttpPostCommandProcessor - [localhost]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job'}AbstractTextCommand[HTTP_POST]{requestId=6}
java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='connector-fake'} not found.

### SeaTunnel Version

dev （2.3.4）

### SeaTunnel Config

```conf
default
```

### Running Command

```shell
./bin/seatunnel-cluster.sh -d
```

### Error Exception

```log
java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='connector-fake'} not found.
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

1.8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/28780269/f3b90819-fb00-443f-8ff2-d414324c5ca3)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
the laster version is 2.3.3, why you have version 2.3.4? pls check you change, or re-download the lib and test.

**Comment by QiuZiXian** [comment]
#5691 
#5702 
2.3.3 how to apply the newest fix.
I have to pull the newest code.
When will a stable version be updated recently?

**Comment by liunaijie** [comment]
when the fix pr is merged, you can fetch the dev branch and rebuild the lib from source code. Or wait release.
For the rest-api issue, you can add the parameter jobId=1 as the temporary soluaction.

**Comment by QiuZiXian** [comment]
thks.
