### ISSUE TITLE
[Bug] [connector-v2] [http-base] How do I pass a POST request when the body parameter is a form?

### ISSUE THREAD

**Issue by cugwangping** [apache/seatunnel#5761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

How do I pass a POST request when the body parameter is a form? request method is POST,body parameter is form type,Content-Type: multipart/form-data，I hava a request test's response：{"timestamp":"2023-10-31T03:38:40.252+00:00","status":500,"error":"Internal Server Error","path":"/example/login"}. The Http interface returns 500 status code. The request body is a StringEntity, not a MultipartForm object. How should I solve this problem?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
	"env": {
		"execution.parallelism": 1,
		"job.mode": "BATCH"
	},
	"source": [{
		"plugin_name": "Http",
		"url": "http://127.0.0.1:8080/example/login",
		"format": "json",
		"method": "POST",
		"schema": {
			"fields": {
				"msg": "String",
				"code": "String"
			}
		},
		"json_field": {
			"msg": "$.msg",
			"code": "$.code"
		},
		"headers": {
			"Content-Type": "multipart/form-data"
		},
		"body": "username:\"admin\" password:\"12345\"",
		"result_table_name": "source"
	}],
	"sink": [{
		"plugin_name": "Console",
		"source_table_name": "source"
	}]
}
```

### Running Command

```shell
sh ./bin/seatunnel.sh -c http-form2console.json
```

### Error Exception

```log
ERROR org.apache.seatunnel.connectors.seatunnel.http.source.HttpSourceReader - http client execute exception, http response status code:[500], content:[{"timestamp":"2023-10-31T01:52:57.511+00:00","status":500,"error":"Internal Server Error","path":"/example/login"}]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jackyyyyyssss** [comment]
params args

**Comment by cugwangping** [comment]
This is my another test case, the response is still 500,exception is ERROR org.apache.seatunnel.connectors.seatunnel.http.source.HttpSourceReader - http client execute exception, http response status code:[500], content:[{"timestamp":"2023-10-31T06:15:48.040+00:00","status":500,"error":"Internal Server Error","path":"/example/login"}],config content is
{
	"env": {
		"execution.parallelism": 1,
		"job.mode": "BATCH"
	},
	"source": [{
		"plugin_name": "Http",
		"url": "http://127.0.0.1:8080/example/login",
		"format": "json",
		"method": "POST",
		"schema": {
			"fields": {
				"msg": "String",
				"code": "String"
			}
		},
		"json_field": {
			"msg": "$.msg",
			"code": "$.code"
		},
		"headers": {
			"Content-Type": "multipart/form-data"
		},
		"params": {
			"username": "admin",
			"password": "12345"
		},
		"result_table_name": "source"
	}],
	"sink": [{
		"plugin_name": "Console",
		"source_table_name": "source"
	}]
}
Please help me see what is wrong with the content of config? Thanks!

**Comment by jackyyyyyssss** [comment]
remove headers  try again

**Comment by cugwangping** [comment]
I execute again,this is my execute exception result 
ERROR org.apache.seatunnel.connectors.seatunnel.http.source.HttpSourceReader - http client execute exception, http response status code:[415], content:[{"timestamp":"2023-10-31T07:11:17.196+00:00","status":415,"error":"Unsupported Media Type","path":"/example/login"}]
Base on this exception 415 status code，request header parameter Content-Type: "multipart/form-data" is need

**Comment by cugwangping** [comment]
I have read the source code of Seatunnel. In the Http Post method, only the UrlEncodedFormEntity parameter object is passed in the params parameter, and the Content-Type is set to application/x-www-form-urlencoded. There is no parameter object handling like MultipartEntityBuilder, pom.xml has only httpclient and httpcore dependencies, and no httpmime dependency for handling the body parameter of multipart/form-data，Are you sure that Content-Type multipart/form-data form parameter passing is supported?

**Comment by jackyyyyyssss** [comment]
thanks  remind source code   auto  set application/x-www-form-urlencoded. this version not support . welcome to submit a PR to support in the future
