### ISSUE TITLE
[Feature] [rest-api] get finished jobs info.

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

get {{seatunnel-server}}/hazelcast/rest/maps/running-jobs
(I have submit some job, and confirmed they are successfully working.)
always get a empty list.
Could it be that this interface can only obtain running tasks, but cannot obtain completed or failed tasks?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
default
```

### Running Command

```shell
get {{seatunnel-server}}/hazelcast/rest/maps/running-jobs
```

### Error Exception

```log
empty list
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

1.8

### Screenshots

![Uploading image.png…]()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@liugddx  PTAL

**Comment by wangzhiwei61** [comment]
I'm also having the same problem, can you solve it @liugddx

**Comment by liugddx** [comment]
> I'm also having the same problem, can you solve it @liugddx

Can you put your detailed log here? I'll take a look when I have time.

**Comment by wangzhiwei61** [comment]
I looked at the source code, and if the task is completed, I can't get the job information, right? Because the data is in memory, can I only get the log file, or is there any other solution?@liugddx

**Comment by wangzhiwei61** [comment]
The operation process and logs are as follows,Trouble the big guy to help take a look:
1.The jobId is returned when the task is submitted
2.Query the result by using the jobId,Expects to return object, actually returns {}
@liugddx 
[log.txt](https://github.com/apache/seatunnel/files/13496242/log.txt)
<img width="451" alt="1" src="https://github.com/apache/seatunnel/assets/106916990/0aff0106-c14f-4fef-a69e-163ceeef4bd1">

**Comment by wangzhiwei61** [comment]
@QiuZiXian  Friend, do you have any solution to this problem, please if you know can give some valuable advice

**Comment by liugddx** [comment]
Do you want to get historical jobs?

**Comment by wangzhiwei61** [comment]
@liugddx  I don't know if it's appropriate to ask a question on this bug,Because I'm getting the data empty for the  /hazelcast/rest/maps/running-job/:jobId , but I think it might be the same problem
-------------------
environment：
1.Apache SeaTunnel 2.3.3
2.SeaTunnel Engine
3.cluster-mode，But in reality, I'm just a single service, because I want to start in the background, just for testing
steps：
1./hazelcast/rest/maps/submit-job,return jobId and jobname 
2./hazelcast/rest/maps/running-job/{jobid} ,return {}
-------------------
log：
[log.txt](https://github.com/apache/seatunnel/files/13539022/log.txt)
-------------------
config:

hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - localhost
    port:
      auto-increment: false
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50

I don't know if there is any lack of information, can you tell me to see the first time to complete，sir

**Comment by liugddx** [comment]
> @liugddx  I don't know if it's appropriate to ask a question on this bug,Because I'm getting the data empty for the  /hazelcast/rest/maps/running-job/:jobId , but I think it might be the same problem
> 
> -------------------
> 
> environment：
> 
> 1.Apache SeaTunnel 2.3.3
> 
> 2.SeaTunnel Engine
> 
> 3.cluster-mode，But in reality, I'm just a single service, because I want to start in the background, just for testing
> 
> steps：
> 
> 1./hazelcast/rest/maps/submit-job,return jobId and jobname 
> 
> 2./hazelcast/rest/maps/running-job/{jobid} ,return {}
> 
> -------------------
> 
> log：
> 
> [log.txt](https://github.com/apache/seatunnel/files/13539022/log.txt)
> 
> -------------------
> 
> config:
> 
> 
> 
> hazelcast:
> 
>   cluster-name: seatunnel
> 
>   network:
> 
>     rest-api:
> 
>       enabled: true
> 
>       endpoint-groups:
> 
>         CLUSTER_WRITE:
> 
>           enabled: true
> 
>         DATA:
> 
>           enabled: true
> 
>     join:
> 
>       tcp-ip:
> 
>         enabled: true
> 
>         member-list:
> 
>           - localhost
> 
>     port:
> 
>       auto-increment: false
> 
>       port: 5801
> 
>   properties:
> 
>     hazelcast.invocation.max.retry.count: 20
> 
>     hazelcast.tcp.join.port.try.count: 30
> 
>     hazelcast.logging.type: log4j2
> 
>     hazelcast.operation.generic.thread.count: 50
> 
> 
> 
> I don't know if there is any lack of information, can you tell me to see the first time to complete，sir

It's the same problem.
