### ISSUE TITLE
[Bug] [seatunnel-connectors-v2] [connector-elasticsearch] 同步es array格式数据出错

### ISSUE THREAD

**Issue by klin-w** [apache/seatunnel#5792]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

同步数组格式时返回值只有一个值正确，其他值为null

### SeaTunnel Version

2.3.3
2.3.2
2.3.1

### SeaTunnel Config

```conf
key1 = "array<string>"
```

### Running Command

```shell
sh apache-seatunnel-2.3.3/bin/seatunnel.sh --config test.config
```

### Error Exception

```log
返回值为null
{
"key1": ["value1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
}
```

### Zeta or Flink or Spark Version

zeta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klin-w** [comment]
目前发现代码bug
https://github.com/apache/seatunnel/blob/2.3.3-release/seatunnel-connectors-v2/connector-elasticsearch/src/main/java/org/apache/seatunnel/connectors/seatunnel/elasticsearch/serialize/source/DefaultSeaTunnelRowDeserializer.java
convertValue方法中
for (int i = 0; i < stringList.size(); i++) {
                Object convertValue = convertValue(elementType, stringList.get(i));
                Array.set(arr, 0, convertValue);
            }
Array.set(arr, 0, convertValue);应该修改为Array.set(arr, i, convertValue);

**Comment by Carl-Zhou-CN** [comment]
@klin-w hi, this seems to be a bug, are you interested in fixing it
