### ISSUE TITLE
[Bug] jdbc to jdbc数据同步任务卡住&数据量与日志打印不符(2.3.2版本正常)

### ISSUE THREAD

**Issue by ClamJohn** [apache/seatunnel#5806]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

jdbc数据同步任务卡住&数据量与日志打印不符
<img width="1545" alt="image" src="https://github.com/apache/seatunnel/assets/53480226/8c60ebc0-0797-4d2f-b158-9281f3df8117">

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
	    "env" : {
	        "execution.parallelism" : 10,
	        "job.mode" : "BATCH",
	        "job.name" : "ads.ads_tag_user_pregnant_d_20231106",
	        "checkpoint.interval" : 60000
	    },
	    "source" : [
	        {
	            "password" : "xxx",
	            "driver" : "com.mysql.cj.jdbc.Driver",
	            "query" : " select id ,day_time ,user_id ,data_source ,replace(replace(result,'\n',''),'\r','') result ,pregnant_date ,report_pregnant_w ,pregnant_w ,pregnant_period ,pregnant_flag ,pregnant_prepare_flag ,create_time ,update_time from shujuzhongxin.ads_user_pregnant_d",
	            "connection_check_timeout_sec" : 100,
	            "fetch_size" : 10000,
	            "partition_column" : "id",
	            "plugin_name" : "Jdbc",
	            "user" : "shujuzhongxin",
	            "url" : "jdbc:mysql://10.20.50.29:3306?serverTimezone=GMT%2b8",
	            "partition_num" : 10
	        }
	    ],
	    "transform" : [],
	    "sink" : [
	        {
	            "password" : "xxx",
	            "database" : "ads",
	            "primary_keys" : [
	                "id"
	            ],
	            "batch_size" : 10000,
	            "driver" : "com.mysql.cj.jdbc.Driver",
	            "max_retries" : 1,
	            "connection_check_timeout_sec" : 100,
	            "generate_sink_sql" : true,
	            "plugin_name" : "Jdbc",
	            "user" : "DolphinScheduler",
	            "url" : "jdbc:mysql://xxx:3306?serverTimezone=GMT%2b8&rewriteBatchedStatements=true",
	            "table" : "ads_tag_user_pregnant_d"
	        }
	    ]
	}
```

### Running Command

```shell
${SEATUNNEL_HOME}/seatunnel.sh --config ${st_config_file}
```

### Error Exception

```log
无异常,任务卡住
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by happyboy1024** [comment]
Can you provide a more complete log? And describe your environment in detail.

**Comment by ClamJohn** [comment]
[1699406867117.log](https://github.com/apache/seatunnel/files/13291464/1699406867117.log)

**Comment by happyboy1024** [comment]
> [1699406867117.log](https://github.com/apache/seatunnel/files/13291464/1699406867117.log)

This is the log of the client side, and the log of the server side is also provided.

**Comment by ClamJohn** [comment]
[seatunnel-engine-server.log](https://github.com/apache/seatunnel/files/13292824/seatunnel-engine-server.log)

**Comment by happyboy1024** [comment]
> [seatunnel-engine-server.log](https://github.com/apache/seatunnel/files/13292824/seatunnel-engine-server.log)

I see that your server deployment has three nodes, but only provides logs for one node.

**Comment by happyboy1024** [comment]
> [seatunnel-engine-server.log](https://github.com/apache/seatunnel/files/13292824/seatunnel-engine-server.log)

I used the dolphinscheduler 3.1.8 and seatunnel 2.3.3 environments for testing and the data was synchronized successfully. You can try analyzing the logs of other server nodes
![image](https://github.com/apache/seatunnel/assets/137260654/34724f0e-ffb5-4f57-86e6-851ba9f433c9)
![image](https://github.com/apache/seatunnel/assets/137260654/4207781a-2fa6-48c6-b579-70a970453ba6)

**Comment by ClamJohn** [comment]
[seatunnel-engine-server3.log](https://github.com/apache/seatunnel/files/13314385/seatunnel-engine-server3.log)
[seatunnel-engine-server2.log](https://github.com/apache/seatunnel/files/13314386/seatunnel-engine-server2.log)

**Comment by EricJoy2048** [comment]
Can you run this sql in the mysql client?`select id ,day_time ,user_id ,data_source ,replace(replace(result,'\n',''),'\r','') result ,pregnant_date ,report_pregnant_w ,pregnant_w ,pregnant_period ,pregnant_flag ,pregnant_prepare_flag ,create_time ,update_time from shujuzhongxin.ads_user_pregnant_d` ?
