### ISSUE TITLE
[Bug] [Module Name]  Hive Source  read_partitions option  当配置的分区不在表文件目录时会被throw 异常提早退出

### ISSUE THREAD

**Issue by viverlxl** [apache/seatunnel#5811]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

如下配置，当指定分区的时候，如果该表的有任何一个分区路径没有包含在分区的时候，直接抛出异常。
<img width="780" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/3dc90247-3637-444f-8ea2-a64d0f1c8064">

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "hive_to_ck_file"
  spark.executor.instances = 4
  spark.executor.cores = 1
  spark.executor.memory = "3g"
  // This configuration is required
  spark.sql.catalogImplementation = "hive"
  spark.executor.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.driver.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.hadoop.hive.exec.dynamic.partition = "true"
  spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
  spark.debug.maxToStringFields = 100000
}
source {
    hive {
        table_name = "xxxx.xxxx"
        metastore_uri = "thrift://xxxx:9083"
        result_table_name = "xxx_d_test_01"
        parallelism = 4
        read_partitions = ["dt=2023-10-30"]
    }
}
transform {}
sink {
    ClickhouseFile {
        host = "xxxx:8123"
        server_time_zone = "Asia/Shanghai"
        database = "dms_ddcx_xxx"
        parallelism = 4
        table = "xx_d_test_test"
        sharding_key = "diversion_id"
        username = "xxx"
        password = "xxxx"
        node_free_password = true
        clickhouse_local_path = "/opt/software/clickhouse local"
        node_pass = []
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-3-connector-v2.sh --master yarn --deploy-mode cluster --config config/hive_to_ck_online.config
```

### Error Exception

```log
throw new FileConnectorException(
                    FileConnectorErrorCode.FILE_LIST_EMPTY,
                    "The target file list is empty,"
                            + "SeaTunnel will not be able to sync empty table, "
                            + "please check the configuration parameters such as: [file_filter_pattern]");
```

### Zeta or Flink or Spark Version

spark: 3.2.4

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by viverlxl** [comment]
判断fileNames是不是空，应该要在递归函数之外

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X I'd like to try it. Please assign it to me

**Comment by hailin0** [comment]
this pr fixed
https://github.com/apache/seatunnel/pull/5591

**Comment by Carl-Zhou-CN** [comment]
@viverlxl hi, can you help verify this problem?

**Comment by viverlxl** [comment]
> @viverlxl hi, can you help verify this problem?

yes, LGTM

**Comment by Carl-Zhou-CN** [comment]
> > @viverlxl hi, can you help verify this problem?
> 
> yes, LGTM

Let me close this issue
