### ISSUE TITLE
[Bug] [Module Name] Hive2CK using CK File  generate data_local.log slow

### ISSUE THREAD

**Issue by viverlxl** [apache/seatunnel#5819]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

using  CK File sync hive data to ck，total data count 2.3KW，using CK JDBC 40m, using CK File 8h。

From Spark Log, know generate data_local.log  spend 7h, from data_local.log to CK table file spend 5h

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "hive_to_ck_file"
  spark.executor.instances = 4
  spark.executor.cores = 1
  spark.executor.memory = "3g"
  // This configuration is required
  spark.sql.catalogImplementation = "hive"
  spark.executor.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.driver.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.hadoop.hive.exec.dynamic.partition = "true"
  spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
  spark.debug.maxToStringFields = 100000
}
source {
    hive {
        table_name = "dms_ddcx.xx_table"
        metastore_uri = "thrift://xxxxx:9083"
        result_table_name = "table"
        parallelism = 4
        read_partitions = ["dt=2023-10-30"]
    }
}
transform {}
sink {
    ClickhouseFile {
        host = "xxx:8123"
        server_time_zone = "Asia/Shanghai"
        database = "dms_ddcx"
        parallelism = 4
        table = "xxxx"
        source_table_name = "xxxx"
        sharding_key = "diversion_id"
        username = "default"
        password = ""
        node_free_password = true
        clickhouse_local_path = "/opt/software/clickhouse local"
        node_pass = []
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-3-connector-v2.sh --master yarn --deploy-mode cluster --config config/hive_to_ck_test.config
```

### Error Exception

```log
no error
```

### Zeta or Flink or Spark Version

spark 3.2.4

### Java or Scala Version

java 1.8

### Screenshots

<img width="1393" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/6f7857e7-e5ef-48d7-875c-4f69d62bc243">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by viverlxl** [comment]
<img width="675" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/c2a21770-f944-4c1d-8047-1c3411d4bf34">
如图中的每条数据一个mmap操作导致写入性能不太好

**Comment by viverlxl** [comment]
use mmap buffer can solve this issue
<img width="890" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/13086f6e-ee47-4cea-83dd-05081a7d8de0">

写2.3kw到data_local.log， 从原来的5小时变成4分钟。表象来看是一条数据初始化一个mmap带来的性能问题

**Comment by viverlxl** [comment]
<img width="1147" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/ac2ef499-3eef-483a-aed5-983aca320144">
原代码和修改后的代码做对比

**Comment by viverlxl** [comment]
@Hisoka-X  can i fix this issue

**Comment by Hisoka-X** [comment]
Sure! Looking forward your PR! @viverlxl

**Comment by viverlxl** [comment]
after fix this issue 
<img width="1425" alt="image" src="https://github.com/apache/seatunnel/assets/35752202/ac65c6c3-9c0d-4959-b387-2983b863e28d">

2.3kw records generate data_local.log file is 4 minutes
