### ISSUE TITLE
[Feature][Zeta] Add a checkpoint switch option to control the opening and closing of the checkpoint

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5829]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

## Backend

Now in zeta engine all job will enable checkpoint default. However, based on user feedback, it is not necessary to enable checkpoint in most offline scenarios, and the use of checkpoint requires high configuration of split data in the source table. Many users experience checkpoint timeout due to incorrect split configuration.

## How to solve it

We can determine whether checkpoint is enabled by whether `checkpoint.interval` is configured.
Some key points:

* This parameter also acts on Zeta, Flink, and Spark. The specific unified behavior of the three engines.
* For Streaming Job, checkpoint cannot be closed. If `checkpoint.interval` is not configured, the `checkpoint.interval` value configured in `seatunnel.yaml` will be used.
* For Batch Job, we can choose to turn checkpoint on or off, do not start checkpoint if `checkpoint.interval` is not configured, and enable checkpoint if `checkpoint.interval` is configured.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
clean checkpoint  setting  in the batch job e2e & docs

**Comment by FlechazoW** [comment]
I'm willing to do this task, can you assign this to me?

**Comment by EricJoy2048** [comment]
> I'm willing to do this task, can you assign this to me?

Hi, @FlechazoW  , Is there any progress on this task?
