### ISSUE TITLE
[Feature][Translation] support dbt

### ISSUE THREAD

**Issue by jianchengwang** [apache/seatunnel#5834]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

dbt is a transformation workflow that helps you get more work done while producing higher quality results. You can use dbt to modularize and centralize your analytics code, while also providing your data team with guardrails typically found in software engineering workflows. Collaborate on data models, version them, and test and document your queries before safely deploying them to production, with monitoring and visibility.

here is the website https://docs.getdbt.com/

airbyte, bigquery, and most of elt engine also support dbt as their translation.

so I recommend you can support it

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vijay-jangir** [comment]
any work being done on this?
