### ISSUE TITLE
[Feature][Connector-V2] is oss support minio?

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5835]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

is oss support minio.
if yes,can you give me an example 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi，@QiuZiXian Can you be more specific？

**Comment by QiuZiXian** [comment]
### Oss file source connector：
**is this only supply for ali oss？**
**[ minio](https://github.com/minio/minio) is used to be oss system，but fail.**
```json
{
    "deploy-mode":"run",
    "env": {
        "job.mode": "batch"
    },
    "source": [
        {
            "plugin_name": "OssFile",
            "path": "test.xlsx",
            "bucket": "oss://test",
            "access_key": "axxin",
            "access_secret": "adm456",
            "endpoint": "http://192.1xx138:9000",
            "file_format_type": "excel",
            "schema": {
                "fields": {
                    "name": "string",
                    "nick": "string"
                }
            }
        }
    ],
    "transform": [],
    "sink": [
        {
            "plugin_name": "Console"

        }
    ]
}

````
**fail msg:**

`
{
    "status": "fail",
    "message": "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.\n[ErrorCode]: InvalidRequest\n[RequestId]: \n[HostId]: ddaed5a9-1053-4c93-b1f3-6ec208c3ae88\n[ResponseError]:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><Resource>/</Resource><RequestId></RequestId><HostId>ddaed5a9-1053-4c93-b1f3-6ec208c3ae88</HostId></Error>"
}
`

**use "bucket": "test"：**
`bash
{
    "status": "fail",
    "message": "java.net.UnknownHostException: test"
}
`
**I'm sure minio has the bucket of test .**

**Comment by Carl-Zhou-CN** [comment]
hi ,@QiuZiXian Can you try it using S3File?,because minio should support s3 protocol
