### ISSUE TITLE
[OnlineMeeting&Nov.14] SeaTunnel community meeting Topic collection

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5837]
hailin0 invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Time: 2023/11/14 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/0Ewo1mAGdKsl

#TencentMeeting: 100-588-218

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

**Comment by hailin0** [comment]
@hailin0 
https://github.com/apache/seatunnel/issues/5677


@Hisoka-X
https://github.com/apache/seatunnel/issues/5652
https://github.com/apache/seatunnel/issues/5651

**Comment by hailin0** [comment]
@chl-wxp
https://github.com/apache/seatunnel/issues/5390

**Comment by hailin0** [comment]
@FlechazoW
https://github.com/apache/seatunnel/issues/5829

**Comment by zhilinli123** [comment]
### Connector doc  sync
 **open doc pr:**
- [ ]  SftpFile:https://github.com/apache/seatunnel/pull/5386

 **Complete Connector document:**
- [x]  RocketMq:https://github.com/apache/seatunnel/pull/5361
- [x]  Socket:https://github.com/apache/seatunnel/pull/5287
- [x]  Console:https://github.com/apache/seatunnel/pull/5230
**issues:**
https://github.com/apache/seatunnel/issues/4572
**Thanks to all contributors for their contributions to the Connector documentation**

**Comment by liunaijie** [comment]
docker image https://github.com/apache/seatunnel/pull/5526

**Comment by coalchan** [comment]
目前 SeaTunnel Web 只支持 zeta server ，不支持 on spark/flink 吗

**Comment by xiamidavid00** [comment]
Batch job support scheduled tasks

**Comment by Carl-Zhou-CN** [comment]
The meeting ends. Close this issue
