### ISSUE TITLE
[Feature][connector] key by with sink

### ISSUE THREAD

**Issue by zhangqing123** [apache/seatunnel#5839]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I want to implement a sink for a graph database that includes creation, modification, and deletion. However, I'm unsure how to implement keyBy because I can't confirm if the data received by the writer will be processed in chronological order after being written.
我想实现一个图数据的sink 包含新增、删除、修改等动作, 但是在writer实现的时候，发现仅能够处理数据，无法处理数据的keyby,因此我想请问这块如何处理，seatunnel 如何使用keyby,以及相关的资料 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi @zhangqing123 Can you be more specific？
