### ISSUE TITLE
[Bug] [connector-http-base] source code compile error

### ISSUE THREAD

**Issue by alextinng** [apache/seatunnel#5840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source code compile error, error message is "Cannot resolve symbol 'Config'"

![image](https://github.com/apache/seatunnel/assets/17078980/bf806535-9e21-4135-b290-31288cd31096)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DalongZhenZ** [comment]
mvn -T 16  clean install '-Dmaven.test.skip=true' '-Dcheckstyle.skip=true'  , rebuild, your network cause this wrong

**Comment by ruanwenjun** [comment]
Seems solved, I close this issue.
