### ISSUE TITLE
[Bug] [website] Checkpoint-Storage description is incorrect.

### ISSUE THREAD

**Issue by utopianet** [apache/seatunnel#5845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://seatunnel.incubator.apache.org/docs/2.3.3/seatunnel-engine/checkpoint-storage
Among the HDFS section, the kerberosKeytab configuration item is incorrect.
Among them, the seatunnel.hadoop.dfs.client.failover.proxy.provider.usdp-bing configuration item has an extra double quotation mark at the end.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
not need
```

### Running Command

```shell
not need
```

### Error Exception

```log
not need
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by michalrys** [comment]
Simple fix is here: https://github.com/apache/seatunnel/pull/5883
