### ISSUE TITLE
[Bug] [WebSite] SeaTunnel Web Source download link is error

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#5846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://seatunnel.apache.org/download

<img width="1104" alt="image" src="https://github.com/apache/seatunnel/assets/32193458/f4437d72-d62c-40d9-85e5-55e009e06098">

The source tar download link is `https://downloads.apache.org/seatunnel/seatunnel-web/1.0.0/apache-seatunnel-web-1.0.0-bin.tar.gz`

### SeaTunnel Version

seatunnel web 1.0.0

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GHkrishna** [comment]
I have created a PR on the respective repo (seatunnel-website)

The PR: https://github.com/apache/seatunnel-website/pull/280 

Would appreciate it if @EricJoy2048, you could please review.

**Comment by EricJoy2048** [comment]
> I have created a PR on the respective repo (seatunnel-website)
> 
> The PR: [apache/seatunnel-website#280](https://github.com/apache/seatunnel-website/pull/280)
> 
> Would appreciate it if @EricJoy2048, you could please review.

Done, Thanks for your contribution.
