### ISSUE TITLE
[Improve][E2E] Rename connector-jdbc-e2e-part-x module name

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#5849]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have multiple submodule in e2e.
<img width="407" alt="image" src="https://github.com/apache/seatunnel/assets/22415594/898aefea-86ee-489f-8ec1-023c3e8bde65">
<img width="437" alt="image" src="https://github.com/apache/seatunnel/assets/22415594/cd0ec9bc-e4fc-42e1-acce-66113bc227d5">
This is not friendly enough for contributors wants to add e2e code. It's better to rename to `connector-jdbc-e2e-oracle` , `connector-jdbc-e2e-mysql` or some else.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hnbian** [comment]
Could I try it?

**Comment by ruanwenjun** [comment]
> Could I try it?

Assigned.

**Comment by hnbian** [comment]
Sorry, can you assign that to me again?

**Comment by Carl-Zhou-CN** [comment]
> Sorry, can you assign that to me again?

It was reassigned to you
