### ISSUE TITLE
[Feature][Connector] have any plans to support Oracle cdc?

### ISSUE THREAD

**Issue by elait** [apache/seatunnel#5854]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

hi，Do you have any plans to support Oracle cdc？eg oracle 11, 12, 19, 21.
and the debezium version upgrade to 1.9 +?

### Usage Scenario

debezium :1.9+;
Oracle cdc:11, 12, 19, 21

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jyclovep** [comment]
we have alreay  supported  that but not upload the code yet

**Comment by yinshaohua77** [comment]
next version will not upload code and support the feature 吗？@jylovep

**Comment by Carl-Zhou-CN** [comment]
In the near future, I will complete Oracle CDC #5196

**Comment by xyzhh** [comment]
> In the near future, I will complete Oracle CDC #5196

I am looking forward to it.I wish "near fture"  doesn't mean more than  three months. Good luck!

**Comment by Carl-Zhou-CN** [comment]
> > In the near future, I will complete Oracle CDC #5196
> 
> I am looking forward to it.I wish "near fture" doesn't mean more than three months. Good luck!

Stay tuned
