### ISSUE TITLE
[Bug] [Doc] [Web] Fix web doc bug

### ISSUE THREAD

**Issue by ldxwmr** [apache/seatunnel#5855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The document version may be faulty.
![image](https://github.com/apache/seatunnel/assets/34700499/4b276914-6db4-43e6-974e-937698de3d52)

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
No
```

### Running Command

```shell
No
```

### Error Exception

```log
No
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi, @ldxwmr Has he made any new progress?
