### ISSUE TITLE
[Feature][CDC] seatunnel can support china dameng database cdc

### ISSUE THREAD

**Issue by wilsonfu88** [apache/seatunnel#5858]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

You will support china dameng database cdc？ How to config it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangwei560** [comment]
Is Dameng CDC already supported, or is it still under development? If so, in which version can the relevant code be found
