### ISSUE TITLE
[Bug] [Zeta] HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V 

### ISSUE THREAD

**Issue by Light-Towers** [apache/seatunnel#5861]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use hive as connector-source, but failed. I'm not sure if it's a problem with manually upgrading the Hive version.

Related version info
**Bigdata platform**: CDH 6.3.2
**Hadoop version**: Hadoop 3.0.0-cdh6.3.2
**Hive version**: 3.1.3 (Manually upgraded version)

${apache-seatunnel}/lib catalog info:
[root@master01 apache-seatunnel-2.3.3]# ll lib/
total 83348
-rw-r--r-- 1 root root 41873154 Nov 16 09:51 hive-exec-3.1.3.jar
-rw-r--r-- 1 root root   313702 Nov 15 17:58 libfb303-0.9.3.jar
-rw-r--r-- 1 root root    10503 Aug 18 17:10 seatunnel-hadoop3-3.1.4-uber-2.3.3.jar
-rw-r--r-- 1 root root 42110549 Nov 14 16:25 seatunnel-hadoop3-3.1.4-uber-2.3.3-optional.jar
-rw-r--r-- 1 root root  1032927 Feb 18  2022 seatunnel-transforms-v2.jar

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  Hive {
    table_name = "ods_mg.ods_mg_enterprise_entbaseinfo"
    metastore_uri = "thrift://master02:9083"
    hdfs_site_path = "/etc/hadoop/conf/hdfs-site.xml"
    hive_site_path = "/etc/hive/conf/hive-site.xml"
#    read_partitions = ["dt=2023-11-13"]
  }

}

sink {
  Console {
    source_table_name = "fake1"
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/hive-es.config -e local
```

### Error Exception

```log
2023-11-16 10:37:08,623 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:61)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:77)
	at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:73)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:123)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Screenshots

![image](https://github.com/apache/seatunnel/assets/29267453/56af93be-8528-4c73-a462-977523182090)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CheneyYin** [comment]
`connector-hive` just support hive2. You might as well try the `connector-jdbc`, which provide hive3 jdbc source.

**Comment by Light-Towers** [comment]
> `connector-hive` just support hive2. You might as well try the `connector-jdbc`, which provide hive3 jdbc source.

I tried, but didn't succeed. `connector-jdbc` don't support hive too.

![image](https://github.com/apache/seatunnel/assets/29267453/b7f4c7a8-a431-4dfe-9920-5a29f8930fb8)

**Comment by CheneyYin** [comment]
> > `connector-hive` just support hive2. You might as well try the `connector-jdbc`, which provide hive3 jdbc source.
> 
> I tried, but didn't succeed. `connector-jdbc` don't support hive too.
> 
> ![image](https://github.com/apache/seatunnel/assets/29267453/b7f4c7a8-a431-4dfe-9920-5a29f8930fb8)
> 

Hive jdbc source will be released in 2.3.4. You can manually compile a copy to verify whether it is valid.

**Comment by Light-Towers** [comment]
> > > `connector-hive` just support hive2. You might as well try the `connector-jdbc`, which provide hive3 jdbc source.
> > 
> > 
> > I tried, but didn't succeed. `connector-jdbc` don't support hive too.
> > ![image](https://user-images.githubusercontent.com/29267453/284173716-b7f4c7a8-a431-4dfe-9920-5a29f8930fb8.png)
> 
> Hive jdbc source will be released in 2.3.4. You can manually compile a copy to verify whether it is valid.

OK，I will give it a try .  By the way, `connector-hive` ，When is it supported hive3 ？

**Comment by JohnYehyo** [comment]
> > > `connector-hive` just support hive2. You might as well try the `connector-jdbc`, which provide hive3 jdbc source.
> > 
> > 
> > I tried, but didn't succeed. `connector-jdbc` don't support hive too.
> > ![image](https://private-user-images.githubusercontent.com/29267453/284173716-b7f4c7a8-a431-4dfe-9920-5a29f8930fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTc0MTIsIm5iZiI6MTcwMjQ1NzExMiwicGF0aCI6Ii8yOTI2NzQ1My8yODQxNzM3MTYtYjdmNGM3YTgtYTQzMS00ZGZlLTk5MjAtNWEyOWY4OTMwZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA4NDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMWZmYTgyMzBiY2MxM2VjOGExOTlhMDU5MGZkNTExM2I2MWNhOGI2ODdjZTJhOWU0OTBlNjA0ZjRkZjUwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z1LfcJjuuU0GYIz4UkgNqt5ddwfsZ6int45FPo0KYcI)
> 
> Hive jdbc source will be released in 2.3.4. You can manually compile a copy to verify whether it is valid.

How to clone the code from the 2.3.4 branch? I can't find it in the repository branches

**Comment by sanjaychitransh** [comment]
Sea tunnel support table format  text, parquet and orc in hive, create table in default database.
try below after copying necessary jar in Lib directory. try below,i have done

# Defining the runtime environment
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**

  Hive {
    table_name = "default.countries_manged"
    metastore_uri = "thrift://cxxxxxxxx.xxxx.ixxx.com:9083"
  }

  # If you would like to get more information about how to configure seatunnel and see full list of input plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/source-plugins/Fake
}

transform {

}

sink {
  # choose stdout output plugin to output data to console
  Console {
  }

**Comment by Light-Towers** [comment]
@JohnYehyo   The latest released version is 2.3.3,

**Comment by JohnYehyo** [comment]
> @JohnYehyo The latest released version is 2.3.3,

Yes. Additionally, I resolved this issue by using HdfsFile instead of connector-hive/connector-jdbc.
for example:
```
HdfsFile {
      fs.defaultFS = "hdfs://192.168.7.43:8020"
      path = "/user/hive/warehouse/xxx.db/xxx"
      file_format_type = "text"
    }
```
[HdfsFile](https://seatunnel.apache.org/docs/2.3.3/connector-v2/sink/HdfsFile)

**Comment by Light-Towers** [comment]
> > @JohnYehyo The latest released version is 2.3.3,
> 
> Yes. Additionally, I resolved this issue by using HdfsFile instead of connector-hive/connector-jdbc. for example:
> 
> ```
> HdfsFile {
>       fs.defaultFS = "hdfs://192.168.7.43:8020"
>       path = "/user/hive/warehouse/xxx.db/xxx"
>       file_format_type = "text"
>     }
> ```
> 
> [HdfsFile](https://seatunnel.apache.org/docs/2.3.3/connector-v2/sink/HdfsFile)

HDFS can solve current problem, Thank you 👍

**Comment by Light-Towers** [comment]
#5174   The same question

**Comment by Light-Towers** [comment]
use ${SEATUNNEL_HOME}/lib/hive-exec-2.3.9.jar  instead of  `hive-exec-3.1.3.jar`  is success

**Comment by jeanleen** [comment]
> use ${SEATUNNEL_HOME}/lib/hive-exec-2.3.9.jar instead of `hive-exec-3.1.3.jar` is success

but it till bring another bug, it may be imcompatible version about hive3 and hive-exec-2.3.9
`Caused by: java.io.InvalidClassException: org.apache.hadoop.hive.metastore.api.Table; local class incompatible: stream classdesc serialVersionUID = -8209215142020627313, local class serialVersionUID = -3348693286624209466`
