### ISSUE TITLE
[Feature][ZETA REST API] CAN submit job with rest api to Zeta master node automaticly

### ISSUE THREAD

**Issue by gitfortian** [apache/seatunnel#5862]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

now ,when i submit job with rest api to Zeta ,it return can not submit requst to inactive master node, CAN submit job with rest api to Zeta master node automaticly,Users do not need to worry about whether it is a master node

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
There may exist two solutions:
1. Provide API query the Master Node address.
2. Submit job to anynode in the cluster then the backend server will redirect the request to master.

**Comment by zhibinF** [comment]
Let me try to implement the second solution.
