### ISSUE TITLE
[Bug] [connector-file-base] Error "write data to orc file error" will happen in OrcWriteStrategy.class when sink table without partition column

### ISSUE THREAD

**Issue by SinyoWong** [apache/seatunnel#5863]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Error "write data to orc file error" will happen in OrcWriteStrategy.class when sink table without partition column

### SeaTunnel Version

seatunnel 2.3.3 +

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
      Hive {
        table_name = "order_analysis3"
        metastore_uri = "thrift://testIp:9083"
        kerberos_principal = "test@DATALAKE.COM"
        kerberos_keytab_path = "/home/tickets/t.kesteytab"
        hdfs_site_path = "/etc/hadoop/hdfs-site.xml"
        hive_site_path = "/etc/hive/hive-site.xml"
      }
}

sink {
    Hive{
        table_name = "order_analysis2"
        metastore_uri = "thrift://testIp:9083"
        kerberos_principal = "test@DATALAKE.COM"
        kerberos_keytab_path = "/home/tickets/test.keytab"
        hdfs_site_path = "/etc/hadoop/hdfs-site.xml"
        hive_site_path = "/etc/hive/hive-site.xml"
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink.sh --config config/example01.conf
```

### Error Exception

```log
Write data to orc file error, array[null] exception.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Please offer table schema information and hive version.
