### ISSUE TITLE
[Bug] [local deploy mode] Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found

### ISSUE THREAD

**Issue by codeDing18** [apache/seatunnel#5877]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I compile the seatunnel dev(2.3.4).When I run the command `bin/seatunnel.sh -c config/v2.batch.config.template -e local`,it have the problem.But I run successfully in 2.3.3

### SeaTunnel Version

dev(2.3.4)

### SeaTunnel Config

```conf
connectors/seatunnel have connector-fake-2.3.4-snapshot.jar and console
connectors/plugin-mapping.properties have connetor-fake and console
```

### Running Command

```shell
bin/seatunnel.sh -c config/v2.batch.config.template -e local
```

### Error Exception

```log
Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found
```

### Java or Scala Version

java8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liutianyuan** [comment]
请问解决了吗
