### ISSUE TITLE
[Bug] [Connector-v2][connector-common] Is `assert` used to control program flow?

### ISSUE THREAD

**Issue by CheneyYin** [apache/seatunnel#5902]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

https://github.com/apache/seatunnel/blob/6f49ec6ead82f842c6d93563ffce64853deb1bed/seatunnel-connectors-v2/connector-common/src/main/java/org/apache/seatunnel/connectors/seatunnel/common/source/reader/fetcher/SplitFetcher.java#L181-L201

Is `assert` used to control program flow? If so, then it will not work unless the JVM enables `-ea`.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
This is a defect. can you help improve it?

**Comment by CheneyYin** [comment]
> This is a defect. can you help improve it?

Please assign it to me
