### ISSUE TITLE
[OnlineMeeting&Nov.28] SeaTunnel community meeting Topic collection

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#5930]
### Description

Jia Fan invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel community meeting
Time: 2023/11/28 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/wNKoAkG7LtlE

#TencentMeeting: 218-331-685

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

**Comment by Hisoka-X** [comment]
#5620 and #5651

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/pull/5872
https://github.com/apache/seatunnel/issues/5677
