### ISSUE TITLE
HdfsFile sink not found save_mode

### ISSUE THREAD

**Issue by PenneyHuang** [apache/seatunnel#5946]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

save_mode not work

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
save_mode = "overwrite"
```

### Running Command

```shell
./start-seatunnel-spark-3-connector-v2.sh --config /home/module/apache-seatunnel-2.3.3/config/v2.spark_sqlserver_hdfs.conf
```

### Error Exception

```log
save_mode not work
```

### Zeta or Flink or Spark Version

spark 3.3.3

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi @PenneyHuang Can you provide more information, such as config?

**Comment by PenneyHuang** [comment]
sink {
  HdfsFile {
    source_table_name = "access1"
    hdfs_site_path = "/usr/hadoop/conf/hdfs-site.xml"
    fs.defaultFS = "hdfs://testcluster"
    path = "/warehouse/ods/ods__module__nd"
    custom_filename = true
    file_name_expression = "${transactionId}_${now}"
    filename_time_format = "yyyy-MM-dd-HH.mm.ss"
    file_format_type = "parquet"
    field_delimiter = "\\001"
    row_delimiter = "\n"
    compress_codec = "snappy"
    sink_columns = ["ID","Name"]
    is_enable_transaction = true
    save_mode="overwrite"
  }
}

Every time, a new file is generated instead of overwriting the files in the folder

**Comment by liunaijie** [comment]
hi @PenneyHuang. for now HDFS save_mode is not support. The support parameter you can refer this page: https://seatunnel.apache.org/docs/2.3.3/connector-v2/sink/HdfsFile

Save mode feature is track by this issue: https://github.com/apache/seatunnel/issues/5390.

**Comment by Carl-Zhou-CN** [comment]
Thanks @liunaijie, @PenneyHuang ,  closing this issue
