### ISSUE TITLE
[Bug] [seatunnel.engine.server.rest] The submit task rest API cannot adapt to changes in the master

### ISSUE THREAD

**Issue by letusgoH** [apache/seatunnel#5981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1. 当使用 /hazelcast/rest/maps/submit-job 提交任务时服务端抛出空指针，因为org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor#handleSubmitJob 111 行 jobId是必须得，与官方文档不符合。
![文档描述](https://github.com/apache/seatunnel/assets/153248029/f0630098-b935-4b95-b7d0-0e14576aaa1c)
2. /hazelcast/rest/maps/submit-job 接口无法自适应，master节点的变动，接口使用者无法感知到。会导致接口调用返回异常“"Please don't get coordinator service from an inactive master node”

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          storage.type: hdfs
          fs.defaultFS: hdfs://cdh1:8020 # Ensure that the directory                                                    has written permission
map:
    engine*:
       map-store:
         enabled: true
         initial-mode: EAGER
         factory-class-name: org.apache.seatunnel.engine.server.persi                                                   stence.FileMapStoreFactory
         properties:
           type: hdfs
           namespace: /tmp/seatunnel/imap
           clusterName: seatunnel-cluster
           storage.type: hdfs
           fs.defaultFS: file:///
```

### Running Command

```shell
http://192.xxx.xxx.201:5801/hazelcast/rest/maps/submit-job/?jobId=111111112

{"env":{"execution.parallelism":"2","job.mode":"BATCH","checkpoint.interval":"10000"},"source":[{"plugin_name":"Jdbc","url":"jdbc:mysql://192.xxx.xxx.202:3306/bigdata?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true","driver":"com.mysql.cj.jdbc.Driver","connection_check_timeout_sec":"100","user":"xxx","password":"xxx","query":"select * from user"}],"sink":[{"plugin_name":"HdfsFile","fs.defaultFS":"hdfs://192.xx.xx.xxx:8020","path":"/srv/data_universe/data_center/data_pool/DW_USER_DAY/2023-12-04/batch_xxxxx_from_mysql_1.txt","tmp_path":"/srv/data_universe/cluster_worker/tmp/seatunnel","file_format_type":"text","field_delimiter":"|"}]}
```

### Error Exception

```log
Please don't get coordinator service from an inactive master node
```

### Java or Scala Version

JDK 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
Hi @letusgoH 
the job id issue has fixed at https://github.com/apache/seatunnel/pull/5702
and submit in non master node is in this pr https://github.com/apache/seatunnel/pull/5950
