### ISSUE TITLE
[SeaTunnelClient] java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by yanhan-chan** [apache/seatunnel#6022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I am new to Apache SeaTunnel and I wanted to run SeaTunnel locally using the SeaTunnel Engine.

Below are the full exact steps that i have taken:
1. Download Java from Oracle JDK 11
2. Set JAVA_HOME
3. Download SeaTunnel 2.3.3 from --> https://www.apache.org/dyn/closer.lua/seatunnel/2.3.3/apache-seatunnel-2.3.3-bin.tar.gz
4. Move file into directory --> C:\Users\MyProfileName\Learn-Apache-SeaTunnel
5. Using Git bash to move into respective directory and executed --> tar -xzvf "apache-seatunnel-incubating-2.3.1-bin.tar.gz"
6. Using VSCode edited the config/plugin_config file to only remain the connector-fake, and connector-console
7. Executed --> sh bin/install-plugin.sh 2.3.1 in git bash
8. Using VSCode, edited the config/v2.batch.config.template file
9. Executed --> ./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local

I have tried running on docker, or using spark and got similar errors upon ClassNotFoundException.

### SeaTunnel Version

SeaTunnel Version 2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
1. To extract the downloaded files: tar -xzvf "apache-seatunnel-${version}-bin.tar.gz"
2. To install the plugins: sh bin/install-plugin.sh 2.3.3
3. To Run SeaTunnel Application: ./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
Error: Could not find or load main class org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
```

### Zeta or Flink or Spark Version

I am running it using the Zeta engine.

### Java or Scala Version

JDK 11
<img width="464" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/4ce6ac6e-aae1-47a2-ae09-fc78cfdfa228">

<img width="485" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/3a24f90a-f94e-40ed-87b7-62e708314747">

<img width="106" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/3a5dadcf-649d-4264-a1ed-9216a556ba72">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TARKII** [comment]
I've encountered the same error :( , have you solved this bug yet?

**Comment by TARKII** [comment]
Hi, I've encountered the same error :( , how did you solve this?

**Comment by 2gamayibuxulong** [comment]
same error

**Comment by TARKII** [comment]
https://blog.csdn.net/qq_36434219/article/details/134857560?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522171167441716800182729272%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=171167441716800182729272&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-2-134857560-null-null.142%5ev100%5epc_search_result_base1&utm_term=apache-seatunnel-2.3.3-SNAPSHOT-bin.tar.gz&spm=1018.2226.3001.4449
I followed this link and it worked, you may also check your /lib, different versions of .jars may cause this error.
