### ISSUE TITLE
[Feature][TIDB] TiDB Connector supports CDC or not.

### ISSUE THREAD

**Issue by CodeExplorer10** [apache/seatunnel#6031]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

TiDB Source Connector supports CDC or not.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi, @CodeExplorer10  not yet. Would you like to contribute to this?
