### ISSUE TITLE
[Bug] [connector-cdc-postgres] Table public.postgres_cdc_table_1 does not exist in Catalog Postgres

### ISSUE THREAD

**Issue by czb2021** [apache/seatunnel#6043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The following error occurs when testing postgres locally to the cdc of postgres. The configuration is as follows: plugins have been added in plugin-mapping.properties and pom.xml
Is it a configuration problem？
thanks
<img width="1280" alt="微信图片_20231219234630" src="https://github.com/apache/seatunnel/assets/135789126/a1b38eeb-e623-4493-8734-ce93947d3400">
In addition, the error of running Times on linux is different, please also help to check that the version of seatunnel in linux is 2.3.3
![微信截图_20231219234842](https://github.com/apache/seatunnel/assets/135789126/a466ae9a-be11-48c6-8cc5-dd9236e7d3d0)
![微信截图_20231219234913](https://github.com/apache/seatunnel/assets/135789126/0b1420a9-575a-4b0f-9471-39864f49f6cf)

### SeaTunnel Version

2.3.4-SNAPSHOT

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=400
}

source {
  Postgres-CDC {
    result_table_name = "customers_mysql_cdc"
    username = "postgres"
    password = "123456"
    database-names = ["postgres"]
    schema-names = ["inventory"]
    table-names = ["postgres.inventory.postgres_cdc_table_1"]
    base-url = "jdbc:postgresql://192.168.221.212:5432/postgres?loggerLevel=OFF"
  }
}

transform {

}

sink {
  jdbc {
    source_table_name = "customers_mysql_cdc"
    url = "jdbc:postgresql://192.168.221.212:5432/postgres?loggerLevel=OFF"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "123456"

    generate_sink_sql = true
    # You need to configure both database and table
    database = postgres
    table = inventory.sink_postgres_cdc_table_1
    primary_keys = ["id"]
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/postgrescdc_to_postgres.conf -e local
```

### Error Exception

```log
1.java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Postgres-CDC'} not found. 

2.org.apache.seatunnel.api.table.catalog.exception.TableNotExistException: ErrorCode:[API-05], ErrorDescription:[Table not existed] - Table public.postgres_cdc_table_1 does not exist in Catalog Postgres.
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
What version of the code are you using?

**Comment by czb2021** [comment]
> What version of the code are you using?

Use the code of your pg-cdc branch
![微信截图_20231225175715](https://github.com/apache/seatunnel/assets/135789126/65e392e1-8a81-4700-91f7-5c470e886b42)

**Comment by czb2021** [comment]
Is 2.3.4 going to be updated soon? Do you know if pg-cdc is supported and when？

**Comment by Carl-Zhou-CN** [comment]
> Is 2.3.4 going to be updated soon? Do you know if pg-cdc is supported and when？

Will be updated recently, pg cdc is in release planning,I updated the pg-cdc code so you can try it out and it is currently available, config may refer to `postgrescdc_to_postgres.conf` in e2e of PR

**Comment by Carl-Zhou-CN** [comment]
Using SeaTunnelEngineExample testing requires adding a dependency to the pom
![image](https://github.com/apache/seatunnel/assets/67902676/9a307f0b-b5f0-47a6-b9a6-d79ca1bc121d)
