### ISSUE TITLE
[OnlineMeeting&Dec.14] SeaTunnel community meeting Topic collection

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#6053]
hailin0 invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Community Meeting
Time: 2023/12/26 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/7lAWhuEujlx1

#腾讯会议：536-766-046

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

**Comment by hailin0** [comment]
Discuss review and code merge rules
cc @Hisoka-X @TyrantLucifer

**Comment by KangTomwk** [comment]
Could you please pay attention to this https://github.com/apache/seatunnel/issues/6053

**Comment by KangTomwk** [comment]
Could you please pay attention to this https://github.com/apache/seatunnel/issues/5700

**Comment by TyrantLucifer** [comment]
#4587

**Comment by TyrantLucifer** [comment]
Support metrics exporter.

**Comment by TyrantLucifer** [comment]
Support flink 17 18
