### ISSUE TITLE
[Feature][Connectors-v2-Paimon] Adaptation Paimon 0.6 Version

### ISSUE THREAD

**Issue by SimonChou12138** [apache/seatunnel#6058]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

paimon has now been updated to version 0.6, adding many new features and actually reaching production availability. Currently the bundle of seatunnel connectors for paimon uses 0.4, so I want to upgrade it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
It has been merged, closing issues
