### ISSUE TITLE
[Bug] [seatunnel web ] source name is empty

### ISSUE THREAD

**Issue by sunyaf** [apache/seatunnel#6073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/apache/seatunnel/assets/26950710/c79c4059-7257-4cb0-90bc-44e9df750d5f)
source name select list is empty

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
1.0
```

### Running Command

```shell
2023-12-25 14:55:04.255 seatunnel yunzhanghu-bj1154deMacBook-Pro WARN [tr:,sp:] [qtp1902499120-144] [SeatunnelPermissionServiceImpl.funcPermissionCheck():38] - func permission check in seatunnel
```

### Error Exception

```log
2023-12-25 14:55:04.255 seatunnel yunzhanghu-bj1154deMacBook-Pro WARN [tr:,sp:] [qtp1902499120-144] [SeatunnelPermissionServiceImpl.funcPermissionCheck():38] - func permission check in seatunnel
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pppeace** [comment]
same phenomenon.

**Comment by BobFang2023** [comment]
me too!

**Comment by BobFang2023** [comment]
> me too!

I tried adding SEATUNNEL_HOME to the environment variable and exported SEATUNNEL_HOME=/opt/apache-seatunnel-2.3, but there was still no data in the sub-database and sub-table mode.

**Comment by Hu-WF** [comment]
I have solved this problem:
Firstly, if you deploy SeaTunnel and SeaTunnel-Web on different nodes, when copying apache-seatunnel-2.3.3-bin.tar.gz as a client to the node where the SeaTunnel-Web service is located, you must ensure that the datasource is also in the client.
Then, it is necessary to configure the environment variable SEATUNNEL_ HOME, SEATUNNEL_ WEB_ HOME, ST_ WEB_ BASEDIR_ PATH in the SeaTunnel-Web service, as shown below：
![image](https://github.com/apache/seatunnel/assets/30825060/98e99f47-29d4-4988-a19d-3895f6af9111)
As follows：
![image](https://github.com/apache/seatunnel/assets/30825060/543b0fcc-7ff9-4331-a1f9-61dc60b92296)

Similar issues：https://github.com/apache/seatunnel/issues/6004

**Comment by czxin788** [comment]
I have the same issue, and don't resolve:
```
cat /etc/profile.d/seatunnel.sh 
export SEATUNNEL_HOME=/data0/seatunnel/apache-seatunnel
export SEATUNNEL_WEB_HOME=/data0/seatunnel/apache-seatunnel-web-1.0.0-bin
export ST_WEB_BASEDIR_PATH=/data0/seatunnel/apache-seatunnel-web-1.0.0-bin
export PATH=$SEATUNNEL_WEB_HOME/bin:$SEATUNNEL_HOME/bin:/usr/local/maven/bin/:$JAVA_HOME/bin:/usr/local/python3.6.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/mysql/bin
```

I don't know how to do .

Ii is too difficult
