### ISSUE TITLE
[Improve][Clickhouse File]Speed up in large number of data

### ISSUE THREAD

**Issue by zhanggougou** [apache/seatunnel#6091]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

My test data is 30KW, when data is all scp to ck node,the driver will cost many time to attach file
why not put attach in the exector?
so i move attach step into the exectutor
<img width="1320" alt="image" src="https://github.com/apache/seatunnel/assets/25924003/6c7b4536-32d7-462f-8119-7c503848547b">

### Usage Scenario

dataSize:30KW
before cost time: 100min+
after cost time: 60min

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi @zhanggougou  Looking forward to your PR

**Comment by zhanggougou** [comment]
> hi @zhanggougou Looking forward to your PR

Done
