### ISSUE TITLE
[Bug] [seatunnel engine] can not restore running jobs

### ISSUE THREAD

**Issue by bjdaijun** [apache/seatunnel#6105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I submit a streaming job, and after a while, kill local seatunnel server and restart seatunnel server, 
As I thought, seatunnel should restore the before running jobs, but the running jobs is empty after restart server.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ #
```

### Running Command

```shell
no
```

### Error Exception

```log
no error
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VincentSleepless** [comment]
try to delete files under /tmp/seatunnel/checkpoint_snapshot

**Comment by bjdaijun** [comment]
I tried to remove the checkout_snapshot, and restart the cluster. Then all the jobs terminated, and it didn't automatically restart the previous jobs. Maybe it doesn't have this feature.

But I can resubmit jobs with the same name and ID. It will resume working.
