### ISSUE TITLE
test

### ISSUE THREAD

**Issue by dream2zz** [apache/seatunnel#6107]
test

**Comment by fangshuaifeng** [comment]
hub.docker.com上有一个封装好的镜像，sounos/seatunnel-web:1.0.0，没有使用教程，部署启动后无法访问 :8801/ui/，可以交流下吗？
![QQ截图20231229093722](https://github.com/apache/seatunnel/assets/45835777/55fdd7db-daf2-4df8-b430-89c4313636a8)

**Comment by dream2zz** [comment]
这个组织的文章比技术好。
