### ISSUE TITLE
mysql 的 binlog 实时解析,没有看到,你们这个同步工具,有没有做mysql  binlog实时同步?

### ISSUE THREAD

**Issue by ithjz** [apache/seatunnel#613]
**1. Waterdrop Version(Waterdrop版本)**
2021年2月18号, 下载的waterdrop 源码,查看了没有涉及mysql binlog 相关的数据;

**2. 你希望增加什么功能？请尽可能详细描述**
mysql 的 binlog 实时解析,没有看到,你们这个同步工具,有没有做mysql  binlog实时同步? 请问实现了吗??

**3. 以上新功能的使用场景？**
mysql实时数据同步 ,mysql 实时同步到clickhouse的场景??
**4. Additional Context Information /  其他附加信息（如有）**

**Comment by garyelephant** [comment]
@ithjz 你好，目前还没有做，我们会记录此需求，后续会支持。
