### ISSUE TITLE
[Bug] mysql同步到clickhouse时，mysql删除一条数据，clickhouse里面自动添加一个数据，mysql修改一条数据，clickhouse里面添加了另个数据，一个是修改的原数据，一个是修改后的数据

### ISSUE THREAD

**Issue by 1790753131** [apache/seatunnel#6134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[mysql同步clickhouse不成功] # 
[mysql同步clckhouse不成功.docx](https://github.com/apache/seatunnel/files/13837019/mysql.clckhouse.docx)

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
        execution.parallelism = 1
        job.mode = "STREAMING"
        checkpoint.interval = 2000
}
source {
        MySQL-CDC {
        base-url = "jdbc:mysql://192.168.85.128:3307/gisqbpm"
        username = "root"
        password = "wxy123456"
        table-names = ["gisqbpm.test"]
   }
}
sink {
      Clickhouse {
                host = "192.168.85.128:8123"
                database = "gisqbpm"
                table = "test"
                username = "default"
                password = "wxy123456"
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mysqlcdctock.template -e local
```

### Error Exception

```log
修改和删除变成了新增
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VincentSleepless** [comment]
clickhouse的删除和更新性能还是比较弱的，即使连接器根据row kind实现了数据update/upsert/delete，也会有一定的性能问题。如果上游cdc是数据源，下游为啥不去接Doris/StarRock，这类库对update/upsert/delete是不是会友好一些

**Comment by Carl-Zhou-CN** [comment]
@1790753131 hi,  'primary_key = "id" support_upsert = true'  you need to add parameters related to cdc

**Comment by 1790753131** [comment]
@VincentSleepless  @Carl-Zhou-CN 感谢两位大佬指导， 'primary_key = "id" support_upsert = true' 这种方式试了删除可以了，但是修改还是存在问题，修改变成添加了，且发现执行过程中删除和修改容易导致系统挂掉！！！主要是这个方案领导敲定的，要实现主从同步，就不得不考虑更新和删除

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-clickhouse-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseSinkCDCChangelogIT.java#L115
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-clickhouse-e2e/src/test/resources/clickhouse_sink_cdc_changelog_case2.conf

Not reading the documentation?
https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/sink/Clickhouse.md#cdcchange-data-capture-sink
