### ISSUE TITLE
[Feature][Core] Support flink 17 and 18 version

### ISSUE THREAD

**Issue by TaoZex** [apache/seatunnel#6137]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We need support 17 and 18 version flink

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment]
Please assign to me. @TyrantLucifer Thanks.

**Comment by Carl-Zhou-CN** [comment]
@TaoZex hi, It's been assigned to you. I look forward to your contribution
