### ISSUE TITLE
严重怀疑mongo-cdc能上生产的可行性，一个string类型字段null,直接就报错Unable to convert to <STRING> from nullable value null，那这个mongo-cdc存在的意义是？

### ISSUE THREAD

**Issue by bulolo** [apache/seatunnel#6149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

```
source {
  MongoDB-CDC {
    hosts = "192.168.103.113:27011"
    database = ["pms-local"]
    collection = ["pms-local.demand_item_row"]
    username = root
    password = "XXX"
    schema = {
      fields {
        "_id" : string,
        "ras" : string,
        "planSn" : string,
      }
    }
  }
}
```
```
db.getCollection("demand_item_row").insert( {
    _id: ObjectId("64c8c053a0385c21b5b17872"),
    ras: "23127-AAT",
} );
```
随便来一个 string 类型的planSn字段是null ，就直接报错停止，这个CDC的意义何在？

并且2.3.3 无法设置无这个字段时的默认值

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  execution.checkpoint.interval = 5000
}

source {
  MongoDB-CDC {
    hosts = "192.168.103.113:27011"
    database = ["pms-local"]
    collection = ["pms-local.demand_item_row"]
    username = root
    password = "XXX"
    schema = {
      fields {
        "_id" : string,
        "ras" : string,
        "planSn" : string
      }
    }
  }
}


sink {
  jdbc {
    url = "jdbc:mysql://192.168.103.113:3306"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "XXX"
    generate_sink_sql = true
    database = test
    table = demand_item_row
    primary_keys = ["_id"]
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./example/mongo -e local
```

### Error Exception

```log
[Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Unable to convert to <STRING> from nullable value BsonNull](ception: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Unable to convert to <STRING> from nullable value null)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
@bulolo hi,It has been fixed in dev

**Comment by bulolo** [comment]
> @bulolo hi,It has been fixed in dev

请问dev分支要如何编译，还是有提供编译后的？

**Comment by hailin0** [comment]
> > @bulolo hi,It has been fixed in dev
> 
> 请问dev分支要如何编译，还是有提供编译后的？

./mvnw -T 1C clean package -pl seatunnel-dist -am -Dmaven.test.skip=true

**Comment by bulolo** [comment]
> > > @bulolo hi,It has been fixed in dev
> 
> > 
> 
> > 请问dev分支要如何编译，还是有提供编译后的？
> 
> 
> 
> ./mvnw -T 1C clean package -pl seatunnel-dist -am -Dmaven.test.skip=true

请问2.3.4什么时候发布？

**Comment by bulolo** [comment]
> @bulolo hi,It has been fixed in dev

麻烦关注一下这个，这个的修复引发了更严重的问题
https://github.com/apache/seatunnel/issues/6347
