### ISSUE TITLE
When is 2.3.4 released?

### ISSUE THREAD

**Issue by wu-a-ge** [apache/seatunnel#6150]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When is 2.3.4 released?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by inkkim** [comment]
Did you get answer from community?
