### ISSUE TITLE
[Feature][source] Oracle CDC streaming source

### ISSUE THREAD

**Issue by colagy** [apache/seatunnel#6156]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Oracle CDC streaming source

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/pull/5196
