### ISSUE TITLE
[Feature][source] Postgres CDC streaming source

### ISSUE THREAD

**Issue by Hu-WF** [apache/seatunnel#6158]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Postgres CDC streaming source

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2606090723** [comment]
你好  目前SeaTunnel自带引擎 是不是还没有 pgsql CDC的source呀

**Comment by Hu-WF** [comment]
> 你好 目前SeaTunnel自带引擎 是不是还没有 pgsql CDC的source呀

官方文档是这么说的
