### ISSUE TITLE
[E2e][Excel Source] Add e2e to test excel source read duplicate data

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#6159]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

test for https://github.com/apache/seatunnel/pull/5932

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hustxjs** [comment]
这个解决了吗，从excel抽数据到pg/mysql/ck，都会出现重复数据。
