### ISSUE TITLE
Missing map name

### ISSUE THREAD

**Issue by Tussy-gif** [apache/seatunnel#6163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

call the rest api
url   /hazelcast/rest/maps/stop-job
return 
{
    "status": "fail",
    "message": "Missing map name"
}

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/
```

### Running Command

```shell
call the rest api
url   /hazelcast/rest/maps/stop-job
```

### Error Exception

```log
{
    "status": "fail",
    "message": "Missing map name"
}
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dzygoon** [comment]
2.3.3 version unsupport stop-job api.try dev branch.

**Comment by Tussy-gif** [comment]
> 2.3.3 version unsupport stop-job api.try dev branch.

thanks
