### ISSUE TITLE
[Feature][doc] Add V2 connector jdbc document parameter can speed up data import

### ISSUE THREAD

**Issue by shuihua777** [apache/seatunnel#6167]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

`Option<Boolean> ENABLE_UPSERT =
            Options.key("enable_upsert")
                    .booleanType()
                    .defaultValue(true)
                    .withDescription("enable upsert by primary_keys exist");`
This parameter was found in the JdbcOptions interface of the source code, but it is not included in the official documentation
[https://seatunnel.apache.org/zh-CN/docs/2.3.3/connector-v2/source/Jdbc/](https://seatunnel.apache.org/zh-CN/docs/2.3.3/connector-v2/source/Jdbc/)

I tested that connecting to MySQL or Greenplum using jdbc and changing the default value of this parameter from true to false can accelerate the data import speed during the snapshot phase

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, and comments has been left in the PR comments area
