### ISSUE TITLE
[Bug] [Hive] Hive connector only support [text parquet orc] table now

### ISSUE THREAD

**Issue by notAprogrammer-0** [apache/seatunnel#6178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want to synchronize mysql data to hive, but something went wrong.
What does this question mean? How can I solve this?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  Jdbc {
    url = "jdbc:mysql://xxx:**/database_name"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = "root"
    password = "xxx"
    query = "select * from test_table limit 10"
  }
}

sink {
  Hive {
    table_name = "test_database.test_table"
    hdfs_site_path = "/opt/seatunnel/seatunnel-2.3.3/config/hdfs-site.xml"
    metastore_uri = "thrift://xxx:**,thrift://xxx:**"
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mysql-to-hive-test -e local
```

### Error Exception

```log
2024-01-10 17:27:46,734 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.hive.exception.HiveConnectorException: ErrorCode:[COMMON-06], ErrorDescription:[Illegal argument] - Hive connector only support [text parquet orc] table now
	at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.prepare(HiveSink.java:162)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSink(JobConfigParser.java:194)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSinks(JobConfigParser.java:166)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:534)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:190)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
	... 2 more
```

### Zeta or Flink or Spark Version

zata: 2.3.3

### Java or Scala Version

java version: 1.8
hive version: 3.1.0

### Screenshots

![image](https://github.com/apache/seatunnel/assets/66351499/f2f02d26-465d-406a-9030-25d6ee0082f3)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
as the exception said: now for hive table, we only support text, parquet, orc table format. if your table format is something else, you will get this exception. 
what's your table format?

**Comment by notAprogrammer-0** [comment]
> as the exception said: now for hive table, we only support text, parquet, orc table format. if your table format is something else, you will get this exception. what's your table format?

The table format is roughly like this. In order to prevent it from being too confusing, I deleted some repeated fields.

CREATE TABLE `test_table`  (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `GET_TIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除 0：未删除 1：已删除',
  `STARTDATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '开始时刻',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `idx_get_time`(`GET_TIME` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 26282 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

**Comment by liunaijie** [comment]
> > as the exception said: now for hive table, we only support text, parquet, orc table format. if your table format is something else, you will get this exception. what's your table format?
> 
> The table format is roughly like this. In order to prevent it from being too confusing, I deleted some repeated fields.
> 
> CREATE TABLE `test_table` ( `ID` bigint NOT NULL AUTO_INCREMENT, `GET_TIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL, `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除 0：未删除 1：已删除', `STARTDATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '开始时刻', PRIMARY KEY (`ID`) USING BTREE, INDEX `idx_get_time`(`GET_TIME` ASC) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 26282 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

this exception is write/sink error. you should check your hive table format instand of source mysql table.

**Comment by notAprogrammer-0** [comment]
> > > as the exception said: now for hive table, we only support text, parquet, orc table format. if your table format is something else, you will get this exception. what's your table format?
> > 
> > 
> > The table format is roughly like this. In order to prevent it from being too confusing, I deleted some repeated fields.
> > CREATE TABLE `test_table` ( `ID` bigint NOT NULL AUTO_INCREMENT, `GET_TIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL, `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除 0：未删除 1：已删除', `STARTDATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '开始时刻', PRIMARY KEY (`ID`) USING BTREE, INDEX `idx_get_time`(`GET_TIME` ASC) USING BTREE ) ENGINE = InnoDB AUTO_INCREMENT = 26282 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;
> 
> this exception is write/sink error. you should check your hive table format instand of source mysql table.

But i use a test like this config:
mysql:
```
CREATE TABLE test_hive(
	id INT,
	uname VARCHAR(20),
	gender VARCHAR(20)
);
```
hive:
```
CREATE external TABLE `cc2_l2_data.test_hive3`(  
  `id` int,   
  `uname` string,   
  `gender` string
);
```
And seatunnel config like:
```
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  Jdbc {
    url = "jdbc:mysql://xxx:**/df2cc-dev"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "password"
    query = "select * from test_hive"

  }
}

sink {
  Hive {
    table_name = "cc2_l2_data.test_hive3"
    hdfs_site_path = "/opt/seatunnel/seatunnel-2.3.3/config/hdfs-site.xml"
    metastore_uri = "thrift://xxx:**,thrift://xxx:**"
  }
}
```
It still occur this problem:
![image](https://github.com/apache/seatunnel/assets/66351499/3c13187f-16d5-4e5e-b617-9a386f2eff05)
