### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/runtime/state/StateBackend

### ISSUE THREAD

**Issue by zhaoysg** [apache/seatunnel#618]
waterdrop-2.0.2 源码启动时 出现以下报错大佬可以帮忙看一下吗
![微信图片_20210311182810](https://user-images.githubusercontent.com/39149223/110773321-92d46e00-8297-11eb-889d-cda1acc14232.png)

**Comment by garyelephant** [comment]
@zhaoysg 你好，请按照ISSUE模版提供必要信息，以帮助排查问题
