### ISSUE TITLE
[Bug] [SeaTunnel-Web] Bugs and maintenance plan for seatunnel-web（seatunnel-web的Bug反馈，以及了解维护计划）

### ISSUE THREAD

**Issue by Hu-WF** [apache/seatunnel#6197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel-web-1.0.0的Bug有点多，目前我知道的包括：
- 分页没有实现；
- 任务实例无法删除；
- 任务实例页面的刷新按钮无效；
- 创建虚拟表时，非空和主键无法分开设置；
- 任务运行时间不准。

并且令人担忧的是，seatunnel-web最近的一次fix bug记录是在2个月以前。想了解一下，是否官方已经不打算维护seatunnel-web项目了，还是说有其他的安排呢？
seatunnel-web项目还是有挺多亮点的，包括：
- 拖拽式创建任务，用户上手难度低；
- 虚拟表的概念；
- 任务的管理、状态监控等。

这些亮点个人认为对于seatunnel的推广使用还是很有帮助的，如果seatunnel-web项目放弃维护了还是挺可惜的

---
There are a lot of bugs in seatunnel-web-1.0.0, what I know includes:
- Paging not implemented;
- Task instances cannot be deleted;
- The refresh button on the task instance page is invalid;
- When creating a virtual table, non null and primary keys cannot be set separately;
- The task running time is not accurate.
And worrisome, the latest fix bug record on seatunnel-web was two months ago. I would like to know if the official is no longer planning to maintain the seasunnel web project, or if there are other arrangements?
There are quite a few highlights of the seatunnel web project, including:
- Drag and drop task creation, low difficulty for users to get started;
- The concept of virtual tables;
- Task management, status monitoring, etc.
I personally believe that these highlights are very helpful for the promotion and use of seasunnel. It would be a pity if the seasunnel web project were to abandon maintenance

### SeaTunnel Version

Web 1.0.0

### SeaTunnel Config

```conf
Pass
```

### Running Command

```shell
Pass
```

### Error Exception

```log
Pass
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GangLiCN** [comment]
web项目Bug确实太多了，如果不尽早修复，以后估计没人用了。。。
1.1版本(如果有的话) 建议不要增加任何新功能，把当前版本存在的问题能修复大部分就是成功。

**Comment by sxiongzhang** [comment]
> web项目Bug确实太多了，如果不尽早修复，以后估计没人用了。。。 1.1版本(如果有的话) 建议不要增加任何新功能，把当前版本存在的问题能修复大部分就是成功。

同意，一大堆问题好久都没修复更新
