### ISSUE TITLE
[Feature][Tool] Add connector check script

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#6199]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a new script, it can check which connector supported by now in `/connector` directory. Also support show connector option rule in shell command.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by manauwarcode** [comment]
Hi @Hisoka-X Can you please elaborate where do i have to write it ?

**Comment by manauwarcode** [comment]
Hi @Hisoka-X if you explain i can definitely write it

**Comment by Hisoka-X** [comment]
Thanks @manauwarcode  for your interest in this issue. Here are some QA which I hope can help you go on.
1. how to get all support connectors and how do get the connector option rule??
At now, we can get all support connectors and its option rule in `/connector` directory use https://github.com/apache/seatunnel/blob/101e14731cfad6a46fc58c80f6604a5ef16b2231/seatunnel-plugin-discovery/src/main/java/org/apache/seatunnel/plugin/discovery/AbstractPluginDiscovery.java#L239
we should return it and then display it in the console.
2. where the code be put in?
The new shell command should be in https://github.com/apache/seatunnel/tree/101e14731cfad6a46fc58c80f6604a5ef16b2231/seatunnel-core/seatunnel-starter/src/main/bin
The new command code should be in https://github.com/apache/seatunnel/tree/101e14731cfad6a46fc58c80f6604a5ef16b2231/seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command

**Comment by manauwarcode** [comment]
@Hisoka-X I have a doubt, when i see in the /connectors directory i have bunch of connector jar files, do i have to list these using command or something else, can you please elaborate what is the exact feature you wanted to add in details. Thank you!!

**Comment by Hisoka-X** [comment]
> @Hisoka-X I have a doubt, when i see in the /connectors directory i have bunch of connector jar files, do i have to list these using command or something else, can you please elaborate what is the exact feature you wanted to add in details. Thank you!!

The connector jar represents our currently supported connectors, but from the name of the connector jar we get very little information. The tool we developed can load these connectors through SPI and tell users which Sources/Transforms/Sinks are supported by the current connector, and the corresponding option rule.
Let call our new script `plugin-helper.sh`
eg: 
```shell
ls connectors/
connector-amazonsqs-2.3.4.jar            connector-cdc-postgres-2.3.4.jar    connector-file-local2.3.4jar

./bin/plugin-helper.sh -l
Source:
AmazonSqs Postgres-CDC LocalFile
Sink:
AmazonSqs LocalFile
Transform:
SQL Split

./bin/plugin-helper.sh -o LocalFile
....(show localfile option rule)
```

**Comment by manauwarcode** [comment]
Hi @Hisoka-X can you please explain even more, i am new to shell just finished the tutorials , wanted to help in open source contribution, hope you understand. Thank You!!

**Comment by Hisoka-X** [comment]
> Hi @Hisoka-X can you please explain even more, i am new to shell just finished the tutorials , wanted to help in open source contribution, hope you understand. Thank You!!

Which part?

**Comment by manauwarcode** [comment]
Hi @Hisoka-X how do we find source sink and transform and explain LocalFile as well. Thank you!!

**Comment by Hisoka-X** [comment]
> Hi @Hisoka-X how do we find source sink and transform and explain LocalFile as well. Thank you!!

In principle, by searching for Java's SPI interface implementation, find the corresponding connector factory, and then call the corresponding method to obtain the option rule. Like
https://github.com/apache/seatunnel/blob/5c917bcefecda6397fb82440369c83088c4e7cc6/seatunnel-connectors-v2/connector-file/connector-file-local/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/local/source/LocalFileSourceFactory.java#L38

From a practical perspective, we only need to call the corresponding method of the Factory to get all the information we need (the logic of searching through SPI has been encapsulated), and then display it. 
https://github.com/apache/seatunnel/blob/101e14731cfad6a46fc58c80f6604a5ef16b2231/seatunnel-plugin-discovery/src/main/java/org/apache/seatunnel/plugin/discovery/AbstractPluginDiscovery.java#L239

**Comment by dailai** [comment]
@Hisoka-X Please assign it to me, I'll try it.
