### ISSUE TITLE
[Feature][web] 安装手册简单点

### ISSUE THREAD

**Issue by lliuql** [apache/seatunnel#6204]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

感谢团队的开源，但是我还是想指出一点，就是文档写的异常的不清楚。如果想让产品更好的推广的话，清晰的文档是很有必要的。希望在写文档的兄弟们，能站在没有使用过本项目的人来写。我再使用的过程中，发现web手册真的是很难看明白，又是idea又是服务器的。web项目应该改ide工具没关系把。还有配置文件还需要拷贝来拷贝去的。真的很难让人部署起来使用。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CoderXionghs** [comment]
同感啊

**Comment by czxin788** [comment]
seatunnel web，我都部署 一周了，还没部署起来，似乎是jar下载的不对

**Comment by GangLiCN** [comment]
web项目一堆bug, 我已经放弃了。。。

文档确实需要大幅加强，例如 每种数据同步场景 起码要有一个完整的例子，包括配置文件怎么写，
常见的错误汇总，这样一来就算是初学者也能快速入门。

**Comment by GangLiCN** [comment]
> seatunnel web，我都部署 一周了，还没部署起来，似乎是jar下载的不对

我已经部署成功了，也可以登录了，但是 基本的功能到处是bug,  真没法用，还是用命令行的方式稍微靠谱一点。

**Comment by czxin788** [comment]
> > seatunnel web，我都部署 一周了，还没部署起来，似乎是jar下载的不对
> 
> 我已经部署成功了，也可以登录了，但是 基本的功能到处是bug, 真没法用，还是用命令行的方式稍微靠谱一点。

我现在也能登录了，但是数据库源那选不了，是空，我其实已经建立数据源了。
你遇到了什么问题

**Comment by xi-xi-jun** [comment]
@GangLiCN 老哥，我部署也可以进入界面了，但是数据库源那选不了，空的，同问是怎么解决的呢？

**Comment by GangLiCN** [comment]
> @GangLiCN 老哥，我部署也可以进入界面了，但是数据库源那选不了，空的，同问是怎么解决的呢？

这个问题 我也遇到过，后来解决了。
1) 首先要把datasource目录下那一堆jar文件复制到libs目录;
2) 有一个hive的jar包跟Springboot冲突，不要复制这个包。

**Comment by GangLiCN** [comment]
> @GangLiCN 老哥，我部署也可以进入界面了，但是数据库源那选不了，空的，同问是怎么解决的呢？

这个问题 我也遇到过，后来解决了。

首先要把datasource目录下那一堆jar文件复制到libs目录;
有一个hive的jar包跟Springboot冲突，不要复制这个包。

我的问题是
1) 没法创建数据同步任务，编辑界面是乱的，啥都用不了；
2) 有一些数据库的数据源没法添加，比如Mysql8的，后台抛出错误，但是用mysql客户端或者JAVA应用程序去连数据库都没问题。

**Comment by GangLiCN** [comment]
我的建议是： 在这一堆bug没有修复前，还是别用web了，浪费时间。 用命令行提交作业吧。

**Comment by GangLiCN** [comment]
> > > seatunnel web，我都部署 一周了，还没部署起来，似乎是jar下载的不对
> > 
> > 
> > 我已经部署成功了，也可以登录了，但是 基本的功能到处是bug, 真没法用，还是用命令行的方式稍微靠谱一点。
> 
> 我现在也能登录了，但是数据库源那选不了，是空，我其实已经建立数据源了。 你遇到了什么问题

建库脚本你执行了没有？ seatunnel这个数据库和下面的表建好了没有？

**Comment by dujiaoxi404** [comment]
确实挺粗略的，我是源码启动的方式，搞了几天现在能用local模式debug跑job了。但命令行+有网的linux环境部署个demo还挺简单的。现在再找如何同步整个库，而不是table-names指定表，看上去是不支持，得自己写代码

**Comment by dujiaoxi404** [comment]
mvn spotless:apply

**Comment by tchivs** [comment]
是的，太简陋了，而且web也部署不起来，还是以后再用吧
