### ISSUE TITLE
[Bug] [Install Connector Shell]2.3.3 Version used "install-plugin.sh" download Connector has error

### ISSUE THREAD

**Issue by dzygoon** [apache/seatunnel#6219]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When you use the install_plugin.sh script in the bin/ directory of version 2.3.3 to download plug-ins and connectors, it is found that the connector-file-oss-jindo.jar version 2.3.3 is not available.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
sh bin/install-plugin.sh
```

### Error Exception

```log
not has 2.3.3 version connector-file-oss-jindo.jar
```

### Java or Scala Version

jdk 1.8

### Screenshots

![5aee6e379f7170fd911acbd39581e64](https://github.com/apache/seatunnel/assets/96854451/738a4b79-52bf-4333-909f-d57efe9393f4)
![image](https://github.com/apache/seatunnel/assets/96854451/2b863dd1-2580-4e05-a103-bd016d0f3cba)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GangLiCN** [comment]
类似的问题出现在MongoDB这个jar,  因为Maven中央仓库也没有2.3.3版本的jar。

**Comment by dzygoon** [comment]
> 类似的问题出现在MongoDB这个jar, 因为Maven中央仓库也没有2.3.3版本的jar。

这个我倒是没发现.

**Comment by wbbcx** [comment]
I have  met the same error.
