### ISSUE TITLE
[Bug] [seatunnel-web] 整库-多表同步无法选择数据源

### ISSUE THREAD

**Issue by cooltnt** [apache/seatunnel#6233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

集成方式经过折腾, 能够选择数据源, 并且也成功完成同步任务.

但是整库方式, 这个数据源, 怎么弄的不行, 是缺少哪些jar包吗?  还是有其他目录要放?

![image](https://github.com/apache/seatunnel/assets/41370387/dc2b8390-2712-4ff6-b635-923ea1e08061)

### SeaTunnel Version

seatunnel 2.33
web 1.0.0

### SeaTunnel Config

```conf
已在 apache-seatunnel-2.3.3/lib/
apache-seatunnel-2.3.3/connectors/seatunnel/
apache-seatunnel-web-1.0.0/libs/
中放入相同的datasource相关jar包

connector-console-2.3.3.jar
connector-fake-2.3.3.jar
connector-jdbc-2.3.3.jar
datasource-elasticsearch-1.0.0.jar
datasource-hive-1.0.0.jar
datasource-jdbc-clickhouse-1.0.0.jar
datasource-jdbc-hive-1.0.0.jar
datasource-jdbc-mysql-1.0.0.jar
datasource-jdbc-oracle-1.0.0.jar
datasource-jdbc-postgresql-1.0.0.jar
datasource-jdbc-redshift-1.0.0.jar
datasource-jdbc-sqlserver-1.0.0.jar
datasource-jdbc-starrocks-1.0.0.jar
datasource-jdbc-tidb-1.0.0.jar
datasource-kafka-1.0.0.jar
datasource-mysql-cdc-1.0.0.jar
datasource-plugins-api-1.0.0.jar
datasource-s3-1.0.0.jar
datasource-sqlserver-cdc-1.0.0.jar
datasource-starrocks-1.0.0.jar
mysql-connector-j-8.0.33.jar
mysql-connector-java-5.1.49.jar1111
postgresql-42.7.1.jar
seatunnel-hadoop3-3.1.4-uber-2.3.3-optional.jar
```

### Running Command

```shell
server:
nohup sh bin/seatunnel-cluster.sh 2>&1 &

web:
sh ./bin/seatunnel-backend-daemon.sh start
```

### Error Exception

```log
无error信息, 只有几个警告
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cooltnt** [comment]
不好意思, 没有注意置顶信息

**Comment by czxin788** [comment]
解决了吗，怎么解决的，我也遇到数据源是空的问题

**Comment by cooltnt** [comment]
> 解决了吗，怎么解决的，我也遇到数据源是空的问题

我这个问题是选择整库模式下, 无法选择源, 这个好像目前不支持.

如果是集成方式下无法选择源的话, 请到 https://mvnrepository.com/search?q=org.apache.seatunnel 下载
以下jar :
  "datasource-plugins-api"
  "datasource-elasticsearch"
  "datasource-hive"
  "datasource-jdbc-clickhouse"
  "datasource-jdbc-hive"
  "datasource-jdbc-mysql"
  "datasource-jdbc-oracle"
  "datasource-jdbc-postgresql"
  "datasource-jdbc-redshift"
  "datasource-jdbc-sqlserver"
  "datasource-jdbc-starrocks"
  "datasource-jdbc-tidb"
  "datasource-kafka"
  "datasource-mysql-cdc"
  "datasource-s3"
  "datasource-sqlserver-cdc"
  "datasource-starrocks"
  "datasource-mongodb"
 放入${seatunnel_web_path}/libs ,   ${seatunnel_path}/lib,    ${seatunnel_path}//connectors/seatunnel    这几个目录

**Comment by Osolosooo** [comment]
> 解决了吗，怎么解决的，我也遇到数据源是空的问题

我这边ok了可以参考：https://juejin.cn/post/7353193850456948770

**Comment by Osolosooo** [comment]
多表同步的应该是没有创建cdc的数据源，创建个数据源就好了
![image](https://github.com/apache/seatunnel/assets/30710888/9e765994-83e0-44c4-9b48-8d71a09efd36)

![image](https://github.com/apache/seatunnel/assets/30710888/9f9b6699-0e99-457a-ab9e-694cf8197428)
