### ISSUE TITLE
[Bug] [CheckPoint] Checkpoints were not deleted

### ISSUE THREAD

**Issue by W-dragan** [apache/seatunnel#6238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I ran the seatunnel task, I found that the checkpoints file continued to grow, and even after the task was completed, it was not deleted
![image](https://github.com/apache/seatunnel/assets/69575498/7ad454bc-3dec-4fcc-9b9f-54a77875e0dc)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
any config
```

### Running Command

```shell
./seatunnel-cluster.sh -d
```

### Error Exception

```log
org.apache.seatunnel.engine.server.checkpoint.CheckpointManager#shutdown is only used in unitTest. 
In the previous version 2.3.1, this interface was called to delete checkpoints, but currently there is no call. It is uncertain whether the refactoring was missed or a new strategy was used. However, the current phenomenon is that checkpoints were not deleted, resulting in continuous file growth
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
cc @EricJoy2048
