### ISSUE TITLE
ck的写入为什么不按顺序写入而是使用map？

### ISSUE THREAD

**Issue by ganlingithub** [apache/seatunnel#624]
**Waterdrop Version(Waterdrop版本)**

A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by garyelephant** [comment]
@RickyHuo 请帮忙看看这个问题

**Comment by RickyHuo** [comment]
@ganlingithub  麻烦详细描述下问题
