### ISSUE TITLE
代码疑问：CK批量写入代码为什么每次批量写入后就关闭了statement ？

### ISSUE THREAD

**Issue by baoyubobo** [apache/seatunnel#625]
类： io.github.interestinglab.waterdrop.output.batch.Clickhouse

方法：private def execute(statement: ClickHousePreparedStatement, retry: Int)

为什么上述方法中 statement.executeBatch() 执行成功后，就执行 statement.close() 关闭了该statement对象？
该方法在代码中有多调用，如果第一次执行就关闭掉statement，那么后续执行会报错呀？

![image](https://user-images.githubusercontent.com/19707063/116840349-10698a00-ac08-11eb-99b7-f2eaab427bba.png)

麻烦解答一下我的疑问！  
谢谢！

**Comment by garyelephant** [comment]
@RickyHuo 请帮忙看看这个问题。

**Comment by RickyHuo** [comment]
@baoyubobo https://github.com/InterestingLab/waterdrop/blob/master/waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Clickhouse.scala#L181 每一个batch都会创建一个statement

**Comment by baoyubobo** [comment]
@RickyHuo   感谢上面的回答！ 

但是还是有疑问：
https://github.com/InterestingLab/waterdrop/blob/b92018f56dadfc7de180eab33dca9a8b3450524a/waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Clickhouse.scala#L183-L193

181 行创建一个statement， 下面while循环中 的execute(statement, retry)可能执行多次。 第一次循环execute执行后statement就关闭了，那么第二次执行再执行statement时，由于statement已经关闭了，就会报错
