### ISSUE TITLE
[Bug] [seatunnel-web] 2024-01-19 11:07:30.955 seatunnel XXX-LAPTOP INFO [qtp82328216-16] [AuthenticationInterceptor.preHandle():70] - user does not exist

### ISSUE THREAD

**Issue by gguo** [apache/seatunnel#6253]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Based on the deployment guide of seatunnel web https://seatunnel.apache.org/zh-CN/seatunnel_web/1.0.0/deploy, I could run seatunnel server and seatunnel web. When I accessed the url: http://[localhost:8801/ui](http://localhost:8801/ui), I always got "There was an unexpected error (type=Not Found, status=404)."。And in the log file, it always show the info "user does not exist". I didn't do any logon operation. It's weird.

### SeaTunnel Version

seatunnel 2.3.3
seatunnel web 1.0.0

### SeaTunnel Config

```conf
application.yml (seatunnel web):
server:
  port: 8801

spring:
  application:
    name: seatunnel
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.194.29:3306/seatunnel?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  expireTime: 86400
  secretKey: https://github.com/apache/seatunnel
  algorithm: HS256
```

### Running Command

```shell
sh seatunnel-backend-daemon.sh start
```

### Error Exception

```log
2024-01-19 11:07:02.110 seatunnel GILGUO-LAPTOP INFO [main] [CachingOperationNameGenerator.startingWith():40] - Generating unique operation named: listSourceUsingGET_1
2024-01-19 11:07:02.114 seatunnel GILGUO-LAPTOP INFO [main] [CachingOperationNameGenerator.startingWith():40] - Generating unique operation named: syncUsingGET_1
2024-01-19 11:07:02.196 seatunnel GILGUO-LAPTOP INFO [main] [CachingOperationNameGenerator.startingWith():40] - Generating unique operation named: getJobDefinitionUsingGET_1
2024-01-19 11:07:02.695 seatunnel GILGUO-LAPTOP INFO [main] [StartupInfoLogger.logStarted():61] - Started SeatunnelApplication in 7.265 seconds (JVM running for 7.542)
2024-01-19 11:07:30.955 seatunnel GILGUO-LAPTOP INFO [qtp82328216-16] [AuthenticationInterceptor.preHandle():70] - user does not exist
```

### Java or Scala Version

JDK_1.8

### Screenshots

<img width="611" alt="web" src="https://github.com/apache/seatunnel/assets/1058182/3770dc8a-f217-476e-b605-d50c714ff262">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CoderXionghs** [comment]
这个问题我也遇到过好几次，要重启seatunnel-web后，才好，感觉这玩意太不稳定了。就是个kpi产物

**Comment by czxin788** [comment]
我也遇到这个问题了，重启也不好使，
sh bin/seatunnel-backend-daemon.sh start 也不好使

**Comment by czxin788** [comment]
I known 
http://ip:8801/ui/index.html

can successful

**Comment by gguo** [comment]
It cannot work with http://ip:8801/ui/index.html
![image](https://github.com/apache/seatunnel/assets/1058182/9dd66ee8-8459-4127-ac10-b4fcac9667f2)

**Comment by czxin788** [comment]
I think deploy apache seatunnel web is very difficult.

**Comment by feiyuthomas** [comment]
start web     不要再bin目录下启动  

sh ./bin/seatunnel-backend-daemon.sh start

**Comment by YuqiZhuSH** [comment]
try like this
http://localhost:8801/ui/index.html#/login
