### ISSUE TITLE
[Doc Bug] [Doc Error]

### ISSUE THREAD

**Issue by dzygoon** [apache/seatunnel#6255]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In the official document version 2.3.3,checkpoint-storage config.When the hdfs is ha,The example configuration is misspelled,`seatunnel.hadoop.dfs.client.failover.proxy.provider.usdp-bing` Its value has an extra double quotation mark.

### SeaTunnel Version

2.3.3 doc

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
doc error.
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/96854451/6f375556-63e6-4dee-9e6c-e89ff61be970)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Can you submit a PR to fix this issue?

**Comment by dzygoon** [comment]
> 您可以提交 PR 来解决这个问题吗？

Sure,But i dont know how can do it.I will learn and fix it.

**Comment by liugddx** [comment]
> > 您可以提交 PR 来解决这个问题吗？
> 
> Sure,But i dont know how can do it.I will learn and fix it.
You can refer to https://seatunnel.apache.org/community/contribution_guide/contribute

**Comment by dzygoon** [comment]
> > > 您可以提交 PR 来解决这个问题吗？
> > 
> > 
> > Sure,But i dont know how can do it.I will learn and fix it.
> > You can refer to https://seatunnel.apache.org/community/contribution_guide/contribute

ok

**Comment by dzygoon** [comment]
fix is here: https://github.com/apache/seatunnel/pull/5883 @michalrys
