### ISSUE TITLE
[Feature][Elasticsearch] sink supported elasticsearch8.x ?

### ISSUE THREAD

**Issue by laizuan** [apache/seatunnel#6267]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hi. SeaTunnel team. 

Our team is evaluating excellent seatunnel projects and we have noticed that `sink -> elasticsearch` has this description
> supported ElasticSearch version is >= 2.x and <= 8.x

Is it ready to support elastic8.x now?

Looking forward to your reply, thanks.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laizuan** [comment]
Also, does mysql cdc support multiple tables sink into the same index?

**Comment by iture123** [comment]
Is it ready to support elastic8.x now?
Yes,It do.
