### ISSUE TITLE
sink为clickhouse，插入到clickhouse后，字段对应的数据不一致

### ISSUE THREAD

**Issue by Seapein** [apache/seatunnel#6274]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source为mysql,sink为clickhouse时，使用FieldMapper,如果mysql与clickhouse的表字段顺序不同，插入到clickhouse后，字段对应的数据会不一致。
![89158b637a3adb5fe4d324a04cc8cf8](https://github.com/apache/seatunnel/assets/37824176/75680929-7c19-4e79-833c-8f7a33f058b9)

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
"job.mode"=BATCH
"job.name"="SeaTunnel_Job"
}
source {
Jdbc {
    "connection_check_timeout_sec"=30
    parallelism=1
    "result_table_name"=Table12372182520352
    query="SELECT `id`, `code`, `name` FROM `admin_langfang`.`depttt`"
    driver="com.mysql.cj.jdbc.Driver"
    password="123456"
    url="jdbc:mysql://192.168.1.191:3306/seatunnel?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    user=root
}
}
transform {
FieldMapper {
    "result_table_name"=Table12372182520353
    "source_table_name"=Table12372182520352
    "field_mapper" {
        id=id
        code=code
        name=name
    }
}
}
sink {
Clickhouse {
    username=default
    password="keli@1991"
    "clickhouse.config" {}
    "bulk_size"=20000
    "split_mode"="false"
    "support_upsert"="false"
    "allow_experimental_lightweight_delete"="false"
    "source_table_name"=Table12372182520353
    database="inside_data"
    table="depe_test"
    host="192.168.1.207:8123"
    url="jdbc:clickhouse://192.168.1.207:8123/inside_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&connectTimeout=300000&socketTimeout=300000"
    driver="ru.yandex.clickhouse.ClickHouseDriver"
    user=default
}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/test.template
```

### Error Exception

```log
no error
```

### Zeta or Flink or Spark Version

使用zeta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Seapein** [comment]
![4d6117437dc3d319db8bfb835f0249d](https://github.com/apache/seatunnel/assets/37824176/c3b9d4b5-1d7b-431a-ab01-fd5460caf24b)
mysql数据源截图

**Comment by liugddx** [comment]
Change field mappings . Refer to https://seatunnel.apache.org/docs/2.3.3/transform-v2/sql

**Comment by Seapein** [comment]
> Change field mappings . Refer to https://seatunnel.apache.org/docs/2.3.3/transform-v2/sql

Hi,I have tried this method before, but it did not take effect：
transform {
Sql {
   "result_table_name"=Table12372182520353
    "source_table_name"=Table12372182520352
    query = "select id as id, code as code, name as name from Table12372182520352 "
  }
}

**Comment by liugddx** [comment]
Try to adjust the following order.

**Comment by Seapein** [comment]
> Try to adjust the following order.

hi，what order?

**Comment by liugddx** [comment]
transform {
Sql {
"result_table_name"=Table12372182520353
"source_table_name"=Table12372182520352
query = "select id as id,  name as name,code as code from Table12372182520352 "
}
}

**Comment by Seapein** [comment]
> transform { Sql { "result_table_name"=Table12372182520353 "source_table_name"=Table12372182520352 query = "select id as id, name as name,code as code from Table12372182520352 " } }

Thank you very much for solving my problem！
