### ISSUE TITLE
[Bug] [doc] hotfix ci dead link

### ISSUE THREAD

**Issue by 531651225** [apache/seatunnel#6279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

ci checked dead link

### SeaTunnel Version

2.1

### SeaTunnel Config

```conf
xxx
```

### Running Command

```shell
xxx
```

### Error Exception

```log
xx
```

### Zeta or Flink or Spark Version

xx

### Screenshots

![image](https://github.com/apache/seatunnel/assets/33744252/637aaa8d-4b1a-4090-a4ab-2f8d469bf4c8)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CheneyYin** [comment]
related:
- #6015
- #6016
