### ISSUE TITLE
如何自定义的plugin在yarn模式下在代码中获取plugin的files文件?

### ISSUE THREAD

**Issue by kaijianding** [apache/seatunnel#629]
**Waterdrop Version(Waterdrop版本)**

A clear version of Waterdrop. 
1.5.1
**Flink or Spark Version(Flink 或者 Spark 版本)**
2.4

如何自定义的plugin在yarn模式下在代码中获取plugin的files文件? 在https://github.com/InterestingLab/waterdrop/issues/267 中没找到对应的说明

按照文档已经把插件的files按照目录格式放入了plugins.tar.gz  
在executor里如何拿到plugins.tar.gz里的内容? 在new File(".")下面没找到解压后的plugins目录
```java

      df.foreachPartition(new ForeachPartitionFunction<Row>()
      {
        @Override
        public void call(Iterator<Row> rows) throws Exception
        {
          File[] files = new File(".").listFiles();
          for (File f : files) {
            log().info(f.getAbsolutePath());
            if (f.isDirectory()) {
              if ("__spark_libs__".equals(f.getName())) {
                continue;
              }
              for (File f2 : f.listFiles()) {
                log().info(f2.getAbsolutePath());
              }
           }
          }
        }
      }
```

输出如下
`

/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/tmp
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/tmp/liblz4-java1903200695783061477.so
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/tmp/1622628782975-0
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/launch_container.sh
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/container_tokens
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/plugins.tar.gz
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/__spark_libs__
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/__app__.jar
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/waterdrop_conf.conf
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/rm-audit.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/stateChange.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/mapred-audit.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/clienttrace.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/hdfs-audit.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/top.log
/data11/hadoopdata/nodemanager/local/usercache/dingkaijian/appcache/application_1618385933965_29227511/container_e23_1618385933965_29227511_01_000037/hadoop-mapreduce.jobsummary.log
`

可以看到plugins.tar.gz并没有解压, 所以也拿不到里面的内容(除非自己在plugin里主动解压).

这是我所用到的命令
```shell
spark-submit \
--class io.github.interestinglab.waterdrop.Waterdrop \
--name Waterdrop \
--conf spark.sql.catalogImplementation=hive \
--conf spark.executor.heartbeatInterval=60s \
--conf spark.driver.memory=10G \
--conf spark.executor.memory=1g \
--conf spark.executor.cores=1 \
--files plugins.tar.gz,waterdrop_conf.conf \
--jars myplugin-1.0.jar \
Waterdrop-1.5.1-2.11.8.jar \
"-m" "yarn" \
"-e" "cluster" \
"--config" "waterdrop_conf.conf"

```

**Comment by garyelephant** [comment]
你好，请参考这个：https://github.com/InterestingLab/waterdrop/blob/master/waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Grok.scala#L47

需要用到的API是：Common.pluginFilesDir()

**Comment by kaijianding** [comment]
例子里的Common.pluginFilesDir()是在prepare方法里调用的, 但我是在df.foreachPartition({...})里用这个plugin的目录, 但在prepare里获取到的plugin的地址, 在foreachPartition里用的时候, 事实上这个目录并不存在. 应该是因为foreachPartition里是在executor里执行的, prepare是在driver本地执行的.

@garyelephant 我是想要在foreachPartition里访问plugin的目录

**Comment by garyelephant** [comment]
@kaijianding foreachPartition里面应该也可以用的，文件会被上传到executor上。
