### ISSUE TITLE
[QUESION] 特定情况下报字段不存在

### ISSUE THREAD

**Issue by KnightChess** [apache/seatunnel#630]
https://github.com/InterestingLab/waterdrop/blob/ba17135e00fbfcfec7183a42c6ee5aa9a2fe8814/waterdrop-spark-api/src/main/scala/io/github/interestinglab/waterdrop/spark/batch/SparkBatchExecution.scala#L30-L48

[branch] wd-v2-bashline
- 场景如下：
source hive表有个 task_id 字典，对应 sink mysql 表的 activity_id 字段，别名替换在 transform 操作中 select task_id as activity_id from xxx. 
- 问题描述：
报错，标识 sink 表中没有 task_id  的字段，原因：hive 表里没有数据，导致上面的代码 ds.take(1) 长度没法大于 0，然后就没有走 transform 的逻辑惹，无法别名。
- 疑问：
这里 take 的用意是啥，如果多个 source 的话，第一个 source 没有数据，但是其它 source 有数据的话，存在场景是需要继续同步其它的数据并清洗的。比如分库分表的数据同步（只是举个不同 source schema 相同的场景），然后 transform 处理 union all，继续 sink 到目标表。但是如果首个 source 没有数据，ds.take(1) 就为 false 了，剩下的 source 没有同步，如果有别名的情况，甚至会直接报错。

**Comment by RickyHuo** [comment]
@KnightChess  take 是为了做非空判断， 就是为了避免空souce导致处理逻辑报错，例如以下的配置


```
source {
   mysql {
     result_table_name = 'xxx'
  }
}

filter {
  sql {
    sql = "select field from xxx"
  } 
}

....
```

你说的多souce的情况的确存在，这里有个取舍， 我们也考虑一下怎么兼容你说的场景。

**Comment by RickyHuo** [comment]
@KnightChess 目前只有第一个source会有这个判断， 尽量保证第一个source非空
