### ISSUE TITLE
[Bug] [JDBC] Connection leak when exception occurs

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#6308]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 [JDBC] Connection leak when exception occurs
![image](https://github.com/apache/seatunnel/assets/14371345/ddfd658f-e5f1-4305-8389-8328a3badad2)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by happyboy1024** [comment]
please assign me

**Comment by happyboy1024** [comment]
The new multi-table write feature changes the way connections are managed, and the connection leak issue has been resolved in the `dev` branch.
