### ISSUE TITLE
When is releasing v2.3.4?

### ISSUE THREAD

**Issue by xinfeingxia85** [apache/seatunnel#6320]
I am using the SQL transform feature, but there seems to be a bug with the cast function when it converts from int to timestamp.
I've been waiting for this bug to be fixed and I hope a new version can be released as soon as possible.

**Comment by xinfeingxia85** [comment]
@Carl-Zhou-CN

**Comment by cqutwangyu** [comment]
I see that the 2.3.4-release branch has been created, maybe you can pull over to this branch and build the seatunnel application for version 2.3.4

**Comment by Carl-Zhou-CN** [comment]
hi @xinfeingxia85  Keep an eye on the dev mailing list, 2.3.4 is already in the voting process
