### ISSUE TITLE
[Feature][Seatunnel Source] localfile source needs quoteChar option

### ISSUE THREAD

**Issue by terry-xu-2021** [apache/seatunnel#6321]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Localfile source has option delimiter, tell connector how to slice field, but there is no quoteChar option as Hive serde.  Field data may be wrapped in double quotes，but two-side double quotes not part of data.

### Usage Scenario

localfile like this：
"id","name","message"
"1","hello world", "I have a dream"
Seatunnel loaded data include double quotes too. double quotes become part of data. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WuJiY** [comment]
same too. 
It will be split an new row when the column has the line feed.
