### ISSUE TITLE
[Feature][connector-v2]  Support append or overwrite operations of hive table in seatunnel 2.3.3

### ISSUE THREAD

**Issue by BookTraceless** [apache/seatunnel#6351]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I want to implement append or overwrite operation of hive table

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Liugh2020** [comment]
+1

**Comment by frankiewen** [comment]
+1

**Comment by jianJizz** [comment]
+1

**Comment by jianJizz** [comment]
为啥sink hdfs，hive都没有ovewrite的参数，对于分区表这太痛苦了
