### ISSUE TITLE
[Feature][connector] How to compile the specified connectors from the source code?

### ISSUE THREAD

**Issue by zhangm365** [apache/seatunnel#6374]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

How to compile the specified connectors from source code? 
For example, I have just needed to build the `connector-cdc` connector module and package it to the target tar file named `apache-seatunnel-2.3.4/connectors/`.

### Usage Scenario

build from source code

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
if you compile jar from the source code, there has some way to reduce the connector jars:
1. added one more maven profile
2. update the current profile (by default using `seatunnel` profile), remove some connectors
all the above operation is in this file https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml

**Comment by zhangm365** [comment]
> if you compile jar from the source code, there has some way to reduce the connector jars:
> 
> 1. added one more maven profile
> 2. update the current profile (by default using `seatunnel` profile), remove some connectors
>    all the above operation is in this file https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml

What is the maven profile?, Where is it?

**Comment by liunaijie** [comment]
https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml 
this file

> > if you compile jar from the source code, there has some way to reduce the connector jars:
> > 
> > 1. added one more maven profile
> > 2. update the current profile (by default using `seatunnel` profile), remove some connectors
> >    all the above operation is in this file https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml
> 
> What is the maven profile?, Where is it?
