### ISSUE TITLE
[Bug] [start] v2.3.4 can't startup in Linux environment

### ISSUE THREAD

**Issue by cs-charles** [apache/seatunnel#6380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After installing the seatunnel and executing the install-plugin.sh script in the bin directory to install the plugin, when running the seatunnel-cluster.sh script, an error is reported: "Cannot find or load main class."

### SeaTunnel Version

v2.3.4

### SeaTunnel Config

```conf
without any configuration changes made.
```

### Running Command

```shell
bin/seatunnel-cluster.sh
```

### Error Exception

```log
...
+ '[' -n $'\r' ']'
+ JAVA_OPTS=' -Dseatunnel.config=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/seatunnel.yaml -Dhazelcast.config=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/hazelcast.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.configurationFile=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/log4j2.properties -Dseatunn'-XX:MaxMetaspaceSize=2geatunnel/dump/zeta-servernnel-2.3.4/logs -Dseatunnel.logs.file_name=seatunnel-engine-server
+ read line
 == \#* ]]1GC
+ read line
+ [[ '' == true ]]
+ java -Dseatunnel.config=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/seatunnel.yaml -Dhazelcast.config=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/hazelcast.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.configurationFile=/data/seatunnel/backend/apache-seatunnel-2.3.4/config/log4j2.properties -Dseatunnel.logs.path=/data/seatunnel/backend/apache-seatunnel-2.3.4/logs -Dseatunnel.logs.file_name=seatunnel-engine-server $'\r' $'-Xms2g\r' $'-Xmx2g\r' $'\r' $'-XX:+HeapDumpOnOutOfMemoryError\r' $'-XX:HeapDumpPath=/tmp/seatunnel/dump/zeta-server\r' $'\r' $'-XX:MaxMetaspaceSize=2g\r' $'\r' -cp '/data/seatunnel/backend/apache-seatunnel-2.3.4/lib/*:/data/seatunnel/backend/apache-seatunnel-2.3.4/starter/seatunnel-starter.jar' org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer
Error: Cannot find or load main class.
```

### Java or Scala Version

java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode)

### Screenshots

No

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Thanks for report this. We are try to fixing it. You can use source code to compile binary package at now.

**Comment by cs-charles** [comment]
来信已收到，谢谢！
祝安好。

**Comment by littlebear-xbz** [comment]
windows characters and linux characters problem, replace the bin/*.sh file and the file under config with linux characters, it will run ok

**Comment by cqutwangyu** [comment]
please see https://github.com/apache/seatunnel/issues/6285

**Comment by Blackerman** [comment]
> windows characters and linux characters problem, replace the bin/*.sh file and the file under config with linux characters, it will run ok

Not enough yet, you also need to modify the configuration files in the config directory. You can use dos2unix with the following two commands: `find config/ -type f -exec dos2unix {} \;` `find bin/ -name "*.sh" -exec dos2unix {} \`; to perform the conversion.

**Comment by Carl-Zhou-CN** [comment]
May be used temporarily, https://dist.apache.org/repos/dist/dev/seatunnel/2.3.4/
But he's temporary, waiting for a new release

**Comment by Carl-Zhou-CN** [comment]
@cs-charles hi ,the issue has been resolved, please re-download the distribution
