### ISSUE TITLE
[Bug] [Module Name] SeaTunnel 2.3.4 本地启动

### ISSUE THREAD

**Issue by wangcong19901212** [apache/seatunnel#6395]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

直接使用github 中打包好的程序

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template01 -e local
```

### Error Exception

```log
错误: 找不到或无法加载主类
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by littlebear-xbz** [comment]
the same as #6380

**Comment by PINK97** [comment]
You can use sh +x xxxx.sh to test which step of the script file reports an error. As far as I know, there are line breaks in these lines in the script. You can comment them out.

**Comment by PINK97** [comment]
![image](https://github.com/apache/seatunnel/assets/130653156/c65b7e88-a43d-410d-871d-6fb96124e6dc)

**Comment by Carl-Zhou-CN** [comment]
May be used temporarily, https://dist.apache.org/repos/dist/dev/seatunnel/2.3.4/
But he's temporary, waiting for a new release

**Comment by Carl-Zhou-CN** [comment]
@wangcong19901212 hi ,the issue has been resolved, please re-download the distribution
