### ISSUE TITLE
[Bug] [Module Name] 还是无法加载主类

### ISSUE THREAD

**Issue by wangcong19901212** [apache/seatunnel#6396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1、还是无法加载主类,
2、还有windows中字符不匹配linux的情况

这种低级错误都能犯，down下来包，不管是安装插件还是启动，主打一个失败。

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
./install-plugin.sh 2.3.4
```

### Error Exception

```log
install connector :  connector-redis
错误: 找不到或无法加载主类 org.apache.maven.wrapper.MavenWrapperMain
install connector :  connector-s3-redshift
错误: 找不到或无法加载主类 org.apache.maven.wrapper.MavenWrapperMain
install connector :  connector-sentry
错误: 找不到或无法加载主类 org.apache.maven.wrapper.MavenWrapperMain
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java 8

### Screenshots

是是是

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I'm sorry, we need to wait for the re-release.

**Comment by Carl-Zhou-CN** [comment]
May be used temporarily, https://dist.apache.org/repos/dist/dev/seatunnel/2.3.4/
But he's temporary, waiting for a new release

**Comment by physym** [comment]
可以把sh里的命令echo出来，直接执行命令就可以启动了，但是没什么用，接下来执行同步命令还有一堆bug

**Comment by Carl-Zhou-CN** [comment]
@wangcong19901212 hi ,the issue has been resolved, please re-download the distribution
