### ISSUE TITLE
[Bug] [Module Name] /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by woozhijun** [apache/seatunnel#6403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

bash ./bin/install-plugin.sh 2.3.4
for Error log:
/bin/sh^M: bad interpreter: No such file or directory

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
config/plugin_config
```

### Running Command

```shell
bash ./bin/install-plugin.sh 2.3.4
```

### Error Exception

```log
/bin/sh^M: bad interpreter: No such file or directory
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tianxingdao** [comment]
Maybe you need install maven i guess

**Comment by Carl-Zhou-CN** [comment]
the same as https://github.com/apache/seatunnel/issues/6380

**Comment by Carl-Zhou-CN** [comment]
@woozhijun hi ,the issue has been resolved, please re-download the distribution

**Comment by woozhijun** [comment]
@Carl-Zhou-CN  this is download url has not changed for 2.3.4 binary distribution ， The re-download is failed.
https://seatunnel.apache.org/download

**Comment by Carl-Zhou-CN** [comment]
> @Carl-Zhou-CN this is download url has not changed for 2.3.4 binary distribution ， The re-download is failed. https://seatunnel.apache.org/download

@woozhijun hi, The download address is not changed, whether it is caused by network problem?

**Comment by woozhijun** [comment]
@Carl-Zhou-CN Hi， this is url install to same problem.

**Comment by Carl-Zhou-CN** [comment]
hi @woozhijun 
![image](https://github.com/apache/seatunnel/assets/67902676/41123cac-c4fd-4aa3-970d-b9c2c78a1818)
I just downloaded it for verification
