### ISSUE TITLE
mysqlcdc,postgresqlcdc支持将已经被更新或删除的数据再次同步到sink吗？

### ISSUE THREAD

**Issue by Seapein** [apache/seatunnel#6452]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

通过mysqlcdc已经将新增的数据同步到了sink中，这时我修改或删除了原新增的数据，请问这部分数据还会被同步到sink中吗？因为我尝试了这种情况，发现运行报错了。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
Supported.

**Comment by Seapein** [comment]
> Supported.

thanks
