### ISSUE TITLE
[Feature][Source Data] Expect for support for XML format from HTTP or LocalFile

### ISSUE THREAD

**Issue by Wudadada** [apache/seatunnel#6473]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

thanks!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Can you describe the feature much more clearly?
