### ISSUE TITLE
[Bug] [Doc] Fail to build the zeta(local-mode) image according to the doc 

### ISSUE THREAD

**Issue by litiliu** [apache/seatunnel#6474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I was following the https://seatunnel.apache.org/docs/2.3.3/start-v2/kubernetes/#installation to build the Zeta(local-mode) image. The docker file on the official website went fine except below line:

````
RUN cd ${SEATUNNEL_HOME}||sh bin/install-plugin.sh ${SEATUNNEL_VERSION}
````

![Screenshot 2024-03-08 at 16 04 43](https://github.com/apache/seatunnel/assets/38579068/a501a723-6f30-45b1-ae12-3bea13ac943d)

This will cause the `bin/install-plugin.sh` to not be executed, if we successfully execute the cd command.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
docker file
```

### Running Command

```shell
FROM openjdk:8

ENV SEATUNNEL_VERSION="2.3.3"
ENV SEATUNNEL_HOME="/opt/seatunnel"

RUN wget https://dlcdn.apache.org/seatunnel/${SEATUNNEL_VERSION}/apache-seatunnel-${SEATUNNEL_VERSION}-bin.tar.gz
RUN tar -xzvf apache-seatunnel-${SEATUNNEL_VERSION}-bin.tar.gz
RUN mv apache-seatunnel-${SEATUNNEL_VERSION} ${SEATUNNEL_HOME}

RUN cd ${SEATUNNEL_HOME}||sh bin/install-plugin.sh ${SEATUNNEL_VERSION}
```

### Error Exception

```log
This will cause the `bin/install-plugin.sh` to not be executed, if we successfully execute the cd command.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
good job, have my +1
