### ISSUE TITLE
[Bug] [hive-connector] read_columns is specified, but the partition field is synchronized to the downstream

### ISSUE THREAD

**Issue by PINK97** [apache/seatunnel#6513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In the hive2kafka scenario, read_columns and read_partitions are specified in the hive source. I do not want to synchronize the partition fields to downstream kafka.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
{
  "env": {
    "job.name": "seatunnel_zeta.hive_to_kafka",
    "job.mode": "BATCH",
    "parallelism": 6
  },
  "source": [
    {
      "plugin_name": "Hive",
      "table_name": "test.edw_company_adm_dg_hq_mysql_concept_label_to_mysql_sea_poc_1d_di",
      "metastore_uri": "thrift://xxx:9083,thrift://xxx:9083",
      "krb5_path": "/etc/krb5.conf",
      "kerberos_principal": "xxx@INTSIG.INTERNAL",
      "kerberos_keytab_path": "/home/xxx/yueyang_li.keytab",
      "hdfs_site_path": "/etc/hadoop/conf/hdfs-site.xml",
      "hive_site_path": "/etc/hive/conf/hive-site.xml",
      "read_partitions": [
        "batch=202401220000"
      ],
      "read_columns": [
        "cond_keys",
        "data"
      ]
    }
  ],
  "transform": [],
  "sink": [
    {
      "plugin_name": "Kafka",
      "topic": "test_seatunnel_zeta_hive_to_kafka",
      "bootstrap.servers": "xxx:9092,xxx:9092",
      "format": "json",
      "kafka.config": {
        "acks": "all"
      }
    }
  ]
}
```

### Running Command

```shell
./bin/seatunnel.sh -cn seatunnel -c ./config/seatunnel_zeta_kafka_to_http_234.json
```

### Error Exception

```log
There are no exceptions or errors. I just feel that the parameters are not effective, or whether the partition field needs to be synchronized, a new parameter is added.
```

### Zeta or Flink or Spark Version

2.3.4

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
Try HiveSource setting this parameter parse_partition_from_path=false.

**Comment by PINK97** [comment]
> Try HiveSource setting this parameter parse_partition_from_path=false.

thx！i will try

**Comment by PINK97** [comment]
> Try HiveSource setting this parameter parse_partition_from_path=false.

thx！it works！
