### ISSUE TITLE
是否可以提供Rest Api或者Java API 来完成配置文件内容提交以及任务执行？

### ISSUE THREAD

**Issue by chenhu** [apache/seatunnel#654]
**1. Waterdrop Version(Waterdrop版本)**
1.x 和2.x 应该都具备这个功能

**2. 你希望增加什么功能？请尽可能详细描述**
正常情况下，是自己编辑配置文件，然后运行waterdrop-start.sh 带入配置文件来提交一个任务
但是，如果把waterdrop作为一个业务平台的后台任务执行系统的时候，任务配置参数是从界面上输入，在界面功能提交的时候，能够调用waterdrop的Java API或者调用 Rest API来执行任务
**3. 以上新功能的使用场景？**
将waterdrop作为一个中台的支撑组件使用
**4. Additional Context Information /  其他附加信息（如有）**
Nothing

**Comment by chenhu** [comment]
现在相当于是手动模式，增加了Java API或者Rest API 相当于是自动模式

**Comment by garyelephant** [comment]
这是一个非常好的需求，近期正在研发waterdrop结合开源livy组件来实现此功能。

**Comment by chenhu** [comment]
> 这是一个非常好的需求，近期正在研发waterdrop结合开源livy组件来实现此功能。

请问如果想contribute这个feature，我应该如何做？

**Comment by mahengyang** [comment]
附议此需求，通过http接口会更实用，便于自己定制平台封装
