### ISSUE TITLE
从hdfs向clickhouse导入数据是出错 

### ISSUE THREAD

**Issue by zhaobingkun** [apache/seatunnel#655]
hive3.1 hadoop2.7
我在从hive想clickhouse导数据的时候报错

**Waterdrop Version(Waterdrop版本)**

1.5.3

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark2.0

**Java or Scala Version(Java或者Scala版本)**

java 1.8

**Running Command(启动命令)**

./start-waterdrop.sh --master yarn --deploy-mode client --config ../config/batch.com

**Error Exception**
java.lang.ClassNotFoundException:org.apache.spark.sql.hive.HiveSessionState

**Comment by RickyHuo** [comment]
@zhaobingkun 升级Spark到2.2以上， Spark 2.4最佳
