### ISSUE TITLE
transform generates a uuid from a postgresql function and updates the ID field value in the database table

### ISSUE THREAD

**Issue by sandyustc** [apache/seatunnel#6555]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In seatunnel, transform wants to read the sql function written by itself from the target database to generate uuid and update the target database field. How to write the plug-in, or is there another way to deal with it

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
you can implement the UDF to generate uuid, please refer https://seatunnel.apache.org/docs/2.3.4/transform-v2/sql-udf

**Comment by sandyustc** [comment]
> you can implement the UDF to generate uuid, please refer https://seatunnel.apache.org/docs/2.3.4/transform-v2/sql-u

@liunaijie   thanks

I have already done that, in fact, I have another idea, is to use plugins in the sink to handle business data, etc., that plugin should inherit from those classes, thanks!
