### ISSUE TITLE
[Feature][RestAPI] get job status by id return all life cycle status

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#6574]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

For now, when we call `/hazelcast/rest/maps/running-job/:jobId` api, when the job is not running, whether failed or finished. it need call another api `/hazelcast/rest/maps/finished-jobs/:state` to check.
Can we improve this api to get all life cycle status. whether running or finished.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
@liugddx What do you think?

**Comment by liugddx** [comment]
> @liugddx What do you think?

LGTM. We can unify these two apis
