### ISSUE TITLE
sink jdbc connect hive Error

### ISSUE THREAD

**Issue by wwd-wwp** [apache/seatunnel#6578]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 ERROR org.apache.seatunnel.connectors.seatunnel.common.multitablesink.MultiTableSinkWriter - close error
java.lang.LinkageError: loader constraint violation: when resolving method 'org.apache.thrift.transport.TTransport org.apache.hadoop.hive.common.auth.HiveAuthUtils.getSocketTransport(java.lang.String, int, int)' the class loader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader @a92104c of the current class, org/apache/hive/jdbc/HiveConnection, and the class loader 'app' for the method's defining class, org/apache/hadoop/hive/common/auth/HiveAuthUtils, have different Class objects for the type org/apache/thrift/transport/TTransport used in the signature (org.apache.hive.jdbc.HiveConnection is in unnamed module of loader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader @a92104c, parent loader 'app'; org.apache.hadoop.hive.common.auth.HiveAuthUtils is in unnamed module of loader 'app')

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  #read_limit.bytes_per_second=70000
  read_limit.rows_per_second=400
}
source {
  Postgres-CDC {
    result_table_name ="r_name" 
    table-names = ["xx_1","xxs_2","xxx_3"]
    username = "postgres"
    password = "postgres"
    database-names = ["test"]
    schema-names = ["public"]
    base-url = "jdbc:postgresql://ip/test?loggerLevel=OFF"
    startup.mode = latest
  }
}
sink {
    jdbc {
      source_table_name ="r_name"
      url = "jdbc:hive2://127.0.0.1:10000/hive_test"
      driver = "org.apache.hive.jdbc.HiveDriver"
      user = "root"
      password = "root"
      generate_sink_sql = true
      database = hive_test
    }
}
```

### Running Command

```shell
seatunnel --config ./myConfig/postgresql-cdc-hive2.conf
```

### Error Exception

```log
ERROR org.apache.seatunnel.connectors.seatunnel.common.multitablesink.MultiTableSinkWriter - close error
java.lang.LinkageError: loader constraint violation: when resolving method 'org.apache.thrift.transport.TTransport org.apache.hadoop.hive.common.auth.HiveAuthUtils.getSocketTransport(java.lang.String, int, int)' the class loader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader @a92104c of the current class, org/apache/hive/jdbc/HiveConnection, and the class loader 'app' for the method's defining class, org/apache/hadoop/hive/common/auth/HiveAuthUtils, have different Class objects for the type org/apache/thrift/transport/TTransport used in the signature (org.apache.hive.jdbc.HiveConnection is in unnamed module of loader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader @a92104c, parent loader 'app'; org.apache.hadoop.hive.common.auth.HiveAuthUtils is in unnamed module of loader 'app')
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
As far as I know, hive jdbc does not support upsert operation at the moment and I am curious how you do it?
cc @hailin0 @ic4y
