### ISSUE TITLE
[Connector-V2]  The plug-in of sink type written by myself has not been found. The test method is: using open source code and restapi

### ISSUE THREAD

**Issue by sandyustc** [apache/seatunnel#6582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I wrote a type of sink in Connector-v2, and the plugin name is xxxxxName (my own plugin). This plugin is not found by seatunnel plugin, how do I need to use my plugin, such as where to configure it or put my package in a fixed directory?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
	"env": {
		"parallelism": 1,
		"job.mode": "batch",
		"checkpoint.interval": 10000
	},
	"source": [{
		    "plugin_name": "jdbc",
			"url": "jdbc:oracle:thin:@xxx.xxx.11.xxx:1521:orcl",
			"driver": "oracle.jdbc.OracleDriver",
			"connection_check_timeout_sec": 100,
			"user": "xxxg",
			"password": "xxxg",
			"query": "select * from  user3",
			"partition_column": "ID",
			"split.size": 10000
		
	}],
    "transform": [

    ],
		"sink": [{
		"plugin_name": "ownnerplugin",
			"url": "jdbc:postgresql://xxx.xxx.11.xxx:5432/xxxx",
			"driver": "org.postgresql.Driver",
			"user": "pixg",
			"password": "erdc",
			"generate_sink_sql": true,
			"database": xxsk
			"table": "public.user5",
			"schema_save_mode": "CREATE_SCHEMA_WHEN_NOT_EXIST",
			"data_save_mode": "APPEND_DATA",
			"primary_keys": ["ID"]

		
	}]
}
```

### Running Command

```shell
/hazelcast/rest/maps/submit-job
```

### Error Exception

```log
{

    "status": "fail",

    "message": "Plugin PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='ownnerplugin'} not found."

}
```

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
@sandyustc 
1. put your connector lib to `connector` (2.3.3 is `connector/seatunnel`) folder
2. modify the `plugin-mapping.properties` file in `connector` folder (2.3.3 is in `connector/seatunnel`) add you own connector

**Comment by sandyustc** [comment]
> @sandyustc
> 
> 1. put your connector lib to `connector` (2.3.3 is `connector/seatunnel`) folder
> 2. modify the `plugin-mapping.properties` file in `connector` folder (2.3.3 is in `connector/seatunnel`) add you own connector

@liunaijie  

 Following your steps and my connector  lib  was found, thank you very much

**Comment by liunaijie** [comment]
> > @sandyustc
> > 
> > 1. put your connector lib to `connector` (2.3.3 is `connector/seatunnel`) folder
> > 2. modify the `plugin-mapping.properties` file in `connector` folder (2.3.3 is in `connector/seatunnel`) add you own connector
> 
> @liunaijie
> 
> Following your steps and my connector lib was found, thank you very much

np~
