### ISSUE TITLE
[Feature][connector-cdc] Should we consider upgrading to the debezium version?

### ISSUE THREAD

**Issue by sunxiaojian** [apache/seatunnel#6600]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Upgrade debezium version

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ic4y** [comment]
Considering the upgrade and SeaTunnel's current support for JDK 1.8, it's a complex situation. Adopting a new version would mean SeaTunnel might have to let go of JDK 1.8 support, or we would have to find another solution. Both options present significant challenges that need careful consideration of the gains and losses.

**Comment by ic4y** [comment]
What are the confirmed benefits of upgrading debezium at this time
