### ISSUE TITLE
[Bug] [Module Name] Bug title - inconsitent encounter blacklist issue

### ISSUE THREAD

**Issue by ml-jin** [apache/seatunnel#6623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 The run command:
 bin/seatunnel.sh --config config/mysqlCDC-to-console.conf  -e local

### SeaTunnel Version

V2.3.4

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
```

### Running Command

```shell
bin/seatunnel.sh --config config/mysqlCDC-to-console.conf  -e local
```

### Error Exception

```log
2024-04-01 10:30:45,961 INFO  [c.h.i.s.t.TcpServerConnection ] [main] - [localhost]:5803 [seatunnel-173392] [5.1] Connection[id=1, /127.0.0.1:47279->localhost/127.0.0.1:5802, qualifier=null, endpoint=[localhost]:5802, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: TcpServer is stopping
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
any detail error log? can't understand what's your issue by the log or title
