### ISSUE TITLE
[Feature][Rest API] Add restore job in rest-api

### ISSUE THREAD

**Issue by kissycn** [apache/seatunnel#6650]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently rest-api supports stopping a job and saving it to savepoint. We hope to provide a restore interface for starting the stopped job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
@kissycn now the submit api is support restore job. 
you need set the job id, isStartWithSavePoint = true.
![image](https://github.com/apache/seatunnel/assets/28497357/0a81d7d4-64f9-4869-acd4-3e02c246efec)
