### ISSUE TITLE
[Doc][Kafka] Add kafka kerberos config document

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#6653]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add kafka kerberos config document.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
I am willing to submit a PR!
