### ISSUE TITLE
[OnlineMeeting&April.9]SeaTunnel community meeting Topic collect

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#6655]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

hailin invites you to a meeting on Tencent Meeting
Meeting Topic:  SeaTunnel community meeting
Time：2024/04/09 20:00-21:00 (GMT+08:00)  China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/TQWEnguJwAHh

#TencentMeeting：617-719-822
Copy this invitation and open in Tencent Meeting app to join the meeting

Everyone is very welcome to join:
If you have an issue, please submit it one day before the meeting, and provide a specific issue link and context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
discuss
https://github.com/apache/seatunnel/pull/6144
https://github.com/apache/seatunnel/pull/6556

**Comment by kissycn** [comment]
Please merge the two PRs：
#5983 
#5929

**Comment by hailin0** [comment]
> Please merge the two PRs： #5983 #5929

@kissycn
You can participate in review or help fix issues

**Comment by EricJoy2048** [comment]
Summer of Open Source

**Comment by hailin0** [comment]
Add scenario e2e

e.g:
mysql-oracle(multiple-tables/all types/savemode/ddl change/...)
mysql-doris(multiple-tables/all types/savemode/ddl change/...)
mysql-clickhouse(multiple-tables/all types/savemode/ddl change/...)

**Comment by EricJoy2048** [comment]
[STIP7-The Zeta Master is separated from the Worker](https://cwiki.apache.org/confluence/display/SEATUNNEL/STIP7-The+Zeta+Master+is+separated+from+the+Worker)
