### ISSUE TITLE
[Feature] Add E2E case for hive with kerberos

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#6664]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Right now, we didn't have e2e case for hive with kerberos, we need add test case.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
link [paimon sink kerberos](https://github.com/apache/seatunnel/pull/6585/files#diff-2610a87f1a5958d9d73ecffae4f29e860c4327191ab3c623609ed67560cfc6e7R106)
