### ISSUE TITLE
[Improve][Zeta] Does not save checkpoint file when job finished.

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#6670]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, at the end of the job (with `FINISHED` status), the last checkpoint will be called to perform shutdown and resource cleanup operations, but when the checkpoint finished, the corresponding checkpoint file will be kept in the file system. A job that ends with `FINISHED` does not need to save the checkpoint file, so we need to skip the logic of saving the checkpoint file when the last checkpoint is completed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
I want take this task

**Comment by liunaijie** [comment]
@Hisoka-X From your description and the code, i find the checkpoint is write to file by this code： https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java#L771

So i am going to add some logical to check job status, if it's finished, skip this method call, is this right?

**Comment by Hisoka-X** [comment]
> @Hisoka-X From your description and the code, i find the checkpoint is write to file by this code： https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java#L771
> 
> So i am going to add some logical to check job status, if it's finished, skip this method call, is this right?

Almost right. But just need check `completedCheckpoint`'s checkpointType is `COMPLETED_POINT_TYPE` is enough. You can use https://github.com/apache/seatunnel/blob/19888e7969475389b2e9f120a92267a2294dc8cd/seatunnel-engine/seatunnel-engine-core/src/main/java/org/apache/seatunnel/engine/core/checkpoint/CheckpointType.java#L94
