### ISSUE TITLE
[Bug] [Tool] Failed to resolve parameter [org.apache.seatunnel.e2e.common.container.TestContainer arg0] 

### ISSUE THREAD

**Issue by xiaochen-zhou** [apache/seatunnel#6677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Compilation failed：
<img width="1348" alt="image" src="https://github.com/apache/seatunnel/assets/27844885/86f053cd-db6d-4483-be14-48856110be53">

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
mvn -T 8 clean install
```

### Error Exception

```log
-------------------------------------------------------------------------------
Test set: org.apache.seatunnel.core.starter.seatunnel.SeaTunnelConnectorTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in org.apache.seatunnel.core.starter.seatunnel.SeaTunnelConnectorTest
testExecCheck{TestContainer}[1]  Time elapsed: 0.012 s  <<< ERROR!
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.apache.seatunnel.e2e.common.container.TestContainer arg0] in method [public void org.apache.seatunnel.core.starter.seatunnel.SeaTunnelConnectorTest.testExecCheck(org.apache.seatunnel.e2e.common.container.TestContainer) throws java.lang.Exception]: Exception when executing docker-machine ls -q
Caused by: org.testcontainers.utility.CommandLine$ShellCommandException: Exception when executing docker-machine ls -q
Caused by: org.testcontainers.shaded.org.zeroturnaround.exec.InvalidExitValueException: 
Unexpected exit value: 2, allowed exit values: [0], executed command [docker-machine, ls, -q], output was 597 bytes:
fatal error: runtime: bsdthread_register error
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dailai** [comment]
Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows:
![image](https://github.com/apache/seatunnel/assets/18141150/b6c2040c-65a0-440d-9080-a3b3825a98fa)

**Comment by xiaochen-zhou** [comment]
> Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows: ![image](https://private-user-images.githubusercontent.com/18141150/321134448-b6c2040c-65a0-440d-9080-a3b3825a98fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzY5MjMsIm5iZiI6MTcxMjczNjYyMywicGF0aCI6Ii8xODE0MTE1MC8zMjExMzQ0NDgtYjZjMjA0MGMtNjVhMC00NDBkLTkwODAtYTNiMzgyNWE5OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMzRiMDI0N2Q5NmVjZjMxMzhlMjYyMWNhY2ExYzBkNmI5ZmZiODNhMzIwYjE4NTQ5Y2I4MjM4MzNmNWU5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NC5k0prPJ1JncR2KTBFPjFDbftbuOK8OTysRYQ3PwSQ)

"I'm a bit puzzled by this error message too. I was also working on the 'dev' branch. Let me try it again."

**Comment by liunaijie** [comment]
try this command: 
```
./mvnw -U -T 1C clean install -DskipTests -D"maven.test.skip"=true -D"maven.javadoc.skip"=true -D"checkstyle.skip"=true -D"license.skipAddThirdParty"
```

**Comment by xiaochen-zhou** [comment]
> try this command:
> 
> ```
> ./mvnw -U -T 1C clean install -DskipTests -D"maven.test.skip"=true -D"maven.javadoc.skip"=true -D"checkstyle.skip"=true -D"license.skipAddThirdParty"
> ```

But I want to know the reason why the test didn't pass.

**Comment by xiaochen-zhou** [comment]
> Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows: ![image](https://private-user-images.githubusercontent.com/18141150/321134448-b6c2040c-65a0-440d-9080-a3b3825a98fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA4MDAsIm5iZiI6MTcxMjc1MDUwMCwicGF0aCI6Ii8xODE0MTE1MC8zMjExMzQ0NDgtYjZjMjA0MGMtNjVhMC00NDBkLTkwODAtYTNiMzgyNWE5OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzk2YmJlZWFjMzNhMTYzOWNjZjE3MTc4NWE2OGM2MTc4MDI3ODJjMmIxM2Q2ZDBkZjEyYjQ2NzNhZjkyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IAj48qOOXvX_eAkbFXiRry2WouvlZFBrycFG8Rml--8)



> Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows: ![image](https://private-user-images.githubusercontent.com/18141150/321134448-b6c2040c-65a0-440d-9080-a3b3825a98fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA4MDAsIm5iZiI6MTcxMjc1MDUwMCwicGF0aCI6Ii8xODE0MTE1MC8zMjExMzQ0NDgtYjZjMjA0MGMtNjVhMC00NDBkLTkwODAtYTNiMzgyNWE5OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzk2YmJlZWFjMzNhMTYzOWNjZjE3MTc4NWE2OGM2MTc4MDI3ODJjMmIxM2Q2ZDBkZjEyYjQ2NzNhZjkyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IAj48qOOXvX_eAkbFXiRry2WouvlZFBrycFG8Rml--8)

Does the issue have anything to do with my code compilation environment being macOS?

**Comment by dailai** [comment]
> > Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows: ![image](https://private-user-images.githubusercontent.com/18141150/321134448-b6c2040c-65a0-440d-9080-a3b3825a98fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA4MDAsIm5iZiI6MTcxMjc1MDUwMCwicGF0aCI6Ii8xODE0MTE1MC8zMjExMzQ0NDgtYjZjMjA0MGMtNjVhMC00NDBkLTkwODAtYTNiMzgyNWE5OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzk2YmJlZWFjMzNhMTYzOWNjZjE3MTc4NWE2OGM2MTc4MDI3ODJjMmIxM2Q2ZDBkZjEyYjQ2NzNhZjkyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IAj48qOOXvX_eAkbFXiRry2WouvlZFBrycFG8Rml--8)
> 
> > Why is "ls -q"? I was also successful running this test locally alone。Screenshot as follows: ![image](https://private-user-images.githubusercontent.com/18141150/321134448-b6c2040c-65a0-440d-9080-a3b3825a98fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTA4MDAsIm5iZiI6MTcxMjc1MDUwMCwicGF0aCI6Ii8xODE0MTE1MC8zMjExMzQ0NDgtYjZjMjA0MGMtNjVhMC00NDBkLTkwODAtYTNiMzgyNWE5OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzk2YmJlZWFjMzNhMTYzOWNjZjE3MTc4NWE2OGM2MTc4MDI3ODJjMmIxM2Q2ZDBkZjEyYjQ2NzNhZjkyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IAj48qOOXvX_eAkbFXiRry2WouvlZFBrycFG8Rml--8)
> 
> Does the issue have anything to do with my code compilation environment being macOS?

Looking at the screenshot above, my environment is also mac. You can debug it using Idea and run the e2e test.
