### ISSUE TITLE
[Improve][Doc] Intro the multi-line text feature in document

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#6682]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We need to provide a detailed introduction in the Config https://github.com/apache/seatunnel/blob/dev/docs/en/concept/config.md document about our support for multi-line symbols `"""`, making it easier for users to write complex configuration files. Please refer https://seatunnel.apache.org/docs/2.3.4/faq#how-do-i-write-a-configuration-item-in-multi-line-text-in-the-configuration-file

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nianhua99** [comment]
Can I take this issue? It's my first time contributing.

**Comment by Hisoka-X** [comment]
closed by #6713
