### ISSUE TITLE
[Feature][e2e] what's e2e?

### ISSUE THREAD

**Issue by Jiangnanjiezi** [apache/seatunnel#6704]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hello, I want to ask a question: in seatunnel jar, some with e2e, some without, what is the difference? Which one should I use?
![image](https://github.com/apache/seatunnel/assets/50507696/6640cf36-5546-48e7-b87b-2aafb0d528e4)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
E2E is the abbreviation for end-to-end testing. It used for test case, not for user.
