### ISSUE TITLE
[Feature][Spark Starter] Add suuport for Spark Operator

### ISSUE THREAD

**Issue by Rianico** [apache/seatunnel#6709]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Recently, we tried to run Seatunnel on our k8s cluster, and found that seatunnel had supported **flink operator** and **seatunnel engine** but not **spark operator**.
I think adding support for spark operator could be a common requirement.

### Usage Scenario

Run spark task on k8s cluster in Spark Operator way.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Rianico** [comment]
If this feature is approved, it can be assigned to me.

**Comment by liunaijie** [comment]
you can deploy the cluster and setup spark home to spark lib dir or mount spark lib to `/opt/spark`
then you can submit to spark on k8s.

**Comment by Rianico** [comment]
> you can deploy the cluster and setup spark home to spark lib dir or mount spark lib to `/opt/spark` then you can submit to spark on k8s.

However, relying solely on native `spakr-submit` is not advisable. It only creates the [naked pods](https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs), which is not recommended by k8s official, and lacks some essential components such as services and ingresses. It might not suffice for production scenarios.
