### ISSUE TITLE
No document was found for clickhouse multi-table writes

### ISSUE THREAD

**Issue by zhaoruosong** [apache/seatunnel#6716]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

No document was found for clickhouse multi-table writes.I saw that version 2.3.4 updated the ability of JDBC to read multiple tables, but I could not find an instance of a configuration file with few links on the sink side, nor did it update the function of writing multiple tables in the 2.3.4 document.like this
![1713255464542](https://github.com/apache/seatunnel/assets/167179759/a07eb6c4-8aec-40a8-a69f-e611d0cf5080)

### Usage Scenario

Multi-meter synchronization

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
clickhouse is not supported yet,Are you interested in that?

**Comment by zhaoruosong** [comment]
Now there is such a scheduling task, which needs to synchronize many tables regularly. If each form writes a config separately, it will take quite a long time to start seatunnel service. Before 2.3.4, it is possible to write multiple links in a config and synchronize multiple tables at the same time to reduce service startup times, but increase the consumption of link numbers. So I was concerned about JDBC's multi-table read in 2.3.4. However, if the sink terminal does not support it, I guess it will not be used in production.

**Comment by Carl-Zhou-CN** [comment]
> Now there is such a scheduling task, which needs to synchronize many tables regularly. If each form writes a config separately, it will take quite a long time to start seatunnel service. Before 2.3.4, it is possible to write multiple links in a config and synchronize multiple tables at the same time to reduce service startup times, but increase the consumption of link numbers. So I was concerned about JDBC's multi-table read in 2.3.4. However, if the sink terminal does not support it, I guess it will not be used in production.

@zhaoruosong  hi，He is still in the planning stage, and I haven't had time recently to complete it. If you're interested, you can keep an eye on it. https://github.com/apache/seatunnel/issues/5652
