### ISSUE TITLE
[Feature][Elastic search] Support multi-table source feature 

### ISSUE THREAD

**Issue by FuYouJ** [apache/seatunnel#6730]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Elastic search Support multi-table source feature 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
hi @FuYouJ 

Is there any progress on this task?

**Comment by FuYouJ** [comment]
> hi @FuYouJ
> 
> Is there any progress on this task?

I'll start right now
