### ISSUE TITLE
[Bug] [seatunnel-engine-server] slot申请时如果资源不够,已申请成功的资源未释放

### ISSUE THREAD

**Issue by liangcw1111** [apache/seatunnel#6761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

当设置seatunnel.engine.slot-service.slot-num=5时,提交一个需要6个slot的任务,前面5个slot申请成功,最后一个因为资源不足抛出NoEnoughResourceException. 此时任务失败结束但申请成功的5个slot没有释放.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
seatunnel:
  engine:
    classloader-cache-mode: true
    backup-count: 1
    print-execution-info-interval: 120
    print-job-metrics-info-interval: 10
    queue-type: blockingqueue
    slot-service:
      dynamic-slot: false
      slot-num: 5
    checkpoint:
      interval: 30000
      timeout: 21474836460
      max-concurrent: 10
      tolerable-failure: 2
```

### Running Command

```shell
java -Dseatunnel.config=/alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/config/seatunnel.yaml -Dhazelcast.config=/alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/config/hazelcast.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.configurationFile=/alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/config/log4j2.properties -Dseatunnel.logs.path=/alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/logs -Dseatunnel.logs.file_name=seatunnel-engine-server -Xrunjdwp:server=y,transport=dt_socket,address=5001,suspend=y -Xms3g -Xmx3g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/seatunnel/dump/zeta-server -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -XX:+PrintGCDetails -Xloggc:/alidata1/za-seatunnel/logs/gc.log -XX:+PrintGCDateStamps -XX:MaxGCPauseMillis=3000 -cp /alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/lib/*:/alidata1/za-seatunnel/apache-seatunnel-2.3.4-SNAPSHOT/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer -d
```

### Error Exception

```log
NoEnoughResourceException时未释放已成功资源
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VincentSleepless** [comment]
@hailin0 海林麻烦看看！

**Comment by hailin0** [comment]
cc @Hisoka-X

**Comment by liunaijie** [comment]
please temporarily assign me, thanks.

**Comment by liangcw1111** [comment]
![image](https://github.com/apache/seatunnel/assets/20763533/e86ce1e2-8104-4f08-ab04-f3c6e588fcaf)
在SubPlan中执行完CANCELING的逻辑后,jobMaster的resourceManger的registerWorker中仍然存在assignedSlots.
跟踪PhysicalVertex的cancel逻辑,发现checkTaskGroupIsExecuting返回false,直接更改状态为CANCELED , 没有执行CancelTaskOperation逻辑

**Comment by liangcw1111** [comment]
![image](https://github.com/apache/seatunnel/assets/20763533/e86ce1e2-8104-4f08-ab04-f3c6e588fcaf)
在SubPlan中执行完CANCELING的逻辑后,jobMaster的resourceManger的registerWorker中仍然存在assignedSlots.
跟踪PhysicalVertex的cancel逻辑,发现checkTaskGroupIsExecuting返回false,直接更改状态为CANCELED , 没有执行CancelTaskOperation逻辑

**Comment by liunaijie** [comment]
update some finding here:
in this method [releasePipelineResource](https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java#L392) can't get the slot prifle. so the resource is not released.
<img width="975" alt="image" src="https://github.com/apache/seatunnel/assets/28497357/edd0302c-3ea4-4216-9610-69ee84c91b89">

**Comment by liunaijie** [comment]
> update some finding here: in this method [releasePipelineResource](https://github.com/apache/seatunnel/blob/dev/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/master/JobMaster.java#L392) can't get the slot prifle. so the resource is not released. <img alt="image" width="975" src="https://private-user-images.githubusercontent.com/28497357/326146723-edd0302c-3ea4-4216-9610-69ee84c91b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODQ1NDAsIm5iZiI6MTcxNDE4NDI0MCwicGF0aCI6Ii8yODQ5NzM1Ny8zMjYxNDY3MjMtZWRkMDMwMmMtM2VhNC00MjE2LTk2MTAtNjllZTg0YzkxYjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAyMTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTA1YTZhZGZhNmZjOGNhMjcwZjAxN2FlMzM1ZWQ4N2Y3ZjZmYjZjODI0YTNjMjNlYjBkYWYyYTBmYjAzYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WS5r9pdNnfrMKenT9G13u32w4V1RlJOL6YQ2rDm15QA">

this IMAP info is put on `SCHEDULED` status when resource apply successed. but in this case, apply resource is failed. so  put method is never called.

<img width="1031" alt="image" src="https://github.com/apache/seatunnel/assets/28497357/02555a8e-5b3f-49fa-8f51-64c80731575e">
