### ISSUE TITLE
[Bug] [shell client] variable not correct when it has space, eg: -i dt="2024-04-28 00:00:00"

### ISSUE THREAD

**Issue by hogger2099** [apache/seatunnel#6769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

variable replaced not correct

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
mysql_2_doris.config:
source {
    Jdbc {
        query = "select * from t where updated_time >= '"${dt}"'"
    }
}
```

### Running Command

```shell
./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt="2024-04-28 00:00:00"
```

### Error Exception

```log
the executed SQL is below, the variable is not replaced correct!
actual:
select * from t where updated_time >= '2024-04-28'
expected:
select * from t where updated_time >= '2024-04-28 00:00:00'
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hogger2099** [comment]
Need help, thank you all.

**Comment by liunaijie** [comment]
you can refer this pr #6387  
try to use single quota.
```
-i dt='2024-04-28 00:00:00'
```

**Comment by liunaijie** [comment]
> you can refer this pr #6387 try to use single quota.
> 
> ```
> -i dt='2024-04-28 00:00:00'
> ```

https://github.com/apache/seatunnel/pull/6387/files#diff-f7dba51c9511c67942157a5e10fc0224f0c526f024db8dc95018be4229e27bbbR255

**Comment by hogger2099** [comment]
Thank u for replay. But not work if use variable like below, any suggestion?
here use two single quota to use variable "dt"


```
dt=$(date +'%Y-%m-%d 00:00:00')

./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt=''$dt''

```

> > you can refer this pr #6387 try to use single quota.
> > ```
> > -i dt='2024-04-28 00:00:00'
> > ```
> 
> https://github.com/apache/seatunnel/pull/6387/files#diff-f7dba51c9511c67942157a5e10fc0224f0c526f024db8dc95018be4229e27bbbR255

**Comment by liunaijie** [comment]
> Thank u for replay. But not work if use variable like below, any suggestion? here use two single quota to use variable "dt"
> 
> ```
> dt=$(date +'%Y-%m-%d 00:00:00')
> 
> ./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt=''$dt''
> ```
> 
> > > you can refer this pr #6387 try to use single quota.
> > > ```
> > > -i dt='2024-04-28 00:00:00'
> > > ```
> > 
> > 
> > https://github.com/apache/seatunnel/pull/6387/files#diff-f7dba51c9511c67942157a5e10fc0224f0c526f024db8dc95018be4229e27bbbR255



```
echo dt=\'$dt\'
```

**Comment by hogger2099** [comment]
> > Thank u for replay. But not work if use variable like below, any suggestion? here use two single quota to use variable "dt"
> > ```
> > dt=$(date +'%Y-%m-%d 00:00:00')
> > 
> > ./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt=''$dt''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > > you can refer this pr #6387 try to use single quota.
> > > > ```
> > > > -i dt='2024-04-28 00:00:00'
> > > > ```
> > > 
> > > 
> > > https://github.com/apache/seatunnel/pull/6387/files#diff-f7dba51c9511c67942157a5e10fc0224f0c526f024db8dc95018be4229e27bbbR255
> 
> ```
> echo dt=\'$dt\'
> ```

what's the meaning?

**Comment by liunaijie** [comment]
> > > Thank u for replay. But not work if use variable like below, any suggestion? here use two single quota to use variable "dt"
> > > ```
> > > dt=$(date +'%Y-%m-%d 00:00:00')
> > > 
> > > ./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt=''$dt''
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > > you can refer this pr #6387 try to use single quota.
> > > > > ```
> > > > > -i dt='2024-04-28 00:00:00'
> > > > > ```
> > > > 
> > > > 
> > > > https://github.com/apache/seatunnel/pull/6387/files#diff-f7dba51c9511c67942157a5e10fc0224f0c526f024db8dc95018be4229e27bbbR255
> > 
> > 
> > ```
> > echo dt=\'$dt\'
> > ```
> 
> what's the meaning?
```
./start-seatunnel-spark-2-connector-v2.sh --config ./mysql_2_doris.config -i dt=\'$dt\'
```

**Comment by hogger2099** [comment]
OK, thx, will version2.3.6 support this feature?

**Comment by liunaijie** [comment]
> OK, thx, will version2.3.6 support this feature?

yes, the mentioned pr has merged. it will be release in 2.3.6.

and for your case, you mentiond you can pass the variable, but the format is not right. so maybe you can try pass the variables with single quota first. maybe it can work for you.
