### ISSUE TITLE
[Bug] [dev branch] Version 2.3.5 of dev packages and runs on the server with an error message

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#6777]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

错误: 找不到或无法加载主类

### SeaTunnel Version

dev 2.3.5

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
bin/seatunnel-cluster.sh
```

### Error Exception

```log
错误: 找不到或无法加载主类
```

### Java or Scala Version

1.8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/90698333/6c7499d3-cb40-4585-bb49-591844ff72f5)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
package with windows?

**Comment by Xuzhengz** [comment]
> package with windows?
yes

**Comment by liunaijie** [comment]
> > package with windows?
> > yes

you need change the starter shell command file line separator from windows (CRLF) to unix (LF)
