### ISSUE TITLE
[Feature][Connector-V2] Support Hive catalog for paimon sink

### ISSUE THREAD

**Issue by MirrerZu** [apache/seatunnel#6821]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Paimon supports to create a catalog with Hive Metastore. 
At present, we can use the Paimon sink connector to automatically create databases and tables, but the metadata is not synchronized to the Hive Metastore. 
Many metadata management tools support extracting from Hive, but do not support directly reading the Paimon table from HDFS.
Hope to add the feature of synchronizing metadata to Hive Metastore when writing into Paimon.

### Usage Scenario

Support catalog with Hive Metastore.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dailai** [comment]
OK
