### ISSUE TITLE
[Bug] quick-start-flink not working !!! ?

### ISSUE THREAD

**Issue by zhouhoo** [apache/seatunnel#6832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I try seatunne on flink as offical doc says in the [link](https://seatunnel.apache.org/docs/2.3.5/start-v2/locally/quick-start-flink), I got no error , flink job running but console had NO sink data output as the doc says!!! I tried to ask slack channel for help ,but slack link is outdated!!! 
BTW, I tried to sink to mysql database, still no data sinked!

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
only modified seatunnel-env.sh file:
FLINK_HOME=/root/shen/flink-1.13.5
```

### Running Command

```shell
1. add mysql-connector-j-8.3.0.jar to lib, 
2. install some plugins including fake-source and console.
3. ./bin/start-seatunnel-flink-13-connector-v2.sh --config ./config/v2.batch.config.template
```

### Error Exception

```log
Job has been submitted with JobID 607d2d65753670b5f381fc502cb65c57
Program execution finished
Job with JobID 607d2d65753670b5f381fc502cb65c57 has finished.
Job Runtime: 2207 ms
```

### Zeta or Flink or Spark Version

flink 1.13.5

### Screenshots

![无标题](https://github.com/apache/seatunnel/assets/5432592/491456f4-151a-4bf4-93ca-20118fdf3e21)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
you submitted config is fake source to console, the console out is print in your worker node. not your submit job node.

**Comment by liunaijie** [comment]
you can update the config, write data to a local file or other connector, then verify the result

**Comment by zhouhoo** [comment]
> you submitted config is fake source to console, the console out is print in your worker node. not your submit job node.

flink worker node?  I start flink 、seatunnel all on same host, only one host. just a quick start.

**Comment by zhouhoo** [comment]
> you can update the config, write data to a local file or other connector, then verify the result

I also sink to mysql database, no data sinked in.

**Comment by liunaijie** [comment]
try this way to verify:
1. submit `v2.streaming.conf.template` config ( this is streaming job config)
2. login flink ui check running flink jobs, check whether this job has submitted to your flink cluster.
3. check log

**Comment by zhouhoo** [comment]
> try this way to verify:
> 
> 1. submit `v2.streaming.conf.template` config ( this is streaming job config)
> 2. login flink ui check running flink jobs, check whether this job has submitted to your flink cluster.
> 3. check log

I tried, job was successfully submitted to flink, no error ,running status. but no data consuming.
flink logs print some checkpoings was done successfully. 
seatunnel has no log output.

**Comment by liunaijie** [comment]
> > try this way to verify:
> > 
> > 1. submit `v2.streaming.conf.template` config ( this is streaming job config)
> > 2. login flink ui check running flink jobs, check whether this job has submitted to your flink cluster.
> > 3. check log
> 
> I tried, job was successfully submitted to flink, no error ,running status. but no data consuming. flink logs print some checkpoings was done successfully. seatunnel has no log output.

Hi, i package from dev, using flink 1.13.5. 
some update to `v2.streaming.conf.template` : 
1. update `env.parallelism` and `FakeSource.parallelism` to 1
2. update `FakeSource.row.num` to 100

Then it can run well. i can see the result in taskmanager's log.
![image](https://github.com/apache/seatunnel/assets/28497357/62a87b16-56d3-4ed0-838a-c950c73b28f3)
