### ISSUE TITLE
[Bug] when upgrade 2.3.5 version from 2.3.4, job restore failed

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#6853]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In version 2.3.4, i enable the IMAP storage cache, when upgrade to version 2.3.5. Will get exception when read data from the cached imap data.
the error reason is this pr https://github.com/apache/seatunnel/pull/6666/files#r1598217272 update the field type in IMAP cached class. 

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
na
```

### Running Command

```shell
na
```

### Error Exception

![image](https://github.com/apache/seatunnel/assets/28497357/f795feab-010d-4c58-bb18-8b4172d83709)

### Zeta or Flink or Spark Version

zeta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
cc @EricJoy2048

**Comment by liunaijie** [comment]
For the storage info (imap, checkpoint), In feature maybe still has some change, like add a filed, data type change.
We need make sure we can compatible with old version (at least last version), then we can restore the historary data.

What can we do now:
1. fix in release version or give advice (soluaction/warning) to user that want upgrade to version 2.3.5
2. add ut to make sure in feature when we modify those class, we can notice this case.

**Comment by Hisoka-X** [comment]
> add ut to make sure in feature when we modify those class, we can notice this case. 

Yes, this is one I really think SeaTunnel should have.
