### ISSUE TITLE
[Bug] [CheckPoint] checkpoint ineffective

### ISSUE THREAD

**Issue by 15767714253** [apache/seatunnel#6874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/apache/seatunnel/assets/37656068/4b15a93b-6db6-4f25-a64c-c9008fb98390)
![image](https://github.com/apache/seatunnel/assets/37656068/5c785c81-c37f-435c-9343-f6fd482b8463)
![image](https://github.com/apache/seatunnel/assets/37656068/c9a7c7a4-89ae-4225-a6d0-8ef21a19280b)

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 2000
  read_limit.rows_per_second=1
  job.name = cell-Job
}

source {

    InfluxDB {
        result_table_name = "test"
        url = "http://localhost:8086"
        sql = "select number from test1"
        database = "mydb"
        username = "admin"
        password = "123456"
        upper_bound = 10
        lower_bound = 1
        partition_num = 10
        split_column = "number"
        query_timeout_sec = 60
        connect_timeout_ms = 150000
        chunk_size = 1
        chunk_read = true
        schema {
                fields {
                         number = INT
                }
        }
    }

}


sink {
  Console {
          source_table_name = "test"
        }

}
```

### Running Command

```shell
./start-seatunnel-flink-15-connector-v2.sh --config ../jobs/job.txt
```

### Error Exception

```log
**BATCH    checkpoint ineffective**
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
using streaming mode

**Comment by 15767714253** [comment]
> using streaming mode
this source support batch mode only
