### ISSUE TITLE
Unable to create a source for identifier 'Postgres-CDC'.

### ISSUE THREAD

**Issue by yqyqyqyqyqyq** [apache/seatunnel#6877]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

postgreCdc:
Unable to create a source for identifier 'Postgres-CDC'.
Caused by: org.apache.seatunnel.common.utils.SeaTunnelException: Can not find catalog table with factoryId [Postgres]

ALTER SYSTEM SET wal_level TO 'logical';
SELECT pg_reload_conf(); 
ALTER TABLE your_table_name REPLICA IDENTITY FULL;

### Usage Scenario

postgreCdc:

### Related issues

ALTER SYSTEM SET wal_level TO 'logical';
SELECT pg_reload_conf(); 
ALTER TABLE your_table_name REPLICA IDENTITY FULL;

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yqyqyqyqyqyq** [comment]
resolve

**Comment by Laninfinite** [comment]
how to do？
