### ISSUE TITLE
flink on yarn execute fail  (Provider org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource not a subtype)

### ISSUE THREAD

**Issue by ljl568419709** [apache/seatunnel#6891]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

version seatunall 2.3.3    flink 1.3.6
cmd :    ./bin/start-seatunnel-flink-13-connector-v2.sh -e run-application --master yarn-application  --config /apps/hive/apache-seatunnel-2.3.3/config/v2.batch.config.mysql_mysql.template --name SeaTunnel

env {
  parallelism = 4
  job.mode = "BATCH"
}
source{
    jdbc {
        url = "jdbc:mysql://10.26.32.16:3306/communal_new?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "Meicloud12#$"
        query = "select * from sys_menu"
    }
}

transform {
    # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
    # please go to https://seatunnel.apache.org/docs/transform-v2/sql
}

sink {
    jdbc {
        url = "jdbc:mysql://10.26.32.16:3306/test"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "Meicloud12#$"
        # Automatically generate sql statements based on database table names
        generate_sink_sql = true
        database = test
        table = sys_menu
    }
}

![1](https://github.com/apache/seatunnel/assets/33241462/a1cfc8f0-61e8-4d5e-a6e0-b058420ae708)
![2](https://github.com/apache/seatunnel/assets/33241462/d0392425-8752-4631-8eeb-455cc1e4ae77)
![3](https://github.com/apache/seatunnel/assets/33241462/11d1eea4-54b7-4807-be99-6ae4fbfdc818)
我怀疑有没有人测试过

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ljl568419709** [comment]
jdbc  jar sumbited   yarn
![5](https://github.com/apache/seatunnel/assets/33241462/4c71ceaa-68d1-4ab3-a3a7-d17fbbd9552d)

![4](https://github.com/apache/seatunnel/assets/33241462/00d81e2c-3437-42b9-acf2-0553b6b5d8cf)

**Comment by ljl568419709** [comment]
而且seatunnel提交到yarn时，并没有将connectors/seatunnel提交到yarn，导致seatunnel找不到，上面的日志截图也有说明，这个是还有遗漏其他配置吗

**Comment by guojp1992** [comment]
I have also encountered this problem，same as you

**Comment by guojp00** [comment]
I have also encountered this problem，same as you . and it is not work for this solution #6068
