### ISSUE TITLE
[Feature][Transform-V2 Filter] support exclude columns in the filter transform

### ISSUE THREAD

**Issue by litiliu** [apache/seatunnel#6910]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We want to use the filter transform plugin-in to exclude specific columns because we have a huge table containing hundreds of columns and only a small amount of columns we want to drop, it's not convenient to specify all the needed columns using, https://seatunnel.apache.org/docs/2.3.5/transform-v2/filter . We want to add properties for the transform-v2/filter to support excluding columns by name

### Usage Scenario

we have a huge table containing hundreds of columns and only a small amount of columns we want to drop

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
there has `sql` transofrm, you can use query to keep the col you want

**Comment by litiliu** [comment]
> there has `sql` transofrm, you can use query to keep the col you want

Yes, but to exclude a few columns from a large number of columns, that SQL query would be extremely long (because there are still many columns we want to retain). Let's say we have a table with 200 columns, and now I only want to drop one column. It's feasible to write the SQL or use a filtering transform to specify the 199 columns I want to keep, but it's not user-friendly.
