### ISSUE TITLE
[Feature][Rest] Support set job id when use rest api to submit job

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#6968]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We supported set job id in shell when submit job #6943. We should support it in rest api too.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@dailai Hi, are you interested in this issue?

**Comment by dailai** [comment]
> @dailai Hi, are you interested in this issue?

Ok, I have a look.
