### ISSUE TITLE
[Feature][Config File Encryption And Decryption] The decrypted result does not need to be printed

### ISSUE THREAD

**Issue by mayufeng2595** [apache/seatunnel#6980]
### Search before asking

- [x] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When my configuration file needs to be decrypted, the decrypted file is printed directly at the info level. This puts the password at risk of being compromised。If you want the configuration file to be printed, you can set whether it is printed or not through the configuration file.

当我的配置文件需要解密时，解密后的文件会直接以info级别的形式打印出来。这样会导致密码存在泄漏的风险。如果要打印配置文件，可以通过配置文件设置是否打印。

### Usage Scenario

During the security check, the plaintext of the password is not allowed in the log file。

安全检查的时候，日志文件中不允许出现密码的明文。

### Related issues

Can the default encryption field be adjusted to be configurable? Auth and username are currently encrypted. But there are times when you don't want to encrypt these two fields.

默认加密字段是否可以调整为可配置的？目前会对auth 和 username进行加密。但是有些时候并不想对这两个字段加密。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@chl-wxp

**Comment by Hisoka-X** [comment]
Fixed by #6987

**Comment by Hisoka-X** [comment]
> Can the default encryption field be adjusted to be configurable? Auth and username are currently encrypted. But there are times when you don't want to encrypt these two fields.

Please create another issue to follow it.
