### ISSUE TITLE
seatunnel engine 与Datax采集性能比对

### ISSUE THREAD

**Issue by rocketguan** [apache/seatunnel#6983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我在本地使用seatunnel engine和datax进行性能比对验证，我配置了一个mysql到mysql数据采集任务，配置信息如下

env {
  execution.parallelism = 5
  job.mode = "BATCH"
}
source{
    Jdbc {
		parallelism=5
		partition_num="20"
        url = "jdbc:mysql://127.0.0.1:3306/mysql_src"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "111111"
		table_path="mysql_src.product_catalog"
		split.size = 10000
    }
}

transform {
}

sink {
  jdbc {
        url = "jdbc:mysql://127.0.0.1:3306/mysql_dest"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "*****"
		enable_upsert = false
		query = "insert into product_catalog(product_id,catalog_name) values(?,?)"
  }
}

运行后发现速度很慢，每秒处理速度只有几百条，具体统计信息如下
***********************************************
           Job Progress Information
***********************************************
Job Id                    :  853820592841818113
Read Count So Far         :               25365
Write Count So Far        :               15120
Average Read Count        :               422/s
Average Write Count       :               252/s
Last Statistic Time       : 2024-06-14 10:18:13
Current Statistic Time    : 2024-06-14 10:19:13
***********************************************

我同时尝试用datax采集同样的源表并插入到相同的目标表

{
	"content":[
		{
			"reader":{
				"name":"mysqlreader",
				"parameter":{
					"column":[
						"product_id",
						"catalog_name"
					],
					"connection":[
						{
							"jdbcUrl":[
								"jdbc:mysql://localhost:3306/mysql_src"
							],
							"table":[
								"product_catalog"
							]
						}
					],
					"password":"******",
					"splitPk":"product_id",
					"username":"root"
				}
			},
			"writer":{
				"name":"mysqlwriter",
				"parameter":{
					"batchSize":1024,
					"column":[
						"product_id",
						"catalog_name"
					],
					"connection":[
						{
							"jdbcUrl":"jdbc:mysql://localhost:3306/mysql_dest",
							"table":[
								"product_catalog"
							]
						}
					],
					"password":"******",
					"username":"root",
					"writeMode":"insert"
				}
			}
		}
	],
	"setting":{
		"speed":{
			"channel":"1"
		}
	}
}

任务启动时刻                    : 2024-06-14 09:02:49
任务结束时刻                    : 2024-06-14 09:04:00
任务总计耗时                    :                 70s
任务平均流量                    :          572.77KB/s
记录写入速度                    :          37449rec/s
读出记录总数                    :             2621440
读写失败总数                    :                   0

每秒处理速度能达到3W+

seatunnel engine运行速度严重低于预期，想请教下我应该如何调整配置，提升运行速度呢？

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  execution.parallelism = 5
  job.mode = "BATCH"
}
source{
    Jdbc {
		parallelism=5
		partition_num="20"
        url = "jdbc:mysql://127.0.0.1:3306/mysql_src"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "111111"
		table_path="mysql_src.product_catalog"
		split.size = 10000
    }
}

transform {
}

sink {
  jdbc {
        url = "jdbc:mysql://127.0.0.1:3306/mysql_dest"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "*****"
		enable_upsert = false
		query = "insert into product_catalog(product_id,catalog_name) values(?,?)"
  }
}
```

### Running Command

```shell
bin/seatunnel.sh --config jobs/mysql2mysql.conf
```

### Error Exception

```log
运行速度慢
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
```
env {
  job.mode = "BATCH"
}
source{
  Jdbc {
    parallelism=5
    url = "jdbc:mysql://127.0.0.1:3306/mysql_src"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = "root"
    password = "111111"
    table_path="mysql_src.product_catalog"
    split.size = 100000
  }
}

transform {
}

sink {
  jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/mysql_dest"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = "root"
    password = "*****"
    enable_upsert = false
    table="product_catalog"
    batch_size=10000
    generate_sink_sql=true
  }
}

```

**Comment by rocketguan** [comment]
@EricJoy2048 按照你的示例，我重新运行，速度还是没有得到提升
***********************************************
           Job Progress Information
***********************************************
Job Id                    :  853890593112195073
Read Count So Far         :               13074
Write Count So Far        :               11025
Average Read Count        :               217/s
Average Write Count       :               183/s
Last Statistic Time       : 2024-06-14 14:56:23
Current Statistic Time    : 2024-06-14 14:57:23
***********************************************
请问还有哪些地方有优化的空间呢

**Comment by hawk9821** [comment]
观察一下seatunnel-server的gc ，调整jvm_options

**Comment by rocketguan** [comment]
谢谢各位的耐心答复，问题排查到了，是因为我的sink端jdbc没有加上：rewriteBatchedStatements=true，因为DataX是默认会增加这个配置，所以没有受影响，ST需要手工增加这个配置

**Comment by EricJoy2048** [comment]
> 谢谢各位的耐心答复，问题排查到了，是因为我的sink端jdbc没有加上：rewriteBatchedStatements=true，因为DataX是默认会增加这个配置，所以没有受影响，ST需要手工增加这个配置

After seatunnel version 2.3.4, this parameter was added by default.

**Comment by 3047365466** [comment]
@rocketguan 现在性能如何呢？和datax比起来如何

**Comment by Joe12-24** [comment]
....最新版本,oracle写入oceanbase的mysql模式,还是每秒四五千条, datax每秒12万条, 咋回事...

**Comment by Cocytus316** [comment]
> ....最新版本,oracle写入oceanbase的mysql模式,还是每秒四五千条, datax每秒12万条, 咋回事...

seatunnel真的是一言难行，官方文档等于没有，
从1.x版本就开始关注了，尝试部署测试都是一堆bug小问题，
真心不推荐踩坑，也就软文吹的牛

**Comment by davidzollo** [comment]
> > ....最新版本,oracle写入oceanbase的mysql模式,还是每秒四五千条, datax每秒12万条, 咋回事...
> 
> seatunnel真的是一言难行，官方文档等于没有， 从1.x版本就开始关注了，尝试部署测试都是一堆bug小问题， 真心不推荐踩坑，也就软文吹的牛

If you have any questions, you are welcome to submit detailed issue descriptions. If you have a better suggestions for the documentation, you are welcome to share them. And of course, you are highly welcome to join the contributors
