### ISSUE TITLE
[Bug] [Redis Sink] cluster mode has some issue

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#6984]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/apache/seatunnel/assets/28497357/fb73b852-d062-4563-9c91-1c1b0fada767)

In redis sink, we will build the redis client(using jedis)
when build the client with cluster mode, it will wrapper the jediscluster to jedis.
after that, something wrong.

you can see the code above, when i use jediscluster it will be ok, but when i use jediswrapper, will got exception.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Redis {
    mode = "cluster"
    nodes = ["127.0.0.1:7000"]
    host = "127.0.0.1"
    port = 7000
    keys = "aaa*"
    data_type = key
  }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
example module
```

### Error Exception

```log
JedisConnectionException: Failed to connect to any host resolved for DNS name.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liwenban** [comment]
I also encountered this problem. This is usually because the redis cluster you deployed is in sharding mode, jedis is not suitable, and you need to use lettuce to implement it.
