### ISSUE TITLE
[Feature][Flink] Support multiple tables read and write

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7008]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

validate
Remove `flink` filter item
https://github.com/apache/seatunnel/blob/0c3044e3f6d5d1a52df1896e069676b509419e4b/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mysql-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/mysql/MysqlCDCIT.java#L266

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
i want take this task

**Comment by hailin0** [comment]
@liunaijie 

Sorry, this feature has been selected for Open Source Summer, so let's wait for applicants to complete it

https://summer-ospp.ac.cn/org/prodetail/248940457?list=org&navpage=org
