### ISSUE TITLE
[Feature][Spark] Support multiple tables read and write

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7009]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

validate
Remove `spark` filter item
https://github.com/apache/seatunnel/blob/0c3044e3f6d5d1a52df1896e069676b509419e4b/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-1/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcMysqlMultipleTablesIT.java#L174

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
link
https://github.com/apache/seatunnel/issues/7008

**Comment by Carl-Zhou-CN** [comment]
@hailin0 Leave it to me

**Comment by hailin0** [comment]
hi @Carl-Zhou-CN Is there any progress on this task?

**Comment by Carl-Zhou-CN** [comment]
I'm very sorry, there are some delays, currently in progress
