### ISSUE TITLE
[Bug] [env jars] third-party packages can't be loaded

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#7025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

third-party packages can't be loaded

### SeaTunnel Version

dev-2.3.6

### SeaTunnel Config

```conf
{
  "env": {
    "execution.parallelism": 1,
    "job.name": "udf测试",
    "job.mode": "batch",
    "jars": "file://Users/xuzhengzhou/IdeaProjects/starrocks-udf/target/starrocks-udf-1.0-SNAPSHOT-jar-with-dependencies.jar;"
  },
  "preHandler": [
  ],
  "source": [
    {
      "plugin_name": "FakeSource",
      "resourceType": "nosql",
      "row.num": 100,
      "schema": {
        "table": "ottomi",
        "fields": {
          "id": "string",
          "age": "int"
        }
      },
      "resources": [
        "ottomi"
      ],
      "result_table_name": "fake_source",
      "ottomi_node_type": "FakeSource"
    }
  ],
  "transform": [
  ],
  "sink": [
    {
      "plugin_name": "Void",
      "source_table_name": "fake_source"
    }
  ]
}
```

### Running Command

```shell
bin/seatunnel.sh -c udf.json
```

### Error Exception

```log
null
```

### Java or Scala Version

1.8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/90698333/ac4a43ed-9e95-4342-9e6a-200322a29aae)
![image](https://github.com/apache/seatunnel/assets/90698333/0f002101-eec8-465c-bd94-320cc6e01201)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@Hisoka-X  PTAL

**Comment by EricJoy2048** [comment]
you can put the jar to plugins dir

**Comment by Hisoka-X** [comment]
@Xuzhengz Could you try with #7035 ?

**Comment by Xuzhengz** [comment]
> @Xuzhengz Could you try with #7035 ?

Does env.jars only support local files? If the clustering mode fails, the jar package may not be on another node

**Comment by Hisoka-X** [comment]
> > @Xuzhengz Could you try with #7035 ?
> 
> Does env.jars only support local files? If the clustering mode fails, the jar package may not be on another node

It should support HTTP/HTTPS, FTP, Local at now.

**Comment by Xuzhengz** [comment]
> > > @Xuzhengz Could you try with #7035 ?
> > 
> > 
> > Does env.jars only support local files? If the clustering mode fails, the jar package may not be on another node
> 
> It should support HTTP/HTTPS, FTP, Local at now.

Please tell me that the code you repaired has not been merged into the dev branch, how can I test it or wait for the dev branch

**Comment by Hisoka-X** [comment]
> > > > @Xuzhengz Could you try with #7035 ?
> > > 
> > > 
> > > Does env.jars only support local files? If the clustering mode fails, the jar package may not be on another node
> > 
> > 
> > It should support HTTP/HTTPS, FTP, Local at now.
> 
> Please tell me that the code you repaired has not been merged into the dev branch, how can I test it or wait for the dev branch

You can cherry pick to your local branch or waiting it merge into dev.
