### ISSUE TITLE
[Bug] [ZETA] debezium_json Chinese garbled characters

### ISSUE THREAD

**Issue by kekely471** [apache/seatunnel#7031]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Hello! I am configuring the corresponding parameters in the instance, expecting to import 【MySQL CDC】 information into 【Kafka】, and the format used is compatible_debezium_json, but I found that there is garbled Chinese characters. How can I solve this?
I found that if I change the format in the sink to json, there are actually no Chinese garbled characters, but when both the source and sink are configured with the format as compatible_debezium_json, the problem arises.
like this:

expected =
        {"name": "常禄产权2",
        "registered_no": null,
        "short_name": "常禄产权2"}

actual = 
        {"name": "��»��Ȩ2",
        "registered_no": null,
        "short_name": "��»��Ȩ2"}

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {

  MySQL-CDC {
    base-url = "jdbc:mysql://10.0.0.136:3306/ihr_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8"
    hostname = 10.0.0.136
    username = "root"
    password = "123456"
    table-names = ["ihr_test.company"]
	
    catalog {
        factory=MySQL
    }

    startup.mode = "initial"

    # compatible_debezium_json options
    format = compatible_debezium_json
    debezium = {
        # include schema into kafka message
        key.converter.schemas.enable = false
        value.converter.schemas.enable = false
        # include ddl
        include.schema.changes = true
        # topic prefix
        database.server.name =  "keke_mysql_cdc"
    }
  }
}


sink {
  kafka {
      topic = "keke_topic_mysql_ihr_test"
      bootstrap.servers = "10.0.0.98:39092"
	  format = compatible_debezium_json
      semantics = AT_LEAST_ONCE
      kafka.config = {
        acks = "all"
        request.timeout.ms = 60000
      }
  }
}
```

### Running Command

```shell
seatunnel.cmd --config ./config/v2.batch.config.kafka.template -e local
```

### Error Exception

```log
There are no error messages in the console.
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java version "1.8.0_101"

### Screenshots

![b706b6b1-45ad-4f16-ad93-a446519d9bdb](https://github.com/apache/seatunnel/assets/45355196/d2a6368b-5c7a-4d0b-bce8-0073d20c7fcf)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Hi @kekely471 , could you try with #7046 again?

**Comment by kekely471** [comment]
after deploying my service to a Linux environment, the issue of garbled Chinese characters has been resolved. Does this bug also have something to do with the environment? The previous problematic environment was Windows.

**Comment by taoganio** [comment]
Hello, has it been resolved? I encountered the same issue on Windows using version 2.3.12, but it works normally on Linux
