### ISSUE TITLE
[Feature][Resource Manager][Zeta] add tag to worker, when submit job can use tag to choose worker

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#7036]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now, we don't have the resource manager on queue level. like yarn `queue`. when submit job we will send job to all worker if avaliable.

I check the code, find we can add some `tag` to hazelcast node, then when we assign task, we can use this tag to choose node.

Here are some code need to update:
1.`SeaTunnelServer` then create node, add tag
![image](https://github.com/apache/seatunnel/assets/28497357/3acb1621-c8e1-42e6-b59c-0d36ae502dba)

2. `DefaultSlotService` when create slot profile, read tag.
![image](https://github.com/apache/seatunnel/assets/28497357/943de221-29cc-49c3-8a9d-24ef28098ffe)

3. `AbstractResourceManager` when assign task to worker, use tag to choose

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
great!!!
