### ISSUE TITLE
seatunnel web 中，在使用sql转换因子时，提示找不到表

### ISSUE THREAD

**Issue by xinjingqing** [apache/seatunnel#7038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

配置好流程，选择SQL转换因子，run时，后台报错，提示“ SQL validate failed: select age * 10 as age from userinfo, cause: Table name: userinfo not found”

### SeaTunnel Version

SeaTunnel Web 1.0.1-release

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
idea开发环境
```

### Error Exception

```log
org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - SQL validate failed: select age * 10 as age from userinfo, cause: Table name: userinfo not found
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Fixed by #7020
