### ISSUE TITLE
[Feature][ConnectorV2] new option for determining split owners

### ISSUE THREAD

**Issue by loustler** [apache/seatunnel#7043]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Connectors determine a owner of split like `(tp.hashCode() & Integer.MAX_VALUE) % numReaders)`. This make a skew of own split among readers in my case. Why not add a optional configuration that allows user to choose the class that determines the split owner they want?

### Usage Scenario

```
env {
  parallelism = 1
  job.mode = "BATCH"
  #spark config
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 1
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
  MongoDB {
    uri = "mongodb://e2e_mongodb:27017/test_db"
    database = "test_db"
    collection = "test_null_op_db"
    match.projection = "{ c_bigint:0 }"
    result_table_name = "mongodb_null_table"
    cursor.no-timeout = true
    fetch.size = 1000
    max.time-min = 100
    determine.split.owner.class = "org.apache.seatunnel.connectors.seatunnel.common.source.HashCodeBasedSplitOwnerDeterminer"
    schema = {
      fields {
        c_map = "map<string, string>"
        c_array = "array<int>"
        c_string = string
        c_boolean = boolean
        c_int = int
        c_bigint = bigint
        c_double = double
        c_row = {
          c_map = "map<string, string>"
          c_array = "array<int>"
          c_string = string
          c_boolean = boolean
          c_int = int
          c_bigint = bigint
          c_double = double
        }
      }
    }
  }
}
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Hi @loustler ,I think this feature makes sense. Are you willing to move forward with it? cc @hailin0 @EricJoy2048
