### ISSUE TITLE
[Feature][Kafka-connector] Proposal to Add Kafka Protobuf Data Parsing Support

### ISSUE THREAD

**Issue by chessplay** [apache/seatunnel#7059]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Protobuf (Protocol Buffers) is a widely adopted method for serializing structured data, especially in distributed systems. It offers several advantages, including smaller payload sizes and faster parsing compared to JSON or XML. Adding support for Kafka to parse protobuf format data in Apache SeaTunnel would enable more efficient data processing and broaden the platform's applicability in modern data engineering workflows.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
+1

**Comment by zhangshenghang** [comment]
Please assign it to me, I can complete it @Hisoka-X
