### ISSUE TITLE
Support reading from Kafka and writing to MySQL using SeaTunnel

### ISSUE THREAD

**Issue by ragdollcb** [apache/seatunnel#7077]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I would like to request a feature that allows SeaTunnel to read data from Kafka and write it to MySQL. This feature would be incredibly useful for scenarios where data needs to be processed or transformed after being streamed to Kafka and then stored in a MySQL database for further analysis or use.

### Usage Scenario

In my current project, I am using MySQL with Canal to write data changes into Kafka. I need to read this data from Kafka using SeaTunnel and then write it into MySQL. This would streamline the data flow and enable real-time data processing and storage, improving the efficiency of our data pipeline.

If implemented, this feature would enhance the versatility of SeaTunnel and make it a more powerful tool for data integration and ETL processes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
i think this feature already supported, kafka canal to mysql

**Comment by ragdollcb** [comment]
Could you please provide an example?

**Comment by liunaijie** [comment]
kafka source: https://seatunnel.apache.org/docs/2.3.5/connector-v2/source/kafka
kafka canal json format: https://seatunnel.apache.org/docs/2.3.5/connector-v2/formats/canal-json/
mysql sink: https://seatunnel.apache.org/docs/2.3.5/connector-v2/sink/Mysql#cdcchange-data-capture-event

**Comment by ragdollcb** [comment]
thinks
