### ISSUE TITLE
[Feature] [Github CI] connector-kafka-e2e , connector-rocketmq-e2e module runs repeatedly

### ISSUE THREAD

**Issue by hawk9821** [apache/seatunnel#7090]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Both the update-modules-integration-test-part-1 and kafka-connector-it  workflows run the connector-kafka-e2e module
Both the update-modules-integration-test-part-2 and rocketmq-connector-it  workflows run the connector-rocketmq-e2e module

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
fixed by #7091
