### ISSUE TITLE
[Feature][Core] Introduce dynamic custom parameters

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#7115]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

`sh seatunnel.sh -di date="def java.text.SimpleDateFormat fmt = new java.text.SimpleDateFormat("yyyyMM"); Calendar calendar = Calendar.getInstance(); calendar.setTime(new Date()); return fmt.format(calendar.getTime());"`

will get a parameter date="2024"

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CheneyYin** [comment]
Hi, @liugddx 
What is the access scope of dynamic parameters? 
The command substitutions function provided by the shell can also output parameters. Compared with command substitutions, what are the advantages of parameters computed by injecting Java code? 
Please introduce a user-face usage scenario.

**Comment by liugddx** [comment]
> Hi, @liugddx What is the access scope of dynamic parameters? The command substitutions function provided by the shell can also output parameters. Compared with command substitutions, what are the advantages of parameters computed by injecting Java code? Please introduce a user-face usage scenario.

For example, the http connector can obtain the token through dynamic parameters.

**Comment by CheneyYin** [comment]
> > Hi, @liugddx What is the access scope of dynamic parameters? The command substitutions function provided by the shell can also output parameters. Compared with command substitutions, what are the advantages of parameters computed by injecting Java code? Please introduce a user-face usage scenario.
> 
> For example, the http connector can obtain the token through dynamic parameters.

Is it a scenario like refreshing the token every time it expires?

**Comment by liugddx** [comment]
> > > Hi, @liugddx What is the access scope of dynamic parameters? The command substitutions function provided by the shell can also output parameters. Compared with command substitutions, what are the advantages of parameters computed by injecting Java code? Please introduce a user-face usage scenario.
> > 
> > 
> > For example, the http connector can obtain the token through dynamic parameters.
> 
> Is it a scenario like refreshing the token every time it expires?

Yes, it can be understood that way.

**Comment by liugddx** [comment]
I found that shell scripts can do the same thing and are more lightweight than groovy

**Comment by liugddx** [comment]
> Hi, @liugddx 
> What is the access scope of dynamic parameters? 
> The command substitutions function provided by the shell can also output parameters. Compared with command substitutions, what are the advantages of parameters computed by injecting Java code? 
> Please introduce a user-face usage scenario.

You’re right. Shell can also do this, and it‘s lighter.
