### ISSUE TITLE
[Improve][RestAPI] overview api add tag filter

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#7123]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now, we supported overview api it can return the current cluster's overview. and in this [pr](https://github.com/apache/seatunnel/pull/7045) bring `tag` to zeta engine, 
we can add tag to the overview api then it can only return the slot that tag matched

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
+1
