### ISSUE TITLE
[Feature][Transform] Move transform from seatunnel-starter.jar to transform directory

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7171]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, transform is packaged in the `seatunnel-starter.jar` package. If users need to extend transform, they need to restart the zeta engine. We hope that transform, like connector, exists in a separate folder and is dynamically loaded when a task is submitted. At the same time, users can also dynamically add transform without restarting the engine.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
please assign it to me, thx.
