### ISSUE TITLE
[Feature][Qdrant] Support qdrant connector source/sink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7190]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, we already support the milvus connector, would anyone like to add support for qdrant?

reference
https://github.com/qdrant/qdrant
https://github.com/qdrant/java-client

milvus connector pr
https://github.com/apache/seatunnel/pull/7158

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Anush008** [comment]
Hey!
I'll be trying to implement this.

**Comment by hailin0** [comment]
@Anush008 good!
