### ISSUE TITLE
[Feature][Typesense] Support typesense connector source/sink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7191]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, we already support the milvus connector, would anyone like to add support for typesense?

reference
https://github.com/typesense/typesense
https://github.com/typesense/typesense-java

milvus connector pr
https://github.com/apache/seatunnel/pull/7158

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
please assign it to me

**Comment by hailin0** [comment]
hi @zhangshenghang 
Is there any progress on this task?

**Comment by hailin0** [comment]
hi @zhangshenghang 
Is there any progress on this task?

**Comment by hailin0** [comment]
hi @zhangshenghang
Is there any progress on this task?

**Comment by zhangshenghang** [comment]
> hi @zhangshenghang Is there any progress on this task?

Yes, I will submit it soon @hailin0 

Because I am handling issue #7059 at the same time, the update is a bit slow

**Comment by hailin0** [comment]
> > hi @zhangshenghang Is there any progress on this task?
> 
> Yes, I will submit it soon @hailin0
> 
> Because I am handling issue #7059 at the same time, the update is a bit slow

ok, good
