### ISSUE TITLE
[Feature][CDC] Support tidb cdc connector source

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7199]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, we don't support reading tidb change data capture (CDC), does anyone want to add support for tidb?

docs
https://github.com/tikv/client-java

reference
https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-cdc/connector-cdc-mysql
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mysql-e2e
https://github.com/apache/seatunnel/tree/dev/docs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
@hailin0 please assign it to me

**Comment by hailin0** [comment]
hi @sunxiaojian 
Is there any progress on this task?

**Comment by dailai** [comment]
+1

**Comment by hailin0** [comment]
No response at the moment

**Comment by hailin0** [comment]
@dailai Are you interested in completing this?

**Comment by dailai** [comment]
> @dailai Are you interested in completing this?

Yeah

**Comment by hailin0** [comment]
> > @dailai Are you interested in completing this?
> 
> Yeah

good

**Comment by hailin0** [comment]
@sunxiaojian 
Hello, temporarily transfer the task to @dailai , you can choose another task later

**Comment by hailin0** [comment]
In communication with the author, I see that the author is working on this

**Comment by sunxiaojian** [comment]
In developing,   It will be completed in about two weeks
