### ISSUE TITLE
[Feature][Prometheus] Support Prometheus connector source/sink

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7201]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, we don't support reading and writing Prometheus, does anyone want to add support for Prometheus?

docs
https://github.com/prometheus/client_java

reference

https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-iotdb
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-iotdb-e2e

https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-influxdb
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-influxdb-e2e

https://github.com/apache/seatunnel/tree/dev/docs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CosmosNi** [comment]
I want to try it.please assign it to me.

**Comment by hailin0** [comment]
> I want to try it.please assign it to me.

@CosmosNi assigned

**Comment by hailin0** [comment]
hi @CosmosNi 
Is there any progress on this task?

**Comment by CosmosNi** [comment]
> hi @CosmosNi Is there any progress on this task?

Looking at other modules

**Comment by CosmosNi** [comment]
hi,@hailin0 ,I am confused whether to put this module under the http module or to build a separate module.can you give me a good suggestion.I plan to use http base to achieve.

**Comment by hailin0** [comment]
> hi,@hailin0 ,I am confused whether to put this module under the http module or to build a separate module.can you give me a good suggestion.I plan to use http base to achieve.

@CosmosNi 
I recommend you to create new module, but you can ref on already existing code

**Comment by CosmosNi** [comment]
hi,@hailin0，PLAL ，Can you help me figure out what needs improvement?

**Comment by CosmosNi** [comment]
hi,@hailin0，about sink，I haven't found a good way. i try pushgateway,But it cannot take timestamp. or use vm?

**Comment by hailin0** [comment]
For Prometheus, its main function is write, and read  is of little significance.

**Comment by CosmosNi** [comment]
hi,@hailin0，for writer，I haven't found a good way. use pushgateway or vm writer?for pushgateway,it cannot take timestamp

**Comment by hailin0** [comment]
@CosmosNi I see remote_write, you need to compare
https://prometheus.io/docs/specs/remote_write_spec/
https://www.51cto.com/article/671796.html

**Comment by corgy-w** [comment]
> hi,@hailin0，for writer，I haven't found a good way. use pushgateway or vm writer?for pushgateway,it cannot take timestamp

Any progress? We're adding to that as well

**Comment by hailin0** [comment]
> > hi,@hailin0，for writer，I haven't found a good way. use pushgateway or vm writer?for pushgateway,it cannot take timestamp
> 
> Any progress? We're adding to that as well

@corgy-w 
You can participate in code reviews and suggestions to merge it as soon as possible

https://github.com/apache/seatunnel/pull/7265

**Comment by corgy-w** [comment]
> @corgy-w You can participate in code reviews and suggestions to merge it as soon as possible
> 
> #7265

Ok, I'll take a look at it sometime
