### ISSUE TITLE
[Feature][CDC] Support DDL parse for oracle-cdc

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7204]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, we don't support read oracle ddl, does anyone want to add support for oracle?

reference
https://github.com/apache/seatunnel/pull/6929

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
@dailai 
Hello, are you interested in this issue?

**Comment by dailai** [comment]
> @dailai Hello, are you interested in this issue?

Ok, but maybe the priority is not that high。

**Comment by dailai** [comment]
Wait for this pr https://github.com/apache/seatunnel/pull/7463
