### ISSUE TITLE
seatunel中能否提供gaussdb的插件

### ISSUE THREAD

**Issue by xinjingqing** [apache/seatunnel#7213]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

seatunel中能否提供gaussdb的插件

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hogger2099** [comment]
直接用jdbc就行了吧

**Comment by hailin0** [comment]
Invalid subject title
