### ISSUE TITLE
[Feature][Log]How to control logging in cluster mode

### ISSUE THREAD

**Issue by Arsenal1109** [apache/seatunnel#7217]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

How to control logging in cluster mode where SLF4J logs are all printed in the 'seatunnel-engine-server.log' file, and how to print more logs to the console in this scenario. who can help me？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
update the `config/log4j2.properties`

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/fd1b5ec1-2c2a-4a33-82cc-de4aabb6b9fb">

enable line 37,38 if you want print the log to console. 
if you don't want write it to file, then disable line 41

**Comment by Arsenal1109** [comment]
This configuration prints some of the client logs to the server console. I want to print server logs to the client console.Too few client console logs.Can only print the client main thread log?

**Comment by liunaijie** [comment]
> This configuration prints some of the client logs to the server console. I want to print server logs to the client console.Too few client console logs.Can only print the client main thread log?

what do you mean client log?
update this config only change log location, won't impact the log content.
