### ISSUE TITLE
缺少DB2的支持包

### ISSUE THREAD

**Issue by xinjingqing** [apache/seatunnel#7227]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/catalog中，缺少DB2的支持包

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
无
```

### Error Exception

```log
无
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
Invalid subject title
