### ISSUE TITLE
[Feature][Activemq] Support Activemq connector source/sink

### ISSUE THREAD

**Issue by asapekia** [apache/seatunnel#7237]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Adding connector for apache activemq

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by asapekia** [comment]
Hi Team, I am working on this. I am implementing the source using AbstractSingleSplitSource. Can anyone confirm if I am doing the right things.

**Comment by Hisoka-X** [comment]
> Hi Team, I am working on this. I am implementing the source using AbstractSingleSplitSource. Can anyone confirm if I am doing the right things.

Hi @asapekia , welcome for contribute  SeaTunnel! I suggest you refer to the implementation of kafka or rabbitmq, because the message queue involves multi-split and multi-parallel processing, and AbstractSingleSplitSource only provides a single parallel source.

**Comment by Hisoka-X** [comment]
closed by #7251
