### ISSUE TITLE
[Feature][maintain] Auto release notes more easier for maintainer

### ISSUE THREAD

**Issue by zhongjiajie** [apache/seatunnel#726]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I thinks we seatunnel should support auto release note for more easier to maintain our repo.
I recommend using https://github.com/marketplace/actions/release-drafter to auto create release note base on PR title and labels. If our PR title is good and each merged PR have specific labels, our release note would be create expect, and we have an example in https://github.com/sqlfluff/sqlfluff/releases/tag/0.8.2

So use https://github.com/marketplace/actions/release-drafterc for auto create release note key point is:

* keep PR title meaningful and suitable
* keep each PR would have specific labels when merged

At this two point, I suggest we use https://mergeable.us/ to do it.
* For title: https://mergeable.readthedocs.io/en/latest/validators/title.html#title could strict our PR title
* For lables: https://mergeable.readthedocs.io/en/latest/validators/label.html#label we could request PR must have labels `chorn|feature|bug` for release note classification

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
What do you think @CalvinKirs

**Comment by kezhenxu94** [comment]
GitHub has officially provided the tool to generate release notes, if we have well-written PR title and label, it's not necessary to use release-draft, also, after entering ASF incubator, this kind of release must be done by human beings, not bot

**Comment by zhongjiajie** [comment]
Good suggestion, I do not know github provide release notes yet. and 

> after entering ASF incubator, this kind of release must be done by human beings, not bot

Why should we create release note by human beings but not bot? @kezhenxu94

**Comment by kezhenxu94** [comment]
> Good suggestion, I do not know github provide release notes yet. and
> 
> > after entering ASF incubator, this kind of release must be done by human beings, not bot
> 
> Why should we create release note by human beings but not bot? @kezhenxu94

To clarify: we can create release note text with tools / bots, but we cannot push them (git commit) with bot account.

**Comment by zhongjiajie** [comment]
Ok, I got your point. So we can also use bot to create release note, but we have push by hand when we put git ASF git archive?
