### ISSUE TITLE
[Bug] [plugin-discovery] Jar found with same prefix

### ISSUE THREAD

**Issue by corgy-w** [apache/seatunnel#7271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When the project began loading the plugin, we encountered multiple jars during the search due to custom development（eg ⬇️：plugin-mapping.properties）. I propose using a similarity algorithm to match the most appropriate jar. Please review the details, and I will submit the corresponding pr.

### SeaTunnel Version

2.3.3 When I raised this issue, I found that 2.3.5 had already avoided this by throwing IllegalArgumentException

### SeaTunnel Config

```conf
plugin-mapping.properties
---
seatunnel.source.HttpBase = connector-http
seatunnel.sink.HttpBase = connector-http
seatunnel.source.HttpJira = connector-http-jira
seatunnel.sink.HttpJira = connector-http-jira
seatunnel.source.Kafka = connector-kafka
seatunnel.sink.Kafka = connector-kafka
seatunnel.source.Kafka-Alcs = connector-kafka-alcs
seatunnel.sink.Kafka-Alcs = connector-kafka-alcs
seatunnel.source.Kafka-Blcs = connector-kafka-blcs
seatunnel.sink.Kafka-Blcs = connector-kafka-blcs
---
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Screenshots

<img width="1316" alt="image" src="https://github.com/user-attachments/assets/763d08f3-ff8d-4c7e-9a1a-5137d78ca9a5">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Yes, the current jar package path positioning is not perfect.
