### ISSUE TITLE
[Bug] [Seatunnel-config-sql] No exception for error config

### ISSUE THREAD

**Issue by dailai** [apache/seatunnel#7276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There is a comma missing in the configuration, but there is no error in the job, and the database name passed to the sink is not correct
![截屏2024-07-26 16 45 20](https://github.com/user-attachments/assets/8c5c92bc-04da-45b6-b7bf-6b050d40553f)

![截屏2024-07-26 16 34 08](https://github.com/user-attachments/assets/416cb1b7-d5a4-42b8-9ec2-d9dbc5cb3465)

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
The jdbc_mysql_source_and_sink_with_multiple_tables.sql in e2e case
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config jdbc_mysql_source_and_sink_with_multiple_tables.sql
```

### Error Exception

```log
No exception. But the database name in sink is not right.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
cc @rewerma
