### ISSUE TITLE
[Bug] Job Status update error when master switch

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#7286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I have an JDBC sink to Starrocks job. normally it can run very fast, end within 3 mins.
But today i find this job is stuck in RUNNING status nearly 3 hours.
I check the log, find when this job running, the master node has switch.

![image](https://github.com/user-attachments/assets/1cc206ee-6b8f-4e45-8fe7-db6c9e1bff20)

before the master switch, the source read print `Closed the bounded jdbc source` log, but after this master switch, i can't see this log. And after node switch, the job is stuck in RUNNING status.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
mysql jdbc to starrocks
```

### Running Command

```shell
use rest api to submit job
```

### Error Exception

```log
no exception, job status is stuck in RUNNING status.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
attach log 
[node0.txt](https://github.com/user-attachments/files/16436534/node0.txt)
[node1.txt](https://github.com/user-attachments/files/16436535/node1.txt)
[node2.txt](https://github.com/user-attachments/files/16436536/node2.txt)

**Comment by hailin0** [comment]
please add thread stack dump
