### ISSUE TITLE
[Improvement][Seatunnel-web] Add support to execute seatunnel-web REST API e2e

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7344]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Write base classes for writing integration test cases.
The base test class must initiate the SeaTunnel-Web server using an in-memory database.
It should also launch the SeaTunnel-Engine to perform end-to-end functionality verification.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
+1

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/180

**Comment by arshadmohammad** [comment]
PR is merged https://github.com/apache/seatunnel-web/commit/7205efe14cf42683ffb9a22113d6d4fe32e6f857
