### ISSUE TITLE
[Feature][e2e] testMultiTableHttp test case is not suitable for spark or flink

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#7345]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 testMultiTableHttp test case is not suitable for spark or flink

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
link https://github.com/apache/seatunnel/pull/7283

**Comment by jackyyyyyssss** [comment]
Thank you for the reminder. I will make the necessary modifications when I have free time
