### ISSUE TITLE
[Bug] [Module Name] Doris custom_sql can't work

### ISSUE THREAD

**Issue by RaymondFishWang** [apache/seatunnel#7367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I have tested 2.3.5 and 2.3.6 version with 
data_save_mode=CUSTOM_PROCESSING
custom_sql="delete from table;
system can't work. I also tested the same function with starocks. It is ok.

### SeaTunnel Version

2.3.5 
2.3.6

### SeaTunnel Config

```conf
sink {
    Doris {
        fenodes = "ip***:8030"
        query-port=9030
        password=""
        username=""
        database = "test"
        table = "***"
        batch_max_rows=10240
        data_save_mode=CUSTOM_PROCESSING
        custom_sql="delete from table;"
        doris.config = {
           format = "json"
           read_json_by_line = "true"
        }
    }
}
```

### Running Command

```shell
/seatunnel-2.3.6/bin/seatunnel.sh --config aa.config
```

### Error Exception

```log
have no error. all the data have been inserted into the database . System can't delete the data from db.
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RaymondFishWang** [comment]
even if I write the wrong sql in custom_sql. System don't issue the error. It prove system don't execute the custom_sql.
this function is seem to have the bug

**Comment by Hisoka-X** [comment]
cc @chl-wxp

**Comment by zhangshenghang** [comment]
@Hisoka-X You can assign it to me, I'll handle it
