### ISSUE TITLE
[Feature][Connector-V2] Fake Source support produce vector data

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7390]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

After we supported vector type in #7158 . We should support produce vector data in fake source too. Used to add test case or test data write into vector database.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgy-w** [comment]
assign to me, I'm almost done, forgot to comment last night 🎑

**Comment by Hisoka-X** [comment]
closed by #7401
