### ISSUE TITLE
[Feature][CDC] Opengauss CDC

### ISSUE THREAD

**Issue by dailai** [apache/seatunnel#7410]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I will do this

### Usage Scenario

cdc

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Closed by #7433
