### ISSUE TITLE
[Bug] [jdbc] 任务会卡主

### ISSUE THREAD

**Issue by 13813586515** [apache/seatunnel#7449]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用ds来调度st，任务会卡住，导致定时跑的任务无法继续

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
env {
  parallelism = 10
  job.mode = "BATCH"
}

source {
    Jdbc {
        driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
        url = "jdbc:sqlserver://192.168.0.123:1433;databaseName=BSERP3_LP"
        user = sa
        password = "123"
        # Define query logic as required
      table_list = [
        {
          table_path = "BSERP3_LP.dbo.fjsx9"
          # Use query filetr rows & columns
          query = "select * from BSERP3_LP.dbo.fjsx9 "
        }
        
    ]

    }
}

 

sink {
  Doris {
    fenodes = "192.168.0.168:8030,192.168.0.169:8030,192.168.0.170:8030"
    username = root
    password = "123"
    database = "ods_bs"
    table = "ods_${table_name}"
    # 保证每个文件唯一，拷贝之后文件需要修改此处
    sink.label-prefix = "bs-product-${table_name}-jdbc"
    sink.enable-2pc = "true"
    # sink.enable-delete = "true"
    save_mode_create_template="CREATE TABLE IF NOT EXISTS `${database}`.`${table_name}` (${rowtype_fields},dt datetime(0) default current_timestamp(0) on update current_timestamp(0)) ENGINE=OLAP UNIQUE KEY (SXDM) DISTRIBUTED BY HASH (SXDM) BUCKETS 3 PROPERTIES ( \"replication_allocation\" = \"tag.location.default: 1\",\"in_memory\" = \"false\",\"storage_format\" = \"V2\", \"disable_auto_compaction\" = \"false\")"
    doris.config {
      format = "json"
      read_json_by_line = "true"
    }
  }
}
```

### Running Command

```shell
集群
```

### Error Exception

```log
任务卡主不动
```

### Screenshots

![image](https://github.com/user-attachments/assets/97678874-4a7c-460a-a89b-f82e03f19acd)
![image](https://github.com/user-attachments/assets/bfe96013-87dc-430b-9997-625a763770ff)
![image](https://github.com/user-attachments/assets/faa6068a-e002-4ad0-80a2-57693e70d57b)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhawenjie** [comment]
从Oracle向doris中同步数据 总是出现任务读写为0的情况

<img width="1084" alt="Snipaste_2024-10-18_11-06-19" src="https://github.com/user-attachments/assets/0c7006be-7c49-4ead-bf05-4edd53bdadd5">

**Comment by loevingerx** [comment]
从Oracle向doris中同步数据总是出现任务读写为0的情况
<img width="1084" alt="Snipaste_2024-10-18_11-07-22" src="https://github.com/user-attachments/assets/468ca816-fba3-42d8-bd39-01284ee2cd0d">

**Comment by shenzhy5** [comment]
数据写过去了，但是一直running

**Comment by aiyougit** [comment]
> 从Oracle向doris中同步数据总是出现任务读写为0的情况 <img alt="Snipaste_2024-10-18_11-07-22" width="1084" src="https://private-user-images.githubusercontent.com/37870495/377706004-468ca816-fba3-42d8-bd39-01284ee2cd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjYzMjQsIm5iZiI6MTczMzEyNjAyNCwicGF0aCI6Ii8zNzg3MDQ5NS8zNzc3MDYwMDQtNDY4Y2E4MTYtZmJhMy00MmQ4LWJkMzktMDEyODRlZTJjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA3NTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzMzMmJmMDdjODNlM2E1ZjU2Y2ViOTUzMjkxN2VjNDczMmUwOTI1M2M0NDk4NjgwODllYTZjNDVmYTkwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uq4uLI_RcAZfYR09kZFHGCg3dqrHztwwtsN1AKQ1qcw">

doris用什么连接的呢？
