### ISSUE TITLE
Does MySQL CDC have plans to support DDL

### ISSUE THREAD

**Issue by dibrother** [apache/seatunnel#7454]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I tested the synchronization between MySQL and MySQL, but currently it does not support DDL changes (such as adding a field on the source side). I think this is an important feature, and Flink CDC already supports it, but it is easier to get started without SeaTunnel

version :2.3.7
MySQL:8.0.39

### Usage Scenario

data synchronization

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dailai** [comment]
It's supported, but you need to enable it via this configuration in mysql-cdc source.

debezium = {
  include.schema.changes = true
}


reference: https://github.com/apache/seatunnel/pull/6929/files#diff-b413df0d7dea1ddb842f03d9070ef7040f4f26ce0b83602a3329b0e72b773d2e

**Comment by dibrother** [comment]
He can execute successfully, thank you！
