### ISSUE TITLE
[Bug] [Seatunnel-web] Tasks pagination is not working

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7478]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In seatunnel-web UI, Tasks pagination is not working
records per page is set to 10, still it is listing all the entries

### SeaTunnel Version

NA

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
NA
```

### Screenshots

![image](https://github.com/user-attachments/assets/c5c84af5-9707-413f-82bb-a4cc8c235e2b)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
if anybody iterested to work on this issue, please assign the issue to yourself or comment on this to start working on this issue.

**Comment by BilwaST** [comment]
@arshadmohammad Can you please assign this issue to me? I would like to work on it

**Comment by arshadmohammad** [comment]
This issue is fixed.
https://github.com/apache/seatunnel-web/commit/fcc0e6beb11174d15e72181cf51870deb765ec7f

Thanks @BilwaST  for working on this issue
