### ISSUE TITLE
[Feature][Zeta] Unify the triggering logic of job status related events

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7485]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We already supported define some lifecycle event type. 
![image](https://github.com/user-attachments/assets/51587630-7829-4173-9af1-a0d31d3c1629)
But only FakeSource support produce these event. 
https://github.com/apache/seatunnel/blob/1bba72385b6797dc5edd96fa5951376d0594e633/seatunnel-connectors-v2/connector-fake/src/main/java/org/apache/seatunnel/connectors/seatunnel/fake/source/FakeSourceReader.java#L77

We should support produce event in engine side, not connector side. Eg:
Produce reader open event in where invoke open method.
![image](https://github.com/user-attachments/assets/9f5d0452-0372-4242-ab5c-0dab316a4b6d)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Can be assigned to me and I will complete it , thanks
