### ISSUE TITLE
[Feature][Zeta] add RestApi to update node tag

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#7510]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now we support add tag to each node, but it can't be changed after startup.

We can add api to let user update the tag value on runtime. after tag updatd, it will update it's value to master in next heartbeat

![image](https://github.com/user-attachments/assets/f5dc62b7-0e06-4513-ad70-6a7b1300f930)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
This feature need to know each node's ip, then use api to update  this node's attribution.

**Comment by Cheun99** [comment]
pls assign me
