### ISSUE TITLE
[Feature][Core] Added rest-api for batch start and stop

### ISSUE THREAD

**Issue by zhangshenghang** [apache/seatunnel#7511]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Added rest-api for batch start and stop .

https://seatunnel.apache.org/docs/2.3.7/seatunnel-engine/rest-api

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I look forward to your contribution @zhangshenghang
