### ISSUE TITLE
[Feature][Core]Added support for batch stop client commands 

### ISSUE THREAD

**Issue by zhangshenghang** [apache/seatunnel#7512]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Added support for batch start and stop client commands 

https://seatunnel.apache.org/docs/2.3.7/seatunnel-engine/user-command

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
I look forward to your contribution @zhangshenghang

**Comment by zhangshenghang** [comment]
@dailai @Carl-Zhou-CN @Hisoka-X 

Do you have any good suggestions? How to submit and stop batch tasks on the command line?
I mainly want to discuss how it is more convenient to use.
The current single task submission is:
```shell
sh bin/seatunnel.sh --config $SEATUNNEL_HOME/config/v2.batch.config.template --async -n myjob
```

**Comment by Hisoka-X** [comment]
> @dailai @Carl-Zhou-CN @Hisoka-X
> 
> Do you have any good suggestions? How to submit and stop batch tasks on the command line? I mainly want to discuss how it is more convenient to use. The current single task submission is:
> 
> ```shell
> sh bin/seatunnel.sh --config $SEATUNNEL_HOME/config/v2.batch.config.template --async -n myjob
> ```

1. So batch submit mode can not trace log?
2. Any other project supported feature like this?

**Comment by dailai** [comment]
1. The main scenario is batch submission of recovery tasks and no batch submission of new tasks
