### ISSUE TITLE
Hazelcast 5.5 CP Subsystem Changes - Impact on Project

### ISSUE THREAD

**Issue by Basil1991** [apache/seatunnel#7513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Hi,

I noticed that our project depends on Hazelcast, which recently made the CP Subsystem an enterprise-only feature starting from version 5.5. This change raises some concerns regarding how it might affect our project, especially in terms of maintaining compatibility and functionality with future updates.

Could you please provide some insights on how the project plans to handle this change? Will there be any adjustments to the dependency or considerations for alternative solutions?

Looking forward to your guidance on this matter.

https://docs.hazelcast.com/hazelcast/5.5/release-notes/5-5-0

**Comment by Hisoka-X** [comment]
SeaTunnel does not use CP system at now. It's disabled by default. https://docs.hazelcast.com/hazelcast/5.1/cp-subsystem/configuration#quickstart-configuration
