### ISSUE TITLE
[Improvement] [Seatunnel-web] Add API to get and update job definition.

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7525]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As part of https://github.com/apache/seatunnel-web/commit/f45dacd11759bcf0fb0ad363b334d0a00af5e69a we have added single API to create a job. There should be corresponding get and update APIs also. So add following two APIs
GET /seatunnel/api/v1/job/get/{jobVersionId}
PUT /seatunnel/api/v1/job/update/{jobVersionId}

### Usage Scenario

Do Job CRUD operations in single API call.

### Related issues

NA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/198

**Comment by Hisoka-X** [comment]
Closed by https://github.com/apache/seatunnel-web/pull/198
