### ISSUE TITLE
[Bug] [connector-v2] Dependency Conflict

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#7528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The jar packages in the lib directory have dependency conflicts. For example, when running the s3 plugin, there are multiple Hadoop dependent jar files (hive jar files) that cause errors. When uploading other JDBC drivers, running the es plugin results in HTTP dependency jar conflicts. How to resolve such dependency conflicts

### SeaTunnel Version

dev,2.3.8

### SeaTunnel Config

```conf
{
  "env": {
    "execution.parallelism": "1",
    "job.mode": "BATCH"
  },
  "source": [
     {
      "plugin_name":"jdbc",
      "url":"jdbc:postgresql://******:5432/oceandatum?currentSchema=dw_label",
      "password":"******",
      "user":"******",
      "driver":"org.postgresql.Driver",
      "query": "SELECT \"id\",\"name\",\"label_column_fact\" FROM \"label_group_a\"",
      "result_table_name": "fake"
    }
  ],
  "transform": [
    {"plugin_name": "sql",
      "source_table_name": "fake",
      "result_table_name": "fake2",
      "query": "SELECT  concat(id,'$test') AS id,name AS label,concat('{','\"id\":\"',id,'\",','\"name\":\"',name,'\",','\"label_column_fact\":\"',label_column_fact,'\"','}') AS property FROM fake "
}
  ],
  "sink": [
    {
      "plugin_name": "elasticsearch",
      "hosts":["******:9200"],
      "index":"relation",
      "primary_keys":["id"]
    }
  ]
}
```

### Running Command

```shell
bin/seatunnel.sh -c demo.json
```

### Error Exception

```log
Caused by: java.io.IOException: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider instantiation exception: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
```

### Java or Scala Version

1.8

### Screenshots

![image](https://github.com/user-attachments/assets/4061152a-ad12-467e-9c9b-265b24f14cda)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuzhengz** [comment]
Reason for S3 plugin error: The guava version in the Hive driver is lower, while the guava version in the S3 plugin is higher, but now the driver dependencies are all in lib. How to eliminate this dependency conflict problem

**Comment by zhangqing123** [comment]
![image](https://github.com/user-attachments/assets/078d499f-cc65-4f4c-90d7-af28a569703e)
该行与hadoop-aws包也有冲突。

**Comment by dailai** [comment]
I fix the problem.
