### ISSUE TITLE
[Feature][Core] Support config variable substitution with default value

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7535]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We had supported default value with el expression feature in [sink-options-placeholders](https://seatunnel.apache.org/docs/concept/sink-options-placeholders). 
eg:
${table_name:default_my_table}

We should support default value with el expression in all config place too. Including `env`, `source`, `transform`, `sink`.
It's a sub feature of [config-variable-substitution](https://seatunnel.apache.org/docs/concept/config#config-variable-substitution). So the el expression with default value will be replaced with user configure value when use shell script with `-i`.

The flow diagram:
![image](https://github.com/user-attachments/assets/4d09f9ce-f6b5-4584-a5d7-15ae5e35e622)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Can be assigned to me ，thks

**Comment by Hisoka-X** [comment]
I added a flow diagram cc @zhangshenghang @arshadmohammad

**Comment by zhangshenghang** [comment]
> I added a flow diagram cc @zhangshenghang @arshadmohammad

@Hisoka-X I have a general understanding of the overall idea. thks

**Comment by arshadmohammad** [comment]
Design and approach looks good to me.
