### ISSUE TITLE
[Bug] [Seatunnel-web] Job instance delete is not working

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Job instance is not working, from UI it is calling API  `/job/executor/del?jobInstanceId=${id}` which do not exist.
Need to add new API and then call the new job instance delete API

### SeaTunnel Version

NA

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
NA
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/200

**Comment by Hisoka-X** [comment]
Closed by https://github.com/apache/seatunnel-web/pull/200
