### ISSUE TITLE
为什么没有docker安装文档，我等的花儿都凋谢了，我一直在等一直在等，我们服务器都是基于docker在部署，hub.docker.com只有仓库里面一个tag都没有

### ISSUE THREAD

**Issue by FN20200222** [apache/seatunnel#7541]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

为什么没有docker安装文档，我等的花儿都凋谢了，我一直在等一直在等，我们服务器都是基于docker在部署，hub.docker.com只有仓库里面一个tag都没有

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgy-w** [comment]
ing

**Comment by corgy-w** [comment]
#7346 #7486  #7532 You can follow these

**Comment by liunaijie** [comment]
hi @FN20200222  now i am working on it. the offical docker image shoule be publish in next version `2.3.8` i think.
the related doc you can find it in above pr.


Another question, you mentioned you deploy base on docker. is docker or K8S?

**Comment by liunaijie** [comment]
@FN20200222 Hi, after version 2.3.8, when version release we will auto upload docker image to docker hub. 
now you can find the 2.3.8 tag in docker hub.
