### ISSUE TITLE
[Bug] [StarRocks] StarRocks JDBC Dialect confilect with StarRocks Connector

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#7551]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

this pr https://github.com/apache/seatunnel/pull/7294 added StarRocks JDBC dialect. 

It will has some issue when both JDBC connector and StarRocks connector exist.

![image](https://github.com/user-attachments/assets/584dc729-7d53-47ee-819d-1c4114ef9cd7)

jdbc catalog will use `dialect.dialectName()` as factoryIdentifier to load Catalog. `StarRocks` catalog in created in `StarRocks` connector, so if `StarRocks` connector exist, it will read an error Catalog get `ClassCastException` exception

If not exist, it will use loading tables from jdbc directly, the e2e test case is work because of this.
![image](https://github.com/user-attachments/assets/2265a817-b654-4ab2-883f-77cbff491d2c)

```
Caused by: java.lang.ClassCastException: org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog cannot be cast to org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog

	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:75) ~[?:?]

```

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
jdbc {
compatible_mode = "starrocks"
}
```

### Running Command

```shell
rest api to submit job
```

### Error Exception

```log
Caused by: java.lang.ClassCastException: org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog cannot be cast to org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog

	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:75) ~[?:?]

```
```


### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
another thing we can improve is starrocks jdbc dialect use `md5sum_numeric` as hash function, maybe we can replace with `murmur_hash3_32`

**Comment by Hisoka-X** [comment]
We should fix it before 2.3.8 release.

**Comment by Hisoka-X** [comment]
How about change `StarRocksDialect`'s dialet name? For example: `Jdbc-StarRocks`. Because the name of all dialet come from `compatibleMode` is useless.

**Comment by liunaijie** [comment]
> How about change `StarRocksDialect`'s dialet name? For example: `Jdbc-StarRocks`. Because the name of all dialet come from `compatibleMode` is useless.

In my hot fix,  i delete the `StarRocksDialect` class's `dialectName` method implemention, then it will call parent `MysqlDialect` to create `MySqlCatalog`.

Change `StarRocksDialect` dialect name to `Jdbc-StarRocks` it need to create `Jdbc-StarRocks` catalog and extends `MysqlCatalog`

**Comment by Hisoka-X** [comment]
> > How about change `StarRocksDialect`'s dialet name? For example: `Jdbc-StarRocks`. Because the name of all dialet come from `compatibleMode` is useless.
> 
> In my hot fix, i delete the `StarRocksDialect` class's `dialectName` method implemention, then it will call parent `MysqlDialect` to create `MySqlCatalog`.
> 
> Change `StarRocksDialect` dialect name to `Jdbc-StarRocks` it need to create `Jdbc-StarRocks` catalog and extends `MysqlCatalog`

oh. You are right.
