### ISSUE TITLE
[Bug] [transforms] [SQL] SQL engine conditional query error

### ISSUE THREAD

**Issue by zhangshenghang** [apache/seatunnel#7552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

SQL engine conditional query error, when using the 'where name='abc' string equal to the query, it cannot take effect because of a logical judgment error.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
  job.name = "this_is_a_job_name"
  parallelism = 2
}

source {
  FakeSource {
    result_table_name = "fake"
    row.num = 10
    string.template = ['abc','d~f','hi']
    int.template = [20, 21]
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

transform {
    sql {
      source_table_name = "fake"
      result_table_name = "sql"
      query = "select * from "fake" where name = 'abc' "
    }

}

sink {
  Console {
     source_table_name = "sql"
     username = "seatunnel=2.3.1"
        password = "$a^b%c.d~e0*9("
    }
}
```

### Running Command

```shell
bin/seatunnel.sh
```

### Error Exception

```log
query error
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
I rember this can work before, do we know which pr has bug?

**Comment by liunaijie** [comment]
> I rember this can work before, do we know which pr has bug?

In version 2.3.5, this config can work.

```
env {
  job.mode = "BATCH"
  job.name = "this_is_a_job_name"
  parallelism = 2
}

source {
  FakeSource {
    result_table_name = "fake"
    row.num = 10
    string.template = ["abc","d~f","hi"]            ----  here need double quota
    int.template = [20, 21]
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

transform {
    sql {
      source_table_name = "fake"
      result_table_name = "sql"
      query = "select * from "fake" where name = 'abc' "
    }

}

sink {
  Console {
     source_table_name = "sql"
     username = "seatunnel=2.3.1"
        password = "$a^b%c.d~e0*9("
    }
}
```


But if the string.template value use single quota, it will get same issue.

**Comment by zhangshenghang** [comment]
Yes, I have identified this issue, which can also occur here. I will try to fix it
```
/ bin/seatunnel.sh -c <this_config_file> 
-i jobName='this_is_a_job_name' 
-i resName=fake 
-i rowNum=10 
-i strTemplate=['abc','d~f','hi'] 
-i nameType=string 
-i nameVal=abc 
-i username=seatunnel=2.3.1 
-i password='$a^b%c.d~e0*9(' 
-m local
```

**Comment by liunaijie** [comment]
> Yes, I have identified this issue, which can also occur here. I will try to fix it
> 
> ```
> / bin/seatunnel.sh -c <this_config_file> 
> -i jobName='this_is_a_job_name' 
> -i resName=fake 
> -i rowNum=10 
> -i strTemplate=['abc','d~f','hi'] 
> -i nameType=string 
> -i nameVal=abc 
> -i username=seatunnel=2.3.1 
> -i password='$a^b%c.d~e0*9(' 
> -m local
> ```

Hi, i noticed you using the variable replacement. 
now there has a known issue, the variable value can't has space.

like `-i nameVal='a bc'` , then we will only receive `nameVal=a`.
we can add quota on start script, but in `seatunnel.sh` when it run `java xxxx -i ` command, it will lose the quota.   FYR.

**Comment by zhangshenghang** [comment]
> > Yes, I have identified this issue, which can also occur here. I will try to fix it
> > ```
> > / bin/seatunnel.sh -c <this_config_file> 
> > -i jobName='this_is_a_job_name' 
> > -i resName=fake 
> > -i rowNum=10 
> > -i strTemplate=['abc','d~f','hi'] 
> > -i nameType=string 
> > -i nameVal=abc 
> > -i username=seatunnel=2.3.1 
> > -i password='$a^b%c.d~e0*9(' 
> > -m local
> > ```
> 
> Hi, i noticed you using the variable replacement. now there has a known issue, the variable value can't has space.
> 
> like `-i nameVal='a bc'` , then we will only receive `nameVal=a`. we can add quota on start script, but in `seatunnel.sh` when it run `java xxxx -i ` command, it will lose the quota. FYR.

- link https://github.com/apache/seatunnel/issues/6840

**Comment by zhangshenghang** [comment]
Use 
```
string.template=["abc", "d~f", "hi"]---- here need double quota
```
Can solve the problem, cannot use ' . 
Single quotation marks will be treated as strings
