### ISSUE TITLE
[Feature][zeta] Support Zeta Engine to distinguish between the master and worker process names.

### ISSUE THREAD

**Issue by gitfortian** [apache/seatunnel#7558]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support Zeta Engine to distinguish between the master and worker process names.  like SeatunnelMaster  SeatunnelWorker

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
+1

**Comment by dailai** [comment]
I can do it.

**Comment by dailai** [comment]
I did some research and found that you can see which is master just by  jcmd command. Like this:
![image](https://github.com/user-attachments/assets/70724238-0d5b-49e3-a8f5-140c90761367)
