### ISSUE TITLE
[Feature][Doc] Add icon for connectors

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7581]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add custom icons for our all connectors.
![image](https://github.com/user-attachments/assets/12ef769d-7fdf-4360-8795-007ab11a06c4)
https://seatunnel.apache.org/docs/connector-v2/source
Please refer https://github.com/facebook/docusaurus/discussions/10476#discussioncomment-10545432

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by zhangshenghang** [comment]
Can be assigned to me

**Comment by zhangshenghang** [comment]
@Hisoka-X 
The implementation method and effect are as follows. If there is no problem, I will start to modify it.
It will support the following three configurations: SVG, PNG, and Link.
e.g.
**svg**
<img width="439" alt="image" src="https://github.com/user-attachments/assets/59f3a0b8-8ee3-4de2-a44d-64644ddeb4f7">
**png**
<img width="421" alt="image" src="https://github.com/user-attachments/assets/82d9b2f5-afe0-4f03-bf3b-5ebe2ddcd9fc">
**link**
<img width="652" alt="image" src="https://github.com/user-attachments/assets/a29bfece-9843-4a8e-ac5b-a35c8944aa1c">

**effect**
<img width="405" alt="image" src="https://github.com/user-attachments/assets/bf609df1-5fb0-4fb6-951d-e57387d56916">

**Comment by Hisoka-X** [comment]
> @Hisoka-X The implementation method and effect are as follows. If there is no problem, I will start to modify it. It will support the following three configurations: SVG, PNG, and Link. e.g. **svg** <img alt="image" width="439" src="https://private-user-images.githubusercontent.com/29418975/365185694-59f3a0b8-8ee3-4de2-a44d-64644ddeb4f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzI2NzAsIm5iZiI6MTcyNTYzMjM3MCwicGF0aCI6Ii8yOTQxODk3NS8zNjUxODU2OTQtNTlmM2EwYjgtOGVlMy00ZGUyLWE0NGQtNjQ2NDRkZGViNGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjY1ZjhlMTJkZmJiZmRmY2JkOWFjYzk0YjBjNmNiNDU3ODljZGFhNDBjYWU3Y2U3YzkwMGFiODg5ZTM5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fdzq4HieH8xUmnEd-WatBfI13eroYKELdvWXfpywghw"> **png** <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/29418975/365185862-82d9b2f5-afe0-4f03-bf3b-5ebe2ddcd9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzI2NzAsIm5iZiI6MTcyNTYzMjM3MCwicGF0aCI6Ii8yOTQxODk3NS8zNjUxODU4NjItODJkOWIyZjUtYWZlMC00ZjAzLWJmM2ItNWViZTJkZGNkOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkN2M4OTM4NzE1OTEwZjQwMjMxZTAxZWNlYmM3ZWIxOGE3YzczNTZiMzJkODdlNDY2OGIzMDA3ZTEwOWQyNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vz3qxHEdbAN34kZbht42w2AI5_6EK_G_AX9eMaTPBT0"> **link** <img alt="image" width="652" src="https://private-user-images.githubusercontent.com/29418975/365186052-a29bfece-9843-4a8e-ac5b-a35c8944aa1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzI2NzAsIm5iZiI6MTcyNTYzMjM3MCwicGF0aCI6Ii8yOTQxODk3NS8zNjUxODYwNTItYTI5YmZlY2UtOTg0My00YThlLWFjNWItYTM1Yzg5NDRhYTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTYxODYyNzIwZDllY2FiYTQ0Y2Y3ODhiZTVkMzZjZTVjOTI4ZTgyNmMyNzYzZWFlODZmNzYzODUwMTAxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afha-Ve1yyGOwYxLgXUkK7A16wAvdEjUQ8dG8E-8HrI">
> 
> **effect** <img alt="image" width="405" src="https://private-user-images.githubusercontent.com/29418975/365187839-bf609df1-5fb0-4fb6-951d-e57387d56916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzI2NzAsIm5iZiI6MTcyNTYzMjM3MCwicGF0aCI6Ii8yOTQxODk3NS8zNjUxODc4MzktYmY2MDlkZjEtNWZiMC00ZmI2LTk1MWQtZTU3Mzg3ZDU2OTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZTBmMGM2ZjNhNWVjYTgyYmQzZjI5OThkNjg0MDdhNjU2NTA0MDE1NDA5YjIyYmFiYWY3Y2Q0Y2M0YjIwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xAa0abe8iHBAPUXDwsIZSSzkuvlm94vNxSc6sSBjHJ8">

Looking great! Thanks @zhangshenghang for the demo.
