### ISSUE TITLE
[Feature][connectors-v2][connector-file] Add support for reading and writing compressed files, such as tar.gz, zip, etc

### ISSUE THREAD

**Issue by wuchunfu** [apache/seatunnel#7587]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now it seems that our file connectors do not support reading compressed files, such as tar.gz, zip, and other types of files, and adding common types of compressed files for reading and writing

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgy-w** [comment]
Can be assigned to me temporarily

**Comment by corgy-w** [comment]
@wuchunfu #6826 I think binary can actually represent compressed files. should we distinguish them?

**Comment by wuchunfu** [comment]
> @wuchunfu #6826 I think binary can actually represent compressed files. should we distinguish them?

@corgy-w Binary seems impossible, so how to store a compressed file instead of just transferring it

**Comment by corgy-w** [comment]
Now there are two ways to achieve, hope express their views

1. in the case of not adding new types to support zip, etc., for example: there is text.zip is essentially a text file needs to be imported, parse the zip file can be
2. add a new type of suffix, reuse the processing logic of various formats, scalability is strong

Personally prefer the first option

**Comment by corgy-w** [comment]
> Now there are two ways to achieve, hope express their views
> 
> 1. in the case of not adding new types to support zip, etc., for example: there is text.zip is essentially a text file needs to be imported, parse the zip file can be
> 2. add a new type of suffix, reuse the processing logic of various formats, scalability is strong
> 
> Personally prefer the first option

Choose 1
