### ISSUE TITLE
Doesn't support SQLSERVER type 'UNIQUEIDENTIFIER' on column 'Id'

### ISSUE THREAD

**Issue by visiontk** [apache/seatunnel#7590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Doesn't support SQLSERVER type 'UNIQUEIDENTIFIER' on column 'Id'

### SeaTunnel Version

 apache-seatunnel-2.3.7 

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
}
source {
    Jdbc {
        driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
        url = "jdbc:sqlserver://ip;databaseName="
        user = "sa"
        password = ""
        query = "select top 100 * from  table where CreationTime> '${maxtime}' order by CreationTime"
    }
}
sink {
  jdbc {
    url = "jdbc:mysql://ip/?"
    driver = "com.mysql.cj.jdbc.Driver"
    user = ""
    password = ""
    generate_sink_sql = true
    database = ""
    table = ""
  }
}
```

### Running Command

```shell
null
```

### Error Exception

```log
08:51:05.155 [main] WARN org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource - get row type info exception

	org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Doesn't support SQLSERVER type 'UNIQUEIDENTIFIER' on column 'Id'  yet.

		at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlserverTypeMapper.mapping(SqlserverTypeMapper.java:130)

		at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.initTableField(JdbcSource.java:178)

		at
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Please assign it to me

**Comment by zhangshenghang** [comment]
Error `SqlserverTypeMapper.java:130`, does not exist in the code. This issue has been resolved.


Please confirm whether your version is correct.

- https://github.com/apache/seatunnel/pull/6122 
- [https://github.com/apache/seatunnel/blob/2.3.7-release/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/sqlserver/SqlserverTypeMapper.java](https://github.com/apache/seatunnel/blob/2.3.7-release/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect/sqlserver/SqlserverTypeMapper.java)
