### ISSUE TITLE
[Feature][Seatunnel-web]Add support to configure placeholder with default value in the job config.

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7599]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We have two options to replace placeholders with actual values:
1. During job execution, send the actual value to the seatunnel-engine, which will replace it before execution.
This way, the actual job executed won't be recorded in seatunnel-web history.
2. Replace the actual values in seatunnel-web before sending the job to the engine. This way, the actual executed job will be recorded in seatunnel-web history.

I propose the second option

### Usage Scenario

To support conditional query parameterisation

### Related issues

As part of blew jira similar feature is being added in seatunnel-engine
https://github.com/apache/seatunnel/pull/7562

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
How about we encrypt the configuration file content with Base64 and then implement this function through shell script?

I think hocon syntax is loose, and the advantage of this approach is that it can avoid many problems caused by escape.

seatunnel-web can be called directly through this method

e.g.

```shell
sh seatunnel.sh --web-config ZW52IHsKICBwYXJhbGxlbGlzbSA9IDEKICBqb2IubW9kZSA9ICJCQVRDSCIKfQoKc291cmNlIHsKICBGYWtlU291cmNlIHsKIC4uLi4KfQoKc2luayB7Ci4gLi4KfQ==
```

After base64 decryption：
```hocon
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
 ....
}

sink {
. ..
}
```

**Comment by arshadmohammad** [comment]
PR is merged https://github.com/apache/seatunnel-web/commit/70e526a2d38a4fe1243dc0e9d74edeb4f3826941
