### ISSUE TITLE
[Improvement][Seatunnel-client] Support executing jobs from job configure string instead of file.

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7600]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In seatunnel-web, fist job config is written to a file, then job is executed passing the file path.
Why can't we execute the job directly from the job config string? This will avoid writing the job config to file and managing the file.
Lets add this support to execute job directly from content.

### Usage Scenario

Seatunnle-web job execution scenario

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
If anybody interested, please feel free to work on this.

**Comment by zhangshenghang** [comment]
How about we encrypt the configuration file content with Base64 and then implement this function through shell script?

I think hocon syntax is loose, and the advantage of this approach is that it can avoid many problems caused by escape.

seatunnel-web can be called directly through this method

e.g.

```shell
sh seatunnel.sh --web-config ZW52IHsKICBwYXJhbGxlbGlzbSA9IDEKICBqb2IubW9kZSA9ICJCQVRDSCIKfQoKc291cmNlIHsKICBGYWtlU291cmNlIHsKIC4uLi4KfQoKc2luayB7Ci4gLi4KfQ==
```

After base64 decryption：
```hocon
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
 ....
}

sink {
. ..
}
```

**Comment by corgy-w** [comment]
> ```shell
> sh seatunnel.sh --web-config ZW52IHsKICBwYXJhbGxlbGlzbSA9IDEKICBqb2IubW9kZSA9ICJCQVRDSCIKfQoKc291cmNlIHsKICBGYWtlU291cmNlIHsKIC4uLi4KfQoKc2luayB7Ci4gLi4KfQ==
> ```
> 
> ```hocon
> env {
>   parallelism = 1
>   job.mode = "BATCH"
> }
> 
> source {
>   FakeSource {
>  ....
> }
> 
> sink {
> . ..
> }
> ```


I think this is a good idea, also,  converting to hocon via json is not currently supported for SDK，maybe can support it.

**Comment by arshadmohammad** [comment]
> How about we encrypt the configuration file content with Base64

Encryption is certainly important, but there's another issue at hand. 
Despite encrypting the data, if we're still writing the encrypted content to a file and then executing it, we're not fully addressing the problem. 

> sh seatunnel.sh --web-config

Utilising this from Java code may not be straightforward.


There should be an additional API in SeaTunnelClient, something similar to.
 public ClientJobExecutionEnvironment createExecutionContext(
            List<String> variables,
            @NonNull JobConfig jobConfig,
            @NonNull SeaTunnelConfig seaTunnelConfig,
            Long jobId, String jobConfigString)

@zhangshenghang, @corgy-w, what are your thoughts on this?

**Comment by corgy-w** [comment]
As far as I know, the purpose of writing the file is to restore the control of the task when it is fault tolerant. If the file is not written, I think it needs to be combined with other fault tolerant control @arshadmohammad 

oh, the jobstore is also dependent on the file, I think that if you completely discard the file need to simple design here

**Comment by arshadmohammad** [comment]
Thank you, @corgy-w, for your very informative response. 
The client (seatunnel-web) reads the content from a file and sends it to the server (Zeta Master). Since the client and server can be on different machines, the file path is irrelevant; only the content matters. I'll investigate further and see what we can do.
