### ISSUE TITLE
[Feature][Official Website]  new official Website.

### ISSUE THREAD

**Issue by wolfboys** [apache/seatunnel#764]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

we need a beautiful, atmospheric, contracted but not simple official website 😁✌️

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
@wolfboys https://github.com/apache/incubator-seatunnel-website#2-directory-structure 
Do pictures not discriminate between languages?
