### ISSUE TITLE
[Feature][Source & Sink] Support for VictoriaMetrics as Source and Sink

### ISSUE THREAD

**Issue by Wudadada** [apache/seatunnel#7644]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hi Seatunnel team,

I would like to request support for VictoriaMetrics as both a source and sink in Seatunnel. VictoriaMetrics is a fast and scalable time-series database commonly used for storing large amounts of monitoring data. Adding support for it as a source and sink would enable efficient data ingestion and export between Seatunnel and VictoriaMetrics, making it easier to integrate with existing monitoring and observability setups.

Here are some use cases where this integration could be useful:

	•	Ingesting data from VictoriaMetrics into Seatunnel for further processing.
	•	Exporting processed data back into VictoriaMetrics for long-term storage and analysis.

Thank you for considering this feature request! I believe it will enhance the flexibility and integration capabilities of Seatunnel.

Best regards

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CosmosNi** [comment]
This seems similar to Prometheus. Let me try

**Comment by CosmosNi** [comment]
#7265 look  VictoriaMetricsIT.It is compatible

**Comment by Wudadada** [comment]
> #7265 look VictoriaMetricsIT.It is compatible

Thanks a lot
