### ISSUE TITLE
[Bug][Seatunnel-web] download_datasource.sh fails due to missing mvnw command

### ISSUE THREAD

**Issue by chenyz1984** [apache/seatunnel#7653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Run the scripts `seatunnel-web/bin/download_datasource.sh`, report there is not mvnw in seatunnel-web directory.

The line of the error is:

```shell
"$SEATUNNEL_WEB_HOME"/mvnw dependency:get -DgroupId=org.apache.seatunnel -DartifactId="$i" -Dversion="$version" -Ddest="$DATASOURCE_DIR"
```

There is not mvnw in the SeaTunnel-Web binary package. The content of SeaTunnel-Web binary package:

```shell
[seatunnel@h142 apache-seatunnel-web]$ ls -l
total 72
drwxr-xr-x 2 seatunnel hadoop   104 Sep 13 14:11 bin
drwxr-xr-x 2 seatunnel hadoop   185 Sep 13 14:29 conf
drwxr-xr-x 2 seatunnel hadoop     6 Sep 13 12:38 datasource
-rw-r--r-- 1 seatunnel hadoop   552 Feb 18  2022 DISCLAIMER
drwxr-xr-x 2 seatunnel hadoop  8192 Sep 13 14:12 libs
-rw-r--r-- 1 seatunnel hadoop 32455 Feb 18  2022 LICENSE
drwxr-xr-x 3 seatunnel hadoop   317 Sep 13 11:53 licenses
drwxr-xr-x 2 seatunnel hadoop    60 Sep 13 14:05 logs
-rw-r--r-- 1 seatunnel hadoop 23737 Feb 18  2022 NOTICE
drwxr-xr-x 2 seatunnel hadoop   121 Sep 13 13:31 script
drwxr-xr-x 3 seatunnel hadoop    62 Sep 13 11:53 ui
```

### SeaTunnel Version

SeaTunnel-Web 1.0.1

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
`sh seatunnel-web/bin/download_datasource.sh`
```

### Error Exception

```log
Downloading datasource:  datasource-starrocks
bin/download_datasource.sh: line 69: /usr/hadoop/apache-seatunnel-web/mvnw: No such file or directory
datasource-mongodb
Downloading datasource:  datasource-mongodb
bin/download_datasource.sh: line 69: /usr/hadoop/apache-seatunnel-web/mvnw: No such file or directory
```

### Screenshots

![image](https://github.com/user-attachments/assets/38c6b45b-4520-4143-be71-bd6eb9d08bcd)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
I will submit PR for this

**Comment by arshadmohammad** [comment]
PR  https://github.com/apache/seatunnel-web/pull/227 was raised and it was merged.
https://github.com/apache/seatunnel-web/commit/fe098459285b9b266ed1ce866c5f2c1e9a71c024
