### ISSUE TITLE
[Feature][Framework] Translate Framework scala code to java

### ISSUE THREAD

**Issue by yx91490** [apache/seatunnel#766]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Translate Framework scala code to java, including modules:
- https://github.com/apache/incubator-seatunnel/issues/767
- https://github.com/apache/incubator-seatunnel/issues/1142
- https://github.com/InterestingLab/seatunnel/issues/798

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
maybe can split this task to some subtasks, anybody want to implement it? @wolfboys @leo65535 @wuchunfu @zixi0825

**Comment by leo65535** [comment]
+1, nice idea!

**Comment by wolfboys** [comment]
+1, nice idea, 
i am interested in `seatunnel-core`,`seatunnel-spark-api` modules, maybe i can try.😊

**Comment by wuchunfu** [comment]
`seatunnel-apis` and `seatunnel-flink-api` Module, no need to convert,  `seatunnel-spark-api`: https://github.com/InterestingLab/seatunnel/pull/742 and `seatunnel-common` Module, someone has already implemented it

**Comment by huzk8** [comment]
> 

can you help me  review for #742 ?

**Comment by huzk8** [comment]
> `seatunnel-apis` and `seatunnel-flink-api` Module, no need to convert, `seatunnel-spark-api`: #742 and `seatunnel-common` Module, someone has already implemented it

can you help me  review for #742 ?

**Comment by yx91490** [comment]
> > `seatunnel-apis` and `seatunnel-flink-api` Module, no need to convert, `seatunnel-spark-api`: #742 and `seatunnel-common` Module, someone has already implemented it
> 
> can you help me review for #742 ?

Sorry, I can review it sometime, but I don't have permission to merge code, maybe you can call @garyelephant @RickyHuo @CalvinKirs.
besides I don't think it's worth to translate plugin modules scala code.

**Comment by CalvinKirs** [comment]
> > > `seatunnel-apis` and `seatunnel-flink-api` Module, no need to convert, `seatunnel-spark-api`: #742 and `seatunnel-common` Module, someone has already implemented it
> > 
> > 
> > can you help me review for #742 ?
> 
> Sorry, I can review it sometime, but I don't have permission to merge code, maybe you can call @garyelephant @RickyHuo @CalvinKirs. besides I don't think it's worth to translate plugin modules scala code.

yup, I think the plugins  not need limit the language, and for the kernel module, we use Java uniformly.

**Comment by zixi0825** [comment]
> > > > `seatunnel-apis` and `seatunnel-flink-api` Module, no need to convert, `seatunnel-spark-api`: #742 and `seatunnel-common` Module, someone has already implemented it
> > > 
> > > 
> > > can you help me review for #742 ?
> > 
> > 
> > Sorry, I can review it sometime, but I don't have permission to merge code, maybe you can call @garyelephant @RickyHuo @CalvinKirs. besides I don't think it's worth to translate plugin modules scala code.
> 
> yup, I think the plugins not need limit the language, and for the kernel module, we use Java uniformly.

I agree with you

**Comment by leo65535** [comment]
> yup, I think the plugins not need limit the language, and for the kernel module, we use Java uniformly.

Agree, plugins should not be limited.
