### ISSUE TITLE
[Improve][Doc] icon  display problem

### ISSUE THREAD

**Issue by zhangshenghang** [apache/seatunnel#7663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/a7076ad3-8515-4821-9f46-606f6d36ad1e)

The current icon configuration cannot read the images in the `docs/images` directory
```
sidebar_custom_props:
link:img:image/apache.ico
```
<img width="244" alt="image" src="https://github.com/user-attachments/assets/bec388ac-5bae-48d9-937b-4b0cf76bb7aa">

Maybe it's because the icon image is not converted to a link when it is loaded
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/6ec13665-da7c-4c26-8ec6-ca16b2c9b4cc">

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/50c443e6-e79a-46cd-9762-e8dd539753e9">

### SeaTunnel Version

seatunnel-web

### SeaTunnel Config

```conf
---
sidebar_custom_props:
  link: img:images/apache.ico
---
```

### Running Command

```shell
None
```

### Error Exception

```log
None
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Currently only absolute paths are supported, not relative paths.
- link https://github.com/apache/seatunnel-website/pull/334

**Comment by Hisoka-X** [comment]
fixed by https://github.com/apache/seatunnel-website/pull/335
