### ISSUE TITLE
[Feature][seatunnel-engine] Rest-api supports querying job run logs by jobId

### ISSUE THREAD

**Issue by youshaojun** [apache/seatunnel#7689]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Rest-api supports querying job run logs [`logs/seatunnel-starter-client-xxx.log`] by jobId.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
duplicated of #7724
