### ISSUE TITLE
[Feature][Zeta] Support automatic delete of completed task log files 

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#7716]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Current, zeta support creating log files for each job, #7712

But because the logging framework cannot get the job status, it cannot automatically delete completed job log files.

Therefore, we can add a scheduled task to automatically delete the completed job logs.

Requirements:
1. Check regularly every day, use corn expression configuration, users can change the configuration, and it is executed every night by default
2. The log file can no longer find the unfinished job status (running/savepoint)
3. The log file has not been updated for 30 days, and users can change the configuration
4. add testcase check this feature
5.add docs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgy-w** [comment]
can be assigned to me :>

**Comment by corgy-w** [comment]
### Implementation

Configured cron-related settings through `st.yaml` and implemented scheduled log cleanup using `ScheduledExecutorService` during server startup.

### Issue

Configuration Retrieval

I tried to obtain the value of `appender.routing.route.job.appender.fileName = ${file_path}/job-${ctx:ST-JID}.log` from the `log4j2.properties` file, but I was unable to retrieve it, or I couldn't find the correct way to access it.
![image](https://github.com/user-attachments/assets/5f790380-b520-4f6e-88ea-69cb722bb5b1)
