### ISSUE TITLE
[Feature][Zeta][Core] Add support for accessing job execution output log files through an API.

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7724]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As part of https://github.com/apache/seatunnel/pull/7712, job execution logs will now be available in a separate file on the SeaTunnel engine. Provide an option to retrieve this file through an API, enabling seamless integration with SeaTunnel-web.

### Usage Scenario

End users will interact exclusively with SeaTunnel-web, without direct access to the SeaTunnel engine. Displaying logs in SeaTunnel-web will enable them to debug and investigate issues effectively.

### Related issues

https://github.com/apache/seatunnel/pull/7712

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Please assign it to me, I will complete it

**Comment by zhangle910522** [comment]
When will the plan be completed

**Comment by Hisoka-X** [comment]
closed by #7818
