### ISSUE TITLE
[Bug] [Transform V2] DynamicCompile compilation error in version 2.3.7

### ISSUE THREAD

**Issue by cmx-ops** [apache/seatunnel#7740]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I initially planned to use SQL to deduplicate data, but it currently does not support group by aggregation, and using distinct has no effect. Then I found out that I could use DynamicCompile to code and process the data, but the Java code I wrote for data deduplication does not compile successfully, and I don't know where the problem lies.

my code:
```java
import org.apache.seatunnel.api.table.catalog.Column;
import org.apache.seatunnel.transform.common.SeaTunnelRowAccessor;
import org.apache.seatunnel.api.table.catalog.CatalogTable;
import org.apache.seatunnel.api.table.catalog.PhysicalColumn;
import org.apache.seatunnel.api.table.type.BasicType;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

public class DeduplicationTransform {
    // 使用一个集合来存储已经见过的组合键
    private Set<String> uniqueRows = new HashSet<String>();

    public Column[] getInlineOutputColumns(CatalogTable inputCatalogTable) {
        ArrayList<Column> columns = new ArrayList<Column>();
        // 复制原始列
        columns.add(PhysicalColumn.of("name", BasicType.STRING_TYPE, 255, true, "", ""));
        columns.add(PhysicalColumn.of("age", BasicType.INT_TYPE, 10, true, "", ""));
        columns.add(PhysicalColumn.of("gender", BasicType.STRING_TYPE, 50, true, "", ""));
        return columns.toArray(new Column[0]);
    }

    public Object[] getInlineOutputFieldValues(SeaTunnelRowAccessor inputRow) {
        // 创建一个组合键，包含 name, age, gender
        String compositeKey = inputRow.getString("name") + "#" + inputRow.getInt("age") + "#" + inputRow.getString("gender");
        
        // 检查这个组合键是否已经出现过
        if (uniqueRows.add(compositeKey)) {
            Object[] fieldValues = new Object[3];
            fieldValues[0] = inputRow.getString("name");
            fieldValues[1] = inputRow.getInt("age");
            fieldValues[2] = inputRow.getString("gender");
            return fieldValues;
        } else {
            // 如果这行数据已经出现过，返回 null 或者空数组
            return null;
        }
    }
}
```

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
# 数据转换：使用 SQL 进行去重
transform {
 DynamicCompile {
  source_table_name = "csv_data"
  result_table_name = "csv_data_output"
  compile_language = "JAVA"
  compile_pattern = "ABSOLUTE_PATH"
  absolute_path="""/home/reformer/apache_seaTunnel/dynamic_compile_code/DeduplicationTransform.java"""
 }
}

# 数据输出：输出到控制台
#sink {
#  Console {
#    source_table_name = "csv_data_output"
#  }
#}

sink {
  LocalFile {
    path = "/home/reformer/apache_seaTunnel/localfile/test_local_file_output"
    file_format_type = "csv"
    field_delimiter = ","
    schema {
      fields {
        name = string
        age = int
        gender = string
      }
    }
    compress_codec = "none"
    encoding = "UTF-8"
  }
}
```

### Running Command

```shell
./start-seatunnel-spark-2-connector-v2.sh --master local[4] --deploy-mode client --config ../config/local_file_source_distinct_by_code.conf
```

### Error Exception

```log
Caused by: org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMPILE_TRANSFORM_ERROR_CODE-01], ErrorDescription:[CompileTransform error please check code] - org.apache.seatunnel.shade.org.codehaus.commons.compiler.CompileException: Line 21, Column 15: Assignment conversion not possible from type "java.lang.Object[]" to type "org.apache.seatunnel.api.table.catalog.Column[]"
        at org.apache.seatunnel.transform.dynamiccompile.DynamicCompileTransform.getOutputColumns(DynamicCompileTransform.java:89)
        at org.apache.seatunnel.transform.common.MultipleFieldOutputTransform.transformTableSchema(MultipleFieldOutputTransform.java:67)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.transformCatalogTable(AbstractCatalogSupportTransform.java:64)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.getProducedCatalogTable(AbstractCatalogSupportTransform.java:54)
        at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.sparkTransform(TransformExecuteProcessor.java:143)
        at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:119)
        ... 16 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look

**Comment by liunaijie** [comment]
in you code, you use `inputRow.getString("name")`, which version you are use? 
in 2.3.7, it only support `getField(int index)` method, return an object.

**Comment by cmx-ops** [comment]
> hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look

That is to say, my code is incorrect and cannot be written this way; it only supports simple transformations and does not support aggregation or deduplication operations.

**Comment by liunaijie** [comment]
> > hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look
> 
> That is to say, my code is incorrect and cannot be written this way; it only supports simple transformations and does not support aggregation or deduplication operations.



Hi, base my understand, DynamicCompile is not support `Filter` data. @jackyyyyyssss please correct me if i am wrong.


If you want filter the duplicated data, you can do like this:
1. use `DynamicalCompile` transform, add a flag column.
2. use `Sql` transform to filter that flag mark as duplicated.

**Comment by cmx-ops** [comment]
> > > hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look
> > 
> > 
> > That is to say, my code is incorrect and cannot be written this way; it only supports simple transformations and does not support aggregation or deduplication operations.
> 
> Hi, base my understand, DynamicCompile is not support `Filter` data. @jackyyyyyssss please correct me if i am wrong.
> 
> If you want filter the duplicated data, you can do like this:
> 
> 1. use `DynamicalCompile` transform, add a flag column.
> 2. use `Sql` transform to filter that flag mark as duplicated.

I tried using the DynamicCompiler Transform method you mentioned, intending to add a new field to each row of data as an identifier for data duplication, but this could not be achieved. Because I cannot define a common collection to store the existing row data.
，Here is my code:
```java
    private Set<String> uniqueRows = new HashSet<>();
    public Column[] getInlineOutputColumns(CatalogTable inputCatalogTable) {

        ArrayList<Column> columns = new ArrayList<Column>();
        PhysicalColumn destColumn =
                PhysicalColumn.of(
                        "duplicate",
                        BasicType.STRING_TYPE,
                        10,
                        true,
                        "",
                        "");
        return new Column[]{
                destColumn
        };

    }

    public Object[] getInlineOutputFieldValues(SeaTunnelRowAccessor inputRow) {
        Object field0 = inputRow.getField(0);
        Object field1 = inputRow.getField(1);
        Object field2 = inputRow.getField(2);

        String compositeKey = field0 + "#" + field1 + "#" + field2;
        boolean isNew = uniqueRows.add(compositeKey);
        Object[] fieldValues = new Object[1];
        if (!isNew){
            fieldValues[0] ="duplicate";
        }else {
            fieldValues[0] ="no";
        }
        return fieldValues;
    }
```

**Comment by liunaijie** [comment]
> > > > hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look
> > > 
> > > 
> > > That is to say, my code is incorrect and cannot be written this way; it only supports simple transformations and does not support aggregation or deduplication operations.
> > 
> > 
> > Hi, base my understand, DynamicCompile is not support `Filter` data. @jackyyyyyssss please correct me if i am wrong.
> > If you want filter the duplicated data, you can do like this:
> > 
> > 1. use `DynamicalCompile` transform, add a flag column.
> > 2. use `Sql` transform to filter that flag mark as duplicated.
> 
> I tried using the DynamicCompiler Transform method you mentioned, intending to add a new field to each row of data as an identifier for data duplication, but this could not be achieved. Because I cannot define a common collection to store the existing row data. ，Here is my code:
> 
> ```java
>     private Set<String> uniqueRows = new HashSet<>();
>     public Column[] getInlineOutputColumns(CatalogTable inputCatalogTable) {
> 
>         ArrayList<Column> columns = new ArrayList<Column>();
>         PhysicalColumn destColumn =
>                 PhysicalColumn.of(
>                         "duplicate",
>                         BasicType.STRING_TYPE,
>                         10,
>                         true,
>                         "",
>                         "");
>         return new Column[]{
>                 destColumn
>         };
> 
>     }
> 
>     public Object[] getInlineOutputFieldValues(SeaTunnelRowAccessor inputRow) {
>         Object field0 = inputRow.getField(0);
>         Object field1 = inputRow.getField(1);
>         Object field2 = inputRow.getField(2);
> 
>         String compositeKey = field0 + "#" + field1 + "#" + field2;
>         boolean isNew = uniqueRows.add(compositeKey);
>         Object[] fieldValues = new Object[1];
>         if (!isNew){
>             fieldValues[0] ="duplicate";
>         }else {
>             fieldValues[0] ="no";
>         }
>         return fieldValues;
>     }
> ```


What do you mean:
> Because I cannot define a common collection to store the existing row data.


You has defined `Set<String> uniqueRows` to store it. The code looks good to me, is there anything wrong?

When you add this transfrom, the output data should has one more column, named `duplicate`.  
And you need set this transform `parallelism` to 1 to ensure only one `Set` to check the data duplicate.

**Comment by cmx-ops** [comment]
> > > > > hi, i update the DynamicCompile Document recently https://github.com/apache/seatunnel/pull/7730/files, you can take a look
> > > > 
> > > > 
> > > > That is to say, my code is incorrect and cannot be written this way; it only supports simple transformations and does not support aggregation or deduplication operations.
> > > 
> > > 
> > > Hi, base my understand, DynamicCompile is not support `Filter` data. @jackyyyyyssss please correct me if i am wrong.
> > > If you want filter the duplicated data, you can do like this:
> > > 
> > > 1. use `DynamicalCompile` transform, add a flag column.
> > > 2. use `Sql` transform to filter that flag mark as duplicated.
> > 
> > 
> > I tried using the DynamicCompiler Transform method you mentioned, intending to add a new field to each row of data as an identifier for data duplication, but this could not be achieved. Because I cannot define a common collection to store the existing row data. ，Here is my code:
> > ```java
> >     private Set<String> uniqueRows = new HashSet<>();
> >     public Column[] getInlineOutputColumns(CatalogTable inputCatalogTable) {
> > 
> >         ArrayList<Column> columns = new ArrayList<Column>();
> >         PhysicalColumn destColumn =
> >                 PhysicalColumn.of(
> >                         "duplicate",
> >                         BasicType.STRING_TYPE,
> >                         10,
> >                         true,
> >                         "",
> >                         "");
> >         return new Column[]{
> >                 destColumn
> >         };
> > 
> >     }
> > 
> >     public Object[] getInlineOutputFieldValues(SeaTunnelRowAccessor inputRow) {
> >         Object field0 = inputRow.getField(0);
> >         Object field1 = inputRow.getField(1);
> >         Object field2 = inputRow.getField(2);
> > 
> >         String compositeKey = field0 + "#" + field1 + "#" + field2;
> >         boolean isNew = uniqueRows.add(compositeKey);
> >         Object[] fieldValues = new Object[1];
> >         if (!isNew){
> >             fieldValues[0] ="duplicate";
> >         }else {
> >             fieldValues[0] ="no";
> >         }
> >         return fieldValues;
> >     }
> > ```
> 
> What do you mean:
> 
> > Because I cannot define a common collection to store the existing row data.
> 
> You has defined `Set<String> uniqueRows` to store it. The code looks good to me, is there anything wrong?
> 
> When you add this transfrom, the output data should has one more column, named `duplicate`. And you need set this transform `parallelism` to 1 to ensure only one `Set` to check the data duplicate.

The `uniqueRows` set is being re-initialized for each row of data, so the size of `uniqueRows` is always 1.

**Comment by cmx-ops** [comment]
![image](https://github.com/user-attachments/assets/fa38b80f-579c-499f-8f4c-04deade1f7c7)
![image](https://github.com/user-attachments/assets/d8e3899d-9222-44cb-9ef1-69139d07fda6)

**Comment by jackyyyyyssss** [comment]
Because this object is not singleton, you cannot obtain the value of the shared variable. You can use third-party storage to maintain this state, such as Redis. Even if it is singleton, it may be distributed in different nodes, so writing it is not possible. It requires parallelism of 1+static

**Comment by cmx-ops** [comment]
> Because this object is not singleton, you cannot obtain the value of the shared variable. You can use third-party storage to maintain this state, such as Redis. Even if it is singleton, it may be distributed in different nodes, so writing it is not possible. It requires parallelism of 1+static

"Okay, I understand.thank you！"

**Comment by YYChildren** [comment]
How I Get CatalogTable in method 'getInlineOutputFieldValues'

**Comment by lovatti** [comment]
Hi!

Same problem here...

How to get the CatalogTable or get the field names and types in getInlineOutputFieldValues.

Did you find the solution?

Thank you!

**Comment by liunaijie** [comment]
@YYChildren @lovatti 
Hi, the method `getInlineOutputFieldValues ` can't get the table info and field info as the input parameter only save the field value.


But you can get table info and field info from method `getInlineOutputColumns`. Maybe you can try get the info you wanted from this method and save into a variable. (I am not sure it can be work, but you can try it)

**Comment by liunaijie** [comment]
@YYChildren @lovatti 

Hi, the method `getInlineOutputFieldValues ` can't get the table info and field into.

You can get them from `getInlineOutputColumns` store it into a variable and access it from `getInlineOutputFieldValues` method

**Comment by lovatti** [comment]
Thank you!

I'll try it.

Appreciate if you share an example.

Is it possible to share in the same java block code or do I need to store in Redis?

Bruno
