### ISSUE TITLE
[Feature][transforms-v2] Support append only stream from cdc source

### ISSUE THREAD

**Issue by dailai** [apache/seatunnel#7756]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a new transform which can transform cdc row to append  only row that contains the cdc rowkind or other needed info.

Example:
CDC row:  +D 1, test1, test2
new Row: +I 1,test1,test2,DELETE

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hawk9821** [comment]
I am willing to submit a PR!  Please assign it to me

**Comment by Carl-Zhou-CN** [comment]
> I am willing to submit a PR! Please assign it to me

ok，Thanks for your contributions, and thanks to @dailai   for the great idea
