### ISSUE TITLE
[Bug] [Seatunnel-web] No value found for placeholder : [transactionId]

### ISSUE THREAD

**Issue by shashwatsai** [apache/seatunnel#7808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

While working on contributing to seatunnel-web HDFS datasource interface, on saving the source-sink config, using HTTP POST

```
curl 'http://seatunnel-host.company.com:8801/seatunnel/api/v1/job/dag/15216283007968' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://seatunnel-host.company.com:8801' \
  -H 'Referer: http://seatunnel-host.company.com:8801/ui/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  -H 'token: eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6MiwidHlwZSI6MCwic3RhdHVzIjowLCJpYXQiOjE3Mjg1NDA2MTksImV4cCI6MTcyODYyNzAxOX0.Mj-cEWbwUhOUUb-k_MQsa2nJTBiHh_JxLXA-g5qID5Q' \
  --data-raw '{"edges":[{"inputPluginId":"17283730097821j8","targetPluginId":"17284533967521hy"}]}' \
  --insecure
  ```
  
  We are getting following error:
 ```
 {
    "code": 99994,
    "msg": "No value found for placeholder: [transactionId]",
    "data": null,
    "failed": true,
    "success": false
}
```

In the JobUtils#replaceJobConfigPlaceholders, we are trying to replace all the placeholder, in case hdfs, ${transactionId} is used as a placeholder in connection-file-hadoop implementation while creating files in Sink. 

The issue was observed while working on https://github.com/apache/seatunnel/issues/7767

### SeaTunnel Version

**seatunnel**: 2.3.7
**seatunnel-web**: 1.0.1

### SeaTunnel Config

```conf
Happens during saving the HDFS source-sink DAG.
```

### Running Command

```shell
1. Navigate to seatunnel-web deployment.
2. create an HDFS DAG, with HDFS as sink. 
3. Fails with No value found for placeholder : [transactionId]
```

### Error Exception

```log
{
    "code": 99994,
    "msg": "No value found for placeholder: [transactionId]",
    "data": null,
    "failed": true,
    "success": false
}
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shashwatsai** [comment]
CC: @arshadmohammad

**Comment by arshadmohammad** [comment]
We should add a mechanism to escape placeholders. This will ensure the placeholder values are not replaced, but instead, passed to the engine as they are

**Comment by shashwatsai** [comment]
https://github.com/apache/seatunnel/issues/7767 must be handled first.

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/225
