### ISSUE TITLE
PostgresSQL and PostgresSQL CDC connector does not support the “inet” data type

### ISSUE THREAD

**Issue by douglli** [apache/seatunnel#7817]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

PostgresSQL and PostgresSQL CDC connectors support inet data  type 
  

### Usage Scenario

  I encountered an error when reading PostgresSQL table data using the PostgresSQL CDC connector. 
  There is an inet type field in my table,and the error message reads: ['Postgres' tables unsupported get catalog table, the corresponding field types in the following tables are not supported: '{"nsc. public. audit": {"ip": "inet"}']. 
  Upon checking the source code, I found that the PostgresTypeConverter class does not support the data type "inet".

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CosmosNi** [comment]
yeah,no inet type.Is there any problem with converting to string?

**Comment by douglli** [comment]
No problem, that's exactly what I did.
