### ISSUE TITLE
[Feature][dependencies structure] move plugin dependencies from seatunnel-core to seatunnel-dist

### ISSUE THREAD

**Issue by yx91490** [apache/seatunnel#782]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

seatunnel-core is the core framework of this project, it should only depends on abstract but detail, but currently seatunnel-core depends all plugins in pom.xml, which is not a good design, whenever we add a plugin we should modify seatunnel-core's pom.xml.
so how about move plugin dependencies from seatunnel-core to seatunnel-dist to make sure all things work well, then we should solve how to run seatunnel in  Idea, maybe we can create a new module 'seatunnel-standalone' to solve it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by timothy1024** [comment]
hi, it seems we can not remove these dependencies, we will need them when we add unit tests.

**Comment by timothy1024** [comment]
hi, it seems we can not remove these dependencies, we will need them when we add unit tests.

**Comment by yx91490** [comment]
> hi, it seems we can not remove these dependencies, we will need them when we add unit tests.

I think plugin's UT should locate in their own module.
