### ISSUE TITLE
seatunnel-web也应该来个docker的

### ISSUE THREAD

**Issue by FN20200222** [apache/seatunnel#7850]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

seatunnel-web也应该来个docker的

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cobolbaby** [comment]
Although seatunnel-web provides a [Docker build script](https://github.com/apache/seatunnel-web/blob/main/build.sh), it would be even better if the official team could provide image maintenance.
