### ISSUE TITLE
[Improvement][Zeta] jetty port issue

### ISSUE THREAD

**Issue by corgy-w** [apache/seatunnel#7868]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/89d80a70-73fd-4e93-8c9a-bec4ba9783bd">

When deploying multiple nodes on a single machine, is there a better way to configure this port?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgy-w** [comment]
cc @liugddx

**Comment by liugddx** [comment]
Currently it is fixed. We can change the jetty port to a dynamic range binding

**Comment by liugddx** [comment]
Already fixed by #7903
