### ISSUE TITLE
[Feature][Connector-Redis]Support redis sink to write custom key and value 

### ISSUE THREAD

**Issue by lm-ylj** [apache/seatunnel#7884]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When I use Redis as a Sink, I encountered the following problems:
1.Redis keys cannot be customized. If a custom key is generated during the Transform phase, this additional field will be introduced in the value
For example, the expected key to be written is pay:pay_channel:{order_no}, and the data for order_no comes from upstream
2.Currently, only the entire JSON data can be written, and it cannot support writing a specific field value or specifying a fixed value
For example, the expected value to be written to Redis is {order_no}, rather than the entire JSON data

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FuYouJ** [comment]
你的场景我有点不明白，有没有具体的配置案例看一下

**Comment by lm-ylj** [comment]
假设上游数据是：
order_no  |  pay_channel  |  pkg
1111        |  wxpay           |  aaa
2222        |  alipay            |  bbb
我的场景是：期望存入Redis的key是pay:{pay_channel}:{order_no}，value为{pkg}，即存入的数据为
pay:wxpay:1111  |  aaa
pay:alipay:2222   |  bbb
另外还有Hash结构的场景，例如存入的数据期望是：
key                      | hashKey | hashValue
pay:pay_channel | wxpay     | aaa
pay:pay_channel | alipay     | bbb
总的来说，就是期望Redis Sink写入的Key和Value更加灵活，能够由用户指定

**Comment by FuYouJ** [comment]
> 假设上游数据是： order_no | pay_channel | pkg 1111 | wxpay | aaa 2222 | alipay | bbb 我的场景是：期望存入Redis的key是pay:{pay_channel}:{order_no}，value为{pkg}，即存入的数据为 pay:wxpay:1111 | aaa pay:alipay:2222 | bbb 另外还有Hash结构的场景，例如存入的数据期望是： key | hashKey | hashValue pay:pay_channel | wxpay | aaa pay:pay_channel | alipay | bbb 总的来说，就是期望Redis Sink写入的Key和Value更加灵活，能够由用户指定

理解你的业务场景了
