### ISSUE TITLE
[Bug] [Postgres-CDC] 使用 CDC 进行同步的时候，Flink 任务总会显示处于背压状态

### ISSUE THREAD

**Issue by cobolbaby** [apache/seatunnel#7901]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用 CDC 进行同步的时候，Flink 任务总会显示处于背压状态。但总共运行了几个小时也没几条测试数据。

### SeaTunnel Version

2.3.x

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=400
}

source {
  Postgres-CDC {
    # 源端数据库 JDBC Url
    result_table_name = "ITC_PG_DAuth_CDC"
    username = "***"
    password = "***"
    database-names = ["ITCDAuth"]
    schema-names = ["public"]
    table-names = ["ITCDAuth.public.account_login_log", "ITCDAuth.public.ldap_sync_accout"]
    base-url = "jdbc:postgresql://****/ITCDAuth"
  }
}

transform {

}

sink {
  jdbc {
    # https://seatunnel.apache.org/docs/2.3.8/connector-v2/sink/Jdbc
    source_table_name = "ITC_PG_DAuth_CDC"
    url = "jdbc:postgresql://***/ITCDAuth"
    driver = "org.postgresql.Driver"
    user = "***"
    password = "***"

    # You need to configure both database and table
    database = "ITCDAuth"
    table = "${schema_name}.${table_name}"
    primary_keys = ["${primary_key}"]
    schema_save_mode = "IGNORE"
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-15-connector-v2.sh --config /opt/tasks/examples/pgcdc2pg_dauth.conf
```

### Error Exception

```log
无
```

### Zeta or Flink or Spark Version

Flink: 1.18.1

### Screenshots

![seatunnel-debug2](https://github.com/user-attachments/assets/486033c6-efc8-4513-b175-12a1b2bea184)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MurderWind** [comment]
哥们，我也遇到了这个问题，请问你最后怎么解决的啊

**Comment by cobolbaby** [comment]
没解决，然后 issue 就关了，看着活跃的社区，貌似社区都没人做解答

**Comment by MurderWind** [comment]
> 没解决，然后 issue 就关了，看着活跃的社区，貌似社区都没人做解答

这个官方也是厉害
