### ISSUE TITLE
[Feature][RestAPI] Support submit job with seatunnel style hocon format config

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7925]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At now, user only can use json format to submit job with rest api. But json format not fisrt choice in SeaTunnel. We should support submit job with seatunnel style hocon format in rest api.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CosmosNi** [comment]
i want try,can be assigned to me
