### ISSUE TITLE
[Feature][Jdbc] Add Jdbc default dialect for all jdbc series database without dialect

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7956]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We should add Jdbc default dialect for all jdbc series database without dialect, when some jdbc url not match our dialect in https://github.com/apache/seatunnel/tree/dev/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/internal/dialect, it can use default dialect not throw an exception.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BranGao19** [comment]
对的，kettle或者datax都有这个功能的，这不是什么新东西了

**Comment by sunxiaojian** [comment]
@Hisoka-X  please assign it to me
