### ISSUE TITLE
[Bug] [Klaviyo DOC] The link in the Klaviyo document has been 404

### ISSUE THREAD

**Issue by YOMO-Lee** [apache/seatunnel#7968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I was about to submit a PR, I was stuck in Dead Links and one of the links in the Klaviyo connector document has become invalid and is currently in 404 status

### SeaTunnel Version

NULL

### SeaTunnel Config

```conf
NULL
```

### Running Command

```shell
NULL
```

### Error Exception

```log
404
```

### Screenshots

![image](https://github.com/user-attachments/assets/973e8eb9-9dca-49bc-a1c6-98c4c2d03320)
![image](https://github.com/user-attachments/assets/fb62d78c-2e66-456c-83e1-337f4eac6468)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YOMO-Lee** [comment]
assign to me

**Comment by davidzollo** [comment]
Please update to this link `https://developers.klaviyo.com/en/reference/api_overview`

**Comment by Hisoka-X** [comment]
closed by #7969
