### ISSUE TITLE
[Feature][Zeta] Add jar path precheck when job submit on master

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#7970]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When job submit for client with logicplan and jar path info to master node, we should add jar path precheck on master and worker. To make sure all connector and dependency can be load normally to avoid throw unexpected exception happend.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
cc @zhangshenghang

**Comment by zhangshenghang** [comment]
Please assign it to me，thks
