### ISSUE TITLE
job在设置为流处理模式情况下，kafka-source不会根据group-offset进行自动消费，

### ISSUE THREAD

**Issue by sj15600520109** [apache/seatunnel#7971]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

创建了一个job，设置为流处理模式，kafka-source设置为group-offset模式，首次会把当前topic里未消费的message进行消费，消费完成后，我通过生产者又生产了消息，但此时job状态一直为running状态，但不会消费消息了，是设置的问题吗？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sj15600520109** [comment]
在相同的conf文件下，我换成了2.3.7版本的环境就可以正常消费，2.3.8版本应该存在bug

**Comment by liunaijie** [comment]
> 在相同的conf文件下，我换成了2.3.7版本的环境就可以正常消费，2.3.8版本应该存在bug

Yes, 2.3.8 Kafka connector has some bug, This pr will fix it https://github.com/apache/seatunnel/pull/7871
