### ISSUE TITLE
mysql to doris, report this error, Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8040 [/127.0.0.1] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by FN20200222** [apache/seatunnel#7999]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql to doris, report this error, Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8040 [/127.0.0.1] failed: Connection refused (Connection refused)
![doris](https://github.com/user-attachments/assets/13ba4cdb-e6b7-49f6-bf06-6d852eab138d)

### SeaTunnel Version

docker 2.3.8

### SeaTunnel Config

```conf
docker run --rm -it -v F:\volume\seatunnel\config:/config apache/seatunnel:2.3.8 ./bin/seatunnel.sh -m local -c /config/mysqlcdc_doris.conf
```

### Running Command

```shell
docker run --rm -it -v F:\volume\seatunnel\config:/config apache/seatunnel:2.3.8 ./bin/seatunnel.sh -m local -c /config/mysqlcdc_doris.conf
```

### Error Exception

```log
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8040 [/127.0.0.1] failed: Connection refused (Connection refused)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
When create bug, please attach your config file.


This error is the docker container can't connect to doris. You set the doris address to `127.0.0.1`? 
You need update the doris url to the right address and make sure container can connect to doris.

**Comment by FN20200222** [comment]
> When create bug, please attach your config file.
> 
> This error is the docker container can't connect to doris. You set the doris address to `127.0.0.1`? You need update the doris url to the right address and make sure container can connect to doris.

env {
	parallelism = 1
	job.mode = "STREAMING"
	checkpoint.interval = 10000
}

source {
	MySQL-CDC {
		base-url = "jdbc:mysql://10.3.51.209:3306/test"
		username = "root"
		password = "FN920127_z"
		table-names = ["test.tab_user"]

		startup.mode = "initial"
	}
}

sink {
	Doris {
		fenodes = "10.3.51.209:8030"
		username = root
		password = ""
		database = "test"
		table = "e2e_table_sink"
		sink.label-prefix = "test-cdc"
		sink.enable-2pc = "true"
		sink.enable-delete = "true"
		doris.config {
			format = "json"
			read_json_by_line = "true"
		}
	}
}

**Comment by FN20200222** [comment]
how to set seatunnel docker doris ip address

**Comment by liunaijie** [comment]
> > When create bug, please attach your config file.
> > This error is the docker container can't connect to doris. You set the doris address to `127.0.0.1`? You need update the doris url to the right address and make sure container can connect to doris.
> 
> env { parallelism = 1 job.mode = "STREAMING" checkpoint.interval = 10000 }
> 
> source { MySQL-CDC { base-url = "jdbc:mysql://10.3.51.209:3306/test" username = "root" password = "FN920127_z" table-names = ["test.tab_user"]
> 
> ```
> 	startup.mode = "initial"
> }
> ```
> 
> }
> 
> sink { Doris { fenodes = "10.3.51.209:8030" username = root password = "" database = "test" table = "e2e_table_sink" sink.label-prefix = "test-cdc" sink.enable-2pc = "true" sink.enable-delete = "true" doris.config { format = "json" read_json_by_line = "true" } } }

Are you sure you are using this config to submit job?  The error message show you are setting doris fenodes to `127.0.0.1:8040`

**Comment by hawk9821** [comment]
@FN20200222   please refer to the DorisE2E initializeBE method .

**Comment by KawYang** [comment]
sink.enable-2pc = "true" It seems that you need to access the node of doris be, 8040 is the port of be

**Comment by FN20200222** [comment]
> sink.enable-2pc = "true" It seems that you need to access the node of doris be, 8040 is the port of be

how to set

> > > When create bug, please attach your config file.
> > > This error is the docker container can't connect to doris. You set the doris address to `127.0.0.1`? You need update the doris url to the right address and make sure container can connect to doris.
> > 
> > 
> > env { parallelism = 1 job.mode = "STREAMING" checkpoint.interval = 10000 }
> > source { MySQL-CDC { base-url = "jdbc:mysql://10.3.51.209:3306/test" username = "root" password = "FN920127_z" table-names = ["test.tab_user"]
> > ```
> > 	startup.mode = "initial"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > sink { Doris { fenodes = "10.3.51.209:8030" username = root password = "" database = "test" table = "e2e_table_sink" sink.label-prefix = "test-cdc" sink.enable-2pc = "true" sink.enable-delete = "true" doris.config { format = "json" read_json_by_line = "true" } } }
> 
> Are you sure you are using this config to submit job? The error message show you are setting doris fenodes to `127.0.0.1:8040`

这个是找不到doris，seatunnel默认会找127.0.0.1:8040，怎么设置正确的doris服务地址

**Comment by FN20200222** [comment]
> > > When create bug, please attach your config file.
> > > This error is the docker container can't connect to doris. You set the doris address to `127.0.0.1`? You need update the doris url to the right address and make sure container can connect to doris.
> > 
> > 
> > env { parallelism = 1 job.mode = "STREAMING" checkpoint.interval = 10000 }
> > source { MySQL-CDC { base-url = "jdbc:mysql://10.3.51.209:3306/test" username = "root" password = "FN920127_z" table-names = ["test.tab_user"]
> > ```
> > 	startup.mode = "initial"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > sink { Doris { fenodes = "10.3.51.209:8030" username = root password = "" database = "test" table = "e2e_table_sink" sink.label-prefix = "test-cdc" sink.enable-2pc = "true" sink.enable-delete = "true" doris.config { format = "json" read_json_by_line = "true" } } }
> 
> Are you sure you are using this config to submit job? The error message show you are setting doris fenodes to `127.0.0.1:8040`

它为什么会找8040端口，配置了8030端口还不够吗

**Comment by KawYang** [comment]
@FN20200222 我开始用docker-compose 部署的doris，be的端口是内部ip，会提示这个错误，后来我重新部署了doris，把be的ip换成宿主机的IP，并把端口开放出来就好了。但是我没找到配置be端口的地方。而且我发现  sink.enable-2pc = "true"  会报这个错误

**Comment by FN20200222** [comment]
> @FN20200222 我开始用docker-compose 部署的doris，be的端口是内部ip，会提示这个错误，后来我重新部署了doris，把be的ip换成宿主机的IP，并把端口开放出来就好了。但是我没找到配置be端口的地方。而且我发现 sink.enable-2pc = "true" 会报这个错误

**Comment by FN20200222** [comment]
@KawYang 你的意思，我把be的ip换成宿主机IP，把端口开放出来，并且把sink.enable-2pc = "true"这个设置去掉就可以是吗

**Comment by KawYang** [comment]
@FN20200222 我测着是 sink.enable-2pc = "true" 才会访问be，你可以改成false试试，或者 把be的ip换成宿主机IP映射出来。不知道是bug 还是就是设计的这样
