### ISSUE TITLE
[Feature][Transform] Multi-table transform

### ISSUE THREAD

**Issue by Ivan-gfan** [apache/seatunnel#8006]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I would like to request the ability to configure field mapping relationships for specific tables or a subset of tables during multi-table synchronization.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please track #7628
