### ISSUE TITLE
[Bug] [seatunnel-web] can't build seatunnel-web project

### ISSUE THREAD

**Issue by susanbushisan** [apache/seatunnel#8051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The error occurs when I build seatunnel-web, and I'm guessing that the front-end component code is causing the problem

### SeaTunnel Version

1.0.3-SNAPSHOT

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
/build.sh code
```

### Error Exception

```log
Running 'npm run build:prod' in D:\project\personal\seatunnel-web\seatunnel-web-dist\..\seatunnel-ui
[INFO] 
[INFO] > seatunnel-ui@0.0.0 build:prod
[INFO] > vue-tsc --noEmit && vite build --mode production
[INFO]
[INFO] src/views/task/synchronization-definition/dag/sidebar/index.tsx(75,34): error TS2322: Type '{ width: string; height: string; }' is not assignable to type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
[INFO]   Property 'width' does not exist on type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
[INFO] src/views/task/synchronization-definition/dag/sidebar/index.tsx(91,35): error TS2322: Type '{ width: string; height: string; }' is not assignable to type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
[INFO]   Property 'width' does not exist on type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
[INFO] src/views/task/synchronization-definition/dag/sidebar/index.tsx(136,41): error TS2322: Type '{ width: string; height: string; }' is not assignable to type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
[INFO]   Property 'width' does not exist on type 'IntrinsicAttributes & { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ref_key?: string | undefined; ... 7 more ...; style?: unknown; }'.
```

### Screenshots

![image](https://github.com/user-attachments/assets/4da07e78-6de0-4900-b7eb-0cf6008a2e2a)
![image](https://github.com/user-attachments/assets/b7919052-dfd8-4434-a7de-f03b32c11ffb)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by susanbushisan** [comment]
https://github.com/apache/seatunnel-web/pull/241 this is PR

**Comment by windyYangShu** [comment]
![屏幕截图 2024-12-06 100253](https://github.com/user-attachments/assets/d02b8a39-f2d6-41cf-915d-7b881a7453a0)
i have encountered a similar problem and solved it in the following way: change `strict: true`  to `strict: false` in tsconfig.json.

**Comment by susanbushisan** [comment]
> ![屏幕截图 2024-12-06 100253](https://private-user-images.githubusercontent.com/51824698/393064770-d02b8a39-f2d6-41cf-915d-7b881a7453a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzIzMjksIm5iZiI6MTczMzczMjAyOSwicGF0aCI6Ii81MTgyNDY5OC8zOTMwNjQ3NzAtZDAyYjhhMzktZjJkNi00MWNmLTkxNWQtN2I4ODFhNzQ1M2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4MTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzIwMDQ1ODY2MWFiOTE2OTA5MTNkMzE5ZWQ4NWI0MmQ3NDMwMjI3OGQyMGYxMDYxMDYyMDMzMjhiNTk5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SjT6cTaszx0SF5bwy0uMK23Ybk5MaYr4w9i67DLPCkk) i have encountered a similar problem and solved it in the following way: change `strict: true` to `strict: false` in tsconfig.json.

thank for your solution, but i hope build without code change, now my PR is merged for improve
