### ISSUE TITLE
[Feature][Rest-API] Add token authentication when calling API

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#8096]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add token authentication when calling API

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuzhengz** [comment]
cc

**Comment by liunaijie** [comment]
Hi @Xuzhengz How do the ST server verify the token is right or not, base on what's information? 
Is there need a api to generate the token first, if yes, same question how and base on what's information? Do we need import other components?
