### ISSUE TITLE
[Bug] [org/apache/seatunnel/shade/com/typesafe/config/impl/ConfigParser.java] java: 不兼容的类型: com.typesafe.config.ConfigIncluder无法转换为org.apache.seatunnel.shade.com.typesafe.config.ConfigIncluder

### ISSUE THREAD

**Issue by yaoquanxin** [apache/seatunnel#8104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I download the source code of dev. find something problem that I can`t solve，I guess that a bug of org.apache.seatunnel.shade.com.typesafe.config.Config.（https://github.com/apache/seatunnel/discussions/1043）
The following are my questions：
![image](https://github.com/user-attachments/assets/5393bc70-9605-48b1-8172-642f8e353cc1)
I have the confuse of the class:  org/apache/seatunnel/shade/com/typesafe/config/impl/ConfigParser.java

that`s no problem ？  I remember Have a hot fix of the class(org/apache/seatunnel/shade/com/typesafe/config/impl/ConfigParser.java) 
but, why i can`t run my code in my PC？
it`s my configuration.
![image](https://github.com/user-attachments/assets/ff41e929-0f90-4861-9db4-5872dfc23d2b)

I try it：mvn clean install, but  can`t solve it.

### SeaTunnel Version

our seatunnel version is 2.3.8

### SeaTunnel Config

```conf
in my question of sreenshot
```

### Running Command

```shell
no
```

### Error Exception

```log
java: 不兼容的类型: com.typesafe.config.ConfigIncluder无法转换为org.apache.seatunnel.shade.com.typesafe.config.ConfigIncluder
```

### Java or Scala Version

1.8

### Screenshots

![image](https://github.com/user-attachments/assets/dae5abaa-f018-4b1a-99de-4138994bc854)
![image](https://github.com/user-attachments/assets/96b6d397-3f3a-419f-b07b-35a17c5c6365)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yaoquanxin** [comment]
i guess something of  BUG in branch of dev. I try again：sh ./mvnw clean install -DskipTests -Dskip.spotless=true

![image](https://github.com/user-attachments/assets/fdefad76-51a0-4275-b1d2-88a07404b912)

**Comment by yaoquanxin** [comment]
I try 2.3.8 and 2.3.5 , I can`t run it in my pc ,always have the problem.
com.typesafe.config.ConfigIncluder无法转换为org.apache.seatunnel.shade.com.typesafe.config.ConfigIncluder.

**Comment by hailin0** [comment]
try `./mvnw install -Dmaven.test.skip`

**Comment by yaoquanxin** [comment]
> try `./mvnw install -Dmaven.test.skip`

oh,my big bro , that look no use。  our seatunnel source code can work well in local PC?  OR that a bug for run seatunnel source code in local PC? I try it again,again,again, but it look so upset.
![image](https://github.com/user-attachments/assets/d5b769b9-491b-4f51-8b94-63da33a53955)
Our company is looking forward to use seatunnel in production environment，could you help me?  big bro~

**Comment by yaoquanxin** [comment]
> try `./mvnw install -Dmaven.test.skip`

if you in china, may be we can exchange wehat and discuss in depth the question.xue`s snacks NEED YOU. It`s my we chat:18770170039

**Comment by yaoquanxin** [comment]
thanks for bigbro to solving the proble. why we meet the question? because window enviroment will cut out maven command.

在 Windows 环境下，命令行解析器（如 CMD 或 PowerShell）对命令的解析可能导致参数被截断或错误解释。具体到你的问题中，-D 后面的内容可能由于解析器对符号 . 的处理不当而被误解析。

错误根本原因：
Maven将.test.skip 解释为i一个生命周期阶段（lfiecycle phase）,由于命令解释器错误地分割-D后面的内容,导致它变成了无效参数.

解决方案：
step1: 将拉取下来的代码回滚 rollback（可以全部回滚的，亲测）
step2:
./mvnw install  -Dmaven.test.skip=true
更改为：
./mvnw install  '-Dmaven.test.skip=true'
并在在控制台输入.
