### ISSUE TITLE
[Bug] [connector-jdbc] ChunkSplitter class generateSplits method: The catalogTable in the JdbcSourceTable table object does not obtain the primary key

### ISSUE THREAD

**Issue by shuihua777** [apache/seatunnel#8154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

debug find that method [getCatalogTable(ResultSetMetaData metadata,BiFunction<ResultSetMetaData, Integer, Column> columnConverter,String sqlQuery)):CatalogTable] 

The TableSchema in the created CatalogTable object does not assign a PrimaryKey object value, resulting in the ChunkSplitter class generateSplits method JdbcSourceTable object having no primary key value

![image](https://github.com/user-attachments/assets/ce8abd27-2ec9-4d24-81be-6c6aa94c0ece)

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  job.mode = BATCH
  job.name = "SeaTunnel"
  spark.executor.instances = 1
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source{
jdbc {
  driver = "com.mysql.cj.jdbc.Driver"
  url = "jdbc:mysql://xxxxxx:3307/xxxxx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false"
  user = "xxxxxxx"
  password = "xxxxxxxx"
  query = "select id,xxxx from xxx.xxxxxxx"
#   partition_column = "id"
  split.size = 8096
 }
}
transform {
}
sink {
  Console {
      parallelism = 2
    }
}
```

### Running Command

```shell
seatunnel-spark-connector-v2-example
SeaTunnelApiExample class
```

### Error Exception

```log
no exception
```

### Zeta or Flink or Spark Version

spark

### Java or Scala Version

java 1.8
scala 2.11.12

### Screenshots

![image](https://github.com/user-attachments/assets/ce8abd27-2ec9-4d24-81be-6c6aa94c0ece)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunxiaojian** [comment]
Not use `query = "select id,xxxx from xxx.xxxxxxx"`, use `table_path`
