### ISSUE TITLE
[Improve][Connector-V2] Save data savemode operation when schema savemode created new table

### ISSUE THREAD

**Issue by Hisoka-X** [apache/seatunnel#8156]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, in our `DefaultSaveModeHandler`, `handleSchemaSaveMode` and `handleDataSaveMode` are separated. Imagine a situation where a new table is created in `handleSchemaSaveMode`, we do not need to execute the truncate of the table data in `handleDataSaveMode`, but the data will still to be truncated at now. Therefore, we should skip the execution of some `handleDataSaveMode` after `handleSchemaSaveMode` determines that a new table has created.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangshenghang** [comment]
Please assign it to me
