### ISSUE TITLE
[Feature][Connector-V2] Support the jdbc connector for highgo db

### ISSUE THREAD

**Issue by SimonChou12138** [apache/seatunnel#8280]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

New jdbc connector for highgo db.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ichenfeiyang** [comment]
<img width="824" height="270" alt="Image" src="https://github.com/user-attachments/assets/e21d199a-2d8b-461c-b400-85faff1a1080" />

<img width="1567" height="397" alt="Image" src="https://github.com/user-attachments/assets/da99db9e-32e7-45b4-9b09-ac68651e342b" />

When I use JDBC to connect to the HighGo database, the URL contains the database information, but when it executes, the URL does not include the database information.
