### ISSUE TITLE
[Feature][K8S deploy] add helm chart

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#8283]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add helm chart to help deploy seatunnel on K8S

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FrommyMind** [comment]
Plase assign to me.

**Comment by flyrun9527** [comment]
helm安装后 开启ingress true 报错 这个报错啥原因啊

        * Ingress in version "v1" cannot be handled as a Ingress: v1.Ingress.Spec: v1.IngressSpec.Rules: []v1.IngressRule: v1.IngressRule.IngressRuleValue: HTTP: v1.HTTPIngressRuleValue.Paths: []v1.HTTPIngressPath: v1.HTTPIngressPath.Backend: v1.IngressBackend.Service: v1.IngressServiceBackend.Port: v1.ServiceBackendPort.Name: ReadString: expects " or n, but found 5, error found in #10 byte of ...|:{"name":5801}}},"pa|..., bigger context ...|rvice":{"name":"seatunnel-master","port":{"name":5801}}},"path":"/","pathType":"Prefix"}]}}]}}
|...

**Comment by flyrun9527** [comment]
找到问题了 ingress.yaml中 其中port: name 应该是port: number
应该是
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            service:
              name: {{ include "seatunnel.fullname" . }}-master
              port:
                number: 5801
