### ISSUE TITLE
[DISCUSS] Data consistency related discuss

### ISSUE THREAD

**Issue by wolfboys** [apache/seatunnel#834]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

At present, the underlying engines for data integration in SeaTunnel is spark and flink. The data consistency is also guaranteed by the consistency of spark|flink itself.

As we all know, spark is not ideal in terms of data consistency. The general processing method requires users to maintain the offset by themselves, or at least once + idempotence to ensure that, the various connectors implemented by SeaTunnel based on spark have no relevant processing in this area.

Flink uses the distributed snapshot algorithm + two-phase submission to better solve this problem. In version 1.4.0, the TwoPhaseCommitSinkFunction interface is introduced, which encapsulates the two-phase submission logic, so that data consistency is effectively guaranteed, but there is no in SeaTunnel. Implement the TwoPhaseCommitSinkFunction interface. Therefore, I think SeaTunnel has not been resolved on the issue of data consistency, and it is necessary for us to start relevant discussions.

### SeaTunnel Version

2.0.4

### SeaTunnel Config

```conf
--
```

### Running Command

```shell
--
```

### Error Exception

```log
--
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xtr1993** [comment]
this discuss is very nice!
I think seatunnel as a etl tool，Data consistency is very important. now i have a few suggestions for seatunnel ：
1. for offline etl scenes,for example mysql binlog to doris, when job is restarted,we usually start from scratch or start from specified binlog data,This is so troublesome.
2. for streaming etl scenes, for example kafka using flink streaming to doris，when job is restarted,flink can use checkpoint to exactly-once,but some scenes,user wants specify kafka offset.
Above problems In the case of job restart，do you need to maintain a recent offset？This can ensure that the user does not need to recalculate and ensure that the offset can be specified flexibly when the task is restarted.
