### ISSUE TITLE
[Feature][plugin-spark-sink-clickhouse] always select replica that "replica_num = 1" when insert data into table,even it is down

### ISSUE THREAD

**Issue by zqrainracp** [apache/seatunnel#841]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

导入数据到clickhouse内多副本表时，总会选择副本编号为1的副本节点，即使节点挂掉而其他副本还可用，是否可以修改为随机选择
以下为修改建议：

    val sql =
      s"SELECT cluster,shard_num,shard_weight,groupArray(1)(host_address)[1] " +
      s"AS host_address from (SELECT  cluster, shard_num, shard_weight, host_address " +
      s"FROM system.clusters WHERE cluster = '$cluster' ORDER BY rand()) GROUP BY cluster,shard_num,shard_weight"

### SeaTunnel Version

1.5.5

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config config/hive_to_clickhouse.conf
```

### Error Exception

```log
连接节点失败
```

### Flink or Spark Version

2.4.7

### Java or Scala Version

1.8

### Screenshots

![image](https://user-images.githubusercontent.com/23446592/146864588-0147362f-7cbc-4994-997f-550240c4ba61.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
> 导入数据到clickhouse内多副本表时，总会选择副本编号为1的副本节点，即使节点挂掉而其他副本还可用，是否可以修改为随机选择

Nice idea! you can try to improve it by yourself.

**Comment by dpchenxk** [comment]
i want to fix this bug, can assign to me ?
