### ISSUE TITLE
[Feature][build] Use mvnd to increase build speed

### ISSUE THREAD

**Issue by wuchunfu** [apache/seatunnel#866]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I think we can use `mvnd` to speed up the build, This project aims at providing faster `Maven` builds using techniques known from `Gradle` and `Takari` .

This is the project address

```bash
https://github.com/apache/maven-mvnd
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
@wuchunfu Hi, any update of this?

**Comment by wuchunfu** [comment]
`mvnd` seems to be unstable at the moment, need to wait and see.

**Comment by wuchunfu** [comment]
> @wuchunfu Hi, any update of this?

`mvnd` seems to be unstable at the moment, need to wait and see
