### ISSUE TITLE
[Feature][transform] Type conversion of the specified field

### ISSUE THREAD

**Issue by wuchunfu** [apache/seatunnel#895]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Type conversion of the specified field

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
One convert transform can deal with multiple field could be better.

**Comment by wuchunfu** [comment]
> One convert transform can deal with multiple fields could be better.

Agree with you, I will realize it.
