### ISSUE TITLE
[Discuss][plugin] unify the format of parameters in plugins

### ISSUE THREAD

**Issue by zixi0825** [apache/seatunnel#932]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now I find that the formats of parameters in our plugins are quite diverse，the formats as follow : 
- producer.bootstrap.servers
- batch_size
- customUpdateStmt

I think we should unify the format of parameters in plugins, and wo can choose a format from follow

1. batch.size
2. batch_size
3. batchSize

And everyone can vote and choose the appropriate format 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
I approve your suggestion, but better to keep backward compatibility when make adjustments.

**Comment by CalvinKirs** [comment]
I very much agree with you, and I prefer to use the second one. If everyone is sure later, I suggest that the plug-in configuration submitted in the current version can be reformatted again. (The old version is temporarily not used)

**Comment by huangxianxin** [comment]
I very much agree with you, and I prefer to use the second one, ( batch_size)

**Comment by YangCH0915** [comment]
Get used to the second one，( batch_size)

**Comment by leo65535** [comment]
Prefer to `producer.bootstrap.servers` 😄

**Comment by zixi0825** [comment]
I think the first format will be better. At present, most connector parameters use the first format. We can use this format with less conversion and more general and mainstream. So I prefer to first one (producer.bootstrap.servers).
