### ISSUE TITLE
[Bug] [Doc] Some pictures or link on the official website are lost

### ISSUE THREAD

**Issue by cdmikechen** [apache/seatunnel#942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I opened the document connection of the web page, I found that the links of some pictures on the page could not be accessed. 
Link: <https://interestinglab.github.io/seatunnel-docs/#/zh-cn/v2/>

At the same time, I click `quick start` on the home page, but it doesn't jump to the corresponding page.

### SeaTunnel Version

V2

### SeaTunnel Config

```conf
No
```

### Running Command

```shell
No
```

### Error Exception

```log
No
```

### Flink or Spark Version

No

### Java or Scala Version

No

### Screenshots

![image](https://user-images.githubusercontent.com/12069428/147995077-4b06d0f4-4b8c-48fe-b376-b060274d3c81.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cdmikechen** [comment]
@stale No it is still unseen.

**Comment by cdmikechen** [comment]
@liunaijie it is still useen, pleas reopen this issue

**Comment by liunaijie** [comment]
> @liunaijie it is still useen, pleas reopen this issue

Hi @cdmikechen , the seatunnel offical website is update to https://seatunnel.apache.org/
