### ISSUE TITLE
[Feature][package] Optimize the package name of plugin

### ISSUE THREAD

**Issue by charlesy6** [apache/seatunnel#947]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

`SeaTunnel` project put all plugins in a same package, it seems not a good way, it can easily cause class conflicts. 
It's better to put different plugins into their own packages, like

```
org.apache.seatunnel.connector.flink.console.sink
org.apache.seatunnel.connector.flink.doris.sink
org.apache.seatunnel.connector.flink.fake.sink
org.apache.seatunnel.connector.flink.druid.sink
org.apache.seatunnel.connector.flink.jdbc.sink
org.apache.seatunnel.connector.flink.jdbc.source
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
I agree with you, even if he looks good now.
