### ISSUE TITLE
[DISCUSS]Unified DSL Design(alternatives HOCON, SQL, JSON, YAML ...

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#964]

**Comment by xtr1993** [comment]
I always pay attention to DSL issues and  have implemented a way to parse DSL into SQL
![98dada7e25eb9749a54fcd30a918d6d](https://user-images.githubusercontent.com/38655011/148509512-63e1c97f-347e-4d7d-bd8d-0c02518c52e7.png)
I defined a set of SQL rules myself, including Prjection.Sort,Filter,Group Operators;

**Comment by AaronLinOops** [comment]
Why not design the DSL around SQL？

**Comment by ainusers** [comment]
您好，这边可以参考您这个编写解析SQL语句的项目嘛？
