### ISSUE TITLE
[Feature][SparkPlugin] add neo4j sink

### ISSUE THREAD

**Issue by an-shi-chi-fan** [apache/seatunnel#968]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add neo4j sink to write data to neo4j

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuangjiang** [comment]
we have developed the neo4j sink plugin before:
The difficulty lies in how to generate the relationship. It is easy to develop a plug-in separately

**Comment by an-shi-chi-fan** [comment]
i am a user of nebula , it is also a graph db , there is good tool named of nebula exchange. i have use it to import data to nebula for many times so i wang to have a try. @yuangjiang

**Comment by dailidong** [comment]
Please submit your pr, thx
by the way,  you can have another issue for the nebula if you want to contribute source or sink plugin

**Comment by an-shi-chi-fan** [comment]
i will have a try in my free time, and submit after it was done
